CREATE PROC [dbo].[AXP_AA] AS
BEGIN
 IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
 IF OBJECT_ID('tempdb..#LEAD') IS NOT NULL
  DROP TABLE #LEAD
   IF OBJECT_ID('tempdb..#LLEAD') IS NOT NULL
  DROP TABLE #LLEAD
     IF OBJECT_ID('tempdb..#LLLEAD') IS NOT NULL
  DROP TABLE #LLLEAD

 SELECT A.PartyId,LastMovement,A.ReportsTo,MAX(START_DT) START_DT,IS_CURRENT,T.TeamNo,T.TeamNoReference,T.Name TeamName,Manager into #LEAD FROM DLKHDIM..DIM_AGENT A
INNER JOIN SGTM_TEAM T ON A.ReportsTo=T.PartyId WHERE LastMovement IN ('App','Tran','Chan','Prom') 
--and A.PartyId='100020'
GROUP BY LastMovement,A.ReportsTo,IS_CURRENT,T.TeamNo,T.Name,A.PartyId,Manager,T.TeamNoReference

select L.* INTO #LLLEAD from #LEAD L INNER JOIN (select max(START_DT) START_DT,IS_CURRENT,PartyId from #LEAD group by IS_CURRENT,PartyId) LL ON L.PartyId=LL.PartyId AND L.START_DT=LL.START_DT AND L.IS_CURRENT=LL.IS_CURRENT

select L.PartyId,L.LastMovement,L.ReportsTo ReportsTo1,L.TeamNo TeamNo1,A.Surname+' '+ISNULL(A.Forename2,A.Forename1) ManagerName2,L.Manager Manager2,T1.TeamNo TeamNo2,TT.TeamNo TeamNo3,TT.Manager Manager3,
A1.Surname+' '+ISNULL(A1.Forename2,A1.Forename1) ManagerName3,MAX(cast(IS_CURRENT as int)) IS_CURRENT into #LLEAD from #LLLEAD L
INNER JOIN SGTM_TEAM T ON L.ReportsTo=T.PartyId
INNER JOIN SGTM_TEAM TT ON T.ReportsTo=TT.PartyId
INNER JOIN SGTM_TEAM T1 ON TT.Manager=T1.Manager AND T1.TeamType IN ('U','O','R')
INNER JOIN SGTM_AGENT A ON A.PartyId=L.Manager
INNER JOIN SGTM_AGENT A1 ON A1.PartyId=TT.Manager
--where TT.name like '%ABM%'

group by L.PartyId,L.LastMovement,L.ReportsTo,L.TeamNo,L.Manager,T.ReportsTo,T.TeamNo,TT.Manager,TT.TeamNo,T1.TeamNo,A.Surname,A.Forename2,A.Forename1,A1.Surname,A1.Forename2,A1.Forename1

SELECT AGENT_KEY,P.POL_KEY,VC.CLI_KEY,VC.CLIIND_KEY,P.POL_ID,P.POL_APP_FORM_ID,P.PLAN_ID,PA.ETBL_DESC_TXT PLAN_NAME,V.SURNAME+' '+ISNULL(ISNULL(V.NAME2,V.NAME1),'') AGENT_NAME,VC.ENTR_SUR_NM ENTR_SUR_NM,VC.ENTR_GIV_NM ENTR_GIV_NM,P.POL_APP_RECV_DT CS_REV_DT,P.POL_CREAT_DT PRO_LOAD_DT,P.POL_INFC_DT POL_ISS_DT,
C.CVG_MPREM_AMT,p.POL_BILL_MODE_CD,C.CVG_MPREM_AMT*(CASE WHEN CAST(POL_BILL_MODE_CD AS INT)>0 THEN 12/CAST(POL_BILL_MODE_CD AS INT)
ELSE 1 END) AS AFYP,P.POL_CSTAT_CD,PARA.DM_AV_DESC_TXT,C.CVG_FACE_AMT CVG_SUM_INS_AMT,POL_PREM_PAY_DUR,AGT_ID AGENT_CODE,W.POL_AGT_SHR_PCT,CSC_CODE
,CVG_ME_FCT,C.CVG_MPREM_AMT-CVG_ME_PREM_AMT PRE_BEFORE,C.CVG_MPREM_AMT PRE_AFTER
 INTO #TMP FROM DLKHDIM..DIM_POLICY P INNER JOIN DLKHDIM..DIM_POLICY_CLIENT PC ON P.POL_ID=PC.POL_ID AND P.IS_CURRENT=1 AND PC.IS_CURRENT=1 AND PC.POL_CLI_REL_SUB_CD='P'
INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1
INNER JOIN V_CLI_INFO VC ON  VC.CLI_ID=PC.CLI_ID
INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
INNER JOIN V_AGENT_INFO V ON V.PARTY_ID=AGT_ID
LEFT JOIN SGTB_EDITTABLE PA ON P.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN'
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD'

--INSERT INTO  DLKHFACT..FACT_AXP_AA
SELECT AGENT_KEY,POL_KEY,CLI_KEY,CLIIND_KEY,POL_ID,POL_APP_FORM_ID,PLAN_ID,PLAN_NAME,AGENT_NAME,ENTR_SUR_NM,ENTR_GIV_NM,CS_REV_DT,PRO_LOAD_DT,POL_ISS_DT,SUM(CVG_MPREM_AMT) CVG_MPREM_AMT,POL_BILL_MODE_CD,SUM(AFYP) AFYP,POL_CSTAT_CD,DM_AV_DESC_TXT,SUM(CVG_SUM_INS_AMT) CVG_SUM_INS_AMT,
POL_PREM_PAY_DUR,AGENT_CODE,POL_AGT_SHR_PCT,CSC_CODE,CVG_ME_FCT,SUM(PRE_BEFORE) PRE_BEFORE,SUM(PRE_AFTER) PRE_AFTER,CASE WHEN POL_BILL_MODE_CD='06' THEN SUM(CVG_MPREM_AMT)/2 ELSE SUM(CVG_MPREM_AMT) END WFYP,
LL.Manager2 PCODE,LL.TeamNo1 PUNIT,LL.ManagerName2 PNAME,LL.TeamNo2 PAUNIT,LL.Manager3 PManager,LL.ManagerName3 PABM,L.Manager2 LCODE,L.TeamNo1 LUNIT,L.ManagerName2 LNAME,L.TeamNo2 LAUNIT,L.Manager3 LManager,L.ManagerName3 LABM FROM #TMP T
LEFT JOIN #LLEAD L ON T.AGENT_CODE=L.PartyId AND L.IS_CURRENT=1
LEFT JOIN #LLEAD LL ON T.AGENT_CODE=LL.PartyId AND LL.IS_CURRENT=0
GROUP BY AGENT_KEY,POL_KEY,CLI_KEY,CLIIND_KEY,POL_ID,PLAN_ID,PLAN_NAME,ENTR_SUR_NM,ENTR_GIV_NM,CS_REV_DT,PRO_LOAD_DT,POL_ISS_DT,POL_BILL_MODE_CD,DM_AV_DESC_TXT,
POL_PREM_PAY_DUR,AGENT_CODE,POL_AGT_SHR_PCT,CSC_CODE,POL_CSTAT_CD,POL_BILL_MODE_CD,POL_APP_FORM_ID,AGENT_NAME,CVG_ME_FCT,
LL.Manager2 ,LL.TeamNo1 ,LL.ManagerName2 ,LL.TeamNo2 ,LL.Manager3 ,LL.ManagerName3 ,L.Manager2 ,L.TeamNo1 ,L.ManagerName2 ,L.TeamNo2 ,L.Manager3 ,L.ManagerName3

END
