CREATE proc [dbo].[compro] @START DATE,@END DATE
AS
 IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
 IF OBJECT_ID('tempdb..#LEAD') IS NOT NULL
  DROP TABLE #LEAD
   IF OBJECT_ID('tempdb..#LLEAD') IS NOT NULL
  DROP TABLE #LLEAD
     IF OBJECT_ID('tempdb..#LLLEAD') IS NOT NULL
  DROP TABLE #LLLEAD

 SELECT A.PartyId,LastMovement,A.ReportsTo,MAX(START_DT) START_DT,IS_CURRENT,T.TeamNo,T.TeamNoReference,T.Name TeamName,Manager into #LEAD FROM DLKHDIM..DIM_AGENT A
INNER JOIN SGTM_TEAM T ON A.ReportsTo=T.PartyId WHERE LastMovement IN ('App','Tran','Chan','Prom') 
--and A.PartyId='100020'
GROUP BY LastMovement,A.ReportsTo,IS_CURRENT,T.TeamNo,T.Name,A.PartyId,Manager,T.TeamNoReference

select L.* INTO #LLLEAD from #LEAD L INNER JOIN (select max(START_DT) START_DT,IS_CURRENT,PartyId from #LEAD group by IS_CURRENT,PartyId) LL ON L.PartyId=LL.PartyId AND L.START_DT=LL.START_DT AND L.IS_CURRENT=LL.IS_CURRENT

select L.PartyId,L.LastMovement,L.ReportsTo ReportsTo1,L.TeamNo TeamNo1,A.Surname+' '+ISNULL(A.Forename2,A.Forename1) ManagerName2,L.Manager Manager2,T1.TeamNo TeamNo2,TT.TeamNo TeamNo3,TT.Manager Manager3,
A1.Surname+' '+ISNULL(A1.Forename2,A1.Forename1) ManagerName3,MAX(cast(IS_CURRENT as int)) IS_CURRENT into #LLEAD from #LLLEAD L
INNER JOIN SGTM_TEAM T ON L.ReportsTo=T.PartyId
INNER JOIN SGTM_TEAM TT ON T.ReportsTo=TT.PartyId
INNER JOIN SGTM_TEAM T1 ON TT.Manager=T1.Manager AND T1.TeamType IN ('U','O','R')
INNER JOIN SGTM_AGENT A ON A.PartyId=L.Manager
INNER JOIN SGTM_AGENT A1 ON A1.PartyId=TT.Manager
--where TT.name like '%ABM%'

group by L.PartyId,L.LastMovement,L.ReportsTo,L.TeamNo,L.Manager,T.ReportsTo,T.TeamNo,TT.Manager,TT.TeamNo,T1.TeamNo,A.Surname,A.Forename2,A.Forename1,A1.Surname,A1.Forename2,A1.Forename1

SELECT  POL_KEY,AGENT_KEY,COV_KEY,P.POL_ID,P.POL_APP_FORM_ID,AGT_ID,V.SURNAME+' '+ISNULL(ISNULL(V.NAME2,V.NAME1),'') AGENT_NAME,COMM_HIST_AMT,COMM_EFF_DT,COMM_HIST_PRCES_DT,C.PLAN_ID,PA.ETBL_DESC_TXT PLAN_DESC,P.POL_PREM_PAY_DUR POL_TERM,POL_CSTAT_CD,PARA.DM_AV_DESC_TXT POL_STAT_DESC,
POL_CREAT_DT,P.POL_APP_CMPLT_DT,
AGT_CPREM_AMT COM_PRE,V.CSC_CODE,
CASE WHEN P.POL_BILL_MODE_CD=3 THEN
'Quarterly' WHEN P.POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN P.POL_BILL_MODE_CD=1 THEN 'Monthly' WHEN P.POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE P.POL_BILL_MODE_CD END PRE_MODE,PC.POL_ACTV_TYP_ID,CASE WHEN PC.POL_ACTV_TYP_ID='1082' THEN 'IFYC' ELSE 'RFYC' END COM_TYPE,PPC.PCHST_EFF_DT INITIAL_DATE,
CVG_MPREM_AMT MODAL_PRE,CVG_ME_FCT,C.CVG_MPREM_AMT-CVG_ME_PREM_AMT PRE_BEFORE,C.CVG_MPREM_AMT PRE_AFTER,
C.CVG_MPREM_AMT*(CASE WHEN CAST(P.POL_BILL_MODE_CD AS INT)>0 THEN 12/CAST(P.POL_BILL_MODE_CD AS INT)
ELSE 1 END) AS AFYP into #TMP FROM DLKHDIM..DIM_POLICY P
INNER JOIN SGTB_COMMISSION_HIS COM ON COM.POL_ID=P.POL_ID AND P.IS_CURRENT=1
INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1 AND C.PLAN_ID=COM.CVG_PLAN_ID and C.CVG_NUM=COM.CVG_NUM
INNER JOIN V_AGENT_INFO V ON V.PARTY_ID=COM.AGT_ID
LEFT JOIN (SELECT POL_ID,MIN(PCHST_EFF_DT) PCHST_EFF_DT FROM SGTB_POLICY_CHANGE PPC WHERE PPC.PCHST_STAT_CD='A' AND PPC.POL_ACTV_TYP_ID='1082' GROUP BY POL_ID) PPC ON COM.POL_ID=PPC.POL_ID
LEFT JOIN SGTB_POLICY_CHANGE PC ON COM.POL_ID=PC.POL_ID AND COM.COMM_EFF_DT=PC.PCHST_EFF_DT AND PCHST_STAT_CD='A' AND POL_ACTV_TYP_ID IN ('1082','1084')
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD'
LEFT JOIN SGTB_EDITTABLE PA ON C.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN'

UPDATE #TMP SET COM_TYPE='RFYC' WHERE POL_ACTV_TYP_ID='1082' AND DATEDIFF(M,INITIAL_DATE,COMM_EFF_DT)>0 
UPDATE #TMP SET COM_TYPE='2YC' WHERE POL_ACTV_TYP_ID='1084' AND DATEDIFF(DAY,INITIAL_DATE,COMM_EFF_DT)>365
UPDATE #TMP SET COM_TYPE='3YC' WHERE POL_ACTV_TYP_ID='1084' AND DATEDIFF(DAY,INITIAL_DATE,COMM_EFF_DT)>730

SELECT T.*,CASE WHEN POL_TERM='6' THEN MODAL_PRE/2 ELSE MODAL_PRE END WFYP,
LL.Manager2 PCODE,LL.TeamNo1 PUNIT,LL.ManagerName2 PNAME,LL.TeamNo2 PAUNIT,LL.Manager3 PManager,LL.ManagerName3 PABM,L.Manager2 LCODE,L.TeamNo1 LUNIT,L.ManagerName2 LNAME,L.TeamNo2 LAUNIT,L.Manager3 LManager,L.ManagerName3 LABM FROM #TMP T 
LEFT JOIN #LLEAD L ON T.AGT_ID=L.PartyId AND L.IS_CURRENT=1
LEFT JOIN #LLEAD LL ON T.AGT_ID=LL.PartyId AND LL.IS_CURRENT=0
where t.COMM_HIST_PRCES_DT between @START and @END
