
/***************************************************************************************************
    Changelog
    ***********
	VERSION    DATE CHNG    UPDATE_BY    DESC
	VERS0.1		                          Initial Version
	VERS0.2	   12-06-2025    SAVRATH      Change UAT7 schema from KCAPXUT1 -> KCAPXUAT
****************************************************************************************************/

CREATE PROC [dbo].[PARA_REQUIR_STATUS]
AS
	DROP TABLE IF EXISTS #TREQT
	DROP TABLE IF EXISTS #EDIT

	-- GET ALL REQUIREMENTS OF STATUS "ORDERED" & "REVIEWED AND ACCEPTED"
	SELECT REQT.* INTO #TREQT FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TREQT') REQT
		WHERE CPREQ_POL_CLI_CD = 'P' AND REQT.CPREQ_STAT_CD IN ('ORD','RAC') 
	SELECT * INTO #EDIT FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TEDIT WHERE ETBL_LANG_CD=''E''')

	SELECT  R.POL_CLI_ID POL_ID
		,R.REQIR_ID
		,CASE WHEN REASON = '' THEN LTRIM(RTRIM(E.ETBL_DESC_TXT))  ELSE  LTRIM(RTRIM(E.ETBL_DESC_TXT))+';'+ REPLACE(REASON,'AMP;','') END  ETBL_DESC_TXT 
		,REASON
		,CPREQ_STAT_CD
	FROM #TREQT R 
	LEFT JOIN #EDIT E ON R.REQIR_ID = E.ETBL_VALU_ID AND ETBL_TYP_ID='REQTC' 
	LEFT JOIN 
		(
			SELECT POL_CLI_ID, REQIR_ID, CPREQ_SEQ_NUM
				, STUFF((SELECT  '; ' + LTRIM(RTRIM(RMRKS))
					FROM #TREQT T2
					WHERE T2.POL_CLI_ID = T1.POL_CLI_ID
						AND T2.REQIR_ID = T1.REQIR_ID AND  T2.CPREQ_SEQ_NUM = T1.CPREQ_SEQ_NUM
					FOR XML PATH('')),1,1,'') REASON
			FROM #TREQT T1  
			--WHERE POL_CLI_ID = '700000010'
			GROUP BY POL_CLI_ID,REQIR_ID,CPREQ_SEQ_NUM
		) RR ON R.POL_CLI_ID = RR.POL_CLI_ID AND R.REQIR_ID = RR.REQIR_ID AND R.CPREQ_SEQ_NUM = RR.CPREQ_SEQ_NUM
