

CREATE PROC [dbo].[RPT_REJECT_LETTER_LIVE] 
(
	@POL_ID		VARCHAR(9) = ''
	,@POL_STAT_CD VARCHAR(3) = ''
	,@REJ_STAT_CD VARCHAR(3) = ''
)
AS
	DECLARE	@SQL		NVARCHAR(MAX)
		--,@POL_ID		VARCHAR(9) = '700004396'
		--,@POL_STAT_CD VARCHAR(3) = 'R'
		--,@REJ_STAT_CD VARCHAR(3) = ''

	DROP TABLE IF EXISTS #POL
	CREATE TABLE #POL
	(
		POL_ID				VARCHAR(10)
		,POL_APP_FORM_ID	VARCHAR(20)
		,POL_CSTAT_CD		VARCHAR(4)
		,POL_REJ_REASN_CD		VARCHAR(4)
		,POL_STAT_CHNG_DT	DATE
		,POL_REJ_EFF_DT	DATE
		,POL_MPREM_AMT		DECIMAL(15,2)
		,POL_MEDIC_FEE_AMT	DECIMAL(15,2)
		,POL_REFUND_AMT		DECIMAL(15,2)
		,PO_ID				VARCHAR(10)
		,PO_SEX_CD			VARCHAR(1)
		,PO_ENTR_SUR_NM		VARCHAR(25)
		,PO_ENTR_GIV_NM		VARCHAR(25)
		,PO_ADDR_LN_1_TXT	VARCHAR(128)
		,PO_ADDR_LN_2_TXT	VARCHAR(128)
		,PO_ADDR_LN_3_TXT	VARCHAR(128)
		,PO_ADDR_CNTY_CD	VARCHAR(6)
		,PO_ADDR_MUN_CD		VARCHAR(4)
		,PO_CRNT_LOC_CD		VARCHAR(2)
		,BLI_SEX_CD			VARCHAR(1)
		,BLI_ENTR_SUR_NM	VARCHAR(25)
		,BLI_ENTR_GIV_NM	VARCHAR(25)
		,PO_NM_LAST_UPDT_TS	DATE
		,PO_ADDR_LAST_UPDT_TS	DATE
		,BLI_NM_LAST_UP_TS	DATE
		,PO_NM_LAST_UPDT_NO	SMALLINT
		,PO_ADDR_LAST_UPDT_NO	SMALLINT
		,BLI_NM_LAST_UP_NO	SMALLINT
	)

	SET @SQL = N'
		SELECT *
			,PO_LAST_UPDT_NM_NO = ROW_NUMBER() OVER (ORDER BY PO_NM_LAST_UPDT_TS DESC)
			,PO_ADDR_LAST_UPDT_NO = ROW_NUMBER() OVER (ORDER BY PO_ADDR_LAST_UPDT_TS DESC)
			,BLI_NM_LAST_UP_NO = ROW_NUMBER() OVER (ORDER BY BLI_NM_LAST_UPDT_TS DESC)
		FROM OPENQUERY(UAT7,
		''
			SELECT POL.POL_ID
				,POL.POL_APP_FORM_ID
				,POL.POL_CSTAT_CD
				,POL.POL_REJ_REASN_CD
				,POL.POL_STAT_CHNG_DT
				,POL.POL_REJ_EFF_DT
				,POL.POL_MPREM_AMT
				,POL.POL_MEDIC_FEE_AMT
				,CASE WHEN ISNULL(ACCT_TRXN_AMT,0) = 0 THEN ACTH.ACCT_HIST_AMT ELSE ACTX.ACCT_TRXN_AMT END AS POL_REFUND_AMT
				,POLC.CLI_ID AS PO_ID
				,PO.CLI_SEX_CD AS PO_SEX_CD
				,TRIM(PONM.ENTR_SUR_NM) AS PO_ENTR_SUR_NM
				,TRIM(PONM.ENTR_GIV_NM) AS PO_ENTR_GIV_NM
				,TRIM(POAD.CLI_ADDR_LN_1_TXT) AS PO_ADDR_LN_1_TXT
				,TRIM(POAD.CLI_ADDR_LN_2_TXT) AS PO_ADDR_LN_2_TXT
				,TRIM(POAD.CLI_ADDR_LN_3_TXT) AS PO_ADDR_LN_3_TXT
				,POAD.CLI_ADDR_CNTY_CD AS PO_ADDR_CNTY_CD
				,POAD.CLI_ADDR_MUN_CD AS PO_ADDR_MUN_CD
				,POAD.CLI_CRNT_LOC_CD AS PO_CRNT_LOC_CD
				,BLI.CLI_SEX_CD AS BLI_SEX_CD
				,TRIM(BLINM.ENTR_SUR_NM) AS BLI_ENTR_SUR_NM
				,TRIM(BLINM.ENTR_GIV_NM) AS BLI_ENTR_GIV_NM
				,PONM.PREV_UPDT_TS AS PO_NM_LAST_UPDT_TS
				,POAD.PREV_UPDT_TS AS PO_ADDR_LAST_UPDT_TS
				,BLINM.PREV_UPDT_TS BLI_NM_LAST_UPDT_TS
			
			FROM KCAPXUAT.TPOL POL
			-- PO
			LEFT JOIN KCAPXUAT.TPOLC POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = ''''O''''
			LEFT JOIN KCAPXUAT.TCLI PO ON POLC.CLI_ID = PO.CLI_ID
			LEFT JOIN KCAPXUAT.TCLNM PONM ON POLC.CLI_ID = PONM.CLI_ID
			LEFT JOIN KCAPXUAT.TCLIA POAD ON POLC.CLI_ID = POAD.CLI_ID
			-- BLI
			LEFT JOIN KCAPXUAT.TCVGC CVGC ON POL.POL_ID = CVGC.POL_ID AND CVG_NUM = ''''01''''
			LEFT JOIN KCAPXUAT.TCLI BLI ON CVGC.INSRD_CLI_ID = BLI.CLI_ID
			LEFT JOIN KCAPXUAT.TCLNM BLINM ON CVGC.INSRD_CLI_ID = BLINM.CLI_ID
			-- REFUND AMOUNT
			LEFT JOIN KCAPXUAT.TACTX ACTX ON POL.POL_ID = ACTX.POL_ID  AND ACCT_TRXN_AMT > 0 AND ACTX.BUS_FCN_ID = ''''0222''''
			LEFT JOIN KCAPXUAT.TACTH ACTH ON POL.POL_ID = ACTH.POL_ID  AND ACCT_HIST_AMT > 0 AND ACTH.BUS_FCN_ID = ''''0222''''

			WHERE POL.POL_ID = ''''@POL_ID''''
			AND POL.POL_CSTAT_CD = ''''@POL_STAT_CD'''' 
			AND CASE WHEN ''''@REJ_STAT_CD'''' = '''''''' THEN '''''''' ELSE POL.POL_REJ_REASN_CD END = ''''@REJ_STAT_CD''''						
		'')
	';

	SET @SQL = REPLACE(@SQL,'@POL_ID',@POL_ID)
	SET @SQL = REPLACE(@SQL,'@POL_STAT_CD',@POL_STAT_CD)
	SET @SQL = REPLACE(@SQL,'@REJ_STAT_CD',@REJ_STAT_CD)

	INSERT INTO #POL EXEC SP_EXECUTESQL @SQL;

	SELECT POL.POL_ID
		,POL_APP_FORM_ID = RTRIM(POL_APP_FORM_ID)
		,POL_CSTAT_CD 
		,POL_REJ_REASN_CD
		,POL_STAT_CHNG_DT 
		,POL_REJ_EFF_DT
		,REJ_EFF_DAY = DAY(POL_REJ_EFF_DT)
		,REJ_EFF_MONTH = DBO.CONVERT_KH_MONTH(MONTH(POL_REJ_EFF_DT))
		,REJ_EFF_YEAR = YEAR(POL_REJ_EFF_DT)		
		,POLH.POL_MPREM_AMT
		,POL_MEDIC_FEE_AMT 
		,POL_REFUND_AMT
		,PO_ID 
		,PO_SEX_CD 
		,PO_TITLE = CASE WHEN PO_SEX_CD = 'M' THEN 'Mr.' ELSE 'Mrs.' END
		,PO_ENTR_SUR_NM 
		,PO_ENTR_GIV_NM 
		,PO_ADDRESS = POL.PO_ADDR_LN_1_TXT + 
			CASE WHEN POL.PO_ADDR_LN_2_TXT = '' THEN '' ELSE ', ' + POL.PO_ADDR_LN_2_TXT END + 
			CASE WHEN POL.PO_ADDR_LN_3_TXT = '' THEN '' ELSE ', ' + POL.PO_ADDR_LN_3_TXT END + 
			', ' + RTRIM(POCMU.ETBL_DESC_TXT) + ', ' + RTRIM(PODIS.ETBL_DESC_TXT) + ', ' + RTRIM(POCIT.ETBL_DESC_TXT)
		,BLI_SEX_CD 
		,BLI_TITLE = CASE WHEN BLI_SEX_CD = 'M' THEN 'Mr.' ELSE 'Mrs.' END
		,BLI_ENTR_SUR_NM 
		,BLI_ENTR_GIV_NM
		,PO_NM_LAST_UPDT_NO
		,PO_ADDR_LAST_UPDT_NO
		,BLI_NM_LAST_UP_NO
	FROM #POL POL
	LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE POLH ON POL.POL_ID = POLH.POL_ID
	LEFT JOIN SGTB_EDITTABLE POCMU ON POCMU.ETBL_TYP_ID='CTYPC' AND POL.PO_ADDR_CNTY_CD = POCMU.ETBL_VALU_ID AND POCMU.CO_ID = 'CP' AND POCMU.ETBL_LANG_CD = 'E' 
	LEFT JOIN SGTB_EDITTABLE PODIS ON PODIS.ETBL_TYP_ID='MCPCD' AND POL.PO_ADDR_MUN_CD = PODIS.ETBL_VALU_ID AND PODIS.CO_ID = 'CP' AND PODIS.ETBL_LANG_CD = 'E' 
	LEFT JOIN SGTB_EDITTABLE POCIT ON POCIT.ETBL_TYP_ID='CLOC' AND  POL.PO_CRNT_LOC_CD = POCIT.ETBL_VALU_ID AND POCIT.CO_ID = 'CP' AND POCIT.ETBL_LANG_CD = 'E' 	
	WHERE PO_NM_LAST_UPDT_NO = 1
