

CREATE OR ALTER PROC [dbo].[RPT_POL_DISPATCH_AND_ACKNOWLEDGED] @start_date date = null , @end_date date = null
AS

	DROP TABLE IF EXISTS #DIS
	DROP TABLE IF EXISTS #AGT
	DROP TABLE IF EXISTS #XTAB
	DROP TABLE IF EXISTS #EDIT
	DROP TABLE IF EXISTS #CRI

	--DECLARE @start_date DATE 
	--DECLARE @end_date DATE
	if @start_date is null SET @start_date = '2023-01-01'
	if @end_date is null SET  @end_date = CONVERT(DATE,GETDATE())

	SELECT * 
	INTO #DIS 
	FROM OPENQUERY(DLIUDW01,'SELECT * FROM PNSDLIKH.DBO.INGENIUM_POLICY_DISPATCHES')
	
	SELECT * 
	INTO #AGT 
	FROM V_GET_AGENT_BASIC
	
	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) 
	INTO #EDIT 
	FROM SGTB_EDITTABLE 
	WHERE CO_ID = 'CP' AND ETBL_LANG_CD = 'E' 
		AND ETBL_TYP_ID IN ('CLOC','CTYPC','MCPCD', 'BTLOC')
	
	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) 
	INTO #XTAB 
	FROM SGTM_PARA
	WHERE ETBL_LANG_CD = 'E' AND ETBL_TYP_ID = 'SOLDBR'

	
	-- GET ONLY FAIL CRITERIA CODE - CRI
	SELECT POL_ID, STUFF( (SELECT  ', '+LTRIM(RTRIM(AUTO_UW_REL_CD)) +':'+ LTRIM(RTRIM(AUTO_UW_RULE_CD))
			FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T WHERE T.POL_ID = T1.POL_ID
			FOR XML PATH('')),1,1,'') AUTO_UW_RULE_CD
	INTO #CRI
	FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T1
	GROUP BY POL_ID
	
	SELECT DIS.POLICY_ID
		,DIS.DISPATCHED_DATE
		,DIS.INFORCED_DATE
		,DIS.SIGNED_DATE
		,DATEDIFF(DAY, DIS.DISPATCHED_DATE, DIS.ACKNOWLEDGEMENT_DATE) AS NB_DURATION
		,DIS.NB_NOTE
		,DIS.ACKNOWLEDGEMENT_DATE
		,DIS.WELCOME_DATE
		,DIS.CS_NOTE
		,(DATEDIFF(DAY, DIS.ACKNOWLEDGEMENT_DATE, DIS.WELCOME_DATE) + 1)
		  - (DATEDIFF(WK, DIS.ACKNOWLEDGEMENT_DATE, DIS.WELCOME_DATE) * 2)
		  - (CASE DATEPART(DW, DIS.ACKNOWLEDGEMENT_DATE) WHEN 1 THEN 1 ELSE 0 END) 
		  - (CASE DATEPART(DW, DIS.WELCOME_DATE) WHEN 7 THEN 1 ELSE 0 END)
		   AS CS_DURATION
		,DIS.CREATED_USER
		,CONVERT(VARCHAR,DIS.CREATED_AT,105) AS CREATED_AT
		,POL.POL_INFC_DT
		,POL.POL_REISS_DT
		,POL_MPREM_AMT = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
		,APE = (FN_AFYP.multiplier) *  CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END * 
			(CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL.POL_BILL_MODE_CD AS INT) END)	-- APE/AFYP
		,POL.POL_BILL_MODE_CD
		,POL.POL_CSTAT_CD
		,POL_CSTAT_DESC = UPPER(RTRIM(CSTAT.DM_AV_DESC_TXT))
		,POLC.CLI_ID
		,PO_ID = POLC.CLI_ID
		,PO_SEX_CD = CLI.CLI_SEX_CD
		,PO_BTH_DT = CLI.CLI_BTH_DT
		,PO_ENTR_GIV_NM = RTRIM(CIND.ENTR_GIV_NM)
		,PO_ENTR_SUR_NM = RTRIM(CIND.ENTR_SUR_NM)
		,CLI_ADDR_LN_1_TXT = RTRIM(CLIA.CLI_ADDR_LN_1_TXT)
		,CLI_ADDR_LN_2_TXT = RTRIM(CLIA.CLI_ADDR_LN_2_TXT)
		,CLI_ADDR_LN_3_TXT = RTRIM(CLIA.CLI_ADDR_LN_3_TXT)
		,CLIA.CLI_CTRY_CD			-- Country
		,CLI_CTRY_DESC = CTRY.ETBL_DESC_TXT
		,CLIA.CLI_CITY_NM_TXT
		,CLI_CITY = (CIT.ETBL_DESC_TXT)
		,CLI_DISTRICT = (DIST.ETBL_DESC_TXT)
		,CLI_COMMUNE = (COMU.ETBL_DESC_TXT)
		,CLIA.CLI_ADDR_STAT_CD
		,CLI_ADDR_STAT_DESC = (CASE ISNULL(CLIA.CLI_ADDR_STAT_CD,'') WHEN 'C' THEN 'COMPLETE' WHEN 'I' THEN 'INCOMPLETE' ELSE '' END)
		,CLIC.MO
		,CLIC.EM
		,CLIC.HO
		,AG.AGT_DISB_CHNL
		,AGT_DISB_CHNL_DESC = RTRIM(AG.AGT_DISB_CHNL_DESC)
		,AG.OVRID_BASE_AGT_ID
		,AG.OVRID_ID
		,POLW.AGT_ID
		,AGT_ENTR_SUR_NM = (AG.ENTR_SUR_NM)
		,AGT_ENTR_GIV_NM = (AG.ENTR_GIV_NM)
		,AGT_PHON_NUM = (AG.AGT_PHON_NUM)
		,AGT_EMIAL = AG.AGT_EMAIL
		,AG.AGT_ADDR_LN_1_TXT
		,AG.AGT_CNTRCT_STRT_DT
		,AGT_LDR_ID = AGL.AGT_ID
		,AGT_LDR_SUR_NM = (AGL.ENTR_SUR_NM)
		,AGT_LDR_GIV_NM = AGL.ENTR_GIV_NM
		,AGT_LDR_PHON_NUM = AGL.AGT_PHON_NUM
		,AGT_LDR_EMAIL = AGL.AGT_EMAIL
		,AGT_MGR_ID = AGM.AGT_ID
		,AGT_MGR_SUR_NM = AGM.ENTR_SUR_NM
		,AGT_MGR_GIV_NM = AGM.ENTR_GIV_NM
		,AGT_MGR_PHON_NUM = AGM.AGT_PHON_NUM
		,AGT_MGR_EMAIL = AGM.AGT_EMAIL
		,POLw.POL_SOLD_BR_ID
		,POL_SOLD_BR_NAME = SLDBR.ETBL_DESC_TXT
		,POL.APP_SUBMIT_CD
		,CASE_STT = CASE WHEN POL.POL_CASE_STAT_CD ='M' THEN 'Manual' WHEN POL.POL_CASE_STAT_CD ='A' THEN 'Auto' ELSE '' END
		,CASE_STT_RMKS = POLC.POL_UW_RMRKS
		,CRI.AUTO_UW_RULE_CD
        ,AGENT_TYPE = AG.AGT_TITL
	FROM #DIS DIS
	LEFT JOIN SGTB_POLICY POL ON DIS.POLICY_ID = POL.POL_ID
	LEFT JOIN SGTB_POLICY_CLIENT POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = 'O'
	LEFT JOIN SGTM_CLIENT CLI ON POLC.CLI_ID = CLI.CLI_ID
	LEFT JOIN SGTM_CLIENT_IND CIND ON CLI.CLI_ID = CIND.CLI_ID AND CIND.PREV_UPDT_TS = (SELECT MAX(PREV_UPDT_TS) FROM SGTM_CLIENT_IND  WHERE CLI_ID = CLI.CLI_ID GROUP BY CLI_ID)
	LEFT JOIN SGTM_CLIENT_ADD CLIA ON CLI.CLI_ID = CLIA.CLI_ID AND CLIA.PREV_UPDT_TS = (SELECT MAX(PREV_UPDT_TS) FROM SGTM_CLIENT_ADD  WHERE CLI_ID = CLI.CLI_ID GROUP BY CLI_ID)
	LEFT JOIN V_PIVOT_CLIENT_CONTACT CLIC ON CLI.CLI_ID = CLIC.CLI_ID
	LEFT JOIN #EDIT CTRY ON CLIA.CLI_CTRY_CD = CTRY.ETBL_VALU_ID AND CTRY.ETBL_TYP_ID = 'BTLOC'
	LEFT JOIN #EDIT CIT ON  CLIA.CLI_CRNT_LOC_CD = CIT.ETBL_VALU_ID AND CIT.ETBL_TYP_ID='CLOC'
	LEFT JOIN #EDIT COMU ON CLIA.CLI_ADDR_CNTY_CD = COMU.ETBL_VALU_ID AND COMU.ETBL_TYP_ID = 'CTYPC'
	LEFT JOIN #EDIT DIST ON CLIA.CLI_ADDR_MUN_CD= DIST.ETBL_VALU_ID AND DIST.ETBL_TYP_ID='MCPCD'
	LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE POL0 ON POL.POL_ID = POL0.POL_ID
	LEFT JOIN SGTM_PARA_1 CSTAT ON POL.POL_CSTAT_CD = CSTAT.DM_AV_CD AND CSTAT.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND CSTAT.CO_ID = 'CP' AND DM_AV_DESC_LANG_CD = 'E'
	LEFT JOIN SGTB_POLICY_WRITING POLW ON POL.POL_ID = POLW.POL_ID
	---- AGENT
	LEFT JOIN #AGT AG ON POLW.AGT_ID = AG.AGT_ID
	--LEFT JOIN #AGT AGL ON AG.OVRID_BASE_AGT_ID = AGL.AGT_ID
	LEFT JOIN #AGT AGL ON CASE WHEN AG.AGT_DISB_CHNL IN ('3','4') AND AG.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AG.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	--	LEFT JOIN #AGT AGM ON AGL.OVRID_BASE_AGT_ID = AGM.AGT_ID
	LEFT JOIN #AGT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
	LEFT JOIN #XTAB SLDBR ON POLW.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_TYP_ID = 'SOLDBR'
	LEFT JOIN #CRI CRI ON POL.POL_ID = CRI.POL_ID 
	OUTER APPLY DLKHSTAGE.dbo.FN_GET_AFYP_MULTIPLIER(POL.PLAN_ID, POL.POL_BILL_TYP_CD) FN_AFYP
	WHERE DIS.DISPATCHED_DATE BETWEEN @start_date and @end_date
