

CREATE PROCEDURE [dbo].[RPT_LAPSE_REINSTATE]
	@RE_INS_FROM	DATE = ''
	,@RE_INS_TO		DATE = ''
AS

--DECLARE	@RE_INS_FROM	DATE = '2023-11-01'
--	,	@RE_INS_TO		DATE = '2023-11-14'

	DROP TABLE IF EXISTS #TMP_POL
	DROP TABLE IF EXISTS #TMP_LAP

	SELECT MAX(POL_KEY) POL_KEY
	,P.POL_ID
	,POL_ISS_EFF_DT
	,POL_STAT_CHNG_DT REINSTATED
	,POL_CRNT_MODE_FCT
	,POL_MPREM_AMT
	,POL_MPREM_AMT * (
		CASE WHEN CAST(POL_BILL_MODE_CD AS INT)> 0 THEN 12 / CAST(POL_BILL_MODE_CD AS INT)
		ELSE 1 END) AS AFYP
	,CASE WHEN P.POL_BILL_MODE_CD = 3 THEN 'Quarterly' 
		WHEN P.POL_BILL_MODE_CD=6 THEN 'Semi Annual' 
		WHEN P.POL_BILL_MODE_CD=1 THEN 'Monthly' 
		WHEN P.POL_BILL_MODE_CD=12 THEN 'Annual'
		ELSE P.POL_BILL_MODE_CD END PRE_MODE
	,CHANNEL 
	,REMARK = 'REMARK'
	INTO #TMP_POL 
	FROM DLKHDIM..DIM_POLICY P 
	LEFT JOIN SGTB_POLICY_WRITING W ON P.POL_ID=W.POL_ID 
	LEFT JOIN V_AGENT V ON V.AGT_ID = W.AGT_ID AND V.AGT_CLI_REL_TYP_CD ='M'
	WHERE POL_CSTAT_CD ='1' AND POL_PREV_CSTAT_CD ='B' AND POL_STAT_CHNG_DT BETWEEN @RE_INS_FROM AND @RE_INS_TO
	GROUP BY P.POL_ID,POL_ISS_EFF_DT,POL_STAT_CHNG_DT,POL_CRNT_MODE_FCT,POL_MPREM_AMT,POL_BILL_MODE_CD,CHANNEL

	SELECT P.POL_ID,MAX(P.POL_STAT_CHNG_DT) LAPSED_DATE 
	INTO #TMP_LAP 
	FROM DLKHDIM..DIM_POLICY P INNER JOIN #TMP_POL T ON P.POL_ID=T.POL_ID AND P.POL_STAT_CHNG_DT < T.REINSTATED 
	WHERE P.POL_CSTAT_CD='B'
	GROUP BY P.POL_ID

	SELECT T.POL_ID, PC.CLI_ID
		,RTRIM(LTRIM(CL.ENTR_SUR_NM))+' '+ RTRIM(LTRIM(CL.ENTR_GIV_NM)) CLI_NAME
		,POL_ISS_EFF_DT,REINSTATED,LAPSED_DATE,POL_CRNT_MODE_FCT,POL_MPREM_AMT,AFYP,CHANNEL,PRE_MODE , T.REMARK
	FROM #TMP_POL T 
	LEFT JOIN #TMP_LAP L ON T.POL_ID=L.POL_ID
	LEFT JOIN DLKHSTAGE..SGTB_POLICY_CLIENT PC ON T.POL_ID = PC.POL_ID
	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_IND CL ON PC.CLI_ID = CL.CLI_ID
	ORDER BY T.POL_ID
