CREATE OR ALTER PROC [dbo].[RPT_LAPSE_POLICY]
	@ISSUE_DATE_FROM	DATE = NULL
	,@ISSUE_DATE_TO	DATE = NULL
AS
-- DECLARE @ISSUE_DATE_FROM	DATE = '2026-06-01'
-- ,@ISSUE_DATE_TO	DATE = '2026-07-27';
	DROP TABLE IF EXISTS #TREQT
	DROP TABLE IF EXISTS #TMP
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #TCLIA
	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS #AGT
	DROP TABLE IF EXISTS #AGENTS_NAME
	DROP TABLE IF EXISTS #XTAB

	IF ISNULL(@ISSUE_DATE_FROM,'') = '' SET @ISSUE_DATE_FROM = '2000-01-01'
	IF ISNULL(@ISSUE_DATE_TO,'') = '' SET @ISSUE_DATE_TO = CONVERT(DATE, GETDATE())
	--IF ISNULL(@ISSUE_DATE_TO,'') = '' SET @ISSUE_DATE_TO = DATEADD(day, -1, CAST(GETDATE() AS date))CONVERT(DATE,GETDATE())

	-- GET CLIENT ADDRESS AND DEFINE THE LATEST UPDATED ADDRESS INFO, 1 = LATEST UPDATE
	SELECT *,#LAST_UPTD_ADD = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLIA
	FROM SGTM_CLIENT_ADD

	-- GET CLIENT NAME AND DEFINE THE LATEST UPDATED NAME INFO, 1 = LATEST UPDATE
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),#LAST_UPDT_NM =  ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM FROM SGTM_CLIENT_IND

	SELECT AGT.AGT_ID,AGT.OVRID_BASE_AGT_ID,AGT.AGT_DISB_CHNL
		,ENTR_SUR_NM = RTRIM(AGNM.ENTR_SUR_NM)
		,ENTR_GIV_NM = RTRIM(AGNM.ENTR_GIV_NM)
		,AGT_DISB_CHNL_DESC = RTRIM(CHNL.ETBL_DESC_TXT)
		,AGT.AGT_STAT_CD
	INTO #AGENT
	FROM SGTM_AG AGT
	LEFT JOIN #TCLNM AGNM ON AGT.AGT_ID = AGNM.CLI_ID AND #LAST_UPDT_NM = 1
	LEFT JOIN SGTB_EDITTABLE CHNL ON AGT.AGT_DISB_CHNL = CHNL.ETBL_VALU_ID AND CHNL.ETBL_TYP_ID ='DCHNL' AND CHNL.ETBL_LANG_CD = 'E' AND CHNL.CO_ID = 'CP'
	-- GET AGENT INFO
	SELECT * INTO #AGT FROM V_GET_AGENT_BASIC

	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #XTAB FROM SGTM_PARA
		WHERE ETBL_LANG_CD = 'E' AND ETBL_TYP_ID = 'SOLDBR'

	SELECT
		--,SOURCE_CUSTOMER = SLDBR.ETBL_DESC_TXT
		--,SOURCE_CUSTOMER = dbo.[FnGetSourceOfCustomerText](POL.CUST_SRC_CD)
		SOURCE_CUSTOMER = src.ObjectName
		,CLIN_OCCUPATION = OCC.ETBL_DESC_TXT
		,PO_MATCHED_ANYAGENT = CASE WHEN PONM.ENTR_SUR_NM + ' ' + PONM.ENTR_GIV_NM IN(AGT.ENTR_SUR_NM + ' ' + AGT.ENTR_GIV_NM) THEN 'YES' ELSE 'NO' END
		,AGENT_JOIN_DATE = AG.AGT_CNTRCT_STRT_DT
		,POL_EQUAL_AGENT = CASE WHEN AGT.ENTR_SUR_NM + ' ' + AGT.ENTR_GIV_NM = PONM.ENTR_SUR_NM + ' ' + PONM.ENTR_GIV_NM THEN 'YES' ELSE 'NO' END
		,PO_NAME = PONM.ENTR_SUR_NM + ' ' + PONM.ENTR_GIV_NM
		--,CLIENT_INCOME = CASE WHEN ISNULL(CINF.EARN_INCM_MODE_CD,'') = 'M' THEN 12 ELSE 1 END * CINF.CLI_EARN_INCM_AMT
		,CLIENT_INCOME = ISNULL( CINF.CLI_EARN_INCM_AMT,0)		--2022-11-02: There is no logic to capture income by month (only annual income is input)
		,CLIENT_AGE = CLIN.CLI_BTH_DT
		,[PO_AGE] = dbo.CALCULATE_PO_AGE(CLIN.CLI_BTH_DT,POL_ISS_EFF_DT)
		,POL_GENDER = CASE WHEN CLIN.CLI_SEX_CD = 'F' THEN 'Female' ELSE 'Male'END
		,POLC.CLI_ID
		,POL.POL_ID
		,POL.POL_APP_FORM_ID
		,CVG.CVG_FACE_AMT
		,CVG.CVG_STAT_EFF_DT
		,POL_MPREM_AMT = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
		,POL.PLAN_ID
		,POL_NOT = RTRIM(POL.POL_NOT)
		,PLAN_DESC = RTRIM(PLN.ETBL_DESC_TXT)
		,POL_STAT_DESC = CASE WHEN POL_CSTAT_CD='A' THEN 'CFI' ELSE RTRIM(PARA.DM_AV_DESC_TXT) END
		,PRE_MODE = RTRIM(BLM.ETBL_DESC_TXT)
		,POL_ISS_EFF_DT
		,POL_APP_RECV_DT
		,POL_APP_CMPLT_DT  = CASE WHEN POL_INFC_DT=POL_STAT_CHNG_DT OR POL_CSTAT_CD='B' OR (POL_CSTAT_CD='1' AND POL_PREV_CSTAT_CD='B') THEN NULL ELSE POL_INFC_DT END
		,POL_STAT_CHNG_DT = CASE WHEN POL_CSTAT_CD='B' OR (POL_CSTAT_CD='1' AND POL_PREV_CSTAT_CD='B') THEN POL_APP_CMPLT_DT ELSE POL_STAT_CHNG_DT END
		,APE = (12 / CAST(POL.POL_BILL_MODE_CD AS INT)) * CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
		,LAPSED_DATE = CASE WHEN POL_CSTAT_CD ='B' OR POL_CSTAT_CD = 'E' THEN POL_STAT_CHNG_DT ELSE NULL END
		,LAPSED_REASON = RTRIM(CEASE.ETBL_DESC_TXT)
		,POL.POL_PD_TO_DT_NUM
		,PO_CLI_ID = PCLIR.PO
		,PO_PHONE = RTRIM(POC.CLI_CNTCT_ID_TXT)
		,PO_ADDR_LN_1_TXT = RTRIM(POA.CLI_ADDR_LN_1_TXT)
		,PO_ADDR_LN_2_TXT = RTRIM(POA.CLI_ADDR_LN_2_TXT)
		,PO_ADDR_LN_3_TXT = RTRIM(POA.CLI_ADDR_LN_3_TXT)
		,PO_CITY_NM_TXT = RTRIM(POA.CLI_CITY_NM_TXT)
		-- BLI
		,BLI_ID = PCLIR.BLI
		,BLI_NAME = BLINM.ENTR_SUR_NM + ' ' + BLINM.ENTR_GIV_NM
		,BLI_PHONE = RTRIM(BLIC.CLI_CNTCT_ID_TXT)
		-- ALI 1
		,ALI1_NAME = ALI1NM.ENTR_SUR_NM + ' ' + ALI1NM.ENTR_GIV_NM
		,ALI1_CLI_ID = PCLIR.ALI1
		,ALI1_PHONE = RTRIM(ALI1C.CLI_CNTCT_ID_TXT)
		-- ALI 2
		,ALI2_NAME = ALI2NM.ENTR_SUR_NM + ' ' + ALI2NM.ENTR_GIV_NM
		,ALI2_CLI_ID = PCLIR.ALI2
		,ALI2_PHONE = RTRIM(ALI2C.CLI_CNTCT_ID_TXT)
		,AGT.AGT_ID
		,AGENT_NAME = AGT.ENTR_SUR_NM + ' ' + AGT.ENTR_GIV_NM
		,AGENT_MANAGER_NAME = AGM.ENTR_SUR_NM + ' ' + AGM.ENTR_GIV_NM
		,AGENT_STATUS = CASE WHEN AGT.AGT_STAT_CD = 'A' THEN 'ACTIVE'  WHEN AGT.AGT_STAT_CD = 'I' THEN 'INACTIVE' ELSE 'INACTIVE VESTED' END
		,AGT.AGT_DISB_CHNL_DESC
		,JETCASE = ''
		,NONJET_STATUS = ''
		,AGENT_BRACH = RTRIM(AGL.ENTR_SUR_NM) + ' ' + RTRIM(AGL.ENTR_GIV_NM)
		,CLI_CITY = (CIT.ETBL_DESC_TXT)
		,POl.COLCT_MTHD_CD,
		POL_COLCT_MTHD_DESC = (COMTH.ETBL_DESC_TXT),
		DATEDIFF(month, POL.POL_PD_TO_DT_NUM, GETDATE()) AS TERMINATE,
		CASE WHEN DATEDIFF(month, POL.POL_PD_TO_DT_NUM, GETDATE()) >24 THEN 'TERMINATE' ELSE ' ' END AS POL_TER,
        AGENT_TITLE = EDIT.ETBL_DESC_TXT
--	INTO #TM
	FROM SGTB_POLICY POL
	LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE POL0 ON POL.POL_ID = POL0.POL_ID
	LEFT JOIN SGTB_POLICY_CLIENT POLC ON POLC.POL_ID = POL.POL_ID AND POLC.POL_CLI_REL_TYP_CD = 'O'
	LEFT JOIN SGTB_POLICY_WRITING POLW ON POL.POL_ID = POLW.POL_ID
	LEFT JOIN SGTM_COVERAGE CVG ON POL.POL_ID = CVG.POL_ID AND CVG_NUM = '01'	-- GET ONLY BASIC PLAN
	LEFT JOIN SGTB_COVERAGE_CLI CVGC ON CVG.POL_ID = CVGC.POL_ID AND CVG.CVG_NUM = CVGC.CVG_NUM AND CVG_FACE_AMT > 0

	LEFT JOIN #AGENT AGT ON AGT.AGT_ID = POLW.AGT_ID
	LEFT JOIN #AGENT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGENT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID

	-- <N
	LEFT JOIN SGTM_CLIENT CLIN ON CLIN.CLI_ID = POLC.CLI_ID
	LEFT JOIN #AGT AG ON POLW.AGT_ID = AG.AGT_ID
	--LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_INFO WHERE LEN(CLI_ID) >= 10) CINF ON CVGC.INSRD_CLI_ID = CINF.CLI_ID AND CINF.#NO = 1
	--LEFT JOIN (SELECT DISTINCT CLI_ID,CLI_EARN_INCM_AMT FROM SGTM_CLIENT_INFO) CINF ON CINF.CLI_ID=CVGC.INSRD_CLI_ID  ----2022-11-02: There are 3000+ duplicate record in table SGTM_CLIENT_INFO
	OUTER APPLY (SELECT TOP 1 CLI_ID,CLI_EARN_INCM_AMT FROM SGTM_CLIENT_INFO inc WHERE inc.CLI_ID=POLC.CLI_ID ORDER BY inc.CLI_INCM_EFF_DT DESC ) CINF
	LEFT JOIN SGTB_EDITTABLE EDIT ON EDIT.ETBL_VALU_ID = AG.AGT_TITL AND ETBL_TYP_ID= 'AGTLE' AND EDIT.CO_ID = 'CP' AND EDIT.ETBL_LANG_CD = 'E'
	LEFT JOIN SGTB_EDITTABLE OCC ON CLIN.OCCP_ID = OCC.ETBL_VALU_ID AND OCC.ETBL_TYP_ID='OCCCD'
	LEFT JOIN #XTAB SLDBR ON POLW.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_TYP_ID = 'SOLDBR'
	-- N>


	LEFT JOIN V_PIVOT_POL_CLI_ROLE PCLIR ON POL.POL_ID = PCLIR.POL_ID
	-- PO
	LEFT JOIN #TCLNM PONM ON PCLIR.PO = PONM.CLI_ID AND PONM.#LAST_UPDT_NM = 1
	LEFT JOIN #TCLIA POA  ON PCLIR.PO = POA.CLI_ID AND POA.#LAST_UPTD_ADD = 1
	LEFT JOIN SGTM_CLIENT_CONTACT POC ON PCLIR.PO = POC.CLI_ID AND POC.CLI_CNTCT_ID_CD = 'MO'
	-- BLI
	LEFT JOIN #TCLNM BLINM ON PCLIR.BLI = BLINM.CLI_ID AND BLINM.#LAST_UPDT_NM = 1
	LEFT JOIN SGTM_CLIENT_CONTACT BLIC ON PCLIR.BLI = BLIC.CLI_ID AND BLIC.CLI_CNTCT_ID_CD = 'MO'
	-- ALI 1
	LEFT JOIN #TCLNM ALI1NM ON PCLIR.ALI1 = ALI1NM.CLI_ID AND ALI1NM.#LAST_UPDT_NM = 1
	LEFT JOIN SGTM_CLIENT_CONTACT ALI1C ON PCLIR.ALI1 = ALI1C.CLI_ID AND ALI1C.CLI_CNTCT_ID_CD = 'MO'
	-- ALI 2
	LEFT JOIN #TCLNM ALI2NM ON PCLIR.ALI2 = ALI2NM.CLI_ID AND ALI2NM.#LAST_UPDT_NM = 1
	LEFT JOIN SGTM_CLIENT_CONTACT ALI2C ON PCLIR.ALI2 = ALI2C.CLI_ID AND ALI2C.CLI_CNTCT_ID_CD = 'MO'
	LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_ADD WHERE LEN(CLI_ID) >= 10 AND CLI_ADDR_TYP_CD = 'PR') CLIA ON CVGC.INSRD_CLI_ID = CLIA.CLI_ID AND CLIA.#NO = 1
	LEFT JOIN SGTB_EDITTABLE BLM ON POL.POL_BILL_MODE_CD = BLM.ETBL_VALU_ID AND BLM.ETBL_TYP_ID ='BILL-MODE' AND BLM.ETBL_LANG_CD = 'E' AND BLM.CO_ID = 'CP'
	LEFT JOIN SGTB_EDITTABLE CEASE ON POL.POL_CEAS_REASN_CD = CEASE.ETBL_VALU_ID AND CEASE.ETBL_TYP_ID = 'CEASE' AND CEASE.ETBL_LANG_CD = 'E' AND CEASE.CO_ID = 'CP'
	LEFT JOIN SGTB_EDITTABLE PLN ON POL.PLAN_ID = PLN.ETBL_VALU_ID AND PLN.ETBL_TYP_ID = 'PLAN' AND PLN.ETBL_LANG_CD = 'E' AND PLN.CO_ID = 'CP'
	LEFT JOIN SGTB_EDITTABLE COMTH ON POL.COLCT_MTHD_CD = COMTH.ETBL_VALU_ID AND COMTH.ETBL_TYP_ID = 'COMTH'
	LEFT JOIN SGTM_PARA_1 PARA ON POL.POL_CSTAT_CD = PARA.DM_AV_CD AND DM_AV_TBL_CD = 'POL-CSTAT-CD' AND PARA.CO_ID = 'CP' AND PARA.DM_AV_DESC_LANG_CD = 'E'
	LEFT JOIN SGTB_EDITTABLE CIT ON  CLIA.CLI_CRNT_LOC_CD = CIT.ETBL_VALU_ID AND CIT.ETBL_TYP_ID='CLOC' AND CLIA.#NO = 1 AND CIT.ETBL_LANG_CD = 'E' AND CIT.CO_ID = 'CP'
	-- Getting Source of Customer description
	LEFT JOIN dbo.VW_SetUp_SourceOfCustomer src ON src.ObjectCode = TRIM(POL.CUST_SRC_CD)

	WHERE POL.POL_CSTAT_CD IN  ('1','B','E') 
	AND POL.POL_APP_RECV_DT BETWEEN @ISSUE_DATE_FROM AND @ISSUE_DATE_TO

	DROP TABLE IF EXISTS	#XTAB
