
/***************************************************************************************************
	REPORT:.......... POLICY REFUND
	PURPOSE:......... 
        
    Changelog
    ***********
	VERSION    DATE CHNG    UPDATE_BY    DESC
	VER.1		                          Initial Version
	VER.2      29-03-24     SOUTHENAE     DISC % INFORMATION
	VER.3      04-03-24     SOUTHEANE	  CASE STATUS & REMARK
    VER.4      12-06-25     SAVRATH	      Change UAT7 schema from KCAPXUT1 -> KCAPXUAT
    VER.5      18-06-25     SAVRATH	      ADD AML STATUS [DL-1173]
    VER.6      18-06-25     SAVRATH	      ADD STP STATUS [DL-1283]
****************************************************************************************************/

CREATE PROC [dbo].[RPT_REFUND] 
	@AS_OF		DATE
	,@START		DATE = NULL
	,@END		DATE = NULL
AS
	--DECLARE @START	DATE = '2000-04-01'
	--	,@END		DATE = '2024-05-03'
	--	,@AS_OF		DATE = '2024-05-03'

	DROP TABLE IF EXISTS #AGT
	DROP TABLE IF EXISTS #TCHTX
	DROP TABLE IF EXISTS #TCHDL
	DROP TABLE IF EXISTS #TPOTD
	DROP TABLE IF EXISTS #TACTX
	DROP TABLE IF EXISTS #MAIN_TMP
	DROP TABLE IF EXISTS #CRI
    DROP TABLE IF EXISTS #POL -- VER.5

	IF ISNULL(@START,'') = ''	SET @START = '2000-01-01'
	IF ISNULL(@END,'') = ''	SET @END = @AS_OF

	-- GET AGENT INFO
	SELECT * INTO #AGT FROM V_GET_AGENT_BASIC

	-- TO GET DESCRIPTION AND REASON OF DISBURSEMENT
	SELECT * INTO #TCHTX FROM OPENQUERY(ING77UAT,'SELECT CHQ_REF_ID,CHQ_AMT,CHQ_GEN_ID,CHQ_BTCH_NUM,CHQ_DESC_LN_1_TXT FROM KCAPXUT1.TCHTX')
	SELECT * INTO #TCHDL FROM OPENQUERY(ING77UAT,'SELECT CHQ_GEN_ID,CHQ_DTL_FLD_ID,CHQ_DTL_VALU_TXT FROM KCAPXUT1.TCHDL WHERE CHQ_DTL_FLD_ID = ''REASN''')
	SELECT * INTO #TPOTD FROM OPENQUERY(ING77UAT,'SELECT POL_ID,CFI_RESN_CD FROM KCAPXUT1.TPOTD WHERE CFI_RESN_CD != ''''')

	--Accounting Transaction [In Business Day]
	SELECT * INTO #TACTX FROM OPENQUERY(ING77UAT,'SELECT ACCT_TRXN_PAY_TYP_CD, POL_ID FROM KCAPXUT1.TACTX WHERE BUS_FCN_ID = ''0222''')

	-- GET ONLY FAIL CRITERIA CODE - CRI
	SELECT POL_ID, STUFF( (SELECT  ', '+LTRIM(RTRIM(AUTO_UW_REL_CD)) +':'+ LTRIM(RTRIM(AUTO_UW_RULE_CD))
			FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T WHERE T.POL_ID = T1.POL_ID
			FOR XML PATH('')),1,1,'') AUTO_UW_RULE_CD
	INTO #CRI
	FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T1
	GROUP BY POL_ID

    -- VER.5
    SELECT * INTO #POL FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TPOL')

	SELECT POL.POL_ID
		,POL_APP_FORM_ID = RTRIM(POL.POL_APP_FORM_ID)
		,POL.POL_INFC_DT
		,APE = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END * 
			(CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL.POL_BILL_MODE_CD AS INT) END)	-- APE/AFYP
		,POL_MPREM_AMT = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
		,POL.POL_BILL_MODE_CD
		,POL_BILL_MODE_DESC = RTRIM(BLM.ETBL_DESC_TXT)
		,POL.POL_CSTAT_CD 
		,POL_CSTAT_DESC = RTRIM(PARA.DM_AV_DESC_TXT)
		,PO_ID = PO.CLI_ID
		,PO_NAME = RTRIM(LTRIM(PONM.ENTR_SUR_NM))+' '+ RTRIM(LTRIM(PONM.ENTR_GIV_NM))
		,PO_CELL_PHONE = RTRIM(CONT.MO)
		,POL_REJ_EFF_DT = ISNULL(POL.POL_REJ_EFF_DT,POL.POL_STAT_CHNG_DT) 
		,REJECT_REASON = 
			CASE WHEN POL.POL_CSTAT_CD='1' THEN ' ' 
			ELSE (CASE WHEN POL.POL_REJ_REASN_CD='PP' THEN POL.POL_REJ_REASN_CD 
				WHEN POL.POL_REJ_REASN_CD='NP' THEN 'WD' 
				WHEN POL.POL_REJ_REASN_CD='NT' THEN 'CFI' 
				WHEN POL.POL_REJ_REASN_CD='DC' THEN 'DECLINED' 
				WHEN POL.POL_REJ_REASN_CD='FC' THEN 'NTU' ELSE '' END) 
			END 
		,POL.POL_REJ_REASN_CD	
		,ACTH.USER_ID
		,ACTH.ACCT_BASE_ID
		,ACTH.BPF_ID
		,ACTH.BUS_FCN_ID		
		,ACTH.ACCT_HIST_PST_DT
		,ACTH.ACCT_HIST_AMT
		,ACTH.ACCT_DESC_REASN_CD
		,ACCT_DESC_TXT = RTRIM(ACTH.ACCT_DESC_TXT)
		,CHQ_DESC_LN_1_TXT = RTRIM(CHTX.CHQ_DESC_LN_1_TXT)
		,CHQ_DTL_VALU_TXT = RTRIM(CHDL.CHQ_DTL_VALU_TXT)
		,CHTX.CHQ_BTCH_NUM
		,AGT.AGT_ID
		,AGENT_NAME = RTRIM(LTRIM(AGT.ENTR_SUR_NM))+' '+ RTRIM(LTRIM(AGT.ENTR_GIV_NM)) 
		,AGENT_LEADER_ID = AGL.AGT_ID
		,AGENT_LEADER_NAME = RTRIM(LTRIM(AGL.ENTR_SUR_NM))+' '+ RTRIM(LTRIM(AGL.ENTR_GIV_NM)) 
		,AGENT_MANAGER_ID = AGM.AGT_ID
		,AGENT_MANAGER_NAME = RTRIM(LTRIM(AGM.ENTR_SUR_NM))+' '+ RTRIM(LTRIM(AGM.ENTR_GIV_NM)) 
		,AGT.AGT_DISB_CHNL
		,AGT.AGT_DISB_CHNL_DESC
		,POL.POL_MEDIC_FEE_AMT
		,POL.REJ_REMKS_CD
		,POTD.CFI_RESN_CD
		,CFI_REASON = RTRIM(REJR.ETBL_DESC_TXT)
		,[PaymentTypeCode]= ISNULL(accTrx.ACCT_TRXN_PAY_TYP_CD,ACTH.ACCT_HIST_PAY_TYP_CD)
		,[PaymentType]=pyTyp.ETBL_DESC_TXT
		,POL.APP_SUBMIT_CD
		--VERS0.4 ADDING DISCOUNT % DL-236
		,ORIGINAL_PRM =  CASE WHEN CVG.CVG_UNDSCNT_PREM = 0 THEN (CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END) ELSE CVG.CVG_UNDSCNT_PREM END
		,AUTO_DIS = CVG.CVG_PREM_DISC_2_FCT
		,MAN_DIS = CVG.CVG_PREM_DISC_1_FCT
	    ,CASE_STT = CASE WHEN POL.POL_CASE_STAT_CD ='M' THEN 'Manual' WHEN POL.POL_CASE_STAT_CD ='A' THEN 'Auto' ELSE '' END
		,CASE_STT_RMKS = POLC.POL_UW_RMRKS
		,CRI.AUTO_UW_RULE_CD
        ,POL1.AML_STAT_CD AML_CODE -- VER.5
        ,RTRIM(STP.ETBL_DESC_TXT) STP_CODE -- VER.6

	INTO #MAIN_TMP
		
	FROM SGTB_POLICY POL
	
	LEFT JOIN SGTM_COVERAGE CVG ON CVG.POL_ID = POL.POL_ID
	LEFT JOIN SGTB_POLICY_CLIENT POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = 'O'
	LEFT JOIN SGTB_ACCOUNTING_TRANHIS ACTH ON ACTH.POL_ID = POL.POL_ID
	LEFT JOIN #TCHTX CHTX ON ACTH.POL_ID = CHTX.CHQ_REF_ID AND ACTH.ACCT_HIST_BTCH_NUM = CHTX.CHQ_BTCH_NUM AND ACTH.ACCT_HIST_AMT = CHTX.CHQ_AMT
	LEFT JOIN #TCHDL CHDL ON CHTX.CHQ_GEN_ID = CHDL.CHQ_GEN_ID AND RTRIM(CHDL.[CHQ_DTL_FLD_ID])='REASN'
	LEFT JOIN #TPOTD POTD ON POL.POL_ID = POTD.POL_ID 
	LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE POL0 ON POL.POL_ID = POL0.POL_ID
	LEFT JOIN SGTB_POLICY_CLIENT PO ON POL.POL_ID = PO.POL_ID AND PO.POL_CLI_REL_TYP_CD = 'O'
	LEFT JOIN SGTM_CLIENT_IND PONM ON PO.CLI_ID = PONM.CLI_ID AND PONM.PREV_UPDT_TS = (SELECT MAX(PREV_UPDT_TS) FROM SGTM_CLIENT_IND  WHERE CLI_ID = PO.CLI_ID GROUP BY CLI_ID)
	LEFT JOIN V_PIVOT_CLIENT_CONTACT CONT ON PO.CLI_ID = CONT.CLI_ID
	LEFT JOIN SGTB_POLICY_WRITING W ON W.POL_ID = POL.POL_ID
	LEFT JOIN #AGT AGT ON W.AGT_ID = AGT.AGT_ID
	LEFT JOIN #AGT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
	LEFT JOIN SGTM_PARA_1 PARA ON POL.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.CO_ID = 'CP' AND PARA.DM_AV_DESC_LANG_CD = 'E' 
	LEFT JOIN SGTB_EDITTABLE BLM ON POL.POL_BILL_MODE_CD = BLM.ETBL_VALU_ID AND BLM.ETBL_TYP_ID = 'BILL-MODE' AND BLM.CO_ID = 'CP' AND BLM.ETBL_LANG_CD = 'E'
	LEFT JOIN SGTB_EDITTABLE REJR ON CASE POL.POL_CSTAT_CD WHEN 'A' THEN POTD.CFI_RESN_CD WHEN 'R' THEN POL.REJ_REMKS_CD ELSE '' END = REJR.ETBL_VALU_ID AND REJR.ETBL_TYP_ID = 'REJRMK' AND BLM.CO_ID = 'CP' AND BLM.ETBL_LANG_CD = 'E'

	-- Load Payment type
	 LEFT JOIN #TACTX accTrx ON accTrx.POL_ID=POL.POL_ID
	 LEFT JOIN SGTB_EDITTABLE pyTyp ON pyTyp.ETBL_TYP_ID='PMTTYP' AND pyTyp.ETBL_VALU_ID=ISNULL(accTrx.ACCT_TRXN_PAY_TYP_CD,ACTH.ACCT_HIST_PAY_TYP_CD)
	
	--GET FAIL CRITERIA CODE----
	LEFT JOIN #CRI CRI ON POL.POL_ID = CRI.POL_ID 

    LEFT JOIN #POL POL1 ON POL1.POL_ID = POL.POL_ID -- VER.5
    LEFT JOIN SGTB_EDITTABLE STP ON STP.ETBL_VALU_ID = POL.POL_STP_CD AND STP.ETBL_TYP_ID = 'STPCD' -- VER.6

	WHERE ACTH.BUS_FCN_ID  = '0222'	-- DISBURSEMENT
	AND ACTH.ACCT_HIST_SRC_CD = 'P'	-- P = PAYMENT
	AND ACTH.ACCT_HIST_GEN_ID != '310375527'	-- DUPLICATE RECORD IN ING
	AND ACTH.ETL_DATE = @AS_OF
	AND ACTH.ACCT_HIST_PST_DT BETWEEN @START AND @END
	ORDER BY POL.POL_ID

	/*

	SELECT ACCT_HIST_PAY_TYP_CD,* FROM [PRD].DB77IPR1.KCAPXPR1.TACTH
	WHERE BUS_FCN_ID = '0222' 
	--AND POL_ID='700009176'
	ORDER BY ACCT_HIST_PRCES_DT DESC

	SELECT ACCT_HIST_PAY_TYP_CD,* FROM DLKHDIM..TACTH
	WHERE BUS_FCN_ID = '0222' 
	--AND POL_ID='700009176'
	ORDER BY ACCT_HIST_PRCES_DT DESC

	*/

	--EXEC [RPT_REFUND] '2022-12-28','',''

	SELECT DISTINCT MAIN_TMP.*
		,TOTAL_DIS_AMT = CASE WHEN (MAIN_TMP.ORIGINAL_PRM - MAIN_TMP.POL_MPREM_AMT) < 0 THEN 0 ELSE (MAIN_TMP.ORIGINAL_PRM - MAIN_TMP.POL_MPREM_AMT) END
		--,MP_BE_DIS = CASE WHEN (MAIN_TMP.POL_MPREM_AMT + ( MAIN_TMP.ORIGINAL_PRM - MAIN_TMP.POL_MPREM_AMT)) <= 0 THEN MAIN_TMP.POL_MPREM_AMT ELSE (MAIN_TMP.POL_MPREM_AMT + ( MAIN_TMP.ORIGINAL_PRM - MAIN_TMP.POL_MPREM_AMT)) END 
	FROM #MAIN_TMP MAIN_TMP 
	--WHERE POL_ID = '700000862'

	ORDER BY POL_ID
