
CREATE OR ALTER PROCEDURE [dbo].[RPT_UW_REPORT] @STAT_DATE DATE, @END_DATE DATE AS 

--DECLARE  @STAT_DATE DATE = '2025-10-18' ,
--		 @END_DATE DATE = '2025-10-25'

DROP TABLE IF EXISTS	#TREQT
DROP TABLE IF EXISTS    #TCLNM
DROP TABLE IF EXISTS	#TPOL
DROP TABLE IF EXISTS	#TPOLC
DROP TABLE IF EXISTS	#TPOLW
DROP TABLE IF EXISTS	#TCVG
DROP TABLE IF EXISTS	#TCVGC
DROP TABLE IF EXISTS    #UWG
DROP TABLE IF EXISTS    #ME
DROP TABLE IF EXISTS    #ALI
DROP TABLE IF EXISTS    #ALII
DROP TABLE IF EXISTS    #ALI2
DROP TABLE IF EXISTS    #AGENT

SELECT * , ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY UWG_CREAT_DT ASC) AS ROW_NUM
INTO #UWG FROM OPENQUERY(UAT7, '
SELECT S.POL_ID,S.UWG_SUMM_TXT,S.UWG_CREAT_USER_ID,S.UWG_CREAT_DT,S.UWG_UPDATE_DT,S.UWG_SEQ_NUM,S.PREV_UPDT_USER_ID,
P.UWG_USER_1_ID, P.UWG_DECID_1_DT, P.UWG_USER_2_ID, P.UWG_DECID_2_DT, P.UWG_SUMM_CSTAT_1_CD,P.UWG_SUMM_CSTAT_2_CD, 
P.UWG_SUMM_1_TXT, P.UWG_SUMM_2_TXT,
D.DM_AV_MODEL_TXT UWG_SUMM_CSTAT_1_DESC ,D1.DM_AV_MODEL_TXT UWG_SUMM_CSTAT_2_DESC
FROM KCAPXUAT.TZUWS S
LEFT JOIN KCAPXUAT.TZUWP P ON P.POL_ID = S.POL_ID
LEFT JOIN KCAPXUAT.TDMAV D ON D.DM_AV_CD = P.UWG_SUMM_CSTAT_1_CD AND D.DM_AV_TBL_CD = ''UWG-SUMM-CSTAT-CD''
LEFT JOIN KCAPXUAT.TDMAV D1 ON D1.DM_AV_CD = P.UWG_SUMM_CSTAT_2_CD AND D1.DM_AV_TBL_CD = ''UWG-SUMM-CSTAT-CD''
')
SELECT * INTO #TCVG  FROM OPENQUERY(UAT7,'SELECT POL_ID,CVG_CSTAT_CD, CVG_FACE_AMT, CVG_MPREM_AMT,CVG_NUM, CVG_MAT_XPRY_DUR,PLAN_ID,UWGDECN_COMNT_TXT,CVG_BASIC_PREM_AMT FROM KCAPXUAT.TCVG')

SELECT * INTO #TCVGC  FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TCVGC')

SELECT * INTO #TPOL  FROM OPENQUERY(UAT7,'
SELECT POL_ID,PLAN_ID,POL_APP_SIGN_DT,POL_APP_RECV_DT,POL_APP_FORM_ID,PREV_UPDT_USER_ID
,POL_CSTAT_CD,POL_ISS_EFF_DT,LOAN_CNTRCT_NUM,POL_REJ_REASN_CD,POL_BILL_MODE_CD,SERV_BR_ID,POL_GRS_APREM_AMT
,POL_MPREM_AMT,COLCT_MTHD_CD,POL_STAT_CHNG_DT,POL_SAR,CUST_SRC_CD,POL_CASE_STAT_CD,POL_INFC_DT,POL_REISS_DT, POL_BILL_TYP_CD
FROM KCAPXUAT.TPOL
')

SELECT * INTO #TPOLC  FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TPOLC WHERE POL_CLI_REL_TYP_CD = ''O'' ')

SELECT * INTO #TPOLW  FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TPOLW')

-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT,PREV_UPDT_TS
	, #NO = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY CLI_INDV_EFF_DT DESC)
INTO #TCLNM
FROM OPENQUERY(UAT7,
'	SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS
	FROM KCAPXUAT.TCLNM
')

SELECT REQT.*, NJET.GRP_CD, NJET.NON_JET_STAT_CD INTO #TREQT FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TREQT WHERE CPREQ_POL_CLI_CD = ''P'' ') REQT 
INNER JOIN V_GET_NON_JET_AND_INCOMPLETE_CODE NJET ON REQT.REQIR_ID = NJET.REQIR_ID  

SELECT * INTO #ME  FROM (SELECT *  FROM #TREQT WHERE GRP_CD = 'ME' ) ME

SELECT  DISTINCT POLC.POL_ID,POLC.CLI_ID,ALIID1.INSRD_CLI_ID,ALIID1.CVG_NUM,ALNAME1.ENTR_SUR_NM,ALNAME1.ENTR_GIV_NM,ALNAME1.PREV_UPDT_TS 
INTO #ALI 
FROM #TPOLC POLC
LEFT JOIN #TCVGC ALIID1 ON ALIID1.POL_ID = POLC.POL_ID AND ALIID1.CVG_NUM != '01' AND ALIID1.INSRD_CLI_ID != POLC.CLI_ID
LEFT JOIN #TCLNM ALNAME1 ON ALNAME1.CLI_ID = ALIID1.INSRD_CLI_ID AND #NO = 1
WHERE  POLC.POL_CLI_REL_TYP_CD = 'O' 

SELECT * INTO #ALII FROM (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY CVG_NUM) AS ROW#,*  FROM #ALI) ALII

-- GET SOME INFO OF AGENT ONLY 
SELECT * INTO #AGENT  FROM V_DMS_AGENT_REPORTING_LINE_LIVE

SELECT DISTINCT POL.POL_ID,
	RTRIM(POL.POL_APP_FORM_ID) APPLICATION_NO,
	POLC.CLI_ID PO_ID, 
	CONCAT(RTRIM(PONM.ENTR_SUR_NM),' ', RTRIM(PONM.ENTR_GIV_NM)) PO_NAME,
	BLI.INSRD_CLI_ID BLI_ID,
	CONCAT(RTRIM(BLNM.ENTR_SUR_NM),' ', RTRIM(BLNM.ENTR_GIV_NM)) BLI_NAME
	,ALI1_ID  = ALI1.INSRD_CLI_ID
	,ALI1_Name =RTRIM(ALI1.ENTR_SUR_NM)+ ' '+ RTRIM(ALI1.ENTR_GIV_NM)
	,ALI2_ID = ALI2.INSRD_CLI_ID
	,ALI2_Name = RTRIM(ALI2.ENTR_SUR_NM)+ ' '+ RTRIM(ALI2.ENTR_GIV_NM)
	,POL_COMM_DT =POL.POL_ISS_EFF_DT
	,POL.POL_INFC_DT ISSUED_DATE
	,POL.POL_REISS_DT REISS_DATE 
	,POL.POL_APP_RECV_DT
	,Main_Product = RTRIM(PLN.ETBL_DESC_TXT)
	,CTERM.CVG_MAT_XPRY_DUR POL_TERM
	,MODE_OF_PAY = CASE WHEN POL.PLAN_ID = 'KBE003' THEN CASE WHEN POL.POL_BILL_TYP_CD = 'P' THEN 'Single Pay' ELSE 'Regular Pay' END  ELSE RTRIM(BLLM.ETBL_DESC_TXT)  END
	,Face_Amount = CVG.FACE_AMT
	,MD_Premium = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END 
	,APE_AFYP = (FN_AFYP.multiplier) * CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END * (12 / CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE CAST(POL.POL_BILL_MODE_CD AS INT) END )
	,RTRIM(PSTAT.DM_AV_DESC_TXT) POL_STATUS
	,POL_SAT_DT = POL.POL_STAT_CHNG_DT
	,DIST_CHANHEL = AGD.CHANNEL_DESC
	,AGD.AGENT_NAME AGE_NAME
	,AGD.ManagerName AGE_MG_NAME
	,ME1_RQ_DT = TME1.CPREQ_CREAT_DT
	,ME1_RC_DT = TME1.CPREQ_TST_DT
	,ME2_RQ_DT = TME2.CPREQ_CREAT_DT
	,ME2_RC_DT = TME2.CPREQ_TST_DT
	,ME3_RQ_DT = TME3.CPREQ_CREAT_DT
	,ME3_RC_DT = TME3.CPREQ_TST_DT 
	,COL_CRE_DT = TCOL.CPREQ_CREAT_DT
	,RC_COL_DT = TCOL.CPREQ_TST_DT
	--,IA_RQ_DT = TIA.CPREQ_CREAT_DT
	--,OTR_RQ_DT = TOTR.CPREQ_CREAT_DT 
	,UW_SUM_1CRE_DT = UWG.UWG_CREAT_DT
	,UW_DEC = RTRIM(UWG.UWG_SUMM_CSTAT_2_DESC)
	,ST_UW_DEC_DT= UWG.UWG_DECID_1_DT
	,ND_UW_DEC_DT = UWG.UWG_DECID_2_DT
	,UW = UWG.UWG_USER_1_ID
	,UW2 = UWG.UWG_USER_2_ID
	,IS_USER = UWG.PREV_UPDT_USER_ID
	,POL_REJ_REAS = RTRIM(CTERM.UWGDECN_COMNT_TXT)
	,RTRIM(CS.DM_AV_DESC_TXT) CASE_STATUS
	,PCVG.POL_BASIC_MPREM_AMT
	--DL-1856
	,MR.HAS_MEDICAL_RIDER
	,MR_CVG_MPREM_AMT = CASE WHEN MR.HAS_MEDICAL_RIDER = 1 THEN MR.MR_CVG_MPREM_AMT ELSE NULL END
	,MR_CVG_FACE_AMT = CASE WHEN MR.HAS_MEDICAL_RIDER = 1 THEN MR.MR_CVG_FACE_AMT ELSE NULL END
	,PO_OCC_NAME = OCC.ETBL_DESC_TXT
	,PO_OCC_CLASS = OCC_CL.ETBL_DESC_TXT
	--DL-1856
    ,AGD.AGENT_TYPE
FROM #TPOL POL
LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE_LIVE POL0 ON POL0.POL_ID = POL.POL_ID
LEFT JOIN #TPOLC POLC ON POLC.POL_ID = POL.POL_ID
LEFT JOIN #TCLNM PONM ON POLC.CLI_ID= PONM.CLI_ID AND PONM.#NO = 1
LEFT JOIN #TCVGC BLI ON BLI.POL_ID = POL.POL_ID AND CVG_NUM = '01'
LEFT JOIN #TCLNM BLNM ON BLI.INSRD_CLI_ID= BLNM.CLI_ID AND BLNM.#NO = 1
LEFT JOIN #TCVG CTERM ON  CTERM.POL_ID = POL.POL_ID AND CTERM.CVG_NUM = '01'

LEFT JOIN (
		SELECT POL_ID
	, POL_BASIC_MPREM_AMT = SUM(CVG_BASIC_PREM_AMT)
	FROM #TCVG 
	GROUP BY POL_ID
) PCVG ON PCVG.POL_ID = POL.POL_ID

LEFT JOIN ( SELECT POL_ID, CVG_CSTAT_CD , SUM(CVG_MPREM_AMT) AS [CoveragePremium], SUM(CVG_FACE_AMT) AS FACE_AMT,SUM(CVG_MPREM_AMT) AS UW_AMT FROM  #TCVG GROUP BY POL_ID,CVG_CSTAT_CD ) CVG ON CVG.POL_ID=POL.POL_ID AND CVG.CVG_CSTAT_CD=POL.POL_CSTAT_CD

LEFT JOIN SGTB_EDITTABLE PLN ON PLN.ETBL_VALU_ID = POL.PLAN_ID AND PLN.ETBL_TYP_ID = 'PLAN'
LEFT JOIN SGTB_EDITTABLE BLLM ON BLLM.ETBL_VALU_ID = POL.POL_BILL_MODE_CD AND BLLM.ETBL_LANG_CD = 'E' AND BLLM.CO_ID = 'CP' AND BLLM.ETBL_TYP_ID = 'BILL-MODE'
LEFT JOIN SGTM_PARA_1 PSTAT ON PSTAT.DM_AV_CD = POL.POL_CSTAT_CD AND PSTAT.DM_AV_TBL_CD='POL-CSTAT-CD' AND PSTAT.DM_AV_DESC_LANG_CD = 'E' AND PSTAT.CO_ID = 'CP'

LEFT JOIN #TPOLW POW ON POW.POL_ID = POL.POL_ID
LEFT JOIN #AGENT AGD ON POW.AGT_ID = CAST(AGD.AGENT_CODE AS VARCHAR)
LEFT JOIN SGTB_EDITTABLE RJR ON RJR.ETBL_VALU_ID = POL.POL_REJ_REASN_CD AND RJR.ETBL_TYP_ID = 'REJCD'

LEFT JOIN #UWG  UWG ON UWG.POL_ID = POL.POL_ID AND ROW_NUM = 1

LEFT JOIN #TREQT TCOL ON POL.POL_ID = TCOL.POL_CLI_ID AND TCOL.GRP_CD = 'COL'
LEFT JOIN (SELECT * FROM #ME) TME1 ON POL.POL_ID = TME1.POL_CLI_ID AND TME1.GRP_CD = 'ME' AND TME1.REQIR_ID IN ('0031','0032', '0033','0034','0035','0036','0037','0038','0039','0040')
LEFT JOIN (SELECT * FROM #ME) TME2 ON POL.POL_ID = TME2.POL_CLI_ID AND TME2.GRP_CD = 'ME' AND TME2.REQIR_ID = '0029'
LEFT JOIN (SELECT * FROM #ME) TME3 ON POL.POL_ID = TME3.POL_CLI_ID AND TME3.GRP_CD = 'ME' AND TME3.REQIR_ID = '0030'

LEFT JOIN #ALII ALI1 ON ALI1.POL_ID = POLC.POL_ID AND ALI1.ROW# = 1
LEFT JOIN #ALII ALI2 ON ALI2.POL_ID = POLC.POL_ID AND ALI2.ROW# = 2

LEFT JOIN SGTM_PARA_1 CS ON CS.DM_AV_CD = POL.POL_CASE_STAT_CD AND CS.DM_AV_TBL_CD = 'POL-CASE-STAT-CD'
--DL-1856
LEFT JOIN (
    SELECT 
        POL_ID,
        HAS_MEDICAL_RIDER = 1,
        CVG_MPREM_AMT AS MR_CVG_MPREM_AMT,
        CVG_FACE_AMT as MR_CVG_FACE_AMT
    FROM #TCVG
    WHERE PLAN_ID IN ('DRM001')
) MR ON MR.POL_ID = POL.POL_ID

LEFT JOIN SGTM_CLIENT CLI ON CLI.CLI_ID = POLC.CLI_ID AND POL_CLI_REL_TYP_CD = 'O'
LEFT JOIN SGTB_EDITTABLE OCC ON OCC.ETBL_VALU_ID = CLI.OCCP_ID AND OCC.ETBL_TYP_ID = 'OCCCD'
LEFT JOIN SGTB_EDITTABLE OCC_CL ON OCC_CL.ETBL_VALU_ID = CLI.CLI_OCCP_CLAS_CD AND OCC_CL.ETBL_TYP_ID = 'OCCCL'
--DL-1856
OUTER APPLY DLKHSTAGE.dbo.FN_GET_AFYP_MULTIPLIER(POL.PLAN_ID, POL.POL_BILL_TYP_CD) FN_AFYP

WHERE 1 = 1
AND POL.POL_APP_RECV_DT BETWEEN @STAT_DATE AND @END_DATE
-- AND POL.POL_ID = '700039818'