

CREATE PROCEDURE [dbo].[RPT_UEF_CERTIFICATE] 
	@Start DATE = NULL
	,@End DATE = NULL
AS 
BEGIN

	DROP TABLE IF EXISTS	#UEF 
	SELECT  POLC.POL_ID, FORMAT(CVG.CVG_MAT_XPRY_DT,' dd/MMM/yyyy') AS MATURITY_DATE, PO_NAME = RTRIM(CLNM.ENTR_SUR_NM) + ' ' + RTRIM(CLNM.ENTR_GIV_NM), POL.POL_ISS_EFF_DT INTO #UEF
				FROM SGTB_POLICY_CLIENT POLC
				INNER JOIN SGTM_COVERAGE CVG ON POLC.POL_ID = CVG.POL_ID AND CVG.CVG_NUM = '01'
				INNER JOIN SGTM_CLIENT_IND CLNM ON POLC.CLI_ID = CLNM.CLI_ID
				INNER JOIN SGTB_POLICY POL ON POLC.POL_ID = POL.POL_ID AND POL.POL_NOT LIKE 'UEF'
	IF @Start IS NOT NULL AND @End IS NOT NULL
		SELECT * FROM #UEF UEF WHERE UEF.POL_ISS_EFF_DT BETWEEN @Start AND @End ORDER BY UEF.POL_ISS_EFF_DT DESC
	ELSE 
		SELECT * FROM #UEF UEF ORDER BY UEF.POL_ISS_EFF_DT DESC
END
