

CREATE PROC [dbo].[RPT_OUTSTANDING]
	@START_DATE		DATE = NULL
	,@END_DATE		DATE = NULL
AS

	-- DECLARE @START_DATE		DATE = '2026-01-01'
			-- ,@END_DATE		DATE = '2026-06-01'

	DROP TABLE IF EXISTS #TDMAD
	DROP TABLE IF EXISTS #TPHST
	DROP TABLE IF EXISTS #TEDIT
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #TCLIC
	DROP TABLE IF EXISTS #TCLIA
	DROP TABLE IF EXISTS #TCVG
	DROP TABLE IF EXISTS #TPOL
	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS  #CRI

	IF ISNULL(@START_DATE,'') = '' SET @START_DATE = '2000-01-01'
	IF ISNULL(@END_DATE,'') = '' SET @END_DATE = CONVERT(DATE,GETDATE())

	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #TEDIT FROM OPENQUERY(UAT7,
	'	SELECT ETBL_TYP_ID,ETBL_VALU_ID,ETBL_DESC_TXT FROM KCAPXUAT.TEDIT
		WHERE CO_ID = ''CP'' AND ETBL_LANG_CD = ''E'' AND ETBL_TYP_ID IN (''CEASE'',''PLAN'',''DCHNL'')
	')

	SELECT DM_AV_CD,DM_AV_TBL_CD,DM_AV_DESC_TXT = RTRIM(DM_AV_DESC_TXT) INTO #TDMAD FROM SGTM_PARA_1 
	WHERE CO_ID = 'CP' AND DM_AV_DESC_LANG_CD = 'E' AND DM_AV_TBL_CD IN ('POL-CSTAT-CD')

	SELECT POL_ID,CVG_NUM,POL_ACTV_TYP_ID,PREV_UPDT_TS,PCHST_EFF_DT 
		,#LAST_UPDT_PHST = ROW_NUMBER() OVER (PARTITION BY POL_ID ORDER BY PCHST_EFF_DT DESC,PREV_UPDT_TS DESC)	
	INTO #TPHST FROM OPENQUERY(UAT7,
	'	SELECT POL_ID,CVG_NUM,POL_ACTV_TYP_ID,PREV_UPDT_TS,PCHST_EFF_DT
		FROM KCAPXUAT.TPHST
		WHERE POL_ACTV_TYP_ID = ''3003''
	')

	-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT
		,CLI_INDV_GR_CD
		,#LAST_UPTD_NM = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM
	FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS,CLI_INDV_GR_CD
		FROM KCAPXUAT.TCLNM
	')

	-- GET ONLY REQUIRED INFO OF CLIENT CONTACT - TCLIC
	SELECT CLI_ID,CLI_CNTCT_ID_CD,CLI_CNTCT_ID_TXT = RTRIM(CLI_CNTCT_ID_TXT)
	INTO #TCLIC FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_CNTCT_ID_CD,CLI_CNTCT_ID_TXT
		FROM KCAPXUAT.TCLIC
		WHERE LENGTH(RTRIM(CLI_ID)) >= 10
	')

	-- GET ONLY REQUIRED INFO ON CLIENT ADDRESS - TCLIA
	SELECT CLI_ID,CLI_ADDR_LN_1_TXT = RTRIM(CLI_ADDR_LN_1_TXT),CLI_ADDR_LN_2_TXT = RTRIM(CLI_ADDR_LN_2_TXT)
		,CLI_ADDR_LN_3_TXT = RTRIM(CLI_ADDR_LN_3_TXT),CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD,CLI_CRNT_LOC_CD
		,CLI_ADDR_STAT_CD,CLI_ADDR_GR_CD,CLI_ADDR_TYP_CD,CLI_ADDR_EFF_DT,CLI_CITY_NM_TXT
	INTO #TCLIA FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_ADDR_LN_1_TXT,CLI_ADDR_LN_2_TXT,CLI_ADDR_LN_3_TXT,CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD,CLI_CRNT_LOC_CD,CLI_ADDR_STAT_CD
			,CLI_ADDR_GR_CD,CLI_ADDR_TYP_CD,CLI_ADDR_EFF_DT,CLI_CITY_NM_TXT
		FROM KCAPXUAT.TCLIA
		WHERE CLI_ADDR_TYP_CD = ''PR''
			AND LENGTH(RTRIM(CLI_ID)) >= 10
	')

	SELECT *,CVG_TERM_AT_POS = ROW_NUMBER() OVER(PARTITION BY POL_ID ORDER BY CVG_MAT_XPRY_DUR DESC)
	INTO #TCVG FROM OPENQUERY(UAT7,
	'	SELECT CVG.POL_ID,CVG.CVG_NUM,CVG.CVG_MAT_XPRY_DUR
			,CVGC.INSRD_CLI_ID 
		FROM KCAPXUAT.TCVG CVG
		INNER JOIN KCAPXUAT.TCVGC CVGC ON CVG.POL_ID = CVGC.POL_ID AND CVG.CVG_NUM = CVGC.CVG_NUM
	')

	SELECT * INTO #TPOL FROM OPENQUERY(UAT7,
	'	SELECT POL.POL_ID,POL.POL_BASE_CVG_NUM,POL.POL_CSTAT_CD,POL.POL_CEAS_REASN_CD,POL.POL_ISS_EFF_DT
			,POL.POL_INFC_DT,POL.POL_OS_DISB_AMT,POL.POL_OS_DISB_DT,POL.PLAN_ID
			,POLC.CLI_ID,POLW.AGT_ID
			,POL.POL_CASE_STAT_CD
			,POLC.POL_UW_RMRKS
		FROM KCAPXUAT.TPOL POL
		INNER JOIN KCAPXUAT.TPOLC POLC ON POL.POL_ID = POLC.POL_ID
		INNER JOIN KCAPXUAT.TPOLW POLW ON POL.POL_ID = POLW.POL_ID
		WHERE POL.POL_OS_DISB_AMT != 0 AND POLC.POL_CLI_REL_TYP_CD = ''O''
	')
	
	-- GET SOME INFO OF AGENT ONLY 
	SELECT AG.AGT_ID,AG.AGT_DISB_CHNL,AGT_DISB_CHNL_DESC = CHNL.ETBL_DESC_TXT,AG.OVRID_BASE_AGT_ID,AGNM.ENTR_SUR_NM,AGNM.ENTR_GIV_NM
	INTO #AGENT 
	FROM OPENQUERY(UAT7,
	'	SELECT AGT_ID,AGT_DISB_CHNL,OVRID_BASE_AGT_ID
		FROM KCAPXUAT.TAG
	') AG
	LEFT JOIN #TCLNM AGNM ON AG.AGT_ID = AGNM.CLI_ID AND AGNM.#LAST_UPTD_NM = 1
	LEFT JOIN #TEDIT CHNL ON AG.AGT_DISB_CHNL = CHNL.ETBL_VALU_ID AND ETBL_TYP_ID = 'DCHNL'

	-- GET ONLY FAIL CRITERIA CODE - CRI
	SELECT POL_ID, STUFF( (SELECT  ', '+LTRIM(RTRIM(AUTO_UW_REL_CD)) +':'+ LTRIM(RTRIM(AUTO_UW_RULE_CD))
			FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T WHERE T.POL_ID = T1.POL_ID
			FOR XML PATH('')),1,1,'') AUTO_UW_RULE_CD
	INTO #CRI
	FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T1
	GROUP BY POL_ID

	SELECT GETDATE() AS REPT_DT
		,TPOL.POL_ID
		,TPOL.POL_ISS_EFF_DT
		,TPOL.POL_INFC_DT
		,TPHST.PCHST_EFF_DT
		,TPOL.POL_OS_DISB_AMT
		,TPOL.POL_OS_DISB_DT
		,POL_STATUS = TDMAD.DM_AV_DESC_TXT
		,CASE WHEN TPOL.POL_CSTAT_CD = 'E' THEN TEDIT.ETBL_DESC_TXT ELSE '' END AS TPOL_REASON_TERM
		,TPOL.CLI_ID
		,POL_OWN_NAME = TCLNM.ENTR_SUR_NM + ' ' + TCLNM.ENTR_GIV_NM
		,POL_OWNER_ADDRESS1 = TOWNA.CLI_ADDR_LN_1_TXT
		,POL_OWNER_ADDRESS2 = TOWNA.CLI_ADDR_LN_2_TXT
		,POL_OWNER_ADDRESS3 = CLI_ADDR_LN_3_TXT
		,POL_OWNER_ADDRESS4 = CLI_CITY_NM_TXT
		,TCLIC1.CLI_CNTCT_ID_TXT AS PO_CEL_TEL
		,TCLIC2.CLI_CNTCT_ID_TXT AS PO_BIZ_TEL
		,TCLIC3.CLI_CNTCT_ID_TXT AS PO_RES_TEL
		,POL_INSRD_NAME = TLIFE.ENTR_SUR_NM + ' ' + TLIFE.ENTR_GIV_NM 
		,TPOL.AGT_ID
		,TPOL.PLAN_ID
		,PLAN_NAME = TEDIT1.ETBL_DESC_TXT
		,CHANNEL = AGT.AGT_DISB_CHNL_DESC
		,AGENT_NAME = AGT.ENTR_SUR_NM + ' ' + AGT.ENTR_GIV_NM 
		,ABM_NAME = AGM.ENTR_SUR_NM + ' ' + AGM.ENTR_GIV_NM
		,TCVG.CVG_MAT_XPRY_DUR
		,CASE_STT = CASE WHEN TPOL.POL_CASE_STAT_CD ='M' THEN 'Manual' WHEN TPOL.POL_CASE_STAT_CD ='A' THEN 'Auto' ELSE '' END
		,CASE_STT_RMKS = TPOL.POL_UW_RMRKS
		,CRI.AUTO_UW_RULE_CD
    ,AGT_INFO.AGENT_TYPE
	FROM #TPOL TPOL
	INNER JOIN #TCVG TCVG ON TCVG.POL_ID = TPOL.POL_ID AND TCVG.CVG_TERM_AT_POS = 1
	LEFT JOIN #TPHST TPHST ON TPHST.POL_ID = TPOL.POL_ID AND TPHST.#LAST_UPDT_PHST = 1
	LEFT JOIN #TCLNM TCLNM ON TPOL.CLI_ID = TCLNM.CLI_ID AND TCLNM.#LAST_UPTD_NM = 1
	LEFT JOIN #TCLIC TCLIC1 ON TCLIC1.CLI_ID = TPOL.CLI_ID AND TCLIC1.CLI_CNTCT_ID_CD = 'CP'
	LEFT JOIN #TCLIC TCLIC2 ON TCLIC2.CLI_ID = TPOL.CLI_ID AND TCLIC2.CLI_CNTCT_ID_CD = 'MO'
	LEFT JOIN #TCLIC TCLIC3 ON TCLIC3.CLI_ID = TPOL.CLI_ID AND TCLIC3.CLI_CNTCT_ID_CD = 'HO'
	LEFT JOIN #TCLIA TOWNA ON TOWNA.CLI_ID = TPOL.CLI_ID
	LEFT JOIN #TCLNM TLIFE ON TCVG.INSRD_CLI_ID = TLIFE.CLI_ID AND TCVG.CVG_NUM = '01' AND TLIFE.#LAST_UPTD_NM = 1
	LEFT JOIN #TEDIT AS TEDIT1 ON TEDIT1.ETBL_TYP_ID = 'PLAN' AND TEDIT1.ETBL_VALU_ID = TPOL.PLAN_ID
	LEFT JOIN #TDMAD TDMAD ON TDMAD.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND TDMAD.DM_AV_CD = TPOL.POL_CSTAT_CD
	LEFT JOIN #TEDIT TEDIT ON TEDIT.ETBL_TYP_ID = 'CEASE' AND TEDIT.ETBL_VALU_ID = TPOL.POL_CEAS_REASN_CD
	LEFT JOIN #AGENT AGT ON TPOL.AGT_ID = AGT.AGT_ID
	LEFT JOIN #AGENT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID 
	LEFT JOIN #AGENT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
  LEFT JOIN DLKHSTAGE..DMS_AGENT_DETAIL AGT_INFO on CAST(AGT_INFO.AGENT_CODE AS VARCHAR)= TPOL.AGT_ID
  LEFT JOIN #CRI CRI ON TPOL.POL_ID = CRI.POL_ID 

	WHERE TPOL.POL_OS_DISB_DT BETWEEN @START_DATE AND @END_DATE
