

/***************************************************************************************************
	REPORT:.......... 
	PURPOSE:......... 
        
    Changelog
    ***********
	VERSION    DATE CHNG    UPDATE_BY    DESC
	VERS0.1    28-03-2024	 SOUTHEANE	 ADD RENEWAL AND COLLECTION METHOD
	VERS0.2    22-04-2024	 SOUTHEANE   ADD DIS % INFORMATION
    VERS0.3	   19-06-2025    SAVRATH     ADD AML STATUS [DL-1173]
    VERS0.4	   25-07-2025    SAVRATH     ADD STP STATUS [DL-1283]

****************************************************************************************************/
CREATE PROC [dbo].[RPT_PENDING] 
AS
	DROP TABLE IF EXISTS #POL
	DROP TABLE IF EXISTS #EDIT
	DROP TABLE IF EXISTS #PAR
	DROP TABLE IF EXISTS #XTAB
	DROP TABLE IF EXISTS #TREQ
	DROP TABLE IF EXISTS #NJET
	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS #CLNM
	DROP TABLE IF EXISTS #FPREM
	DROP TABLE IF EXISTS #TMP
    DROP TABLE IF EXISTS #CRI
	DROP TABLE IF EXISTS #APPTIME

	SELECT ETBL_VALU_ID, ETBL_TYP_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #EDIT 
	FROM OPENQUERY(UAT7,'SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT FROM KCAPXUAT.TEDIT WHERE ETBL_LANG_CD = ''E'' 
	AND CO_ID = ''CP'' AND ETBL_TYP_ID IN (''PLAN'',''DCHNL'' , ''RENWMCD'',''COMTH'')')  

	SELECT PAR.DM_AV_CD, PAR.DM_AV_TBL_CD, DM_AV_DESC_TXT = RTRIM(PAR.DM_AV_DESC_TXT) INTO #PAR
	FROM SGTM_PARA_1 PAR WHERE PAR.CO_ID = 'CP' AND PAR.DM_AV_DESC_LANG_CD = 'E' AND PAR.DM_AV_TBL_CD IN ('BILLN-MODE-CD')	-- 'POL-CSTAT-CD',

	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #XTAB FROM SGTM_PARA
	WHERE ETBL_LANG_CD = 'E' AND ETBL_TYP_ID = 'SOLDBR'

	-- GET ONLY POLICIES ARE PENDING
	SELECT POL.*, REMC.SUBMITED_TYPE 
	INTO #POL 
	FROM OPENQUERY(UAT7,
	'	SELECT POL.POL_ID
			,POL.POL_APP_FORM_ID,POL.POL_MPREM_AMT,POL.PLAN_ID,POL.POL_APP_RECV_DT,POL.POL_APP_CMPLT_DT
			,POL.POL_BILL_MODE_CD
			,CVG.CVG_NUM,CVG.CVG_MAT_XPRY_DUR,CVG.CVG_FACE_AMT
			,CVGC.INSRD_CLI_ID
			,POLW.AGT_ID
			,POLW.POL_SOLD_BR_ID,POL.APP_SUBMIT_CD
			,POL.COLCT_MTHD_CD
			,POL.POL_RENW_MTHD_CD
			,CVG.CVG_UNDSCNT_PREM
			,CVG.CVG_PREM_DISC_1_FCT
			,CVG.CVG_PREM_DISC_2_FCT
			,POL.POL_CASE_STAT_CD
			,POLC.POL_UW_RMRKS
            ,POL.AML_STAT_CD
            ,POL.POL_STP_CD
		FROM KCAPXUAT.TPOL POL
		INNER JOIN KCAPXUAT.TPOLC POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = ''O''
		LEFT JOIN KCAPXUAT.TPOLW POLW ON POL.POL_ID = POLW.POL_ID
		LEFT JOIN KCAPXUAT.TCVG CVG ON POL.POL_ID = CVG.POL_ID AND CVG.CVG_NUM = ''01''
		LEFT JOIN KCAPXUAT.TCVGC CVGC ON CVG.POL_ID = CVGC.POL_ID AND CVG.CVG_NUM = CVGC.CVG_NUM
		WHERE POL.POL_CSTAT_CD LIKE ''P%'' AND POL.POL_ID != ''700018430''
	') POL
	LEFT JOIN V_GET_REMOTE_CASE_OF_EXIST_POLICY REMC ON POL.POL_ID = REMC.POL_ID

	-- NB/UW REQUIREMENT
	SELECT *
	INTO #TREQ FROM OPENQUERY(UAT7,'SELECT POL_CLI_ID,REQIR_ID,CPREQ_SEQ_NUM,CPREQ_STAT_CD,RMRKS FROM KCAPXUAT.TREQT WHERE CPREQ_POL_CLI_CD = ''P'' AND CPREQ_STAT_CD IN (''ORD'',''RAC'')') REQ
	--INNER JOIN #POL POL ON POL.POL_ID = REQ.POL_CLI_ID
			

	-- NJET: COL, ME, IA, OTR
	-- EVEN IF THE NJET WITH SAME STATUS HAVE MORE THAN 1 FOR EACH POLICY, BUT GET ONLY FIRST
	SELECT DISTINCT REQ.POL_CLI_ID, NJET.GRP_CD, NJET.NON_JET_STAT_CD  INTO #NJET FROM #TREQ REQ
	INNER JOIN V_GET_NON_JET_AND_INCOMPLETE_CODE NJET ON REQ.REQIR_ID = NJET.REQIR_ID --AND REQ.CPREQ_SEQ_NUM = '001' 

	-- AGENT
	SELECT * INTO #AGENT FROM V_DMS_AGENT_REPORTING_LINE_LIVE

	-- CLIENT NANME
	SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC),CLNM.CLI_ID,ENTR_SUR_NM = RTRIM(CLNM.ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(CLNM.ENTR_GIV_NM)
		, CLI_FULL_NAME = RTRIM(CLNM.ENTR_SUR_NM) + ' ' + RTRIM(CLNM.ENTR_GIV_NM)
	INTO #CLNM FROM OPENQUERY(UAT7,'SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,PREV_UPDT_TS FROM KCAPXUAT.TCLNM') CLNM WHERE LEN(CLI_ID) >= 10

	-- GET INITIAL PREMIUM OF EACH POLICY
	SELECT POL.POL_ID, POL_INITIAL_PREM = SUM(CAST(ISNULL(ACTH.ACCT_HIST_AMT,0) AS BIGINT))
	INTO #FPREM
	FROM #POL POL
	LEFT JOIN OPENQUERY(UAT7,
	'	SELECT POL_ID,ACCT_HIST_AMT FROM KCAPXUAT.TACTH 
		WHERE BUS_FCN_ID NOT IN (''0222'') AND ACCT_BASE_ID =''249800''

		UNION ALL

		SELECT POL_ID,ACCT_TRXN_AMT FROM KCAPXUAT.TACTX
		WHERE BUS_FCN_ID NOT IN (''0222'') AND ACCT_BASE_ID =''249800''
	') ACTH ON POL.POL_ID = ACTH.POL_ID
	GROUP BY POL.POL_ID

	--GET DATE TIME APPLICATION RECIEVED FROM LOG 
	select CPEVNT_POL_CLI_ID, CPEVNT_TRXN_DT,CPEVNT_TRXN_TIME,
	FORMAT(CONVERT(bigint,CPEVNT_TRXN_TIME),'##:##:##') AS TMR_TIME INTO #APPTIME  
	from OPENQUERY(UAT7, 'SELECT * from KCAPXUAT.tdalg') WHERE BUS_FCN_ID = '8001';

	
	-- GET ONLY FAIL CRITERIA CODE - CRI
	SELECT POL_ID, STUFF( (SELECT  ', '+LTRIM(RTRIM(AUTO_UW_REL_CD)) +':'+ LTRIM(RTRIM(AUTO_UW_RULE_CD))
			FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T WHERE T.POL_ID = T1.POL_ID
			FOR XML PATH('')),1,1,'') AUTO_UW_RULE_CD
	INTO #CRI
	FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T1
	GROUP BY POL_ID

	SELECT POL.POL_ID
		,POL.POL_APP_FORM_ID
		,POL.POL_MPREM_AMT
		,POL.PLAN_ID
		,PLAN_DESC = PLN.ETBL_DESC_TXT
		,POL.POL_APP_RECV_DT POL_CREAT_DT
		,POL.POL_APP_CMPLT_DT
		,POL.CVG_MAT_XPRY_DUR
		,POL.CVG_FACE_AMT
		,FPREM.POL_INITIAL_PREM
		,PRE_MODE = PAR.DM_AV_DESC_TXT
		,POL.INSRD_CLI_ID
		,PCLIR.PO
		,PO_NAME = PONM.CLI_FULL_NAME
		,PCLIR.BLI
		,BLI_NAME = BLINM.CLI_FULL_NAME
		,PCLIR.ALI1
		,ALI1_NAME = ALI1NM.CLI_FULL_NAME
		,PCLIR.ALI2
		,ALI2_NAME = ALI2NM.CLI_FULL_NAME
		,APE = POL_MPREM_AMT * (CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL.POL_BILL_MODE_CD AS INT) END) 
		,DATEDIFF(DAY,POL_APP_RECV_DT,GETDATE()) PENDING_DAYS
		,DATEADD(DAY,21,POL_APP_RECV_DT) NTU
		,REMOTE_CASE = CASE WHEN ISNULL(POL.SUBMITED_TYPE,'') != '' THEN POL.SUBMITED_TYPE 
			ELSE 
				CASE WHEN LEFT(POL.POL_APP_FORM_ID,2) IN ('AR', 'BR') THEN 'Remote Case' ELSE NULL END
			END
		,COL = TCOL.NON_JET_STAT_CD
		,ME = TME.NON_JET_STAT_CD
		,IA = TIA.NON_JET_STAT_CD
		,OTR = TOTR.NON_JET_STAT_CD
		,RMKS.REASON
		,POL.AGT_ID
		,AGT.AGENT_NAME AGENT_NAME
		,AGT.LeaderId LEADER_CODE
		,AGT.LeaderName LEADER_NAME
		,AGT.ManagerId MANAGER_CODE
		,AGT.ManagerName MANAGER_NAME
		,AGT.CHANNEL CSC_NAME	-- PREVIOUS NAME, WILL REMOVE AFTER UPDATING TEMPLATE.
		,AGT.CHANNEL_DESC
		,POL.POL_SOLD_BR_ID
		,POL_SOLD_BR_NAME = SLDBR.ETBL_DESC_TXT
		,POL.APP_SUBMIT_CD
		,BRANCH_CODE = CASE WHEN AGT.CHANNEL = 'AG' THEN '' ELSE BRANCH_CODE END
		,BRANCH_NAME = CASE WHEN AGT.CHANNEL = 'AG' THEN 'AGENCY' ELSE BRANCH_NAME END
		,ORGANIZATION = CASE WHEN AGT.CHANNEL = 'AG' THEN AGT.BRANCH_NAME ELSE AGT.PARTNER_NAME END
		,AGT.SMALL_OFFICE
		,INITIAL_COLM =  COLM.ETBL_DESC_TXT --VERS 0.1
		,RENEWAL_COLM = RCOLM.ETBL_DESC_TXT --VERS 0.1
		,SUBMISSION_DATE = CAST(FORMAT(POL.POL_APP_RECV_DT,'dd-MM-yyyy') AS varchar) + ' ' + APPTIME.TMR_TIME
		--VERS0.4 ADDING DISCOUNT % DL-236
		,ORIGINAL_PRM =  CASE WHEN CAST(POL.CVG_UNDSCNT_PREM AS BIGINT) = 0 THEN POL.POL_MPREM_AMT ELSE CAST(POL.CVG_UNDSCNT_PREM AS BIGINT) END
		,AUTO_DIS = POL.CVG_PREM_DISC_2_FCT
		,MAN_DIS = POL.CVG_PREM_DISC_1_FCT
		,TOTAL_DIS_AMT = CASE WHEN (CAST(POL.CVG_UNDSCNT_PREM AS BIGINT) - CAST(POL.POL_MPREM_AMT AS BIGINT)) < 0 THEN 0 ELSE (CAST(POL.CVG_UNDSCNT_PREM AS BIGINT) - CAST(POL.POL_MPREM_AMT AS BIGINT)) END
		--,MP_BE_DIS = CASE WHEN (POL.POL_MPREM_AMT + ( POL.CVG_UNDSCNT_PREM - POL.POL_MPREM_AMT)) <= 0 THEN POL.POL_MPREM_AMT ELSE (POL.POL_MPREM_AMT + ( POL.CVG_UNDSCNT_PREM - POL.POL_MPREM_AMT)) END 
		,CASE_STT = CASE WHEN POL.POL_CASE_STAT_CD ='M' THEN 'Manual' WHEN POL.POL_CASE_STAT_CD ='A' THEN 'Auto' ELSE '' END
		,CASE_STT_RMKS = POL.POL_UW_RMRKS
	    ,CRI.AUTO_UW_RULE_CD
        ,POL.AML_STAT_CD AML_CODE -- VERS0.3
        ,RTRIM(STP.ETBL_DESC_TXT) STP_CODE -- VERS0.4

	--INTO #TMP
	FROM #POL POL	
	LEFT JOIN #EDIT PLN ON POL.PLAN_ID = PLN.ETBL_VALU_ID AND PLN.ETBL_TYP_ID='PLAN'
	LEFT JOIN #EDIT COLM ON POL.COLCT_MTHD_CD = COLM.ETBL_VALU_ID AND COLM.ETBL_TYP_ID = 'COMTH' --vers 0.2 add COLM
	LEFT JOIN #EDIT RCOLM ON POL.POL_RENW_MTHD_CD = RCOLM.ETBL_VALU_ID AND RCOLM.ETBL_TYP_ID = 'RENWMCD' --vers 0.2 add Renewal COLM
	LEFT JOIN #PAR PAR ON POL.POL_BILL_MODE_CD = PAR.DM_AV_CD AND PAR.DM_AV_TBL_CD = 'BILLN-MODE-CD'
	LEFT JOIN #NJET TCOL ON POL.POL_ID = TCOL.POL_CLI_ID AND TCOL.GRP_CD = 'COL'
	LEFT JOIN #NJET TME ON POL.POL_ID = TME.POL_CLI_ID AND TME.GRP_CD = 'ME'
	LEFT JOIN #NJET TIA ON POL.POL_ID = TIA.POL_CLI_ID AND TIA.GRP_CD = 'IA'
	LEFT JOIN #NJET TOTR ON POL.POL_ID = TOTR.POL_CLI_ID AND TOTR.GRP_CD = 'OTR'
    LEFT JOIN SGTB_EDITTABLE STP ON STP.ETBL_VALU_ID = POL.POL_STP_CD AND STP.ETBL_TYP_ID = 'STPCD' -- VERS0.4
	LEFT JOIN 
		(
			SELECT POL_CLI_ID,
				STUFF((SELECT DISTINCT ', ' + LTRIM(RTRIM(RMRKS))
						FROM #TREQ T2
						WHERE T2.POL_CLI_ID = T1.POL_CLI_ID AND T2.CPREQ_STAT_CD IN ('ORD')	-- GET ONLY REMARK THAT REQUIREMENT STATUS IS "ORDERED"
						FOR XML PATH('')),1,1,''
				) REASON
			FROM #TREQ T1
			GROUP BY POL_CLI_ID
		)RMKS ON POL.POL_ID = RMKS.POL_CLI_ID

	-- CLIENT
	LEFT JOIN V_PIVOT_POL_CLI_ROLE_LIVE PCLIR ON POL.POL_ID = PCLIR.POL_ID
	LEFT JOIN #APPTIME APPTIME ON APPTIME.CPEVNT_POL_CLI_ID = POL.POL_ID AND APPTIME.CPEVNT_TRXN_DT = POL.POL_APP_RECV_DT
	-- PO
	LEFT JOIN #CLNM PONM ON PCLIR.PO = PONM.CLI_ID AND PONM.#NO = 1
	-- BLI
	LEFT JOIN #CLNM BLINM ON PCLIR.BLI = BLINM.CLI_ID AND BLINM.#NO = 1
	-- ALI 1
	LEFT JOIN #CLNM ALI1NM ON PCLIR.ALI1 = ALI1NM.CLI_ID AND ALI1NM.#NO = 1
	-- ALI 2
	LEFT JOIN #CLNM ALI2NM ON PCLIR.ALI2 = ALI2NM.CLI_ID AND ALI2NM.#NO = 1

	-- AGENT
	LEFT JOIN #AGENT AGT ON CAST(AGT.AGENT_CODE AS VARCHAR(10)) = POL.AGT_ID
	--LEFT JOIN #AGENT AGT ON POL.AGT_ID = AGT.AGT_ID AND AGT.#LAST_UPTD_NM = 1
	LEFT JOIN #FPREM FPREM ON POL.POL_ID = FPREM.POL_ID
	LEFT JOIN #XTAB SLDBR ON POL.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_TYP_ID = 'SOLDBR'
	
	---GET FAIL CRITERIA----
	LEFT JOIN #CRI CRI ON POL.POL_ID = CRI.POL_ID 

	--SELECT * FROM #TMP
