CREATE PROC [RPT_COVER_SHEET_BENE] @POL_ID VARCHAR(200)
AS
   IF OBJECT_ID('tempdb..#CIND') IS NOT NULL
  DROP TABLE #CIND
  
   IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
     IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
  DROP TABLE #TMP1

SELECT I.* INTO #CIND FROM SGTM_CLIENT_IND I INNER JOIN (SELECT MAX(CLI_INDV_EFF_DT) EFF, CLI_ID FROM SGTM_CLIENT_IND GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INDV_EFF_DT=II.EFF

SELECT RTRIM(LTRIM(ENTR_SUR_NM)) ENTR_SUR_NM,RTRIM(LTRIM(ENTR_GIV_NM)) ENTR_GIV_NM,BE.CLI_ID BE_CLIID,ED.ETBL_DESC_TXT BNFY_REL_INSRD_CD,BNFY_PRCDS_PCT,C.CLI_BTH_DT,C.CLI_CIN_NUM CLI_ID_NUM,POL_ID,CLI_SEX_CD,
CAD.CLI_ADDR_LN_1_TXT,CMU.ETBL_DESC_TXT CLI_ADDR_LN_2_TXT,DIS.ETBL_DESC_TXT CLI_ADDR_LN_3_TXT,CIT.ETBL_DESC_TXT CLI_CITY_NM_TXT,CC1.CLI_CNTCT_ID_TXT,BNFY_SEQ_NUM INTO #TMP FROM SGTM_BENE BE 
INNER JOIN SGTM_CLIENT C ON BE.CLI_ID=C.CLI_ID
INNER JOIN #CIND D ON BE.CLI_ID=D.CLI_ID
LEFT JOIN SGTM_CLIENT_ADD CAD ON C.CLI_ID=CAD.CLI_ID
LEFT JOIN  SGTB_EDITTABLE ED ON BE.BNFY_REL_INSRD_CD=ED.ETBL_VALU_ID AND ETBL_TYP_ID='BTOI' AND ED.ETBL_LANG_CD='E'AND ED.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CMU ON CMU.ETBL_LANG_CD='E' AND CMU.ETBL_TYP_ID='CTYPC' AND  CAD.CLI_ADDR_CNTY_CD=CMU.ETBL_VALU_ID AND CMU.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE DIS ON DIS.ETBL_LANG_CD='E' AND DIS.ETBL_TYP_ID='MCPCD' AND  CAD.CLI_ADDR_MUN_CD=DIS.ETBL_VALU_ID AND DIS.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CIT ON CIT.ETBL_LANG_CD='E' AND CIT.ETBL_TYP_ID='CLOC' AND  CAD.CLI_CRNT_LOC_CD=CIT.ETBL_VALU_ID AND CIT.CO_ID='CP'
LEFT JOIN SGTM_CLIENT_CONTACT CC1 ON C.CLI_ID=CC1.CLI_ID AND CC1.CLI_CNTCT_ID_CD='MO'
WHERE POL_ID=@POL_ID order by BNFY_SEQ_NUM

DECLARE @CLI_ID VARCHAR(200),@GIV VARCHAR(200)
,@SUR VARCHAR(200),@ID VARCHAR(200),@SEX VARCHAR(100),@DOB DATE,@ADD1 VARCHAR(200),@COMMUNE VARCHAR(200),@DISTRICT VARCHAR(200),@CITY VARCHAR(200),@PHONE VARCHAR(200)

SELECT  @CLI_ID=BE_CLIID,@GIV=ENTR_GIV_NM,@SUR=ENTR_SUR_NM,@ID=CLI_ID_NUM,@SEX=CLI_SEX_CD,@DOB=CLI_BTH_DT,@ADD1=CLI_ADDR_LN_1_TXT,
@COMMUNE=CLI_ADDR_LN_2_TXT,@DISTRICT=CLI_ADDR_LN_3_TXT,@CITY=CLI_CITY_NM_TXT,@PHONE=CLI_CNTCT_ID_TXT FROM #TMP WHERE BNFY_SEQ_NUM=1

SELECT DISTINCT  CL.CLI_ID,IND.ENTR_SUR_NM,IND.ENTR_GIV_NM,CLI_CIN_NUM,CLI_SEX_CD,CLI_BTH_DT,C1.CLI_CNTCT_ID_TXT,CA.CLI_ADDR_LN_1_TXT,CMU.ETBL_DESC_TXT COMMUNE,DIS.ETBL_DESC_TXT DISTRICT,CIT.ETBL_DESC_TXT CITY INTO #TMP1 FROM SGTB_POLICY P INNER JOIN SGTB_POLICY_CLIENT PC ON P.POL_ID=PC.POL_ID
INNER JOIN SGTM_CLIENT CL ON CL.CLI_ID=PC.CLI_ID
INNER JOIN DLKHDIM..DIM_CLIENT_IND IND ON PC.CLI_ID=IND.CLI_ID AND IND.IS_CURRENT=1
LEFT JOIN SGTM_CLIENT_ADD CA ON CA.CLI_ID=CL.CLI_ID
LEFT JOIN SGTM_CLIENT_CONTACT C1 ON PC.CLI_ID=C1.CLI_ID AND C1.CLI_CNTCT_ID_CD='MO'
LEFT JOIN SGTB_EDITTABLE CMU ON CMU.ETBL_LANG_CD='E' AND CMU.ETBL_TYP_ID='CTYPC' AND  CA.CLI_ADDR_CNTY_CD=CMU.ETBL_VALU_ID AND CMU.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE DIS ON DIS.ETBL_LANG_CD='E' AND DIS.ETBL_TYP_ID='MCPCD' AND  CA.CLI_ADDR_MUN_CD=DIS.ETBL_VALU_ID AND DIS.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CIT ON CIT.ETBL_LANG_CD='E' AND CIT.ETBL_TYP_ID='CLOC' AND  CA.CLI_CRNT_LOC_CD=CIT.ETBL_VALU_ID AND CIT.CO_ID='CP'
WHERE  CL.CLI_ID<>@CLI_ID AND ((CL.CLI_CIN_NUM=@ID) 
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND CLI_SEX_CD=@SEX)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND CLI_ADDR_LN_1_TXT=@ADD1 AND CMU.ETBL_DESC_TXT=@COMMUNE AND DIS.ETBL_DESC_TXT=@DISTRICT AND CIT.ETBL_DESC_TXT=@CITY)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_SEX_CD=@SEX AND CLI_ADDR_LN_1_TXT=@ADD1 AND CMU.ETBL_DESC_TXT=@COMMUNE AND DIS.ETBL_DESC_TXT=@DISTRICT AND CIT.ETBL_DESC_TXT=@CITY)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND C1.CLI_CNTCT_ID_TXT=@PHONE)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_SEX_CD=@SEX AND C1.CLI_CNTCT_ID_TXT=@PHONE))

DECLARE @MAX INT = (SELECT MAX(BNFY_SEQ_NUM) FROM #TMP)

IF(@MAX>1)
BEGIN
DECLARE @SEQ INT =2
WHILE @MAX>=@SEQ
BEGIN
SELECT  @CLI_ID=BE_CLIID,@GIV=ENTR_GIV_NM,@SUR=ENTR_SUR_NM,@ID=CLI_ID_NUM,@SEX=CLI_SEX_CD,@DOB=CLI_BTH_DT,@ADD1=CLI_ADDR_LN_1_TXT,
@COMMUNE=CLI_ADDR_LN_2_TXT,@DISTRICT=CLI_ADDR_LN_3_TXT,@CITY=CLI_CITY_NM_TXT,@PHONE=CLI_CNTCT_ID_TXT FROM #TMP WHERE BNFY_SEQ_NUM=@SEQ

INSERT INTO #TMP1
SELECT DISTINCT  CL.CLI_ID,IND.ENTR_SUR_NM,IND.ENTR_GIV_NM,CLI_CIN_NUM,CLI_SEX_CD,CLI_BTH_DT,C1.CLI_CNTCT_ID_TXT,CA.CLI_ADDR_LN_1_TXT,CMU.ETBL_DESC_TXT COMMUNE,DIS.ETBL_DESC_TXT DISTRICT,CIT.ETBL_DESC_TXT CITY  FROM SGTB_POLICY P INNER JOIN SGTB_POLICY_CLIENT PC ON P.POL_ID=PC.POL_ID
INNER JOIN SGTM_CLIENT CL ON CL.CLI_ID=PC.CLI_ID
INNER JOIN DLKHDIM..DIM_CLIENT_IND IND ON PC.CLI_ID=IND.CLI_ID AND IND.IS_CURRENT=1
LEFT JOIN SGTM_CLIENT_ADD CA ON CA.CLI_ID=CL.CLI_ID
LEFT JOIN SGTM_CLIENT_CONTACT C1 ON PC.CLI_ID=C1.CLI_ID AND C1.CLI_CNTCT_ID_CD='MO'
LEFT JOIN SGTB_EDITTABLE CMU ON CMU.ETBL_LANG_CD='E' AND CMU.ETBL_TYP_ID='CTYPC' AND  CA.CLI_ADDR_CNTY_CD=CMU.ETBL_VALU_ID AND CMU.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE DIS ON DIS.ETBL_LANG_CD='E' AND DIS.ETBL_TYP_ID='MCPCD' AND  CA.CLI_ADDR_MUN_CD=DIS.ETBL_VALU_ID AND DIS.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CIT ON CIT.ETBL_LANG_CD='E' AND CIT.ETBL_TYP_ID='CLOC' AND  CA.CLI_CRNT_LOC_CD=CIT.ETBL_VALU_ID AND CIT.CO_ID='CP'
WHERE  CL.CLI_ID<>@CLI_ID AND ((CL.CLI_CIN_NUM=@ID) 
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND CLI_SEX_CD=@SEX)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND CLI_ADDR_LN_1_TXT=@ADD1 AND CMU.ETBL_DESC_TXT=@COMMUNE AND DIS.ETBL_DESC_TXT=@DISTRICT AND CIT.ETBL_DESC_TXT=@CITY)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_SEX_CD=@SEX AND CLI_ADDR_LN_1_TXT=@ADD1 AND CMU.ETBL_DESC_TXT=@COMMUNE AND DIS.ETBL_DESC_TXT=@DISTRICT AND CIT.ETBL_DESC_TXT=@CITY)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND C1.CLI_CNTCT_ID_TXT=@PHONE)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_SEX_CD=@SEX AND C1.CLI_CNTCT_ID_TXT=@PHONE))

SET @SEQ = @SEQ + 1
END

END
SELECT * FROM #TMP1
