

CREATE PROC  [dbo].[RPT_DISCOUNT] @START DATE, @END DATE
AS
	DROP TABLE IF EXISTS #AGENT

	----DECLARE @START	DATE = '2019-01-01'
	----		,@END	DATE = '2021-11-12'

	SELECT * INTO #AGENT FROM DLKHFACT..FACT_AGENT WHERE DATE_KEY = (SELECT MAX(DATE_KEY) FROM DLKHFACT..FACT_AGENT)

	SELECT P.POL_ID
		,POL_APP_FORM_ID = RTRIM(P.POL_APP_FORM_ID)
		,P.POL_APP_RECV_DT
		,P.POL_ISS_EFF_DT CS_REV_DT
		,P.POL_APP_RECV_DT PRO_LOAD_DT
		,P.POL_INFC_DT POL_ISS_EFF_DT
		,P.POL_CSTAT_CD
		,RTRIM(PARA.DM_AV_DESC_TXT) POL_STATUS
		,P.POL_BILL_MODE_CD
		,C.CVG_MAT_XPRY_DUR
		,C.CVG_NUM
		,C.PLAN_ID
		,TYPE = RTRIM(ED.ETBL_DESC_TXT)
		,PLAN_NAME = RTRIM(ED.ETBL_DESC_TXT)
		,C.CVG_FACE_AMT
		,C.CVG_MPREM_AMT
		,AFYP = C.CVG_MPREM_AMT * (CASE WHEN CAST(POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL_BILL_MODE_CD AS INT) END)
		,PC.CLI_ID
		,I.CLI_INDV_TITL_TXT
		,RTRIM(LTRIM(I.ENTR_SUR_NM)) + ' ' + RTRIM(LTRIM(I.ENTR_GIV_NM)) CLIENT_NAME
		,RTRIM(CO.CLI_CNTCT_ID_TXT) CLIENT_MOBILE
		,BNK_ID = RTRIM(CLIB.BNK_ID)
		,BNK_NM = RTRIM(BNK.BNK_NM)
		,CLIB.BNK_ACCT_ID
		,BNK_ACCT_HLDR_NM = RTRIM(BAC.BNK_ACCT_HLDR_NM)
		,CHANNEL = RTRIM(AGT.CHANNEL)
		,RTRIM(LTRIM(AGT.ENTR_SUR_NM))+ ' ' + RTRIM(LTRIM(AGT.ENTR_GIV_NM)) AGENT_NAME
		,AGT_PHON_NUM = RTRIM(AGT.AGT_PHON_NUM)
		,W.AGT_ID
		,C.CVG_ME_FCT
		,C.CVG_MPREM_AMT - CVG_ME_PREM_AMT PRE_BEFORE
		,C.CVG_MPREM_AMT PRE_AFTER
		,ABM_ID = AGT.ABM_ID
		,RTRIM(LTRIM(AGT.ABM_SURNAME))+ ' ' + RTRIM(LTRIM(AGT.ABM_GIVNAME)) ABM_NAME
		,LEADER_ID = AGL.AGT_ID
		,RTRIM(LTRIM(AGL.ENTR_SUR_NM))+ ' ' + RTRIM(LTRIM(AGL.ENTR_GIV_NM)) LEADER_NAME
	FROM SGTB_POLICY P 
	LEFT JOIN SGTM_COVERAGE C ON P.POL_ID=C.POL_ID 
	LEFT JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
	LEFT JOIN #AGENT AGT ON AGT.AGT_ID=W.AGT_ID
	LEFT JOIN #AGENT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID 
	--LEFT JOIN #AGENT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID 
	LEFT JOIN SGTB_POLICY_CLIENT PC ON PC.POL_ID=P.POL_ID AND PC.POL_CLI_REL_TYP_CD='O'
	LEFT JOIN SGTM_CLIENT_IND I ON I.CLI_ID=PC.CLI_ID AND I.PREV_UPDT_TS = (SELECT MAX(PREV_UPDT_TS) FROM SGTM_CLIENT_IND WHERE CLI_ID = I.CLI_ID GROUP BY CLI_ID)
	LEFT JOIN SGTM_CLIENT_CONTACT CO ON I.CLI_ID=CO.CLI_ID AND CO.CLI_CNTCT_ID_CD='MO'
	LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' and PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
	LEFT JOIN SGTB_EDITTABLE ED ON C.PLAN_ID = ED.ETBL_VALU_ID AND ED.CO_ID = 'CP' AND ETBL_LANG_CD = 'E' AND ETBL_TYP_ID = 'PLAN'
	LEFT JOIN SGTM_CLIB CLIB ON PC.CLI_ID = CLIB.CLI_ID AND CLIB.PREV_UPDT_TS = (SELECT MAX(PREV_UPDT_TS) FROM SGTM_CLIB WHERE CLI_ID = PC.CLI_ID GROUP BY CLI_ID)
	LEFT JOIN SGTM_BANK_ACC BAC ON CLIB.BNK_ACCT_ID = BAC.BNK_ACCT_ID
	LEFT JOIN SGTM_BANK BNK ON CLIB.BNK_ID = BNK.BNK_ID 
	WHERE 1 = 1 
		AND P.POL_CSTAT_CD IN ('1') 
		AND P.POL_INFC_DT BETWEEN @START AND @END
	--AND CLIB.BNK_ACCT_ID = '1002550029734'
	--AND ISNULL(CLIB.BNK_ACCT_ID,'') != ''
	ORDER BY P.POL_ID
