
/***************************************************************************************************
	REPORT:.......... LARGE CASH TRANSACTION (OPT. DEPT.)
	PURPOSE:......... L&C GENERATE LARGE CASH TRANSACTION FROM CUSTOMER
	CREATED BY: ..... YOUERN RIN
	CREATED AT: ..... 08-AUG-2024
        
    Changelog
    ***********
	VERSION    DATE CHNG      DESC
	VERS0.1		              Initial Version

****************************************************************************************************/

CREATE PROCEDURE [dbo].[RPT_LARGE_CASH_TRANSACTION] @STAT_DATE DATE, @END_DATE DATE AS 

--DECLARE @STAT_DATE DATE = '2024-8-01';
--DECLARE @END_DATE DATE = '2024-8-23';

SELECT DISTINCT 
 PC.POL_ID
,P.POL_APP_SIGN_DT INPUT_DATE
,CONCAT(RTRIM(PONM.ENTR_SUR_NM),' ', RTRIM(PONM.ENTR_GIV_NM)) PO_NAME
,RTRIM(SEX.ETBL_DESC_TXT) GENDER
,C.CLI_BTH_DT DOB
,RTRIM(BTLOC.ETBL_DESC_TXT) PO_NATLITY
,RTRIM(PLN.ETBL_DESC_TXT) PD_PLAN
,POL_TERM = (CVG.CVG_MAT_XPRY_DUR)
,PCVG.POL_FACE_AMT SUM_INSURED
,P.POL_MPREM_AMT MODE_PRE
,PRM_TYPE = CASE WHEN DATEDIFF(DAY, P.POL_ISS_EFF_DT, A.ACCT_HIST_PRCES_DT) <=0 THEN 'Initial' else 'Renewal' end
,P.POL_PD_TO_DT_NUM RENEWAL_PAID_DATE
,A.ACCT_HIST_AMT AMT_PRE_RE
,A.ACCT_HIST_PRCES_DT PM_RC_DT
,FREQUENCY = RTRIM(ED.ETBL_DESC_TXT)
,COL_MTH = RTRIM(COMTH.ETBL_DESC_TXT)
,POL_STATUS = RTRIM(STAT.DM_AV_DESC_TXT)
,POW.AGT_ID AgentId
,AGD.Name AGE_NAME
,AGD.ManagerName AGE_MG_NAME
,ManagerPhone = AGM.PhoneNumber

--INTO #TEMP
FROM SGTB_ACCOUNTING_TRANHIS A
LEFT JOIN SGTB_POLICY P ON P.POL_ID = A.POL_ID
LEFT JOIN SGTB_EDITTABLE COMTH ON P.COLCT_MTHD_CD = COMTH.ETBL_VALU_ID AND COMTH.ETBL_TYP_ID = 'COMTH'
LEFT JOIN SGTM_PARA_1 STAT ON STAT.DM_AV_CD = P.POL_CSTAT_CD AND STAT.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND STAT.DM_AV_DESC_LANG_CD = 'E'
LEFT JOIN SGTB_EDITTABLE ED ON ED.ETBL_VALU_ID = P.POL_BILL_MODE_CD AND ED.ETBL_TYP_ID = 'BILL-MODE'
LEFT JOIN SGTB_POLICY_WRITING POW ON POW.POL_ID = P.POL_ID
LEFT JOIN SGTB_POLICY_CLIENT PC ON PC.POL_ID = A.POL_ID AND PC.POL_CLI_REL_TYP_CD = 'O'
LEFT JOIN SGTM_CLIENT C ON C.CLI_ID = PC.CLI_ID
LEFT JOIN SGTB_EDITTABLE SEX ON SEX.ETBL_VALU_ID = C.CLI_SEX_CD AND SEX.ETBL_TYP_ID = 'SEX'
LEFT JOIN SGTB_EDITTABLE BTLOC ON BTLOC.ETBL_VALU_ID = C.CLI_BTH_LOC_CD AND BTLOC.ETBL_TYP_ID = 'BTLOC'
LEFT JOIN SGTB_EDITTABLE PLN ON PLN.ETBL_VALU_ID = P.PLAN_ID AND PLN.ETBL_TYP_ID = 'PLAN'
LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) PONM ON PC.CLI_ID= PONM.CLI_ID AND PONM.#NO = 1
LEFT JOIN (SELECT SUM(CVG_FACE_AMT) POL_FACE_AMT, SUM(CVG_ME_PREM_AMT) CVG_ME_PREM_AMT, SUM(CVG_MPREM_AMT) CVG_MPREM_AMT, POL_ID, MAX(CVG_MAT_XPRY_DUR) POL_TERM FROM SGTM_COVERAGE GROUP BY POL_ID) PCVG ON PCVG.POL_ID = P.POL_ID
LEFT JOIN (
	SELECT PC.CLI_ID, SUM(A.ACCT_HIST_AMT) TOTAL_PRE
	FROM SGTB_ACCOUNTING_TRANHIS A 
	LEFT JOIN SGTB_POLICY_CLIENT PC ON PC.POL_ID = A.POL_ID 
	WHERE A.ACCT_HIST_AMT >= 10000 AND  A.ACCT_BASE_ID IN( '102300','249800') AND   A.ACCT_HIST_PRCES_DT BETWEEN @STAT_DATE AND @END_DATE 
	GROUP BY PC.CLI_ID
) TAMT ON TAMT.CLI_ID = PC.CLI_ID AND PC.POL_CLI_REL_TYP_CD = 'O'
LEFT JOIN SGTM_COVERAGE CVG ON CVG.POL_ID = P.POL_ID AND CVG.CVG_NUM = '01'
LEFT JOIN SGTM_AGENT_DETAIL AGD ON POW.AGT_ID = AGD.AgentId
LEFT JOIN SGTM_AGENT_DETAIL AGM ON AGM.AgentId = AGD.AgentId
WHERE (A.ACCT_HIST_AMT >= 10000 OR TAMT.TOTAL_PRE >= 10000) AND  A.ACCT_BASE_ID IN( '102300','249800') 
AND A.ACCT_HIST_PRCES_DT BETWEEN @STAT_DATE AND @END_DATE
--AND PC.CLI_ID = '0000006649'
