

CREATE PROC [dbo].[RPT_REJECT] 
	@START	DATE = NULL
	,@END	DATE = NULL
AS
	--DECLARE @START	DATE = '2024-06-01'
	--		,@END	DATE = '2024-07-17' 

	DROP TABLE IF EXISTS  #TDMAD
	DROP TABLE IF EXISTS  #TEDIT
	DROP TABLE IF EXISTS  #TCLNM
	DROP TABLE IF EXISTS  #TCLIC	
	DROP TABLE IF EXISTS  #TCLIA
	DROP TABLE IF EXISTS  #TCVG
	DROP TABLE IF EXISTS  #TPOL
	DROP TABLE IF EXISTS  #AGENT
	DROP TABLE IF EXISTS  #CRI

	IF ISNULL(@START,'') = '' SET @START = '2000-01-01'
	IF ISNULL(@END,'') = '' SET @END = CONVERT(DATE,GETDATE())

	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #TEDIT FROM SGTB_EDITTABLE
	WHERE CO_ID = 'CP' AND ETBL_LANG_CD = 'E' AND ETBL_TYP_ID IN ('CEASE','PLAN','DCHNL','REJRMK')

	SELECT DM_AV_CD,DM_AV_TBL_CD,DM_AV_DESC_TXT = RTRIM(DM_AV_DESC_TXT) INTO #TDMAD FROM SGTM_PARA_1 
	WHERE CO_ID = 'CP' AND DM_AV_DESC_LANG_CD = 'E' AND DM_AV_TBL_CD IN ('POL-CSTAT-CD','POL-BILL-MODE-CD','POL-REJ-REASN-CD')

	-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT
		,CLI_INDV_GR_CD
		,#LAST_UPTD_NM = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM
	FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS,CLI_INDV_GR_CD
		FROM KCAPXUAT.TCLNM
	')

	-- GET ONLY REQUIRED INFO OF CLIENT CONTACT - TCLIC
	SELECT CLI_ID,CLI_CNTCT_ID_CD,CLI_CNTCT_ID_TXT = RTRIM(CLI_CNTCT_ID_TXT)
	INTO #TCLIC FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_CNTCT_ID_CD,CLI_CNTCT_ID_TXT
		FROM KCAPXUAT.TCLIC
		WHERE LENGTH(RTRIM(CLI_ID)) >= 10
	')

	-- GET ONLY REQUIRED INFO ON CLIENT ADDRESS - TCLIA
	SELECT CLI_ID,CLI_ADDR_LN_1_TXT = RTRIM(CLI_ADDR_LN_1_TXT),CLI_ADDR_LN_2_TXT = RTRIM(CLI_ADDR_LN_2_TXT)
		,CLI_ADDR_LN_3_TXT = RTRIM(CLI_ADDR_LN_3_TXT),CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD,CLI_CRNT_LOC_CD
		,CLI_ADDR_STAT_CD,CLI_ADDR_GR_CD,CLI_ADDR_TYP_CD,CLI_ADDR_EFF_DT,CLI_CITY_NM_TXT
	INTO #TCLIA FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_ADDR_LN_1_TXT,CLI_ADDR_LN_2_TXT,CLI_ADDR_LN_3_TXT,CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD,CLI_CRNT_LOC_CD,CLI_ADDR_STAT_CD
			,CLI_ADDR_GR_CD,CLI_ADDR_TYP_CD,CLI_ADDR_EFF_DT,CLI_CITY_NM_TXT
		FROM KCAPXUAT.TCLIA
		WHERE CLI_ADDR_TYP_CD = ''PR''
			AND LENGTH(RTRIM(CLI_ID)) >= 10
	')

	SELECT *,CVG_TERM_AT_POS = ROW_NUMBER() OVER(PARTITION BY POL_ID ORDER BY CVG_MAT_XPRY_DUR DESC)
	INTO #TCVG FROM OPENQUERY(UAT7,
	'	SELECT CVG.POL_ID,CVG.CVG_NUM,CVG.CVG_MAT_XPRY_DUR,CVG.PLAN_ID,CVGC.INSRD_CLI_ID 
			,CVG.CVG_FACE_AMT
			,CVG.CVG_UNDSCNT_PREM
			,CVG.CVG_PREM_DISC_1_FCT
			,CVG.CVG_PREM_DISC_2_FCT
		FROM KCAPXUAT.TCVG CVG
		INNER JOIN KCAPXUAT.TCVGC CVGC ON CVG.POL_ID = CVGC.POL_ID AND CVG.CVG_NUM = CVGC.CVG_NUM
	')

	SELECT * INTO #TPOL FROM OPENQUERY(UAT7,
	'	SELECT POL.POL_ID,POL.POL_BASE_CVG_NUM,POL.POL_CSTAT_CD,POL.POL_CEAS_REASN_CD,POL.POL_ISS_EFF_DT,POL.POL_BILL_MODE_CD
			,POL.POL_INFC_DT,POL.POL_OS_DISB_AMT,POL.POL_OS_DISB_DT,POL.PLAN_ID,POL.POL_MPREM_AMT,POL.POL_REJ_REASN_CD,POL.REJ_REMKS_CD
			,POL.POL_STAT_CHNG_DT,POL.POL_APP_FORM_ID
			,POL.POL_APP_RECV_DT,POL.POL_GRS_APREM_AMT,POL.POL_INS_TYP_CD,POL.POL_BUS_CLAS_CD
			,POLC.CLI_ID,POLW.AGT_ID,POL_MEDIC_FEE_AMT
			,DLAG.CPEVNT_POL_CLI_ID,DLAG.USER_ID,POL.APP_SUBMIT_CD
			,POL.POL_CASE_STAT_CD
			,POLC.POL_UW_RMRKS
		FROM KCAPXUAT.TPOL POL
		INNER JOIN KCAPXUAT.TPOLC POLC ON POL.POL_ID = POLC.POL_ID
		INNER JOIN KCAPXUAT.TPOLW POLW ON POL.POL_ID = POLW.POL_ID
		LEFT JOIN KCAPXUAT.TDALG DLAG ON POL.POL_ID = DLAG.CPEVNT_POL_CLI_ID 
		WHERE POLC.POL_CLI_REL_TYP_CD = ''O''
			AND (POL.POL_CSTAT_CD = ''R'' OR POL.POL_ID = ''001000744'')
			AND DLAG.CPEVNT_POL_CLI_CD = ''P'' AND DLAG.EVNT_ACT_CD = ''REJ''
	')

	-- GET SOME INFO OF AGENT ONLY 
	SELECT * INTO #AGENT FROM V_DMS_AGENT_REPORTING_LINE_LIVE

	-- POLICY NO 001000744: USER REQUEST TO CONVERT STATUS FROM 'A' TO 'R'
	UPDATE #TPOL SET POL_CSTAT_CD = 'R', POL_MPREM_AMT = 814.03, POL_REJ_REASN_CD = 'PP' WHERE POL_ID = '001000744' 

	-- GET ONLY FAIL CRITERIA CODE - CRI
	SELECT POL_ID, STUFF( (SELECT  ', '+LTRIM(RTRIM(AUTO_UW_REL_CD)) +':'+ LTRIM(RTRIM(AUTO_UW_RULE_CD))
			FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T WHERE T.POL_ID = T1.POL_ID
			FOR XML PATH('')),1,1,'') AUTO_UW_RULE_CD
	INTO #CRI
	FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T1
	GROUP BY POL_ID

	SELECT  NBR = 0	
		,REPORT_DT = GETDATE()
		,POLICY_NO = POL.POL_ID
		,PROPOSAL_NO = POL.POL_APP_FORM_ID
		,POL_OWN_NAME = PO.ENTR_SUR_NM + ' ' + PO.ENTR_GIV_NM
		,POL.POL_ISS_EFF_DT
		,POL.POL_INFC_DT
		,POL.POL_STAT_CHNG_DT
		,POLICY_STATUS = C.DM_AV_DESC_TXT
		,POL_LI_NAME = BLI.ENTR_SUR_NM + ' ' + BLI.ENTR_GIV_NM 
		,POL.POL_BILL_MODE_CD
		,POL.POL_MPREM_AMT
		,POL_CREAT_DT = POL.POL_APP_RECV_DT
		,CVG.CVG_FACE_AMT
		,TOTAL_MODAL_TP = POL.POL_MPREM_AMT
		,AFYP = POL.POL_MPREM_AMT * (CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) > 0 THEN 12/CAST(POL.POL_BILL_MODE_CD AS INT) ELSE 1 END)
		,TOTAL_ANNUALIZE_TP = POL.POL_GRS_APREM_AMT
		,BILLING_MODE = BLMD.DM_AV_DESC_TXT
		,PLAN_NAME = CVG_PLN.ETBL_DESC_TXT
		,PO_MOBILE_PHONE = CLIC1.CLI_CNTCT_ID_TXT
		,PO_EMAIL = CLIC2.CLI_CNTCT_ID_TXT
		,POL.USER_ID
		,POL_REJ_REASN_TXT = REJT.DM_AV_DESC_TXT
		,POL.AGT_ID
		,CHANNEL = AGT.CHANNEL_DESC
		,AGENT_NAME = AGT.AGENT_NAME
		,LEADER_ID = AGT.LeaderId
		,LEADER_NAME = AGT.LeaderName
		,AGT_MANAGER_ID = AGT.ManagerId
		,AGT_MANAGER_NAME = AGT.ManagerName
		,CASE WHEN AGT.CHANNEL = 'BA' THEN AGT.BRANCH_CODE ELSE NULL END BANK_BRANCH_CODE
		,CASE WHEN AGT.CHANNEL = 'BA' THEN AGT.BRANCH_NAME WHEN AGT.CHANNEL = 'AG' THEN 'AGENCY' ELSE NULL END BANK_BRANCH_NAME
		,CASE WHEN AGT.CHANNEL = 'BA' THEN AGT.PARTNER_NAME WHEN AGT.CHANNEL = 'AG' THEN CONCAT(AGT.BRANCH_CODE,' - ',AGT.BRANCH_NAME) ELSE NULL END ORGANIZATION
		,AGT.SMALL_OFFICE
		,CVG.CVG_MAT_XPRY_DUR
		,POL.POL_REJ_REASN_CD
		,POL.POL_MEDIC_FEE_AMT
		,POL.REJ_REMKS_CD
		,REJECT_REASON = REJRMK.ETBL_DESC_TXT
		,POL.APP_SUBMIT_CD
		
		--VERS0.4 ADDING DISCOUNT % DL-236
		,ORIGINAL_PRM =  CASE WHEN CVG.CVG_UNDSCNT_PREM = 0 THEN POL.POL_MPREM_AMT ELSE CVG.CVG_UNDSCNT_PREM END
		,AUTO_DIS = CVG.CVG_PREM_DISC_2_FCT
		,MAN_DIS = CVG.CVG_PREM_DISC_1_FCT
		,TOTAL_DIS_AMT = CASE WHEN (CVG.CVG_UNDSCNT_PREM - POL.POL_MPREM_AMT) < 0 THEN 0 ELSE (CVG.CVG_UNDSCNT_PREM - POL.POL_MPREM_AMT) END
		,MP_BE_DIS = CASE WHEN (POL.POL_MPREM_AMT + ( CVG.CVG_UNDSCNT_PREM - POL.POL_MPREM_AMT)) <= 0 THEN POL.POL_MPREM_AMT ELSE (POL.POL_MPREM_AMT + ( CVG.CVG_UNDSCNT_PREM - POL.POL_MPREM_AMT)) END 
		,CASE_STT = CASE WHEN POL.POL_CASE_STAT_CD ='M' THEN 'Manual' WHEN POL.POL_CASE_STAT_CD ='A' THEN 'Auto' ELSE '' END
		,CASE_STT_RMKS = POL.POL_UW_RMRKS
		,CRI.AUTO_UW_RULE_CD

	FROM #TPOL POL
	INNER JOIN  #TCVG AS  CVG ON POL.POL_ID = CVG.POL_ID AND CVG.CVG_NUM = '01'
	-- GET BILLING FREQUENCY --
	LEFT JOIN #TDMAD AS  BLMD ON BLMD.DM_AV_TBL_CD = 'POL-BILL-MODE-CD'AND BLMD.DM_AV_CD = POL.POL_BILL_MODE_CD
	-- REASON --  
	LEFT JOIN #TDMAD AS  REJT ON REJT.DM_AV_TBL_CD = 'POL-REJ-REASN-CD' AND REJT.DM_AV_CD = POL.POL_REJ_REASN_CD
	-- GET STATUS POLICY --
	LEFT JOIN #TDMAD AS  C ON C.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND C.DM_AV_CD = POL.POL_CSTAT_CD 
	-- GET POLICY OWNER NAME --
	LEFT JOIN #TCLNM PO ON POL.CLI_ID = PO.CLI_ID AND #LAST_UPTD_NM = 1  
	LEFT JOIN #TCLIC CLIC1 ON CLIC1.CLI_ID  = PO.CLI_ID AND CLIC1.CLI_CNTCT_ID_CD = 'MO'
	LEFT JOIN #TCLIC CLIC2 ON CLIC2.CLI_ID  = PO.CLI_ID AND CLIC2.CLI_CNTCT_ID_CD = 'EM' 
	--GET BLI NAME ---
	LEFT JOIN #TCLNM BLI ON CVG.INSRD_CLI_ID = BLI.CLI_ID AND BLI.#LAST_UPTD_NM = 1
	LEFT JOIN #TEDIT REJRMK ON POL.REJ_REMKS_CD = REJRMK.ETBL_VALU_ID AND REJRMK.ETBL_TYP_ID = 'REJRMK' 
	LEFT JOIN #TEDIT CVG_PLN ON CVG_PLN.ETBL_TYP_ID = 'PLAN' AND CVG_PLN.ETBL_VALU_ID = CVG.PLAN_ID

	-- AGENT INFO
	LEFT JOIN #AGENT AGT ON POL.AGT_ID = CONVERT(VARCHAR(10), AGT.AGENT_CODE)
	LEFT JOIN #CRI CRI ON POL.POL_ID = CRI.POL_ID 

	WHERE POL.POL_STAT_CHNG_DT BETWEEN @START AND @END
