
/***************************************************************************************************
	REPORT:.......... PREMIUM COLLECTION AND RENEWAL (SALE DIST. DEPT.)
	PURPOSE:......... LISTING DETAIL OF PREMIUM COLLECTION AND RENEWAL FOR POLICY
        
    Changelog
    ***********
	VERSION    DATE CHNG   UPD_BY     DESC
	VERS0.1		                      Initial Version
	VERS0.1	   28-05-2024  DOM        GET UNDISCOUNT PREMIUM AMOUNT AS MODAL PREM FOR EASYCARE
***************************************************************************************************/

CREATE PROC [dbo].[RPT_AGENT_COLLECTION]
 @START DATE,@END DATE
AS

	--DECLARE @START		DATE = '2024-08-01'
	--		,@END		DATE = '2024-08-27'

	IF @END = '2024-01-31' SET @END = '2024-02-01'
	DROP TABLE IF EXISTS #TMP
	DROP TABLE IF EXISTS #AGENT

	SELECT POL_KEY
		,P.POL_ID
		,P.POL_APP_FORM_ID
		,W.AGT_ID AGT_ID
		,RTRIM(CL.ENTR_SUR_NM) + ' ' + RTRIM(CL.ENTR_GIV_NM) CLI_NAME
		,AGD.Name AGENT_NAME
		,RTRIM(AGD.TitleRole) AGENT_POS
		,PC.PCHST_EFF_DT
		,P.PLAN_ID,PA.ETBL_DESC_TXT PLAN_DESC
		,POL_CSTAT_CD
		,PARA.DM_AV_DESC_TXT POL_STAT_DESC
		,POL_APP_RECV_DT POL_CREAT_DT
		,P.POL_APP_CMPLT_DT
		--,CASE WHEN P.PLAN_ID = 'BES001' THEN PREM.CVG_UNDSCNT_PREM ELSE PREM.CVG_MPREM_AMT END PREAMT --	REMOVE AS USER REQUEST FOR ACTUAL COLLECTED AMOUNT AND REPLACE BY BELOW LINE
		,CASE WHEN P.PLAN_ID = 'BES001' THEN PREM.CVG_UNDSCNT_PREM ELSE CAST(SUBSTRING(PC.PCHST_NEW_VALU_TXT, 0, charindex('/',PC.PCHST_NEW_VALU_TXT)) AS float) END PREAMT
		,AGD.DistributionChannel CHANNEL
		,CL.CLI_CNTCT_ID_TXT PHONE
		,TEM.CVG_MAT_XPRY_DUR TERM
		,ABM_ID = AGD.ManagerId
		,AGD.ManagerName ABM_NAME
		,LEADER_ID = AGD.LeaderId
		,AGD.LeaderName LEADER_NAME
		,RTRIM(PN.NAME) BANK_NAME
		,CASE WHEN P.POL_BILL_MODE_CD=3 THEN 'QUARTERLY' 
			WHEN P.POL_BILL_MODE_CD=6 THEN 'SEMI ANNUAL' 
			WHEN P.POL_BILL_MODE_CD=1 THEN 'MONTHLY' 
			WHEN P.POL_BILL_MODE_CD=12 THEN 'ANNUAL'
			ELSE P.POL_BILL_MODE_CD 
			END PRE_MODE,PC.POL_ACTV_TYP_ID
		,CASE WHEN PC.POL_ACTV_TYP_ID='1082'  THEN 'IFYP' ELSE 'RFYP' END COM_TYPE
		,PPC.PCHST_EFF_DT INITIAL_DATE
		,PC.PCHST_EFF_DT COL_EFF_DT
		,(PREM.CVG_FACE_AMT) FACE_AMT
		,AGD.LeaderId OVRID_BASE_AGT_ID
		,AFYP = CASE WHEN P.PLAN_ID = 'BES001' THEN PREM.CVG_UNDSCNT_PREM ELSE PREM.CVG_MPREM_AMT END * (CASE WHEN CAST(P.POL_BILL_MODE_CD AS INT)> 0 THEN 12 / CAST(P.POL_BILL_MODE_CD AS INT) ELSE 1 END) 
		,CASE WHEN CAST(PC.PREV_UPDT_TS AS DATE) = '2024-02-01' THEN '2024-01-31' ELSE CAST(PC.PREV_UPDT_TS AS DATE) END TRAN_DT 
		,POL_DURATION_DAY = DATEDIFF(DAY,PPC.PCHST_EFF_DT,PC.PCHST_EFF_DT)
	
    
    	, CASE 
			WHEN P.PLAN_ID = 'BES001' THEN PS.ETBL_DESC_TXT 
			WHEN P.PLAN_ID IN  ('CBS001') THEN 'Single Premium' 
             WHEN P.PLAN_ID IN ('KBE003') AND P.POL_BILL_TYP_CD = 'P' THEN 'Single Premium' 
			ELSE CASE WHEN P.PLAN_ID = 'KBE003' THEN 'Limited Premium' ELSE 'Regular Premium' END
		END AS PYM_STATUS

		,CASE WHEN AGD.DistributionChannelCode = 'BA' THEN ORG.ORG_CODE ELSE NULL END BANK_BRANCH_CODE
		,CASE WHEN AGD.DistributionChannelCode = 'BA' THEN ORG.NAME ELSE NULL END BANK_BRANCH_NAME
		,C.INTRO_ID
	INTO #TMP 
	FROM DLKHDIM..DIM_POLICY P 
	INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1 AND  P.IS_CURRENT=1 AND C.CVG_NUM = '01'
	LEFT JOIN (
		SELECT P.POL_ID, SUM(C.CVG_MPREM_AMT) CVG_MPREM_AMT, SUM(C.CVG_FACE_AMT) CVG_FACE_AMT, SUM(C.CVG_UNDSCNT_PREM) CVG_UNDSCNT_PREM FROM DLKHDIM..DIM_POLICY P 
		INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1 AND  P.IS_CURRENT=1 
		 WHERE NOT (P.POL_CSTAT_CD = '1' AND C.CVG_CSTAT_CD IN ('B','R', 'S'))
		GROUP BY P.POL_ID
		) PREM ON PREM.POL_ID = P.POL_ID
	INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
	INNER JOIN SGTB_POLICY_CLIENT PCL ON PCL.POL_ID = P.POL_ID AND PCL.POL_CLI_REL_TYP_CD='O' AND PCL.POL_CLI_REL_SUB_CD='P' --ADD PCL.POL_CLI_REL_SUB_CD='P' 2023/03/06
	INNER JOIN V_CLI_INFO CL ON CL.CLI_ID=PCL.CLI_ID 
	INNER JOIN SGTM_COVERAGE TEM ON TEM.POL_ID=P.POL_ID AND P.POL_BASE_CVG_NUM=TEM.CVG_NUM
	LEFT JOIN SGTM_AGENT_DETAIL AGD ON AGD.AgentId = W.AGT_ID
	LEFT JOIN DMS_ORGANIZATION ORG ON ORG.SALE_SUPPORT LIKE CONCAT('%',W.AGT_ID,'%')
	LEFT JOIN DMS_PARTNER PN ON PN.CODE = ORG.PARTNER_CODE AND HIERARCHICAL_MODEL = 3
	LEFT JOIN (SELECT POL_ID,MIN(PCHST_EFF_DT) PCHST_EFF_DT FROM SGTB_POLICY_CHANGE PPC WHERE PPC.PCHST_STAT_CD='A' AND PPC.POL_ACTV_TYP_ID='1082' GROUP BY POL_ID) PPC ON P.POL_ID=PPC.POL_ID
	LEFT JOIN SGTB_POLICY_CHANGE PC ON P.POL_ID=PC.POL_ID  AND PCHST_STAT_CD='A' AND POL_ACTV_TYP_ID IN ('1082','1084')
	LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
	LEFT JOIN SGTB_EDITTABLE PA ON P.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
	LEFT JOIN SGTB_EDITTABLE PS ON PS.ETBL_VALU_ID = C.CVG_STBL_1_CD AND PS.ETBL_TYP_ID = 'STB1' -- DL-297 SOUTHEANE 06052024 UPDATED-----
	WHERE P.POL_ID NOT IN ('001000744') AND P.POL_CSTAT_CD  IN ('1','B','3','E') 
		AND CAST(PC.PREV_UPDT_TS AS DATE) BETWEEN @START AND @END
		AND NOT (P.POL_CSTAT_CD = '1' AND C.CVG_CSTAT_CD IN ('B','R', 'S'))
		
	--OR PC.PCHST_EFF_DT IS NOT NULL
	GROUP BY POL_KEY,P.POL_ID,P.POL_APP_FORM_ID,W.AGT_ID,PC.PCHST_EFF_DT,P.PLAN_ID,PA.ETBL_DESC_TXT,POL_CSTAT_CD,PARA.DM_AV_DESC_TXT,
	POL_APP_RECV_DT,P.POL_APP_CMPLT_DT,P.POL_BILL_MODE_CD,P.POL_BILL_TYP_CD,PC.POL_ACTV_TYP_ID,PPC.PCHST_EFF_DT,CL.CLI_CNTCT_ID_TXT,CL.ENTR_SUR_NM,CL.ENTR_GIV_NM
	,AGD.Name
	,AGD.LeaderId
	,AGD.LeaderName
	,AGD.ManagerName
	,AGD.ManagerId
	,TEM.CVG_MAT_XPRY_DUR
	,PC.PREV_UPDT_TS
	,AGD.TitleRole
	,PN.NAME
	,PREM.CVG_MPREM_AMT
	,PREM.CVG_FACE_AMT
	,PS.ETBL_DESC_TXT 
	,PREM.CVG_UNDSCNT_PREM
	,ORG.ORG_CODE
	,ORG.NAME
	,AGD.DistributionChannelCode
	,AGD.DistributionChannel
	,PC.PCHST_NEW_VALU_TXT
	,C.INTRO_ID

	UPDATE #TMP SET COM_TYPE = 
	CASE 
    WHEN POL_DURATION_DAY >= 1 AND POL_DURATION_DAY < 365 THEN 'RFYP'
    WHEN POL_DURATION_DAY >= 365 AND POL_DURATION_DAY < 730 THEN '2YP'
    WHEN POL_DURATION_DAY >= 730 AND POL_DURATION_DAY < 1095 THEN '3YP'
    WHEN POL_DURATION_DAY >= 1095 AND POL_DURATION_DAY < 1460 THEN '4YP'
    WHEN POL_DURATION_DAY >= 1460 AND POL_DURATION_DAY < 1825 THEN '5YP'
    WHEN POL_DURATION_DAY >= 1825 AND POL_DURATION_DAY < 2190 THEN '6YP'
    WHEN POL_DURATION_DAY >= 2190 AND POL_DURATION_DAY < 2555 THEN '7YP'
    WHEN POL_DURATION_DAY >= 2555 AND POL_DURATION_DAY < 2920 THEN '8YP'
    WHEN POL_DURATION_DAY >= 2920 AND POL_DURATION_DAY < 3285 THEN '9YP'
    WHEN POL_DURATION_DAY >= 3285 AND POL_DURATION_DAY < 3650 THEN '10YP'
    WHEN POL_DURATION_DAY >= 3650 AND POL_DURATION_DAY < 4015 THEN '11YP'
    WHEN POL_DURATION_DAY >= 4015 AND POL_DURATION_DAY < 4380 THEN '12YP'
    WHEN POL_DURATION_DAY >= 4380 AND POL_DURATION_DAY < 4745 THEN '13YP'
    WHEN POL_DURATION_DAY >= 4745 AND POL_DURATION_DAY < 5110 THEN '14YP'
    WHEN POL_DURATION_DAY >= 5110 AND POL_DURATION_DAY < 5475 THEN '15YP'
    ELSE COM_TYPE
	END
	WHERE POL_ACTV_TYP_ID = '1082'
	--------------------------------------------

	SELECT DISTINCT T.*,POL_DURATION_MONTH = DATEDIFF(M,INITIAL_DATE,PCHST_EFF_DT)
	FROM #TMP T
	--WHERE T.POL_ID = '700003729 '
	--ORDER BY POL_ID
