CREATE PROC [dbo].[RPT_APPL_CASH] @STARTDATE DATE,@ENDDATE DATE
AS

 IF OBJECT_ID('tempdb..#TACTH') IS NOT NULL
  DROP TABLE #TACTH
  	 IF OBJECT_ID('tempdb..#TPHST') IS NOT NULL
  DROP TABLE #TPHST
   IF OBJECT_ID('tempdb..#TACTX') IS NOT NULL
  DROP TABLE #TACTX
   IF OBJECT_ID('tempdb..#TPOL') IS NOT NULL
  DROP TABLE #TPOL
     IF OBJECT_ID('tempdb..#TCOLL') IS NOT NULL
  DROP TABLE #TCOLL
     IF OBJECT_ID('tempdb..#TCOLD') IS NOT NULL
  DROP TABLE #TCOLD
     IF OBJECT_ID('tempdb..#COL') IS NOT NULL
  DROP TABLE #COL

SELECT * INTO #TACTH FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TACTH')
SELECT * INTO #TPHST FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TPHST')
SELECT * INTO #TACTX FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TACTX')
SELECT * INTO #TPOL FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TPOL')
    SELECT * into #TCOLL  FROM    OPENQUERY(uat7,'SELECT * FROM KCAPXUAT.TCOLL')
    SELECT *  into #TCOLD FROM    OPENQUERY(uat7,'SELECT * FROM KCAPXUAT.TCOLD')

	SELECT D.COLCT_EFF_DT,CL.PREV_UPDT_TS LPREV_UPDT_TS,CL.COLCT_DOC_DT,CL.COLCT_TOT_AMT,COLCT_ACCT_NUM,CL.COLCT_PAYR_NM,CL.COLCT_CLR_REJ_DT,CL.COLCT_STAT_CD,CL.COLCT_RCPT_NUM,PA.ETBL_DESC_TXT COLLEC_SRCE,CL.COLCT_REMARK,COLCT_REF_NUM,
D.PREV_UPDT_TS DPREV_UPDT_TS,D.POL_ID,D.COLCT_POL_AMT,D.COLCT_PREM_AMT,D.COLCT_DPOS_AMT,D.COLCT_LOAN_AMT,D.COLCT_APL_AMT,D.COLCT_PDF_AMT,D.COLCT_SIDFND_AMT,D.POL_PREM_SUSP_AMT,D.POL_MISC_SUSP_AMT,D.POL_OS_DISB_AMT,D.COLCT_TOPUP_AMT,
RIGHT('000000000'+ CONVERT(VARCHAR(9), CL.COLCT_MICR_NUM),9) COLCT_MICR_NUM into #COL FROM #TCOLL CL 
INNER JOIN #TCOLD D ON CL.COLCT_MICR_NUM=D.COLCT_MICR_NUM AND CL.COLCT_ID_NUM=D.COLCT_ID_NUM
LEFT JOIN SGTB_EDITTABLE PA ON PA.ETBL_VALU_ID=CL.COLCT_PREM_SRCE AND PA.ETBL_TYP_ID='PSRC' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'

SELECT DISTINCT R.*,CASE WHEN PH.PREV_UPDT_TS IS NULL THEN 'N' ELSE (CASE WHEN (ACCT_HIST_PST_DT)<=(PH.PREV_UPDT_TS) THEN 'N' ELSE 'R' END) END COLLECT_TYPE,F.COLCT_RCPT_NUM,F.COLLEC_SRCE,COLCT_REF_NUM,F.COLCT_DOC_DT,f.COLCT_EFF_DT,COLCT_MICR_NUM,COLCT_REMARK FROM (SELECT      GETDATE()                AS  REPORT_DT,
            TACTH.POL_ID,
            TPOL.POL_APP_FORM_ID,
            TPOL.POL_MPREM_AMT,
            TPOL.POL_INFC_DT,
            RTRIM(TDMAV.DM_AV_DESC_TXT) AS FREQUENCY,
            TACTH.ACCT_HIST_PRCES_DT,
			TACTH.ACCT_HIST_PST_DT,
            CASE WHEN TACTH.ACCT_HIST_AMT<0 THEN 'Reversed' ELSE 'Applied' end Type_,
            TACTH.USER_ID,
            TACTH.ACCT_HIST_AMT Applied_Amount,TACTH.ACCT_BASE_ID,TACTH.BUS_FCN_ID
            
FROM        #TPOL              AS  TPOL
  
INNER JOIN  (SELECT 
            POL_ID,
            ACCT_HIST_PRCES_DT,
			ACCT_HIST_PST_DT,
            USER_ID,
            ACCT_BASE_ID,
            ACCT_HIST_GEN_ID,CO_ID,ACCT_HIST_AMT,BUS_FCN_ID FROM #TACTH WHERE BUS_FCN_ID NOT IN ('0222')
UNION ALL
SELECT 
            POL_ID,
            ACCT_TRXN_PRCES_DT,
			CAST(ACCT_TRXN_GR_TS AS DATE) ACCT_TRXN_GR_TS,
            USER_ID,
            ACCT_BASE_ID,
            ACCT_TRXN_GEN_ID,CO_ID,ACCT_TRXN_AMT,BUS_FCN_ID  FROM #TACTX WHERE BUS_FCN_ID NOT IN ('0222'))             AS  TACTH 
ON          TACTH.CO_ID                 =   TPOL.CO_ID
  AND       TACTH.POL_ID                =   TPOL.POL_ID  
         
--  AND       TACTH.ACCT_HIST_AMT         >   0
  
  
-- BILLING FREQUENCY
LEFT JOIN   SGTM_PARA_1             AS  TDMAV
ON          TDMAV.DM_AV_TBL_CD          =   'POL-BILL-MODE-CD'
  AND       TDMAV.DM_AV_CD              =   TPOL.POL_BILL_MODE_CD
  AND TDMAV.DM_AV_DESC_LANG_CD='E' AND TDMAV.CO_ID='CP'

WHERE       TPOL.CO_ID                  =   'CP'  AND CAST(TACTH.ACCT_HIST_PST_DT AS DATE) BETWEEN  @STARTDATE AND @ENDDATE AND TPOL.POL_CSTAT_CD NOT IN ('2') 
and TACTH.ACCT_BASE_ID          in    ('249800')
or (TACTH.ACCT_BASE_ID='102300' and TACTH.BUS_FCN_ID='0462' AND CAST(TACTH.ACCT_HIST_PST_DT AS DATE) BETWEEN  @STARTDATE AND @ENDDATE)
) R LEFT JOIN (SELECT pol_id,pol_actv_typ_id,min(PREV_UPDT_TS) PREV_UPDT_TS FROM #TPHST PH WHERE  pol_actv_typ_id='1082' and pchst_stat_cd='A' 
group by pol_id,pol_actv_typ_id) PH ON R.POL_ID=PH.POL_ID
LEFT JOIN #COL F ON R.POL_ID=F.POL_ID AND R.ACCT_HIST_PST_DT=F.COLCT_CLR_REJ_DT AND R.Applied_Amount=F.COLCT_TOT_AMT
