
/***************************************************************************************************
	REPORT:.......... lETTER COVERSHEET (OPT. DEPT.)
	PURPOSE:......... LISTING DETAIL OF POLICY REAL TIME
        
    Changelog
    ***********
	VERSION    DATE CHNG      DESC
	VERS0.1		              Initial Version
	VERS0.2		              ENHANCE HC/RC OCC ClASS
	VERS0.3	   08-11-2023     ADD OVERSEA ADDR.
	VERS0.4	   30-01-2023     CHANGE AGENT ROLE BBM: BANCA 30,31,32,33,34 ARE BBM ROLE (PBD,RH,SBBM, BBM, SBBS), AGENCY 11, 22,23,25 ('RH', 'DRAD', 'RAD', 'BDM','SBDM')
	VERS0.5    10-04-2024     AML ADD RISK CLASSIFICATION DL-231
    VERS0.6    18-06-2025     ADD AML STATUS [DL-1173]
    VERS0.7    02-09-2025     [MIS] Coversheet: Field "Type" capture N/A [DL-1401]
    VERS0.8    08-09-2025     [MIS] Coversheet: Incorrect Premium Type of Policy EliteCare Single Premium [DL-1419]

****************************************************************************************************/
			
CREATE PROC [dbo].[RPT_COVER_SHEET] @POL VARCHAR(10) AS

	--DECLARE @POL	VARCHAR(20) = '700002362'

	DROP TABLE IF EXISTS #EDIT
	DROP TABLE IF EXISTS #TCLII
	DROP TABLE IF EXISTS #CLIB
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #CLI
	DROP TABLE IF EXISTS #POL
	DROP TABLE IF EXISTS #TCVG
	DROP TABLE IF EXISTS #TCLII
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #TCLIA
	DROP TABLE IF EXISTS #TCLIC
	DROP TABLE IF EXISTS #TREQT
	DROP TABLE IF EXISTS #TDMAD
	DROP TABLE IF EXISTS #ACTH
	DROP TABLE IF EXISTS #FINAL
	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS #XTAB
	DROP TABLE IF EXISTS #AGN
	DROP TABLE IF EXISTS #CREATE_BY
	DROP TABLE IF EXISTS #AUWR
	DROP TABLE IF EXISTS #FINALTMP --VERS0.5 Using TempTbl to receive POID information to execute SP to retreive level of Risk

	SELECT * INTO #AGN FROM SGTM_AGENT_DETAIL 
	--Check User Who create 
	SELECT TOP 1 * INTO #CREATE_BY  FROM [UAT7].[DB77IUA1].[KCAPXUAT].TDALG  WHERE CPEVNT_POL_CLI_CD='P' AND EVNT_ACT_CD='SIR' AND CPEVNT_POL_CLI_ID = @POL ORDER BY CPEVNT_TRXN_DT,CPEVNT_TRXN_TIME
    
	
	
	-- GET ONLY REQUIRED DATA FROM TEDIT ONLY
	/*	GET QUERY FROM DATAWARE HOUSE
	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #EDIT FROM SGTB_EDITTABLE
	WHERE ETBL_LANG_CD = 'E' AND CO_ID = 'CP'
			AND ETBL_TYP_ID IN ('OCCCD','DCHNL','CLDEC','CTYPC','MCPCD','CLOC','COMTH','PLAN','STB1','CSRC','MARST' , 'PKGTYP' ,''PACKAGE'' ) 
	*/
	-- GET QUERY FROM LIVE DATA 

	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #EDIT FROM OPENQUERY(UAT7,
	'	SELECT ETBL_TYP_ID ,ETBL_VALU_ID,ETBL_DESC_TXT
		FROM KCAPXUAT.TEDIT WHERE ETBL_LANG_CD = ''E'' AND CO_ID = ''CP'' AND ETBL_TYP_ID IN (''OCCCD'',''DCHNL'',''CLDEC'',''CTYPC'',''MCPCD'',''CLOC'',''COMTH'',''PLAN'',''STB1'',''CSRC'',''MARST'' , ''PKGTYP'' ,''PACKAGE'',''RENWMCD'', ''SMOKE'' ) 
	')
	-- GET ONLY REQUIRED DATA FROM XTAB
	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #XTAB FROM SGTM_PARA
	WHERE ETBL_LANG_CD = 'E' AND ETBL_TYP_ID = 'SOLDBR' OR ETBL_TYP_ID='CNTRY'

	-- GET ONLY REQUIRED INFO OF CLIENT BACK ACCOUNT
	SELECT * INTO #CLIB FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CB.BNK_ACCT_ID,CLI_BNK_ACCT_DT,BNK_ACCT_TYP_CD,BNK_ACCT_HLDR_NM,BNK_NM 
		FROM KCAPXUAT.TCLIB CB 
		INNER JOIN KCAPXUAT.TBNKA A ON CB.BNK_ACCT_ID = A.BNK_ACCT_ID AND CB.BNK_ID = A.BNK_ID AND CB.BNK_BR_ID = A.BNK_BR_ID
		INNER JOIN KCAPXUAT.TBNKB B ON B.BNK_ID = CB.BNK_ID 
		WHERE CLI_BNK_ACCT_CD = 1
	')
	-- GET REQUIRED INFO OF CLIENT ONLY - TCLI 
	-- HC/FC SELECT OCC_CLAS_1
	SELECT * INTO #CLI FROM OPENQUERY(UAT7,
	'	SELECT CLI.CLI_ID,CLI.CLI_BTH_DT,CLI.CLI_CIN_NUM,CLI.CLI_SEX_CD,CLI.CLI_HT,CLI.CLI_WGT,CLI.CLI_SMKR_CD,CLI.CLI_US_TAX_ID,CLI.OCCP_ID,CLI.CLI_OCCP_CLAS_CD ,CLI.CLI_MARIT_STAT_CD ,  
		CLI.CLI_CTZN_CTRY_CD, CLI.CLI_US_TAX_FILE_IND,CLI.CLI_UW_ANSWR_CD, OC.OCCP_CLAS_1_CD
		FROM KCAPXUAT.TCLI CLI
		LEFT JOIN KCAPXUAT.TOCTB OC ON OC.OCCP_ID = CLI.OCCP_ID 
	')

	-- GET REQUIRED INFO OF CLIENT INFO/INCOME
	SELECT CLI_ID,CLI_INCM_EFF_DT,EARN_INCM_MODE_CD,CLI_EARN_INCM_AMT
		, #LAST_UPDT = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLII
	FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_INCM_EFF_DT,EARN_INCM_MODE_CD,CLI_EARN_INCM_AMT,PREV_UPDT_TS
		FROM KCAPXUAT.TCLII
	')

	-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT
		, #LAST_UPDT = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM
	FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS
		FROM KCAPXUAT.TCLNM
	') ORDER BY ENTR_SUR_NM, ENTR_GIV_NM

	-- GET ONLY REQUIRED INFO ON CLIENT ADDRESS - TCLIA
	-- VERS0.3 ADD CLI_ADDR_TYP_CD 'O'
	SELECT CLI_ID,CLI_ADDR_LN_1_TXT = RTRIM(CLI_ADDR_LN_1_TXT),CLI_ADDR_LN_2_TXT = RTRIM(CLI_ADDR_LN_2_TXT)
		,CLI_ADDR_LN_3_TXT = RTRIM(CLI_ADDR_LN_3_TXT),CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD,CLI_CRNT_LOC_CD, CLI_ADDR_TYP_CD, CLI_CTRY_CD
	INTO #TCLIA FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_ADDR_LN_1_TXT,CLI_ADDR_LN_2_TXT,CLI_ADDR_LN_3_TXT,CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD,CLI_CRNT_LOC_CD, CLI_ADDR_TYP_CD, CLI_CTRY_CD
		FROM KCAPXUAT.TCLIA
		WHERE CLI_ADDR_TYP_CD IN (''PR'', ''O'')
	')

	-- GET ONLY REQUIRED INFO OF CLIENT CONTACT - TCLIC
	SELECT CLI_ID,CLI_CNTCT_ID_CD,CLI_CNTCT_ID_TXT = RTRIM(CLI_CNTCT_ID_TXT)
	INTO #TCLIC FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_CNTCT_ID_CD,CLI_CNTCT_ID_TXT
		FROM KCAPXUAT.TCLIC
	')

	-- GET ONLY REQUIRED INFO OF POLICY + POLICY WRITING
	SELECT * INTO #POL FROM OPENQUERY(UAT7,
	'	SELECT POL.POL_ID,POL.PLAN_ID,POL.POL_APP_SIGN_DT,POL.POL_APP_RECV_DT,POL.POL_APP_FORM_ID,POL.PREV_UPDT_USER_ID
			,POL.POL_CSTAT_CD,POL.POL_ISS_EFF_DT,POL.LOAN_CNTRCT_NUM,POL.POL_REJ_REASN_CD,POL.POL_BILL_MODE_CD,POL.SERV_BR_ID,POL.POL_GRS_APREM_AMT
			,POL.POL_MPREM_AMT,POL.COLCT_MTHD_CD,POL.POL_STAT_CHNG_DT,POL.POL_SAR,POL.CUST_SRC_CD
			,POLW.AGT_ID,POLW.POL_AGT_SHR_PCT,POLW.POL_SOLD_BR_ID
			,POLC.POL_CLI_REL_TYP_CD,POLC.CLI_ID , POL.POL_NOT , POL.USER_ID ,POL_PKG_ID ,POL_PKG_TYP_ID,POL.POL_CASE_STAT_CD,POL_RENW_MTHD_CD,POL_STP_CD,AML_STAT_CD,POL_BILL_TYP_CD
		FROM KCAPXUAT.TPOL POL
		INNER JOIN KCAPXUAT.TPOLW POLW ON POL.POL_ID = POLW.POL_ID
		INNER JOIN KCAPXUAT.TPOLC POLC ON POL.POL_ID = POLC.POL_ID
	')

	-- GET ONLY REQIRED INFO FROM COVERAGE
	SELECT * INTO #TCVG FROM OPENQUERY(UAT7,
	'	SELECT CVG.POL_ID,CVG.CVG_NUM,CVG.CVG_ISS_EFF_DT,CVG.CVG_RT_AGE,CVG.CVG_CSTAT_CD,CVG.CVG_FACE_AMT,CVG.PLAN_ID
			,CVG.CVG_SEX_CD,CVG.CVG_MAT_XPRY_DUR,CVG.PREM_PMT_DUR,CVG.CVG_STAT_PRCES_DT,CVG.ANN_MTG_INT_PCT
			,CVG.INT_CMPND_FREQ_CD,CVG.MTG_REPAY_FREQ_CD,CVG.CVG_STBL_1_CD,CVG.CVG_SAR_BASE,CVG_STBL_3_CD
			,CVGC.INSRD_CLI_ID,CVG_PREM_DISC_1_FCT,CVG_PREM_DISC_2_FCT 
		FROM KCAPXUAT.TCVG CVG
		INNER JOIN KCAPXUAT.TCVGC CVGC ON CVG.POL_ID = CVGC.POL_ID AND CVG.CVG_NUM = CVGC.CVG_NUM
	')

	-- GET ONLY POLICY HAVE REQUIREMENT
	SELECT * INTO #TREQT FROM OPENQUERY(UAT7,
	'SELECT POL_CLI_ID FROM KCAPXUAT.TREQT  GROUP BY POL_CLI_ID HAVING COUNT(REQIR_ID) = 1')

	-- GET ONLY REQUIRED INFO FROM TDMAD
	SELECT DM_AV_CD,DM_AV_TBL_CD,DM_AV_DESC_TXT = RTRIM(DM_AV_DESC_TXT) INTO #TDMAD FROM OPENQUERY(UAT7,
	'	SELECT DM_AV_CD,DM_AV_TBL_CD,DM_AV_DESC_TXT
		FROM KCAPXUAT.TDMAD WHERE CO_ID = ''CP'' AND DM_AV_DESC_LANG_CD = ''E'' AND DM_AV_TBL_CD IN (''INT-CMPND-FREQ-CD'', ''MTG-REPAY-FREQ-CD'')
	') 
		
	-- GET ONLY REQUIRED INFO FROM JOINING OF ACTH + ACTX
	SELECT * INTO #ACTH FROM OPENQUERY(UAT7,
	'	SELECT SUM(ACCT_HIST_AMT) HIS_AMT,POL_ID 
		FROM KCAPXUAT.TACTH 
		WHERE ACCT_BASE_ID=''102300'' 
		GROUP BY POL_ID

		UNION

		SELECT SUM(ACCT_TRXN_AMT) HIS_AMT,POL_ID 
		FROM KCAPXUAT.TACTX 
		WHERE ACCT_BASE_ID=''102300'' 
		GROUP BY POL_ID
	')	

	-- GET SOME INFO OF AGENT ONLY 
	SELECT * INTO #AGENT  FROM V_DMS_AGENT_REPORTING_LINE_LIVE

	---GET AUTO UNDERWRITING RULE
	SELECT POL_ID, STUFF( (SELECT  ', '+LTRIM(RTRIM(AUTO_UW_REL_CD)) +':'+ LTRIM(RTRIM(AUTO_UW_RULE_CD))
					FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') WHERE POL_ID = @POL
					FOR XML PATH('')),1,1,'') AUTO_UW_RULE_CD
			INTO #AUWR
			FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') 
			WHERE POL_ID = @POL
			GROUP BY POL_ID

	
	SELECT DISTINCT 
		--POL--
		POL1.POL_APP_SIGN_DT
		,POL1.POL_APP_RECV_DT POL_CREAT_DT
		,POL1.POL_ISS_EFF_DT POL_APP_RECV_DT
		,POL1.POL_ID
		,POL1.POL_APP_FORM_ID
		,POL1.PREV_UPDT_USER_ID
		,POL1.CUST_SRC_CD
		,CUST_SRC_DESC = CSRC.ETBL_DESC_TXT
		,POL1.POL_SOLD_BR_ID
		,POL_SOLD_BR_NAME = SLDBR.ETBL_DESC_TXT
		-- CLI -- 
		,CL.CLI_BTH_DT HCLI_BTH_DT
		,CL.CLI_CIN_NUM HCLI_ID_NUM
		,CL.CLI_SEX_CD HCLI_SEX_CD
		,CL.CLI_HT HCLI_HT
		,CL.CLI_WGT HCLI_WGT
		,CL.CLI_SMKR_CD HCLI_SMKR_CD
		,RTRIM(HSMK.ETBL_DESC_TXT) HCLI_SMKR_DESC
		,CL.CLI_US_TAX_FILE_IND HCLI_DOC_TYP
		,HOCCP_CD = RTRIM(CL.OCCP_ID)
		,HOCCP_ID = RTRIM(HE.ETBL_DESC_TXT) --CL.OCCP_ID 
		,HOCCP_DESC = RTRIM(HE.ETBL_DESC_TXT)
		,CI.ENTR_SUR_NM HENTR_SUR_NM
		,CI.ENTR_GIV_NM HENTR_GIV_NM
		,CL.CLI_ID HCLI_ID
		,CL.CLI_MARIT_STAT_CD HCLI_MSTAT_CD
		,H_MSTAT.ETBL_DESC_TXT HCLI_MSTAT_DESC
		,CLI_CTZN_DESC.ETBL_DESC_TXT HCLI_CTZN_DESC
		--UPDATE HAGE AS ERROR CASE PO#BLI AND PO HAVE NO COVERAGE
		,HAGE = DBO.CALCULATE_PO_AGE(CL.CLI_BTH_DT, POL1.POL_ISS_EFF_DT)
		,HCL_HQ = CASE WHEN CL.CLI_UW_ANSWR_CD = 'Y' THEN 'Yes' WHEN CL.CLI_UW_ANSWR_CD = 'N' THEN 'No' ELSE 'Unanswered' END
		,CAD.CLI_ADDR_LN_1_TXT HCLI_ADDR_LN_1_TXT
		,CAD.CLI_ADDR_LN_2_TXT HCLI_ADDR_LN_2
		,CAD.CLI_ADDR_LN_3_TXT HCLI_ADDR_LN_3
		,CMU.ETBL_DESC_TXT HCLI_ADDR_LN_2_TXT
		,DIS.ETBL_DESC_TXT HCLI_ADDR_LN_3_TXT
		,CIT.ETBL_DESC_TXT  HCLI_CITY_NM_TXT

		,COAD.CLI_ADDR_LN_1_TXT HCLI_OVRS_ADDR_LN_1_TXT   --VERS0.3
		,COAD.CLI_ADDR_LN_2_TXT HCLI_OVRS_ADDR_LN_2     --VERS0.3
		,COAD.CLI_ADDR_LN_3_TXT HCLI_OVRS_ADDR_LN_3   --VERS0.3
		,CNTY.ETBL_DESC_TXT  HCLI_OVRS_CNTY_NM_TXT    --VERS0.3

		,CASE 
			WHEN CINFOR.EARN_INCM_MODE_CD='M' THEN ISNULL(CINFOR.CLI_EARN_INCM_AMT,0)*12 
			ELSE ISNULL(CINFOR.CLI_EARN_INCM_AMT,0) END CLI_EARN_INCM_AMT
		,C1.CLI_CNTCT_ID_TXT HPHONE1
		,C2.CLI_CNTCT_ID_TXT HPHONE2
		,EM.CLI_CNTCT_ID_TXT HEMAIL
		,CASE WHEN RR.POL_CLI_ID IS NULL THEN 'NON-JET CASE' ELSE 'JET CASE' END JETCASE
		,POL1.LOAN_CNTRCT_NUM
		,CVG.CVG_NUM
		,CVG.INSRD_CLI_ID
		--CLI2--
		,CLI2.CLI_BTH_DT
		,CLI2.CLI_CIN_NUM CLI_ID_NUM
		,CLI2.CLI_SEX_CD
		,CLI2.CLI_HT
		,CLI2.CLI_WGT
		,CLI2.CLI_SMKR_CD
		,RTRIM(CSMK.ETBL_DESC_TXT) CLI_SMKR_DESC
		,'' CLI_DOC_TYP
		,CLI2.CLI_OCCP_CLAS_CD 
		,CLI2.OCCP_CLAS_1_CD  ---HC/FC SELECT OCC_CLAS_1
		,OCCP_CD = RTRIM(CLI2.OCCP_ID)
		,OCCP_ID = RTRIM(HHE.ETBL_DESC_TXT)	--	CLI2.OCCP_ID 
		,OCCP_DESC = RTRIM(HHE.ETBL_DESC_TXT)
		,CLNM2.ENTR_SUR_NM
		,CLNM2.ENTR_GIV_NM
		,CLI2.CLI_MARIT_STAT_CD HHCLI_MSTAT_CD
		,HH_MSTAT.ETBL_DESC_TXT HHCLI_MSTAT_DESC
		,CLI2_CTZN_DESC.ETBL_DESC_TXT HHCLI_CTZN_DESC
		
		,AGE = (SELECT TOP 1 CVG_RT_AGE FROM #TCVG WHERE INSRD_CLI_ID = CLI2.CLI_ID AND POL_ID = @POL) + 0
		,HHCL_HQ = CASE WHEN CLI2.CLI_UW_ANSWR_CD = 'Y' THEN 'Yes' WHEN CLI2.CLI_UW_ANSWR_CD = 'N' THEN 'No' ELSE 'Unanswered' END
		--FLOOR(DATEDIFF(DAY, CLI2.CLI_BTH_DT,CVG.CVG_ISS_EFF_DT) / 365.2375) 
		,CVG.CVG_FACE_AMT
		,CASE WHEN LEFT(CVG.CVG_CSTAT_CD,1)='P' THEN 'PD' 
			WHEN CVG.CVG_CSTAT_CD = '1' THEN 'IF' 
			WHEN CVG.CVG_CSTAT_CD = 'A' THEN 'CFI' 
			WHEN CVG.CVG_CSTAT_CD = 'B' THEN 'LAPSE' 
			WHEN CVG.CVG_CSTAT_CD = '3' THEN 'PAID' 
			ELSE 
				(CASE 
					WHEN POL1.POL_REJ_REASN_CD='PP' THEN POL1.POL_REJ_REASN_CD 
					WHEN POL1.POL_REJ_REASN_CD='NP' THEN 'WD' 
					WHEN POL1.POL_REJ_REASN_CD='NT' THEN 'CFI' 
					WHEN POL1.POL_REJ_REASN_CD='DC' THEN 'DECLINED' 
					ELSE 'NTU' 
				END) 
		END CVG_CSTAT_CD
		,CVG.PLAN_ID
		,CVG.CVG_SEX_CD
		,CVG.CVG_MAT_XPRY_DUR CVG_PREM_PAY_DUR
		,PREM_PMT_DUR = CASE WHEN CVG.PREM_PMT_DUR = 0 THEN CVG.CVG_MAT_XPRY_DUR ELSE CVG.PREM_PMT_DUR END	-- USER CALL "PREMIUM TERM" ELSE DIFF_CVG.PREM_PMT_DUR 
		,CVG.CVG_STAT_PRCES_DT CVG_APP_RECV_DT
		,CVG.ANN_MTG_INT_PCT			--	Annual Mortgage Interest Rate
		,CVG.INT_CMPND_FREQ_CD		--	Interest Compoundings Per Year
		,INT_CMPND_FREQ_DESC = RTRIM(CMPND.DM_AV_DESC_TXT)
		,CVG.MTG_REPAY_FREQ_CD		--	Mortgage Repayment Amount Frequency
		,MTG_REPAY_FREQ_DESC = RTRIM(MTGR.DM_AV_DESC_TXT)
		,CVG.CVG_STBL_1_CD			--	Sub-Table 1
		,CVG_STBL_1_DESC = RTRIM(STB1.ETBL_DESC_TXT)
		,CASE 
			WHEN CVG.PLAN_ID='DRD004' THEN CVG.CVG_FACE_AMT * 1.5 
			WHEN CVG.PLAN_ID='DWP002' THEN CVG.CVG_FACE_AMT * CAST(CVG.CVG_MAT_XPRY_DUR AS INT) * 0.5 
			ELSE CVG.CVG_SAR_BASE 
		END SAR
		,CVG.CVG_PREM_DISC_1_FCT 
        ,CVG.CVG_PREM_DISC_2_FCT 
		,CCAD.CLI_ADDR_LN_1_TXT
		,CCAD.CLI_ADDR_LN_2_TXT CLI_ADDR_LN_2
		,CCAD.CLI_ADDR_LN_3_TXT CLI_ADDR_LN_3
		,CMU1.ETBL_DESC_TXT CLI_ADDR_LN_2_TXT
		,DIS1.ETBL_DESC_TXT CLI_ADDR_LN_3_TXT
		,CIT1.ETBL_DESC_TXT CLI_CITY_NM_TXT

		,CCOAD.CLI_ADDR_LN_1_TXT CLI_OVRS_ADDR_LN_1_TXT   --VERS0.3
		,CCOAD.CLI_ADDR_LN_2_TXT CLI_OVRS_ADDR_LN_2     --VERS0.3
		,CCOAD.CLI_ADDR_LN_3_TXT CLI_OVRS_ADDR_LN_3   --VERS0.3
		,CNTY1.ETBL_DESC_TXT  CLI_OVRS_CNTY_NM_TXT    --VERS0.3

		,CC1.CLI_CNTCT_ID_TXT PHONE1
		,CC2.CLI_CNTCT_ID_TXT PHONE2
		,CEM.CLI_CNTCT_ID_TXT EMAIL
		,CASE WHEN CCINFOR.EARN_INCM_MODE_CD='M' THEN ISNULL(CCINFOR.CLI_EARN_INCM_AMT,0) 
			ELSE ISNULL(CCINFOR.CLI_EARN_INCM_AMT,0) END CCLI_EARN_INCM_AMT
		,CVG.POL_ID P_POL_ID
		,PO.PLAN_ID POPLAN_ID
		,POL_PLAN_NAME = RTRIM(PLN.ETBL_DESC_TXT)
		,PO.POL_CSTAT_CD POPOL_CSTAT_CD
		,DIFF_POL.POL_ID SPOL_ID
		,CUW.CVG_EMR_REASN_1_CD
		,CUW.UW_COMMENT
		,DIFF_POL.CLI_ID SCLI_ID
		,UWDEC.UWDECIS
        ,UWDEC.UWDECIS_VAL
		,SCC.ENTR_SUR_NM SENTR_SUR_NM
		,SCC.ENTR_GIV_NM SENTR_GIV_NM
		,DIFF_CVG.PLAN_ID POSPLAN_ID
		,DIFF_CVG.CVG_NUM POSCVG_NUM
		,DIFF_CVG.CVG_CSTAT_CD POSPOL_CSTAT_CD
		,SCGV.SUM_IN,BS.CVG_FACE_AMT BSSUM
		,CASE WHEN SCGV.PLAN_ID='DRD004' THEN  SCGV.SUM_IN*1.5 
			WHEN SCGV.PLAN_ID='DWP002' THEN SCGV.SUM_IN * CAST(SCGV.CVG_MAT_XPRY_DUR AS INT) * 0.5 
			ELSE  SCGV.CVG_SAR_BASE 
		END SSAR
		,TERM = DIFF_CVG.CVG_MAT_XPRY_DUR
		,PRE_TERM = CASE WHEN DIFF_CVG.PREM_PMT_DUR = 0 THEN DIFF_CVG.CVG_MAT_XPRY_DUR ELSE DIFF_CVG.PREM_PMT_DUR END	-- USER CALL "PREMIUM TERM"
		,DIFF_CVG.CVG_SEX_CD POS_CVG_SEX_CD
		,POSS.POL_STAT_CHNG_DT SPOL_APP_RECV_DT
		,POSS.POL_REJ_REASN_CD
		,CASE WHEN POSS.POL_CSTAT_CD = '1' THEN 'IF' 
			WHEN POSS.POL_CSTAT_CD = 'A' THEN 'CFI' 
			WHEN LEFT(POSS.POL_CSTAT_CD,1)='P' THEN 'PD' 
			WHEN POSS.POL_CSTAT_CD = 'B' THEN 'LAPSE' 
			WHEN POSS.POL_CSTAT_CD = '3' THEN 'PAID' 
			ELSE
				(CASE 
					WHEN POSS.POL_REJ_REASN_CD='PP' THEN POSS.POL_REJ_REASN_CD 
					WHEN POSS.POL_REJ_REASN_CD='NP' THEN 'WD' 
					WHEN POSS.POL_REJ_REASN_CD='NT' THEN 'CFI' 
					WHEN POSS.POL_REJ_REASN_CD='DC' THEN 'DECLINED' 
					ELSE 'NTU' 
				END) 
			END STATUS_
			,CB.BNK_ACCT_ID
			,CB.BNK_NM
			,CB.BNK_ACCT_HLDR_NM
			,CASE 
				WHEN POL1.POL_BILL_MODE_CD=1 THEN 'MONTHLY' 
				WHEN POL1.POL_BILL_MODE_CD=3 THEN 'QUARTERLY' 
				WHEN POL1.POL_BILL_MODE_CD=6 THEN 'SEMI-ANNUAL' 
				WHEN POL1.POL_BILL_MODE_CD=12 THEN 'ANNUALLY' 
			END POL_BILL_MODE_CD
			--,ABM = RTRIM(AGM.ENTR_SUR_NM) + ' ' + RTRIM(AGM.ENTR_GIV_NM)
			,CASE WHEN AG.CHANNEL = 'BA' THEN AG.LeaderName ELSE AG.ManagerName END ABM -- (BA) BRANCH MANAGER -- (AG) MANAGER
			,AG.ManagerId ABM_ID
			,ABM_PHON_NUMBER = AM.MOBILE_PHONE	--	VA.AGT_PHON_NUM ABM_PHON_NUM
			,BRANCH_NAME = CASE WHEN AG.CHANNEL = 'AG' THEN AG.LeaderName ELSE AG.BRANCH_NAME END   --- Branch Rep (BA)-- LEADERNAME(AG)
			,AGENT_NAME = AG.AGENT_NAME
			,AG_PHON_NUM = AG.MOBILE_PHONE  
			,AGT_ID = AG.AGENT_CODE  	    -- FA/FP Code Type servicing
			,AGT_STATUS = AG.AGENT_STATUS
			,POL1.SERV_BR_ID
			,ISNULL(PKG.ETBL_DESC_TXT , '') AS PACKAGE_NAME
			,PKG1.ETBL_DESC_TXT AS PACKAGE_TYPE 
			,POL1.POL_PKG_ID
			,POL1.POL_PKG_TYP_ID
			,CASE WHEN AG.CHANNEL = 'BA' THEN 'BANCA' WHEN AG.CHANNEL = 'AG' THEN 'AGENCY' ELSE NULL END CSC_NAME
			,MET.ETBL_DESC_TXT METHOD
			,CASE 
				WHEN POL1.POL_BILL_MODE_CD=1 THEN POL1.POL_MPREM_AMT*12 
				WHEN POL1.POL_BILL_MODE_CD=3 THEN POL1.POL_MPREM_AMT*4 
				WHEN POL1.POL_BILL_MODE_CD=6 THEN POL1.POL_MPREM_AMT*2 
				ELSE POL1.POL_MPREM_AMT 
			END POL_ANNUALPRE
			,POL1.POL_GRS_APREM_AMT
			,POL1.POL_MPREM_AMT
			,POL1.POL_AGT_SHR_PCT
			,ISNULL(PR.HIS_AMT,0) HIS_AMT
			,PLAN_ORDER = 
				CASE 
					WHEN LEFT(CVG.PLAN_ID,2)='DW' THEN '1' 
					WHEN CVG.PLAN_ID IN ('KBE001', 'CBR001','CBS001','BRL002') THEN '2' 
					ELSE '3' 
				END 
		    ,POL1.POL_NOT
			,PLAN_CODE = CASE CVG.PLAN_ID
				WHEN 'KBE001' THEN 'EduPro'
				WHEN 'DWP001' THEN 'WoP'
				WHEN 'DWP002' THEN 'CI WoP'
				WHEN 'DRD001' THEN 'FIR'
				WHEN 'DRD002' THEN 'FPR'
				WHEN 'DRD003' THEN 'HCR'
				WHEN 'DRD004' THEN 'FCR'
				WHEN 'CBR001' THEN 'Loan'
				WHEN 'CBS001' THEN 'Loan'
				WHEN 'BRL002' THEN 'CareGiver'
				WHEN 'KBE002' THEN 'EduPro-LTM'
				WHEN 'DRD005' THEN 'FPR-LTM'
				WHEN 'BES001' THEN 'EasyCare'
				WHEN 'BSS001' THEN CASE WHEN CVG.CVG_STBL_1_CD = 'SP' THEN 'SecureCare Plus' ELSE 'SecureCare' END
				WHEN 'KBE003' THEN 'EliteCare' -- VERS0.7
                WHEN 'BCLS01' THEN 'CreditCare'
                WHEN 'BCLP01' THEN 'CreditCare Plus'
                WHEN 'DRM001' THEN CASE WHEN CVG.CVG_STBL_3_CD IS NOT NULL AND CVG.CVG_STBL_3_CD <> ''
                                        THEN 'SMARTCare Medical ' + UPPER(LEFT(CVG.CVG_STBL_3_CD, 1)) + LOWER(SUBSTRING(CVG.CVG_STBL_3_CD, 2, LEN(CVG.CVG_STBL_3_CD)))
                                        ELSE 'N/A' END
				ELSE 'N/A'
				END
			,CASE WHEN POL1.POL_CASE_STAT_CD = 'M' THEN 'Manual-UW'			 
				  WHEN POL1.POL_CASE_STAT_CD = 'A' THEN 'Auto-UW'	
			END POL_CASE_STAT_CD
			,AUR.AUTO_UW_RULE_CD
			,RENW.ETBL_DESC_TXT POL_RENW_MTHD
			,PREMIUM_TYPE = CASE WHEN CVG.PLAN_ID IN ('KBE003', 'BCLS01', 'BCLP01') THEN CASE POL1.POL_BILL_TYP_CD -- VERS0.8
                                        WHEN 'P' THEN 'Single Premium'
                                        ELSE 'Regular Premium' END
                                 WHEN LEFT(CVG.PLAN_ID,2) IN ('KB','DW','DR','BR') THEN 'Regular Premium' 
								 WHEN CVG.PLAN_ID = 'CBR001' THEN 'Regular Premium'
								 WHEN CVG.PLAN_ID = 'CBS001' THEN 'Single Premium'
                                 WHEN CVG.PLAN_ID = 'BSS001' THEN CASE WHEN CVG.CVG_MAT_XPRY_DUR != CVG.PREM_PMT_DUR THEN 'Limited Premium' ELSE 'Regular Premium' END
								 ELSE RTRIM(PREMT.ETBL_DESC_TXT) END
			,RTRIM(STP.ETBL_DESC_TXT) STP_CODE
            ,POL1.AML_STAT_CD AML_CODE -- VERS0.6
	INTO #FINAL 
	FROM #POL POL1
	INNER JOIN #CLI CL ON CL.CLI_ID = POL1.CLI_ID
	LEFT JOIN #TCLNM CI ON CI.CLI_ID = CL.CLI_ID AND CI.#LAST_UPDT = 1

	INNER JOIN #TCVG CVG ON POL1.POL_ID = CVG.POL_ID
	INNER JOIN #CLI CLI2 ON CLI2.CLI_ID = CVG.INSRD_CLI_ID
	LEFT JOIN #TCLNM CLNM2 ON CLNM2.CLI_ID = CLI2.CLI_ID AND CLNM2.#LAST_UPDT = 1
	LEFT JOIN #XTAB CLI_CTZN_DESC on CL.CLI_CTZN_CTRY_CD = CLI_CTZN_DESC.ETBL_VALU_ID AND CLI_CTZN_DESC.ETBL_TYP_ID = 'CNTRY'
	LEFT JOIN #XTAB CLI2_CTZN_DESC on CLI2.CLI_CTZN_CTRY_CD = CLI2_CTZN_DESC.ETBL_VALU_ID AND CLI2_CTZN_DESC.ETBL_TYP_ID = 'CNTRY'
	
		---- AGENT
	LEFT JOIN #AGENT AG ON POL1.AGT_ID = CAST(AG.AGENT_CODE AS varchar)
	LEFT JOIN #AGENT AM ON AM.AGENT_CODE = AG.ManagerId
	
	LEFT JOIN #TCLII CCINFOR ON CLI2.CLI_ID=CCINFOR.CLI_ID AND CCINFOR.#LAST_UPDT = 1
	LEFT JOIN #CLIB CB ON POL1.CLI_ID=CB.CLI_ID
	LEFT JOIN #POL PO ON CVG.POL_ID=PO.POL_ID
	LEFT JOIN (
		SELECT PC.POL_ID,PC.INSRD_CLI_ID CLI_ID,P.CVG_NUM FROM #TCVG P INNER JOIN #TCVG PC ON P.POL_ID = PC.POL_ID AND P.CVG_NUM = PC.CVG_NUM 
	) DIFF_POL ON CVG.INSRD_CLI_ID = DIFF_POL.CLI_ID AND CVG.POL_ID <> DIFF_POL.POL_ID
	LEFT JOIN #TCVG DIFF_CVG ON DIFF_POL.POL_ID = DIFF_CVG.POL_ID AND DIFF_POL.CVG_NUM = DIFF_CVG.CVG_NUM
	LEFT JOIN #POL POSS ON DIFF_CVG.POL_ID = POSS.POL_ID
	LEFT JOIN #EDIT HE ON CL.OCCP_ID=HE.ETBL_VALU_ID AND HE.ETBL_TYP_ID='OCCCD'
	LEFT JOIN #EDIT HHE ON CLI2.OCCP_ID=HHE.ETBL_VALU_ID AND HHE.ETBL_TYP_ID='OCCCD'
	LEFT JOIN #EDIT H_MSTAT ON CL.CLI_MARIT_STAT_CD = H_MSTAT.ETBL_VALU_ID AND H_MSTAT.ETBL_TYP_ID = 'MARST'
    LEFT JOIN #EDIT HH_MSTAT ON CLI2.CLI_MARIT_STAT_CD = HH_MSTAT.ETBL_VALU_ID AND HH_MSTAT.ETBL_TYP_ID = 'MARST'
	--LEFT JOIN #EDIT CH ON AG.AGT_DISB_CHNL=CH.ETBL_VALU_ID AND CH.ETBL_TYP_ID='DCHNL'
	LEFT JOIN #TCLIA CAD ON CL.CLI_ID=CAD.CLI_ID AND CAD.CLI_ADDR_TYP_CD = 'PR'   --VERS0.3 
	LEFT JOIN #TCLIA CCAD ON CLI2.CLI_ID=CCAD.CLI_ID AND CCAD.CLI_ADDR_TYP_CD = 'PR'     --VERS0.3
	LEFT JOIN #TCLIA COAD ON CL.CLI_ID=COAD.CLI_ID AND COAD.CLI_ADDR_TYP_CD = 'O'    --VERS0.3
	LEFT JOIN #TCLIA CCOAD ON CLI2.CLI_ID=CCOAD.CLI_ID AND CCOAD.CLI_ADDR_TYP_CD = 'O'    --VERS0.3
	LEFT JOIN #TCLII CINFOR ON CL.CLI_ID=CINFOR.CLI_ID AND CINFOR.#LAST_UPDT = 1
	LEFT JOIN #TCVG BS ON DIFF_POL.POL_ID=BS.POL_ID AND LEFT(BS.PLAN_ID,1)='K'
	LEFT JOIN #TCLIC C1 ON CL.CLI_ID=C1.CLI_ID AND C1.CLI_CNTCT_ID_CD='MO'
	LEFT JOIN #TCLIC C2 ON CL.CLI_ID=C2.CLI_ID AND C2.CLI_CNTCT_ID_CD='HO'
	LEFT JOIN #TCLIC EM ON CL.CLI_ID=EM.CLI_ID AND EM.CLI_CNTCT_ID_CD='EM'
	LEFT JOIN #TCLIC CC1 ON CLI2.CLI_ID=CC1.CLI_ID AND CC1.CLI_CNTCT_ID_CD='MO'
	LEFT JOIN #TCLIC CC2 ON CLI2.CLI_ID=CC2.CLI_ID AND CC2.CLI_CNTCT_ID_CD='HO'
	LEFT JOIN #TCLIC CEM ON CLI2.CLI_ID=CEM.CLI_ID AND CEM.CLI_CNTCT_ID_CD='EM'
	---- POLICY PACKAGE
	LEFT JOIN #EDIT PKG on PKG.ETBL_VALU_ID = POL1.POL_PKG_ID AND ISNULL(POL1.POL_PKG_ID,'')<>'' AND PKG.ETBL_TYP_ID='PACKAGE'
	LEFT JOIN #EDIT PKG1 on PKG1.ETBL_VALU_ID = POL1.POL_PKG_TYP_ID AND ISNULL(POL1.POL_PKG_ID,'')<>''AND PKG1.ETBL_TYP_ID='PKGTYP' 

	LEFT JOIN (SELECT DISTINCT POL_ID,CVG_EMR_REASN_1_CD,UW_COMMENT,CVG_NUM FROM SGTM_COVERAGE) CUW ON CUW.POL_ID=DIFF_CVG.POL_ID AND DIFF_CVG.CVG_NUM=CUW.CVG_NUM
	LEFT JOIN 
	(
		SELECT CLI_ID,EDD.ETBL_DESC_TXT UWDECIS, EDD.ETBL_VALU_ID UWDECIS_VAL  FROM SGTM_CLIENT C 
		LEFT JOIN #EDIT EDD ON C.CLI_UWGDECN_CD=EDD.ETBL_VALU_ID AND  EDD.ETBL_TYP_ID='CLDEC' AND EDD.ETBL_VALU_ID<>''
	) UWDEC ON DIFF_POL.CLI_ID=UWDEC.CLI_ID
	LEFT JOIN 
	(
		SELECT POL_ID,CVG_NUM,SUM(CVG_FACE_AMT) SUM_IN,CVG_SAR_BASE,PLAN_ID,CVG_MAT_XPRY_DUR FROM #TCVG 
		GROUP BY POL_ID,CVG_NUM,CVG_SAR_BASE,PLAN_ID,CVG_MAT_XPRY_DUR
	) SCGV ON DIFF_POL.POL_ID = SCGV.POL_ID AND DIFF_POL.CVG_NUM = SCGV.CVG_NUM
	LEFT JOIN #TREQT RR ON POL1.POL_ID = RR.POL_CLI_ID
	LEFT JOIN (SELECT SUM(HIS_AMT) HIS_AMT,POL_ID FROM #ACTH GROUP BY POL_ID) PR ON POL1.POL_ID=PR.POL_ID
	LEFT JOIN #TCLNM SCC ON DIFF_POL.CLI_ID=SCC.CLI_ID AND CI.#LAST_UPDT = 1
	LEFT JOIN #EDIT CMU ON CMU.ETBL_TYP_ID='CTYPC' AND  CAD.CLI_ADDR_CNTY_CD=CMU.ETBL_VALU_ID 
	LEFT JOIN #EDIT DIS ON DIS.ETBL_TYP_ID='MCPCD' AND  CAD.CLI_ADDR_MUN_CD=DIS.ETBL_VALU_ID 
	LEFT JOIN #EDIT CIT ON CIT.ETBL_TYP_ID='CLOC' AND  CAD.CLI_CRNT_LOC_CD=CIT.ETBL_VALU_ID 
	LEFT JOIN #XTAB CNTY ON CNTY.ETBL_TYP_ID='CNTRY' AND  COAD.CLI_CTRY_CD=CNTY.ETBL_VALU_ID     --VERS0.3
	LEFT JOIN #EDIT CMU1 ON CMU1.ETBL_TYP_ID='CTYPC' AND  CCAD.CLI_ADDR_CNTY_CD=CMU1.ETBL_VALU_ID 
	LEFT JOIN #EDIT DIS1 ON DIS1.ETBL_TYP_ID='MCPCD' AND  CCAD.CLI_ADDR_MUN_CD=DIS1.ETBL_VALU_ID 
	LEFT JOIN #EDIT CIT1 ON CIT1.ETBL_TYP_ID='CLOC' AND  CCAD.CLI_CRNT_LOC_CD=CIT1.ETBL_VALU_ID 
	LEFT JOIN #XTAB CNTY1 ON CNTY1.ETBL_TYP_ID='CNTRY' AND  CCOAD.CLI_CTRY_CD=CNTY1.ETBL_VALU_ID     --VERS0.3
	LEFT JOIN #EDIT MET ON MET.ETBL_TYP_ID='COMTH' AND  POL1.COLCT_MTHD_CD=MET.ETBL_VALU_ID 
	LEFT JOIN #EDIT PLN ON  PLN.ETBL_TYP_ID = 'PLAN' AND PO.PLAN_ID = PLN.ETBL_VALU_ID  
	LEFT JOIN #EDIT STB1 ON STB1.ETBL_TYP_ID = 'STB1' AND CVG.CVG_STBL_1_CD = STB1.ETBL_VALU_ID 
	LEFT JOIN #TDMAD CMPND ON CMPND.DM_AV_TBL_CD = 'INT-CMPND-FREQ-CD' AND CVG.INT_CMPND_FREQ_CD = CMPND.DM_AV_CD
	LEFT JOIN #TDMAD MTGR ON MTGR.DM_AV_TBL_CD = 'MTG-REPAY-FREQ-CD' AND CVG.MTG_REPAY_FREQ_CD = MTGR.DM_AV_CD
	LEFT JOIN #EDIT CSRC ON POL1.CUST_SRC_CD = CSRC.ETBL_VALU_ID AND CSRC.ETBL_TYP_ID = 'CSRC'
	LEFT JOIN #XTAB SLDBR ON POL1.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_TYP_ID = 'SOLDBR'
	LEFT JOIN #AUWR AUR ON AUR.POL_ID = POL1.POL_ID
	LEFT JOIN #EDIT RENW ON POL1.POL_RENW_MTHD_CD = RENW.ETBL_VALU_ID AND RENW.ETBL_TYP_ID = 'RENWMCD'
	LEFT JOIN #EDIT HSMK ON CL.CLI_SMKR_CD = HSMK.ETBL_VALU_ID AND HSMK.ETBL_TYP_ID = 'SMOKE'
	LEFT JOIN #EDIT CSMK ON CLI2.CLI_SMKR_CD = CSMK.ETBL_VALU_ID AND CSMK.ETBL_TYP_ID = 'SMOKE'
	LEFT JOIN SGTB_EDITTABLE PREMT ON PREMT.ETBL_VALU_ID = CVG.CVG_STBL_1_CD AND PREMT.ETBL_TYP_ID = 'STB1'
	LEFT JOIN SGTB_EDITTABLE STP ON STP.ETBL_VALU_ID = POL1.POL_STP_CD AND STP.ETBL_TYP_ID = 'STPCD'
	WHERE POL1.POL_ID IN (@POL) 

------VERS0.5 GENERATE THE SCORE LEVEL OF RISK-------
	DECLARE @POID VARCHAR(20)
	DECLARE @LVLRISK INT 
	

	SELECT @POID = HCLI_ID FROM #FINAL 
	------------------------------------
	PRINT @POID

	

	SELECT DISTINCT F.*, ABM_PHON_NUM = F.ABM_PHON_NUMBER
		,ISNULL(S.SUMSAR,0) SUMSAR
		,ISNULL(SS.SUMSSAR,0) SUMSSAR
		,CASE 
			WHEN CVG_CSTAT_CD='PD' THEN 
				(CASE 
					WHEN LEFT(PLAN_ID,1)='K' AND CVG_FACE_AMT<3000 THEN 'ERROR' 
					WHEN PLAN_ID='DRD002' AND CVG_FACE_AMT<3000 THEN 'ERROR'
					WHEN PLAN_ID='DRD002' AND CVG_FACE_AMT<3000 THEN 'ERROR' 
					WHEN PLAN_ID='DRD001' AND  CVG_FACE_AMT<(SELECT TOP 1 CVG_FACE_AMT*0.1 FROM #FINAL WHERE LEFT(PLAN_ID,1)='K') THEN 'ERROR' 
					ELSE '' 
				END)  
			ELSE ''  
		END ERROR
		,CASE 
			WHEN STATUS_ IN ('PD','CFI') THEN 
				(CASE 
					WHEN LEFT(POSPLAN_ID,1)='K' AND SUM_IN<3000 THEN 'ERROR' 
					WHEN POSPLAN_ID='DRD002' AND SUM_IN<3000 THEN 'ERROR'
					WHEN POSPLAN_ID='DRD002' AND SUM_IN<3000 THEN 'ERROR' 
					WHEN POSPLAN_ID='DRD001' AND  SUM_IN<(BSSUM*0.1) THEN 'ERROR' 
					ELSE '' 
				END)  
			ELSE ''  
		END EERROR
		,(SELECT SUM(R.UW) UW FROM (SELECT SUM(SAR) UW,INSRD_CLI_ID  FROM (
				SELECT DISTINCT 
				-- INCLUEDE LAPSE COVERAGE <= 2 YEARS
				SAR = CASE WHEN CVG_CSTAT_CD = 'LAPSE' AND CVG_APP_RECV_DT < CAST(DATEADD(year, -2, DATEADD(day,-1,GETDATE())) AS DATE) THEN 0 ELSE SAR END
				,CVG_NUM,INSRD_CLI_ID 
				FROM #FINAL WHERE CVG_CSTAT_CD IN ('PD','IF','LAPSE')

			) T GROUP BY INSRD_CLI_ID) R) 
			+ (SELECT ISNULL(SUM(R.UW),0) UW FROM (SELECT ISNULL(SUM(SSAR),0) UW,SCLI_ID  FROM (
				SELECT DISTINCT 
				-- INCLUEDE LAPSE COVERAGE <= 2 YEARS
				SSAR = CASE WHEN STATUS_ = 'LAPSE' AND SPOL_APP_RECV_DT < CAST(DATEADD(year, -2, DATEADD(day,-1,GETDATE())) AS DATE) THEN 0 ELSE SSAR END
				,POSCVG_NUM,SCLI_ID 
				FROM #FINAL WHERE STATUS_ IN ('PD','IF','LAPSE')) T GROUP BY SCLI_ID) R) UW
		,DLCN.POL_ID DDPOL_ID
		,DLCN.CLI_NAME DDCLI_NAME
		,DLCN.CLI_ID DD_CLI_ID
		,DLCN.POL_STAT DDPOL_STAT
		,DLCN.DDCVG_FACE_AMT DDSUM_IS
		,DLCN.POL_SAR DDPOL_SAR
		,CASE WHEN ODER.POORDER IS NOT NULL THEN 'A' WHEN ODERR.POORDER IS NOT NULL THEN 'B' WHEN ODERRR.POORDER IS NOT NULL THEN 'D' ELSE 'C' END POORDER
		,post.USER_ID AS POST_BY
	INTO #FINALTMP
	FROM #FINAL F 
	LEFT JOIN (
		SELECT SUM(SAR) SUMSAR,INSRD_CLI_ID FROM 
			(SELECT DISTINCT SAR = CASE WHEN CVG_CSTAT_CD = 'LAPSE' AND CVG_APP_RECV_DT < CAST(DATEADD(year, -2, DATEADD(day,-1,GETDATE())) AS DATE) THEN 0 ELSE SAR END,CVG_NUM,INSRD_CLI_ID FROM #FINAL WHERE CVG_CSTAT_CD IN ('IF','LAPSE','PD')
		) T GROUP BY INSRD_CLI_ID
	) S ON F.INSRD_CLI_ID = S.INSRD_CLI_ID
	LEFT JOIN (
		SELECT SUM(SSAR) SUMSSAR,INSRD_CLI_ID FROM 
			(SELECT DISTINCT INSRD_CLI_ID,SPOL_ID,POSPLAN_ID,SSAR = CASE WHEN STATUS_ = 'LAPSE' AND SPOL_APP_RECV_DT < CAST(DATEADD(year, -2, DATEADD(day,-1,GETDATE())) AS DATE) THEN 0 ELSE SSAR END,POSCVG_NUM FROM #FINAL WHERE STATUS_ IN ('IF','LAPSE','PD')
		) T GROUP BY INSRD_CLI_ID
	) SS ON F.INSRD_CLI_ID=SS.INSRD_CLI_ID
	LEFT JOIN (SELECT INSRD_CLI_ID,LEFT(PLAN_ID,2) POORDER FROM #FINAL) ODER ON F.INSRD_CLI_ID=ODER.INSRD_CLI_ID AND ODER.POORDER='DW'
	LEFT JOIN (SELECT INSRD_CLI_ID,LEFT(PLAN_ID,2) POORDER FROM #FINAL) ODERR ON F.INSRD_CLI_ID=ODERR.INSRD_CLI_ID AND ODERR.POORDER IN ('KB','BE')	
	LEFT JOIN (SELECT INSRD_CLI_ID,LEFT(PLAN_ID,2) POORDER FROM #FINAL) ODERRR ON F.INSRD_CLI_ID=ODERRR.INSRD_CLI_ID AND ODERRR.POORDER='CB'
	--LEFT JOIN #AGENT AGM ON AGM.AGT_ID = F.ABM_ID
	LEFT JOIN #CREATE_BY post ON F.P_POL_ID = post.CPEVNT_POL_CLI_ID
	LEFT JOIN -- TO CHECK WHETHER HAVE DUPLICATE LOAN CONTRACT NUMBER OR NOT
	(
		SELECT POL1.POL_ID,POL1.CLI_ID,CONCAT(RTRIM(LTRIM(C.ENTR_SUR_NM)),' ',RTRIM(LTRIM(C.ENTR_GIV_NM))) CLI_NAME
			,POL_STAT = CASE WHEN POL1.POL_CSTAT_CD='1' THEN 'IF' 
				WHEN POL1.POL_CSTAT_CD='A' THEN 'CFI' 
				WHEN LEFT(POL1.POL_CSTAT_CD,1)='P' THEN 'PD' 
				WHEN POL1.POL_CSTAT_CD='B' THEN 'LAPSE' 
				ELSE(	
					CASE WHEN POL1.POL_REJ_REASN_CD='PP' THEN POL1.POL_REJ_REASN_CD 
					WHEN POL1.POL_REJ_REASN_CD='NP' THEN 'WD' 
					WHEN POL1.POL_REJ_REASN_CD='NT' THEN 'CFI' 
					WHEN POL1.POL_REJ_REASN_CD='DC' THEN 'DECLINED' ELSE 'NTU' 
					END) 
				END
			,SUM(CG.CVG_FACE_AMT) DDCVG_FACE_AMT
			,POL1.POL_SAR,LOAN_CNTRCT_NUM   
		FROM #POL POL1 
		INNER JOIN #TCLNM C ON C.CLI_ID=POL1.CLI_ID AND C.#LAST_UPDT = 1
		INNER JOIN #TCVG CG ON CG.POL_ID=POL1.POL_ID
		GROUP BY POL1.POL_ID,POL1.CLI_ID,C.ENTR_SUR_NM,C.ENTR_GIV_NM,POL1.POL_SAR,POL_REJ_REASN_CD,POL_CSTAT_CD,LOAN_CNTRCT_NUM
	) DLCN ON F.LOAN_CNTRCT_NUM = DLCN.LOAN_CNTRCT_NUM AND F.POL_ID <> DLCN.POL_ID AND F.LOAN_CNTRCT_NUM <> ''

	-------------------
	-------VERS0.4 EXECUTE STORE PROCEDURE-------------
	EXEC RPT_RISK_LEVEL_CLA_BYPOID @PO_ID = @POID, @RISK_LEVEL = @LVLRISK OUTPUT
	--PRINT @LVLRISK

	------GENERATE RESULT TO RETREIVE INFORMATION WITH RISK LEVEL--------------------------------

	SELECT FINALTMP.*,CASE WHEN @LVLRISK <= 5 THEN 'Low' WHEN @LVLRISK <=10 THEN 'Medium' else 'High' end RISKLEVEL  FROM #FINALTMP FINALTMP
