CREATE PROC [dbo].[RPT_POL_LISTING] @NAME VARCHAR(100)
AS
BEGIN
SELECT P.POL_ID,CL.CLI_ID,P.POL_APP_FORM_ID,CL.ENTR_SUR_NM,CL.ENTR_GIV_NM,CL.CLI_CNTCT_ID_TXT CLI_PHONE,PA.ETBL_DESC_TXT PLAN_DESC,CVG_SUM_INS_AMT SUM_ASS,
C.CVG_MPREM_AMT,
CASE WHEN POL_BILL_MODE_CD=3 THEN
'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Month' WHEN POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE POL_BILL_MODE_CD END PRE_MODE,P.POL_CREAT_DT POL_ISS_DT,P.POL_CSTAT_CD,PARA.DM_AV_DESC_TXT POL_STAT_DESC,
CL.CLI_ADDR_LN_1_TXT,CL.CLI_ADDR_LN_2_TXT,CL.CLI_ADDR_LN_3_TXT,CL.CLI_CITY_NM_TXT,
W.AGT_ID AGENT_CODE,POL_ISS_EFF_DT POL_COM_DT,POL_INFC_DT POL_INF_DT,
CVG_ME_FCT,C.CVG_MPREM_AMT/CVG_ME_FCT PRE_BEFORE,C.CVG_MPREM_AMT/CVG_ME_FCT PRE_AFTER
 FROM DLKHDIM..DIM_POLICY P
INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1 AND P.IS_CURRENT=1
INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
INNER JOIN DLKHDIM..DIM_POLICY_CLIENT PC ON PC.POL_ID=P.POL_ID AND PC.IS_CURRENT=1
INNER JOIN V_CLI_INFO CL ON CL.CLI_ID=PC.CLI_ID
LEFT JOIN SGTB_EDITTABLE PA ON C.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN'
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD'
WHERE ((ENTR_GIV_NM LIKE '%'+ @NAME +'%' OR ENTR_SUR_NM LIKE '%'+ @NAME +'%') OR P.POL_ID LIKE '%'+ @NAME +'') AND RTRIM(@NAME)<>''
END
