/***************************************************************************************************
	REPORT:.......... POLICY PAID TO DATE (OPT DEPT.)
	PURPOSE:......... DETAIL OF POLICY WITH PAID TO DATE 
        
    Changelog
    ***********
	VERSION    DATE CHNG   UPD_BY     DESC
	VERS0.1		                      Initial Version
	VERS0.1	   28-05-2024  DOM        GET UNDISCOUNT PREMIUM AMOUNT AS MODAL PREM FOR EASYCARE
***************************************************************************************************/

CREATE PROC [dbo].[RPT_POL_PAID_TO_DATE]
	@FDATE	DATE 
	,@TDATE	DATE 
AS
	--DECLARE	@FDATE	DATE	= '2024-05-01'
	--		,@TDATE	DATE	= '2024-11-27'

	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS #CLNM

	IF @FDATE = ''  SET @FDATE = '2018-01-01'
	IF @TDATE = ''  SET @TDATE = DATEADD(DAY,-1,GETDATE()) 

	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM) 
		,#LAST_UPDT_NM = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #CLNM FROM SGTM_CLIENT_IND

	SELECT AGT.AGT_ID,AGT.OVRID_BASE_AGT_ID,AGT.AGT_DISB_CHNL,AGT_DISB_CHNL_DESC = RTRIM(CHNL.ETBL_DESC_TXT),AGNM.ENTR_SUR_NM,AGNM.ENTR_GIV_NM
	INTO #AGENT 
	FROM SGTM_AG AGT
	LEFT JOIN #CLNM AGNM ON AGT.AGT_ID = AGNM.CLI_ID AND AGNM.#LAST_UPDT_NM = 1
	LEFT JOIN SGTB_EDITTABLE CHNL ON AGT.AGT_DISB_CHNL = CHNL.ETBL_VALU_ID AND CHNL.ETBL_TYP_ID = 'DCHNL' AND CHNL.ETBL_LANG_CD = 'E' AND CHNL.CO_ID = 'CP'
	
	SELECT DISTINCT
		PC.POL_ID
		,DBO.CONVERTDATE(TPOL.POL_PD_TO_DT_NUM) AS PAID_TO_DATE
		,CASE WHEN TPOL.POL_MPREM_AMT = 0 AND TPOL.PLAN_ID = 'BES001' THEN POLH.POL_UNDSCNT_MPREM_AMT 
			WHEN TPOL.POL_MPREM_AMT = 0  THEN POLH.POL_MPREM_AMT 
			WHEN TPOL.PLAN_ID = 'BES001' THEN C.CVG_UNDSCNT_PREM
			ELSE TPOL.POL_MPREM_AMT 
		END AS PREMIUM_PAID_AMT
		,TPOL.POL_CSTAT_CD
		,SYS_DATE = (SELECT MAX(ONLN_PRCES_DT) FROM OPENQUERY(UAT7,'SELECT ONLN_PRCES_DT FROM KCAPXUAT.TMAST'))
		,TPOL.POL_PREM_SUSP_AMT
		,TPOL.POL_OS_DISB_AMT
		,TPOL.POL_PREM_SUSP_DT
		,PAYMENT_MODE = RTRIM(BLM.DM_AV_DESC_TXT)
		,CASE WHEN POL_CSTAT_CD = 'B' THEN POL_STAT_CHNG_DT ELSE NULL END LAPSEDDATE
		,RTRIM(PSTAT.DM_AV_DESC_TXT) STATUSDES
		,RTRIM(PLN.ETBL_DESC_TXT) MAIN_PLAN
		,C.CVG_MAT_XPRY_DUR
		,POL_ISS_EFF_DT
		,ENTR_SUR_NM = (CLNM.ENTR_SUR_NM)
		,ENTR_GIV_NM = (CLNM.ENTR_GIV_NM)
		,PHONE = RTRIM(CLIC.CLI_CNTCT_ID_TXT) 
		,AGENTNAME = AGT.ENTR_SUR_NM + ' ' + AGT.ENTR_GIV_NM 
		,ABM_ID = AGM.AGT_ID
		,ABM_SURNAME = AGM.ENTR_SUR_NM
		,ABM_GIVNAME = (AGM.ENTR_GIV_NM)
		,AGT.OVRID_BASE_AGT_ID
		,LEADERNAME = AGL.ENTR_SUR_NM + ' ' + AGL.ENTR_GIV_NM 
		,CHANNEL = AGT.AGT_DISB_CHNL_DESC
		,AGT.AGT_ID
	FROM SGTB_POLICY TPOL
	LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE POLH ON TPOL.POL_ID = POLH.POL_ID
	INNER JOIN SGTM_COVERAGE C ON C.POL_ID=TPOL.POL_ID AND C.CVG_NUM = '01'
	INNER JOIN SGTB_POLICY_CLIENT PC ON PC.POL_ID=TPOL.POL_ID
	INNER JOIN SGTM_CLIENT_IND CLNM ON CLNM.CLI_ID = PC.CLI_ID 
	LEFT JOIN SGTB_POLICY_WRITING POLW ON TPOL.POL_ID = POLW.POL_ID

	LEFT JOIN #AGENT AGT ON AGT.AGT_ID = POLW.AGT_ID
	LEFT JOIN #AGENT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGENT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID

	LEFT JOIN SGTM_CLIENT_CONTACT CLIC ON PC.CLI_ID=CLIC.CLI_ID AND CLIC.CLI_CNTCT_ID_CD='MO'
	LEFT JOIN SGTM_PARA_1 PSTAT ON TPOL.POL_CSTAT_CD = PSTAT.DM_AV_CD AND PSTAT.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND PSTAT.DM_AV_DESC_LANG_CD = 'E' AND PSTAT.CO_ID = 'CP'
	LEFT JOIN SGTM_PARA_1 BLM ON TPOL.POL_BILL_MODE_CD=BLM.DM_AV_CD AND BLM.DM_AV_TBL_CD = 'POL-BILL-MODE-CD' AND BLM.DM_AV_DESC_LANG_CD = 'E' AND BLM.CO_ID = 'CP'
	LEFT JOIN SGTB_EDITTABLE PLN ON TPOL.PLAN_ID = PLN.ETBL_VALU_ID AND PLN.ETBL_TYP_ID = 'PLAN' AND PLN.ETBL_LANG_CD = 'E' AND PLN.CO_ID = 'CP'
	WHERE POL_CSTAT_CD IN('1','B') 
	  AND POL_PD_TO_DT_NUM BETWEEN @FDATE AND @TDATE
