
/***************************************************************************************************
    Changelog
    ***********
	VERSION    DATE CHNG    UPDATE_BY    DESC
	VERS0.1		                          Initial Version
	VERS0.2	   13-06-2025    SAVRATH      Change UAT7 schema from KCAPXUT1 -> KCAPXUAT
****************************************************************************************************/

CREATE PROC [dbo].[RPT_COVERSHEET_HIS]  @POL VARCHAR(100)
AS

	DECLARE	@SQL		NVARCHAR(MAX)
	--		,@POL	VARCHAR(10) = '700003121'

	DROP TABLE IF EXISTS #CURR_POL
	DROP TABLE IF EXISTS #DIFF_POL
	DROP TABLE IF EXISTS #EDIT

	SELECT ETBL_TYP_ID,ETBL_VALU_ID,ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #EDIT FROM SGTB_EDITTABLE WHERE ETBL_LANG_CD = 'E' AND CO_ID='CP' AND ETBL_TYP_ID IN ('CTYPC','MCPCD','CLOC')

	CREATE TABLE #CURR_POL 
	(
		POL_ID VARCHAR(10)
		,CLI_ID VARCHAR(12)
		,CLI_CIN_NUM VARCHAR(21)
		,CLI_SEX_CD VARCHAR(1)
		,CLI_BTH_DT DATE
		,CLI_ADDR_LN_1_TXT VARCHAR(60)
		,CLI_ADDR_CNTY_CD VARCHAR(6)
		,CLI_ADDR_MUN_CD VARCHAR(6)
		,CLI_CRNT_LOC_CD VARCHAR(3)
		,CLI_CNTCT_ID_TXT VARCHAR(50)
		,ENTR_SUR_NM VARCHAR(20)
		,ENTR_GIV_NM VARCHAR(30)
		,CLNM_PREV_UPDT_TS	DATE
		,CLNM_LAST_UPDT SMALLINT
	)

	-- CURRENTY POLICY 
	-- QUERY TO GET DISTINCT LIFE INSURED + BENEFICIARY 
	SET @SQL = N'
				SELECT *
					,#CLNM_LAST_UPDT = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC) 
				FROM OPENQUERY(UAT7,
				''	
					SELECT CVGC.POL_ID
						,CLI.CLI_ID,CLI.CLI_CIN_NUM,CLI.CLI_SEX_CD,CLI.CLI_BTH_DT
						,CLIA.CLI_ADDR_LN_1_TXT,CLIA.CLI_ADDR_CNTY_CD,CLIA.CLI_ADDR_MUN_CD,CLIA.CLI_CRNT_LOC_CD
						,CLIC.CLI_CNTCT_ID_TXT
						,CLNM.ENTR_SUR_NM 
						,CLNM.ENTR_GIV_NM
						,CLNM.PREV_UPDT_TS
					FROM
					(
						SELECT INSRD_CLI_ID,POL_ID FROM KCAPXUAT.TCVGC CVGC WHERE POL_ID = ''''@POL''''
						UNION
						SELECT CLI_ID,POL_ID FROM KCAPXUAT.TBENE WHERE CLI_ID IS NOT NULL AND POL_ID = ''''@POL''''
					) CVGC
					LEFT JOIN KCAPXUAT.TCLI CLI ON CVGC.INSRD_CLI_ID = CLI.CLI_ID
					LEFT JOIN KCAPXUAT.TCLIC CLIC ON CLI.CLI_ID = CLIC.CLI_ID AND CLIC.CLI_CNTCT_ID_CD = ''''MO''''
					LEFT JOIN KCAPXUAT.TCLIA CLIA ON CLI.CLI_ID = CLIA.CLI_ID AND CLIA.CLI_ADDR_TYP_CD = ''''PR''''
					LEFT JOIN KCAPXUAT.TCLNM CLNM ON CLI.CLI_ID = CLNM.CLI_ID
				'')
			';
	SET @SQL = REPLACE(@SQL,'@POL',@POL)
	INSERT INTO #CURR_POL EXEC SP_EXECUTESQL @SQL;

	-- OTHER POLICY BESIDE ABOVE
	-- GET ALL LI'S ROLE + BENEFICIARY BESIDE POLICY ABOVE
	SELECT CVGC.POL_ID
		,CLI.CLI_ID,CLI.CLI_CIN_NUM,CLI.CLI_SEX_CD,CLI.CLI_BTH_DT
		,CLIA.CLI_ADDR_LN_1_TXT
		,CLIA.CLI_ADDR_CNTY_CD	--	COMMUNE
		,CLIA.CLI_ADDR_MUN_CD	--	DISTRICT
		,CLIA.CLI_CRNT_LOC_CD	--	CITY/PROVICE
		,CLIC.CLI_CNTCT_ID_TXT
		,CLNM.ENTR_SUR_NM 
		,CLNM.ENTR_GIV_NM
		,CLNM.PREV_UPDT_TS
		,CVGC.CLI_ROLE
	INTO #DIFF_POL
	FROM
	(
		SELECT POL_ID,CLI_ID,CLI_ROLE = 'PO' FROM SGTB_POLICY_CLIENT WHERE POL_CLI_REL_TYP_CD = 'O'

		UNION 

		SELECT CLI.POL_ID,CLI.INSRD_CLI_ID,CLI_ROLE = CASE WHEN CLI.INSRD_CLI_ID = BLI.BLI_ID THEN 'BLI' ELSE 'ALI' END
		FROM SGTB_COVERAGE_CLI CLI
		LEFT JOIN 
		(
			SELECT POL_ID,BLI_ID = INSRD_CLI_ID, INSRD_ROLE = 'BLI'
			FROM SGTB_COVERAGE_CLI WHERE CVG_NUM = '01'
		)AS BLI ON CLI.INSRD_CLI_ID = BLI.BLI_ID AND CLI.POL_ID = BLI.POL_ID	

		UNION

		SELECT POL_ID,CLI_ID,CLI_ROLE = 'BENE' FROM SGTM_BENE 

	) CVGC
	LEFT JOIN SGTM_CLIENT CLI ON CVGC.CLI_ID = CLI.CLI_ID
	LEFT JOIN SGTM_CLIENT_CONTACT CLIC ON CLI.CLI_ID = CLIC.CLI_ID AND CLIC.CLI_CNTCT_ID_CD = 'MO'
	LEFT JOIN SGTM_CLIENT_ADD CLIA ON CLI.CLI_ID = CLIA.CLI_ID AND CLIA.CLI_ADDR_TYP_CD = 'PR'
	LEFT JOIN SGTM_CLIENT_IND CLNM ON CLI.CLI_ID = CLNM.CLI_ID
	WHERE POL_ID != @POL

	-- CHECK WHETHER THE CLIENT OF ABOVE POLICY (CURRENT) HAVE BOUGHT ANY POLICIES/COVERAGES
	SELECT CURR.CLI_ID
		,CURR_POL_ID = CURR.POL_ID
		,DIFF_POL_ID = DIFF.POL_ID
		,DIFF.POL_ID
		,DIFF.ENTR_SUR_NM
		,DIFF.ENTR_GIV_NM
		,DIFF.CLI_CIN_NUM
		,DIFF.CLI_SEX_CD
		,DIFF.CLI_BTH_DT
		,DIFF.CLI_CNTCT_ID_TXT
		,DIFF.CLI_ADDR_LN_1_TXT
		,COMMUNE = CMU.ETBL_DESC_TXT 
		,DISTRICT = DIS.ETBL_DESC_TXT 
		,CITY = CIT.ETBL_DESC_TXT 
		,TYPE = DIFF.CLI_ROLE
	FROM #CURR_POL CURR
	INNER JOIN #DIFF_POL DIFF ON CURR.CLI_CIN_NUM = DIFF.CLI_CIN_NUM
		OR (CURR.ENTR_SUR_NM = DIFF.ENTR_SUR_NM AND CURR.ENTR_GIV_NM = DIFF.ENTR_GIV_NM AND CURR.CLI_BTH_DT = DIFF.CLI_BTH_DT AND CURR.CLI_SEX_CD = DIFF.CLI_SEX_CD)
		OR (CURR.ENTR_SUR_NM = DIFF.ENTR_SUR_NM AND CURR.ENTR_GIV_NM = DIFF.ENTR_GIV_NM AND CURR.CLI_BTH_DT = DIFF.CLI_BTH_DT AND CURR.CLI_CNTCT_ID_TXT = DIFF.CLI_CNTCT_ID_TXT)
		OR (CURR.ENTR_SUR_NM = DIFF.ENTR_SUR_NM AND CURR.ENTR_GIV_NM = DIFF.ENTR_GIV_NM AND CURR.CLI_SEX_CD = DIFF.CLI_SEX_CD AND CURR.CLI_CNTCT_ID_TXT = DIFF.CLI_CNTCT_ID_TXT)
		OR (CURR.ENTR_SUR_NM = DIFF.ENTR_SUR_NM AND CURR.ENTR_GIV_NM = DIFF.ENTR_GIV_NM AND CURR.CLI_BTH_DT = DIFF.CLI_BTH_DT AND CURR.CLI_ADDR_LN_1_TXT = DIFF.CLI_ADDR_LN_1_TXT
			AND CURR.CLI_ADDR_CNTY_CD = DIFF.CLI_ADDR_CNTY_CD AND CURR.CLI_ADDR_MUN_CD = DIFF.CLI_ADDR_MUN_CD AND CURR.CLI_CRNT_LOC_CD = DIFF.CLI_CRNT_LOC_CD)
		OR (CURR.ENTR_SUR_NM = DIFF.ENTR_SUR_NM AND CURR.ENTR_GIV_NM = DIFF.ENTR_GIV_NM AND CURR.CLI_SEX_CD = DIFF.CLI_SEX_CD
			AND CURR.CLI_ADDR_CNTY_CD = DIFF.CLI_ADDR_CNTY_CD AND CURR.CLI_ADDR_MUN_CD = DIFF.CLI_ADDR_MUN_CD AND CURR.CLI_CRNT_LOC_CD = DIFF.CLI_CRNT_LOC_CD)
	LEFT JOIN #EDIT CMU ON CMU.ETBL_TYP_ID = 'CTYPC' AND CURR.CLI_ADDR_CNTY_CD = CMU.ETBL_VALU_ID
	LEFT JOIN #EDIT DIS ON DIS.ETBL_TYP_ID = 'MCPCD' AND CURR.CLI_ADDR_MUN_CD = DIS.ETBL_VALU_ID
	LEFT JOIN #EDIT CIT ON CIT.ETBL_TYP_ID = 'CLOC' AND  CURR.CLI_CRNT_LOC_CD = CIT.ETBL_VALU_ID
	ORDER BY CURR.CLI_ID,DIFF.POL_ID
