CREATE PROC [dbo].[RPT_WCL] @date date,@POL varchar(100)
AS
	 IF OBJECT_ID('tempdb..#EDIT') IS NOT NULL
  DROP TABLE #EDIT
	 IF OBJECT_ID('tempdb..#CINFOR') IS NOT NULL
  DROP TABLE #CINFOR
	 IF OBJECT_ID('tempdb..#CLIB') IS NOT NULL
  DROP TABLE #CLIB
	 IF OBJECT_ID('tempdb..#CIND') IS NOT NULL
  DROP TABLE #CIND
	 IF OBJECT_ID('tempdb..#CLI') IS NOT NULL
  DROP TABLE #CLI
	 IF OBJECT_ID('tempdb..#POL') IS NOT NULL
  DROP TABLE #POL
	 IF OBJECT_ID('tempdb..#POLW') IS NOT NULL
  DROP TABLE #POLW
	 IF OBJECT_ID('tempdb..#POLC') IS NOT NULL
  DROP TABLE #POLC
    	 IF OBJECT_ID('tempdb..#TCLIA') IS NOT NULL
  DROP TABLE #TCLIA
    	 IF OBJECT_ID('tempdb..#TCLNM') IS NOT NULL
  DROP TABLE #TCLNM
      	 IF OBJECT_ID('tempdb..#CIND') IS NOT NULL
  DROP TABLE #CIND
        	 IF OBJECT_ID('tempdb..#TCVG') IS NOT NULL
  DROP TABLE #TCVG
          	 IF OBJECT_ID('tempdb..#TCLII') IS NOT NULL
  DROP TABLE #TCLII
          IF OBJECT_ID('tempdb..#TCVGC') IS NOT NULL
  DROP TABLE #TCVGC
            IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
              IF OBJECT_ID('tempdb..#T') IS NOT NULL
  DROP TABLE #T
  
  SELECT * INTO #TCLNM FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLNM')
  SELECT * INTO #CLI FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLI')
SELECT * INTO #POL FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TPOL')
SELECT * INTO #POLC FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TPOLC')
SELECT * INTO #TCVG FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCVG')
SELECT * INTO #TCVGC FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCVGC')
SELECT * INTO #TCLII FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLII')
SELECT * INTO #TCLIA FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLIA')

  SELECT I.* INTO #CIND FROM #TCLNM I INNER JOIN (SELECT MAX(CLI_INDV_EFF_DT) EFF, CLI_ID FROM #TCLNM GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INDV_EFF_DT=II.EFF

  
  SELECT P.POL_ID,PA.ETBL_DESC_TXT PO_PLAN,CVG.PLAN_ID,CVG.CVG_NUM,CVGC.INSRD_CLI_ID,POL_APP_CMPLT_DT,CA.CLI_ADDR_LN_1_TXT,CA.CLI_ADDR_LN_2_TXT,CA.CLI_ADDR_LN_3_TXT,CA.CLI_CITY_NM_TXT,CI.ENTR_SUR_NM HENTR_SUR_NM,CI.ENTR_GIV_NM HENTR_GIV_NM,
  CCI.ENTR_SUR_NM ENTR_SUR_NM,CCI.ENTR_GIV_NM ENTR_GIV_NM,CASE WHEN CLI_SEX_CD='M' THEN 'Mr.' ELSE 'Ms.' END TITLE
  INTO #TMP FROM #POL P INNER JOIN #POLC PC ON P.POL_ID=PC.POL_ID
  INNER JOIN #CLI C ON C.CLI_ID=PC.CLI_ID AND PC.POL_CLI_REL_SUB_CD='P'
  INNER JOIN #TCVG CVG ON CVG.POL_ID=P.POL_ID
  INNER JOIN #TCVGC CVGC ON CVG.POL_ID=CVGC.POL_ID AND CVG.CVG_NUM=CVGC.CVG_NUM
  LEFT JOIN #TCLIA CA ON C.CLI_ID=CA.CLI_ID
  LEFT JOIN #CIND CI ON C.CLI_ID=CI.CLI_ID
  LEFT JOIN #CIND CCI ON CVGC.INSRD_CLI_ID=CCI.CLI_ID
  LEFT JOIN SGTB_EDITTABLE PA ON P.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' 
  WHERE P.POL_ID=@POL OR (P.POL_APP_CMPLT_DT=@date AND (@POL='' OR @POL IS NULL))
  
  
SELECT *,0 AL INTO #T FROM #TMP WHERE LEFT(PLAN_ID,1) IN ('A','W')
  INSERT INTO #T
  SELECT *,0 FROM #TMP TM WHERE  LEFT(TM.PLAN_ID,1)='T' AND TM.INSRD_CLI_ID NOT IN (SELECT T.INSRD_CLI_ID FROM #T T WHERE T.POL_ID=TM.POL_ID)
  UPDATE T SET AL=1 FROM #T T INNER JOIN (SELECT DISTINCT POL_ID FROM #T WHERE LEFT(PLAN_ID,1)='T') TT ON T.POL_ID=TT.POL_ID
  SELECT * FROM #T
