/***************************************************************************************************
	REPORT:.......... 
	PURPOSE:......... 

    Changelog
    ***********
	VERSION    DATE CHNG    UPDATE_BY    DESC
	VERS0.9    12-03-2026   DARA	      Add Premium Type [DL-1857]
****************************************************************************************************/

CREATE PROC [dbo].[RPT_POL_SUS]
 	@START_DATE		DATE = NULL
	,@END_DATE		DATE = NULL
AS
	DROP TABLE IF EXISTS	#TPOL
	DROP TABLE IF EXISTS	#CRI

	-- DECLARE 	@START_DATE		DATE = '2026-01-01'
	-- DECLARE     @END_DATE		DATE = '2026-07-27'

	IF ISNULL(@START_DATE,'') = '' SET @START_DATE = '2000-01-01'
	IF ISNULL(@END_DATE,'') = '' SET @END_DATE = CONVERT(DATE,GETDATE())

	SELECT * INTO #TPOL FROM    OPENQUERY(UAT7,
	'	SELECT POL.POL_ID,POL.PLAN_ID,POL.POL_BILL_MODE_CD,POL.POL_PREM_SUSP_DT,POL.POL_PREM_SUSP_AMT,POL.POL_MISC_SUSP_DT
			,POL.POL_MISC_SUSP_AMT,POL.POL_PD_TO_DT_NUM,POL.POL_INFC_DT,POL.POL_CSTAT_CD,POL.APP_SUBMIT_CD
			,POL.POL_CASE_STAT_CD
			,POLC.POL_UW_RMRKS
			,POL.POL_BILL_TYP_CD
			,CVG.CVG_STBL_1_CD
		FROM KCAPXUAT.TPOL POL
		LEFT JOIN KCAPXUAT.TPOLC POLC ON POLC.POL_ID = POL.POL_ID AND POLC.POL_CLI_REL_TYP_CD = ''O''
		LEFT JOIN KCAPXUAT.TCVG CVG ON POL.POL_ID = CVG.POL_ID AND CVG.CVG_NUM = ''01''
		WHERE POL_PREM_SUSP_AMT > 0 OR POL_MISC_SUSP_AMT > 0	
	')

	
	-- GET ONLY FAIL CRITERIA CODE - CRI
	SELECT POL_ID, STUFF( (SELECT  ', '+LTRIM(RTRIM(AUTO_UW_REL_CD)) +':'+ LTRIM(RTRIM(AUTO_UW_RULE_CD))
			FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T WHERE T.POL_ID = T1.POL_ID
			FOR XML PATH('')),1,1,'') AUTO_UW_RULE_CD
	INTO #CRI
	FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T1
	GROUP BY POL_ID

	SELECT POL.POL_ID
		,PLAN_NAME = PLN.ETBL_DESC_TXT 
		,POL.POL_PREM_SUSP_DT
		,POL.POL_PREM_SUSP_AMT
		,SUS_DURATION = DATEDIFF(DAY,POL_PREM_SUSP_DT,GETDATE())
		,POL.POL_MISC_SUSP_DT
		,POL.POL_MISC_SUSP_AMT
		,POL_PD_TO_DT_NUM = CASE WHEN POL.POL_PD_TO_DT_NUM = '0000-00-00' THEN NULL ELSE POL_PD_TO_DT_NUM END
		,POL_STAT = RTRIM(PSTAT.DM_AV_DESC_TXT)
		,POL.POL_INFC_DT
		,POL.POL_BILL_MODE_CD
		,PRE_MODE = RTRIM(BLM.DM_AV_DESC_TXT)
		,PREM_TYPE = 			
			CASE 
				WHEN POL.PLAN_ID = 'BES001' THEN PS.ETBL_DESC_TXT 
				ELSE  FN_PREMIUM_TYPE.Premium_Type_Name
			END
		,POL.APP_SUBMIT_CD
		,CASE_STT = CASE WHEN POL.POL_CASE_STAT_CD ='M' THEN 'Manual' WHEN POL.POL_CASE_STAT_CD ='A' THEN 'Auto' ELSE '' END
		,CASE_STT_RMKS = POL.POL_UW_RMRKS
		,CRI.AUTO_UW_RULE_CD

	FROM #TPOL POL
	LEFT JOIN SGTB_EDITTABLE PLN ON PLN.ETBL_VALU_ID = PLAN_ID AND PLN.ETBL_TYP_ID = 'PLAN' AND PLN.CO_ID = 'CP' AND PLN.ETBL_LANG_CD = 'E'
	LEFT JOIN SGTM_PARA_1 PSTAT ON POL.POL_CSTAT_CD = PSTAT.DM_AV_CD AND PSTAT.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND PSTAT.DM_AV_DESC_LANG_CD = 'E' AND PSTAT.CO_ID = 'CP'
	LEFT JOIN SGTM_PARA_1 BLM ON POL.POL_BILL_MODE_CD = BLM.DM_AV_CD AND BLM.DM_AV_TBL_CD = 'BILLN-MODE-CD' AND BLM.DM_AV_DESC_LANG_CD = 'E' AND BLM.CO_ID = 'CP'
	LEFT JOIN #CRI CRI ON POL.POL_ID = CRI.POL_ID 
	LEFT JOIN SGTB_EDITTABLE PS ON PS.ETBL_VALU_ID = POL.CVG_STBL_1_CD AND PS.ETBL_TYP_ID = 'STB1' -- DL-1857- add premium type for BES001
	OUTER APPLY DLKHSTAGE.dbo.FN_GET_PREMIUM_TYPE(POL.PLAN_ID, POL.POL_BILL_TYP_CD) AS FN_PREMIUM_TYPE
	WHERE POL.POL_PREM_SUSP_DT BETWEEN @START_DATE AND @END_DATE
