CREATE PROC [RPT_COVER_SHEET_LI] @POL_ID VARCHAR(200)
AS
	 IF OBJECT_ID('tempdb..#CINFOR') IS NOT NULL
  DROP TABLE #CINFOR
	 IF OBJECT_ID('tempdb..#CIND') IS NOT NULL
  DROP TABLE #CIND
       IF OBJECT_ID('tempdb..#FINAL') IS NOT NULL
  DROP TABLE #FINAL
         IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP

  

SELECT I.* INTO #CINFOR FROM SGTM_CLIENT_INFO I INNER JOIN (SELECT MAX(CLI_INCM_EFF_DT) EFF, CLI_ID FROM SGTM_CLIENT_INFO GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INCM_EFF_DT=II.EFF
SELECT I.* INTO #CIND FROM SGTM_CLIENT_IND I INNER JOIN (SELECT MAX(CLI_INDV_EFF_DT) EFF, CLI_ID FROM SGTM_CLIENT_IND GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INDV_EFF_DT=II.EFF

SELECT distinct P.POL_APP_SIGN_DT,P.POL_APP_RECV_DT POL_CREAT_DT,P.POL_ISS_EFF_DT POL_APP_RECV_DT,P.POL_ID,P.POL_APP_FORM_ID,P.PREV_UPDT_USER_ID,CL.CLI_BTH_DT HCLI_BTH_DT,CL.CLI_CIN_NUM HCLI_ID_NUM,CL.CLI_SEX_CD HCLI_SEX_CD,CL.CLI_HT HCLI_HT,
CL.CLI_WGT HCLI_WGT,CL.CLI_SMKR_CD HCLI_SMKR_CD,CL.CLI_US_TAX_ID HCLI_DOC_TYP,CI.ENTR_SUR_NM HENTR_SUR_NM,CI.ENTR_GIV_NM HENTR_GIV_NM,CL.CLI_ID HCLI_ID,FLOOR(DATEDIFF(DAY, CL.CLI_BTH_DT, P.POL_ISS_EFF_DT) / 365.25) HAGE,
CAD.CLI_ADDR_LN_1_TXT HCLI_ADDR_LN_1_TXT,CMU.ETBL_DESC_TXT HCLI_ADDR_LN_2_TXT,DIS.ETBL_DESC_TXT HCLI_ADDR_LN_3_TXT,CIT.ETBL_DESC_TXT  HCLI_CITY_NM_TXT,CASE WHEN CINFOR.EARN_INCM_MODE_CD='M' THEN isnull(CINFOR.CLI_EARN_INCM_AMT,0)*12 ELSE isnull(CINFOR.CLI_EARN_INCM_AMT,0) END CLI_EARN_INCM_AMT,C1.CLI_CNTCT_ID_TXT HPHONE1,C2.CLI_CNTCT_ID_TXT HPHONE2,

CVL.CVG_NUM,CVL.INSRD_CLI_ID,CCL.CLI_BTH_DT,CCL.CLI_CIN_NUM CLI_ID_NUM,CCL.CLI_SEX_CD,CCL.CLI_HT,CCL.CLI_WGT,CCL.CLI_SMKR_CD,'' CLI_DOC_TYP,CCI.ENTR_SUR_NM,CCI.ENTR_GIV_NM,FLOOR(DATEDIFF(DAY, CCL.CLI_BTH_DT,CG.CVG_ISS_EFF_DT) / 365.25) AGE,
CG.CVG_FACE_AMT,
CASE WHEN LEFT(CG.CVG_CSTAT_CD,1)='P' THEN 'PD' WHEN CG.CVG_CSTAT_CD='1' THEN 'IF' WHEN CG.CVG_CSTAT_CD='A' THEN 'CFI' WHEN CG.CVG_CSTAT_CD='B' THEN 'Lapse'  ELSE 
(CASE WHEN P.POL_REJ_REASN_CD='PP' THEN P.POL_REJ_REASN_CD WHEN P.POL_REJ_REASN_CD='NP' THEN 'WD' WHEN P.POL_REJ_REASN_CD='NT' THEN 'CFI' WHEN P.POL_REJ_REASN_CD='DC' THEN 'Declined' ELSE 'NTU' END) END CVG_CSTAT_CD,
CG.PLAN_ID,CG.CVG_MAT_XPRY_DUR CVG_PREM_PAY_DUR,CG.CVG_STAT_PRCES_DT CVG_APP_RECV_DT,
CG.CVG_SAR_BASE SAR,
CCAD.CLI_ADDR_LN_1_TXT,CMU1.ETBL_DESC_TXT CLI_ADDR_LN_2_TXT,DIS1.ETBL_DESC_TXT CLI_ADDR_LN_3_TXT,CIT1.ETBL_DESC_TXT CLI_CITY_NM_TXT,CC1.CLI_CNTCT_ID_TXT PHONE1,CC2.CLI_CNTCT_ID_TXT PHONE2,CASE WHEN CCINFOR.EARN_INCM_MODE_CD='M' THEN ISNULL(CCINFOR.CLI_EARN_INCM_AMT,0) ELSE ISNULL(CCINFOR.CLI_EARN_INCM_AMT,0) END CCLI_EARN_INCM_AMT,

CVL.POL_ID P_POL_ID,PO.PLAN_ID POPLAN_ID,PO.POL_CSTAT_CD POPOL_CSTAT_CD,

CASE WHEN P.POL_BILL_MODE_CD=1 THEN 'Monthly' WHEN P.POL_BILL_MODE_CD=3 THEN 'Quarterly' WHEN P.POL_BILL_MODE_CD=6 THEN 'Semi-Annual' WHEN P.POL_BILL_MODE_CD=12 THEN 'Annually' END POL_BILL_MODE_CD
,case when P.POL_BILL_MODE_CD=1 then P.POL_MPREM_AMT*12 when P.POL_BILL_MODE_CD=3 then P.POL_MPREM_AMT*4 when P.POL_BILL_MODE_CD=6 then P.POL_MPREM_AMT*2 else P.POL_MPREM_AMT end POL_ANNUALPRE,P.POL_GRS_APREM_AMT,P.POL_MPREM_AMT,W.POL_AGT_SHR_PCT,
CASE WHEN LEFT(CG.PLAN_ID,2)='DW' THEN '1' WHEN LEFT(CG.PLAN_ID,1)='K' THEN '2' ELSE '3' END PLAN_ORDER INTO #FINAL FROM SGTB_POLICY P INNER JOIN SGTB_POLICY_CLIENT PC ON P.POL_ID=PC.POL_ID AND PC.POL_CLI_REL_SUB_CD='P'
INNER JOIN SGTM_CLIENT CL ON CL.CLI_ID=PC.CLI_ID
INNER JOIN #CIND CI ON CI.CLI_ID=CL.CLI_ID
INNER JOIN SGTB_POLICY_WRITING W ON P.POL_ID=W.POL_ID
INNER JOIN SGTB_COVERAGE_CLI CVL ON P.POL_ID=CVL.POL_ID
INNER JOIN SGTM_COVERAGE CG ON CG.POL_ID=CVL.POL_ID AND CG.CVG_NUM=CVL.CVG_NUM
INNER JOIN SGTM_CLIENT CCL ON CCL.CLI_ID=CVL.INSRD_CLI_ID
INNER JOIN #CIND CCI ON CCI.CLI_ID=CCL.CLI_ID
LEFT JOIN #CINFOR CCINFOR ON CCL.CLI_ID=CCINFOR.CLI_ID
LEFT JOIN SGTB_POLICY PO ON CVL.POL_ID=PO.POL_ID
LEFT JOIN SGTM_CLIENT_ADD CAD ON CL.CLI_ID=CAD.CLI_ID
LEFT JOIN SGTM_CLIENT_ADD CCAD ON CCL.CLI_ID=CCAD.CLI_ID
LEFT JOIN #CINFOR CINFOR ON CL.CLI_ID=CINFOR.CLI_ID
LEFT JOIN SGTM_CLIENT_CONTACT C1 ON CL.CLI_ID=C1.CLI_ID AND C1.CLI_CNTCT_ID_CD='MO'
LEFT JOIN SGTM_CLIENT_CONTACT C2 ON CL.CLI_ID=C2.CLI_ID AND C2.CLI_CNTCT_ID_CD='HO'
LEFT JOIN SGTM_CLIENT_CONTACT CC1 ON CCL.CLI_ID=CC1.CLI_ID AND CC1.CLI_CNTCT_ID_CD='MO'
LEFT JOIN SGTM_CLIENT_CONTACT CC2 ON CCL.CLI_ID=CC2.CLI_ID AND CC2.CLI_CNTCT_ID_CD='HO'
LEFT JOIN SGTB_EDITTABLE CMU ON CMU.ETBL_LANG_CD='E' AND CMU.ETBL_TYP_ID='CTYPC' AND  CAD.CLI_ADDR_CNTY_CD=CMU.ETBL_VALU_ID AND CMU.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE DIS ON DIS.ETBL_LANG_CD='E' AND DIS.ETBL_TYP_ID='MCPCD' AND  CAD.CLI_ADDR_MUN_CD=DIS.ETBL_VALU_ID AND DIS.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CIT ON CIT.ETBL_LANG_CD='E' AND CIT.ETBL_TYP_ID='CLOC' AND  CAD.CLI_CRNT_LOC_CD=CIT.ETBL_VALU_ID AND CIT.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CMU1 ON CMU1.ETBL_LANG_CD='E' AND CMU1.ETBL_TYP_ID='CTYPC' AND  CCAD.CLI_ADDR_CNTY_CD=CMU1.ETBL_VALU_ID AND CMU1.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE DIS1 ON DIS1.ETBL_LANG_CD='E' AND DIS1.ETBL_TYP_ID='MCPCD' AND  CCAD.CLI_ADDR_MUN_CD=DIS1.ETBL_VALU_ID AND DIS1.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CIT1 ON CIT1.ETBL_LANG_CD='E' AND CIT1.ETBL_TYP_ID='CLOC' AND  CCAD.CLI_CRNT_LOC_CD=CIT1.ETBL_VALU_ID AND CIT1.CO_ID='CP'
WHERE P.POL_ID=@POL_ID

SELECT F.*
,CASE WHEN ODER.POORDER IS NOT NULL THEN 'A' WHEN ODERR.POORDER IS NOT NULL THEN 'B' ELSE 'C' END POORDER into #TMP
 FROM #FINAL F 
LEFT JOIN (select INSRD_CLI_ID,LEFT(PLAN_ID,2) POORDER from #FINAL) ODER ON F.INSRD_CLI_ID=ODER.INSRD_CLI_ID AND ODER.POORDER='DW'
LEFT JOIN (select INSRD_CLI_ID,LEFT(PLAN_ID,1) POORDER from #FINAL) ODERR ON F.INSRD_CLI_ID=ODERR.INSRD_CLI_ID AND ODERR.POORDER='K'

DECLARE @CLI_ID VARCHAR(200),@GIV VARCHAR(200)
,@SUR VARCHAR(200),@ID VARCHAR(200),@SEX VARCHAR(100),@DOB DATE,@ADD1 VARCHAR(200),@COMMUNE VARCHAR(200),@DISTRICT VARCHAR(200),@CITY VARCHAR(200),@PHONE VARCHAR(200)

SELECT TOP 1 @CLI_ID=HCLI_ID,@GIV=HENTR_GIV_NM,@SUR=HENTR_SUR_NM,@ID=CLI_ID_NUM,@SEX=CLI_SEX_CD,@DOB=CLI_BTH_DT,@ADD1=CLI_ADDR_LN_1_TXT,
@COMMUNE=CLI_ADDR_LN_2_TXT,@DISTRICT=CLI_ADDR_LN_3_TXT,@CITY=CLI_CITY_NM_TXT,@PHONE=PHONE1 FROM #TMP WHERE POORDER='B'

SELECT DISTINCT  CL.CLI_ID,IND.ENTR_SUR_NM,IND.ENTR_GIV_NM,CLI_CIN_NUM,CLI_SEX_CD,CLI_BTH_DT,C1.CLI_CNTCT_ID_TXT,CA.CLI_ADDR_LN_1_TXT,CMU.ETBL_DESC_TXT COMMUNE,DIS.ETBL_DESC_TXT DISTRICT,CIT.ETBL_DESC_TXT CITY FROM SGTB_POLICY P INNER JOIN SGTB_POLICY_CLIENT PC ON P.POL_ID=PC.POL_ID
INNER JOIN SGTM_CLIENT CL ON CL.CLI_ID=PC.CLI_ID
INNER JOIN DLKHDIM..DIM_CLIENT_IND IND ON PC.CLI_ID=IND.CLI_ID AND IND.IS_CURRENT=1
LEFT JOIN SGTM_CLIENT_ADD CA ON CA.CLI_ID=CL.CLI_ID
LEFT JOIN SGTM_CLIENT_CONTACT C1 ON PC.CLI_ID=C1.CLI_ID AND C1.CLI_CNTCT_ID_CD='MO'
LEFT JOIN SGTB_EDITTABLE CMU ON CMU.ETBL_LANG_CD='E' AND CMU.ETBL_TYP_ID='CTYPC' AND  CA.CLI_ADDR_CNTY_CD=CMU.ETBL_VALU_ID AND CMU.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE DIS ON DIS.ETBL_LANG_CD='E' AND DIS.ETBL_TYP_ID='MCPCD' AND  CA.CLI_ADDR_MUN_CD=DIS.ETBL_VALU_ID AND DIS.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CIT ON CIT.ETBL_LANG_CD='E' AND CIT.ETBL_TYP_ID='CLOC' AND  CA.CLI_CRNT_LOC_CD=CIT.ETBL_VALU_ID AND CIT.CO_ID='CP'
WHERE  CL.CLI_ID<>@CLI_ID AND ((CL.CLI_CIN_NUM=@ID) 
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND CLI_SEX_CD=@SEX)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND CLI_ADDR_LN_1_TXT=@ADD1 AND CMU.ETBL_DESC_TXT=@COMMUNE AND DIS.ETBL_DESC_TXT=@DISTRICT AND CIT.ETBL_DESC_TXT=@CITY)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_SEX_CD=@SEX AND CLI_ADDR_LN_1_TXT=@ADD1 AND CMU.ETBL_DESC_TXT=@COMMUNE AND DIS.ETBL_DESC_TXT=@DISTRICT AND CIT.ETBL_DESC_TXT=@CITY)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND C1.CLI_CNTCT_ID_TXT=@PHONE)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_SEX_CD=@SEX AND C1.CLI_CNTCT_ID_TXT=@PHONE))
