
CREATE PROC [dbo].[RPT_DAILY_GL_DETAIL] @START_DATE DATE,@END_DATE DATE
AS

	--DECLARE  @START_DATE DATE = '2024-08-01',
	--		 @END_DATE DATE = '2024-09-30'

	IF OBJECT_ID('TEMPDB..#TZGLE') IS NOT NULL DROP TABLE #TZGLE
  	IF OBJECT_ID('TEMPDB..#TZGLE1') IS NOT NULL DROP TABLE #TZGLE1
    IF OBJECT_ID('TEMPDB..#TZGLE2') IS NOT NULL DROP TABLE #TZGLE2
  	IF OBJECT_ID('TEMPDB..#VE') IS NOT NULL DROP TABLE #VE
    IF OBJECT_ID('TEMPDB..#AGENT') IS NOT NULL DROP TABLE #AGENT

  
	SELECT * INTO #AGENT FROM DLKHFACT..FACT_AGENT 
	WHERE DATE_KEY = (SELECT MAX(DATE_KEY) FROM DLKHFACT..FACT_AGENT)

	SELECT  '02' AS RPT_CD
		,TACTH.ACCT_CRCY_CD
		,TACTH.ACCT_HIST_PRCES_DT AS ACCT_HIST_PRCES_DT
		,TACTH.ACCT_BASE_ID
		,TACTH.ACCT_YR AS ACCT_YR
		,TACTH.ACCT_SBSDRY_CO_ID
		,TACTH.ACCT_PLAN_ID
		,TACTH.BR_OR_DEPT_ID
		,TACTH.ACCT_ISS_LOC_CD
		,TACTH.ACCT_CRNT_LOC_CD
		,TACTH.ACCT_ISS_LOC_CD AS ACCT_ISS_LOC_CD1
		,(CASE WHEN ISNULL(TACTH.ACCT_DESC_TXT,'')<>'' THEN ISNULL(TACTH.ACCT_DESC_TXT,'')
		 ELSE
			CASE WHEN ISNULL(TACTD.ACCT_DESC_TXT,'')<>'' THEN ISNULL(TACTD.ACCT_DESC_TXT,'') 
			ELSE
				CASE WHEN ISNULL(TACTD1.ACCT_DESC_TXT,'')<>'' THEN ISNULL(TACTD1.ACCT_DESC_TXT,'') 		
				ELSE 
					CASE WHEN ISNULL(TACTD2.ACCT_DESC_TXT,'') <>'' THEN ISNULL(TACTD2.ACCT_DESC_TXT,'') 
					ELSE
						ISNULL(TACTD3.ACCT_DESC_TXT,'') 
					END 
				END 
			END
		END
		) AS ACCT_DESC_TXT 
		,TACTH.CHQ_VCHR_ID
		,TACTH.USER_ID
		,PP.POL_MPREM_AMT * (CASE WHEN CAST(PP.POL_BILL_MODE_CD AS INT)>0 THEN 12/CAST(PP.POL_BILL_MODE_CD AS INT) ELSE 1 END) ANUAL_PREM
		,TACTH.ACCT_HIST_GR_TS AS ACCT_HIST_GR_DT
		,ACCT_HIST_GR_TS
		,TACTH.POL_ID AS POL_ID
		,RTRIM(LTRIM(I.ENTR_SUR_NM))+' '+RTRIM(LTRIM(I.ENTR_GIV_NM)) POL_NAME
		,TACTH.POL_PLAN_ID AS POL_PLAN_ID
		,CASE WHEN PP.POL_CSTAT_CD IN ('1','3') THEN 'ACTIVE' ELSE 'CANCEL' END POL_PLAN_NAME,
		PP.POL_APP_FORM_ID
		,0 SUM_ASSURE
		,W.AGT_ID AS ENTRY_AGT_ID
		,A.ENTR_SUR_NM+' '+A.ENTR_GIV_NM  ENTRY_AGT_NAME
		,A.CHANNEL CSC_NAME
		,POL_APP_CMPLT_DT
		,CASE WHEN POL_BILL_MODE_CD=3 THEN
		'QUARTERLY' WHEN POL_BILL_MODE_CD=6 THEN 'SEMI ANNUAL' WHEN POL_BILL_MODE_CD=1 THEN 'MONTH' WHEN POL_BILL_MODE_CD=12 THEN 'ANNUAL'
		ELSE POL_BILL_MODE_CD END PRE_MODE
		,DBO.[CONVERTDATE](POL_PD_TO_DT_NUM) POL_PD_TO_DT_NUM
		,TACTH.CHQ_ID
		,TACTH.ACCT_HIST_SRC_CD 
		,(CASE WHEN TACTH.ACCT_HIST_AMT>0 THEN TACTH.ACCT_HIST_AMT ELSE 0 END) AS ACCT_HIST_AMT
		,(CASE WHEN TACTH.ACCT_HIST_AMT<0 THEN TACTH.ACCT_HIST_AMT ELSE 0 END) AS ACCT_HIST_AMT_A
		,TACTH.ACCT_SUB_TYP_CD AS ACCT_SUB_TYP_CD
		,TACTH.ACCT_HIST_BTCH_NUM
		,TACTH.BUS_FCN_ID AS BUS_FCN_ID
		,TACTH.BPF_ID AS BPF_ID
		, TACTH.ACCT_DESC_TXT ACCT_DESC_TXT_1
		, 0 COMM_HIST_AMT
		, 0 AGT_CPREM_AMT
		, TTBL_VALU_TXT ACCT_SUN_ID
		,PP.POL_MPREM_AMT
		,PP.POL_ISS_EFF_DT
		, '' ACCT_PRD_CD
		, ''  FUND_CD
		, ''  AGT_ID
		,PA.ETBL_DESC_TXT PLANNAME
		,ACCT_HIST_PART_NUM
		,MET.ETBL_DESC_TXT METHOD,P.CVG_MAT_XPRY_DUR TERM,PP.POL_ISS_EFF_DT POL_APP_RECV_DT,PARA.DM_AV_DESC_TXT POL_STAT,PP.POL_INFC_DT,ACCT_HIST_GEN_ID,POL_COMNT_TXT INTO #TZGLE
	FROM SGTB_ACCOUNTING_TRANHIS TACTH
	LEFT JOIN SGTM_TTTAB TZGLM ON TACTH.ACCT_BASE_ID=TZGLM.ETBL_VALU_ID 
	LEFT JOIN SGTM_ACCOUNTDESC TACTD ON TACTH.CO_ID = TACTD.CO_ID AND (TACTH.ACCT_BASE_ID = TACTD.ACCT_DESC_ID) AND TACTH.ACCT_DESC_REASN_CD = TACTD.ACCT_DESC_REASN_CD AND TACTD.ACCT_DESC_LANG_CD='E'
	LEFT JOIN SGTM_ACCOUNTDESC TACTD1 ON TACTH.CO_ID = TACTD1.CO_ID AND(TACTH.ACCT_BASE_ID = TACTD1.ACCT_DESC_ID) AND ISNULL(TACTD1.ACCT_DESC_REASN_CD,'')='' AND TACTD.ACCT_DESC_REASN_CD IS NULL AND TACTD1.ACCT_DESC_LANG_CD='E'
	LEFT JOIN SGTM_ACCOUNTDESC TACTD2 ON TACTH.CO_ID = TACTD2.CO_ID AND TACTD2.ACCT_DESC_ID=CONCAT(LEFT(TACTH.ACCT_BASE_ID,1),'00000') AND TACTH.ACCT_DESC_REASN_CD = TACTD2.ACCT_DESC_REASN_CD AND TACTD.ACCT_DESC_REASN_CD IS NULL AND TACTD1.ACCT_DESC_REASN_CD IS NULL AND TACTD2.ACCT_DESC_LANG_CD='E'
	LEFT JOIN SGTM_ACCOUNTDESC TACTD3 ON TACTH.CO_ID = TACTD3.CO_ID AND TACTD3.ACCT_DESC_ID=CONCAT(LEFT(TACTH.ACCT_BASE_ID,1),'00000') AND ISNULL(TACTD3.ACCT_DESC_REASN_CD,'')='' AND TACTD.ACCT_DESC_REASN_CD IS NULL AND TACTD1.ACCT_DESC_REASN_CD IS NULL AND TACTD2.ACCT_DESC_REASN_CD IS NULL AND TACTD3.ACCT_DESC_LANG_CD='E'
	LEFT JOIN SGTB_POLICY_WRITING W ON TACTH.POL_ID=W.POL_ID
	INNER JOIN SGTB_POLICY_CLIENT C ON C.POL_ID=TACTH.POL_ID  AND C.POL_CLI_REL_TYP_CD = 'O' -- POLICY OWNER
	INNER JOIN DLKHDIM..DIM_CLIENT_IND I ON I.CLI_ID=C.CLI_ID AND I.IS_CURRENT=1
	INNER JOIN (SELECT POL_ID,CVG_MAT_XPRY_DUR FROM SGTM_COVERAGE WHERE CVG_NUM = '01') P ON P.POL_ID=TACTH.POL_ID
	INNER JOIN SGTB_POLICY PP ON PP.POL_ID=P.POL_ID
	LEFT JOIN SGTB_EDITTABLE PA ON TACTH.POL_PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
	LEFT JOIN SGTM_PARA_1 PARA ON PP.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
	LEFT JOIN SGTB_EDITTABLE MET ON MET.ETBL_LANG_CD='E' AND MET.ETBL_TYP_ID='COMTH' AND  PP.COLCT_MTHD_CD=MET.ETBL_VALU_ID AND MET.CO_ID='CP'
	LEFT JOIN V_AGENT A ON W.AGT_ID=A.AGT_ID --AND A.AGT_CLI_REL_TYP_CD = 'R' --REGULAR AGENT
	WHERE TACTH.CO_ID = 'CP' 
	  AND TACTH.ACCT_HIST_PST_DT BETWEEN @START_DATE AND @END_DATE-- AND TACTH.ETL_DATE=@END_DATE
	  --AND TACTH.POL_ID = '700002852'
	 ORDER BY TACTH.ACCT_BASE_ID

	SELECT DISTINCT
		RPT_CD
		,ACCT_CRCY_CD
		,ACCT_HIST_PRCES_DT
		,ACCT_BASE_ID
		,ACCT_YR
		,ACCT_SBSDRY_CO_ID
		,ACCT_PLAN_ID
		,BR_OR_DEPT_ID
		,ACCT_ISS_LOC_CD
		,ACCT_CRNT_LOC_CD
		,ACCT_DESC_TXT
		,CHQ_VCHR_ID
		,USER_ID
		,ANUAL_PREM
		,ACCT_HIST_GR_DT
		,POL_ID
		,POL_PD_TO_DT_NUM
		,POL_NAME
		,POL_PLAN_ID
		,POL_PLAN_NAME
		,POL_APP_FORM_ID
		,SUM_ASSURE
		,PRE_MODE
		,ENTRY_AGT_ID
		,ENTRY_AGT_NAME
		,CSC_NAME,POL_APP_CMPLT_DT
		,CHQ_ID
		,ACCT_HIST_SRC_CD
		,ACCT_HIST_AMT
		,ACCT_HIST_AMT_A
		,ACCT_SUB_TYP_CD
		,ACCT_HIST_BTCH_NUM
		,BUS_FCN_ID
		,ACCT_DESC_TXT_1
		,COMM_HIST_AMT
		,AGT_CPREM_AMT
		,ACCT_SUN_ID
		,POL_MPREM_AMT
		,POL_ISS_EFF_DT
		,ACCT_PRD_CD
		,FUND_CD
		,AGT_ID
		,PLANNAME
		,ACCT_HIST_PART_NUM,METHOD,TERM,POL_APP_RECV_DT,POL_STAT,POL_INFC_DT,ACCT_HIST_GEN_ID,POL_COMNT_TXT 
	INTO #TZGLE1
	FROM #TZGLE
	WHERE NOT (ACCT_BASE_ID LIKE '3S10_0' AND ACCT_DESC_TXT = 'SFG ACCT - ADD PR')

	SELECT RPT_CD
		,ACCT_CRCY_CD
		,ACCT_HIST_PRCES_DT
		,ACCT_BASE_ID
		,ACCT_YR
		,ACCT_SBSDRY_CO_ID
		,ACCT_PLAN_ID
		,BR_OR_DEPT_ID
		,ACCT_ISS_LOC_CD
		,ACCT_CRNT_LOC_CD
		,ACCT_DESC_TXT
		,CHQ_VCHR_ID
		,USER_ID
		,ANUAL_PREM
		,ACCT_HIST_GR_DT
		,POL_ID
		,POL_PD_TO_DT_NUM
		,POL_NAME
		,POL_PLAN_ID
		,POL_PLAN_NAME
		,POL_APP_FORM_ID
		,SUM_ASSURE
		,PRE_MODE
		,ENTRY_AGT_ID
		,ENTRY_AGT_NAME
		,CSC_NAME,POL_APP_CMPLT_DT
		,CHQ_ID
		,ACCT_HIST_SRC_CD
		,SUM(ACCT_HIST_AMT) ACCT_HIST_AMT
		,SUM(ACCT_HIST_AMT_A) ACCT_HIST_AMT_A
		,ACCT_SUB_TYP_CD
		,ACCT_HIST_BTCH_NUM
		,BUS_FCN_ID
		,ACCT_DESC_TXT_1
		,COMM_HIST_AMT
		,AGT_CPREM_AMT
		,ACCT_SUN_ID
		,POL_MPREM_AMT
		,POL_ISS_EFF_DT
		,ACCT_PRD_CD
		,FUND_CD
		,AGT_ID
		,PLANNAME,ACCT_HIST_PART_NUM,METHOD,TERM,POL_APP_RECV_DT,POL_STAT,POL_INFC_DT,POL_COMNT_TXT, ACCT_HIST_GEN_ID
	INTO #TZGLE2 
	FROM #TZGLE1 GROUP BY RPT_CD
		,ACCT_CRCY_CD
		,ACCT_HIST_PRCES_DT
		,ACCT_BASE_ID
		,ACCT_YR
		,ACCT_SBSDRY_CO_ID
		,ACCT_PLAN_ID
		,BR_OR_DEPT_ID
		,ACCT_ISS_LOC_CD
		,ACCT_CRNT_LOC_CD
		,ACCT_DESC_TXT
		,CHQ_VCHR_ID
		,USER_ID
		,ANUAL_PREM
		,ACCT_HIST_GR_DT
		,POL_ID
		,POL_PD_TO_DT_NUM
		,POL_NAME
		,POL_PLAN_ID
		,POL_PLAN_NAME
		,POL_APP_FORM_ID
		,SUM_ASSURE
		,PRE_MODE
		,ENTRY_AGT_ID
		,ENTRY_AGT_NAME
		,CSC_NAME,POL_APP_CMPLT_DT
		,CHQ_ID
		,ACCT_HIST_SRC_CD
		,ACCT_SUB_TYP_CD
		,ACCT_HIST_BTCH_NUM
		,BUS_FCN_ID
		,ACCT_DESC_TXT_1
		,COMM_HIST_AMT
		,AGT_CPREM_AMT
		,ACCT_SUN_ID
		,POL_MPREM_AMT
		,POL_ISS_EFF_DT
		,ACCT_PRD_CD
		,FUND_CD
		,AGT_ID
		,PLANNAME,ACCT_HIST_PART_NUM,METHOD,TERM,POL_APP_RECV_DT,POL_STAT,POL_INFC_DT,POL_COMNT_TXT,ACCT_HIST_GEN_ID

	SELECT CO_ID, POL_ID INTO #VE FROM DLKHDIM..DIM_POLICY 
	WHERE CO_ID = 'CP' AND POL_BUS_CLAS_CD = 'L'  AND POL_PREM_TYP_CD = 'B' AND IS_CURRENT=1

	SELECT  
		@END_DATE AS TRXN_PRCES_DT
		,'POL' AS TYPE
		,A.ACCT_HIST_PRCES_DT
		,A.ACCT_BASE_ID
		,A.ACCT_DESC_TXT
		,A.USER_ID
		,A.POL_ID
		,ANUAL_PREM
		,POL_PD_TO_DT_NUM
		,POL_NAME
		,POL_PLAN_ID
		,POL_APP_CMPLT_DT
		,POL_PLAN_NAME
		,POL_APP_FORM_ID
		,SUM_ASSURE
		,PRE_MODE
		,ENTRY_AGT_ID
		,ENTRY_AGT_NAME
		,A.CSC_NAME
		--,CASE WHEN (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) >= 0 THEN (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) 
		,CASE WHEN (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) >= 0 THEN (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) 
		 ELSE 0 
		 END AS ACCT_HIST_AMT
		--,CASE WHEN (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) <  0 THEN (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) 
		,CASE WHEN (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) <  0 THEN (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) 
		 ELSE 0 
		 END AS ACCT_HIST_AMT_A
		,A.ACCT_SUN_ID
		,A.POL_MPREM_AMT
		,POL_ISS_EFF_DT
		,A.ACCT_PRD_CD
		,A.FUND_CD
		,CASE WHEN A.CSC_NAME = 'AG' THEN 'AGENCY' WHEN A.CSC_NAME = 'BA' THEN 'BANCA' ELSE '' END  CSC_CODE
		,POL_COMNT_TXT
		,ISNULL(FC.COLCT_RCPT_NUM,FCC.COLCT_RCPT_NUM) RECPT_ID,A.PLANNAME
		,ISNULL(FC.COLCT_REMARK,FCC.COLCT_REMARK) PAYMENT_TYPE
		, ISNULL(FC.COLLEC_SRCE,FCC.COLLEC_SRCE)  BNK_BR_NM
		,ISNULL(FC.COLCT_ACCT_NUM,FCC.COLCT_ACCT_NUM) PAYE_BNK_ACCT_ID
		,PPC.PCHST_EFF_DT INITIAL_DATE,PPCC.PCHST_EFF_DT LAST_PAY_DT,CASE WHEN DATEDIFF(DAY,A.POL_INFC_DT,PPCC.PCHST_EFF_DT)>=730 THEN '3YP'
		 WHEN DATEDIFF(DAY,A.POL_INFC_DT,PPCC.PCHST_EFF_DT)>=365 THEN '2YP'  WHEN DATEDIFF(DAY,A.POL_INFC_DT,PPCC.PCHST_EFF_DT)<365 AND DATEDIFF(DAY,A.POL_INFC_DT,PPCC.PCHST_EFF_DT)>0 THEN 'RYP' ELSE 'FYP' END STATUS1,CASE WHEN POL_APP_CMPLT_DT<@START_DATE AND POL_STAT='PREMIUM PAYING' THEN 'INFORCE' WHEN POL_STAT='PREMIUM PAYING' THEN 'NEW BUS' ELSE '' END MODE
		,METHOD,TERM,POL_APP_RECV_DT,POL_INFC_DT,ACCT_HIST_PART_NUM,B.ABM_ID,RTRIM(LTRIM(B.ABM_SURNAME))+' '+RTRIM(LTRIM(B.ABM_GIVNAME)) ABM_NAME,B.OVRID_BASE_AGT_ID,RTRIM(LTRIM(L.ENTR_SUR_NM))+' '+RTRIM(LTRIM(L.ENTR_GIV_NM)) LEADER_NAME
	FROM #TZGLE2 A 
	LEFT JOIN #AGENT B ON A.ENTRY_AGT_ID = B.AGT_ID
	LEFT JOIN #AGENT L ON B.OVRID_BASE_AGT_ID = L.AGT_ID
	LEFT JOIN #VE VE ON VE.CO_ID = 'CP' AND VE.POL_ID = A.POL_ID

	--LEFT JOIN #CASH CS ON A.POL_ID=CS.POL_ID
	--LEFT JOIN SGTM_PARA_1 PARA ON CS.PMT_TYP_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='ZCTX-PMT-TYP-CD'
	--LEFT JOIN SGTM_PARA_1 PARA1 ON A.POL_COLCT_MTHD_CD=PARA1.DM_AV_CD AND PARA1.DM_AV_TBL_CD='POL-COLCT-MTHD-CD'   
	LEFT JOIN (SELECT POL_ID,MIN(PCHST_EFF_DT) PCHST_EFF_DT FROM SGTB_POLICY_CHANGE PPC WHERE PPC.PCHST_STAT_CD='A' AND PPC.POL_ACTV_TYP_ID='1082' AND CAST(PCHST_EFF_DT AS DATE)<=@END_DATE GROUP BY POL_ID) PPC ON A.POL_ID=PPC.POL_ID 
	LEFT JOIN (SELECT POL_ID,MAX(PCHST_EFF_DT) PCHST_EFF_DT FROM SGTB_POLICY_CHANGE PPC WHERE PPC.PCHST_STAT_CD='A' AND PPC.POL_ACTV_TYP_ID IN ('1082','1084') AND CAST(PCHST_EFF_DT AS DATE)<=@END_DATE GROUP BY POL_ID) PPCC ON A.POL_ID=PPCC.POL_ID 
	--** CHNAGE RECEIP ID FOR ONLY RELATED ACCT TRXN ID
	--------LEFT JOIN [FCOLLECTION](@END_DATE) FC ON A.ACCT_HIST_PRCES_DT=FC.COLCT_EFF_DT AND A.POL_ID=FC.POL_ID
	--LEFT JOIN [FCOLLECTION](@END_DATE) FC ON A.ACCT_HIST_PRCES_DT=FC.COLCT_CLR_REJ_DT AND A.POL_ID=FC.POL_ID AND A.ACCT_HIST_AMT=COLCT_TOT_AMT   AND FC.COLCT_STAT_CD='3' AND A.ACCT_BASE_ID = '249800'
	--LEFT JOIN [FCOLLECTION](@END_DATE) FCC ON A.ACCT_HIST_PRCES_DT=FCC.COLCT_CLR_REJ_DT AND A.POL_ID=FCC.POL_ID AND A.ACCT_HIST_AMT_A=(FCC.COLCT_TOT_AMT*-1) AND FCC.COLCT_STAT_CD='3'  AND A.ACCT_BASE_ID = '249800'
	--** CHNAGE RECEIP ID FOR ONLY RELATED ACCT TRXN ID
	LEFT JOIN (
		SELECT T2.POL_ID, COL.COLCT_RCPT_NUM, COL.COLCT_REMARK,COL.COLLEC_SRCE, COL.COLCT_ACCT_NUM , T2.ACCT_HIST_PRCES_DT, T2.ACCT_BASE_ID,T2.ACCT_HIST_GEN_ID,T2.ROW# , COL.ROW# S
		FROM (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY ACCT_HIST_GEN_ID) AS ROW#,*  FROM #TZGLE2 WHERE ACCT_BASE_ID = '249800') T2
		LEFT JOIN (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID,COLCT_CLR_REJ_DT ORDER BY LPREV_UPDT_TS) AS ROW#,* FROM[FCOLLECTION](@END_DATE)) COL ON  T2.ACCT_HIST_PRCES_DT=COL.COLCT_CLR_REJ_DT AND T2.POL_ID=COL.POL_ID AND T2.ACCT_HIST_AMT=COL.COLCT_TOT_AMT AND COL.ROW# = T2.ROW#   AND COL.COLCT_STAT_CD='3' 
	) FC ON FC.POL_ID = A.POL_ID AND A.ACCT_HIST_PRCES_DT = FC.ACCT_HIST_PRCES_DT AND A.ACCT_BASE_ID = FC.ACCT_BASE_ID AND A.ACCT_HIST_GEN_ID = FC.ACCT_HIST_GEN_ID
	LEFT JOIN (
		SELECT T2.POL_ID, COL.COLCT_RCPT_NUM, COL.COLCT_REMARK,COL.COLLEC_SRCE, COL.COLCT_ACCT_NUM , T2.ACCT_HIST_PRCES_DT, T2.ACCT_BASE_ID,T2.ACCT_HIST_GEN_ID
		FROM (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY ACCT_HIST_GEN_ID) AS ROW#,*  FROM #TZGLE2 WHERE ACCT_BASE_ID = '249800') T2
		LEFT JOIN (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID,COLCT_CLR_REJ_DT ORDER BY LPREV_UPDT_TS) AS ROW#,* FROM[FCOLLECTION](@END_DATE)) COL ON  T2.ACCT_HIST_PRCES_DT=COL.COLCT_CLR_REJ_DT AND T2.POL_ID=COL.POL_ID AND T2.ACCT_HIST_AMT_A=(COL.COLCT_TOT_AMT*-1) AND COL.ROW# = T2.ROW#   AND COL.COLCT_STAT_CD='3' 
	) FCC ON FCC.POL_ID = A.POL_ID AND A.ACCT_HIST_PRCES_DT = FCC.ACCT_HIST_PRCES_DT AND FCC.ACCT_BASE_ID =  '249800' AND A.ACCT_HIST_GEN_ID = FCC.ACCT_HIST_GEN_ID
	LEFT JOIN SGTB_EDITTABLE D ON B.AGT_DISB_CHNL=D.ETBL_VALU_ID AND D.ETBL_TYP_ID='DCHNL' AND D.ETBL_LANG_CD='E' AND D.CO_ID='CP'
	WHERE (A.ACCT_SUN_ID NOT IN ('2261010', '5511100', '5512100') OR A.ACCT_BASE_ID IN ('361010','361020','3B1020','3B1120','800100','800001'))  
		AND (LEFT(A.ACCT_BASE_ID,2) <> 'FX' OR VE.POL_ID IS NULL)
