

CREATE PROC [dbo].[RPT_CFI_LETTER_LIVE_NEW] 
(
	@POL_ID		VARCHAR(9) = ''
)
AS

DECLARE	@SQL		NVARCHAR(MAX)
		,@SQL1		NVARCHAR(MAX)
		,@SQL2		NVARCHAR(MAX)
		--,@POL_ID		VARCHAR(9) = '700018082 '

	DROP TABLE IF EXISTS #POL_CFI
	DROP TABLE IF EXISTS #CLNM
	DROP TABLE IF EXISTS #CLIA

	CREATE TABLE #POL_CFI
	(
		POL_ID				VARCHAR(10)
		,POL_APP_FORM_ID	VARCHAR(20)
		,POL_CSTAT_CD		VARCHAR(4)
		,POL_STAT_CHNG_DT	DATE
		,POL_TRMN_EFF_DT	DATE
		,POL_MPREM_AMT		DECIMAL(15,2)
		,POL_MEDIC_FEE_AMT	DECIMAL(15,2)
		,CFI_REFUND_AMT		DECIMAL(15,2)
		,PO_ID				VARCHAR(10)
		,PO_SEX_CD			VARCHAR(1)
		,BLI_ID				VARCHAR(10)
		,BLI_SEX_CD			VARCHAR(1)
	)

		CREATE TABLE #CLNM
	(
		CLI_ID				VARCHAR(10)		
		,ENTR_SUR_NM	VARCHAR(25)
		,ENTR_GIV_NM	VARCHAR(25)
		,PREV_UPDT_TS	DATE
		,LAST_UPDT_NM_NO	SMALLINT
	)

	CREATE TABLE #CLIA
	(
		 CLI_ID				VARCHAR(10)
		,CLI_ADDR_LN_1_TXT	VARCHAR(128)
		,CLI_ADDR_LN_2_TXT	VARCHAR(128)
		,CLI_ADDR_LN_3_TXT	VARCHAR(128)
		,CLI_ADDR_CNTY_CD	VARCHAR(6)
		,CLI_ADDR_MUN_CD		VARCHAR(6)
		,CLI_CRNT_LOC_CD		VARCHAR(6)
		,PREV_UPDT_TS	DATE
		,LAST_UPDT_ADD_NO	SMALLINT
	)

		SET @SQL = N'
		SELECT *
		FROM OPENQUERY(UAT7,
		''
			SELECT POL.POL_ID
				,POL.POL_APP_FORM_ID
				,POL.POL_CSTAT_CD
				,POL.POL_STAT_CHNG_DT
				,POTD.TRMN_EFF_DT
				,POL.POL_MPREM_AMT
				,POL.POL_MEDIC_FEE_AMT
				,CASE WHEN ISNULL(ACCT_TRXN_AMT,0) = 0 THEN ACTH.ACCT_HIST_AMT ELSE ACTX.ACCT_TRXN_AMT END AS CFI_REFUND_AMT
				,POLC.CLI_ID AS PO_ID
				,PO.CLI_SEX_CD AS PO_SEX_CD
				,BLI.CLI_ID AS BLI_ID
				,BLI.CLI_SEX_CD AS BLI_SEX_CD
			
			FROM KCAPXUAT.TPOL POL
			-- PO
			LEFT JOIN KCAPXUAT.TPOLC POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = ''''O''''
			LEFT JOIN KCAPXUAT.TPOTD POTD ON POL.POL_ID = POTD.POL_ID
			LEFT JOIN KCAPXUAT.TCLI PO ON POLC.CLI_ID = PO.CLI_ID
			-- BLI
			LEFT JOIN KCAPXUAT.TCVGC CVGC ON POL.POL_ID = CVGC.POL_ID AND CVG_NUM = ''''01''''
			LEFT JOIN KCAPXUAT.TCLI BLI ON CVGC.INSRD_CLI_ID = BLI.CLI_ID
			-- REFUND AMOUNT
			LEFT JOIN KCAPXUAT.TACTX ACTX ON POL.POL_ID = ACTX.POL_ID  AND ACCT_TRXN_AMT > 0 AND ACTX.BUS_FCN_ID = ''''0222''''
			LEFT JOIN KCAPXUAT.TACTH ACTH ON POL.POL_ID = ACTH.POL_ID  AND ACCT_HIST_AMT > 0 AND ACTH.BUS_FCN_ID = ''''0222''''

			WHERE POL.POL_CSTAT_CD = ''''A'''' AND POL.POL_ID = ''''@POL_ID''''
			'')
			';

			SET @SQL = REPLACE(@SQL,'@POL_ID',@POL_ID)
			INSERT INTO #POL_CFI EXEC SP_EXECUTESQL @SQL;

			SET @SQL1 = N'
			SELECT *, LAST_UPDT_NM_NO = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC) 
			FROM  OPENQUERY(UAT7, ''SELECT CLI_ID, ENTR_SUR_NM,ENTR_GIV_NM, PREV_UPDT_TS FROM KCAPXUAT.TCLNM'' ) 
			';

			INSERT INTO #CLNM EXEC SP_EXECUTESQL @SQL1;

			SET @SQL2 = N'
			SELECT *, LAST_UPDT_ADD_NO = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC) 
			FROM  OPENQUERY(UAT7, ''SELECT CLI_ID,CLI_ADDR_LN_1_TXT, CLI_ADDR_LN_2_TXT, CLI_ADDR_LN_3_TXT,CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD,CLI_CRNT_LOC_CD,PREV_UPDT_TS  FROM KCAPXUAT.TCLIA'' ) 
			';

			INSERT INTO #CLIA EXEC SP_EXECUTESQL @SQL2;

		SELECT CFI.POL_ID
		,CFI.POL_APP_FORM_ID
		,CFI.POL_CSTAT_CD 
		,CFI.POL_STAT_CHNG_DT 
		,CFI.POL_TRMN_EFF_DT
		,TRMN_EFF_DAY = DAY(CFI.POL_TRMN_EFF_DT)
		,TRMN_EFF_MONTH = DBO.CONVERT_KH_MONTH(MONTH(CFI.POL_TRMN_EFF_DT))
		,TRMN_EFF_YEAR = YEAR(CFI.POL_TRMN_EFF_DT)		
		,POLH.POL_MPREM_AMT
		,POL_MEDIC_FEE_AMT 
		,CFI_REFUND_AMT
		,CFI.PO_ID 
		,PO_SEX_CD 
		,RTRIM(PONM.ENTR_SUR_NM) AS PO_ENTR_SUR_NM
		,RTRIM(PONM.ENTR_GIV_NM) AS PO_ENTR_GIV_NM
		,PO_ADDRESS = RTRIM(POAD.CLI_ADDR_LN_1_TXT) + 
			CASE WHEN RTRIM(POAD.CLI_ADDR_LN_2_TXT) = '' THEN '' ELSE ', ' + RTRIM(POAD.CLI_ADDR_LN_2_TXT) END + 
			CASE WHEN RTRIM(POAD.CLI_ADDR_LN_3_TXT) = '' THEN '' ELSE ', ' + RTRIM(POAD.CLI_ADDR_LN_3_TXT) END + 
			', ' + RTRIM(POCMU.ETBL_DESC_TXT) + ', ' + RTRIM(PODIS.ETBL_DESC_TXT) + ', ' + RTRIM(POCIT.ETBL_DESC_TXT)
		,BLI_SEX_CD 
		,RTRIM(BLINM.ENTR_SUR_NM) AS BLI_ENTR_SUR_NM 
		,RTRIM(BLINM.ENTR_GIV_NM) AS BLI_ENTR_GIV_NM
	FROM #POL_CFI CFI
	LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE POLH ON CFI.POL_ID = POLH.POL_ID
	LEFT JOIN #CLNM PONM ON PONM.CLI_ID = CFI.PO_ID AND PONM.LAST_UPDT_NM_NO = 1
	LEFT JOIN #CLNM BLINM ON BLINM.CLI_ID = CFI.BLI_ID AND BLINM.LAST_UPDT_NM_NO = 1
	LEFT JOIN #CLIA POAD ON POAD.CLI_ID = CFI.PO_ID AND POAD.LAST_UPDT_ADD_NO = 1
	LEFT JOIN SGTB_EDITTABLE POCMU ON POCMU.ETBL_TYP_ID='CTYPC' AND POAD.CLI_ADDR_CNTY_CD = POCMU.ETBL_VALU_ID AND POCMU.CO_ID = 'CP' AND POCMU.ETBL_LANG_CD = 'E' 
	LEFT JOIN SGTB_EDITTABLE PODIS ON PODIS.ETBL_TYP_ID='MCPCD' AND POAD.CLI_ADDR_MUN_CD = PODIS.ETBL_VALU_ID AND PODIS.CO_ID = 'CP' AND PODIS.ETBL_LANG_CD = 'E' 
	LEFT JOIN SGTB_EDITTABLE POCIT ON POCIT.ETBL_TYP_ID='CLOC' AND  POAD.CLI_CRNT_LOC_CD = POCIT.ETBL_VALU_ID AND POCIT.CO_ID = 'CP' AND POCIT.ETBL_LANG_CD = 'E'
