CREATE PROC [dbo].[RPT_IN_CER] @date date,@POL VARCHAR(100)
AS
	 IF OBJECT_ID('tempdb..#EDIT') IS NOT NULL
  DROP TABLE #EDIT
	 IF OBJECT_ID('tempdb..#CINFOR') IS NOT NULL
  DROP TABLE #CINFOR
	 IF OBJECT_ID('tempdb..#CLIB') IS NOT NULL
  DROP TABLE #CLIB
	 IF OBJECT_ID('tempdb..#CIND') IS NOT NULL
  DROP TABLE #CIND
	 IF OBJECT_ID('tempdb..#CLI') IS NOT NULL
  DROP TABLE #CLI
	 IF OBJECT_ID('tempdb..#POL') IS NOT NULL
  DROP TABLE #POL
	 IF OBJECT_ID('tempdb..#POLW') IS NOT NULL
  DROP TABLE #POLW
	 IF OBJECT_ID('tempdb..#POLC') IS NOT NULL
  DROP TABLE #POLC
    	 IF OBJECT_ID('tempdb..#TCLIA') IS NOT NULL
  DROP TABLE #TCLIA
    	 IF OBJECT_ID('tempdb..#TCLNM') IS NOT NULL
  DROP TABLE #TCLNM
      	 IF OBJECT_ID('tempdb..#CIND') IS NOT NULL
  DROP TABLE #CIND
        	 IF OBJECT_ID('tempdb..#TCVG') IS NOT NULL
  DROP TABLE #TCVG
          	 IF OBJECT_ID('tempdb..#TCLII') IS NOT NULL
  DROP TABLE #TCLII
          IF OBJECT_ID('tempdb..#TCVGC') IS NOT NULL
  DROP TABLE #TCVGC
       IF OBJECT_ID('tempdb..#TREQT') IS NOT NULL
  DROP TABLE #TREQT
         IF OBJECT_ID('tempdb..#BENE') IS NOT NULL
  DROP TABLE #BENE
         IF OBJECT_ID('tempdb..#FINAL') IS NOT NULL
  DROP TABLE #FINAL
         IF OBJECT_ID('tempdb..##EDIT') IS NOT NULL
  DROP TABLE #EDIT
  
select * INTO #EDIT from openquery(PROD,'select * from kcapxpr1.tedit where etbl_typ_id=''PLAN''')
SELECT * INTO #TREQT FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TBENE')  
  SELECT * INTO #TCLNM FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLNM')
  SELECT * INTO #CLI FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLI')
SELECT * INTO #POL FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TPOL')
SELECT * INTO #POLC FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TPOLC')
SELECT * INTO #TCVG FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCVG')
SELECT * INTO #TCVGC FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCVGC')
SELECT * INTO #TCLII FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLII')
SELECT * INTO #TCLIA FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLIA')

SELECT BE.BNFY_NM,BE.CLI_ID BE_CLIID,ED.ETBL_DESC_TXT BNFY_REL_INSRD_CD,BNFY_PRCDS_PCT,C.CLI_BTH_DT BCLI_BTH_DT,C.CLI_ID_NUM BCLI_ID_NUM,POL_ID INTO #BENE FROM #TREQT BE 
INNER JOIN #CLI C ON BE.CLI_ID=C.CLI_ID
LEFT JOIN  SGTB_EDITTABLE ED ON BE.BNFY_REL_INSRD_CD=ED.ETBL_VALU_ID AND ETBL_TYP_ID='BTOI'

  SELECT I.* INTO #CIND FROM #TCLNM I INNER JOIN (SELECT MAX(CLI_INDV_EFF_DT) EFF, CLI_ID FROM #TCLNM GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INDV_EFF_DT=II.EFF

  
  SELECT PC.CLI_ID HCLI_ID,P.POL_ID HPOL_ID,P.POL_APP_CMPLT_DT HPOL_APP_CMPLT_DT,P.POL_ISS_EFF_DT HPOL_ISS_EFF_DT,LEFT(RTRIM(LTRIM(PA.ETBL_DESC_TXT)),LEN(PA.ETBL_DESC_TXT)-8) PO_PLAN,
  CA.CLI_ADDR_LN_1_TXT HCLI_ADDR_LN_1_TXT,CA.CLI_ADDR_LN_2_TXT HCLI_ADDR_LN_2_TXT,CA.CLI_ADDR_LN_3_TXT HCLI_ADDR_LN_3_TXT,CA.CLI_CITY_NM_TXT HCLI_CITY_NM_TXT,PR.PREM_AMT HPOL_MPREM_AMT,
  CASE WHEN P.POL_BILL_MODE_CD=1 THEN 'Monthly' WHEN P.POL_BILL_MODE_CD=3 THEN 'Quarterly' WHEN P.POL_BILL_MODE_CD=6 THEN 'Semi-Annual' WHEN P.POL_BILL_MODE_CD=12 THEN 'Annually' END HPOL_BILL_MODE_CD,
  C.CLI_BTH_DT HCLI_BTH_DT,C.CLI_SEX_CD HCLI_SEX_CD,C.CLI_ID_NUM HCLI_ID_NUM,

  CVG.PLAN_ID,CVG.CVG_NUM,CVGC.INSRD_CLI_ID,CI.ENTR_SUR_NM HENTR_SUR_NM,CI.ENTR_GIV_NM HENTR_GIV_NM,CCA.CLI_ADDR_LN_1_TXT,CCA.CLI_ADDR_LN_2_TXT,CCA.CLI_ADDR_LN_3_TXT,CCA.CLI_CITY_NM_TXT,CC.CLI_ID_NUM,CC.CLI_BTH_DT,CC.CLI_SEX_CD,
  CVG_MPREM_AMT,CVG_MAT_XPRY_DT,CVG_FACE_AMT,LEFT(RTRIM(LTRIM(PPA.ETBL_DESC_TXT)),LEN(PPA.ETBL_DESC_TXT)-8) CVG_PLAN,
  CCI.ENTR_SUR_NM ENTR_SUR_NM,CCI.ENTR_GIV_NM ENTR_GIV_NM,CASE WHEN LEFT(CVG.PLAN_ID,1)='W' THEN 'PO' ELSE 'LI' END PLAN_TYPE
  

  INTO #FINAL FROM #POL P INNER JOIN #POLC PC ON P.POL_ID=PC.POL_ID
  INNER JOIN #CLI C ON C.CLI_ID=PC.CLI_ID AND PC.POL_CLI_REL_SUB_CD='P'
  INNER JOIN #TCVG CVG ON CVG.POL_ID=P.POL_ID AND CVG.CVG_CSTAT_CD='1'
  INNER JOIN #TCVGC CVGC ON CVG.POL_ID=CVGC.POL_ID AND CVG.CVG_NUM=CVGC.CVG_NUM
  INNER JOIN #CLI CC ON CC.CLI_ID=CVGC.INSRD_CLI_ID AND CVGC.CVG_CLI_REL_TYP_CD='P'
  LEFT JOIN #TCLIA CA ON C.CLI_ID=CA.CLI_ID
  LEFT JOIN #CIND CI ON C.CLI_ID=CI.CLI_ID
  LEFT JOIN #CIND CCI ON CVGC.INSRD_CLI_ID=CCI.CLI_ID
  LEFT JOIN #TCLIA CCA ON CVGC.INSRD_CLI_ID=CCA.CLI_ID AND CVGC.CVG_CLI_REL_TYP_CD='P'
  LEFT JOIN #EDIT PA ON P.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' 
  
  LEFT JOIN (select case when pp.pol_bill_mode_cd='01' then sum(CVG_MPREM_AMT*3) else sum(CVG_MPREM_AMT) end PREM_AMT,pp.pol_id from #TCVG cv inner join #POL pp on cv.pol_id=pp.pol_id where left(cv.plan_id,1) in ('A','W') group by pp.pol_id,pol_bill_mode_cd) PR ON P.POL_ID=PR.pol_id
  LEFT JOIN #EDIT PPA ON CVG.PLAN_ID=PPA.ETBL_VALU_ID AND PPA.ETBL_TYP_ID='PLAN'
    WHERE P.POL_ID=@POL OR (P.POL_APP_CMPLT_DT=@date AND (@POL='' OR @POL IS NULL)) and P.POL_CSTAT_CD='1'

  SELECT F.*,BE.BNFY_NM,BE.BCLI_ID_NUM,BE.BNFY_PRCDS_PCT,BE.BNFY_REL_INSRD_CD,ISNULL(R.CRIDER,0) CRIDER,ISNULL(W.CWOP,0) CWOP,CASE WHEN ODER.POORDER IS NOT NULL THEN 'A' WHEN ODERR.POORDER IS NOT NULL THEN 'B' ELSE 'C' END POORDER,CCVG_MPREM_AMT  FROM #FINAL F LEFT JOIN (SELECT  COUNT(PLAN_ID) CRIDER, HPOL_ID  FROM #FINAL WHERE LEFT(PLAN_ID,1)='T' GROUP BY HPOL_ID) R ON F.HPOL_ID=R.HPOL_ID
  LEFT JOIN (SELECT  COUNT(PLAN_ID) CWOP, HPOL_ID  FROM #FINAL WHERE LEFT(PLAN_ID,1)='W' GROUP BY HPOL_ID) W ON F.HPOL_ID=W.HPOL_ID
  LEFT JOIN (select INSRD_CLI_ID,LEFT(PLAN_ID,1) POORDER from #FINAL) ODER ON F.INSRD_CLI_ID=ODER.INSRD_CLI_ID AND ODER.POORDER='W'
  LEFT JOIN (select INSRD_CLI_ID,LEFT(PLAN_ID,1) POORDER from #FINAL) ODERR ON F.INSRD_CLI_ID=ODERR.INSRD_CLI_ID AND ODERR.POORDER='A'
  LEFT JOIN #BENE BE ON F.HPOL_ID=BE.POL_ID
  INNER JOIN (SELECT SUM(CVG_MPREM_AMT) CCVG_MPREM_AMT,HPOL_ID CHPOL_ID FROM #FINAL GROUP BY HPOL_ID) G ON F.HPOL_ID=G.CHPOL_ID
