CREATE PROC [dbo].[RPT_DAILY_GL_COM] @END_DATE DATE
AS
BEGIN

	 IF OBJECT_ID('tempdb..#TZGLE') IS NOT NULL
  DROP TABLE #TZGLE
  	 IF OBJECT_ID('tempdb..#TZGLE1') IS NOT NULL
  DROP TABLE #TZGLE1
  	 IF OBJECT_ID('tempdb..#VE') IS NOT NULL
  DROP TABLE #VE

DECLARE @START_DATE DATE=DATEADD(month, DATEDIFF(month, 0, @END_DATE), 0)

Select  
'02' as RPT_CD
,TACTH.ACCT_CRCY_CD
,TACTH.ACCT_HIST_PRCES_DT as ACCT_HIST_PRCES_DT
,TACTH.ACCT_BASE_ID
,TACTH.ACCT_YR as ACCT_YR
,TACTH.ACCT_SBSDRY_CO_ID
,TACTH.ACCT_PLAN_ID
,TACTH.BR_OR_DEPT_ID
,TACTH.ACCT_ISS_LOC_CD
,TACTH.ACCT_CRNT_LOC_CD
,TACTH.ACCT_ISS_LOC_CD as ACCT_ISS_LOC_CD1
,(case when ISNULL(TACTH.ACCT_DESC_TXT,'')<>'' then ISNULL(TACTH.ACCT_DESC_TXT,'')
 else
	case when ISNULL(TACTD.ACCT_DESC_TXT,'')<>'' then ISNULL(TACTD.ACCT_DESC_TXT,'') 
	else
		case when ISNULL(TACTD1.ACCT_DESC_TXT,'')<>'' then ISNULL(TACTD1.ACCT_DESC_TXT,'') 		
		else 
			case when ISNULL(TACTD2.ACCT_DESC_TXT,'') <>'' then ISNULL(TACTD2.ACCT_DESC_TXT,'') 
			else
				ISNULL(TACTD3.ACCT_DESC_TXT,'') 
			end 
		end 
	End
end
	) as ACCT_DESC_TXT 
,TACTH.CHQ_VCHR_ID
,TACTH.USER_ID
,TACTH.ACCT_HIST_GR_TS as ACCT_HIST_GR_DT
,ACCT_HIST_GR_TS
,TACTH.POL_ID as POL_ID
,RTRIM(LTRIM(I.ENTR_SUR_NM))+' '+RTRIM(LTRIM(I.ENTR_GIV_NM)) POL_NAME
,TACTH.POL_PLAN_ID as POL_PLAN_ID
,PA.ETBL_DESC_TXT POL_PLAN_NAME
,SUM(P.CVG_SUM_INS_AMT) SUM_ASSURE
,w.AGT_ID as ENTRY_AGT_ID
,A.Surname+' '+A.Forename2  ENTRY_AGT_NAME
,TACTH.CHQ_ID
,TACTH.ACCT_HIST_SRC_CD 
,(Case when TACTH.ACCT_HIST_AMT>0 then TACTH.ACCT_HIST_AMT else 0 end) as ACCT_HIST_AMT
,(Case when TACTH.ACCT_HIST_AMT<0 then TACTH.ACCT_HIST_AMT else 0 end) as ACCT_HIST_AMT_A
,TACTH.ACCT_SUB_TYP_CD as ACCT_SUB_TYP_CD
,TACTH.ACCT_HIST_BTCH_NUM
,TACTH.BUS_FCN_ID as BUS_FCN_ID
,TACTH.BPF_ID as BPF_ID
,CASE WHEN TACTH.ACCT_BASE_ID = '102300' AND TACTH.ACCT_DESC_REASN_CD IN ('POL','FPA','COMP') 
THEN TACTH.ACCT_DESC_REASN_CD ELSE TZGLM.ACCT_DESC_REASN_CD END AS ACCT_DESC_REASN_CD
, TACTH.ACCT_DESC_TXT ACCT_DESC_TXT_1
,TACTH.POL_TRM
, 0 COMM_HIST_AMT
, 0 AGT_CPREM_AMT
, ACCT_SUN_ID
, '' ACCT_PRD_CD
, ''  FUND_CD
, ''  AGT_ID
,TACTH.RECPT_ID INTO #TZGLE
From 
SGTB_ACCOUNTING_TRANHIS TACTH
Left join SGTM_GLMAPSUN TZGLM On TACTH.ACCT_BASE_ID=TZGLM.ACCT_BASE_ID AND TZGLM.ACCT_DESC_REASN_CD<>'LPV'
Left join SGTM_ACCOUNTDESC TACTD On TACTH.CO_ID = TACTD.CO_ID AND (TACTH.ACCT_BASE_ID = TACTD.ACCT_DESC_ID) And TACTH.ACCT_DESC_REASN_CD = TACTD.ACCT_DESC_REASN_CD
Left join SGTM_ACCOUNTDESC TACTD1 On TACTH.CO_ID = TACTD1.CO_ID AND(TACTH.ACCT_BASE_ID = TACTD1.ACCT_DESC_ID) And ISNULL(TACTD1.ACCT_DESC_REASN_CD,'')='' And TACTD.ACCT_DESC_REASN_CD is null
Left join SGTM_ACCOUNTDESC TACTD2 On TACTH.CO_ID = TACTD2.CO_ID AND TACTD2.ACCT_DESC_ID=CONCAT(left(TACTH.ACCT_BASE_ID,1),'00000') And TACTH.ACCT_DESC_REASN_CD = TACTD2.ACCT_DESC_REASN_CD And TACTD.ACCT_DESC_REASN_CD is null And TACTD1.ACCT_DESC_REASN_CD is null
Left join SGTM_ACCOUNTDESC TACTD3 On TACTH.CO_ID = TACTD3.CO_ID AND TACTD3.ACCT_DESC_ID=CONCAT(left(TACTH.ACCT_BASE_ID,1),'00000') And ISNULL(TACTD3.ACCT_DESC_REASN_CD,'')='' And TACTD.ACCT_DESC_REASN_CD is null And TACTD1.ACCT_DESC_REASN_CD is null And TACTD2.ACCT_DESC_REASN_CD is null
left join SGTB_POLICY_WRITING W on TACTH.POL_ID=W.POL_ID
inner join SGTB_POLICY_CLIENT C on C.POL_ID=TACTH.POL_ID
inner join DLKHDIM..DIM_CLIENT_IND I on I.CLI_ID=C.CLI_ID AND I.IS_CURRENT=1
INNER JOIN SGTM_COVERAGE P ON P.POL_ID=TACTH.POL_ID
LEFT JOIN SGTB_EDITTABLE PA ON TACTH.POL_PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN'
LEFT JOIN SGTM_AGENT A ON W.AGT_ID=A.PartyId
Where TACTH.CO_ID = 'CP' 
  AND TACTH.ACCT_HIST_PST_DT BETWEEN @START_DATE AND @END_DATE and TACTH.ETL_DATE=@END_DATE
  GROUP BY TACTH.ACCT_CRCY_CD
,TACTH.ACCT_HIST_PRCES_DT 
,TACTH.ACCT_BASE_ID
,TACTH.ACCT_YR 
,TACTH.ACCT_SBSDRY_CO_ID
,TACTH.ACCT_PLAN_ID
,TACTH.BR_OR_DEPT_ID
,TACTH.ACCT_ISS_LOC_CD
,TACTH.ACCT_CRNT_LOC_CD
,TACTH.ACCT_ISS_LOC_CD 
,TACTH.CHQ_VCHR_ID
,TACTH.USER_ID
,TACTH.ACCT_HIST_GR_TS 
,ACCT_HIST_GR_TS
,TACTH.POL_ID 
,I.ENTR_SUR_NM,I.ENTR_GIV_NM
,TACTH.POL_PLAN_ID 
,PA.ETBL_DESC_TXT 
,w.AGT_ID 
,TACTH.CHQ_ID
,TACTH.ACCT_HIST_SRC_CD 
,TACTH.ACCT_SUB_TYP_CD 
,TACTH.ACCT_HIST_BTCH_NUM
,TACTH.BUS_FCN_ID 
,TACTH.BPF_ID 
, TACTH.ACCT_DESC_TXT 
,TACTH.POL_TRM,
TACTD.ACCT_DESC_TXT,
TACTD2.ACCT_DESC_TXT,
TACTD3.ACCT_DESC_TXT,
TACTD1.ACCT_DESC_TXT,
Surname,Forename2,
TACTH.ACCT_HIST_AMT,
TZGLM.ACCT_DESC_REASN_CD,
TACTH.ACCT_DESC_REASN_CD,
TACTD.ACCT_DESC_REASN_CD,
TACTD1.ACCT_DESC_REASN_CD,
TACTD2.ACCT_DESC_REASN_CD,
TACTD3.ACCT_DESC_REASN_CD,
ACCT_SUN_ID,RECPT_ID order by TACTH.ACCT_BASE_ID

  Select 
RPT_CD
,ACCT_CRCY_CD
,ACCT_HIST_PRCES_DT
,ACCT_BASE_ID
,ACCT_YR
,ACCT_SBSDRY_CO_ID
,ACCT_PLAN_ID
,BR_OR_DEPT_ID
,ACCT_ISS_LOC_CD
,ACCT_CRNT_LOC_CD
,ACCT_DESC_TXT
,CHQ_VCHR_ID
,USER_ID
,ACCT_HIST_GR_DT
,POL_ID
,POL_NAME
,POL_PLAN_ID
,POL_PLAN_NAME
,SUM_ASSURE
,ENTRY_AGT_ID
,ENTRY_AGT_NAME
,CHQ_ID
,ACCT_HIST_SRC_CD
,ACCT_HIST_AMT
,ACCT_HIST_AMT_A
,ACCT_SUB_TYP_CD
,ACCT_HIST_BTCH_NUM
,BUS_FCN_ID
,ACCT_DESC_REASN_CD
,ACCT_DESC_TXT_1
,POL_TRM
,COMM_HIST_AMT
,AGT_CPREM_AMT
,ACCT_SUN_ID
,ACCT_PRD_CD
,FUND_CD
,AGT_ID
,RECPT_ID INTO #TZGLE1
FROM #TZGLE
WHERE NOT (ACCT_BASE_ID LIKE '3S10_0'
       AND ACCT_DESC_TXT = 'SFG ACCT - ADD PR')

Select 
CO_ID, POL_ID INTO #VE
FROM DLKHDIM..DIM_POLICY 
WHERE CO_ID = 'CP' 
AND POL_BUS_CLAS_CD = 'L' 
AND POL_PREM_TYP_CD = 'B' and IS_CURRENT=1

SELECT  
@END_DATE AS TRXN_PRCES_DT
,'POL' AS TYPE
,A.ACCT_HIST_PRCES_DT
,A.ACCT_BASE_ID
,A.ACCT_DESC_TXT
,A.USER_ID
,A.ACCT_HIST_GR_DT
,A.POL_ID
,POL_NAME
,POL_PLAN_ID
,POL_PLAN_NAME
,SUM_ASSURE
,ENTRY_AGT_ID
,ENTRY_AGT_NAME
--,CASE WHEN (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) >= 0 Then (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) 
,CASE WHEN (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) >= 0 Then (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) 
 else 0 
 End as ACCT_HIST_AMT
--,CASE WHEN (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) <  0 Then (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) 
,CASE WHEN (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) <  0 Then (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) 
 else 0 
 End as ACCT_HIST_AMT_A
,A.POL_TRM
,A.ACCT_SUN_ID
,A.ACCT_PRD_CD
,A.FUND_CD
,B.CSC_CODE
,A.RECPT_ID
FROM #TZGLE1 A 
LEFT JOIN #VE VE ON VE.CO_ID = 'CP' AND VE.POL_ID = A.POL_ID
LEFT JOIN V_AGENT_INFO B ON A.ENTRY_AGT_ID = B.PARTY_ID
WHERE A.ACCT_SUN_ID  IN ('2261010', '5511100', '5512100')   
	AND (LEFT(A.ACCT_BASE_ID,2) <> 'FX' OR VE.POL_ID IS NULL)

END
