
CREATE PROC [dbo].[RPT_POL_MASTER_DATA_W_RIDER] 
    @START DATE 
    ,@END DATE 
AS
	 --DECLARE @START	DATE = '2021-11-01'
 	--		,@END	DATE = '2021-11-17'

	DROP TABLE IF EXISTS #AGENT
	SELECT * INTO #AGENT FROM DLKHFACT..FACT_AGENT WHERE DATE_KEY = (SELECT MAX(DATE_KEY) FROM DLKHFACT..FACT_AGENT)

	SELECT 
		POL.POL_ID  
		,POL_APP_FORM_ID = RTRIM(POL.POL_APP_FORM_ID) 
		,PO_NAME = RTRIM(LTRIM(CLI_I.ENTR_SUR_NM))+' '+RTRIM(LTRIM(CLI_I.ENTR_GIV_NM))  
		,PO_ID = CLI.CLI_CIN_NUM
		,PO_PHONE_NUM = CLI_C.CLI_CNTCT_ID_TXT 
		,CVG.CVG_NUM
		,PO_BLI = CASE WHEN CVLI.INSRD_CLI_ID = PCLI.CLI_ID 
			THEN 'PO = BLI'
			ELSE 'PO # BLI'
			END
		,CVG.CO_ID
		,CVG.PLAN_ID
		,PLAN_NM = RTRIM(PA.ETBL_DESC_TXT) 
		,FACE_AMT = CVG.CVG_FACE_AMT -- FACE_AMT = SUM(CVG.CVG_FACE_AMT) OVER (PARTITION BY POL.POL_ID)
		,MODAL_PREM = CVG.CVG_MPREM_AMT -- MODAL_PREM = SUM(CVG.CVG_MPREM_AMT) OVER (PARTITION BY POL.POL_ID)
		,AFYP = CVG.CVG_MPREM_AMT
				*(CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT)> 0 
					THEN 12 / CAST(POL.POL_BILL_MODE_CD AS INT) 
					ELSE 1 
					END
				)
		,WFYP = 
			CASE WHEN dbo.FN_GET_POL_DUR(
			POL.POL_ID
			,PC.PCHST_EFF_DT
			,(CASE WHEN PC.POL_ACTV_TYP_ID='1082' THEN 'IFYP' ELSE 'RFYP' END)
			) IN ('RFYP','IFYP')
				THEN (CASE 
					WHEN CVG.CVG_MAT_XPRY_DUR='6' THEN CVG.CVG_MPREM_AMT/2 
					ELSE CVG.CVG_MPREM_AMT 
					END ) 
				ELSE 0 
				END
		,POL_STAT = PARA.DM_AV_DESC_TXT 
		-- ,POL_TERM = TEM.CVG_MAT_XPRY_DUR 
		,POL_TERM = CVG.CVG_MAT_XPRY_DUR

		,'BILL-MODE' = (
			SELECT CASE POL.POL_BILL_MODE_CD
			WHEN 1 THEN 'MONTHLY' 
			WHEN 3 THEN 'QUARTERLY' 
			WHEN 6 THEN 'SEMI ANNUAL' 
			WHEN 12 THEN 'ANNUAL'
			ELSE POL.POL_BILL_MODE_CD 
			END)
		,PC.PCHST_STAT_CD
		,PC.POL_ACTV_TYP_ID
		,RENEWAL_YR = dbo.FN_GET_POL_DUR(POL.POL_ID,PC.PCHST_EFF_DT,(CASE WHEN PC.POL_ACTV_TYP_ID='1082' THEN 'IFYP' ELSE 'RFYP' END))
		,AGT.AGT_ID -- Servicing Code	
		,AGT_NM = RTRIM(LTRIM(AGT.ENTR_SUR_NM))+' '+RTRIM(LTRIM(AGT.ENTR_GIV_NM)) 
		,AGT_DISB_CHNL_DESC = RTRIM(D.ETBL_DESC_TXT)
		,AGT_LDR_ID = AGL.AGT_ID
		,AGT_LDR_NM = RTRIM(LTRIM(AGL.ENTR_SUR_NM))+' '+RTRIM(LTRIM(AGL.ENTR_GIV_NM)) 
		,AGT_MGR_ID = AGM.AGT_ID 
		,AGT_MGR_NM = RTRIM(LTRIM(AGM.ENTR_SUR_NM))+' '+RTRIM(LTRIM(AGM.ENTR_GIV_NM)) 
    
		,RIDER_EFF_DT = CVG.CVG_ISS_EFF_DT
		,POL_APP_RECV_DT --'Submitted Date'
		,POL.POL_APP_CMPLT_DT --'Issued Date'
		,POL.POL_ISS_EFF_DT
	FROM
		-- GET ALL BASE PLAN AND RIDER
		SGTM_COVERAGE CVG
		LEFT JOIN SGTB_POLICY POL ON POL.POL_ID = CVG.POL_ID
		-- DATE RAGE
		LEFT JOIN SGTB_POLICY_CHANGE PC ON POL.POL_ID=PC.POL_ID  
			AND PCHST_STAT_CD='A'
			AND POL_ACTV_TYP_ID IN ('1082','1084')
		-- PLAN NAME
		LEFT JOIN SGTB_EDITTABLE PA ON CVG.PLAN_ID=PA.ETBL_VALU_ID 
			AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' 
			AND PA.CO_ID='CP' 
		-- GET CLIENT
		LEFT JOIN SGTB_COVERAGE_CLI CVLI ON POL.POL_ID = CVLI.POL_ID 
			AND CVLI.CVG_NUM = '01' 
		LEFT JOIN SGTB_POLICY_CLIENT PCLI ON POL.POL_ID = PCLI.POL_ID 
		LEFT JOIN SGTM_CLIENT_CONTACT CLI_C ON CLI_C.CLI_ID = PCLI.CLI_ID
			AND CLI_C.CLI_CNTCT_ID_CD = 'MO'-- MOBILE PHONE 
		LEFT JOIN SGTM_CLIENT_IND CLI_I ON CLI_I.CLI_ID = PCLI.CLI_ID
		LEFT JOIN SGTM_CLIENT CLI ON CLI.CLI_ID = PCLI.CLI_ID
		-- GET POLICY DETAIL
		LEFT JOIN SGTM_PARA_1 PARA ON POL.POL_CSTAT_CD=PARA.DM_AV_CD 
			AND DM_AV_TBL_CD='POL-CSTAT-CD' 
			AND PARA.DM_AV_DESC_LANG_CD='E' -- ENGLISH
			AND PARA.CO_ID='CP'
		LEFT JOIN SGTM_COVERAGE TEM ON TEM.POL_ID=POL.POL_ID 
			AND POL.POL_BASE_CVG_NUM=TEM.CVG_NUM
		-- GET AGENT
		LEFT JOIN SGTB_POLICY_WRITING POL_W ON POL_W.POL_ID = POL.POL_ID
		LEFT JOIN #AGENT AGT ON AGT.AGT_ID = POL_W.AGT_ID AND AGT.AGT_CLI_REL_TYP_CD='M'
		-- GET CHANNEL
		LEFT JOIN SGTB_EDITTABLE D ON AGT.AGT_DISB_CHNL=D.ETBL_VALU_ID 
			AND D.ETBL_TYP_ID='DCHNL' 
			AND D.ETBL_LANG_CD='E' 
			AND D.CO_ID='CP'
		-- GET LEADER
		LEFT JOIN #AGENT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID AND AGL.AGT_CLI_REL_TYP_CD = 'M'
		-- GET MANGER
		LEFT JOIN #AGENT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID AND AGM.AGT_CLI_REL_TYP_CD = 'M'
	WHERE CAST(PC.PREV_UPDT_TS AS DATE) BETWEEN @START AND @END 
		AND (
			SELECT COUNT(*) 
			FROM dbo.FN_GET_CVG_RIDER(CVG.POL_ID)
			) > 0
		-- AND POL.POL_ID = 001000144 
		--AND POL.POL_ID = '001000127'
		--AND POL.POL_ID LIKE '001000072' --'001000262' 
	ORDER BY
		POL.POL_ID
		,PC.PCHST_EFF_DT
		,CVG.CVG_NUM
