CREATE PROC [dbo].[RPT_PNS_POL_ISS_Test] @START DATE,@END DATE
AS
IF OBJECT_ID('tempdb..#TREQT') IS NOT NULL
DROP TABLE #TREQT
IF OBJECT_ID('tempdb..#NON') IS NOT NULL
DROP TABLE #NON
IF OBJECT_ID('tempdb..#DISPATCH') IS NOT NULL
DROP TABLE #DISPATCH
IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
DROP TABLE #TMP
IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
DROP TABLE #TMP1
IF OBJECT_ID('tempdb..#A') IS NOT NULL
DROP TABLE #A
IF OBJECT_ID('tempdb..#W') IS NOT NULL
DROP TABLE #W
IF OBJECT_ID('tempdb..#T') IS NOT NULL
DROP TABLE #T
IF OBJECT_ID('tempdb..#TT') IS NOT NULL
DROP TABLE #TT
IF OBJECT_ID('tempdb..#POL') IS NOT NULL
DROP TABLE #POL
IF OBJECT_ID('tempdb..#TCVGC') IS NOT NULL
DROP TABLE #TCVGC
IF OBJECT_ID('tempdb..#TCVG') IS NOT NULL
DROP TABLE #TCVG
IF OBJECT_ID('tempdb..#POLC') IS NOT NULL
DROP TABLE #POLC
IF OBJECT_ID('tempdb..#POLW') IS NOT NULL
DROP TABLE #POLW
IF OBJECT_ID('tempdb..#EDIT') IS NOT NULL
  DROP TABLE #EDIT
IF OBJECT_ID('tempdb..#TCLNM') IS NOT NULL
  DROP TABLE #TCLNM
IF OBJECT_ID('tempdb..#TCLIA') IS NOT NULL
  DROP TABLE #TCLIA
IF OBJECT_ID('tempdb..#TCLIAA') IS NOT NULL
  DROP TABLE #TCLIAA
IF OBJECT_ID('tempdb..#TCLIC') IS NOT NULL
  DROP TABLE #TCLIC
IF OBJECT_ID('tempdb..#CIND') IS NOT NULL
  DROP TABLE #CIND
IF OBJECT_ID('tempdb..#CLI') IS NOT NULL
  DROP TABLE #CLI
           IF OBJECT_ID('tempdb..#AGENT') IS NOT NULL
  DROP TABLE #AGENT

  select * INTO #AGENT from DLKHFACT..FACT_AGENT where DATE_KEY = (SELECT MAX(DATE_KEY) FROM DLKHFACT..FACT_AGENT)
  SELECT * INTO #CLI FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TCLI')
  SELECT * INTO #TCLIC FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TCLIC')
SELECT * INTO #TCLIA FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TCLIA')
SELECT * INTO #TCLNM FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TCLNM')
 select * INTO #EDIT from openquery(UAT7,'select * from KCAPXPR1.tedit where ETBL_LANG_CD=''E'' and CO_ID=''CP''')
SELECT * INTO #POLW FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TPOLW')
SELECT * INTO #POLC FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TPOLC')
SELECT * INTO #TCVGC FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TCVGC')
SELECT * INTO #TCVG FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TCVG')
SELECT * INTO #POL FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TPOL')
SELECT * INTO #TREQT FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TREQT')

UPDATE T SET REQIR_ID='JET'  FROM #TREQT T INNER JOIN #POLC P ON T.POL_CLI_ID=P.POL_ID INNER JOIN #CLI C ON C.CLI_ID=P.CLI_ID AND POL_CLI_REL_SUB_CD='P' WHERE REQIR_ID='NJET' AND OCCP_ID='OCC0699'

SELECT DISTINCT POL_CLI_ID,CASE WHEN REQIR_ID IN ('U0193','U0194','U0195','U0196','U0197','U0198','U0199','U0200','U0201','U0202','0085','0086','0084','0097','U0207','U0208',
'0084','0085','0086','0087','0088','0089','0090','0091','0092','0093','0094','0095','0095') 
THEN (CASE WHEN CPREQ_STAT_CD IN ('CAN','WVD') THEN 'Non-ME' ELSE 'ME' END)  WHEN REQIR_ID  IN ('0098','U0209') THEN (CASE WHEN CPREQ_STAT_CD IN ('CAN') THEN 'Non-COL' ELSE 'COL' END)  ELSE 'Non-ME' END NONJET_STATUS INTO #NON FROM #TREQT

SELECT I.* INTO #CIND FROM #TCLNM I INNER JOIN (SELECT MAX(CLI_INDV_EFF_DT) EFF, CLI_ID FROM #TCLNM GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INDV_EFF_DT=II.EFF
SELECT I.* INTO #TCLIAA FROM #TCLIA I INNER JOIN (SELECT MAX(CLI_ADDR_EFF_DT) EFF, CLI_ID FROM #TCLIA GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_ADDR_EFF_DT=II.EFF

SELECT distinct PC.CLI_ID,C.POL_ID,POL_APP_FORM_ID,CVG_FACE_AMT,P.POL_MPREM_AMT,CLL.INSRD_CLI_ID,C.PLAN_ID,PA.ETBL_DESC_TXT PLAN_DESC,CASE WHEN POL_CSTAT_CD='A' THEN 'CFI' ELSE PARA.DM_AV_DESC_TXT END POL_STAT,
CASE WHEN POL_BILL_MODE_CD=3 THEN 'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Month' WHEN POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE POL_BILL_MODE_CD END PRE_MODE,RTRIM(LTRIM(VVC.ENTR_SUR_NM))+' '+RTRIM(LTRIM(VVC.ENTR_GIV_NM)) CLIENT_NAME,C1.CLI_CNTCT_ID_TXT PHONE,VC.CLI_ADDR_LN_1_TXT,VC.CLI_ADDR_LN_2_TXT,VC.CLI_ADDR_LN_3_TXT,
VC.CLI_CITY_NM_TXT,POL_ISS_EFF_DT,POL_APP_RECV_DT POL_CREAT_DT,case when POL_INFC_DT=POL_STAT_CHNG_DT or POL_CSTAT_CD='B' or (POL_CSTAT_CD='1' and POL_PREV_CSTAT_CD='B')  then null else POL_INFC_DT end POL_APP_CMPLT_DT,case when POL_CSTAT_CD='B' or (POL_CSTAT_CD='1' and POL_PREV_CSTAT_CD='B') then POL_APP_CMPLT_DT else POL_STAT_CHNG_DT end POL_STAT_CHNG_DT,W.AGT_ID,RTRIM(LTRIM(va.ENTR_SUR_NM))+' '+RTRIM(LTRIM(VA.ENTR_GIV_NM)) AGENT_NAME,RTRIM(LTRIM(VA.ABM_SURNAME))+' '+RTRIM(LTRIM(VA.ABM_GIVNAME)) ABM,
VA.AGENT_CHANNEL CSC_NAME,CASE WHEN RR.POL_CLI_ID IS NULL THEN 'NON-JET CASE' ELSE 'JET CASE' END JETCASE,CASE WHEN NN.NONJET_STATUS IS NOT NULL THEN NN.NONJET_STATUS
WHEN NN2.NONJET_STATUS IS NOT NULL THEN NN2.NONJET_STATUS
WHEN NN3.NONJET_STATUS IS NOT NULL THEN NN3.NONJET_STATUS
ELSE NN1.NONJET_STATUS END NONJET_STATUS,
GETDATE() DISPATCH_DATE,GETDATE() AL_RECEIPT_DATE,GETDATE() DURATION,GETDATE() WELCOME_CALL,GETDATE() CREATE_BY,
CASE WHEN POL_BILL_MODE_CD=3 THEN P.POL_MPREM_AMT*4 WHEN POL_BILL_MODE_CD=6 THEN P.POL_MPREM_AMT*2 WHEN POL_BILL_MODE_CD=1 THEN P.POL_MPREM_AMT*12 WHEN POL_BILL_MODE_CD=12 THEN P.POL_MPREM_AMT
ELSE P.POL_MPREM_AMT END APE,case when POL_CSTAT_CD='B' then POL_STAT_CHNG_DT else null end Lapsed_Date,dbo.ConvertDate(POL_PD_TO_DT_NUM) POL_PD_TO_DT_NUM INTO #TMP FROM #POL P 
INNER JOIN #TCVG C ON C.POL_ID=P.POL_ID
INNER JOIN #TCVGC CLL ON CLL.POL_ID=C.POL_ID AND C.CVG_NUM=CLL.CVG_NUM AND CVG_FACE_AMT>0 
INNER JOIN #POLC PC ON PC.POL_ID=P.POL_ID
INNER JOIN #POLW W ON W.POL_ID=P.POL_ID
INNER JOIN #AGENT VA ON VA.AGT_ID=W.AGT_ID AND VA.AGT_CLI_REL_TYP_CD='M'
INNER JOIN #CIND VVC ON VVC.CLI_ID=CLL.INSRD_CLI_ID

LEFT JOIN #EDIT PA ON P.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E'
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' and PARA.CO_ID='CP' AND PARA.DM_AV_DESC_LANG_CD='E'
LEFT JOIN (SELECT POL_CLI_ID FROM #TREQT WHERE POL_CLI_ID IN (SELECT POL_CLI_ID FROM #TREQT WHERE REQIR_ID IN ('JET')) GROUP BY POL_CLI_ID HAVING COUNT(REQIR_ID)=2) RR ON P.POL_ID=RR.POL_CLI_ID
LEFT JOIN #NON NN ON P.POL_ID=NN.POL_CLI_ID AND NN.NONJET_STATUS='ME'
LEFT JOIN #NON NN1 ON P.POL_ID=NN1.POL_CLI_ID AND NN1.NONJET_STATUS='Non-ME'
LEFT JOIN #NON NN2 ON P.POL_ID=NN2.POL_CLI_ID AND NN2.NONJET_STATUS='COL'
LEFT JOIN #NON NN3 ON P.POL_ID=NN3.POL_CLI_ID AND NN3.NONJET_STATUS='Non-COL'
--LEFT JOIN #DISPATCH D ON P.POL_ID=D.POLICY_ID
LEFT JOIN #TCLIC C1 ON PC.CLI_ID=C1.CLI_ID AND C1.CLI_CNTCT_ID_CD='MO'
LEFT JOIN #TCLIAA VC ON PC.CLI_ID=VC.CLI_ID
WHERE P.POL_APP_RECV_DT between @START and @END 

--WHERE P.POL_APP_CMPLT_DT BETWEEN @START AND @END AND P.POL_CSTAT_CD IN  ('1','B')
--'2','3','5'
UPDATE #TMP SET NONJET_STATUS='COL+ME'  WHERE POL_ID IN (select N.POL_CLI_ID from #NON N INNER JOIN #NON N1 ON N.POL_CLI_ID=N1.POL_CLI_ID AND N.NONJET_STATUS='COL' AND N1.NONJET_STATUS='ME')

SELECT * INTO #TMP1 FROM #TMP WHERE LEFT(PLAN_ID,2) IN ('KB','DW')
  INSERT INTO #TMP1
  SELECT * FROM #TMP TM WHERE  LEFT(TM.PLAN_ID,2)='DR' AND TM.INSRD_CLI_ID NOT IN (SELECT T.INSRD_CLI_ID FROM #TMP1 T WHERE T.POL_ID=TM.POL_ID)

SELECT * INTO #A FROM #TMP1 WHERE LEFT(PLAN_ID,2)='KB'
SELECT * INTO #W FROM #TMP1 WHERE LEFT(PLAN_ID,2)='DW'
SELECT DISTINCT  POL_ID,INSRD_CLI_ID,CLIENT_NAME,PHONE INTO #T FROM #TMP1 WHERE LEFT(PLAN_ID,2)='DR'

SELECT * INTO #TT FROM (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY INSRD_CLI_ID) AS Row#,*  FROM #T) T

SELECT A.*,CASE WHEN W.POL_ID IS NOT NULL THEN W.CLIENT_NAME ELSE A.CLIENT_NAME END PONAME,
CASE WHEN W.POL_ID IS NOT NULL THEN W.INSRD_CLI_ID ELSE A.INSRD_CLI_ID END POCLI,
CASE WHEN W.POL_ID IS NOT NULL THEN W.PHONE ELSE A.PHONE END POPHONE,
CASE WHEN T.POL_ID IS NOT NULL THEN T.CLIENT_NAME ELSE '' END ALNAME1,
CASE WHEN T.POL_ID IS NOT NULL THEN T.INSRD_CLI_ID ELSE '' END ALCLI1,
CASE WHEN T.POL_ID IS NOT NULL THEN T.PHONE ELSE '' END ALPHONE1,
CASE WHEN T1.POL_ID IS NOT NULL THEN T1.CLIENT_NAME ELSE '' END ALNAME2,
CASE WHEN T1.POL_ID IS NOT NULL THEN T1.INSRD_CLI_ID ELSE '' END ALCLI2,
CASE WHEN T1.POL_ID IS NOT NULL THEN T1.PHONE ELSE '' END ALPHONE2 FROM #A A LEFT JOIN #W W ON A.POL_ID=W.POL_ID
LEFT JOIN #TT T ON A.POL_ID=T.POL_ID AND T.Row#=1
LEFT JOIN #TT T1 ON A.POL_ID=T1.POL_ID AND T1.Row#=2 ORDER BY A.POL_ID
