

CREATE PROC [dbo].[RPT_BENE_UAT] @POL VARCHAR(100)
AS

	DROP TABLE IF EXISTS #TBENE
	DROP TABLE IF EXISTS #CLI
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #CIND

	-- GET ONLY REQUIRED INFO OF BENEFICIARY
	SELECT * INTO #TBENE FROM OPENQUERY(UAT7,'SELECT POL_ID,CLI_ID,BNFY_PRCDS_PCT,BNFY_REL_INSRD_CD,BNFY_SEQ_NUM FROM KCAPXUAT.TBENE')
	WHERE POL_ID = @POL

	-- GET ONLY REQUIRED INFO OF CLIENT
	SELECT * INTO #CLI FROM OPENQUERY(UAT7,'SELECT CLI_ID,CLI_BTH_DT,CLI_SEX_CD,CLI_CIN_NUM FROM KCAPXUAT.TCLI')

	-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT
		, #LAST_UPDT = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM
	FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS
		FROM KCAPXUAT.TCLNM
	')

	

	SELECT CONCAT(RTRIM(LTRIM(CLNM.ENTR_SUR_NM)),' ',RTRIM(LTRIM(CLNM.ENTR_GIV_NM))) BNFY_NM
		,BE.CLI_ID BE_CLIID
		,ED.ETBL_DESC_TXT BNFY_REL_INSRD_CD
		,BNFY_PRCDS_PCT
		,C.CLI_BTH_DT
		,C.CLI_SEX_CD
		,CLI_SEX_FULL = CASE WHEN LEFT(C.CLI_SEX_CD,1) = 'M' THEN 'Male' ELSE 'Female' END
		,C.CLI_CIN_NUM CLI_ID_NUM
		,POL_ID 
	FROM #TBENE BE 
	INNER JOIN #CLI C ON BE.CLI_ID = C.CLI_ID
	INNER JOIN #TCLNM CLNM ON BE.CLI_ID = CLNM.CLI_ID AND CLNM.#LAST_UPDT = 1
	LEFT JOIN  SGTB_EDITTABLE ED ON BE.BNFY_REL_INSRD_CD = ED.ETBL_VALU_ID 
		AND ETBL_TYP_ID='BTOI' AND ED.ETBL_LANG_CD = 'E'AND ED.CO_ID = 'CP'
	WHERE POL_ID = @POL 
	ORDER BY BNFY_SEQ_NUM
