
CREATE PROC [DBO].[RPT_BENE] @POL VARCHAR(100)
AS

	DROP TABLE IF EXISTS #TBENE
	DROP TABLE IF EXISTS #CLI
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #CIND

--	DECLARE @POL	VARCHAR(10) = '700001150'

	SELECT * INTO #TBENE FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUT1.TBENE')
	SELECT * INTO #CLI FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUT1.TCLI')
	SELECT * INTO #TCLNM FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUT1.TCLNM')
	SELECT I.* INTO #CIND FROM #TCLNM I INNER JOIN (SELECT MAX(CLI_INDV_EFF_DT) EFF, CLI_ID FROM #TCLNM GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INDV_EFF_DT=II.EFF

	SELECT CONCAT(RTRIM(LTRIM(ENTR_SUR_NM)),' '
		,RTRIM(LTRIM(ENTR_GIV_NM))) BNFY_NM
		,BE.CLI_ID BE_CLIID
		,ED.ETBL_DESC_TXT BNFY_REL_INSRD_CD
		,BNFY_PRCDS_PCT
		,C.CLI_BTH_DT
		,C.CLI_SEX_CD
		,CLI_SEX_FULL = CASE WHEN LEFT(C.CLI_SEX_CD,1) = 'M' THEN 'MALE' ELSE 'FEMALE' END
		,C.CLI_CIN_NUM CLI_ID_NUM
		,POL_ID 
	FROM #TBENE BE 
	INNER JOIN #CLI C ON BE.CLI_ID=C.CLI_ID
	INNER JOIN #CIND D ON BE.CLI_ID=D.CLI_ID
	LEFT JOIN  SGTB_EDITTABLE ED ON BE.BNFY_REL_INSRD_CD=ED.ETBL_VALU_ID 
		AND ETBL_TYP_ID='BTOI' AND ED.ETBL_LANG_CD='E'AND ED.CO_ID='CP'
	WHERE POL_ID=@POL 
	ORDER BY BNFY_SEQ_NUM
