CREATE PROC [dbo].[RPT_COVER_SHEET_UW_SUMM] @PolID VARCHAR(10) AS

--DECLARE @PolID	VARCHAR(20) = '700003121'

SELECT POL_ID, RTRIM(UWG_SUMM_TXT) UWG_SUMM_TXT,UWG_CREAT_USER_ID,UWG_CREAT_DT
, UWG_UPDATE_DT,UWG_USER_1_ID,UWG_DECID_1_DT,UWG_USER_2_ID,UWG_DECID_2_DT,UWG_SUMM_1_TXT, UWG_SUMM_2_TXT
,UWG_SUMM_CSTAT_1_CD,UWG_SUMM_CSTAT_2_CD,UWG_SUMM_CSTAT_1_DESC, UWG_SUMM_CSTAT_2_DESC
FROM OPENQUERY(UAT7, '
SELECT S.POL_ID,S.UWG_SUMM_TXT,S.UWG_CREAT_USER_ID,S.UWG_CREAT_DT,S.UWG_UPDATE_DT,S.UWG_SEQ_NUM, 
P.UWG_USER_1_ID, P.UWG_DECID_1_DT, P.UWG_USER_2_ID, P.UWG_DECID_2_DT, P.UWG_SUMM_CSTAT_1_CD,P.UWG_SUMM_CSTAT_2_CD, 
P.UWG_SUMM_1_TXT, P.UWG_SUMM_2_TXT,
D.DM_AV_MODEL_TXT UWG_SUMM_CSTAT_1_DESC ,D1.DM_AV_MODEL_TXT UWG_SUMM_CSTAT_2_DESC
FROM KCAPXUAT.TZUWS S
LEFT JOIN KCAPXUAT.TZUWP P ON P.POL_ID = S.POL_ID
LEFT JOIN KCAPXUAT.TDMAV D ON D.DM_AV_CD = P.UWG_SUMM_CSTAT_1_CD AND D.DM_AV_TBL_CD = ''UWG-SUMM-CSTAT-CD''
LEFT JOIN KCAPXUAT.TDMAV D1 ON D1.DM_AV_CD = P.UWG_SUMM_CSTAT_2_CD AND D1.DM_AV_TBL_CD = ''UWG-SUMM-CSTAT-CD''
') 
WHERE UWG_SUMM_TXT!= '' AND POL_ID = @PolID ORDER BY UWG_SEQ_NUM

--SELECT * FROM OPENQUERY(UAT7, 'SELECT * FROM KCAPXUAT.TZUWP') WHERE POL_ID = '700005903'
