
/***************************************************************************************************
	REPORT:.......... 
	PURPOSE:......... 
        
    Changelog
    ***********
	VERSION    DATE CHNG    UPDATE_BY    DESC
	VERS0.1		                          Initial Version
	VERS0.2	   24-11-2023   SAVRATH       ADD OVERSEA ADDR
	VERS0.3    04-03-2024	SOUTHEANE	  ADD INITIAL COLLECTION METHOD, RENEWAL COLLECTION METHOD, SUBMISSSION DATE & TIME
	VERS0.4    22-04-2024	SOUTHEANE	  ADD %DISCOUNT INFORMATION 
	VERS0.5    30-04-2024   SOUTHEANE	  ADD FAIL CRITERIA CODE 
    VERS0.6    12-06-2025   SAVRATH	      Change schema of UAT7 from KCAPXUT1 -> KCAPXUAT
    VERS0.7    18-06-2025   SAVRATH	      ADD AML STATUS [DL-1173]
    VERS0.8    25-07-2025   SAVRATH	      ADD STP STATUS [DL-1283]
****************************************************************************************************/

CREATE PROC [dbo].[RPT_POL_MASTER_DATA]
	@START_DATE		DATE = NULL
	,@END_DATE		DATE = NULL
AS

	--DECLARE	@START_DATE		DATE = NULL
			--,@END_DATE		DATE = NULL

	DROP TABLE IF EXISTS	#EDIT
	DROP TABLE IF EXISTS	#AGT
	DROP TABLE IF EXISTS	#PAR
	DROP TABLE IF EXISTS	#TREQT
	DROP TABLE IF EXISTS	#NJET
	DROP TABLE IF EXISTS	#NBREQT
	DROP TABLE IF EXISTS	#DATA
	DROP TABLE IF EXISTS	#XTAB
	DROP TABLE IF EXISTS    #APPTIME --VERS0.3
	DROP TABLE IF EXISTS    #TMP
	DROP TABLE IF EXISTS    #CRI
    DROP TABLE IF EXISTS	#POL -- VERS0.7

	IF ISNULL(@START_DATE,'') = '' SET @START_DATE = '2023-01-01'
	IF ISNULL(@END_DATE,'') = '' SET @END_DATE = CONVERT(DATE,GETDATE())

	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #EDIT FROM SGTB_EDITTABLE WHERE CO_ID = 'CP' AND ETBL_LANG_CD = 'E' 
		AND ETBL_TYP_ID IN ('PLAN','OTOI','BILL-MODE','PAYT','COMTH','OCCCD','MARST','RESD','CLOC','CTYPC','MCPCD'
		, 'BTLOC','CINSD','ACTYP','REJCD','CEASE','LAPST','SURRR','REQTC','CSRC'  , 'RENWMCD','COMTH')

	SELECT DM_AV_CD, DM_AV_TBL_CD, DM_AV_DESC_TXT = RTRIM(DM_AV_DESC_TXT)  INTO #PAR FROM SGTM_PARA_1 WHERE CO_ID = 'CP' AND DM_AV_DESC_LANG_CD = 'E'
		AND  DM_AV_TBL_CD IN ('POL-CSTAT-CD', 'POL-CSTAT-CD')

	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #XTAB FROM SGTM_PARA
	WHERE ETBL_LANG_CD = 'E' AND ETBL_TYP_ID IN ('SOLDBR','CNTRY')

	-- GET ALL REQUIREMENT WITH STATUS ("ORDERED", "REVIEWED AND ACCEPTED")
	SELECT REQT.* INTO #TREQT FROM SGTB_REQT REQT
			WHERE CPREQ_POL_CLI_CD = 'P' AND CPREQ_STAT_CD IN ('ORD','RAC')	

	-- GET ONLY REQUIREMENT WITH STATUS ABOVE BUT EXISTS IN JET/NON-JET CASE
	SELECT DISTINCT REQT.POL_CLI_ID, NJET.GRP_CD, NJET.NON_JET_STAT_CD  INTO #NJET FROM #TREQT REQT
	INNER JOIN V_GET_NON_JET_AND_INCOMPLETE_CODE NJET ON REQT.REQIR_ID = NJET.REQIR_ID 

	-- GET COMBINATION OF NB'S REQUIREMENT DETAIL (REQUIRED + REMARKS) OF EACH POLICY WITH REQUIREMENT STATUS = "ORDERED"
	SELECT POL_CLI_ID
		, REQIR_DETAIL = STUFF
		((
			--SELECT ';'+ RTRIM(REQTC.ETBL_DESC_TXT) + CASE WHEN ISNULL(REQT2.RMRKS,'') = '' THEN '' ELSE ';' + RTRIM(REQT2.RMRKS) END
			  SELECT ';'+ RTRIM(REQTC.ETBL_DESC_TXT) + CASE WHEN ISNULL(REQT2.RMRKS,'') = '' THEN '' ELSE ';  - ' + REPLACE(RTRIM(REQT2.RMRKS),';','; - ') END
			FROM #TREQT REQT2
			INNER JOIN V_GET_NON_JET_AND_INCOMPLETE_CODE NJET ON REQT2.REQIR_ID = NJET.REQIR_ID 
			LEFT JOIN #EDIT REQTC ON REQT2.REQIR_ID = REQTC.ETBL_VALU_ID AND REQTC.ETBL_TYP_ID = 'REQTC' 
			WHERE REQT1.POL_CLI_ID = REQT2.POL_CLI_ID AND REQT2.CPREQ_STAT_CD IN ('ORD')
			ORDER BY REQT2.POL_CLI_ID
			FOR XML PATH('')), 1, 1, ''
		)
	INTO #NBREQT FROM #TREQT REQT1 WHERE REQT1.CPREQ_STAT_CD IN ('ORD') 	GROUP BY REQT1.POL_CLI_ID

	-- GET AGENT INFO
	SELECT * INTO #AGT FROM V_GET_AGENT_BASIC

	--GET DATE TIME APPLICATION RECIEVED FROM LOG 
	select CPEVNT_POL_CLI_ID, CPEVNT_TRXN_DT,CPEVNT_TRXN_TIME,
	FORMAT(CONVERT(bigint,CPEVNT_TRXN_TIME),'##:##:##') AS TMR_TIME INTO #APPTIME  
	from OPENQUERY(UAT7, 'SELECT * from KCAPXUAT.tdalg') WHERE BUS_FCN_ID = '8001'; -- VERS0.6

	--VERS0.5
	-- GET ONLY FAIL CRITERIA CODE - CRI
	SELECT POL_ID, STUFF( (SELECT  ', '+LTRIM(RTRIM(AUTO_UW_REL_CD)) +':'+ LTRIM(RTRIM(AUTO_UW_RULE_CD))
			FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T WHERE T.POL_ID = T1.POL_ID -- VERS0.6
			FOR XML PATH('')),1,1,'') AUTO_UW_RULE_CD
	INTO #CRI
	FROM OPENQUERY(UAT7, 'SELECT POL_ID, AUTO_UW_RULE_CD,AUTO_UW_REL_CD FROM KCAPXUAT.TZAUF') T1 -- VERS0.6
	GROUP BY POL_ID

    -- VERS0.7
    SELECT * INTO #POL FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TPOL')

	SELECT --DISTINCT 
		RPT_TITLE = 'POLICY MASTER DATA'
		,POL.POL_ID
		,POL_APP_FORM_ID = RTRIM(POL.POL_APP_FORM_ID)
		,REMOTE_CASE = CASE WHEN ISNULL(REMC.SUBMITED_TYPE,'') != '' THEN REMC.SUBMITED_TYPE 
			ELSE 
				CASE WHEN LEFT(POL.POL_APP_FORM_ID,2) IN ('AR', 'BR') THEN 'Remote Case' ELSE NULL END
			END
		,POL.POL_APP_RECV_DT
		,POL.POL_APP_SIGN_DT
		,POL.POL_APP_CMPLT_DT
		,DISP.DISPATCHED_DATE
		,DISP.WELCOME_DATE
		,DISP.ACKNOWLEDGEMENT_DATE
		,POL.POL_ISS_EFF_DT
		,POL.POL_INFC_DT
		,POL.POL_REISS_DT
		,POL_PAID_TO_DATE = CONVERT(DATE,POL.POL_PD_TO_DT_NUM)
		,POL.POL_CEAS_DT
		,POL.POL_CSTAT_CD
		,POL_STATUS_DESC = (PSC.DM_AV_DESC_TXT)
		,POL_TERM = (CVG.CVG_MAT_XPRY_DUR)
		,PREM_TERM = CASE WHEN CVG.PREM_PMT_DUR = 0 THEN CVG.CVG_MAT_XPRY_DUR ELSE CVG.PREM_PMT_DUR END	-- USER CALL "PREMIUM TERM"
		,POL.POL_STAT_CHNG_DT
		,POL.POL_REJ_EFF_DT
		,POL.POL_REJ_REASN_CD
		,POL_REJ_REASN_DESC = REJCD.ETBL_DESC_TXT
		,POL.POL_CEAS_REASN_CD
		,POL_CEAS_REASN_DESC = CEASE.ETBL_DESC_TXT
		,POL.POL_BILL_MODE_CD
		,POL_BILL_MODE_DESC = (BLM.ETBL_DESC_TXT)
		,POL.POL_BILL_TYP_CD
		,POL_BILL_TYPE_DESC = (PAYT.ETBL_DESC_TXT)
		,POL.COLCT_MTHD_CD
		,POL_COLCT_MTHD_DESC = (COMTH.ETBL_DESC_TXT)
		,POL.POL_CRNT_MODE_FCT
		,POL_MPREM_AMT = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
		,APE = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END * 
			(CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL.POL_BILL_MODE_CD AS INT) END)	-- APE/AFYP
		,POL.POL_GRS_APREM_AMT
		,POL.POL_PREM_SUSP_AMT
		,POL.POL_PREM_SUSP_DT
		,POL.POL_MISC_SUSP_AMT
		,POL.POL_MISC_SUSP_DT
		,POL.POL_OS_DISB_AMT
		,POL.POL_OS_DISB_DT
		,POL.LOAN_CNTRCT_NUM
		,POL.CUST_SRC_CD
		,CUST_SRC_DESC = CSRC.ETBL_DESC_TXT
		,POLW.POL_SOLD_BR_ID
		,POL_SOLD_BR_NAME = SLDBR.ETBL_DESC_TXT
		,POL_NOT = RTRIM(POL.POL_NOT)
		,POL_COMNT_TXT = RTRIM(POL.POL_COMNT_TXT)
		,POL.POL_MEDIC_FEE_AMT
		,CFI_REASON = RTRIM(REJR.ETBL_DESC_TXT)
		,JET_CASE = CASE WHEN ISNULL(TCOL.NON_JET_STAT_CD,'') = '' AND ISNULL(TME.NON_JET_STAT_CD, '') = ''
			AND ISNULL(TIA.NON_JET_STAT_CD,'') = '' AND ISNULL(TOTR.NON_JET_STAT_CD,'') = '' THEN 'JET CASE' ELSE 'NON-JET CASE' END
		,COL = TCOL.NON_JET_STAT_CD
		,ME = TME.NON_JET_STAT_CD
		,IA = TIA.NON_JET_STAT_CD
		,OTR = TOTR.NON_JET_STAT_CD
		,NBREQT.REQIR_DETAIL
		,CVG.PLAN_ID
		,CVG_PLAN_DESC = (PLN.ETBL_DESC_TXT)
		,CVGC.CVG_NUM
		,CVG.CVG_CSTAT_CD
		,CVG_STATUS_DESC = CASE WHEN CVG.CVG_CSTAT_CD = 'B' AND CVG.CVG_LAP_TYP_IND = 'Y' THEN 'DROPPED' ELSE  (CVGS.DM_AV_DESC_TXT) END
		,CVG_LAPSE_TYP_CD = ''		-- CVG.CVG_XHBT_TRMN_QTY
		,CVG_LAPSE_TYP_DESC = ''	-- LAPST.ETBL_DESC_TXT
		,CVG.CVG_ISS_EFF_DT
		,CVG.CVG_STAT_EFF_DT
		,CVG.CVG_STAT_PRCES_DT
		,CVG.CVG_FACE_AMT
		,CVG.CVG_MPREM_AMT
		,CVG.CVG_BASIC_PREM_AMT
		,CVG.CVG_UWG_AMT			-- Underwriting Amount
		,CVG.CVG_TOT_SAR			-- Total Sum at Risk
		,POLC.POL_CLI_INSRD_CD		-- Owner Relationship Code
		,OWNER_REL_DESC = PORL.ETBL_DESC_TXT	-- Owner Relationship
		,PO_ID
		,POL_OWNER = CASE WHEN CVGC.PO_ID = CVGC.INSRD_CLI_ID THEN 'OWNER' ELSE '' END
		,PO_CLI_CIN_NUM = PO.CLI_CIN_NUM
		,PO_SEX_CD = PO.CLI_SEX_CD
		,PO_BTH_DT = PO.CLI_BTH_DT
		,PO_SUR_NM = RTRIM(POA.ENTR_SUR_NM)
		,PO_GIV_NM = RTRIM(POA.ENTR_GIV_NM)
		,INSRD_CLI_ID = CASE WHEN CVGC.CVG_NUM = '00' THEN '' ELSE CVGC.INSRD_CLI_ID END
		,CLI_ROLE = CASE WHEN CVGC.PO_ID = CVGC.INSRD_CLI_ID THEN 'PO' ELSE CVGC.INSRD_ROLE END
		,ENTR_SUR_NM = RTRIM(CIND.ENTR_SUR_NM)
		,ENTR_GIV_NM = RTRIM(CIND.ENTR_GIV_NM)
		,CVG.CVG_RT_AGE
		,CVG.ANN_MTG_INT_PCT		-- Annual Mortgage Interest Rate
		,CVG_PREM_DISC_1_FCT = 0	-- Manual Discount	(CVG.CVG_PREM_DISC_1_FCT)
		,CVG_PREM_DISC_2_FCT = 0	-- Auto Discount	(CVG.CVG_PREM_DISC_2_FCT)
		,CLI.CLI_BTH_DT
		,CLI.CLI_SEX_CD
		,CLI.CLI_SMKR_CD
		,CLI.CLI_CIN_NUM
		,CLI.OCCP_ID
		,CLI_OCCP_DESC = (OCC.ETBL_DESC_TXT)
		,CLI_OCCP_CLAS_CD = RTRIM(CLI.CLI_OCCP_CLAS_CD)
		,CLIA.CLI_RES_TYP_CD
		,CLI_RES_DESC = (RESD.ETBL_DESC_TXT)
		,CLIA.CLI_RES_NUM
		,CLI.CLI_MARIT_STAT_CD
		,CLI_MARIT_STAT_DESC = (MARST.ETBL_DESC_TXT)
		,CLI.CLI_SUPPRT_DOC_ID
		,CLI_SUPPRT_DOC_DESC = CINSD.ETBL_DESC_TXT
		,CINF.EARN_INCM_MODE_CD
		,CLI_EARN_INCM_AMT = CASE WHEN ISNULL(CINF.EARN_INCM_MODE_CD,'') = 'M' THEN 12 ELSE 1 END * CINF.CLI_EARN_INCM_AMT
		,CLI.CLI_BTH_LOC_CD								--	BIRTH LOCATION CODE
		,CLI_BTH_LOC_DESC = BTLOC.ETBL_DESC_TXT			--	BIRTH LOCATION
		,CLI.CLI_CTZN_CTRY_CD							--	Country Of Citizenship Code
		,CLI_CTZN_CTRY_DESC = CTZN.ETBL_DESC_TXT		--	Country Of Citizenship
		,CLI_ADDR_LN_1_TXT = RTRIM(CLIA.CLI_ADDR_LN_1_TXT)
		,CLI_ADDR_LN_2_TXT = RTRIM(CLIA.CLI_ADDR_LN_2_TXT)
		,CLI_ADDR_LN_3_TXT = RTRIM(CLIA.CLI_ADDR_LN_3_TXT)
		,CLIA.CLI_CTRY_CD			-- Country
		,CLI_CTRY_DESC = CTRY.ETBL_DESC_TXT
		,CLIA.CLI_CITY_NM_TXT
		,CLI_CITY = (CIT.ETBL_DESC_TXT)
		,CLI_DISTRICT = (DIST.ETBL_DESC_TXT)
		,CLI_COMMUNE = (COMU.ETBL_DESC_TXT)
		,CLI_OVERS_ADDR_LN = RTRIM(CLIAO.CLI_ADDR_LN_1_TXT)+ ' '+ RTRIM(CLIAO.CLI_ADDR_LN_2_TXT) --VERS0.2
		,CLI_OVERS_CTRY_TXT = RTRIM(OCNTRY.ETBL_DESC_TXT) --VERS0.2
		,CLIA.CLI_ADDR_STAT_CD
		,CLI_ADDR_STAT_DESC = (CASE ISNULL(CLIA.CLI_ADDR_STAT_CD,'') WHEN 'C' THEN 'COMPLETE' WHEN 'I' THEN 'INCOMPLETE' ELSE '' END)
		,EM = (CONT.EM)
		,BU = (CONT.BU)
		,MO = (CONT.MO)
		,HO = (CONT.HO)
		,CLI.CLI_US_TAX_FILE_IND	--	US Tax Declared
		,CLI_FATCA_INDCIA = RTRIM(CLI.CLI_FATCA_INDCIA)	-- Declaration Form
		,CLI.CLI_US_TAX_ID			--
		,BNK_NM=RTRIM(BNK.BNK_NM)
		,CLIB.BNK_ID
		,BNK_ACCT_ID=RTRIM(CLIB.BNK_ACCT_ID)
		,BNK_ACCT_HLDR_NM = RTRIM(BNKA.BNK_ACCT_HLDR_NM)
		,BNKA.BNK_ACCT_TYP_CD
		,BNK_ACCT_TYP_DESC = ACTYP.ETBL_DESC_TXT
		,POL.SERV_AGT_ID
		,AG.AGT_STAT_CD
		,AG.AGT_TYP_CD
		,AG.BR_ID
		,AG.AGT_BR_DESC
		,AG.AGT_DISB_CHNL
		,AGT_DISB_CHNL_DESC = RTRIM(AG.AGT_DISB_CHNL_DESC)
		,AG.OVRID_BASE_AGT_ID
		,AG.OVRID_ID
		,POLW.AGT_ID
		,AGT_ENTR_SUR_NM = (AG.ENTR_SUR_NM)
		,AGT_ENTR_GIV_NM = (AG.ENTR_GIV_NM)
		,AGT_PHON_NUM = (AG.AGT_PHON_NUM)
		,AGT_EMIAL = AG.AGT_EMAIL
		,AG.AGT_ADDR_LN_1_TXT
		,AG.AGT_CNTRCT_STRT_DT
		,AGT_LDR_ID = AGL.AGT_ID
		,AGT_LDR_SUR_NM = (AGL.ENTR_SUR_NM)
		,AGT_LDR_GIV_NM = AGL.ENTR_GIV_NM
		,AGT_LDR_PHON_NUM = AGL.AGT_PHON_NUM
		,AGT_LDR_EMAIL = AGL.AGT_EMAIL
		,AGT_MGR_ID = AGM.AGT_ID
		,AGT_MGR_SUR_NM = AGM.ENTR_SUR_NM
		,AGT_MGR_GIV_NM = AGM.ENTR_GIV_NM
		,AGT_MGR_PHON_NUM = AGM.AGT_PHON_NUM
		,AGT_MGR_EMAIL = AGM.AGT_EMAIL
		,BENE.BEN1_CLI_ID
		,BENE.BEN1_CLI_NM
		,BENE.BEN1_PCT
		,BENE.BEN2_CLI_ID
		,BENE.BEN2_CLI_NM
		,BENE.BEN2_PCT
		,BENE.BEN3_CLI_ID 
		,BENE.BEN3_CLI_NM
		,BENE.BEN3_PCT
		,BENE.BEN4_PCT
		,BENE.BEN4_CLI_ID
		,BENE.BEN4_CLI_NM
		,POL.APP_SUBMIT_CD
		,INITIAL_COLM =  COLM.ETBL_DESC_TXT --VERS 0.3
		,RENEWAL_COLM = RCOLM.ETBL_DESC_TXT --VERS 0.3
		,SUBMISSION_DATE = CAST(FORMAT(POL.POL_APP_RECV_DT,'dd-MM-yyyy') AS varchar) + ' ' + APPTIME.TMR_TIME --VERS 0.3
		--ADDING COVERAGE % DISCOUNT INFORMATION DL-236
		----VERSION 0.4
		,ORIGINAL_PRM =  CASE WHEN CVG.CVG_UNDSCNT_PREM  = 0 THEN 
						(CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END) ELSE CVG.CVG_UNDSCNT_PREM  END
		,AUTO_DIS = CVG.CVG_PREM_DISC_2_FCT
		,MAN_DIS = CVG.CVG_PREM_DISC_1_FCT
		,CASE_STT = CASE WHEN POL.POL_CASE_STAT_CD ='M' THEN 'Manual' WHEN POL.POL_CASE_STAT_CD ='A' THEN 'Auto' ELSE '' END
		,CASE_STT_RMKS = POLC.POL_UW_RMRKS
		,CRI.AUTO_UW_RULE_CD
        ,POL1.AML_STAT_CD AML_CODE -- VERS0.7
        ,RTRIM(STP.ETBL_DESC_TXT) STP_CODE -- VERS0.8
	INTO #TMP
	FROM SGTB_POLICY POL
	LEFT JOIN V_INCLUDE_PAYOR_IN_COVERAGE_CLI CVGC ON POL.POL_ID = CVGC.POL_ID 
	LEFT JOIN SGTM_COVERAGE CVG ON CVGC.POL_ID = CVG.POL_ID AND (CASE WHEN CVGC.CVG_NUM = '00' THEN '' ELSE CVGC.CVG_NUM END) = CVG.CVG_NUM
	LEFT JOIN SGTB_POLICY_CLIENT POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = 'O'
	LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE POL0 ON POL.POL_ID = POL0.POL_ID
	-- NJET AND NB REQUIREMENT
	LEFT JOIN #NJET TCOL ON CVGC.POL_ID = TCOL.POL_CLI_ID AND TCOL.GRP_CD = 'COL'
	LEFT JOIN #NJET TME ON CVGC.POL_ID = TME.POL_CLI_ID AND TME.GRP_CD = 'ME'
	LEFT JOIN #NJET TIA ON POL.POL_ID = TIA.POL_CLI_ID AND TIA.GRP_CD = 'IA'
	LEFT JOIN #NJET TOTR ON POL.POL_ID = TOTR.POL_CLI_ID AND TOTR.GRP_CD = 'OTR'
	LEFT JOIN #NBREQT NBREQT ON POL.POL_ID = NBREQT.POL_CLI_ID
	-- PO
	LEFT JOIN SGTM_CLIENT PO ON POLC.CLI_ID = PO.CLI_ID
	LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) POA ON PO.CLI_ID = POA.CLI_ID AND POA.#NO = 1 

	-- INSURED CLIENT
	LEFT JOIN SGTM_CLIENT CLI ON (CASE WHEN CVGC.CVG_NUM = '00' THEN POLC.CLI_ID ELSE  CVGC.INSRD_CLI_ID END) = CLI.CLI_ID
	LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) CIND ON CVGC.INSRD_CLI_ID = CIND.CLI_ID AND CIND.#NO = 1
	LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_ADD WHERE LEN(CLI_ID) >= 10 AND CLI_ADDR_TYP_CD = 'PR') CLIA ON CVGC.INSRD_CLI_ID = CLIA.CLI_ID AND CLIA.#NO = 1
	LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_ADD WHERE LEN(CLI_ID) >= 10 AND CLI_ADDR_TYP_CD = 'O') CLIAO ON CVGC.INSRD_CLI_ID = CLIAO.CLI_ID AND CLIAO.#NO = 1 --VERS0.2
	LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_INFO WHERE LEN(CLI_ID) >= 10) CINF ON CVGC.INSRD_CLI_ID = CINF.CLI_ID AND CINF.#NO = 1
	LEFT JOIN V_PIVOT_CLIENT_CONTACT CONT ON CVGC.INSRD_CLI_ID = CONT.CLI_ID
	LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIB WHERE LEN(CLI_ID) >= 10) CLIB ON CVGC.INSRD_CLI_ID = CLIB.CLI_ID AND CLIB.#NO = 1

	LEFT JOIN (SELECT LAST_UPDT_BNK_ACC = ROW_NUMBER() OVER (ORDER BY PREV_UPDT_TS DESC),* FROM SGTM_BANK_ACC) BNKA ON CLIB.BNK_ACCT_ID = BNKA.BNK_ACCT_ID AND BNKA.LAST_UPDT_BNK_ACC = 1
	LEFT JOIN SGTB_POLICY_WRITING POLW ON POL.POL_ID = POLW.POL_ID
	LEFT JOIN SGTM_BANK BNK ON BNK.BNK_ID = CLIB.BNK_ID
	-- AGENT
	LEFT JOIN #AGT AG ON POLW.AGT_ID = AG.AGT_ID
	LEFT JOIN #AGT AGL ON CASE WHEN AG.AGT_DISB_CHNL IN ('3','4') AND AG.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AG.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID

	---- BENE
	LEFT JOIN V_BENE_PIVOT BENE ON POL.POL_ID = BENE.POL_ID
	---- DISPATCHED
	LEFT JOIN V_POL_DISPATCH DISP ON POL.POL_ID = DISP.POL_ID

	LEFT JOIN #PAR PSC ON POL.POL_CSTAT_CD = PSC.DM_AV_CD AND PSC.DM_AV_TBL_CD = 'POL-CSTAT-CD'
	LEFT JOIN #PAR CVGS ON CVG.CVG_CSTAT_CD = CVGS.DM_AV_CD AND CVGS.DM_AV_TBL_CD = 'POL-CSTAT-CD'
	LEFT JOIN #EDIT PLN ON (CASE WHEN CVGC.CVG_NUM = '00' THEN '' ELSE CVG.PLAN_ID END) = PLN.ETBL_VALU_ID AND PLN.ETBL_TYP_ID = 'PLAN'
	LEFT JOIN #EDIT BLM ON POL.POL_BILL_MODE_CD = BLM.ETBL_VALU_ID AND BLM.ETBL_TYP_ID = 'BILL-MODE'
	LEFT JOIN #EDIT PAYT ON POL.POL_BILL_TYP_CD = PAYT.ETBL_VALU_ID AND PAYT.ETBL_TYP_ID = 'PAYT'
	LEFT JOIN #EDIT COMTH ON POL.COLCT_MTHD_CD = COMTH.ETBL_VALU_ID AND COMTH.ETBL_TYP_ID = 'COMTH'
	LEFT JOIN #EDIT OCC ON CLI.OCCP_ID = OCC.ETBL_VALU_ID AND OCC.ETBL_TYP_ID='OCCCD'  
	LEFT JOIN #EDIT MARST ON CLI.CLI_MARIT_STAT_CD = MARST.ETBL_VALU_ID AND MARST.ETBL_TYP_ID = 'MARST'
	LEFT JOIN #EDIT RESD ON CLIA.CLI_RES_TYP_CD = RESD.ETBL_VALU_ID AND RESD.ETBL_TYP_ID = 'RESD'
	LEFT JOIN #EDIT BTLOC ON CLI.CLI_BTH_LOC_CD = BTLOC.ETBL_VALU_ID AND BTLOC.ETBL_TYP_ID = 'BTLOC'
	LEFT JOIN #EDIT CTRY ON CLIA.CLI_CTRY_CD = CTRY.ETBL_VALU_ID AND CTRY.ETBL_TYP_ID = 'BTLOC'
	LEFT JOIN #EDIT CIT ON  CLIA.CLI_CRNT_LOC_CD = CIT.ETBL_VALU_ID AND CIT.ETBL_TYP_ID='CLOC'
	LEFT JOIN #EDIT COMU ON CLIA.CLI_ADDR_CNTY_CD = COMU.ETBL_VALU_ID AND COMU.ETBL_TYP_ID = 'CTYPC'
	LEFT JOIN #EDIT DIST ON CLIA.CLI_ADDR_MUN_CD= DIST.ETBL_VALU_ID AND DIST.ETBL_TYP_ID='MCPCD'
	LEFT JOIN #EDIT PORL ON POLC.POL_CLI_INSRD_CD = PORL.ETBL_VALU_ID AND PORL.ETBL_TYP_ID = 'OTOI'
	LEFT JOIN #EDIT CINSD ON CLI.CLI_SUPPRT_DOC_ID = CINSD.ETBL_VALU_ID AND CINSD.ETBL_TYP_ID = 'CINSD'
	LEFT JOIN #EDIT CTZN ON CLI.CLI_CTZN_CTRY_CD = CTZN.ETBL_VALU_ID AND CTZN.ETBL_TYP_ID = 'BTLOC'
	LEFT JOIN #EDIT ACTYP ON BNKA.BNK_ACCT_TYP_CD = ACTYP.ETBL_VALU_ID AND ACTYP.ETBL_TYP_ID = 'ACTYP'
	LEFT JOIN #EDIT REJCD ON POL.POL_REJ_REASN_CD = REJCD.ETBL_VALU_ID AND REJCD.ETBL_TYP_ID = 'REJCD'
	LEFT JOIN #EDIT CEASE ON POL.POL_CEAS_REASN_CD = CEASE.ETBL_VALU_ID AND CEASE.ETBL_TYP_ID = 'CEASE'
	LEFT JOIN #EDIT REJR ON POL.REJ_REMKS_CD = REJR.ETBL_VALU_ID AND REJR.ETBL_TYP_ID = 'REJRMK'
	LEFT JOIN V_GET_REMOTE_CASE_OF_EXIST_POLICY REMC ON POL.POL_ID = REMC.POL_ID
	LEFT JOIN #EDIT CSRC ON POL.CUST_SRC_CD = CSRC.ETBL_VALU_ID AND CSRC.ETBL_TYP_ID = 'CSRC'
	LEFT JOIN #XTAB SLDBR ON POLW.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_TYP_ID = 'SOLDBR'
	LEFT JOIN #XTAB OCNTRY ON OCNTRY.ETBL_VALU_ID = CLIAO.CLI_CTRY_CD AND OCNTRY.ETBL_TYP_ID = 'CNTRY' --VERS0.2
	LEFT JOIN #EDIT COLM ON POL.COLCT_MTHD_CD = COLM.ETBL_VALU_ID AND COLM.ETBL_TYP_ID = 'COMTH' --VERS 0.3
	LEFT JOIN #EDIT RCOLM ON POL.POL_RENW_MTHD_CD = RCOLM.ETBL_VALU_ID AND RCOLM.ETBL_TYP_ID = 'RENWMCD' -- VERS 0.3
	LEFT JOIN #APPTIME APPTIME ON APPTIME.CPEVNT_POL_CLI_ID = POL.POL_ID AND APPTIME.CPEVNT_TRXN_DT = POL.POL_APP_RECV_DT
	--GET FAIL CRITERIA---
	LEFT JOIN #CRI CRI ON POL.POL_ID = CRI.POL_ID --VERS0.2
    LEFT JOIN #POL POL1 ON POL1.POL_ID = POL.POL_ID -- VERS0.7
    LEFT JOIN SGTB_EDITTABLE STP ON STP.ETBL_VALU_ID = POL.POL_STP_CD AND STP.ETBL_TYP_ID = 'STPCD' -- VERS0.8
	WHERE POL.POL_APP_RECV_DT BETWEEN @START_DATE AND @END_DATE

	
	--DROP TABLE IF EXISTS	#EDIT
	--DROP TABLE IF EXISTS	#AGT
	--DROP TABLE IF EXISTS	#PAR
	--DROP TABLE IF EXISTS	#TREQT
	--DROP TABLE IF EXISTS	#NJET
	--DROP TABLE IF EXISTS	#NBREQT
	--DROP TABLE IF EXISTS	#DATA
	--DROP TABLE IF EXISTS	#XTAB

	SELECT MTMP.*
		,TOTAL_DIS_AMT = CASE WHEN (MTMP.ORIGINAL_PRM - MTMP.POL_MPREM_AMT) < 0 THEN 0 ELSE (MTMP.ORIGINAL_PRM - MTMP.POL_MPREM_AMT) END
		--,MP_BE_DIS = CASE WHEN (MTMP.POL_MPREM_AMT + ( MTMP.ORIGINAL_PRM - MTMP.POL_MPREM_AMT)) <= 0 THEN MTMP.POL_MPREM_AMT ELSE (MTMP.POL_MPREM_AMT + ( MTMP.ORIGINAL_PRM - MTMP.POL_MPREM_AMT)) END 
	FROM #TMP MTMP
