CREATE PROC [dbo].[RPT_APP_CASH] @FROM DATE,@END DATE
AS
BEGIN
 IF OBJECT_ID('tempdb..#APP') IS NOT NULL
  DROP TABLE #APP
 IF OBJECT_ID('tempdb..#REV') IS NOT NULL
  DROP TABLE #REV
SELECT GETDATE() REPORT_DATE,TACTH.POL_ID,TPOL.POL_APP_FORM_ID,TPOL.POL_MPREM_AMT,TPOL.POL_CREAT_DT,TPOL.POL_INFC_DT,TACTH.ACCT_HIST_PRCES_DT,TACTH.ACCT_HIST_AMT,TACTH.RECPT_ID,
(TDMAV.DM_AV_DESC_TXT) AS FREQUENCY,TACTH.ACCT_HIST_PST_DT INTO #APP FROM DLKHDIM..DIM_POLICY TPOL
INNER JOIN  SGTB_ACCOUNTING_TRANHIS TACTH ON TACTH.CO_ID=TPOL.CO_ID
AND TACTH.POL_ID=TPOL.POL_ID  
AND TACTH.ACCT_BASE_ID='102300'
AND TACTH.ACCT_HIST_PRCES_DT BETWEEN @FROM AND @END
AND TACTH.ACCT_HIST_AMT>0
AND TPOL.IS_CURRENT=1
LEFT JOIN   SGTM_PARA_1 AS  TDMAV
ON TDMAV.DM_AV_TBL_CD = 'POL-BILL-MODE-CD' AND TDMAV.DM_AV_CD = TPOL.POL_BILL_MODE_CD
WHERE TPOL.CO_ID='CP'

SELECT TACTH.POL_ID,TPOL.POL_APP_FORM_ID,TPOL.POL_MPREM_AMT,TPOL.POL_CREAT_DT,TPOL.POL_INFC_DT,TACTH.ACCT_HIST_PRCES_DT,TACTH.ACCT_HIST_AMT,TACTH.RECPT_ID,
(TDMAV.DM_AV_DESC_TXT) AS FREQUENCY,TACTH.ACCT_HIST_PST_DT INTO #REV FROM DLKHDIM..DIM_POLICY TPOL
INNER JOIN  SGTB_ACCOUNTING_TRANHIS TACTH ON TACTH.CO_ID=TPOL.CO_ID
AND TACTH.POL_ID=TPOL.POL_ID  
AND TACTH.ACCT_BASE_ID='102300'
AND TACTH.ACCT_HIST_AMT<0
AND TPOL.IS_CURRENT=1
LEFT JOIN   SGTM_PARA_1 AS  TDMAV
ON TDMAV.DM_AV_TBL_CD = 'POL-BILL-MODE-CD' AND TDMAV.DM_AV_CD = TPOL.POL_BILL_MODE_CD
WHERE TPOL.CO_ID='CP' 

SELECT #APP.*,#REV.ACCT_HIST_AMT REV_AMT,#REV.ACCT_HIST_PST_DT REV_DATE FROM #APP LEFT JOIN #REV ON #APP.RECPT_ID=#REV.RECPT_ID AND #APP.POL_ID=#REV.POL_ID

END
