CREATE PROCEDURE [dbo].[RPT_ABA_POLICY]   
AS   

(SELECT 
CONCAT(RTRIM(CLINM.CLI_INDV_SUR_NM),' ',RTRIM(CLINM.CLI_INDV_GIV_NM)) AS CUS_NAME,
--CLI.CLI_ID,
RTRIM(POL.POL_ID) AS 'POL_ID_OR_APP_FORM_ID',
RTRIM(CLICP.CLI_CNTCT_ID_TXT) AS PHONE,
RTRIM(CLIEM.CLI_CNTCT_ID_TXT) AS EMAIL,
RTRIM(PARA.DM_AV_DESC_TXT) AS POL_STATUS
  FROM [ING77PROD].[DB77IPR1].[KCAPXPR1].[TPOL] POL
  INNER JOIN [ING77PROD].[DB77IPR1].[KCAPXPR1].[TPOLC] POLC ON POL.POL_ID=POLC.POL_ID AND POLC.POL_CLI_REL_SUB_CD='P'
  LEFT JOIN [ING77PROD].[DB77IPR1].[KCAPXPR1].[TCLI] CLI ON POLC.CLI_ID=CLI.CLI_ID
  LEFT JOIN (select ROW_NUMBER() OVER ( PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC) AS ROWNUMBER, TCLNM.* from [ING77PROD].[DB77IPR1].[KCAPXPR1].TCLNM) CLINM ON POLC.CLI_ID=CLINM.CLI_ID AND CLINM.ROWNUMBER=1
  LEFT JOIN [ING77PROD].[DB77IPR1].[KCAPXPR1].TCLIC CLICP ON CLI.CLI_ID=CLICP.CLI_ID AND CLICP.[CLI_CNTCT_ID_CD]='MO'
  LEFT JOIN [ING77PROD].[DB77IPR1].[KCAPXPR1].TCLIC CLIEM ON CLI.CLI_ID=CLIEM.CLI_ID AND CLIEM.[CLI_CNTCT_ID_CD]='EM'
  LEFT JOIN dbo.SGTM_PARA_1 AS PARA ON POL.POL_CSTAT_CD = PARA.DM_AV_CD AND PARA.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND PARA.CO_ID='CP' AND PARA.DM_AV_DESC_LANG_CD='E'
  WHERE POL.POL_CSTAT_CD IN('1','B','PCCC','PCCU','PCRC','PCRU','PECC','PECU','PERC','PERU'))
UNION ALL
(SELECT 
CONCAT(RTRIM(CLINM.CLI_INDV_SUR_NM),' ',RTRIM(CLINM.CLI_INDV_GIV_NM)) AS CUS_NAME,
--CLI.CLI_ID,
RTRIM(POL.POL_APP_FORM_ID) AS 'POL_ID_OR_APP_FORM_ID',
RTRIM(CLICP.CLI_CNTCT_ID_TXT) AS PHONE,
RTRIM(CLIEM.CLI_CNTCT_ID_TXT) AS EMAIL,
RTRIM(PARA.DM_AV_DESC_TXT) AS POL_STATUS
  FROM [ING77PROD].[DB77IPR1].[KCAPXPR1].[TPOL] POL
  INNER JOIN [ING77PROD].[DB77IPR1].[KCAPXPR1].[TPOLC] POLC ON POL.POL_ID=POLC.POL_ID AND POLC.POL_CLI_REL_SUB_CD='P'
  LEFT JOIN [ING77PROD].[DB77IPR1].[KCAPXPR1].[TCLI] CLI ON POLC.CLI_ID=CLI.CLI_ID
  LEFT JOIN (select ROW_NUMBER() OVER ( PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC) AS ROWNUMBER, TCLNM.* from [ING77PROD].[DB77IPR1].[KCAPXPR1].TCLNM) CLINM ON POLC.CLI_ID=CLINM.CLI_ID AND CLINM.ROWNUMBER=1
  LEFT JOIN [ING77PROD].[DB77IPR1].[KCAPXPR1].TCLIC CLICP ON CLI.CLI_ID=CLICP.CLI_ID AND CLICP.[CLI_CNTCT_ID_CD]='MO'
  LEFT JOIN [ING77PROD].[DB77IPR1].[KCAPXPR1].TCLIC CLIEM ON CLI.CLI_ID=CLIEM.CLI_ID AND CLIEM.[CLI_CNTCT_ID_CD]='EM'
  LEFT JOIN dbo.SGTM_PARA_1 AS PARA ON POL.POL_CSTAT_CD = PARA.DM_AV_CD AND PARA.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND PARA.CO_ID='CP' AND PARA.DM_AV_DESC_LANG_CD='E'
  WHERE POL.POL_CSTAT_CD IN('1','B','PCCC','PCCU','PCRC','PCRU','PECC','PECU','PERC','PERU'))
