

CREATE PROC [dbo].[RPT_RISK_PEP_INSERT_UPDATE] 

	@PO_ID nchar(20),
	@USERID nchar(50),
	@PEP char(50)
	
	
AS

IF EXISTS (
	SELECT 1
	FROM [UAT7].[DB77IUA1].[KCAPXUT1].[TPOLC]
	WHERE POL_CLI_REL_TYP_CD ='O' AND [CLI_ID] =@PO_ID
)
BEGIN
IF NOT EXISTS(
              
	select 1 from MISRPTDB..AML_RISK_CLARIFICATION WHERE PO_ID = RTRIM(@PO_ID)
)
BEGIN 
    
	
    IF @PEP IS NOT NULL

            BEGIN 

	INSERT INTO MISRPTDB..AML_RISK_CLARIFICATION
	([PO_ID],[PO_PEP],[UPDATED_USER],[UDATED_DATE],[CREATED_DATE],[CREATED_USER])
			   
	VALUES(@PO_ID,@PEP,@USERID,GETDATE(),GETDATE(),@USERID)

END 

END

ELSE
BEGIN
      IF @PEP IS NOT NULL

           BEGIN
	UPDATE MISRPTDB..AML_RISK_CLARIFICATION
	SET [PO_PEP] = @PEP
	,[UDATED_DATE] = GETDATE()
    ,[UPDATED_USER] = @USERID
    WHERE [PO_ID] = RTRIM(@PO_ID)
          END

END
END
;
