
CREATE PROC [dbo].[RPT_BANCA_SUMMARY_POL_BY_DATE]
	@REPORT_DATE	DATE = NULL
AS
	DROP TABLE IF EXISTS #POL_TEMP
	DROP TABLE IF EXISTS #POL
	DROP TABLE IF EXISTS #POLW
	DROP TABLE IF EXISTS #POL_AMT
	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS #SUM_TYP
	DROP TABLE IF EXISTS #BANK_NAME

	SELECT * INTO #POL FROM SGTB_POLICY
	SELECT * INTO #POLW FROM SGTB_POLICY_WRITING
	SELECT * INTO #POL_AMT FROM V_GET_PREMIUM_AMT_POL_LAPSE
	SELECT * INTO #AGENT FROM SGTM_AG

	SELECT  ORDER_NO = 1, SUMMARY_BY = 'Submissions' INTO #SUM_TYP
	UNION
	SELECT ORDER_NO = 2, SUMMARY_BY = 'Issuance (gross)' 
	UNION
	SELECT ORDER_NO = 3, SUMMARY_BY = 'Cancellations' 	

	SELECT POL.POL_ID
		,POL.POL_APP_RECV_DT
		,POL.POL_INFC_DT
		,CFI_DATE = CASE WHEN POL.POL_CSTAT_CD = 'A' THEN POL.POL_STAT_CHNG_DT ELSE NULL END
		,POL.POL_CSTAT_CD
		,POL.POL_BILL_MODE_CD
		,POL_MPREM_AMT = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POLM.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
		,AFYP = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POLM.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END * (12 / CAST(POL.POL_BILL_MODE_CD AS INT))
		,BANK_PARTNER_ID = BKA.AGT_ID
	INTO #POL_TEMP
	FROM #POL POL
	LEFT JOIN #POL_AMT POLM ON POL.POL_ID = POLM.POL_ID
	LEFT JOIN #POLW POLW ON POL.POL_ID = POLW.POL_ID
	LEFT JOIN #AGENT AGT ON POLW.AGT_ID = AGT.AGT_ID
	LEFT JOIN #AGENT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGENT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
	LEFT JOIN #AGENT BKA ON AGM.OVRID_BASE_AGT_ID = BKA.AGT_ID
	WHERE AGT.AGT_DISB_CHNL = '2'

	--DECLARE @REPORT_DATE	DATE = '2022-01-05'

	IF ISNULL(@REPORT_DATE,'') = '' SET @REPORT_DATE = CONVERT(DATE,DATEADD(DAY,-1, GETDATE()))

	SELECT REPORT = 'DAY (Real-time) '-- + UPPER(CONVERT(VARCHAR(10),@REPORT_DATE,110))
		,STYP.ORDER_NO
		,STYP.SUMMARY_BY
		,POL.POL_MPREM_AMT
		,POL.AFYP
		,POL.BANK_PARTNER_ID
		,BANK_PARTNER = RTRIM(AGNM.ENTR_SUR_NM)
	FROM
	(
		-- ORDER NO. = 1: SUBMISSION
		SELECT ORDER_NO = 1,POL.POL_MPREM_AMT,POL.AFYP,BPT.BANK_PARTNER_ID
		FROM #POL_TEMP POL
		RIGHT JOIN SGTM_BANK_PARTNER_TARGET BPT ON POL.BANK_PARTNER_ID = BPT.BANK_PARTNER_ID AND POL.POL_APP_RECV_DT = @REPORT_DATE 
		WHERE MONTH(BPT.TARGET_DATE) = MONTH(GETDATE()) AND YEAR(BPT.TARGET_DATE) = YEAR(GETDATE())

		UNION ALL

		-- ORDER NO. = 2: ISSUANCE
		SELECT ORDER_NO = 2,POL.POL_MPREM_AMT,POL.AFYP,BPT.BANK_PARTNER_ID
		FROM #POL_TEMP POL
		RIGHT JOIN SGTM_BANK_PARTNER_TARGET BPT ON POL.BANK_PARTNER_ID = BPT.BANK_PARTNER_ID AND POL.POL_INFC_DT = @REPORT_DATE 
		WHERE MONTH(BPT.TARGET_DATE) = MONTH(GETDATE()) AND YEAR(BPT.TARGET_DATE) = YEAR(GETDATE())

		UNION ALL

		-- ORDER NO. = 3: CFI
		SELECT ORDER_NO = 3,POL.POL_MPREM_AMT,POL.AFYP,BPT.BANK_PARTNER_ID
		FROM #POL_TEMP POL
		RIGHT JOIN SGTM_BANK_PARTNER_TARGET BPT ON POL.BANK_PARTNER_ID = BPT.BANK_PARTNER_ID AND (POL.CFI_DATE = @REPORT_DATE AND POL.POL_CSTAT_CD = 'A') 
		WHERE MONTH(BPT.TARGET_DATE) = MONTH(GETDATE()) AND YEAR(BPT.TARGET_DATE) = YEAR(GETDATE())

	) POL RIGHT JOIN #SUM_TYP STYP ON POL.ORDER_NO = STYP.ORDER_NO
	LEFT JOIN SGTM_CLIENT_IND AGNM ON POL.BANK_PARTNER_ID = AGNM.CLI_ID
