
CREATE PROC [dbo].[RPT_ST_UAT] 
	@SDATE DATE = NULL,
	@EDATE DATE = NULL
AS
BEGIN
	SELECT P.POL_ID,
		P.PLAN_ID,
		PA.ETBL_DESC_TXT PLAN_NAME,
		PO_NAME = RTRIM(VC.ENTR_SUR_NM)+ ' ' + RTRIM(VC.ENTR_GIV_NM),
		P.POL_APP_RECV_DT CS_REV_DT,
		P.POL_ISS_EFF_DT PRO_LOAD_DT,
		P.POL_INFC_DT POL_ISS_DT,
		SUM(C.CVG_MPREM_AMT) CVG_MPREM_AMT,
		p.POL_BILL_MODE_CD,
		PARA.DM_AV_DESC_TXT POL_CSTAT_CD,
		SUM(CVG_FACE_AMT)CVG_SUM_INS_AMT,
		C.CVG_MAT_XPRY_DUR,
		W.AGT_ID,
		VC.CLI_ID,
		(R.ACCT_HIST_AMT) PRE_RECV,
		CASE WHEN POL_BILL_MODE_CD=3 THEN 'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Month' WHEN POL_BILL_MODE_CD=12 THEN 'Annual' ELSE POL_BILL_MODE_CD END PRE_MODE,
		CONCAT(V.ENTR_SUR_NM,' ',V.ENTR_GIV_NM) AGENT_NAME,
		MET.ETBL_DESC_TXT METHOD,
		BM_NAME = RTRIM(BMNM.ENTR_SUR_NM) + ' ' + RTRIM(BMNM.ENTR_GIV_NM),
		AGENT_MANAGER_PHONE = CLICT.CLI_CNTCT_ID_TXT,
		SLDBR.ETBL_DESC_TXT 
		FROM SGTB_POLICY_CLIENT PC
		INNER JOIN DLKHDIM..DIM_POLICY P ON P.POL_ID=PC.POL_ID AND P.IS_CURRENT=1
		INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1
		INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
		INNER JOIN V_AGENT V ON V.AGT_ID=W.AGT_ID AND V.AGT_CLI_REL_TYP_CD='M'
		INNER JOIN V_CLI_INFO VC ON  VC.CLI_ID=PC.CLI_ID
		INNER JOIN (SELECT SUM(ACCT_HIST_AMT) ACCT_HIST_AMT,POL_ID FROM SGTB_ACCOUNTING_TRANHIS H WHERE H.ACCT_HIST_PST_DT BETWEEN @SDATE AND @EDATE AND ACCT_BASE_ID='249800' AND H.ETL_DATE=(SELECT TOP(1) [BRANCH_DATE] FROM ETLB_BATCH_PROC_DETAIL  WHERE BATCH_CODE = 'ACCTHIS_STG' ORDER BY BRANCH_DATE DESC) GROUP BY POL_ID HAVING SUM(ACCT_HIST_AMT)>=10000) R ON R.POL_ID=P.POL_ID
		LEFT JOIN SGTB_EDITTABLE PA ON P.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
		LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
		LEFT JOIN SGTB_EDITTABLE MET ON MET.ETBL_LANG_CD='E' AND MET.ETBL_TYP_ID='COMTH' AND  P.COLCT_MTHD_CD=MET.ETBL_VALU_ID AND MET.CO_ID='CP'
		LEFT JOIN SGTM_AG AGT ON W.AGT_ID = AGT.AGT_ID
		LEFT JOIN SGTM_AG AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
		LEFT JOIN SGTM_AG AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
		LEFT JOIN SGTM_CLIENT_IND BMNM ON AGM.AGT_ID = BMNM.CLI_ID AND BMNM.PREV_UPDT_TS = (SELECT MAX(PREV_UPDT_TS) FROM SGTM_CLIENT_IND  WHERE CLI_ID = AGM.AGT_ID GROUP BY CLI_ID)
		LEFT JOIN SGTM_CLIENT_CONTACT CLICT ON CLICT.CLI_ID = AGT.AGT_ID AND CLICT.CLI_CNTCT_ID_CD = 'MO'
		LEFT JOIN OPENQUERY(UAT7,'select POLW.POL_SOLD_BR_ID , POL.POL_ID from KCAPXUT1.TPOLW POLW INNER JOIN KCAPXUT1.TPOL POL ON POL.POL_ID = POLW.POL_ID') POL ON POL.POL_ID = P.POL_ID
		LEFT JOIN SGTM_PARA SLDBR ON SLDBR.ETBL_TYP_ID = 'SOLDBR' AND SLDBR.ETBL_LANG_CD = 'E' AND POL.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID
		GROUP BY P.POL_ID,
					P.PLAN_ID,
					PA.ETBL_DESC_TXT,
					VC.ENTR_SUR_NM,
					VC.ENTR_GIV_NM,
					P.POL_APP_RECV_DT,
					P.POL_ISS_EFF_DT,
					P.POL_INFC_DT,
					p.POL_BILL_MODE_CD,
					PARA.DM_AV_DESC_TXT,
					C.CVG_MAT_XPRY_DUR,
					W.AGT_ID,
					VC.CLI_ID,
					V.ENTR_SUR_NM,
					V.ENTR_GIV_NM,
					R.ACCT_HIST_AMT,
					PA.ETBL_DESC_TXT,
					MET.ETBL_DESC_TXT,
					SLDBR.ETBL_DESC_TXT,
					RTRIM(BMNM.ENTR_SUR_NM) + ' ' + RTRIM(BMNM.ENTR_GIV_NM), 
					CLICT.CLI_CNTCT_ID_TXT

END
