
CREATE PROC [dbo].[RPT_BBM_SUMMARY_POL_BY_MONTH_UW_STATUS]	
AS

--- CHANGE 2023/05/22: REPLACE TABLE MD.AGENT TO SGTM_AGENT_DETAIL SINCE MD.AGENT DATA IS NOT SYNC LATEST ---

	DECLARE
		@START_DATE	DATE = DATEADD(DAY,-DAY(GETDATE()) + 1,GETDATE())
		,@END_DATE	DATE = CONVERT(DATE,GETDATE())

	DROP TABLE IF EXISTS #POL_TEMP
	DROP TABLE IF EXISTS #POL
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #POL_AMT
	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS #SUM_TYP
	DROP TABLE IF EXISTS #REQT
	DROP TABLE IF EXISTS #NJET
	DROP TABLE IF EXISTS #TEMP_DATA

	-- GET ONLY REQUIRED DATA FROM POLICY - TPOL
	SELECT * INTO #POL FROM OPENQUERY(UAT7,'
		SELECT POL.POL_ID,POL.POL_APP_RECV_DT,POL.POL_INFC_DT,POL.POL_STAT_CHNG_DT,POL.POL_CSTAT_CD
			,POL.POL_BILL_MODE_CD,POL.POL_MPREM_AMT,POLW.AGT_ID
		FROM KCAPXUT1.TPOL POL
		LEFT JOIN KCAPXUT1.TPOLW POLW ON POL.POL_ID = POLW.POL_ID
	')

	SELECT REQT.*, NJET.GRP_CD
	INTO #REQT FROM OPENQUERY(UAT7,'
		SELECT POL_CLI_ID,REQIR_ID,CPREQ_STAT_CD FROM KCAPXUT1.TREQT WHERE CPREQ_POL_CLI_CD = ''P'' AND CPREQ_STAT_CD IN (''ORD'')
	') REQT INNER JOIN V_GET_NON_JET_AND_INCOMPLETE_CODE NJET ON REQT.REQIR_ID = NJET.REQIR_ID

	SELECT DISTINCT POL_CLI_ID,GRP_CD INTO #NJET  FROM #REQT WHERE GRP_CD = 'COL' 
	DELETE FROM #REQT WHERE POL_CLI_ID IN (SELECT POL_CLI_ID FROM #NJET)
	INSERT INTO #NJET SELECT DISTINCT POL_CLI_ID,GRP_CD FROM #REQT WHERE GRP_CD = 'ME'
	DELETE FROM #REQT WHERE POL_CLI_ID IN (SELECT POL_CLI_ID FROM #NJET)
	INSERT INTO #NJET SELECT DISTINCT POL_CLI_ID,GRP_CD FROM #REQT WHERE GRP_CD = 'IA'
	DELETE FROM #REQT WHERE POL_CLI_ID IN (SELECT POL_CLI_ID FROM #NJET)
	INSERT INTO #NJET SELECT DISTINCT POL_CLI_ID,GRP_CD FROM #REQT WHERE GRP_CD = 'OTR'

	-- GET PREMIUM AMOUNT FOR ANY POLICIES WITH STATUS LAPSED OR REJECTED
	SELECT * INTO #POL_AMT FROM V_GET_PREMIUM_AMT_POL_LAPSE

	-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT
		, #LAST_UPDT = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM
	FROM OPENQUERY(UAT7, 'SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS
		FROM KCAPXUT1.TCLNM')

	-- GET SOME INFO OF AGENT ONLY 
	SELECT AG.AGT_ID,AG.AGT_DISB_CHNL,AG.OVRID_BASE_AGT_ID
	INTO #AGENT 
	FROM OPENQUERY(UAT7, 'SELECT AGT_ID,AGT_DISB_CHNL,OVRID_BASE_AGT_ID
		FROM KCAPXUT1.TAG
		WHERE AGT_DISB_CHNL = ''2''
	') AG

	-- PREPARE RESULT
	SELECT POL.POL_ID
		,POL.POL_APP_RECV_DT
		,POL.POL_INFC_DT
		,CFI_DATE = CASE WHEN POL.POL_CSTAT_CD = 'A' THEN POL.POL_STAT_CHNG_DT ELSE NULL END
		,POL.POL_CSTAT_CD
		,POL.POL_BILL_MODE_CD
		,POL_MPREM_AMT = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POLM.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
		,AFYP = CASE WHEN POL.POL_MPREM_AMT = 0 
					THEN POLM.POL_MPREM_AMT 
				ELSE POL.POL_MPREM_AMT 
		END * (CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL.POL_BILL_MODE_CD AS INT) END)
			
		,BBM_NAME = AGN.[Name]
		,AGENT_ID = AGN.AgentId
		,BANK_NAME = LEFT(AGN.Tier1Name, CHARINDEX(' ', AGN.Tier1Name,0 ))
		,NJET.GRP_CD
	INTO #POL_TEMP
	FROM #POL POL
	LEFT JOIN #POL_AMT POLM ON POL.POL_ID = POLM.POL_ID
	LEFT JOIN #AGENT AGT ON POL.AGT_ID = AGT.AGT_ID
	LEFT JOIN #AGENT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGENT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
	--LEFT JOIN MISRPTDB.md.Agent AGN ON AGN.AgentId = AGM.AGT_ID AND AGN.TitleRole = 'Banca Region' --REMOVED 2023/05/22 BY OUDOM
	LEFT JOIN SGTM_AGENT_DETAIL AGN ON AGN.AgentId = AGM.AGT_ID AND AGN.TitleRole IN ('Banca Region','SBBS', 'BBM', 'SBBM', 'RH') --ADDED 2023/05/22 BY OUDOM
	LEFT JOIN #NJET NJET ON NJET.POL_CLI_ID = POL.POL_ID
	WHERE AGT.AGT_DISB_CHNL = '2' AND LEFT(POL.POL_CSTAT_CD, 1) IN ('P')
	--RETURN
	
	SELECT DISTINCT
		BBM_NAME = MISRPTDB.dbo.CamelCase(BBM.[Name])
		,BANK_NAME =LEFT(BKBRN.[Name], CHARINDEX(' ', BKBRN.[Name],0 ))
		,TARGET_COUNT = ISNULL(TRG.IssuanceCount, 0)
		,TARGET_FYP = ISNULL(TRG.IssuanceFYP, 0)
		,ME_FYP = ISNULL(ME.FYP, 0)
		,ME_COUNT = ISNULL(ME.TOTAL_CASE, 0)
		,NON_FYP = ISNULL(NON.FYP, 0)
		,NON_COUNT = ISNULL(NON.TOTAL_CASE, 0)
		,COL_FYP = ISNULL(COL.FYP, 0)
		,COL_COUNT = ISNULL(COL.TOTAL_CASE, 0)
		,NOTYET_FYP = ISNULL(NOTYET.FYP, 0)
		,NOTYET_COUNT = ISNULL(NOTYET.TOTAL_CASE, 0)
	INTO #TEMP_DATA
	--FROM MISRPTDB.md.Agent BBM --REMOVED 2023/05/22 BY OUDOM
	FROM SGTM_AGENT_DETAIL BBM --ADDED 2023/05/22 BY OUDOM
		LEFT JOIN MISRPTDB.cfg.BBMTarget TRG 
			ON  TRG.[Year]=YEAR(@START_DATE) AND TRG.[Month]=MONTH(@START_DATE) AND TRG.AgentId=BBM.[AgentId]
		--LEFT JOIN MISRPTDB.md.Agent BKBRN ON BKBRN.Tier1Id=BBM.AgentId --REMOVED 2023/05/22 BY OUDOM
		LEFT JOIN SGTM_AGENT_DETAIL BKBRN ON BKBRN.Tier1Id=BBM.AgentId --ADDED 2023/05/22 BY OUDOM
		--LEFT JOIN MISRPTDB.md.Agent FA ON FA.Tier1Id= BKBRN.AgentId  --REMOVED 2023/05/22 BY OUDOM
		LEFT JOIN SGTM_AGENT_DETAIL FA ON FA.Tier1Id= BKBRN.AgentId  --ADDED 2023/05/22 BY OUDOM
		
		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP, TOTAL_CASE = COUNT(*), POL.AGENT_ID
			FROM #POL_TEMP POL 
			WHERE POL.GRP_CD IN ('ME')
			GROUP BY POL.AGENT_ID
		) ME ON ME.AGENT_ID =  BBM.AgentId -- MED

		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP ,TOTAL_CASE = COUNT(*) ,POL.AGENT_ID
			FROM #POL_TEMP POL 
			WHERE POL.GRP_CD IN ('IA','OTR')
			GROUP BY POL.AGENT_ID
		) NON ON NON.AGENT_ID =  BBM.AgentId -- Non-MED

		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP ,TOTAL_CASE = COUNT(*) ,POL.AGENT_ID
			FROM #POL_TEMP POL 
			WHERE POL.GRP_CD IN ('COL')
			GROUP BY POL.AGENT_ID
		) COL ON COL.AGENT_ID =  BBM.AgentId -- Pending COL Acceptance

		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP ,TOTAL_CASE = COUNT(*) ,POL.AGENT_ID
			FROM #POL_TEMP POL 
			WHERE POL.GRP_CD IS NULL
			GROUP BY POL.AGENT_ID
		) NOTYET ON NOTYET.AGENT_ID =  BBM.AgentId -- Not Yet Check Completeness

	WHERE BBM.TitleRole IN ('Banca Region','SBBS', 'BBM', 'SBBM', 'RH')
		AND BBM.DistributionChannel='BANCA'
		AND FA.AgentId IS NOT NULL

	--SELECT * FROM #TEMP_DATA
	--RETURN;

	-- Select
    SELECT  ORDER_NO = 2, SUMMARY_BY = 'Non-MED' 
	INTO #SUM_TYP
		UNION SELECT ORDER_NO = 1, SUMMARY_BY = 'MED'
		UNION SELECT ORDER_NO = 3, SUMMARY_BY = 'Pending COL Acceptance'
		UNION SELECT ORDER_NO = 4, SUMMARY_BY = 'Not Yet Check Completeness'

	SELECT
		POL.ORDER_NO,
		POL.FYP,
		POL.TOTAL_CASE,
		POL.AGT_LDR_SUR_NM,
		POL.AGT_MGR_SUR_NM,
		STYP.SUMMARY_BY
	FROM (
		SELECT ORDER_NO = 1,
            FYP = POL.ME_FYP,
			TOTAL_CASE = POL.ME_COUNT,
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.ME_COUNT, POL.ME_FYP

		UNION ALL 
		SELECT ORDER_NO = 2,
            FYP = POL.NON_FYP,
			TOTAL_CASE = POL.NON_COUNT,
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.NON_FYP, POL.NON_COUNT

		UNION ALL 
		SELECT ORDER_NO = 3,
            FYP = POL.COL_FYP,
			TOTAL_CASE = POL.COL_COUNT,
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.COL_FYP, POL.COL_COUNT

		UNION ALL 
		SELECT ORDER_NO = 4,
            FYP = POL.NOTYET_FYP,
			TOTAL_CASE = POL.NOTYET_COUNT,
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.NOTYET_FYP, POL.NOTYET_COUNT

	) POL
	RIGHT JOIN #SUM_TYP STYP 
		ON POL.ORDER_NO = STYP.ORDER_NO

	ORDER BY
	   CASE WHEN POL.AGT_LDR_SUR_NM = 'VATTANAC' THEN 0
			WHEN POL.AGT_LDR_SUR_NM = 'SACOM' THEN 1
			WHEN POL.AGT_LDR_SUR_NM = 'AMK' THEN 2
			WHEN POL.AGT_LDR_SUR_NM = 'RHB' THEN 3
	   END

	DROP TABLE IF EXISTS #POL_TEMP
	DROP TABLE IF EXISTS #POL
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #POL_AMT
	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS #SUM_TYP
	DROP TABLE IF EXISTS #REQT
	DROP TABLE IF EXISTS #NJET
	DROP TABLE IF EXISTS #TEMP_DATA
