

create PROC [dbo].[RPT_PNS_POL_ISS_UAT] 
	@START	DATE = ''
	,@END	DATE = ''
AS

	--DECLARE @START	DATE = NULL
	--,@END		DATE = NULL

	DROP TABLE IF EXISTS	#TREQT 
	DROP TABLE IF EXISTS	#DISPATCH
	DROP TABLE IF EXISTS	#TMP
	DROP TABLE IF EXISTS	#TMP1
	DROP TABLE IF EXISTS	#BLI
	DROP TABLE IF EXISTS	#PO
	DROP TABLE IF EXISTS	#T
	DROP TABLE IF EXISTS	#ALI
	DROP TABLE IF EXISTS	#POL
	DROP TABLE IF EXISTS	#TCVG
	DROP TABLE IF EXISTS	#EDIT
	DROP TABLE IF EXISTS	#TCLNM
	DROP TABLE IF EXISTS	#TCLIA
	DROP TABLE IF EXISTS	#TCLIC
	DROP TABLE IF EXISTS	#CLI
	DROP TABLE IF EXISTS	#AGENT
	DROP TABLE IF EXISTS	#XTAB

	IF ISNULL(@START,'') = '' SET @START = '2000-01-01'
	IF ISNULL(@END,'') = '' SET @END = CONVERT(DATE,GETDATE())

	SELECT [POLICY_ID],(DATEDIFF(DAY, DIS.DISPATCHED_DATE, DIS.ACKNOWLEDGEMENT_DATE)) NB_DURATION,
		[CREATED_USER],DISPATCHED_DATE,ACKNOWLEDGEMENT_DATE,WELCOME_DATE
		INTO #DISPATCH
	FROM [PNSDLIKH].[DBO].[INGENIUM_POLICY_DISPATCHES] DIS

	-- GET ONLY REQUIRED TYPES FROM TEDIT ONLY
	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #EDIT FROM OPENQUERY(UAT7,
	'	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT FROM KCAPXUT1.TEDIT WHERE ETBL_LANG_CD = ''E'' AND CO_ID = ''CP''
			AND ETBL_TYP_ID IN (''CTYPC'',''MCPCD'',''CLOC'',''BILL-MODE'',''PLAN'',''DCHNL'')
	')

	SELECT ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #XTAB FROM SGTM_PARA
	WHERE ETBL_LANG_CD = 'E' AND ETBL_TYP_ID = 'SOLDBR'

	-- GET REQUIRED INFO OF CLIENT ONLY - TCLI
	SELECT * INTO #CLI FROM OPENQUERY(UAT7,
	'	SELECT CLI.CLI_ID,CLI.CLI_BTH_DT,CLI.CLI_CIN_NUM,CLI.CLI_SEX_CD,CLI.CLI_HT,CLI.CLI_WGT
			,CLI.CLI_SMKR_CD,CLI.CLI_US_TAX_ID,CLI.OCCP_ID,CLI.CLI_OCCP_CLAS_CD
		FROM KCAPXUT1.TCLI CLI
		WHERE LENGTH(CLI_ID) >= 10
	')

	-- GET ONLY REQUIRED INFO OF CLIENT CONTACT - TCLIC
	SELECT CLI_ID,CLI_CNTCT_ID_CD,CLI_CNTCT_ID_TXT = RTRIM(CLI_CNTCT_ID_TXT)
	INTO #TCLIC FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_CNTCT_ID_CD,CLI_CNTCT_ID_TXT
		FROM KCAPXUT1.TCLIC
	')

	-- GET ONLY REQUIRED INFO ON CLIENT ADDRESS - TCLIA
	SELECT CLI_ID,CLI_ADDR_LN_1_TXT = RTRIM(CLI_ADDR_LN_1_TXT),CLI_ADDR_LN_2_TXT = RTRIM(CLI_ADDR_LN_2_TXT)
		,CLI_ADDR_LN_3_TXT = RTRIM(CLI_ADDR_LN_3_TXT),CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD,CLI_CRNT_LOC_CD,CLI_CITY_NM_TXT = RTRIM(CLI_CITY_NM_TXT)
		,#LAST_UPDT_ADDR = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLIA FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,CLI_ADDR_LN_1_TXT,CLI_ADDR_LN_2_TXT,CLI_ADDR_LN_3_TXT,CLI_ADDR_CNTY_CD,CLI_ADDR_MUN_CD
			,CLI_CRNT_LOC_CD,CLI_CITY_NM_TXT,PREV_UPDT_TS
		FROM KCAPXUT1.TCLIA
		WHERE CLI_ADDR_TYP_CD = ''PR'' AND LENGTH(CLI_ID) >= 10
	')

	-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT
		,#LAST_UPDT_NM = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM
	FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS
		FROM KCAPXUT1.TCLNM
	')

	--SELECT * INTO #TCVGC FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUT1.TCVGC')
	SELECT * INTO #TCVG FROM OPENQUERY(UAT7,
	'	
		SELECT CVG.POL_ID,CVG.CVG_NUM,CVG.PLAN_ID,CVG.CVG_MAT_XPRY_DUR,CVG.CVG_RT_AGE,CVG.CVG_FACE_AMT
			,CVG.CVG_SAR_BASE, CVGC.INSRD_CLI_ID
		FROM KCAPXUT1.TCVG CVG
		INNER JOIN KCAPXUT1.TCVGC CVGC ON CVG.POL_ID = CVGC.POL_ID AND CVG.CVG_NUM = CVGC.CVG_NUM AND CVG.CVG_FACE_AMT > 0
	')

	SELECT POL.*,POL_MPREM_AMT_HIS = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END, REMC.SUBMITED_TYPE 
	INTO #POL 
	FROM OPENQUERY(UAT7,
		'
			SELECT POL.POL_ID,POL.POL_INFC_DT,POL.POL_BILL_MODE_CD,POL.POL_CSTAT_CD,POL.PLAN_ID,POL.POL_APP_FORM_ID
				,POL.POL_REISS_DT,POL.POL_MPREM_AMT,POL.POL_PREV_MPREM_AMT,POL.POL_ISS_EFF_DT,POL.POL_APP_RECV_DT
				,POL.POL_STAT_CHNG_DT,POL.POL_PD_TO_DT_NUM
				,POLC.CLI_ID,POLW.AGT_ID,POLW.POL_SOLD_BR_ID,POL.POL_NOT
			FROM KCAPXUT1.TPOL POL
			INNER JOIN KCAPXUT1.TPOLC POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = ''O''
			INNER JOIN KCAPXUT1.TPOLW POLW ON POL.POL_ID = POLW.POL_ID
		'
	) POL
	LEFT JOIN V_GET_REMOTE_CASE_OF_EXIST_POLICY REMC ON POL.POL_ID = REMC.POL_ID
	LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE_LIVE POL0 ON POL.POL_ID = POL0.POL_ID

	SELECT REQT.*, NJET.GRP_CD, NJET.NON_JET_STAT_CD INTO #TREQT FROM OPENQUERY(UAT7,'SELECT REQIR_ID,POL_CLI_ID FROM KCAPXUT1.TREQT WHERE CPREQ_POL_CLI_CD = ''P'' ') REQT
		INNER JOIN V_GET_NON_JET_AND_INCOMPLETE_CODE NJET ON REQT.REQIR_ID = NJET.REQIR_ID                      

	-- GET SOME INFO OF AGENT ONLY 
	SELECT AG.AGT_ID,AG.AGT_DISB_CHNL,AGT_DISB_CHNL_NAME = CHNL.ETBL_DESC_TXT,AG.OVRID_BASE_AGT_ID,AGNM.ENTR_SUR_NM,AGNM.ENTR_GIV_NM,AGT_PHON_NUM = AGCT.CLI_CNTCT_ID_TXT
	INTO #AGENT 
	FROM OPENQUERY(UAT7,
	'	SELECT AGT_ID,AGT_DISB_CHNL,OVRID_BASE_AGT_ID
		FROM KCAPXUT1.TAG
	') AG
	LEFT JOIN #TCLNM AGNM ON AG.AGT_ID = AGNM.CLI_ID AND AGNM.#LAST_UPDT_NM = 1
	LEFT JOIN #TCLIC AGCT ON AG.AGT_ID = AGCT.CLI_ID AND AGCT.CLI_CNTCT_ID_CD='MO'
	LEFT JOIN #EDIT CHNL ON AG.AGT_DISB_CHNL = CHNL.ETBL_VALU_ID AND ETBL_TYP_ID = 'DCHNL'

	SELECT POL.CLI_ID
		,POL.POL_ID
		,POL_APP_FORM_ID = RTRIM(POL_APP_FORM_ID)
		,CVG_FACE_AMT
		,POL_MPREM_AMT = POL.POL_MPREM_AMT_HIS
		,CVG.INSRD_CLI_ID
		,CVG.PLAN_ID
		,(PA.ETBL_DESC_TXT) PLAN_DESC
		,(PARA.DM_AV_DESC_TXT)  POL_STAT
		,(BLM.ETBL_DESC_TXT) PRE_MODE
		,((CLNM.ENTR_SUR_NM)) + ' ' + ((CLNM.ENTR_GIV_NM)) CLIENT_NAME
		,(C1.CLI_CNTCT_ID_TXT) PHONE
		,CLI_ADDR_LN_1_TXT = (CLIA.CLI_ADDR_LN_1_TXT)
		,CLI_ADDR_LN_2_TXT = (CLIA.CLI_ADDR_LN_2_TXT)
		,CLI_ADDR_LN_3_TXT = (CLIA.CLI_ADDR_LN_3_TXT)
		,CLI_CITY_NM_TXT = (CLIA.CLI_CITY_NM_TXT)
		,POL.POL_ISS_EFF_DT
		,POL.POL_APP_RECV_DT POL_CREAT_DT
		,POL.POL_INFC_DT POL_APP_CMPLT_DT
		,POL.POL_REISS_DT POL_STAT_CHNG_DT
		,POL.AGT_ID
		,((AGT.ENTR_SUR_NM))+' '+ ((AGT.ENTR_GIV_NM)) AGENT_NAME
		,((AGM.ENTR_SUR_NM))+' '+ ((AGM.ENTR_GIV_NM)) ABM
		,(AGT.AGT_DISB_CHNL_NAME) CSC_NAME
		,REASON = ''	-- RR.REASON
		,JET_STATUS = CASE WHEN ISNULL(TCOL.NON_JET_STAT_CD,'') = '' AND ISNULL(TME.NON_JET_STAT_CD, '') = ''
			AND ISNULL(TIA.NON_JET_STAT_CD,'') = '' AND ISNULL(TOTR.NON_JET_STAT_CD,'') = '' THEN 'JET CASE' ELSE 'NON-JET CASE' END
		,COL = TCOL.NON_JET_STAT_CD
		,ME = TME.NON_JET_STAT_CD
		,IA = TIA.NON_JET_STAT_CD
		,OTR = TOTR.NON_JET_STAT_CD
		,D.DISPATCHED_DATE DISPATCH_DATE
		,D.ACKNOWLEDGEMENT_DATE AL_RECEIPT_DATE
		,D.NB_DURATION DURATION
		,D.WELCOME_DATE WELCOME_CALL
		,RTRIM(D.CREATED_USER) CREATE_BY
		,APE = (12 / CAST(POL_BILL_MODE_CD AS INT)) * POL.POL_MPREM_AMT_HIS
		,CASE WHEN POL_CSTAT_CD = 'B' THEN POL_STAT_CHNG_DT ELSE NULL END LAPSED_DATE
		,DBO.CONVERTDATE(POL_PD_TO_DT_NUM) POL_PD_TO_DT_NUM
		,CVG.CVG_MAT_XPRY_DUR
		,(CMU.ETBL_DESC_TXT) COMMUNE
		,(DIS.ETBL_DESC_TXT) DISTRICT
		,(CIT.ETBL_DESC_TXT) CITY
		,CLI.CLI_SEX_CD
		,CVG_RT_AGE = CVG.CVG_RT_AGE + 0
		,REMOTE_CASE = 
			CASE WHEN ISNULL(POL.SUBMITED_TYPE,'') != '' THEN POL.SUBMITED_TYPE 
			ELSE 
				CASE WHEN LEFT(POL.POL_APP_FORM_ID,2) IN ('AR', 'BR') THEN 'Remote Case' ELSE NULL END
			END
		,POL.POL_SOLD_BR_ID
		,POL_SOLD_BR_NAME = SLDBR.ETBL_DESC_TXT
		,UW.SAR
		,POL.POL_NOT AS POL_NOT
	INTO #TMP 
	FROM #POL POL
	LEFT JOIN #TCVG CVG ON CVG.POL_ID = POL.POL_ID
	LEFT JOIN (SELECT POL_ID, SUM(CVG_SAR_BASE) SAR FROM #TCVG GROUP BY POL_ID) UW ON POL.POL_ID = UW.POL_ID 
	LEFT JOIN #TCLNM CLNM ON CLNM.CLI_ID = CVG.INSRD_CLI_ID AND CLNM.#LAST_UPDT_NM = 1
	LEFT JOIN #CLI CLI ON POL.CLI_ID = CLI.CLI_ID

	LEFT JOIN #AGENT AGT ON AGT.AGT_ID = POL.AGT_ID 
	LEFT JOIN #AGENT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGENT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID

	LEFT JOIN #TCLIA CLIA ON POL.CLI_ID = CLIA.CLI_ID AND CLIA.#LAST_UPDT_ADDR = 1
	LEFT JOIN #EDIT PA ON POL.PLAN_ID = PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID = 'PLAN' 
	LEFT JOIN #EDIT CMU ON CMU.ETBL_TYP_ID = 'CTYPC' AND CLIA.CLI_ADDR_CNTY_CD = CMU.ETBL_VALU_ID
	LEFT JOIN #EDIT DIS ON DIS.ETBL_TYP_ID = 'MCPCD' AND CLIA.CLI_ADDR_MUN_CD = DIS.ETBL_VALU_ID 
	LEFT JOIN #EDIT CIT ON CIT.ETBL_TYP_ID = 'CLOC' AND  CLIA.CLI_CRNT_LOC_CD = CIT.ETBL_VALU_ID 
	LEFT JOIN SGTM_PARA_1 PARA ON POL.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.CO_ID='CP' AND PARA.DM_AV_DESC_LANG_CD = 'E'
	LEFT JOIN #TREQT TCOL ON POL.POL_ID = TCOL.POL_CLI_ID AND TCOL.GRP_CD = 'COL'
	LEFT JOIN #TREQT TME ON POL.POL_ID = TME.POL_CLI_ID AND TME.GRP_CD = 'ME'
	LEFT JOIN #TREQT TIA ON POL.POL_ID = TIA.POL_CLI_ID AND TIA.GRP_CD = 'IA'
	LEFT JOIN #TREQT TOTR ON POL.POL_ID = TOTR.POL_CLI_ID AND TOTR.GRP_CD = 'OTR'
	LEFT JOIN #DISPATCH D ON POL.POL_ID=D.POLICY_ID 
	LEFT JOIN #TCLIC C1 ON POL.CLI_ID = C1.CLI_ID AND C1.CLI_CNTCT_ID_CD = 'MO'
	LEFT JOIN #EDIT BLM ON POL.POL_BILL_MODE_CD = BLM.ETBL_VALU_ID AND BLM.ETBL_TYP_ID ='BILL-MODE'
	LEFT JOIN #XTAB SLDBR ON POL.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_TYP_ID = 'SOLDBR'
	WHERE POL.POL_INFC_DT BETWEEN @START AND @END OR (POL_REISS_DT BETWEEN @START AND @END)  

	SELECT * INTO #TMP1 FROM #TMP WHERE LEFT(PLAN_ID,2) IN ('KB','DW','CB')
	INSERT INTO #TMP1
	SELECT * FROM #TMP TM WHERE  LEFT(TM.PLAN_ID,2) = 'DR' AND TM.INSRD_CLI_ID NOT IN (SELECT T.INSRD_CLI_ID FROM #TMP1 T WHERE T.POL_ID = TM.POL_ID)

	SELECT * INTO #BLI FROM #TMP1 WHERE LEFT(PLAN_ID,2) IN ('KB','CB')
	SELECT * INTO #PO FROM #TMP1 WHERE LEFT(PLAN_ID,2) = 'DW'
	SELECT  DISTINCT POL_ID,INSRD_CLI_ID,CLIENT_NAME,PHONE,CVG_RT_AGE INTO #T FROM #TMP1 WHERE LEFT(PLAN_ID,2) = 'DR'

	SELECT * INTO #ALI FROM (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY INSRD_CLI_ID) AS ROW#,*  FROM #T) T
	--SELECT POL_NOT , POL_ID INTO #UEF FROM DLKHSTAGE.dbo.SGTB_POLICY WHERE POL_NOT='UEF' ; 
	SELECT DISTINCT BLI.*
		,CASE WHEN PO.POL_ID IS NOT NULL THEN PO.CLIENT_NAME ELSE BLI.CLIENT_NAME END PONAME
		,CASE WHEN PO.POL_ID IS NOT NULL THEN PO.INSRD_CLI_ID ELSE BLI.INSRD_CLI_ID END POCLI
		,CASE WHEN PO.POL_ID IS NOT NULL THEN PO.PHONE ELSE BLI.PHONE END POPHONE
		,CASE WHEN PO.POL_ID IS NOT NULL THEN PO.CVG_RT_AGE ELSE BLI.CVG_RT_AGE END PO_AGE
		,CASE WHEN ALI1.POL_ID IS NOT NULL THEN ALI1.CLIENT_NAME ELSE '' END ALNAME1
		,CASE WHEN ALI1.POL_ID IS NOT NULL THEN ALI1.INSRD_CLI_ID ELSE '' END ALCLI1
		,CASE WHEN ALI1.POL_ID IS NOT NULL THEN ALI1.PHONE ELSE '' END ALPHONE1
		,CASE WHEN ALI1.POL_ID IS NOT NULL THEN ALI1.CVG_RT_AGE ELSE '0' END ALI1_AGE
		,CASE WHEN ALI2.POL_ID IS NOT NULL THEN ALI2.CLIENT_NAME ELSE '' END ALNAME2
		,CASE WHEN ALI2.POL_ID IS NOT NULL THEN ALI2.INSRD_CLI_ID ELSE '' END ALCLI2
		,CASE WHEN ALI2.POL_ID IS NOT NULL THEN ALI2.PHONE ELSE '' END ALPHONE2 
		,CASE WHEN ALI2.POL_ID IS NOT NULL THEN ALI2.CVG_RT_AGE ELSE '' END ALI2_AGE
		
	FROM #BLI BLI 
	LEFT JOIN #PO PO ON BLI.POL_ID = PO.POL_ID
	LEFT JOIN #ALI ALI1 ON BLI.POL_ID = ALI1.POL_ID AND ALI1.ROW#=1
	LEFT JOIN #ALI ALI2 ON BLI.POL_ID = ALI2.POL_ID AND ALI2.ROW#=2
