CREATE proc [dbo].[rpt_test]
as

	 IF OBJECT_ID('tempdb..#EDIT') IS NOT NULL
  DROP TABLE #EDIT
	 IF OBJECT_ID('tempdb..#CINFOR') IS NOT NULL
  DROP TABLE #CINFOR
	 IF OBJECT_ID('tempdb..#CLIB') IS NOT NULL
  DROP TABLE #CLIB
	 IF OBJECT_ID('tempdb..#CIND') IS NOT NULL
  DROP TABLE #CIND
	 IF OBJECT_ID('tempdb..#CLI') IS NOT NULL
  DROP TABLE #CLI
	 IF OBJECT_ID('tempdb..#POL') IS NOT NULL
  DROP TABLE #POL
	 IF OBJECT_ID('tempdb..#POLW') IS NOT NULL
  DROP TABLE #POLW
	 IF OBJECT_ID('tempdb..#POLC') IS NOT NULL
  DROP TABLE #POLC
	 IF OBJECT_ID('tempdb..#TCVGC') IS NOT NULL
  DROP TABLE #TCVGC
	 IF OBJECT_ID('tempdb..#TCVG') IS NOT NULL
  DROP TABLE #TCVG
	 IF OBJECT_ID('tempdb..#TCLII') IS NOT NULL
  DROP TABLE #TCLII
	 IF OBJECT_ID('tempdb..#TCLNM') IS NOT NULL
  DROP TABLE #TCLNM
  	 IF OBJECT_ID('tempdb..#TCLIA') IS NOT NULL
  DROP TABLE #TCLIA
   IF OBJECT_ID('tempdb..#TCLIC') IS NOT NULL
  DROP TABLE #TCLIC
     IF OBJECT_ID('tempdb..#TREQT') IS NOT NULL
  DROP TABLE #TREQT

select * INTO #EDIT from openquery(PROD,'select * from kcapxpr1.tedit where etbl_typ_id=''OCCCD''')
SELECT * INTO #CLIB FROM OPENQUERY(PROD,'SELECT CLI_ID,CB.BNK_ACCT_ID,CLI_BNK_ACCT_DT,BNK_ACCT_TYP_CD,BNK_ACCT_HLDR_NM,BNK_NM FROM KCAPXPR1.TCLIB CB INNER JOIN KCAPXPR1.TBNKA A ON CB.BNK_ACCT_ID=A.BNK_ACCT_ID AND CB.BNK_ID=A.BNK_ID AND CB.BNK_BR_ID=A.BNK_BR_ID
INNER JOIN KCAPXPR1.TBNKB B ON B.BNK_ID=CB.BNK_ID WHERE CLI_BNK_ACCT_CD=1')
SELECT * INTO #CLI FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLI')
SELECT * INTO #POL FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TPOL')
SELECT * INTO #POLW FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TPOLW')
SELECT * INTO #POLC FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TPOLC')
SELECT * INTO #TCVGC FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCVGC')
SELECT * INTO #TCVG FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCVG')
SELECT * INTO #TCLII FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLII')
SELECT * INTO #TCLNM FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLNM')
SELECT * INTO #TCLIA FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLIA')
SELECT * INTO #TCLIC FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TCLIC')
SELECT * INTO #TREQT FROM OPENQUERY(PROD,'SELECT * FROM KCAPXPR1.TREQT')

SELECT I.* INTO #CINFOR FROM #TCLII I INNER JOIN (SELECT MAX(CLI_INCM_EFF_DT) EFF, CLI_ID FROM #TCLII GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INCM_EFF_DT=II.EFF
SELECT I.* INTO #CIND FROM #TCLNM I INNER JOIN (SELECT MAX(CLI_INDV_EFF_DT) EFF, CLI_ID FROM #TCLNM GROUP BY CLI_ID) II ON I.CLI_ID=II.CLI_ID AND I.CLI_INDV_EFF_DT=II.EFF

SELECT distinct P.POL_APP_SIGN_DT,P.POL_CREAT_DT,P.POL_APP_RECV_DT,P.POL_ID,P.POL_APP_FORM_ID,P.PREV_UPDT_USER_ID,CL.CLI_BTH_DT HCLI_BTH_DT,CL.CLI_ID_NUM HCLI_ID_NUM,CL.CLI_SEX_CD HCLI_SEX_CD,CL.CLI_HT HCLI_HT,
CL.CLI_WGT HCLI_WGT,CL.CLI_SMKR_CD HCLI_SMKR_CD,CL.CLI_DOC_TYP HCLI_DOC_TYP,HE.ETBL_DESC_TXT HOCCP_ID,CI.ENTR_SUR_NM HENTR_SUR_NM,CI.ENTR_GIV_NM HENTR_GIV_NM,CL.CLI_ID HCLI_ID,DATEDIFF(YEAR,CL.CLI_BTH_DT,GETDATE()) HAGE,
CAD.CLI_ADDR_LN_1_TXT HCLI_ADDR_LN_1_TXT,CAD.CLI_ADDR_LN_2_TXT HCLI_ADDR_LN_2_TXT,CAD.CLI_ADDR_LN_3_TXT HCLI_ADDR_LN_3_TXT,CAD.CLI_CITY_NM_TXT HCLI_CITY_NM_TXT,CINFOR.CLI_EARN_INCM_AMT,C1.CLI_CNTCT_ID_TXT HPHONE1,C2.CLI_CNTCT_ID_TXT HPHONE2,EM.CLI_CNTCT_ID_TXT HEMAIL,
CASE WHEN RR.POL_CLI_ID IS NULL THEN 'NON-JET CASE' ELSE 'JET CASE' END JETCASE,

CVL.CVG_NUM,CVL.INSRD_CLI_ID,CCL.CLI_BTH_DT,CCL.CLI_ID_NUM,CCL.CLI_SEX_CD,CCL.CLI_HT,CCL.CLI_WGT,CCL.CLI_SMKR_CD,CCL.CLI_DOC_TYP,HHE.ETBL_DESC_TXT OCCP_ID,CCI.ENTR_SUR_NM,CCI.ENTR_GIV_NM,DATEDIFF(YEAR,CCL.CLI_BTH_DT,GETDATE()) AGE,
CG.CVG_FACE_AMT,CASE WHEN LEFT(CG.CVG_CSTAT_CD,1)='P' THEN 'PD' ELSE CG.CVG_CSTAT_CD END CVG_CSTAT_CD,CG.PLAN_ID,CVG_PREM_PAY_DUR,CG.CVG_APP_RECV_DT,
CASE WHEN LEFT(CG.PLAN_ID,1)='A' THEN CG.CVG_FACE_AMT*1.5 ELSE CG.CVG_FACE_AMT*CVG_PREM_PAY_DUR*0.5 END SAR,
CCAD.CLI_ADDR_LN_1_TXT,CCAD.CLI_ADDR_LN_2_TXT,CCAD.CLI_ADDR_LN_3_TXT,CCAD.CLI_CITY_NM_TXT,CC1.CLI_CNTCT_ID_TXT PHONE1,CC2.CLI_CNTCT_ID_TXT PHONE2,CEM.CLI_CNTCT_ID_TXT EMAIL,

CVL.POL_ID P_POL_ID,PO.PLAN_ID POPLAN_ID,PO.POL_CSTAT_CD POPOL_CSTAT_CD,
PP.POL_ID SPOL_ID,POS.PLAN_ID POSPLAN_ID,POS.POL_CSTAT_CD POSPOL_CSTAT_CD,SCGV.SUM_IN,SCGV.SUM_IN*1.5 SSAR,POS.POL_PREM_PAY_DUR TERM,POS.POL_APP_RECV_DT SPOL_APP_RECV_DT,POS.POL_REJ_REASN_CD,
CASE WHEN POS.POL_CSTAT_CD='1' THEN 'IF' WHEN POS.POL_CSTAT_CD='A' THEN 'CFI' WHEN LEFT(POS.POL_CSTAT_CD,1)='P' THEN 'PD' WHEN POS.POL_CSTAT_CD='B' THEN 'Lapse' ELSE
(CASE WHEN POS.POL_REJ_REASN_CD='PP' THEN 'POSTPONED' WHEN POS.POL_REJ_REASN_CD='NP' THEN 'REJECTED' WHEN POS.POL_REJ_REASN_CD='NT' THEN 'NTU' ELSE '' END) END STATUS_,

CB.BNK_ACCT_ID,CB.BNK_NM,CB.BNK_ACCT_HLDR_NM,
CASE WHEN P.POL_BILL_MODE_CD=1 THEN 'Monthly' WHEN P.POL_BILL_MODE_CD=3 THEN 'Quarterly' WHEN P.POL_BILL_MODE_CD=6 THEN 'Semi-Annual' WHEN P.POL_BILL_MODE_CD=12 THEN 'Annually' END POL_BILL_MODE_CD,
VA.SURNAME,VA.NAME2,VA.PARTY_ID,CSC_NAME,PARA1.DM_AV_DESC_TXT METHOD,P.POL_GRS_APREM_AMT,P.POL_MPREM_AMT,W.POL_AGT_SHR_PCT FROM #POL P INNER JOIN #POLC PC ON P.POL_ID=PC.POL_ID
INNER JOIN #CLI CL ON CL.CLI_ID=PC.CLI_ID
INNER JOIN #CIND CI ON CI.CLI_ID=CL.CLI_ID
INNER JOIN #POLW W ON P.POL_ID=W.POL_ID
INNER JOIN V_AGENT_INFO VA ON VA.PARTY_ID=W.AGT_ID
INNER JOIN #TCVGC CVL ON P.POL_ID=CVL.POL_ID
INNER JOIN #TCVG CG ON CG.POL_ID=CVL.POL_ID AND CG.CVG_NUM=CVL.CVG_NUM
INNER JOIN #CLI CCL ON CCL.CLI_ID=CVL.INSRD_CLI_ID
INNER JOIN #CIND CCI ON CCI.CLI_ID=CCL.CLI_ID
--INNER JOIN SGTM_BENE BE ON BE.POL_ID=P.POL_ID
LEFT JOIN (SELECT PC.POL_ID,PC.CLI_ID FROM #POL P INNER JOIN #POLC PC ON P.POL_ID=PC.POL_ID WHERE P.POL_CSTAT_CD IN ('A','B','H','R','T')) PP ON CVL.INSRD_CLI_ID=PP.CLI_ID
LEFT JOIN #CLIB CB ON PC.CLI_ID=CB.CLI_ID

LEFT JOIN #POL PO ON CVL.POL_ID=PO.POL_ID
LEFT JOIN #POL POS ON PP.POL_ID=POS.POL_ID
LEFT JOIN #EDIT HE ON CL.OCCP_ID=HE.ETBL_VALU_ID AND HE.ETBL_TYP_ID='OCCCD'
LEFT JOIN #EDIT HHE ON CCL.OCCP_ID=HHE.ETBL_VALU_ID AND HHE.ETBL_TYP_ID='OCCCD'
LEFT JOIN #TCLIA CAD ON CL.CLI_ID=CAD.CLI_ID
LEFT JOIN #TCLIA CCAD ON CCL.CLI_ID=CCAD.CLI_ID
LEFT JOIN #CINFOR CINFOR ON CL.CLI_ID=CINFOR.CLI_ID
LEFT JOIN #TCLIC C1 ON CL.CLI_ID=C1.CLI_ID AND C1.CLI_CNTCT_ID_CD='CP'
LEFT JOIN #TCLIC C2 ON CL.CLI_ID=C2.CLI_ID AND C2.CLI_CNTCT_ID_CD='HO'
LEFT JOIN #TCLIC EM ON CL.CLI_ID=EM.CLI_ID AND EM.CLI_CNTCT_ID_CD='EM'
LEFT JOIN #TCLIC CC1 ON CCL.CLI_ID=CC1.CLI_ID AND CC1.CLI_CNTCT_ID_CD='CP'
LEFT JOIN #TCLIC CC2 ON CCL.CLI_ID=CC2.CLI_ID AND CC2.CLI_CNTCT_ID_CD='HO'
LEFT JOIN #TCLIC CEM ON CCL.CLI_ID=CEM.CLI_ID AND CEM.CLI_CNTCT_ID_CD='EM'
LEFT JOIN (SELECT POL_ID,SUM(CVG_SUM_INS_AMT) SUM_IN FROM #TCVG GROUP BY POL_ID) SCGV ON PP.POL_ID=SCGV.POL_ID
LEFT JOIN SGTM_PARA_1 PARA1 ON P.POL_COLCT_MTHD_CD=PARA1.DM_AV_CD AND PARA1.DM_AV_TBL_CD='POL-COLCT-MTHD-CD'
LEFT JOIN (SELECT POL_CLI_ID FROM #TREQT WHERE POL_CLI_ID IN (SELECT POL_CLI_ID FROM #TREQT WHERE REQIR_ID IN ('JET')) GROUP BY POL_CLI_ID HAVING COUNT(REQIR_ID)=2) RR ON P.POL_ID=RR.POL_CLI_ID
WHERE P.POL_ID='001000104    '
