

CREATE PROC [dbo].[RPT_RISK_CLARIFICATION_UAT] 

	@START_DATE		DATE = NULL,
	@END_DATE		DATE = NULL
	
AS
	--DECLARE @START_DATE	DATE = '2020-09-14'
	--DECLARE @END_DATE	DATE = '2023-09-14'

	IF ISNULL(@START_DATE,'') = ''	SET @START_DATE = '2000-01-01'
	IF ISNULL(@END_DATE,'') = ''	SET @END_DATE = GETDATE()

	DROP TABLE IF EXISTS #AGT
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #POL
	DROP TABLE IF EXISTS #EDIT
	DROP TABLE IF EXISTS #TCLI
	DROP TABLE IF EXISTS #TCLII
	DROP TABLE IF EXISTS #PEPTBL
	DROP TABLE IF EXISTS #APEHIS

	SELECT * INTO #AGT FROM DLKHSTAGE..V_GET_AGENT_BASIC_LIVE
	SELECT ETBL_VALU_ID,ETBL_TYP_ID,ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #EDIT FROM DLKHSTAGE..SGTB_EDITTABLE WHERE CO_ID = 'CP' AND ETBL_LANG_CD = 'E'
		AND ETBL_TYP_ID IN ('PAYT','OCCCD','AGTLE','DV-AGT-STAT-CD','CSRC','BILL-MODE','PLAN','AGTLE','BTLOC')

	
	
	SELECT POL.*,POL_MPREM_AMT_HIS = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
		
	INTO #POL 
	FROM OPENQUERY(UAT7,
		'
			SELECT POL.POL_ID,POL.POL_INFC_DT,POL.POL_BILL_MODE_CD,
			POL.POL_BILL_TYP_CD
			,POL.POL_CSTAT_CD,POL.PLAN_ID,POL.POL_APP_FORM_ID
				,POL.POL_REISS_DT,POL.POL_MPREM_AMT,POL.POL_PREV_MPREM_AMT,POL.POL_ISS_EFF_DT,POL.POL_APP_RECV_DT
				,POL.POL_STAT_CHNG_DT,POL.POL_PD_TO_DT_NUM
				,POLC.CLI_ID
				,POL.POL_NOT,POL.APP_SUBMIT_CD,POLC.POL_UW_RMRKS
				,POL.POL_CASE_STAT_CD
				,POL.COLCT_MTHD_CD
				,POL.POL_RENW_MTHD_CD

			FROM KCAPXUT1.TPOL POL
			INNER JOIN KCAPXUT1.TPOLC POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = ''O''
			
		'
	) POL
	--LEFT JOIN DLKHSTAGE.dbo.V_GET_REMOTE_CASE_OF_EXIST_POLICY REMC ON POL.POL_ID = REMC.POL_ID
	LEFT JOIN DLKHSTAGE.dbo.V_GET_PREMIUM_AMT_POL_LAPSE POL0 ON POL.POL_ID = POL0.POL_ID -- ADD COLC_MTHD_CD,POL_RENW_MTHD_CD 05/03/2024

	SELECT POL.CLI_ID, APE = SUM(ISNULL(CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE 
		   POL.POL_MPREM_AMT END * 
		   (CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL.POL_BILL_MODE_CD AS INT) END),0) )
	INTO #APEHIS
	FROM OPENQUERY(UAT7,
		'
			SELECT POL.POL_ID,POL.POL_BILL_MODE_CD
			,POL.POL_CSTAT_CD,POL.PLAN_ID,POL.POL_APP_FORM_ID
			,POL.POL_MPREM_AMT,POL.POL_PREV_MPREM_AMT,POL.POL_ISS_EFF_DT,POL.POL_APP_RECV_DT
			,POLC.CLI_ID
			FROM KCAPXUT1.TPOL POL
			INNER JOIN KCAPXUT1.TPOLC POLC ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = ''O''
			WHERE POL.POL_CSTAT_CD NOT IN (''2'',''4'',''5'',''6'',''7'',''A'',''D'',''E'',''F'',''H'',''R'',''T'',''W'',''X'')
		'
	) POL
	LEFT JOIN DLKHSTAGE.dbo.V_GET_PREMIUM_AMT_POL_LAPSE POL0 ON POL.POL_ID = POL0.POL_ID 
	WHERE POL_APP_RECV_DT <= @END_DATE
	GROUP BY POL.CLI_ID

	-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT
		,#LAST_UPDT_NM = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM
	FROM OPENQUERY(UAT7,
	'	SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS
		FROM KCAPXUT1.TCLNM
	')

	--GET ONLY REQUIRED INFO OF CLINET_DOB & GENDER - TCLI
	SELECT CLI_ID,CLI_SEX_CD,CLI_BTH_DT,CLI_BTH_LOC_CD,OCCP_ID INTO #TCLI
	 FROM OPENQUERY (UAT7,
	'SELECT * FROM KCAPXUT1.TCLI
	');

	--GET ONLY REQUIRED INFO OF CLINET_ANNUAL INCOME - TCLII
	SELECT CLI_ID,CLI_EARN_INCM_AMT
		,#LAST_UPDT_NM = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	 INTO #TCLII
	 FROM OPENQUERY (UAT7,
	'SELECT * FROM KCAPXUT1.TCLII
	');

	--RETREIVE INFORMATION PEP FROM TBL MISRPTDB
	SELECT PO_ID,PO_PEP INTO #PEPTBL FROM [MISRPTDB].[dbo].[AML_RISK_CLARIFICATION];

	
	SELECT PO_NAME,PO_ID,MAX(APP_INPUT_DATE) APP_INPUT_DATE,GENDER,DOB,AGE,BIRTH_COUNTRY,CLASSIFICATIO_CNTRY,CLIENT_INCOME,OCCUPATION,DEF_CL_WORK
	, APE AS APE
	FROM(
	SELECT  --POL.POL_ID,
	((CLNM.ENTR_SUR_NM)) + ' ' + ((CLNM.ENTR_GIV_NM)) PO_NAME
	,PO_ID = POL.CLI_ID
	,APP_INPUT_DATE =	POL.POL_APP_RECV_DT
	,(CASE WHEN CLI.CLI_SEX_CD = 'M' THEN 'MALE' ELSE 'FEMALE' END) AS GENDER	
	,DOB = CLI.CLI_BTH_DT
	,AGE = YEAR(GETDATE()) - YEAR(CLI.CLI_BTH_DT)
	,BIRTH_COUNTRY = EDT.ETBL_DESC_TXT
	,(CASE WHEN EDT.ETBL_VALU_ID IN ('NKOR','IRAN','MM') then 'Blacklisted Country' else 'Not Blacklisted Country' end) CLASSIFICATIO_CNTRY
	,CLIENT_INCOME = CLII.CLI_EARN_INCM_AMT
	,OCCUPATION = OCCP.ETBL_DESC_TXT
	--,DEF_CL_WORK = 'Non-Pep'
	,DEF_CL_WORK = ISNULL(RTRIM(PEPTBL.PO_PEP),'Non-PEP')
	--,(CASE WHEN PAYT.ETBL_DESC_TXT = 'Single Premium' THEN 'Single Payment' ELSE 'Not Single Payment' END) AS METHOD_PAYMENT
	--,APE = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE 
	--	POL.POL_MPREM_AMT END * 
	--	(CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL.POL_BILL_MODE_CD AS INT) END)	-- APE/AFYP
	,APEHIS.APE AS APE
	FROM #POL POL
	--JOIN TO GET CLIENT INFORMATION

	LEFT JOIN #TCLNM CLNM ON CLNM.CLI_ID = POL.CLI_ID AND CLNM.#LAST_UPDT_NM =1
	LEFT JOIN #TCLI CLI ON CLI.CLI_ID = POL.CLI_ID
	LEFT JOIN #TCLII CLII ON CLII.CLI_ID = POL.CLI_ID AND CLII.#LAST_UPDT_NM = 1
	--JOIN TO GET DATA FROM EDIT
	LEFT JOIN #EDIT EDT ON EDT.ETBL_TYP_ID = 'BTLOC' AND EDT.ETBL_VALU_ID = CLI.CLI_BTH_LOC_CD
	LEFT JOIN #EDIT OCCP ON OCCP.ETBL_TYP_ID = 'OCCCD' AND  OCCP.ETBL_VALU_ID =  CLI.OCCP_ID
	LEFT JOIN #EDIT PAYT ON PAYT.ETBL_TYP_ID = 'PAYT' AND PAYT.ETBL_VALU_ID = POL.POL_BILL_TYP_CD

	--JOIN TO GET APE/FYP
	--LEFT JOIN DLKHSTAGE.DBO.V_GET_PREMIUM_AMT_POL_LAPSE POL0 ON POL.POL_ID = POL0.POL_ID
	LEFT JOIN #APEHIS APEHIS ON CLI.CLI_ID = APEHIS.CLI_ID
	--JOIN TO CHECK IF PEP
	LEFT JOIN #PEPTBL PEPTBL ON PEPTBL.PO_ID = POL.CLI_ID
	WHERE POL.POL_APP_RECV_DT BETWEEN @START_DATE AND @END_DATE 
	
	)MAI
	
	GROUP BY PO_NAME,PO_ID,GENDER,DOB,AGE,BIRTH_COUNTRY,CLASSIFICATIO_CNTRY,CLIENT_INCOME,OCCUPATION,DEF_CL_WORK,APE
	ORDER BY PO_ID
	
	--AND PO_ID='0000004792'
