CREATE PROC [dbo].[RPT_APPL_CASH] @STARTDATE DATE,@ENDDATE DATE
AS


	-- DECLARE	@STARTDATE	DATE = '2022-01-01'
	-- 		,@ENDDATE	DATE = '2022-04-01'

	DROP TABLE IF EXISTS #TACTH
	DROP TABLE IF EXISTS #TPHST
	DROP TABLE IF EXISTS #TPOL
	DROP TABLE IF EXISTS #TCOLL
	DROP TABLE IF EXISTS #COL

	-- COMBINE DATA BETWEEN TABLE TACTH AND TACTX
	SELECT * INTO #TACTH FROM OPENQUERY(UAT7,
	'	SELECT POL_ID
			,ACCT_HIST_PRCES_DT
			,ACCT_HIST_PRCES_DT ACCT_HIST_PST_DT
			,USER_ID
			,ACCT_BASE_ID
			,ACCT_HIST_GEN_ID
			,ACCT_HIST_AMT
			,BUS_FCN_ID
		FROM KCAPXUAT.TACTH
		WHERE BUS_FCN_ID NOT IN (''0222'') AND ACCT_BASE_ID =''249800''
			OR (ACCT_BASE_ID = ''102300'' AND BUS_FCN_ID IN (''0462'',''0460''))

		UNION ALL

		SELECT POL_ID
			,ACCT_TRXN_PRCES_DT
			,ACCT_TRXN_GR_TS
			,USER_ID
			,ACCT_BASE_ID
			,ACCT_TRXN_GEN_ID
			,ACCT_TRXN_AMT
			,BUS_FCN_ID
		FROM KCAPXUAT.TACTX
		WHERE BUS_FCN_ID NOT IN (''0222'') AND ACCT_BASE_ID =''249800''
			OR (ACCT_BASE_ID = ''102300'' AND BUS_FCN_ID IN (''0462'',''0460''))
	')

	-- POLICY CHANGE WITH STATUS 'ACTIVE' FOR ACTIVITY 1082
	SELECT * INTO #TPHST FROM OPENQUERY(UAT7,
	'	SELECT POL_ID,POL_ACTV_TYP_ID,MIN(PREV_UPDT_TS) PREV_UPDT_TS
		FROM KCAPXUAT.TPHST
		WHERE POL_ACTV_TYP_ID = ''1082'' AND PCHST_STAT_CD = ''A''
		GROUP BY POL_ID,POL_ACTV_TYP_ID
	')

	-- GET SOME COLUMNS ONLY FROM POLICY TO INCREASE PERFORMANCE
	SELECT * INTO #TPOL FROM OPENQUERY(UAT7,
	'	SELECT POL.POL_ID,POL.POL_APP_FORM_ID,POL.POL_MPREM_AMT,POL.POL_INFC_DT,POL.POL_BILL_MODE_CD,POL.POL_CSTAT_CD
			,POLW.AGT_ID,AGT.AGT_DISB_CHNL
			,RTRIM(AGCH.ETBL_DESC_TXT) AS AGT_DISB_CHNL_DESC
		FROM KCAPXUAT.TPOL POL
		LEFT JOIN KCAPXUAT.TPOLW POLW ON POL.POL_ID = POLW.POL_ID
		LEFT JOIN KCAPXUAT.TAG AGT ON POLW.AGT_ID = AGT.AGT_ID
		LEFT JOIN KCAPXUAT.TEDIT AGCH ON AGT.AGT_DISB_CHNL = AGCH.ETBL_VALU_ID AND AGCH.ETBL_TYP_ID=''DCHNL'' AND AGCH.ETBL_LANG_CD = ''E'' AND AGCH.CO_ID = ''CP''
	')

	-- JOIN AND GET SOME COLUMNS FROM TCOLL AND TCOLD
	SELECT * INTO #TCOLL FROM OPENQUERY(UAT7,
	'	SELECT 	COLL.COLCT_MICR_NUM
			,COLL.COLCT_DOC_DT
			,COLL.COLCT_CLR_REJ_DT
			,COLL.COLCT_TOT_AMT
			,COLL.COLCT_RCPT_NUM
			,COLL.COLCT_PREM_SRCE
			,COLL.COLCT_REMARK
			,COLCT_REF_NUM
			,COLD.COLCT_EFF_DT
			,COLD.POL_ID
			,COLD.COLCT_PREM_AMT
			,COLD.COLCT_APL_AMT
		FROM KCAPXUAT.TCOLL COLL
		INNER JOIN KCAPXUAT.TCOLD COLD ON COLL.COLCT_MICR_NUM = COLD.COLCT_MICR_NUM AND COLL.COLCT_ID_NUM = COLD.COLCT_ID_NUM
	')

	SELECT DISTINCT GETDATE() AS  REPORT_DT
		,POL.POL_ID
		,POL.POL_APP_FORM_ID
		,POL.POL_MPREM_AMT
		,POL.POL_INFC_DT
		,FREQUENCY = RTRIM(DMAV.DM_AV_DESC_TXT)
		,ACTH.ACCT_HIST_PRCES_DT
		,ACTH.ACCT_HIST_PST_DT
		,TYPE_ = CASE WHEN ACTH.ACCT_HIST_AMT<0 THEN 'REVERSED' ELSE 'APPLIED' END
		,ACTH.USER_ID
		,APPLIED_AMOUNT = ACTH.ACCT_HIST_AMT
		,ACTH.ACCT_BASE_ID
		,ACTH.BUS_FCN_ID
		,COLLECT_TYPE = CASE WHEN PHST.PREV_UPDT_TS IS NULL THEN 'N' ELSE (CASE WHEN (ACTH.ACCT_HIST_PRCES_DT)<=(PHST.PREV_UPDT_TS) THEN 'N' ELSE 'R' END) END
		,COLL.COLCT_RCPT_NUM
		,COLLEC_SRCE = PA.ETBL_DESC_TXT
		,COLL.COLCT_REF_NUM
		,COLL.COLCT_DOC_DT
		,COLL.COLCT_EFF_DT
		,COLCT_MICR_NUM = RIGHT('000000000'+ CONVERT(VARCHAR(9), COLL.COLCT_MICR_NUM),9)
		,COLL.COLCT_REMARK
		,COLL.COLCT_TOT_AMT
		,POL.AGT_DISB_CHNL_DESC
	FROM #TPOL POL
	LEFT JOIN #TPHST PHST ON POL.POL_ID = PHST.POL_ID
	LEFT JOIN #TACTH ACTH ON POL.POL_ID = ACTH.POL_ID
	LEFT JOIN #TCOLL COLL ON ACTH.POL_ID = COLL.POL_ID AND ACTH.ACCT_HIST_PRCES_DT = COLL.COLCT_CLR_REJ_DT AND ACTH.ACCT_HIST_AMT = COLL.COLCT_TOT_AMT
	LEFT JOIN SGTB_EDITTABLE PA ON PA.ETBL_VALU_ID = COLL.COLCT_PREM_SRCE AND PA.ETBL_TYP_ID = 'PSRC' AND PA.ETBL_LANG_CD = 'E' AND PA.CO_ID = 'CP'
	LEFT JOIN SGTM_PARA_1 DMAV ON DMAV.DM_AV_TBL_CD = 'POL-BILL-MODE-CD' AND DMAV.DM_AV_CD = POL.POL_BILL_MODE_CD AND DMAV.DM_AV_DESC_LANG_CD = 'E' AND DMAV.CO_ID = 'CP'
	WHERE CAST(ACTH.ACCT_HIST_PRCES_DT AS DATE) BETWEEN  @STARTDATE AND @ENDDATE
