CREATE PROC [dbo].[RPT_POL_SUS]
AS
 IF OBJECT_ID('tempdb..#TPOL') IS NOT NULL
  DROP TABLE #TPOL
SELECT * INTO #TPOL FROM    OPENQUERY(UAT7,'SELECT * FROM KCAPXPR1.TPOL')
SELECT POL_ID,E.ETBL_DESC_TXT PLAN_NAME,POL_PREM_SUSP_DT,POL_PREM_SUSP_AMT,DATEDIFF(DAY,POL_PREM_SUSP_DT,GETDATE()) SUS_DURATION,
POL_MISC_SUSP_DT,POL_MISC_SUSP_AMT,CASE WHEN POL_PD_TO_DT_NUM='0000-00-00' THEN NULL ELSE CAST(DBO.ConvertDate(POL_PD_TO_DT_NUM) AS DATE) END POL_PD_TO_DT_NUM,DM_AV_DESC_TXT POL_STAT,P.POL_INFC_DT,
CASE WHEN POL_BILL_MODE_CD=3 THEN 'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Month' WHEN POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE POL_BILL_MODE_CD END PRE_MODE FROM #TPOL P
LEFT JOIN SGTB_EDITTABLE E ON E.ETBL_VALU_ID=PLAN_ID AND E.ETBL_TYP_ID='PLAN' AND E.CO_ID='CP' AND E.ETBL_LANG_CD='E'
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' and PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
WHERE POL_PREM_SUSP_AMT>0 OR POL_MISC_SUSP_AMT>0
