
CREATE PROCEDURE [dbo].[RPT_RISK_LEVEL_CLA_BYPOID] (
@PO_ID VARCHAR(20)
,@RISK_LEVEL INT OUTPUT
)
AS

BEGIN

DROP TABLE IF EXISTS #CLIRISK
DROP TABLE IF EXISTS #SCORE_TBL
---CREATE TEMP TABLE TO STORE DATA GENERATED FROM STORE PROCEDURE NO NEED TO CREATE TABLE----
CREATE TABLE #CLIRISK (
	TMP_PONAME VARCHAR(MAX),
	TMP_POID VARCHAR(20),
	TMP_APP_INP_DATE DATE,
	TMP_GENDER VARCHAR(10),
	TMP_DOB DATE,
	TMP_AGE INT,
	TMP_BIRTH_COUNTRY VARCHAR(MAX),
	TMP_CLA_CNTRY VARCHAR(MAX),
	TMP_CLI_INCOME DECIMAL,
	TMP_CLI_OCCP VARCHAR(MAX),
	TMP_PEP VARCHAR(20),
	TMP_APE DECIMAL
)
-------------INSERT DATA GENERATED FROM STORE PROCEDURE TO CHECK THE LEVEL OF RISK------
INSERT INTO #CLIRISK 
EXEC RPT_RISK_CLARIFICATION_POID @START_DATE = NULL, @END_DATE = NULL,@POID = @PO_ID 

----DECLARE VARIBALEFOR USING CONDITION TO INDETIFY RISK LEVEL-----
DECLARE @CLA_PEP VARCHAR(20)
DECLARE @CLA_CLA_CNTRY VARCHAR(MAX)
DECLARE @CLA_CLI_INCOME DECIMAL 
DECLARE @CLA_APE DECIMAL
DECLARE @TOTAL_RISK_LVL INT

SET @TOTAL_RISK_LVL = 0

SELECT @CLA_PEP = CLRISK.TMP_PEP
	   ,@CLA_CLA_CNTRY = CLRISK.TMP_CLA_CNTRY
	   ,@CLA_CLI_INCOME = CLRISK.TMP_CLI_INCOME
	   ,@CLA_APE = CLRISK.TMP_APE
FROM #CLIRISK CLRISK

IF @CLA_PEP <> 'Non-PEP'    ----PEP SCORE
BEGIN
	SET @TOTAL_RISK_LVL = @TOTAL_RISK_LVL + 5
END
ELSE
BEGIN
    SET @TOTAL_RISK_LVL = @TOTAL_RISK_LVL + 0
END
IF @CLA_CLI_INCOME >= 10000   ----CLI INCOME SCORE
BEGIN
	SET @TOTAL_RISK_LVL = @TOTAL_RISK_LVL + 5
END
ELSE
BEGIN
    SET @TOTAL_RISK_LVL = @TOTAL_RISK_LVL + 0
END
IF @CLA_APE >= 10000   ----APE SCORE
BEGIN
	SET @TOTAL_RISK_LVL = @TOTAL_RISK_LVL + 5
END
ELSE
BEGIN
    SET @TOTAL_RISK_LVL = @TOTAL_RISK_LVL + 0
END
IF @CLA_CLA_CNTRY <> 'Not Blacklisted Country'    ----BIRTH COUNTRY SCORE
BEGIN
	SET @TOTAL_RISK_LVL = @TOTAL_RISK_LVL + 10
END
ELSE
BEGIN
    SET @TOTAL_RISK_LVL = @TOTAL_RISK_LVL + 0
END

SET @RISK_LEVEL = @TOTAL_RISK_LVL 
--SELECT @TOTAL_RISK_LVL

END
