
CREATE PROC [dbo].[RPT_BBM_SUMMARY_POL_BY_MONTH_TEST]
AS
--- CHANGE 2023/05/22: REPLACE TABLE MD.AGENT TO SGTM_AGENT_DETAIL SINCE MD.AGENT DATA IS NOT SYNC LATEST ---
	DECLARE
		@START_DATE	DATE = DATEADD(DAY,-DAY(GETDATE()) - 1, GETDATE())
		,@END_DATE	DATE = CONVERT(DATE,GETDATE())
		-- @START_DATE DATE = '2024-06-01'
		-- ,@END_DATE DATE = '2024-06-30'

	DROP TABLE IF EXISTS #POL_TEMP
	DROP TABLE IF EXISTS #POL
	DROP TABLE IF EXISTS #TCLNM
	DROP TABLE IF EXISTS #POL_AMT
	DROP TABLE IF EXISTS #AGENT
	DROP TABLE IF EXISTS #SUM_TYP
	DROP TABLE IF EXISTS #REQT
	DROP TABLE IF EXISTS #NJET
	DROP TABLE IF EXISTS #TEMP_DATA

	-- GET ONLY REQUIRED DATA FROM POLICY - TPOL
	SELECT * INTO #POL FROM OPENQUERY(UAT7,'
		SELECT POL.POL_ID,POL.POL_APP_RECV_DT,POL.POL_INFC_DT,POL.POL_STAT_CHNG_DT,POL.POL_CSTAT_CD
			,POL.POL_BILL_MODE_CD,POL.POL_MPREM_AMT,POLW.AGT_ID
		FROM KCAPXUT1.TPOL POL
		LEFT JOIN KCAPXUT1.TPOLW POLW ON POL.POL_ID = POLW.POL_ID
	')

	SELECT REQT.*, NJET.GRP_CD
	INTO #REQT FROM OPENQUERY(UAT7,'
		SELECT POL_CLI_ID,REQIR_ID,CPREQ_STAT_CD FROM KCAPXUT1.TREQT WHERE CPREQ_POL_CLI_CD = ''P'' AND CPREQ_STAT_CD IN (''ORD'')
	') REQT INNER JOIN V_GET_NON_JET_AND_INCOMPLETE_CODE NJET ON REQT.REQIR_ID = NJET.REQIR_ID

	SELECT DISTINCT POL_CLI_ID,GRP_CD INTO #NJET  FROM #REQT WHERE GRP_CD = 'COL' 
	DELETE FROM #REQT WHERE POL_CLI_ID IN (SELECT POL_CLI_ID FROM #NJET)
	INSERT INTO #NJET SELECT DISTINCT POL_CLI_ID,GRP_CD FROM #REQT WHERE GRP_CD = 'ME'
	DELETE FROM #REQT WHERE POL_CLI_ID IN (SELECT POL_CLI_ID FROM #NJET)
	INSERT INTO #NJET SELECT DISTINCT POL_CLI_ID,GRP_CD FROM #REQT WHERE GRP_CD = 'IA'
	DELETE FROM #REQT WHERE POL_CLI_ID IN (SELECT POL_CLI_ID FROM #NJET)
	INSERT INTO #NJET SELECT DISTINCT POL_CLI_ID,GRP_CD FROM #REQT WHERE GRP_CD = 'OTR'

	-- GET PREMIUM AMOUNT FOR ANY POLICIES WITH STATUS LAPSED OR REJECTED
	SELECT * INTO #POL_AMT FROM V_GET_PREMIUM_AMT_POL_LAPSE

	-- GET ONLY REQUIRED INFO OF CLIENT NAME - TCLNM
	SELECT CLI_ID,ENTR_SUR_NM = RTRIM(ENTR_SUR_NM),ENTR_GIV_NM = RTRIM(ENTR_GIV_NM),CLI_INDV_EFF_DT
		, #LAST_UPDT = ROW_NUMBER() OVER (PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC)
	INTO #TCLNM
	FROM OPENQUERY(UAT7, 'SELECT CLI_ID,ENTR_SUR_NM,ENTR_GIV_NM,CLI_INDV_EFF_DT,PREV_UPDT_TS FROM KCAPXUT1.TCLNM')

	SELECT * INTO #AGENT FROM OPENQUERY([10.116.17.220],'
		SELECT AG.AGENT_TYPE, AG.CHANNEL, AG.AGENT_NAME, CAST(AG.AGENT_CODE AS VARCHAR) AGENT_CODE, AG.REPORTING_TO_CODE MANAGER_CODE, O.BD_MANAGER_NAME MANAGER_NAME, O.ORG_PARENT_NAME BANK_NAME
		FROM [DMS_UAT]..DMS_AGENT_DETAIL AG
		INNER JOIN [DMS_UAT]..DMS_ORGANIZATION O ON O.SALE_SUPPORT LIKE CONCAT(''%'', AG.AGENT_CODE,''%'') AND O.ORG_TYPE = ''BR''
		WHERE AG.CHANNEL = ''BA''
	') AG

	-- PREPARE RESULT
	SELECT POL.POL_ID
		,POL.POL_APP_RECV_DT
		,POL.POL_INFC_DT
		,CFI_DATE = CASE WHEN POL.POL_CSTAT_CD = 'A' THEN POL.POL_STAT_CHNG_DT ELSE NULL END
		,POL.POL_CSTAT_CD
		,POL.POL_BILL_MODE_CD
		,POL_MPREM_AMT = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POLM.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END
        ,CASE 
            WHEN POL.POL_MPREM_AMT = 0
                THEN POLM.POL_MPREM_AMT
                ELSE POL.POL_MPREM_AMT
        END * (
            CASE 
                WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0
                THEN 1
                ELSE 12 / CAST(POL.POL_BILL_MODE_CD AS INT)
            END
        ) AS AFYP

		,BBM_NAME = AGT.MANAGER_NAME
		,AGENT_ID = AGT.AGENT_CODE
		,BANK_NAME = AGT.BANK_NAME
		,NJET.GRP_CD
	INTO #POL_TEMP
	FROM #POL POL
	LEFT JOIN #POL_AMT POLM ON POL.POL_ID = POLM.POL_ID
	LEFT JOIN #AGENT AGT ON POL.AGT_ID = AGT.AGENT_CODE
	LEFT JOIN #NJET NJET ON NJET.POL_CLI_ID = POL.POL_ID
	WHERE AGT.CHANNEL = 'BA'
	
	SELECT DISTINCT
		BBM_NAME = BBM.BD_MANAGER_NAME
		,BANK_NAME = BBM.ORG_PARENT_NAME
		,TARGET_COUNT = ISNULL(TRG.IssuanceCount, 0)
		,TARGET_FYP = ISNULL(TRG.IssuanceFYP, 0)
		,SUBMISSION_FYP = ISNULL(SUB.FYP, 0)
		,SUBMISSION_COUNT = ISNULL(SUB.TOTAL_CASE, 0)
		,UW_FYP = ISNULL(UW.FYP, 0)
		,UW_COUNT = ISNULL(UW.TOTAL_CASE, 0) 
		,ISG_FYP = ISNULL(Gross.FYP, 0)
		,ISG_COUNT = ISNULL(Gross.TOTAL_CASE, 0)
		,CAN_FYP = ISNULL(Cancell.FYP, 0)
		,CAN_COUNT = ISNULL(Cancell.TOTAL_CASE, 0)
		,Actual_FYP = ISNULL(Actual.FYP, 0)
		,Actual_COUNT = ISNULL(Actual.TOTAL_CASE, 0)
	INTO #TEMP_DATA
	FROM DLKHSTAGE..DMS_ORGANIZATION BBM
		LEFT JOIN MISRPTDB.cfg.BBMTarget TRG 
            ON TRG.[Year]=YEAR(@START_DATE) 
            AND TRG.[Month]=MONTH(@START_DATE) 
            AND TRG.AgentId=BBM.[BD_MANAGER_CODE]
		
		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP ,TOTAL_CASE = COUNT(*) ,POL.AGENT_ID
			FROM #POL_TEMP POL WHERE POL.POL_APP_RECV_DT BETWEEN @START_DATE AND @END_DATE 
			GROUP BY POL.AGENT_ID
		) SUB ON SUB.AGENT_ID =  BBM.BD_MANAGER_CODE -- Submissions

		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP, TOTAL_CASE=COUNT(*), POL.AGENT_ID
			FROM #POL_TEMP POL
			WHERE LEFT(POL.POL_CSTAT_CD, 1) IN ('P')
			GROUP BY POL.AGENT_ID
		) UW ON UW.AGENT_ID =  BBM.BD_MANAGER_CODE -- UW In Progress
		
		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP, TOTAL_CASE=COUNT(*), POL.AGENT_ID
			FROM #POL_TEMP POL
			WHERE POL.POL_INFC_DT BETWEEN @START_DATE AND @END_DATE AND LEFT(POL.POL_CSTAT_CD, 1) <> 'P' --IN ('1','2','3')
			GROUP BY POL.AGENT_ID
		) Gross ON Gross.AGENT_ID =  BBM.BD_MANAGER_CODE -- Issuance (gross)
		
		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP, TOTAL_CASE=COUNT(*), POL.AGENT_ID
			FROM #POL_TEMP POL
			WHERE POL.CFI_DATE BETWEEN @START_DATE AND @END_DATE AND POL.POL_CSTAT_CD = 'A'
			GROUP BY POL.AGENT_ID
		) Cancell ON Cancell.AGENT_ID =  BBM.BD_MANAGER_CODE -- Cancellations (CFI)
		
		LEFT JOIN (
			SELECT SUM(POL.POL_MPREM_AMT) FYP, TOTAL_CASE=COUNT(*), POL.AGENT_ID
			FROM #POL_TEMP POL
			WHERE POL.POL_INFC_DT BETWEEN @START_DATE AND @END_DATE AND LEFT(POL.POL_CSTAT_CD, 1) <> 'P'
			GROUP BY POL.AGENT_ID
		) Actual ON Actual.AGENT_ID =  BBM.BD_MANAGER_CODE -- Actual Issuance (net)

	WHERE BBM.BD_MANAGER_CODE IS NOT NULL
	AND BBM.ORG_TYPE = 'BR'
    
    ----
    SELECT  ORDER_NO = 2, SUMMARY_BY = 'Submissions' 
	INTO #SUM_TYP
		UNION SELECT ORDER_NO = 1, SUMMARY_BY = 'Target'
		UNION SELECT ORDER_NO = 3, SUMMARY_BY = 'UW In Progress'
		UNION SELECT ORDER_NO = 4, SUMMARY_BY = 'Issuance (gross)'
		UNION SELECT ORDER_NO = 5, SUMMARY_BY = 'Cancellations (CFI)'
		UNION SELECT ORDER_NO = 6, SUMMARY_BY = 'Actual Issuance (net)'
		UNION SELECT ORDER_NO = 7, SUMMARY_BY = 'Shortfall'
		UNION SELECT ORDER_NO = 8, SUMMARY_BY = 'Arch%'

	SELECT
		POL.ORDER_NO,
		POL.FYP,
		POL.TOTAL_CASE,
		POL.AGT_LDR_SUR_NM,
		POL.AGT_MGR_SUR_NM,
		STYP.SUMMARY_BY
	FROM (
		SELECT ORDER_NO = 1, -- Target
            FYP = POL.TARGET_FYP,
			TOTAL_CASE = POL.TARGET_COUNT,
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.TARGET_COUNT, POL.TARGET_FYP

		UNION ALL SELECT ORDER_NO = 2, --Submissions
            FYP = SUM(POL.SUBMISSION_FYP),
			TOTAL_CASE = SUM(POL.SUBMISSION_COUNT),
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.TARGET_COUNT, POL.TARGET_FYP

		UNION ALL SELECT ORDER_NO = 3, --UW In Progress
            FYP = SUM(POL.UW_FYP),
			TOTAL_CASE = SUM(POL.UW_COUNT),
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.TARGET_COUNT, POL.TARGET_FYP

		UNION ALL SELECT ORDER_NO = 4, --Issuance (gross)
            FYP = SUM(POL.ISG_FYP),
			TOTAL_CASE = SUM(POL.ISG_COUNT),
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.TARGET_COUNT, POL.TARGET_FYP

		UNION ALL SELECT ORDER_NO = 5, --Cancellations (CFI)
            FYP = SUM(POL.CAN_FYP),
			TOTAL_CASE = SUM(POL.CAN_COUNT),
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.TARGET_COUNT, POL.TARGET_FYP

		UNION ALL SELECT ORDER_NO = 6,--Actual Issuance (net)
            FYP = SUM(POL.ISG_FYP) - SUM(POL.CAN_FYP), --
				-- SUM(POL.Actual_FYP) - SUM(ISNULL(POL.CAN_FYP, 0)),
			TOTAL_CASE = SUM(POL.ISG_COUNT) - SUM(POL.CAN_COUNT), -- 02-21-2023
				--SUM(POL.Actual_COUNT) -- SUM(ISNULL(POL.CAN_COUNT, 0)),

			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.TARGET_COUNT, POL.TARGET_FYP

		UNION ALL SELECT ORDER_NO = 7, --Shortfall
            FYP = CONVERT(DECIMAL(10, 2), 
				CASE WHEN POL.TARGET_FYP > 0
					--THEN (SUM(POL.TARGET_FYP) - SUM(POL.Actual_FYP))
					--THEN SUM(POL.Actual_FYP) - SUM(POL.TARGET_FYP) 
					THEN SUM(POL.ISG_FYP) - SUM(POL.CAN_FYP) - SUM(POL.TARGET_FYP) -- SHORTFALL = ACT NET - TARGET

					ELSE 0
				END
			),
			TOTAL_CASE = POL.TARGET_COUNT,
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.TARGET_COUNT, POL.TARGET_FYP

		UNION ALL SELECT ORDER_NO = 8,
            FYP = CONVERT(DECIMAL(10, 2), 
				CASE WHEN POL.TARGET_FYP > 0
					THEN SUM(POL.ISG_FYP) - SUM(POL.CAN_FYP)
						--(SUM(POL.TARGET_FYP) - SUM(POL.Actual_FYP))
					ELSE 0
				END
			),
			TOTAL_CASE = POL.TARGET_FYP,
			AGT_LDR_SUR_NM = POL.BANK_NAME,
			AGT_MGR_SUR_NM = POL.BBM_NAME
		FROM #TEMP_DATA POL GROUP BY POL.BANK_NAME, POL.BBM_NAME, POL.TARGET_COUNT, POL.TARGET_FYP

	) POL
	RIGHT JOIN #SUM_TYP STYP 
		ON POL.ORDER_NO = STYP.ORDER_NO

	ORDER BY
	   CASE WHEN POL.AGT_LDR_SUR_NM = 'VATTANAC' THEN 0
			WHEN POL.AGT_LDR_SUR_NM = 'SACOM' THEN 1
			WHEN POL.AGT_LDR_SUR_NM = 'AMK' THEN 2
			WHEN POL.AGT_LDR_SUR_NM = 'RHB' THEN 3
	   END

DROP TABLE IF EXISTS #POL_TEMP
DROP TABLE IF EXISTS #POL
DROP TABLE IF EXISTS #TCLNM
DROP TABLE IF EXISTS #POL_AMT
DROP TABLE IF EXISTS #AGENT
DROP TABLE IF EXISTS #SUM_TYP
DROP TABLE IF EXISTS #REQT
DROP TABLE IF EXISTS #NJET
DROP TABLE IF EXISTS #TEMP_DATA
