CREATE PROC RPT_COVER_SHEET_CHCK 
@CLI_ID VARCHAR(200),@GIV VARCHAR(200)
,@SUR VARCHAR(200),@ID VARCHAR(200),@SEX VARCHAR(100),@DOB DATE,@ADD1 VARCHAR(200),@COMMUNE VARCHAR(200),@DISTRICT VARCHAR(200),@CITY VARCHAR(200),@PHONE VARCHAR(200)
AS
SELECT DISTINCT TOP 1 CL.CLI_ID,IND.ENTR_SUR_NM,IND.ENTR_GIV_NM,CLI_CIN_NUM,CLI_SEX_CD,CLI_BTH_DT,C1.CLI_CNTCT_ID_TXT,CA.CLI_ADDR_LN_1_TXT,CMU.ETBL_DESC_TXT COMMUNE,DIS.ETBL_DESC_TXT DISTRICT,CIT.ETBL_DESC_TXT CITY FROM SGTB_POLICY P INNER JOIN SGTB_POLICY_CLIENT PC ON P.POL_ID=PC.POL_ID
INNER JOIN SGTM_CLIENT CL ON CL.CLI_ID=PC.CLI_ID
INNER JOIN DLKHDIM..DIM_CLIENT_IND IND ON PC.CLI_ID=IND.CLI_ID AND IND.IS_CURRENT=1
LEFT JOIN SGTM_CLIENT_ADD CA ON CA.CLI_ID=CL.CLI_ID
LEFT JOIN SGTM_CLIENT_CONTACT C1 ON PC.CLI_ID=C1.CLI_ID AND C1.CLI_CNTCT_ID_CD='MO'
LEFT JOIN SGTB_EDITTABLE CMU ON CMU.ETBL_LANG_CD='E' AND CMU.ETBL_TYP_ID='CTYPC' AND  CA.CLI_ADDR_CNTY_CD=CMU.ETBL_VALU_ID AND CMU.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE DIS ON DIS.ETBL_LANG_CD='E' AND DIS.ETBL_TYP_ID='MCPCD' AND  CA.CLI_ADDR_MUN_CD=DIS.ETBL_VALU_ID AND DIS.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE CIT ON CIT.ETBL_LANG_CD='E' AND CIT.ETBL_TYP_ID='CLOC' AND  CA.CLI_CRNT_LOC_CD=CIT.ETBL_VALU_ID AND CIT.CO_ID='CP'
WHERE (CL.CLI_CIN_NUM=@ID) 
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND CLI_SEX_CD=@SEX)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND CLI_ADDR_LN_1_TXT=@ADD1 AND CMU.ETBL_DESC_TXT=@COMMUNE AND DIS.ETBL_DESC_TXT=@DISTRICT AND CIT.ETBL_DESC_TXT=@CITY)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_SEX_CD=@SEX AND CLI_ADDR_LN_1_TXT=@ADD1 AND CMU.ETBL_DESC_TXT=@COMMUNE AND DIS.ETBL_DESC_TXT=@DISTRICT AND CIT.ETBL_DESC_TXT=@CITY)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_BTH_DT=@DOB AND C1.CLI_CNTCT_ID_TXT=@PHONE)
OR (IND.ENTR_SUR_NM=@SUR AND IND.ENTR_GIV_NM=@GIV AND CLI_SEX_CD=@SEX AND C1.CLI_CNTCT_ID_TXT=@PHONE)
