
CREATE PROCEDURE [dbo].[RPT_UW_REPORT] @STAT_DATE DATE, @END_DATE DATE AS 

--DECLARE  @STAT_DATE DATE = '2024-8-01'
--DECLARE @END_DATE DATE = '2024-8-23'

DROP TABLE IF EXISTS	#TREQT
DROP TABLE IF EXISTS    #TCLNM
DROP TABLE IF EXISTS	#TCVG
DROP TABLE IF EXISTS    #UWG
DROP TABLE IF EXISTS    #ME
DROP TABLE IF EXISTS    #ALI
DROP TABLE IF EXISTS    #ALI1
DROP TABLE IF EXISTS    #ALI2

SELECT * INTO #UWG FROM OPENQUERY(UAT7, '
SELECT S.POL_ID,S.UWG_SUMM_TXT,S.UWG_CREAT_USER_ID,S.UWG_CREAT_DT,S.UWG_UPDATE_DT,S.UWG_SEQ_NUM,S.PREV_UPDT_USER_ID,
P.UWG_USER_1_ID, P.UWG_DECID_1_DT, P.UWG_USER_2_ID, P.UWG_DECID_2_DT, P.UWG_SUMM_CSTAT_1_CD,P.UWG_SUMM_CSTAT_2_CD, 
P.UWG_SUMM_1_TXT, P.UWG_SUMM_2_TXT,
D.DM_AV_MODEL_TXT UWG_SUMM_CSTAT_1_DESC ,D1.DM_AV_MODEL_TXT UWG_SUMM_CSTAT_2_DESC
FROM KCAPXUAT.TZUWS S
LEFT JOIN KCAPXUAT.TZUWP P ON P.POL_ID = S.POL_ID
LEFT JOIN KCAPXUAT.TDMAV D ON D.DM_AV_CD = P.UWG_SUMM_CSTAT_1_CD AND D.DM_AV_TBL_CD = ''UWG-SUMM-CSTAT-CD''
LEFT JOIN KCAPXUAT.TDMAV D1 ON D1.DM_AV_CD = P.UWG_SUMM_CSTAT_2_CD AND D1.DM_AV_TBL_CD = ''UWG-SUMM-CSTAT-CD''
')

SELECT * INTO #TCVG  FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TCVGC')

SELECT * INTO #TCLNM FROM OPENQUERY(UAT7, ' SELECT CLI_ID, ENTR_SUR_NM, ENTR_GIV_NM, CLI_INDV_EFF_DT, PREV_UPDT_TS FROM KCAPXUAT.TCLNM') AS CLNM;

SELECT REQT.*, NJET.GRP_CD, NJET.NON_JET_STAT_CD INTO #TREQT FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TREQT WHERE CPREQ_POL_CLI_CD = ''P'' ') REQT 
INNER JOIN V_GET_NON_JET_AND_INCOMPLETE_CODE NJET ON REQT.REQIR_ID = NJET.REQIR_ID  

SELECT * INTO #ME  FROM (SELECT *  FROM #TREQT WHERE GRP_CD = 'ME' ) ME

SELECT  DISTINCT POLC.POL_ID,POLC.CLI_ID,ALIID1.INSRD_CLI_ID,ALNAME1.ENTR_SUR_NM,ALNAME1.ENTR_GIV_NM,ALNAME1.PREV_UPDT_TS INTO #ALI FROM SGTB_POLICY_CLIENT POLC
LEFT JOIN #TCVG ALIID1 ON ALIID1.POL_ID = POLC.POL_ID
LEFT JOIN #TCLNM ALNAME1 ON ALNAME1.CLI_ID = POLC.CLI_ID

SELECT * INTO #ALI1 FROM (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY PREV_UPDT_TS) AS ROW#,*  FROM #ALI) ALI1
SELECT * INTO #ALI2 FROM (SELECT ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY PREV_UPDT_TS) AS ROW#,*  FROM #ALI) ALI2

SELECT DISTINCT POL.POL_ID,
RTRIM(POL.POL_APP_FORM_ID) APPLICATION_NO,
POLC.CLI_ID PO_ID, 
CONCAT(RTRIM(PONM.ENTR_SUR_NM),' ', RTRIM(PONM.ENTR_GIV_NM)) PO_NAME,
BLI.INSRD_CLI_ID BLI_ID,
CONCAT(RTRIM(BLNM.ENTR_SUR_NM),' ', RTRIM(BLNM.ENTR_GIV_NM)) BLI_NAME
,ALI1_ID  = ALI1.INSRD_CLI_ID
,ALI1_Name =RTRIM(ALI1.ENTR_SUR_NM)+ ' '+ RTRIM(ALI1.ENTR_SUR_NM)
,ALI2_ID = ALI2.INSRD_CLI_ID
,ALI2_Name = RTRIM(ALI2.ENTR_SUR_NM)+ ' '+ RTRIM(ALI2.ENTR_SUR_NM)
,POL_COMM_DT =POL.POL_APP_RECV_DT
,POL.POL_ISS_EFF_DT ISSUED_DATE
,POL.POL_REISS_DT REISS_DATE 
,Main_Product = RTRIM(PLN.ETBL_DESC_TXT)
,covrTrm.CVG_MAT_XPRY_DUR POL_TERM
,RTRIM(BLLM.ETBL_DESC_TXT) MODE_OF_PAY 
,Face_Amount = CVG.FACE_AMT
,MD_Premium = POL.POL_MPREM_AMT
,APE_AFYP =  cov.CoveragePremium --* (12 / CAST(POL.POL_BILL_MODE_CD AS INT))
,RTRIM(PSTAT.DM_AV_DESC_TXT) POL_STATUS
,POL_SAT_DT = POL.POL_STAT_CHNG_DT
,DIST_CHANHEL = AGB.AGT_DISB_CHNL_DESC
,AGD.Name AGE_NAME
,AGD.ManagerName AGE_MG_NAME
,ME1_RQ_DT = TME1.CPREQ_CREAT_DT
,ME1_RC_DT = TME1.CPREQ_TST_DT
,ME2_RQ_DT = TME2.CPREQ_CREAT_DT
,ME2_RC_DT = TME2.CPREQ_TST_DT
,ME3_RQ_DT = TME3.CPREQ_CREAT_DT
,ME3_RC_DT = TME3.CPREQ_TST_DT 
,COL_CRE_DT = TCOL.CPREQ_CREAT_DT
,RC_COL_DT = TCOL.CPREQ_TST_DT
,UW_SUM_1CRE_DT = UWG.UWG_CREAT_DT
,UW_DEC = UWG.UWG_SUMM_CSTAT_2_DESC
,ST_UW_DEC_DT= UWG.UWG_DECID_1_DT
,ND_UW_DEC_DT = UWG.UWG_DECID_2_DT
,UW = UWG.UWG_USER_1_ID
,IS_USER = UWG.PREV_UPDT_USER_ID
,POL_REJ_REAS = RTRIM(RJR.ETBL_DESC_TXT)
FROM SGTB_POLICY POL
LEFT JOIN SGTB_POLICY_CLIENT POLC ON POLC.POL_ID = POL.POL_ID
LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) PONM ON POLC.CLI_ID= PONM.CLI_ID AND PONM.#NO = 1
LEFT JOIN SGTB_COVERAGE_CLI BLI ON BLI.POL_ID = POL.POL_ID AND CVG_NUM = '01'
LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) BLNM ON BLI.INSRD_CLI_ID= BLNM.CLI_ID AND BLNM.#NO = 1
LEFT JOIN SGTB_EDITTABLE PLN ON PLN.ETBL_VALU_ID = POL.PLAN_ID AND PLN.ETBL_TYP_ID = 'PLAN'
LEFT JOIN SGTM_COVERAGE covrTrm ON covrTrm.CO_ID='CP' AND covrTrm.POL_ID=POL.POL_ID AND covrTrm.ORIG_PLAN_ID=POL.PLAN_ID
LEFT JOIN SGTB_EDITTABLE BLLM ON BLLM.ETBL_VALU_ID = POL.POL_BILL_MODE_CD AND BLLM.ETBL_LANG_CD = 'E' AND BLLM.CO_ID = 'CP' AND BLLM.ETBL_TYP_ID = 'BILL-MODE'
LEFT JOIN (SELECT CVG.POL_ID POL_ID, SUM(CVG.CVG_FACE_AMT) AS FACE_AMT,SUM(CVG.CVG_MPREM_AMT) AS UW_AMT FROM OPENQUERY(UAT7, 'SELECT POL_ID, CVG_FACE_AMT, CVG_MPREM_AMT FROM KCAPXUAT.TCVG') AS CVG GROUP BY CVG.POL_ID) CVG ON CVG.POL_ID = POL.POL_ID
LEFT JOIN ( SELECT POL_ID, CVG_CSTAT_CD , SUM(CVG_MPREM_AMT) AS [CoveragePremium] FROM  SGTM_COVERAGE GROUP BY POL_ID,CVG_CSTAT_CD ) cov ON cov.POL_ID=POL.POL_ID AND cov.CVG_CSTAT_CD=POL.POL_CSTAT_CD
LEFT JOIN SGTM_PARA_1 PSTAT ON PSTAT.DM_AV_CD = POL.POL_CSTAT_CD AND PSTAT.DM_AV_TBL_CD='POL-CSTAT-CD' AND PSTAT.DM_AV_DESC_LANG_CD = 'E' AND PSTAT.CO_ID = 'CP'
LEFT JOIN SGTB_POLICY_WRITING POW ON POW.POL_ID = POL.POL_ID
LEFT JOIN SGTM_AGENT_DETAIL AGD ON POW.AGT_ID = AGD.AgentId
LEFT JOIN SGTM_AGENT_DETAIL AGM ON AGM.AgentId = AGD.AgentId
LEFT JOIN V_GET_AGENT_BASIC AGB ON AGB.AGT_ID = AGD.AgentId
LEFT JOIN SGTB_EDITTABLE RJR ON RJR.ETBL_VALU_ID = POL.POL_REJ_REASN_CD AND RJR.ETBL_TYP_ID = 'REJCD'
LEFT JOIN #UWG  UWG ON UWG.POL_ID = POL.POL_ID

LEFT JOIN #TREQT TCOL ON POL.POL_ID = TCOL.POL_CLI_ID AND TCOL.GRP_CD = 'COL'

LEFT JOIN (SELECT * FROM #ME) TME1 ON POL.POL_ID = TME1.POL_CLI_ID AND TME1.GRP_CD = 'ME' AND TME1.REQIR_ID = '0028'
LEFT JOIN (SELECT * FROM #ME) TME2 ON POL.POL_ID = TME2.POL_CLI_ID AND TME2.GRP_CD = 'ME' AND TME2.REQIR_ID = '0029'
LEFT JOIN (SELECT * FROM #ME) TME3 ON POL.POL_ID = TME3.POL_CLI_ID AND TME3.GRP_CD = 'ME' AND TME3.REQIR_ID = '0030'

LEFT JOIN (SELECT * FROM #ALI1) ALI1 ON ALI1.POL_ID = POLC.POL_ID AND ALI1.ROW# = 1
LEFT JOIN (SELECT * FROM #ALI2) ALI2 ON ALI2.POL_ID = POLC.POL_ID AND ALI2.ROW# = 2

WHERE POL.POL_APP_RECV_DT BETWEEN @STAT_DATE AND @END_DATE
