

CREATE PROCEDURE [dbo].[SP_DAILY_ETL_BATCH] AS 

	DECLARE @CURRENT_DATE DATE
	SET @CURRENT_DATE=CAST(GETDATE() AS DATE)

	EXEC SP_ETL_DIMS_MAIN @CURRENT_DATE;

	--SELECT * FROM ETLB_BATCH_PROC_DETAIL WHERE BRANCH_DATE=@CURRENT_DATE AND PARENT_BATCH IS NULL AND PROC_TYPE='X' AND BATCH_NUM=2

	EXEC SP_ETL_BEFORE_BOD_MAIN 'ALL',@CURRENT_DATE

	--SELECT * FROM ETLB_BATCH_PROC_DETAIL WHERE BRANCH_DATE=@CURRENT_DATE AND PARENT_BATCH IS NULL AND PROC_TYPE='X' AND BATCH_NUM=1

	EXEC SP_ETL_FACTS_MAIN @CURRENT_DATE

	--SELECT * FROM ETLB_BATCH_PROC_DETAIL WHERE BRANCH_DATE=@CURRENT_DATE AND PARENT_BATCH IS NULL AND PROC_TYPE='X' AND BATCH_NUM=3
