
-- =============================================
-- Author:		TIPI HING
-- Create date: 28-APRIL-2017
-- Description:	IACR ACCOUNT
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_FACT_IACR_ACCOUNT]
	@BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCDW..FACT_DAILY_IACR_ACCOUNT WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END
 IF OBJECT_ID('tempdb..#IACR') IS NOT NULL
  DROP TABLE #IACR
 IF OBJECT_ID('tempdb..#IACR1') IS NOT NULL
  DROP TABLE #IACR1
 IF OBJECT_ID('tempdb..#IACR2') IS NOT NULL
  DROP TABLE #IACR2
  IF OBJECT_ID('tempdb..#CUR') IS NOT NULL
  DROP TABLE #CUR
   
DECLARE @COUNT INT
DECLARE @MIN INT=1
SELECT ROW_NUMBER() OVER(ORDER BY CCY_CODE DESC) AS Row,CCY_CODE into #CUR FROM BBCDW..DIM_CURRENCY WHERE CCY_CODE IN ('USD','KHR','EUR','THB')
CREATE TABLE #IACR (CLCY FLOAT,CFCY FLOAT,DLCY FLOAT,DFCY FLOAT,CURRENCY VARCHAR(50),ACCOUNT VARCHAR(100),TYPE VARCHAR(10))
DECLARE @RATE FLOAT
DECLARE @CUR VARCHAR(100)
SELECT @COUNT=COUNT(*) FROM #CUR
WHILE @MIN<=@COUNT
	BEGIN
		SELECT @CUR=CCY_CODE FROM #CUR WHERE Row=@MIN
		SELECT @RATE=MID_RATE FROM BBCDW..DIM_RATE WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) AND BRANCH_CODE='001' AND RATE_TYPE='NBC' AND CCY2=@CUR
		IF @CUR='EUR'
		SET @RATE=1/@RATE

INSERT INTO #IACR
select case when DRCR_IND='C' THEN LCY_AMOUNT ELSE 0 END CLCY,case when DRCR_IND='C' THEN ISNULL(FCY_AMOUNT,0)/@RATE ELSE 0 END CFCY,
case when DRCR_IND='D' THEN LCY_AMOUNT ELSE 0 END DLCY,case when DRCR_IND='D' THEN ISNULL(FCY_AMOUNT,0)/@RATE ELSE 0 END DFCY,AC_CCY,RELATED_ACCOUNT,'S' ACCOUNT_TYPE  from SGTB_AC_ENTRIES E where 
EVENT in ('IACR','ILIQ','INIT') AND 
AC_NO in ('34421000','34422000','34521000','34522000') AND AC_CCY=@CUR  AND TRN_DT<=@BRANCH_DATE
UNION ALL
select case when DRCR_IND='C' THEN LCY_AMOUNT ELSE 0 END CLCY,case when DRCR_IND='C' THEN ISNULL(FCY_AMOUNT,0)/@RATE ELSE 0 END CFCY,
case when DRCR_IND='D' THEN LCY_AMOUNT ELSE 0 END DLCY,case when DRCR_IND='D' THEN ISNULL(FCY_AMOUNT,0)/@RATE ELSE 0 END DFCY,AC_CCY,RELATED_ACCOUNT,'Y'  from SGTB_AC_ENTRIES E where 
EVENT in ('IACR','ILIQ','INIT') AND 
AC_NO in (
'34431000',
'34432000',
'34433000',
'34434000','34324000',

'34531000',
'34532000',
'34533000',
'34534000'
)  AND AC_CCY=@CUR AND TRN_DT<=@BRANCH_DATE
UNION ALL
select case when DRCR_IND='C' THEN LCY_AMOUNT ELSE 0 END CLCY,case when DRCR_IND='C' THEN ISNULL(FCY_AMOUNT,0)/@RATE ELSE 0 END FLCY,
case when DRCR_IND='D' THEN LCY_AMOUNT ELSE 0 END DLCY,case when DRCR_IND='D' THEN ISNULL(FCY_AMOUNT,0)/@RATE ELSE 0 END DFCY,AC_CCY,RELATED_ACCOUNT,'U' from SGTB_AC_ENTRIES E where 
EVENT in ('IACR','ILIQ','INIT') AND 
AC_NO in ('34411000','34412000','34511000','34512000','25211000','25212000','23253000','25351000','25352000') AND AC_CCY=@CUR AND TRN_DT<=@BRANCH_DATE  ORDER BY RELATED_ACCOUNT

	SET @MIN=@MIN+1
	END
SELECT CLCY,DLCY,CURRENCY,ACCOUNT,TYPE INTO #IACR1 FROM #IACR WHERE CURRENCY='USD'
UNION ALL
SELECT CFCY,DFCY,CURRENCY,ACCOUNT,TYPE FROM #IACR WHERE CURRENCY<>'USD'

SELECT isnull(SUM(CLCY),0)C,isnull(SUM(DLCY),0)D,isnull(SUM(CLCY),0)-isnull(SUM(DLCY),0)IACR,ACCOUNT,TYPE INTO #IACR2 FROM #IACR1 GROUP BY ACCOUNT,TYPE

INSERT INTO BBCDW..FACT_DAILY_IACR_ACCOUNT
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112),SUM(C),SUM(D),SUM(IACR),ACCOUNT,TYPE FROM #IACR2
group by ACCOUNT,TYPE

END
