
CREATE PROC [dbo].[SP_ETL_FACT_AGENT_LVL] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

--DECLARE @BRANCH_DATE	DATE = '2024-06-26'
--			,@IS_RE_PROC BIT = 1

IF @IS_RE_PROC=1 DELETE FROM  DLKHFACT..FACT_AGENT WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

DECLARE @COUNT INT=1
DECLARE @AGT_ID VARCHAR(100)
DECLARE @CHECK INT
DECLARE @ABM INT
DECLARE @MAX INT
DECLARE @SUB VARCHAR(100)
DECLARE @ABM_SURNAME VARCHAR(200)
DECLARE @ABM_GIVNAME VARCHAR(200)

IF OBJECT_ID('TEMPDB..#TMP') IS NOT NULL DROP TABLE #TMP
IF OBJECT_ID('TEMPDB..#RESULT') IS NOT NULL DROP TABLE #RESULT
IF OBJECT_ID('TEMPDB..#PREV') IS NOT NULL DROP TABLE #PREV
IF OBJECT_ID('TEMPDB..#PREVABM') IS NOT NULL DROP TABLE #PREVABM

SELECT  ROW_NUMBER() OVER(ORDER BY AGENTID ASC) AS NUM,* INTO #TMP FROM SGTM_AGENT_DETAIL
--SELECT MAX(START_DT) START_DT,OVRID_BASE_AGT_ID,OVRID_AGT_ID INTO #PREV FROM DLKHDIM..DIM_AG_LVL WHERE IS_CURRENT=0 GROUP BY OVRID_BASE_AGT_ID,OVRID_AGT_ID

SELECT AG_KEY,ABM_ID,AGT_CLI_REL_TYP_CD,OVRID_BASE_AGT_ID INTO #PREVABM FROM DLKHFACT..FACT_AGENT WHERE DATE_KEY=(SELECT MAX(DATE_KEY) FROM DLKHFACT..FACT_AGENT WHERE DATE_KEY<CONVERT(VARCHAR,@BRANCH_DATE,112));
SET @MAX = (SELECT COUNT(*) FROM #TMP)

WHILE @COUNT<=@MAX
BEGIN
	SELECT @SUB=AgentId,@AGT_ID=MANAGERID FROM #TMP WHERE NUM=@COUNT
	--SELECT @AGT_ID=OVRID_AGT_ID FROM DLKHDIM..DIM_AG_LVL WHERE IS_CURRENT=1 AND OVRID_BASE_AGT_ID=@SUB
	--SELECT @AGT_ID=OVRID_AGT_ID FROM DLKHDIM..DIM_AG_LVL WHERE IS_CURRENT=1 AND OVRID_BASE_AGT_ID=@AGT_ID
	SELECT @CHECK=COUNT(*) FROM SGTM_AGENT_DETAIL WHERE AgentId=@AGT_ID 
	DECLARE @CHECKABM INT = 0

	WHILE (@CHECK>0)
	BEGIN
		SELECT  @ABM=COUNT(*) FROM DMS_AGENT_DETAIL WHERE  AGENT_CODE = @AGT_ID AND AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4)
		--SELECT @ABM=COUNT(*) FROM DLKHDIM..DIM_AG WHERE IS_CURRENT=1 AND AGT_ID=@AGT_ID AND AGT_TITL IN ('11','14')
		IF(@ABM=1)
		BEGIN
			SET @CHECK = 0
			BREAK;
		END
		SELECT @AGT_ID=MANAGERID FROM SGTM_AGENT_DETAIL WHERE AgentId=@AGT_ID
		--SELECT @AGT_ID=OVRID_BASE_AGT_ID FROM DLKHDIM..DIM_AG WHERE AGT_ID=@AGT_ID AND IS_CURRENT=1
		--SELECT @AGT_ID=OVRID_AGT_ID FROM DLKHDIM..DIM_AG_LVL WHERE IS_CURRENT=1 AND OVRID_BASE_AGT_ID=@AGT_ID
		---SELECT @CHECK=COUNT(*) FROM DLKHDIM..DIM_AG_LVL WHERE IS_CURRENT=1 AND OVRID_BASE_AGT_ID=@AGT_ID

		IF(@ABM=1)
		BEGIN
			SET @CHECK = 0
			BREAK;
		END

		IF @CHECKABM=5
		BEGIN
			BREAK;
		END
		SET @CHECKABM=@CHECKABM+1
	END

SELECT @ABM_SURNAME=ENTR_SUR_NM,@ABM_GIVNAME=ENTR_GIV_NM FROM V_AGENT WHERE AGT_ID=@AGT_ID 

INSERT INTO  DLKHFACT..FACT_AGENT
SELECT DISTINCT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY
	,A.*
	,E.ETBL_DESC_TXT AGENT_TITLE
	,CASE WHEN A.CHANNEL = 'BA' THEN 'BANCA' ELSE 'AGENCY' END AGENT_CHANNEL
	,@AGT_ID ABM_ID
	,@ABM_SURNAME ABM_SURNAME
	,@ABM_GIVNAME ABM_GIVNAME
	,''
	,''  
FROM V_AGENT A 
LEFT JOIN SGTB_EDITTABLE E ON A.AGT_TITL=E.ETBL_VALU_ID AND E.ETBL_TYP_ID='AGTLE' AND E.ETBL_LANG_CD='E' AND E.CO_ID='CP'
--LEFT JOIN #PREV P ON A.OVRID_BASE_AGT_ID=P.OVRID_BASE_AGT_ID AND A.OVRID_BASE_AGT_ID<>P.OVRID_AGT_ID
WHERE A.AGT_ID=@SUB 
SET @COUNT = @COUNT + 1
END

UPDATE T SET PREV_ABM_CODE=P.ABM_ID FROM DLKHFACT..FACT_AGENT T INNER JOIN #PREVABM P ON T.AG_KEY=P.AG_KEY AND T.AGT_CLI_REL_TYP_CD=P.AGT_CLI_REL_TYP_CD WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
UPDATE T SET PREV_LEAD_CODE=P.OVRID_BASE_AGT_ID FROM DLKHFACT..FACT_AGENT T INNER JOIN (SELECT MAX(P.AG_KEY) AG_KEY,P.AGT_ID,P.OVRID_BASE_AGT_ID  FROM DLKHFACT..FACT_AGENT T INNER JOIN DLKHDIM..DIM_AG P ON T.AGT_ID=P.AGT_ID AND P.OVRID_BASE_AGT_ID<>T.OVRID_BASE_AGT_ID WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY P.OVRID_BASE_AGT_ID,P.AGT_ID)
P ON T.AGT_ID=P.AGT_ID  WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

END
