
-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 09-AUG-2016
-- Description:	ETL Facility
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_BATCH_FACSTAGE]
	@BRANCH_CODE AS VARCHAR(3),@BRANCH_DATE AS DATE,
	@BATCH_CODE VARCHAR(15),@BATCH_DESC AS NVARCHAR(MAX),
	@DB_NAME AS VARCHAR(20),@SERVER_NAME AS VARCHAR(20)
AS
BEGIN
	DECLARE @ERROR_CODE VARCHAR(50),@ERROR_MSG NVARCHAR(MAX),@STR_SQL NVARCHAR(MAX),
			@START_TIME AS DATETIME,@END_TIME AS DATETIME,@SQLCODE AS VARCHAR(6),@PROC_DESC AS VARCHAR(250),@ROWCOUNT INT=0

	SET @ERROR_CODE=''
	SET @ERROR_MSG=''
	SET @STR_SQL=''

	BEGIN TRAN;
	BEGIN TRY
			SET @SQLCODE='B004'
			SET @START_TIME=GETDATE();

			SELECT @STR_SQL=SQL_SCRIPT FROM ETLM_SQLSCRIPTS E WHERE E.SQL_CODE=@SQLCODE AND E.BATCH_CODE=@BATCH_CODE;			
			IF ISNULL(RTRIM(LTRIM(@STR_SQL)),'')<>''
			BEGIN
					
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_DATE',@BRANCH_DATE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_CODE',@BRANCH_CODE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@SERVER_NAME',@SERVER_NAME)
					SET @STR_SQL=REPLACE(@STR_SQL,'@DB_NAME',@DB_NAME)
					EXEC sp_executesql @STR_SQL;
					SET @ROWCOUNT = @@RowCount;
					--SELECT 1/0
					INSERT INTO BBCDW..FACT_DAILY_FACILITY
					SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,LIAB_ID,LIAB_NO,LIAB_NAME,LINE_CODE,LINE_SERIAL,LIAB_CCY,MAIN_LINE_ID,CCY_RESTRICTION,REVOLVING_LINE,LINE_START_DATE,
					LINE_EXPIRY_DATE,LAST_NEW_UTIL_DATE,AVAILABILITY_FLAG,LIMIT_AMOUNT,COLLATERAL_CONTRIBUTION,AVAILABLE_AMOUNT,OVERALL_LIMIT,
					FC.USER_DEFINE_STATUS,DATE_OF_FIRST_OD,DATE_OF_LAST_OD,LMT_AMT_BASIS,TRANSFER_AMOUNT,BLOCK_AMOUNT,MATURED_UTIL
					,APPROVED_AMT,DSP_EFF_LINE_AMOUNT,UTILISATION 
					FROM BBCDW..DIM_LIAB LI INNER JOIN SGTB_FACILITY FC ON LI.ID=FC.LIAB_ID AND IS_CURRENT=1 AND FC.ETL_DATE=@BRANCH_DATE
					INNER JOIN BBCDW..DIM_BBC_BRANCH BR ON FC.BRN=BR.BRANCH_CODE AND BR.IS_CURRENT=1
			END 
	END TRY
	BEGIN CATCH
			SELECT 
					@ERROR_CODE=ERROR_NUMBER(),
					@ERROR_MSG=ERROR_MESSAGE()
			
			IF @@TRANCOUNT>0 
				ROLLBACK TRAN
			PRINT ('ETL Processing fail on batch '+ @BATCH_CODE +'. Transaction Rollbacked!')
			SET @PROC_DESC='Error batch '+@BATCH_DESC+' with SQLCODE: '+ @SQLCODE;
			SET @END_TIME=GETDATE()
			EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'E',@PROC_DESC,@START_TIME,@END_TIME,@ERROR_CODE,@ERROR_MSG,@STR_SQL
	END CATCH;

	IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRAN;

		SET @END_TIME=GETDATE();
		SET @PROC_DESC= @BATCH_DESC+', SQLCODE: '+@SQLCODE +', RowCount: '+ CAST(@ROWCOUNT  AS VARCHAR(100))
		EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'C',@PROC_DESC,@START_TIME,@END_TIME,'','',@STR_SQL
	END;

END
