CREATE PROC [dbo].[SP_ETL_FACT_AXP_AGENT_PRO] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_AGENT_PRO WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

INSERT INTO DLKHFACT..FACT_AGENT_PRO

SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,AGENT_KEY,P.POL_KEY,COV_KEY,PRO.REPORT_DT,MOVEMENT_TYPE,BUSINESS_SOURCE,P.POL_ID,EFF_DT,PRCES_DT,CASECOUNT,APP_AMT,AFYC_AMT,DESCRIPTION,P.LATST_ACTV_DT POL_LAST_DT,P.POL_APP_RECV_DT POL_SUBMIT_DT,P.POL_INFC_DT POL_ISS_DT,
C.CVG_MPREM_AMT,CVG_SUM_INS_AMT,0 POL_PREM_PAY_DUR,W.AGT_ID AGENT_CODE,CSC_NAME,TEAM_CODE_1,TEAM_NAME_1,
TEAM_CODE_2,TEAM_NAME_2,TEAM_CODE_3,TEAM_NAME_3,TEAM_CODE_4,TEAM_NAME_4,TEAM_CODE_5,TEAM_NAME_5,TEAM_CODE_6,TEAM_NAME_6,C.CVG_MPREM_AMT-CVG_ME_PREM_AMT PRE_BEFORE,C.CVG_MPREM_AMT PRE_AFTER FROM DLKHDIM..DIM_POLICY P
INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1 AND P.IS_CURRENT=1
INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
INNER JOIN V_AGENT_INFO V ON V.PARTY_ID=W.AGT_ID
INNER JOIN SGTB_AGENT_PRO PRO ON PRO.AGT_ID=W.AGT_ID
WHERE PRCES_DT=@BRANCH_DATE
END
