CREATE proc [dbo].[SP_ETL_FACT_DEPO_CLASS]  @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCNBCMART..FACT_DEPO_CLASS WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END
INSERT INTO BBCNBCMART..FACT_DEPO_CLASS
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,case when CUS.COUNTRY<>'KHM' then 'Non_Resident' 
	else case when (ACCOUNT_CLASS like '%CO%' or ACCOUNT_CLASS like '%SM%' or ACCOUNT_CLASS like '%RF%')  then 
			case when CLA.CUST_CLASS='ENP' then 'Non-Profit' 
	 else 'Corporate' end
	 when ACCOUNT_CLASS like '%MF%' then 'Microfinance'
	 when CUSTOMER_TYPE='I' then 'Individual' end end TYPE,AC.AC_DESC,CUST_AC_NO,AC.ACCOUNT_TYPE,CASE WHEN AC.CCY NOT IN ('USD','KHR') THEN 'O' ELSE AC.CCY END CCY,BAL.ACY_CUR_BAL,BAL.LCY_CUR_BAL+ISNULL(IACR.IACR,0) BALANCE  FROM BBCDW..FACT_DAILY_AC_BAL BAL 
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_KEY=BAL.CUSTOMER_KEY 
LEFT JOIN BBCDW..DIM_CUST_CLASS CLA ON CUS.CUST_CLASS=CLA.CUST_CLASS AND CLA.IS_CURRENT=1
LEFT JOIN BBCDW..FACT_DAILY_IACR_ACCOUNT IACR ON AC.CUST_AC_NO=IACR.ACCOUNT AND IACR.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
WHERE BAL.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) AND ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND LCY_CUR_BAL>=0

end
