CREATE PROC [dbo].[SP_ETL_FACT_CUS_PORTFOLIO] @BRANCH_DATE DATE,@IS_RE_PROC BIT
AS
BEGIN 
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCDW..FACT_CUSTOMER_PORTFOLIO WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END

INSERT INTO BBCDW..FACT_CUSTOMER_PORTFOLIO

select CONVERT(VARCHAR,@BRANCH_DATE,112),RM.RM_NAME,AC.BRANCH_CODE,CUS.CUSTOMER_NO,AC.CUST_AC_NO,AC.AC_DESC,P_SEX,RESIDENT_STATUS,AC.ACCOUNT_CLASS,ACCOUNT_TYPE,AC.CCY
,CIF_CREATION_DATE,AC_OPEN_DATE,ICM.INT_START_DATE,ICM.MATURITY_DATE,ICM.ROLLOVER_TYPE,CASE WHEN AC.ACY_CURR_BALANCE < 0 THEN 'D' ELSE 'C' END DRCR_AC,
AC.ACC_STATUS,DESIGNATION,ACY_CUR_BAL AS FCY_BAL,LCY_CUR_BAL AS LCY_BAL,FAC.APPROVE_AMOUNT LIMIT_AMOUNT,LINK.LINE_START_DATE TOD_LIMIT_START_DATE,LINK.LINE_EXPIRY_DATE TOD_LIMIT_END_DATE,CASE WHEN ACC_STATUS='NORM' THEN 'N' ELSE 'Y' END Dormant,
NATIONALITY,EXPOSURE_COUNTRY,UDF.LOV_DESC,AC.RECORD_STAT,AC.MAKER_ID,AC.MAKER_DT_STAMP,AC.CHECKER_DT_STAMP,CUS.MINOR,
V.FIELD_VAL_22,V.FIELD_VAL_21,
STR_SUBMITTED,	
V.FIELD_VAL_20,v.FIELD_VAL_7,v.FIELD_VAL_11,V.FIELD_VAL_12,V.FIELD_VAL_13,V.FIELD_VAL_14,V.FIELD_VAL_15,V.FIELD_VAL_16,V.FIELD_VAL_17,V.FIELD_VAL_18,V.FIELD_VAL_19,V.FIELD_VAL_23,V.FIELD_VAL_24,
V1.FIELD_VAL_1,UDF1.LOV_DESC,V1.FIELD_VAL_3,V1.FIELD_VAL_4,RM.RM_ID  from BBCDW..FACT_DAILY_AC_BAL BAL INNER JOIN BBCDW..DIM_CUSTOMER CUS ON BAL.CUSTOMER_KEY=CUS.CUSTOMER_KEY
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY and ACCOUNT_CLASS not IN ('NOSTRO', 'INTERN')
LEFT JOIN BBCDW..DIM_ICTM ICM ON ICM.ACC=AC.CUST_AC_NO AND ICM.IS_CURRENT=1
LEFT JOIN BBCDW..FACT_CUST_ACCOUNT_LINKAGES LINK ON AC.ACCOUNT_KEY=LINK.ACCOUNT_KEY AND LINK.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
LEFT JOIN BBCDW..FACT_DAILY_FACILITY FAC ON CONCAT(LINK.LINE_CODE,LINK.LINE_SERIAL)=CONCAT(FAC.LINE_CODE,FAC.LINE_SERIAL) AND FAC.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
LEFT JOIN (select D.REC_KEY CIF_NO,LOV_DESC from BBCDW..DIM_UDF_VAL D
INNER JOIN BBCDW..DIM_UDF_LOV L ON D.FIELD_VAL_10=L.LOV AND L.FIELD_NAME='PACKAGE' WHERE FUNCTION_ID ='STDCIF' AND D.IS_CURRENT=1 AND L.IS_CURRENT=1) UDF ON CUS.CUSTOMER_NO=UDF.CIF_NO AND CUS.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_RELATION_MANAGER RM ON RM.RM_ID=CUS.RM_ID AND RM.BRANCH_CODE=1
LEFT JOIN BBCDW..DIM_UDF_VAL V ON  AC.CUST_NO=V.REC_KEY AND V.FUNCTION_ID='STDCIF' AND V.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_UDF_VAL V1 ON  AC.CUST_AC_NO=V.REC_KEY AND V.FUNCTION_ID='STDCUSAC' AND V.IS_CURRENT=1
LEFT JOIN (select D.REC_KEY CIF_NO,LOV_DESC from BBCDW..DIM_UDF_VAL D
INNER JOIN BBCDW..DIM_UDF_LOV L ON D.FIELD_VAL_2=L.LOV AND L.FIELD_NAME='PACKAGE' WHERE FUNCTION_ID ='STDCUSAC' AND D.IS_CURRENT=1 AND L.IS_CURRENT=1) UDF1 ON AC.CUST_AC_NO=UDF1.CIF_NO 
WHERE BAL.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)

END
