
-- =============================================
-- Author:		HING TIPI
-- Create date: 15-MAR-2017
-- Description:	ICTB
-- =============================================
CREATE  PROCEDURE [dbo].[SP_ETL_BATCH_ICTB]
	@BRANCH_CODE AS VARCHAR(3),@BRANCH_DATE AS DATE,
	@BATCH_CODE VARCHAR(15),@BATCH_DESC AS NVARCHAR(MAX),
	@DB_NAME AS VARCHAR(20),@SERVER_NAME AS VARCHAR(20)
AS
BEGIN
	DECLARE @ERROR_CODE VARCHAR(50),@ERROR_MSG NVARCHAR(MAX),@STR_SQL NVARCHAR(MAX),
			@START_TIME AS DATETIME,@END_TIME AS DATETIME,@SQLCODE AS VARCHAR(6),@PROC_DESC AS VARCHAR(250),@ROWCOUNT INT=0

	SET @ERROR_CODE=''
	SET @ERROR_MSG=''
	SET @STR_SQL=''

	BEGIN TRAN;
	BEGIN TRY
			SET @SQLCODE='B009'
			SET @START_TIME=GETDATE();

			SELECT @STR_SQL=SQL_SCRIPT FROM ETLM_SQLSCRIPTS E WHERE E.SQL_CODE=@SQLCODE AND E.BATCH_CODE=@BATCH_CODE;			
			IF ISNULL(RTRIM(LTRIM(@STR_SQL)),'')<>''
			BEGIN
					
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_DATE',@BRANCH_DATE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_CODE',@BRANCH_CODE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@SERVER_NAME',@SERVER_NAME)
					SET @STR_SQL=REPLACE(@STR_SQL,'@DB_NAME',@DB_NAME)
					EXEC sp_executesql @STR_SQL;
					SET @ROWCOUNT = @@RowCount;
					--SELECT 1/0
					INSERT INTO BBCDW..FACT_DAILY_AC_IC
					SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,BRANCH_KEY,ACCOUNT_KEY,CUSTOMER_KEY,PROD,FRM_NO,AMT,ACCRUED_AMT,AMT_TO_ACCRUE,CUR_RUN_ACCR,ENT_DT,DRCR,HAS_ACCR,DAILY_AMT,NEXT_CALC_DUE_DATE,ACQUIRED_AMT,ACQUIRED_ADJ,PROCESS 
					FROM BBCDW..DIM_CUST_ACCOUNT AC INNER JOIN SGTB_ICTB IC  ON AC.CUST_AC_NO=IC.ACC AND IS_CURRENT=1
					INNER JOIN BBCDW..DIM_BBC_BRANCH BR ON IC.BRN=BR.BRANCH_CODE AND BR.IS_CURRENT=1 
					INNER JOIN BBCDW..DIM_CUSTOMER C ON AC.CUST_NO=C.CUSTOMER_NO AND C.IS_CURRENT=1
					WHERE (IC.AMT>0 OR ACCRUED_AMT>0 OR AMT_TO_ACCRUE>0 OR CUR_RUN_ACCR>0 OR DAILY_AMT>0)
			END 
	END TRY
	BEGIN CATCH
			SELECT 
					@ERROR_CODE=ERROR_NUMBER(),
					@ERROR_MSG=ERROR_MESSAGE()
			
			IF @@TRANCOUNT>0 
				ROLLBACK TRAN
			PRINT ('ETL Processing fail on batch '+ @BATCH_CODE +'. Transaction Rollbacked!')
			SET @PROC_DESC='Error batch '+@BATCH_DESC+' with SQLCODE: '+ @SQLCODE;
			SET @END_TIME=GETDATE()
			EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'E',@PROC_DESC,@START_TIME,@END_TIME,@ERROR_CODE,@ERROR_MSG,@STR_SQL
	END CATCH;

	IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRAN;

		SET @END_TIME=GETDATE();
		SET @PROC_DESC= @BATCH_DESC+', SQLCODE: '+@SQLCODE +', RowCount: '+ CAST(@ROWCOUNT  AS VARCHAR(100))
		EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'C',@PROC_DESC,@START_TIME,@END_TIME,'','',@STR_SQL
	END;

END
