CREATE proc [dbo].[SP_ETL_FACT_DEPO_TOP20]  @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCNBCMART..FACT_DEPO_TOP_20 WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END
  IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
    IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
  DROP TABLE #TMP1
    IF OBJECT_ID('tempdb..#TMP2') IS NOT NULL
  DROP TABLE #TMP2
select CUST_NO,CUST_AC_NO AC_NO,FULL_NAME AC_DESC,case when CUS.COUNTRY='KHM' THEN 'R' ELSE 'N' END RESIDENT_STATUS,CL.DESCRIPTION CUS_CLASS,ICM.MATURITY_DATE,ACCOUNT_TYPE,
CASE WHEN CCY NOT IN ('USD','KHR') THEN 'O' ELSE CCY END CCY,BAL.LCY_CUR_BAL INTO #TMP from BBCDW..DIM_CUST_ACCOUNT AC 
INNER JOIN BBCDW..FACT_DAILY_AC_BAL BAL ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY 
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON AC.CUST_NO=CUS.CUSTOMER_NO AND CUS.IS_CURRENT=1 and AC.ACCOUNT_CLASS not in ('NOSTRO','INTERN')
LEFT JOIN BBCDW..DIM_CUST_CLASS CL ON CUS.CUST_CLASS=CL.CUST_CLASS AND CL.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_ICTM ICM ON AC.CUST_AC_NO=ICM.ACC AND ICM.IS_CURRENT=1 
WHERE ACCOUNT_TYPE<>'Y' and BAL.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
UNION ALL
select CUST_NO,CUST_AC_NO AC_NO,FULL_NAME AC_DESC,case when CUS.COUNTRY='KHM' THEN 'R' ELSE 'N' END RESIDENT_STATUS,CL.DESCRIPTION CUS_CLASS,ICM.MATURITY_DATE,
CASE WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE)>30 THEN 'FB' ELSE 'FS' END ACCOUNT_TYPE,
CASE WHEN CCY NOT IN ('USD','KHR') THEN 'O' ELSE CCY END CCY,BAL.LCY_CUR_BAL from BBCDW..DIM_CUST_ACCOUNT AC 
INNER JOIN BBCDW..FACT_DAILY_AC_BAL BAL ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON AC.CUST_NO=CUS.CUSTOMER_NO  AND CUS.IS_CURRENT=1 and AC.ACCOUNT_CLASS not in ('NOSTRO','INTERN')
LEFT JOIN BBCDW..DIM_CUST_CLASS CL ON CUS.CUST_CLASS=CL.CUST_CLASS AND CL.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_ICTM ICM ON AC.CUST_AC_NO=ICM.ACC AND ICM.IS_CURRENT=1  
WHERE ACCOUNT_TYPE='Y' and BAL.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)

SELECT  AC_NO,AC_DESC,RESIDENT_STATUS,CUS_CLASS,MAX(MATURITY_DATE) MATURITY_DATE,ACCOUNT_TYPE,CCY,sum(LCY_CUR_BAL) LCY_CUR_BAL into #TMP1 FROM #TMP
group by AC_NO,AC_DESC,RESIDENT_STATUS,CUS_CLASS,ACCOUNT_TYPE,CCY

select  AC_DESC,RESIDENT_STATUS,CUS_CLASS,ACCOUNT_TYPE,CCY,sum(LCY_CUR_BAL) LCY_CUR_BAL into #TMP2 from #TMP1
group by AC_DESC,RESIDENT_STATUS,CUS_CLASS,ACCOUNT_TYPE,CCY 

INSERT INTO BBCNBCMART..FACT_DEPO_TOP_20
select top 20 CONVERT(VARCHAR,@BRANCH_DATE,112),* from #TMP2 order by LCY_CUR_BAL desc

END
