-- =============================================
-- Author:		BUNCHHOEUN CHHIM
-- Create date: 19-Feb-18
-- Description:	Loan Payoff
-- =============================================
--CREATE PROCEDURE [dbo].[SP_ETL_FACT_LOAN_PAYOFF]
CREATE PROCEDURE [dbo].[SP_ETL_FACT_LOAN_PAYOFF]
	@BRANCH_DATE DATE, @IS_RE_PRC BIT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	IF @IS_RE_PRC = 1
	BEGIN
		DELETE FROM  BBCDW..FACT_LOAN_PAYOFF WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END

	--PRE PENALTY
	IF OBJECT_ID('tempdb..#PRE_PENALTY') IS NOT NULL
	DROP TABLE #PRE_PENALTY

	SELECT a.LOAN_AC_NO, sum(b.amount_paid) PENALTY_AMT
	INTO #PRE_PENALTY
	FROM BBCDW..DIM_LOAN_ACCOUNT a INNER JOIN BBCSTAGE..SGTB_LOAN_PAYMENT b
		ON a.LOAN_AC_NO = b.ACCOUNT_NUMBER
	WHERE a.ACCOUNT_STATUS = 'L'
		AND a.IS_CURRENT = 1
		AND CONVERT(VARCHAR, a.CHECKER_DT_STAMP, 112) = CONVERT(VARCHAR, @BRANCH_DATE, 112)		
		AND b.COMPONENT_NAME = 'PRE_PENALTY' 
		AND CONVERT(VARCHAR, b.EXEC_DATE, 112) = CONVERT(VARCHAR, @BRANCH_DATE, 112)		
	GROUP BY LOAN_AC_NO

	--INTEREST AMT
	IF OBJECT_ID('tempdb..#INTEREST_AMT') IS NOT NULL
	DROP TABLE #INTEREST_AMT

	SELECT a.LOAN_AC_NO, SUM(b.amount_paid) INT_AMT
	INTO #INTEREST_AMT
	FROM BBCDW..DIM_LOAN_ACCOUNT a inner join BBCSTAGE..SGTB_LOAN_PAYMENT b
		ON a.LOAN_AC_NO = b.ACCOUNT_NUMBER
	WHERE a.ACCOUNT_STATUS = 'L'
		AND a.IS_CURRENT = 1
		AND CONVERT(VARCHAR, a.CHECKER_DT_STAMP, 112) = CONVERT(VARCHAR, @BRANCH_DATE, 112)
		AND b.COMPONENT_NAME = 'MAIN_INT' 
		AND CONVERT(VARCHAR, b.EXEC_DATE, 112) = CONVERT(VARCHAR, @BRANCH_DATE, 112)
	GROUP BY LOAN_AC_NO

	--PRINCIPAL AMT
	IF OBJECT_ID('tempdb..#PRINCIPAL_AMT') IS NOT NULL
	DROP TABLE #PRINCIPAL_AMT

	SELECT a.LOAN_AC_NO, sum(b.amount_paid) PRINCIPAL_AMT
	INTO #PRINCIPAL_AMT
	FROM BBCDW..DIM_LOAN_ACCOUNT a INNER JOIN BBCSTAGE..SGTB_LOAN_PAYMENT b
		ON a.LOAN_AC_NO = b.ACCOUNT_NUMBER
	WHERE a.ACCOUNT_STATUS = 'L'
		AND A.IS_CURRENT = 1
		AND CONVERT(VARCHAR, a.CHECKER_DT_STAMP, 112) = CONVERT(VARCHAR, @BRANCH_DATE, 112)
		AND b.COMPONENT_NAME = 'PRINCIPAL'
		AND CONVERT(VARCHAR, b.EXEC_DATE, 112) = CONVERT(VARCHAR, @BRANCH_DATE, 112)
	GROUP BY LOAN_AC_NO

	INSERT INTO BBCDW..FACT_LOAN_PAYOFF(DATE_KEY, CUST_NO, CUST_NAME, PROD_CODE, APPRO_AMT, LOAN_ACC_NO, START_DT, FT_ST, CASA_ACC, PAY_OFF_DT, PRINCIPAL, INTEREST, PENALTY)
	SELECT CONVERT(VARCHAR, @BRANCH_DATE, 112), A.CUSTOMER_ID, B.FULL_NAME, A.PRODUCT_CODE ,A.AMOUNT_DISBURSED, A.LOAN_AC_NO, A.VALUE_DATE, A.FIELD_CHAR_7, A.DR_AC_NO, A.CHECKER_DT_STAMP,
		C.PRINCIPAL_AMT, D.INT_AMT, E.PENALTY_AMT
	FROM BBCDW..DIM_LOAN_ACCOUNT A
		LEFT JOIN BBCDW..DIM_CUSTOMER B ON A.CUSTOMER_ID = B.CUSTOMER_NO
		LEFT JOIN #PRINCIPAL_AMT C ON A.LOAN_AC_NO = C.LOAN_AC_NO
		LEFT JOIN #INTEREST_AMT D ON A.LOAN_AC_NO = D.LOAN_AC_NO
		LEFT JOIN #PRE_PENALTY E ON A.LOAN_AC_NO = E.LOAN_AC_NO
		
	WHERE A.IS_CURRENT = 1
		AND A.ACCOUNT_STATUS = 'L'
		AND B.IS_CURRENT = 1
		AND CONVERT(VARCHAR, a.CHECKER_DT_STAMP, 112) = CONVERT(VARCHAR, @BRANCH_DATE, 112)

END
