CREATE PROC [dbo].[SP_ETL_FACT_PAY_REV] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_PAYMENT_REVERSE WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

INSERT INTO DLKHFACT..FACT_PAYMENT_REVERSE
select CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,POL_KEY,H.POL_ID,S.POLSTAT_KEY,S.POLSTAT_DES Policy_Status,H.POL_ISS_EFF_DT Effective_Date,ACCT_HIST_GR_TS Transaction_Date,ACCT_HIST_AMT Cash_Amount,'' RECPT_ID 
 from SGTB_ACCOUNTING_TRANHIS H 
INNER JOIN DLKHDIM..DIM_POLICY P ON H.POL_ID=P.POL_ID 
LEFT JOIN DLKHDIM..DIM_POLICY_STATUS S ON P.POL_CSTAT_CD=S.POLSTAT_CODE
where BPF_ID like '%Reversal%' and ACCT_SUB_TYP_CD='N' AND P.IS_CURRENT=1 and H.ETL_DATE=@BRANCH_DATE AND S.POLSTAT_KEY is not null
END
