-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 22-SEP-2016
-- Description:	ETL FACT MM ACCRUED INTEREST
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_FACT_MM_ACCRUED_INT]
	@BRANCH_DATE AS DATE,@IS_RE_PROC AS BIT=0
AS
BEGIN
	
	SET NOCOUNT ON;

	INSERT INTO  BBCDW..FACT_MM_ACCRUED_INT
	SELECT 
			CONVERT(VARCHAR,E.TRN_DT,112) AS DATE_KEY,
			C.CONTRACT_KEY, 
			PR.PRODUCT_KEY,
			BR.BRANCH_KEY,
			E.TRN_DT,E.VALUE_DT,
			E.EVENT,E.AC_BRANCH,E.AC_CCY,E.AC_NO,E.RELATED_CUSTOMER AS CUST_NO,
			ISNULL(E.FCY_AMOUNT,0) FCY_AMOUNT,
			E.LCY_AMOUNT,
			(CASE WHEN E.EVENT='REVC' THEN 0 ELSE DATEDIFF(D,E.TRN_DT,E.VALUE_DT)+1 END) ACCRUED_DAYS,
			CASE WHEN C.CONTRACT_STATUS='A' THEN DATEDIFF(D,C.MATURITY_DATE,E.VALUE_DT) ELSE 0 END  REMAIN_DAYS,
			GETDATE() AS ETL_DATE
	FROM SGTB_AC_ENTRIES E 
	INNER JOIN BBCDW..DIM_MM_CONTRACT C ON E.TRN_REF_NO=C.CONTRACT_REF_NO AND C.IS_CURRENT=1
	INNER JOIN BBCDW..DIM_CS_PRODUCT PR ON PR.PRODUCT_CODE=C.PRODUCT AND PR.IS_CURRENT=1
	INNER JOIN BBCDW..DIM_BBC_BRANCH BR ON C.BRANCH=BR.BRANCH_CODE AND BR.IS_CURRENT=1
	LEFT JOIN BBCDW..FACT_MM_ACCRUED_INT MM ON C.CONTRACT_KEY=MM.CONTRACT_KEY AND E.TRN_DT=MM.TRN_DT
	WHERE E.MODULE='MM' AND E.MODULE='MM' AND E.EVENT IN('ACCR','REVC')
			AND E.AMOUNT_TAG IN('MMINT_ACCR','MMBORROW_ACCR') AND ( (E.DRCR_IND='D' AND E.AMOUNT_TAG='MMINT_ACCR') OR (E.DRCR_IND='C' AND E.AMOUNT_TAG='MMBORROW_ACCR'))
			AND MM.CONTRACT_KEY IS NULL
			AND E.TRN_DT<=@BRANCH_DATE
	ORDER BY E.TRN_DT,C.CONTRACT_KEY,EVENT_SR_NO

	
END
