CREATE proc [dbo].[SP_ETL_FACT_DEPO_AMOUNT]  @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCNBCMART..FACT_DEPO_AMOUNT WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END
  IF OBJECT_ID('tempdb..#DEPO') IS NOT NULL
  DROP TABLE #DEPO
  IF OBJECT_ID('tempdb..#DEPO1') IS NOT NULL
  DROP TABLE #DEPO1
    IF OBJECT_ID('tempdb..#SIZE') IS NOT NULL
  DROP TABLE #SIZE

CREATE TABLE #SIZE(ID SMALLINT,SIZE VARCHAR(100))
INSERT INTO #SIZE
select 1,'a>20,000 USD'
INSERT INTO #SIZE
select 2,'b<=20,000 USD & >10,000 USD'
INSERT INTO #SIZE
select 3,'c<=10,000 USD & >5,000 USD'
INSERT INTO #SIZE
select 4,'d<=5,000 USD & >3,000 USD'
INSERT INTO #SIZE
select 5,'e<=3,000 USD & >1,000 USD'
INSERT INTO #SIZE
select 6,'f<=1,000 USD & >5,000 USD'
INSERT INTO #SIZE
select 7,'g<=500 USD'

SELECT CUST_AC_NO,AC_DESC,CCY,ACCOUNT_TYPE,ACY_CUR_BAL,LCY_CUR_BAL+ISNULL(IACR.IACR,0)LCY_CUR_BAL,
CASE WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 20000 THEN 1
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=20000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 10000 THEN 2
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=10000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 5000 THEN 3
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=5000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 3000 THEN 4
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=3000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 1000 THEN 5
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=1000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 500 THEN 6
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=500  THEN 7 END SIZE,CASE WHEN (ACCOUNT_CLASS LIKE '%MF%' OR ACCOUNT_CLASS LIKE '%BK%') THEN 2 ELSE 1 END TYPE INTO #DEPO
FROM BBCDW..DIM_CUST_ACCOUNT AC INNER JOIN BBCDW..FACT_DAILY_AC_BAL BAL ON AC.ACCOUNT_KEY=BAL.ACCOUNT_KEY
LEFT JOIN BBCDW..DIM_ICTM ICM ON AC.CUST_AC_NO=ICM.ACC AND ICM.IS_CURRENT=1
LEFT JOIN BBCDW..FACT_DAILY_IACR_ACCOUNT IACR ON AC.CUST_AC_NO=IACR.ACCOUNT AND IACR.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
WHERE BAL.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) AND AC.ACCOUNT_CLASS NOT IN ('INTERN','NOSTRO') AND ACCOUNT_TYPE<>'Y' and LCY_CUR_BAL>=0
UNION ALL
SELECT CUST_AC_NO,AC_DESC,CCY,
CASE WHEN (cast(DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) as float)/30)<=1 THEN '1M'
WHEN (cast(DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) as float)/30)>1 AND (cast(DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) as float)/30)<=3 THEN '1_3M'
WHEN (cast(DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) as float)/30)>3 THEN '3M' END TD,ACY_CUR_BAL,LCY_CUR_BAL+ISNULL(IACR.IACR,0)LCY_CUR_BAL, 
CASE WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 20000 THEN 1
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=20000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 10000 THEN 2
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=10000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 5000 THEN 3
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=5000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 3000 THEN 4
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=3000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 1000 THEN 5
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=1000 AND LCY_CUR_BAL+ISNULL(IACR.IACR,0)> 500 THEN 6
WHEN LCY_CUR_BAL+ISNULL(IACR.IACR,0)<=500  THEN 7 END SIZE,CASE WHEN (ACCOUNT_CLASS LIKE '%MF%' OR ACCOUNT_CLASS LIKE '%BK%') THEN 2 ELSE 1 END TYPE 
FROM BBCDW..DIM_CUST_ACCOUNT AC INNER JOIN BBCDW..FACT_DAILY_AC_BAL BAL ON AC.ACCOUNT_KEY=BAL.ACCOUNT_KEY
LEFT JOIN BBCDW..DIM_ICTM ICM ON AC.CUST_AC_NO=ICM.ACC AND ICM.IS_CURRENT=1
LEFT JOIN BBCDW..FACT_DAILY_IACR_ACCOUNT IACR ON AC.CUST_AC_NO=IACR.ACCOUNT AND IACR.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
WHERE BAL.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) AND AC.ACCOUNT_CLASS NOT IN ('INTERN','NOSTRO') AND ACCOUNT_TYPE='Y' and LCY_CUR_BAL>=0

DELETE FROM #DEPO WHERE LCY_CUR_BAL=0

SELECT ACCOUNT_TYPE,SIZE,SUM(LCY_CUR_BAL) BALANCE,COUNT(LCY_CUR_BAL) ACCOUNT,TYPE INTO #DEPO1 FROM #DEPO GROUP BY ACCOUNT_TYPE,SIZE,TYPE 
ORDER BY ACCOUNT_TYPE

INSERT INTO BBCNBCMART..FACT_DEPO_AMOUNT
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112),S.SIZE,ACCOUNT_TYPE,BALANCE,ACCOUNT,TYPE FROM #SIZE S LEFT JOIN #DEPO1 D ON S.ID=D.SIZE

end
