
CREATE PROC [dbo].[SP_ETL_FACT_CHQ_PRINT] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCDW..FACT_PRINT_CHQ WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END
INSERT INTO BBCDW..FACT_PRINT_CHQ
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112),ORDER_DATE,ACCOUNT,CCY,AC.AC_DESC,'','','','',CONCAT('B',CHECK_LEAVES),FIRST_CHECK_NO,CCY,AC.BRANCH_CODE,ACCOUNT_CLASS FROM BBCDW..DIM_CHQ CH INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON CH.ACCOUNT=AC.CUST_AC_NO AND AC.IS_CURRENT=1 AND CH.IS_CURRENT=1
WHERE CH.RECORD_STAT='O' AND ORDER_DATE=@BRANCH_DATE
END
