
-- =============================================
-- Author:		BUNCHHOEUN CHHIM
-- Create date: 14-MAR-18
-- Description:	ATM ACCOUNT TRANSACTION
-- =============================================
CREATE  PROCEDURE [dbo].[SP_ETL_ATM_REC]
--ALTER  PROCEDURE [dbo].[SP_ETL_ATM_REC]
	@BATCH_CODE AS VARCHAR(20) ,@BRANCH_DATE AS DATE
	, @DB_NAME AS VARCHAR(20), @SERVER_NAME AS VARCHAR(20)
AS
BEGIN
	DECLARE @ERROR_CODE VARCHAR(50),@ERROR_MSG NVARCHAR(MAX),@STR_SQL NVARCHAR(MAX),
			@START_TIME AS DATETIME,@END_TIME AS DATETIME,@SQLCODE AS VARCHAR(6),@PROC_DESC AS VARCHAR(250),@ROWCOUNT INT=0,
			@PRE_DATE_ONLY DATETIME, @CUR_DATE_ONLY DATETIME, @CUT_TIME DATETIME, @PRE_DATE_TIME DATETIME, @CUR_DATE_TIME DATETIME
	
	SET @ERROR_CODE=''
	SET @ERROR_MSG=''
	SET @STR_SQL=''

	BEGIN TRAN;
	BEGIN TRY
		SET @SQLCODE='B025'
		SET @START_TIME=GETDATE();

		SELECT @STR_SQL = SQL_SCRIPT FROM ETLM_SQLSCRIPTS E WHERE E.SQL_CODE = @SQLCODE AND E.BATCH_CODE = @BATCH_CODE;			
		IF ISNULL(RTRIM(LTRIM(@STR_SQL)), '') <> ''
		BEGIN
			SET @STR_SQL = REPLACE(@STR_SQL, '@SERVER_NAME', @SERVER_NAME)
			SET @STR_SQL = REPLACE(@STR_SQL, '@DB_NAME', @DB_NAME)
			EXEC sp_executesql @STR_SQL;
			SET @ROWCOUNT = @@RowCount;
			--SELECT 1/0
		END 
	END TRY

	BEGIN CATCH
		SELECT 
			@ERROR_CODE = ERROR_NUMBER(),
			@ERROR_MSG = ERROR_MESSAGE()
			
		IF @@TRANCOUNT > 0 
			ROLLBACK TRAN
		PRINT ('ETL Processing fail on batch ' + @BATCH_CODE + '. Transaction Rollbacked!')
		SET @PROC_DESC = 'Error batch ' + 'ATM ACC TRN' + ' with SQLCODE: ' + @SQLCODE;
		SET @END_TIME = GETDATE()
		EXEC SP_ETL_PROC_WRITE_LOG '001', @BRANCH_DATE, @BATCH_CODE, 'E', @PROC_DESC, @START_TIME, @END_TIME, @ERROR_CODE, @ERROR_MSG, @STR_SQL
	END CATCH;

	IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRAN;

		SET @END_TIME = GETDATE();
		SET @PROC_DESC = 'ATM ACC TRN'+ ', SQLCODE: ' + @SQLCODE + ', RowCount: ' + CAST(@ROWCOUNT  AS VARCHAR(100))
		EXEC SP_ETL_PROC_WRITE_LOG '001', @BRANCH_DATE, @BATCH_CODE, 'C', @PROC_DESC, @START_TIME, @END_TIME, '', '', @STR_SQL

		--FIND LAST REPLENISH DATE ONLY
		IF OBJECT_ID('tempdb..#LAST_REP') IS NOT NULL
		DROP TABLE #LAST_REP

		SELECT TRN.AC_NO, GL.GL_DESC, TRN.LCY_AMOUNT, MAX(TRN.TRN_DT) LAST_REP_DATE
		INTO #LAST_REP
		FROM BBCSTAGE..SGTB_ATM_AC_TRN TRN
			LEFT JOIN BBCDW..DIM_GLMASTER GL ON TRN.AC_NO = GL.GL_CODE 
		WHERE TRN.AC_NO IN (SELECT DISTINCT(ATM.CASH_GL)
						FROM BBCDW..DIM_ATM_POS ATM 
						WHERE ATM.CASH_GL IS NOT NULL 
						AND RECORD_STAT <> 'C' 
						AND IS_CURRENT = 1)
			AND TRN.PROD = 'MGLD'
			AND GL.IS_CURRENT = 1
		GROUP BY TRN.AC_NO, TRN.LCY_AMOUNT, GL.GL_DESC

		--FIND LAST REPLENISH DATE & TIME
		IF OBJECT_ID('tempdb..#LAST_REP_DT') IS NOT NULL
		DROP TABLE #LAST_REP_DT

		SELECT TT.AC_NO, MAX(TT.TXN_DT_TIME) LAST_REP_DATETIME
		INTO #LAST_REP_DT
		FROM BBCSTAGE..SGTB_ATM_AC_TRN TT
		WHERE TT.AC_NO IN (SELECT DISTINCT(ATM.CASH_GL)
						FROM BBCDW..DIM_ATM_POS ATM 
						WHERE ATM.CASH_GL IS NOT NULL 
						AND RECORD_STAT <> 'C' 
						AND IS_CURRENT = 1)
			AND TT.PROD = 'MGLD'
		GROUP BY TT.AC_NO
		
		--CLEAR RECORD IF ALREADY EXISTED
		DELETE FROM  BBCDW..FACT_ATM_REC WHERE DATE_KEY = CONVERT(VARCHAR,@BRANCH_DATE,112);

		--FACT ATM TXN
		SET @CUT_TIME = '01 jan 1900 09:00:00'
		SET @PRE_DATE_ONLY = DATEADD(day, -1, CONVERT (date, SYSDATETIME()))
		SET @CUR_DATE_ONLY = DATEADD(day, 0, CONVERT (date, SYSDATETIME()))

		SELECT @PRE_DATE_TIME = CAST(@PRE_DATE_ONLY + ' ' + @CUT_TIME as datetime)
		SELECT @CUR_DATE_TIME = CAST(@CUR_DATE_ONLY + ' ' + @CUT_TIME as datetime)

		print 'pre ' + Convert(varchar(40), @PRE_DATE_TIME)
		print 'CUIR ' + Convert(varchar(40), @CUR_DATE_TIME)

		INSERT INTO BBCDW..FACT_ATM_REC(DATE_KEY, GL_NO, ATM_NAME, TOD_TXN_AMT, LAST_REP_AMT, LAST_REP_DATE, LAST_REP_DATETIME)
		SELECT CONVERT(VARCHAR, @BRANCH_DATE,112), A.AC_NO, RP.GL_DESC, SUM(A.LCY_AMOUNT) TOD_TXN_AMT, RP.LCY_AMOUNT, RP.LAST_REP_DATE, RPDT.LAST_REP_DATETIME
		FROM BBCSTAGE..SGTB_ATM_AC_TRN A
			LEFT JOIN #LAST_REP RP ON A.AC_NO = RP.AC_NO
			LEFT JOIN #LAST_REP_DT RPDT ON A.AC_NO = RPDT.AC_NO
		WHERE TXN_DT_TIME >= @PRE_DATE_TIME AND TXN_DT_TIME <= @CUR_DATE_TIME
		GROUP BY A.AC_NO, RP.GL_DESC, RP.LCY_AMOUNT, RP.LAST_REP_DATE, RPDT.LAST_REP_DATETIME

	END;

END
