CREATE PROC [dbo].[SP_ETL_FACT_AXP_POLISTING] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

--DECLARE @BRANCH_DATE	DATE = '2024-05-25'
		--	,@IS_RE_PROC BIT = 1

IF OBJECT_ID('tempdb..#APE') IS NOT NULL
DROP TABLE #APE

SELECT POL_ID,SUM(CASE WHEN CVG_CSTAT_CD IN ('1','2') THEN CVG_BASIC_PREM_AMT+CVG_FE_PREM_AMT+CVG_ME_PREM_AMT ELSE 0 END) ANN_PREMIUM12,
SUM(CASE WHEN CVG_CSTAT_CD NOT IN ('1','2') THEN CVG_BASIC_PREM_AMT+CVG_FE_PREM_AMT+CVG_ME_PREM_AMT ELSE 0 END) ANN_PREMIUM_OTHER INTO #APE FROM DLKHDIM..DIM_COVERAGE
WHERE IS_CURRENT=1
GROUP BY POL_ID

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_AXP_POLISTING WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

INSERT INTO DLKHFACT..FACT_AXP_POLISTING
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,
P.POL_KEY,P.POL_ID,V.AG_KEY,W.AGT_ID,V.ENTR_GIV_NM,V.ENTR_SUR_NM
,CASE WHEN V.CHANNEL = 'BA' THEN 'BANCA' ELSE 'AGENCY' END AGT_CHANNEL
,ST.POLSTAT_CODE,ST.POLSTAT_DES,0,CASE WHEN POL_BILL_MODE_CD=3 THEN
'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Month' WHEN POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE POL_BILL_MODE_CD END PRE_MODE,CASE WHEN POL_CSTAT_CD IN ('1','2') THEN APE.ANN_PREMIUM12 ELSE APE.ANN_PREMIUM_OTHER END APE,
P.POL_MPREM_AMT,COV.CVG_FACE_AMT,P.POL_APP_RECV_DT,
CLI_UWGDECN_DT,P.POL_APP_CMPLT_DT  
FROM DLKHDIM..DIM_CLIENT CL 
INNER JOIN DLKHDIM..DIM_POLICY_CLIENT PC ON PC.CLI_ID=CL.CLI_ID AND PC.IS_CURRENT=1
INNER JOIN DLKHDIM..DIM_POLICY P ON P.POL_ID=PC.POL_ID AND P.IS_CURRENT=1
INNER JOIN DLKHSTAGE..SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
INNER JOIN DLKHDIM..DIM_COVERAGE COV ON COV.POL_ID=P.POL_ID AND COV.IS_CURRENT=1
INNER JOIN #APE APE ON APE.POL_ID=P.POL_ID
INNER JOIN V_AGENT V ON V.AGT_ID=W.AGT_ID
LEFT JOIN DLKHDIM..DIM_CLIENT_IND I ON CL.CLI_ID=I.CLI_ID AND I.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_CLIENT_CONTACT C ON CL.CLI_ID=C.CLI_ID AND C.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_POLICY_STATUS ST ON P.POL_CSTAT_CD=ST.POLSTAT_CODE
WHERE CL.PREV_UPDT_TS>'2001-01-01' and CL.IS_CURRENT=1 AND CLI_CNTCT_ID_CD='CP'
END
