CREATE PROC [dbo].[SP_ETL_FACT_AXP_AGENT_COM] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_AXP_AGENT_COM WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

INSERT INTO DLKHFACT..FACT_AXP_AGENT_COM
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY, POL_KEY,AGENT_KEY,COV_KEY,P.POL_ID,AGT_ID,COMM_HIST_AMT,COMM_EFF_DT,COMM_HIST_PRCES_DT,P.PLAN_ID,P.POL_PREM_PAY_DUR POL_TERM,POL_CSTAT_CD,PARA.DM_AV_DESC_TXT POL_STAT_DESC,
POL_CREAT_DT,POL_INFC_DT,
AGT_CPREM_AMT COM_PRE,CSC_NAME,TEAM_CODE_1,TEAM_NAME_1,
TEAM_CODE_2,TEAM_NAME_2,TEAM_CODE_3,TEAM_NAME_3,TEAM_CODE_4,TEAM_NAME_4,TEAM_CODE_5,TEAM_NAME_5,TEAM_CODE_6,TEAM_NAME_6,
AGT_CPREM_AMT MODAL_PRE,CVG_ME_FCT,AGT_CPREM_AMT-AGT_CPREM_AMT PRE_BEFORE,AGT_CPREM_AMT PRE_AFTER FROM DLKHDIM..DIM_POLICY P
INNER JOIN SGTB_COMMISSION_HIS COM ON COM.POL_ID=P.POL_ID AND P.IS_CURRENT=1
INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1 AND C.PLAN_ID=COM.CVG_PLAN_ID and C.CVG_NUM=COM.CVG_NUM
INNER JOIN V_AGENT_INFO V ON V.PARTY_ID=COM.AGT_ID
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD'
WHERE COM.COMM_HIST_PRCES_DT=@BRANCH_DATE

END
