-- =============================================
-- HISTORY MODIFIED SCRIPT
-- =============================================
-- [08-Aug-16]: created by sophat
-- [06-Sep-16]: Move script to UAT round 2, DW staging database 
--
-- ================================================

-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 09-AUG-2016
-- Description:	Backup account info. to stage table
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_BATCH_AC_STAGE]
	@BRANCH_CODE AS VARCHAR(3),@BRANCH_DATE AS DATE,
	@BATCH_CODE VARCHAR(15),@BATCH_DESC AS NVARCHAR(MAX),
	@DB_NAME AS VARCHAR(20),@SERVER_NAME AS VARCHAR(20)
AS
BEGIN

	DECLARE @ERROR_CODE VARCHAR(50),@ERROR_MSG NVARCHAR(MAX),@STR_SQL NVARCHAR(MAX),@START_TIME AS DATETIME,
	@END_TIME AS DATETIME,@SQL_CODE AS VARCHAR(6),@PROC_DESC AS VARCHAR(250),@ROWCOUNT INT

	SET @ERROR_CODE=''
	SET @ERROR_MSG=''
	SET @STR_SQL=''
	SET @SQL_CODE=''

	BEGIN TRAN;
	BEGIN TRY

			-- GET ACCOUNT INFORMATION TO THE STAGE
			SET @SQL_CODE='B002'
			SET @START_TIME=GETDATE();

			SELECT @STR_SQL=SQL_SCRIPT FROM ETLM_SQLSCRIPTS E WHERE E.SQL_CODE=@SQL_CODE AND E.BATCH_CODE=@BATCH_CODE;			
			
			IF ISNULL(RTRIM(LTRIM(@STR_SQL)),'')<>''
			BEGIN
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_CODE',@BRANCH_CODE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_DATE',@BRANCH_DATE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@SERVER_NAME',@SERVER_NAME)
					SET @STR_SQL=REPLACE(@STR_SQL,'@DB_NAME',@DB_NAME)
					EXEC sp_executesql @STR_SQL;
					SET @ROWCOUNT = @@RowCount

					-- ACCOUNT BALANCE  
					INSERT INTO BBCDW..FACT_DAILY_AC_BAL
					SELECT 
							CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,
							BR.BRANCH_KEY,AC.ACCOUNT_KEY,C.CUSTOMER_KEY,CP.CUSTOMER_TYPE_KEY,CT.CUST_CAT_KEY,CL.LOCATION_KEY,
							ACL.ACCOUNT_CLASS_KEY,ACT.ACCOUNT_TYPE_KEY,ACS.ACCOUNT_STATUS_KEY,CCY.CCY_KEY,
							B.ACY_OPENING_BAL,B.LCY_OPENING_BAL,B.ACY_CURR_BALANCE,B.LCY_CURR_BALANCE,B.ACY_AVL_BAL,B.ACY_BLOCKED_AMOUNT,
							GETDATE() ETL_DT
							FROM SGTB_ACCOUNT_STAT_BAL B
							INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON B.CUST_AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
							INNER JOIN BBCDW..DIM_CUSTOMER C ON B.CUST_NO=C.CUSTOMER_NO AND C.IS_CURRENT=1
							INNER JOIN BBCDW..DIM_CUST_CATEGORY CT ON CT.CUST_CAT=C.CUSTOMER_CATEGORY 
							INNER JOIN BBCDW..DIM_CUSTOMER_TYPE CP ON C.CUSTOMER_TYPE=CP.CUSTOMER_TYPE
							INNER JOIN BBCDW..DIM_CUST_LOCATION CL ON CL.LOC_CODE=C.LOC_CODE
							INNER JOIN BBCDW..DIM_ACCOUNT_CLASS ACL ON ACL.ACCOUNT_CLASS=B.ACCOUNT_CLASS 
							INNER JOIN BBCDW..DIM_ACCOUNT_TYPE ACT ON ACT.ACCOUNT_TYPE=B.ACCOUNT_TYPE 
							INNER JOIN BBCDW..DIM_ACCOUNT_STATUS ACS ON ACS.ACCOUNT_STATUS=B.ACC_STATUS
							INNER JOIN BBCDW..DIM_CURRENCY CCY ON B.CCY=CCY.CCY_CODE 
							INNER JOIN BBCDW..DIM_BBC_BRANCH BR ON B.BRANCH_CODE=BR.BRANCH_CODE AND BR.IS_CURRENT=1
					WHERE BR.BRANCH_CODE=@BRANCH_CODE;

					-- ACCOUNT STATUS
					INSERT INTO BBCDW..FACT_DAILY_AC_STATUS
					SELECT 
							CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,
							BR.BRANCH_KEY,AC.ACCOUNT_KEY,ACT.ACCOUNT_TYPE_KEY,ACL.ACCOUNT_CLASS_KEY,
							CY.CCY_KEY,S.AC_STAT_NO_DR,S.AC_STAT_NO_CR,S.AC_STAT_BLOCK,S.AC_STAT_STOP_PAY,S.AC_STAT_DORMANT,
							S.AC_STAT_FROZEN,S.ACC_STATUS, GETDATE()
					FROM SGTB_ACCOUNT_STAT_BAL S
					INNER JOIN BBCDW..DIM_BBC_BRANCH BR ON BR.BRANCH_KEY=S.BRANCH_CODE AND BR.IS_CURRENT=1
					INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON S.CUST_AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
					INNER JOIN BBCDW..DIM_ACCOUNT_TYPE ACT ON S.ACCOUNT_TYPE=ACT.ACCOUNT_TYPE
					INNER JOIN BBCDW..DIM_ACCOUNT_CLASS ACL ON S.ACCOUNT_CLASS=ACL.ACCOUNT_CLASS 
					INNER JOIN BBCDW..DIM_CURRENCY CY ON S.CCY=CY.CCY_CODE
					LEFT JOIN BBCDW..FACT_DAILY_AC_STATUS F ON F.ACCOUNT_KEY=AC.ACCOUNT_KEY AND F.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
					WHERE F.ACCOUNT_KEY IS NULL AND BR.BRANCH_CODE=@BRANCH_CODE;

					SET @PROC_DESC= @BATCH_DESC+', SQLCODE - '+@SQL_CODE +': Get account information to stage, RowCount: '+ CAST(@ROWCOUNT  AS VARCHAR(100))
					SET @END_TIME=GETDATE()
					EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'C',@PROC_DESC,@START_TIME,@END_TIME,'','',@STR_SQL

					--SELECT 1/0
			END 

			-- CREATE ACCOUNT LINKAGE TO THE STAGE
			SET @START_TIME=GETDATE();
			SET @SQL_CODE='B006'
			SELECT @STR_SQL=SQL_SCRIPT FROM ETLM_SQLSCRIPTS E WHERE E.SQL_CODE=@SQL_CODE AND E.BATCH_CODE=@BATCH_CODE;			
			IF ISNULL(RTRIM(LTRIM(@STR_SQL)),'')<>''
			BEGIN
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_CODE',@BRANCH_CODE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_DATE',@BRANCH_DATE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@SERVER_NAME',@SERVER_NAME)
					SET @STR_SQL=REPLACE(@STR_SQL,'@DB_NAME',@DB_NAME)
					EXEC sp_executesql @STR_SQL;
					SET @ROWCOUNT = @@RowCount;
					SET @END_TIME=GETDATE();
					SET @PROC_DESC= @BATCH_DESC+', SQLCODE - '+@SQL_CODE +': Get Account Linkage to stage, RowCount: '+ CAST( @ROWCOUNT  AS VARCHAR(100))
				
					EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'C',@PROC_DESC,@START_TIME,@END_TIME,'','',@STR_SQL
					--SELECT 1/0
					INSERT INTO BBCDW..FACT_CUST_ACCOUNT_LINKAGES
					SELECT DATE_KEY,LIAB_KEY,ACC.ACCOUNT_KEY,CUS.CUSTOMER_KEY,FAC.LIAB_NO,FAC.LIAB_NAME,LINE_CODE,LINE_SERIAL,FAC.LIAB_CCY,MAIN_LINE_ID,CCY_RESTRICTION,REVOLVING_LINE,LINE_START_DATE,LINE_EXPIRY_DATE,LAST_NEW_UTIL_DATE,AVAILABILITY_FLAG,LIMIT_AMOUNT,COLLATERAL_CONTRIBUTION,AVAILABLE_AMOUNT,FAC.OVERALL_LIMIT,TRANSFER_AMOUNT,BLOCK_AMOUNT,MATURED_UTIL,FAC.USER_DEFINE_STATUS,DATE_OF_FIRST_OD,DATE_OF_LAST_OD FROM BBCDW..FACT_DAILY_FACILITY FAC INNER JOIN BBCDW..DIM_LIAB LI ON FAC.LIAB_ID=LI.ID AND LI.IS_CURRENT=1 AND FAC.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
					INNER JOIN SGTB_CUST_AC_LINKAGES AC ON AC.LINKED_REF_NO=CONCAT(LINE_CODE,LINE_SERIAL) and AC.ETL_DATE=@BRANCH_DATE
					INNER JOIN BBCDW..DIM_CUST_ACCOUNT ACC ON ACC.CUST_AC_NO=AC.CUST_AC_NO AND ACC.IS_CURRENT=1
					INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUSTOMER_NO AND CUS.IS_CURRENT=1
					WHERE FAC.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)

			END 
	END TRY
	BEGIN CATCH
			SELECT 
					@ERROR_CODE=ERROR_NUMBER(),
					@ERROR_MSG=ERROR_MESSAGE(),
					@END_TIME=GETDATE()
			
			IF @@TRANCOUNT>0 
				ROLLBACK TRAN
			PRINT ('ETL Processing fail on batch '+ @BATCH_CODE +'. Transaction Rollbacked!')

			SET @PROC_DESC='Error batch '+@BATCH_DESC+' with SQLCODE: '+ @SQL_CODE;

			EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'E',@PROC_DESC,@START_TIME,@END_TIME,@ERROR_CODE,@ERROR_MSG,@STR_SQL

	END CATCH;

	IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRAN;
		
	END;
END
