CREATE PROC [dbo].[SP_ETL_FACT_IACR] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCDW..FACT_DAILY_IACR_LOAN WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END
INSERT INTO  BBCDW..FACT_DAILY_IACR_LOAN  
(DATE_KEY,BRANCH_KEY,LOAN_AC_KEY,ACCOUNT_KEY,CUSTOMER_KEY,PRODUCT_KEY,PRODUCT_CATE_KEY,CURRENCY_KEY,  RM_KEY, UDF_STATUS_KEY,  FINANCED_AMT,DISBURSED_AMT, TOTAL_PRINCIPAL,PRINCIPAL_PAID,PRINCIPAL_OS ,INTEREST_RATE ,   TOTAL_INTEREST,INTEREST_PAID, INTEREST_OS ,  INTEREST_ACCRUED ,INTEREST_ACCRUED_BAL,TOTAL_ACCRUED , LAST_PRINCIPAL_BAL,   LAST_INTEREST_BAL,START_UNPAID_DATE,OVERDUE_DAY ,  PRINCIPAL_OVERDUE,INTEREST_OVERDUE,EMI_AMOUNT,ODIN,ODPR,TENOR,LA.LAST_INSTALLMENT,ETL_DT)  
SELECT    CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,   BR.BRANCH_KEY,   LAC.LOAN_AC_KEY,   AC.ACCOUNT_KEY,   C.CUSTOMER_KEY,   PR.PRODUCT_KEY,   PC.PRODUCT_CATE_KEY,   CY.CCY_KEY,   ISNULL(RM.RM_KEY,1) RM_KEY,    ACS.ACCOUNT_STATUS_KEY UDF_STATUS_KEY,   S.AMOUNT_FINANCED,   S.AMOUNT_DISBURSED,   isnull(S.TOTAL_PRINCIPAL,0) TOTAL_PRINCIPAL,   isnull(S.PRINCIPAL_PAID,0) PRINCIPAL_PAID,   isnull(S.PRINCIPAL_OS,0) PRINCIPAL_OS,   isnull(LAC.INT_RATE,0),  isnull(S.TOTAL_INTEREST,0),   isnull(S.INTEREST_PAID,0),   isnull(S.INTEREST_OS,0),   S.ACCR_AMT INTEREST_ACCRUED, isnull(S.ACCR_BAL+ACCR_AMT-S.INTEREST_PAID,0) INTEREST_ACCRUED_BAL,   S.TOTAL_ACCRUED,   S.LAST_PRINCIPAL_BAL,   S.LAST_INTEREST_BAL,   S.START_UNPAID_DATE,   S.DAY_OVERDUE,   S.PRIN_OVERDUE,   S.INT_OVERDUE,S.EMI_AMOUNT,S.ODIN,S.ODPR,S.TENOR,LA.LAST_INSTALLMENT,   GETDATE() ETL_DT  FROM BBCDW..DIM_LOAN_ACCOUNT LAC  
INNER JOIN SGTB_LOAN_IACR_LOAN S ON LAC.LOAN_AC_NO=S.ACCOUNT_NUMBER AND LAC.IS_CURRENT=1  
INNER JOIN  BBCDW..DIM_CL_PRODUCT PR ON S.PRODUCT_CODE = PR.PRODUCT_CODE AND PR.IS_CURRENT=1  
INNER JOIN  BBCDW..DIM_CL_PRODUCT_CATE PC ON S.PRODUCT_CATEGORY=PC.PRODUCT_CATEGORY   
INNER JOIN  BBCDW..DIM_BBC_BRANCH BR ON S.BRANCH_CODE=BR.BRANCH_CODE AND BR.IS_CURRENT=1  
INNER JOIN  BBCDW..DIM_CUSTOMER C ON S.CUSTOMER_ID=C.CUSTOMER_NO AND C.IS_CURRENT=1  
INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON S.ACCOUNT_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1  
INNER JOIN  BBCDW..DIM_CURRENCY CY ON S.CURRENCY=CY.CCY_CODE   
INNER JOIN  BBCDW..DIM_ACCOUNT_STATUS ACS ON S.USER_DEFINED_STATUS=ACS.ACCOUNT_STATUS  
LEFT JOIN  BBCDW..DIM_RELATION_MANAGER RM ON C.RM_ID=RM.RM_ID AND S.BRANCH_CODE=RM.BRANCH_CODE  
LEFT JOIN (select MAX(DUE_DATE) LAST_INSTALLMENT,ACCOUNT_NUMBER from SGTB_LOAN_PAYMENT where PAID_DATE<=@BRANCH_DATE GROUP BY ACCOUNT_NUMBER) LA ON S.ACCOUNT_NUMBER=LA.ACCOUNT_NUMBER
END
