CREATE PROC [dbo].[SP_ETL_FACT_DEP_PER_CAM] @DATE AS DATE,@IS_RE_PROC BIT=0
AS
BEGIN
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCNBCMART..FACT_TWICE_WEEK_DEP_PERFORM WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112);
	END
--DECLARE @STARTDATE DATE=DATEADD(DAY,-14,@ENDATE)
  IF OBJECT_ID('tempdb..#BAL') IS NOT NULL
  DROP TABLE #BAL
    IF OBJECT_ID('tempdb..#TRAN') IS NOT NULL
  DROP TABLE #TRAN
      IF OBJECT_ID('tempdb..#TRAN1') IS NOT NULL
  DROP TABLE #TRAN1
  IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
    IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
  DROP TABLE #TMP1
      IF OBJECT_ID('tempdb..#FINAL') IS NOT NULL
  DROP TABLE #FINAL
SELECT DATE_KEY,GL.GL_CODE,PARA.CUST_TYPE,PARA.ACCOUNT_TYPE,
SUM(OPN_CR_LCY)-SUM(OPN_DR_LCY) OPEN_BALANCE,PARA.PARENT_GL INTO #BAL  FROM BBCDW..FACT_DAILY_GL_BAL BAL 
INNER JOIN BBCDW..DIM_GLMASTER GL ON BAL.GL_KEY=GL.GL_KEY AND IS_CURRENT=1
INNER JOIN BBCDW..DIM_CURRENCY CUR ON CUR.CCY_KEY=BAL.CCY_KEY AND CUR.IS_USED=1  
INNER JOIN BBCNBCMART..DIM_NBC_DEPOSIT_PER PARA ON PARA.GL_CODE=GL.GL_CODE
WHERE   DATE_KEY= CONVERT(VARCHAR,CAST(@DATE AS DATE),112)
GROUP BY DATE_KEY,GL.GL_CODE,CUR.CCY_CODE,PARA.PARENT_GL,CUST_TYPE,PARA.ACCOUNT_TYPE,NO
ORDER BY NO;

SELECT DATE_KEY,GL.GL_CODE,PARA.CUST_TYPE,PARA.ACCOUNT_TYPE,
SUM(CR_MOV_LCY) DEPOSIT,SUM(DR_MOV_LCY) WITHDRAW,PARA.PARENT_GL INTO #TRAN  FROM BBCDW..FACT_DAILY_GL_BAL BAL 
INNER JOIN BBCDW..DIM_GLMASTER GL ON BAL.GL_KEY=GL.GL_KEY AND IS_CURRENT=1
INNER JOIN BBCDW..DIM_CURRENCY CUR ON CUR.CCY_KEY=BAL.CCY_KEY AND CUR.IS_USED=1  
INNER JOIN BBCNBCMART..DIM_NBC_DEPOSIT_PER PARA ON PARA.GL_CODE=GL.GL_CODE
WHERE   DATE_KEY= CONVERT(VARCHAR,CAST(@DATE AS DATE),112)
GROUP BY DATE_KEY,GL.GL_CODE,CUR.CCY_CODE,PARA.PARENT_GL,CUST_TYPE,PARA.ACCOUNT_TYPE,NO
ORDER BY NO;

SELECT DATE_KEY,PARA.GL_CODE,PARA.CUST_TYPE,PARA.ACCOUNT_TYPE,SUM(OPEN_BALANCE) OPEN_BALANCE INTO #TMP1 FROM BBCNBCMART..DIM_NBC_DEPOSIT_PER PARA
LEFT JOIN #BAL ON PARA.GL_CODE=#BAL.GL_CODE GROUP BY DATE_KEY,PARA.GL_CODE,PARA.CUST_TYPE,PARA.ACCOUNT_TYPE

SELECT GL_CODE,CUST_TYPE,ACCOUNT_TYPE,SUM(DEPOSIT) DEPOSIT,SUM(WITHDRAW) WITHDRAW INTO #TRAN1 FROM #TRAN
GROUP BY GL_CODE,CUST_TYPE,ACCOUNT_TYPE HAVING (SUM(DEPOSIT)>0 OR SUM(WITHDRAW)>0)

SELECT DATE_KEY,t.GL_CODE,t.CUST_TYPE,t.ACCOUNT_TYPE,(t.OPEN_BALANCE) OPEN_BALANCE,(tr.DEPOSIT) DEPOSIT,(tr.WITHDRAW) WITHDRAW INTO #FINAL FROM #TMP1 T full JOIN #TRAN1 TR ON T.GL_CODE=TR.GL_CODE WHERE T.DATE_KEY IS NOT NULL

INSERT INTO BBCNBCMART..FACT_TWICE_WEEK_DEP_PERFORM
SELECT DATE_KEY,@DATE,@DATE,ACCOUNT_TYPE,GL_KEY,CUST_TYPE,ISNULL(OPEN_BALANCE,0) OPEN_BALANCE,ISNULL(DEPOSIT,0) DEPOSIT,ISNULL(WITHDRAW,0) WITHDRAW, GETDATE() FROM #FINAL F INNER JOIN BBCDW..DIM_GLMASTER GL ON F.GL_CODE=GL.GL_CODE

END
