CREATE PROCEDURE [dbo].[SP_ETL_FACT_BC]
	@BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCDW..FACT_BC WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
END
IF OBJECT_ID('tempdb..#SGTB_BC') IS NOT NULL
DROP TABLE #SGTB_BC

select B.* into #SGTB_BC from SGTB_BC B INNER JOIN (SELECT BCREFNO,MAX(VERSION_NO) VERSION_NO FROM SGTB_BC GROUP BY BCREFNO) B1 
ON B.BCREFNO=B1.BCREFNO AND B.VERSION_NO=B1.VERSION_NO AND B.EVENT_CODE IN ('INIT','AMND')
INNER JOIN SGTB_CONTRACT C ON C.CONTRACT_REF_NO=B.BCREFNO AND C.CONTRACT_STATUS<>'V'
INSERT INTO BBCDW..FACT_BC
SELECT cast(CONVERT(VARCHAR,@BRANCH_DATE,112) as int) DATE_KEY,CUS.LOCAL_BRANCH,B.BCREFNO,TXN_DATE,B.VALUE_DATE,MATURITY_DATE,LC_ISSUE_DATE,TENOR_DAYS,BILL_CCY,BILL_AMT_LCY,CUSTOMER_ID,CUSTOMER_PARTY_TYPE,TENOR_CODE,
CASE WHEN WAIVER='Y' THEN 0 ELSE SUM(CHARGE_AMOUNT) END CHARGE_AMOUNT,FA.APPROVE_AMOUNT LIMIT_AMOUNT,L.LIMIT_AMOUNT UTILISATION,
DSP_EFF_LINE_AMOUNT-L.LIMIT_AMOUNT REMAINING_BALANCE,LINKAGE_TYPE,LINKAGE_PERCENTAGE,LINKED_REF_NO,REVOLVING_LINE,FULL_NAME,case when CUS.COUNTRY='KHM' THEN 'R' ELSE 'N' END RESIDENT_STATUS,
ST.ACCOUNT,PRO.PRODUCT_CODE,PRO.PRODUCT_DESCRIPTION,CODE.LOV_DESC CODE,OWN.LOV_DESC OWN,CRR.LOV CRR,SI.LOV SI
 FROM #SGTB_BC B 
INNER JOIN SGTB_BCLIMITS L ON B.BCREFNO=L.BCREFNO
INNER JOIN (select BCREFNO,MAX(EVENT_SEQ_NO) EVE from SGTB_BCLIMITS group by BCREFNO) E on E.EVE=L.EVENT_SEQ_NO and E.BCREFNO=B.BCREFNO
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=B.CUSTOMER_ID AND IS_CURRENT=1
INNER JOIN BBCDW..DIM_CS_PRODUCT PRO ON PRO.PRODUCT_CODE=SUBSTRING(B.BCREFNO,4,4)
LEFT JOIN SGTB_BCCHARGE C ON B.BCREFNO=C.CONTRACT_REF_NO AND VERSION_NO=C.EVENT_SEQ_NO
LEFT JOIN BBCDW..FACT_DAILY_FACILITY FA ON L.LINKED_REF_NO=CONCAT(FA.LINE_CODE,FA.LINE_SERIAL) AND FA.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
LEFT JOIN (SELECT DISTINCT CONTRACT_REF_NO,ACCOUNT FROM SGTB_SETTLEMENT WHERE TRANSFER_TYPE='C') ST ON B.BCREFNO=ST.CONTRACT_REF_NO
LEFT JOIN BBCDW..DIM_UDF_VAL V ON CUS.CUSTOMER_NO=V.REC_KEY AND V.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_UDF_LOV CODE ON V.FIELD_VAL_15=CODE.LOV AND CODE.FIELD_NAME='INDUSTRY_CODE'
LEFT JOIN BBCDW..DIM_UDF_LOV OWN ON V.FIELD_VAL_16=OWN.LOV AND OWN.FIELD_NAME='OWNERSHIP_CIF'
LEFT JOIN BBCDW..DIM_UDF_LOV CRR ON V.FIELD_VAL_17=CRR.LOV AND CRR.FIELD_NAME='CCR_CIF'
LEFT JOIN BBCDW..DIM_UDF_LOV SI ON V.FIELD_VAL_18=SI.LOV AND SI.FIELD_NAME='SI_CIF'
GROUP BY B.BCREFNO,TXN_DATE,B.VALUE_DATE,MATURITY_DATE,LC_ISSUE_DATE,TENOR_DAYS,BILL_CCY,BILL_AMT_LCY,CUSTOMER_ID,CUSTOMER_PARTY_TYPE,TENOR_CODE,
WAIVER,LINKAGE_TYPE,LINKAGE_PERCENTAGE,LINKED_REF_NO,FA.APPROVE_AMOUNT,DSP_EFF_LINE_AMOUNT,L.LIMIT_AMOUNT,FULL_NAME,RESIDENT_STATUS,CUS.LOCAL_BRANCH,CUS.COUNTRY
,ST.ACCOUNT,PRO.PRODUCT_CODE,PRO.PRODUCT_DESCRIPTION,REVOLVING_LINE,CODE.LOV_DESC,OWN.LOV_DESC,CRR.LOV,SI.LOV 

END
