CREATE PROC SP_ETL_FACT_LC_BG @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_UNUSE_POL WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

select DISTINCT CONVERT(VARCHAR,GETDATE(),112) DATE_KEY,CL.CLI_KEY,CL.CLI_ID Client_No,CL.PREV_UPDT_USER_ID User_Input,CASE WHEN CLI_NM_CHNG_DT IS NULL THEN CL.PREV_UPDT_TS ELSE CLI_NM_CHNG_DT END CREATION_DATE,
I.CLIIND_KEY,I.ENTR_SUR_NM Family_Name,I.ENTR_GIV_NM Given_Name,CLI_BTH_DT Birth_Date,CLI_ID_NUM Client_Idenfication_Number,CLI_SEX_CD Sex,CLI_SMKR_CD Smoker,CLI_MARIT_STAT_CD Marital_Status,
CLI_RES_TYP_CD Resident_Type,AD.CLIADD_KEY,CLI_ADDR_LN_1_TXT Address,CLI_CITY_NM_TXT City,CLI_CITY_NM_TXT City_Privince,CASE WHEN CLI_CTRY_CD='VN' THEN 'CA' ELSE CLI_CTRY_CD END Country,D.ETBL_DESC_TXT District,E.ETBL_DESC_TXT Ward,CLI_PSTL_CD Postal_Zipcode,CL.CLI_DOC_TYP Declaration_Form,O.ETBL_DESC_TXT Occupation 
from DLKHDIM..DIM_CLIENT CL
LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE O ON CL.OCCP_ID=O.ETBL_VALU_ID 
LEFT JOIN DLKHDIM..DIM_CLIENT_IND I ON CL.CLI_ID=I.CLI_ID AND I.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_CLIENT_ADD AD ON CL.CLI_ID=AD.CLI_ID AND AD.IS_CURRENT=1
LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE E ON AD.CLI_ADDR_MUN_CD=E.ETBL_VALU_ID AND E.ETBL_TYP_ID='MCPCD'
LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE D ON AD.CLI_ADDR_CNTY_CD=D.ETBL_VALU_ID AND D.ETBL_TYP_ID='CTYPC'
WHERE CL.PREV_UPDT_TS>'2001-01-01' and CL.IS_CURRENT=1
END
