CREATE PROC [dbo].[SP_ETL_FACT_INCOME_STAT] @DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCNBCMART..FACT_INCOME_STATE WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112);
END
 IF OBJECT_ID('tempdb..#INCOME') IS NOT NULL
  DROP TABLE #INCOME
 IF OBJECT_ID('tempdb..#INCOME1') IS NOT NULL
  DROP TABLE #INCOME1
 IF OBJECT_ID('tempdb..#MINUS') IS NOT NULL
  DROP TABLE #MINUS
 IF OBJECT_ID('tempdb..#MINUS1') IS NOT NULL
  DROP TABLE #MINUS1
 IF OBJECT_ID('tempdb..#RESULT') IS NOT NULL
  DROP TABLE #RESULT
   IF OBJECT_ID('tempdb..#RESULT_K') IS NOT NULL
  DROP TABLE #RESULT_K
   IF OBJECT_ID('tempdb..#RESULT_O') IS NOT NULL
  DROP TABLE #RESULT_O
   IF OBJECT_ID('tempdb..#FINAL') IS NOT NULL
  DROP TABLE #FINAL
Declare @ID int, @GL varchar(max),@Des nvarchar(100),@max int,@min int=1
CREATE TABLE #INCOME (ID INT,GL VARCHAR(100),ITEM_KEY INT,DESCRIPTION VARCHAR(100))
CREATE TABLE #MINUS (ID INT,GL VARCHAR(100),ITEM_KEY INT,DESCRIPTION VARCHAR(100))
select @max=MAX(ITEM_KEY) from BBCNBCMART..DIM_INCOME_STAT 
while @min<=@max

	BEGIN
		select @ID=ITEM_KEY,@GL=GL,@Des=Description from BBCNBCMART..DIM_INCOME_STAT where ITEM_KEY=@min
		INSERT INTO #INCOME
		select * from BBCDW..FnSplit_With_Desc(@GL,',',@ID,@Des)
		SET @min=@min+1
	END
SET @ID=0
SET @GL=''
SET @Des=''
SET @max=0
SET @min=1
select @max=MAX(ID) from BBCNBCMART..DIM_INCOME_STAT_MI
while @min<=@max

	BEGIN
		select @ID=ITEM_KEY,@GL=GL,@Des=Description from BBCNBCMART..DIM_INCOME_STAT_MI where ID=@min
		INSERT INTO #MINUS
		select * from BBCDW..FnSplit_With_Desc(@GL,',',@ID,@Des)
		SET @min=@min+1
	END
	SELECT DATE_KEY,ITEM_KEY,DESCRIPTION,SUM(CASE WHEN GL.CBANK_LINE_CR!=LEFT(GL.PARENT_GL,6) THEN CLO_LCY_BAL ELSE 0 END) CLO_LCY_BAL,CU.CCY_CODE INTO #INCOME1 FROM BBCDW..FACT_DAILY_GL_BAL BAL INNER JOIN BBCDW..DIM_GLMASTER GL ON BAL.GL_KEY=GL.GL_KEY AND IS_CURRENT=1
	INNER JOIN #INCOME COM ON COM.GL=GL.CBANK_LINE_CR
	INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=BAL.CCY_KEY AND IS_CURRENT=1 WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112) 
	GROUP BY DATE_KEY,ITEM_KEY,DESCRIPTION,CU.CCY_CODE

	SELECT DATE_KEY,ITEM_KEY,DESCRIPTION,SUM(CLO_LCY_BAL) CLO_LCY_BAL,CU.CCY_CODE INTO #MINUS1 FROM BBCDW..FACT_DAILY_GL_BAL BAL INNER JOIN BBCDW..DIM_GLMASTER GL ON BAL.GL_KEY=GL.GL_KEY AND IS_CURRENT=1
	INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=BAL.CCY_KEY AND IS_CURRENT=1
	INNER JOIN #MINUS COM ON COM.GL=GL.CBANK_LINE_CR WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112)
	GROUP BY DATE_KEY,ITEM_KEY,DESCRIPTION,CU.CCY_CODE

	SELECT COM.DATE_KEY,COM.ITEM_KEY,COM.DESCRIPTION,(COM.CLO_LCY_BAL - ISNULL(MIN.CLO_LCY_BAL,0)) CLO_LCY_BAL,COM.CCY_CODE INTO #RESULT FROM #INCOME1 COM LEFT JOIN #MINUS1 MIN ON COM.ITEM_KEY=MIN.ITEM_KEY AND COM.CCY_CODE=MIN.CCY_CODE
	select ITEM_KEY,DESCRIPTION,sum(CLO_LCY_BAL) CLO_LCY_BAL into #RESULT_K from #RESULT where CCY_CODE='KHR' group by DATE_KEY,ITEM_KEY,DESCRIPTION
	select ITEM_KEY,DESCRIPTION,sum(CLO_LCY_BAL) CLO_LCY_BAL into #RESULT_O from #RESULT where CCY_CODE<>'KHR' group by DATE_KEY,ITEM_KEY,DESCRIPTION
	
	SELECT COM.*,ISNULL(RE.CLO_LCY_BAL,0) CLO_LCY_BAL into #FINAL  FROM BBCNBCMART..DIM_INCOME_STAT COM LEFT JOIN #RESULT_K RE ON COM.ITEM_KEY=RE.ITEM_KEY
	INSERT INTO BBCNBCMART..FACT_INCOME_STATE
	SELECT CONVERT(VARCHAR,@DATE,112),COM.*,ISNULL(RE.CLO_LCY_BAL,0) CLO_FCY_BAL   FROM #FINAL COM LEFT JOIN #RESULT_O RE ON COM.ITEM_KEY=RE.ITEM_KEY
END
