
-- =============================================
-- Author:		HING TIPI
-- Create date: 10-10-2017
-- Description:	SETTLEMENT
-- =============================================
CREATE  PROCEDURE [dbo].[SP_ETL_BATCH_BC_CHARGE]
	@BRANCH_CODE AS VARCHAR(3),@BRANCH_DATE AS DATE,
	@BATCH_CODE VARCHAR(15),@BATCH_DESC AS NVARCHAR(MAX),
	@DB_NAME AS VARCHAR(20),@SERVER_NAME AS VARCHAR(20)
AS
BEGIN
	DECLARE @ERROR_CODE VARCHAR(50),@ERROR_MSG NVARCHAR(MAX),@STR_SQL NVARCHAR(MAX),
			@START_TIME AS DATETIME,@END_TIME AS DATETIME,@SQLCODE AS VARCHAR(6),@PROC_DESC AS VARCHAR(250),@ROWCOUNT INT=0

	SET @ERROR_CODE=''
	SET @ERROR_MSG=''
	SET @STR_SQL=''

	BEGIN TRAN;
	BEGIN TRY
			SET @SQLCODE='B020'
			SET @START_TIME=GETDATE();

			SELECT @STR_SQL=SQL_SCRIPT FROM ETLM_SQLSCRIPTS E WHERE E.SQL_CODE=@SQLCODE AND E.BATCH_CODE=@BATCH_CODE;			
			IF ISNULL(RTRIM(LTRIM(@STR_SQL)),'')<>''
			BEGIN
					
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_DATE',@BRANCH_DATE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@BRANCH_CODE',@BRANCH_CODE)
					SET @STR_SQL=REPLACE(@STR_SQL,'@SERVER_NAME',@SERVER_NAME)
					SET @STR_SQL=REPLACE(@STR_SQL,'@DB_NAME',@DB_NAME)
					EXEC sp_executesql @STR_SQL;
					SET @ROWCOUNT = @@RowCount;
					--SELECT 1/0
			END 
	END TRY
	BEGIN CATCH
			SELECT 
					@ERROR_CODE=ERROR_NUMBER(),
					@ERROR_MSG=ERROR_MESSAGE()
			
			IF @@TRANCOUNT>0 
				ROLLBACK TRAN
			PRINT ('ETL Processing fail on batch '+ @BATCH_CODE +'. Transaction Rollbacked!')
			SET @PROC_DESC='Error batch '+@BATCH_DESC+' with SQLCODE: '+ @SQLCODE;
			SET @END_TIME=GETDATE()
			EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'E',@PROC_DESC,@START_TIME,@END_TIME,@ERROR_CODE,@ERROR_MSG,@STR_SQL
	END CATCH;

	IF @@TRANCOUNT > 0
	BEGIN
		COMMIT TRAN;

		SET @END_TIME=GETDATE();
		SET @PROC_DESC= @BATCH_DESC+', SQLCODE: '+@SQLCODE +', RowCount: '+ CAST(@ROWCOUNT  AS VARCHAR(100))
		EXEC SP_ETL_PROC_WRITE_LOG @BRANCH_CODE,@BRANCH_DATE,@BATCH_CODE,'C',@PROC_DESC,@START_TIME,@END_TIME,'','',@STR_SQL
	END;

END
