
CREATE PROC [dbo].[SP_ETL_FACT_AXP_AA] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

	--DECLARE @BRANCH_DATE	DATE = '2024-05-25'
	--		,@IS_RE_PROC BIT = 1

	IF @IS_RE_PROC = 1 DELETE FROM  DLKHFACT..FACT_AXP_AA WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

	DROP TABLE IF EXISTS #TMP
	DROP TABLE IF EXISTS #CVG
  
	SELECT * INTO #CVG FROM DLKHDIM..DIM_COVERAGE

 
	UPDATE T SET T.CVG_MPREM_AMT=N.CVG_MPREM_AMT 
	FROM #CVG T 
	INNER JOIN (
		SELECT MAX(COV_KEY) COV_KEY,POL_ID,CVG_NUM,CVG_MPREM_AMT 
		FROM DLKHDIM..DIM_COVERAGE WHERE CVG_CSTAT_CD = '1' GROUP BY POL_ID,CVG_MPREM_AMT,CVG_NUM
	)N ON T.POL_ID=N.POL_ID AND T.CVG_NUM=N.CVG_NUM  
	WHERE  T.CVG_MPREM_AMT = 0

	SELECT DISTINCT 
		V.AG_KEY
		,P.POL_KEY
		,VC.CLI_KEY
		,VC.CLIIND_KEY
		,P.POL_ID
		,P.PLAN_ID
		,RTRIM(PA.ETBL_DESC_TXT) PLAN_NAME
		,RTRIM(VC.ENTR_SUR_NM) ENTR_SUR_NM
		,RTRIM(VC.ENTR_GIV_NM) ENTR_GIV_NM
		,P.POL_ISS_EFF_DT CS_REV_DT
		,P.POL_APP_RECV_DT PRO_LOAD_DT
		,P.POL_INFC_DT POL_ISS_DT
		,C.CVG_MPREM_AMT
		,P.POL_BILL_MODE_CD
		,C.CVG_MPREM_AMT * (CASE WHEN CAST(POL_BILL_MODE_CD AS INT)>0 THEN 12/CAST(POL_BILL_MODE_CD AS INT) ELSE 1 END) AS AFYP
		,C.CVG_NUM -- Add this line: 11/11/2022
		,P.POL_CSTAT_CD
		,RTRIM(PARA.DM_AV_DESC_TXT) DM_AV_DESC_TXT
		,C.CVG_FACE_AMT CVG_SUM_INS_AMT
		--,C.CVG_MAT_XPRY_DUR POL_PREM_PAY_DUR --REMOVE 13/02/2023
		,TEM.CVG_MAT_XPRY_DUR POL_PREM_PAY_DUR --ADD 13/02/2023
		,W.AGT_ID AGENT_CODE
		,W.POL_AGT_SHR_PCT
		,CASE WHEN V.CHANNEL = 'BA' THEN 'BANCA' WHEN V.CHANNEL = 'AG' THEN 'AGENCY' ELSE NULL END AGT_CHANNEL
		,C.CVG_ME_FCT
		,C.CVG_MPREM_AMT-C.CVG_ME_PREM_AMT PRE_BEFORE
		,C.CVG_MPREM_AMT PRE_AFTER
		,C.CVG_CSTAT_CD 
	INTO #TMP
	FROM DLKHDIM..DIM_POLICY P
	INNER JOIN SGTB_POLICY_CLIENT PC ON P.POL_ID = PC.POL_ID AND P.IS_CURRENT=1 AND PC.POL_CLI_REL_SUB_CD='P' -- ADD PC.POL_CLI_REL_SUB_CD='P' :06/03/2023
	INNER JOIN #CVG C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1 
	INNER JOIN V_CLI_INFO VC ON  VC.CLI_ID = PC.CLI_ID
	INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
	INNER JOIN SGTM_COVERAGE TEM ON TEM.POL_ID=P.POL_ID AND P.POL_BASE_CVG_NUM=TEM.CVG_NUM
	LEFT JOIN V_AGENT V ON V.AGT_ID=W.AGT_ID 
	LEFT JOIN SGTB_EDITTABLE PA ON P.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
	LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
	WHERE C.CVG_MAT_XPRY_DUR > 0 AND P.IS_CURRENT = 1

	DELETE FROM #TMP WHERE CVG_CSTAT_CD='B' AND POL_CSTAT_CD NOT IN ('B','E') 
	DELETE FROM #TMP WHERE CVG_CSTAT_CD='R' AND POL_CSTAT_CD != 'R'
	DELETE FROM #TMP WHERE CVG_CSTAT_CD='S' AND POL_CSTAT_CD NOT IN ('B','E') 
	DELETE FROM #TMP WHERE CVG_CSTAT_CD='S' AND POL_CSTAT_CD != 'R'

	INSERT INTO  DLKHFACT..FACT_AXP_AA
	SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY
		,AG_KEY
		,POL_KEY
		,CLI_KEY
		,CLIIND_KEY
		,POL_ID
		,PLAN_ID
		,PLAN_NAME
		,ENTR_SUR_NM
		,ENTR_GIV_NM
		,CS_REV_DT
		,PRO_LOAD_DT
		,POL_ISS_DT
		,SUM(CVG_MPREM_AMT) CVG_MPREM_AMT
		,POL_BILL_MODE_CD
		,SUM(AFYP) AFYP
		,POL_CSTAT_CD
		,DM_AV_DESC_TXT
		,SUM(CVG_SUM_INS_AMT) CVG_SUM_INS_AMT
		,POL_PREM_PAY_DUR
		,AGENT_CODE
		,POL_AGT_SHR_PCT
		,AGT_CHANNEL
		,CVG_ME_FCT
		,SUM(PRE_BEFORE) PRE_BEFORE
		,SUM(PRE_AFTER) PRE_AFTER 
	FROM #TMP
	GROUP BY AG_KEY,POL_KEY,CLI_KEY,CLIIND_KEY,POL_ID,PLAN_ID,PLAN_NAME,ENTR_SUR_NM,ENTR_GIV_NM,CS_REV_DT,PRO_LOAD_DT,POL_ISS_DT,POL_BILL_MODE_CD,DM_AV_DESC_TXT,AGENT_CODE,POL_AGT_SHR_PCT,AGT_CHANNEL,POL_CSTAT_CD,CVG_ME_FCT,POL_PREM_PAY_DUR

END
