-- =============================================
-- Author:		HING TIPI
-- Create date: 20-DEC-2018
-- Description:	 RUN ETL BATCH PROCESS
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_PROC_BATCH_BBOD] 
		@BRANCH_CODE AS VARCHAR(3),@BRANCH_DATE AS DATE,@IS_ERROR BIT OUTPUT
AS
BEGIN

DECLARE @TAB TABLE(ID INT IDENTITY,BATCH_CODE VARCHAR(15),BATCH_NAME VARCHAR(100),BATCH_SCRIPT NVARCHAR(MAX),DBNAME VARCHAR(50),SERVER_NAME VARCHAR(50))
DECLARE @COUNT INT,@MAX INT,@BATCH_CODE VARCHAR(15),@BATCH_NAME VARCHAR(100),@BATCH_SCRIPT NVARCHAR(MAX),@DBNAME VARCHAR(50),@SERVER_NAME VARCHAR(50)
DECLARE @ERROR_CODE AS VARCHAR(50),@ERROR_MSG AS NVARCHAR(MAX)

SET @COUNT=1

INSERT INTO @TAB
SELECT 
		BATCH_CODE,BATCH_NAME,BATCH_SCRIPT, [DB_NAME],SERVER_NAME
FROM ETLM_BATCH B 
WHERE B.BATCH_TYPE='B' AND B.IS_ENABLED=1 
AND B.EFFECTIVE_DATE<=@BRANCH_DATE
AND PARENT_BATCH=1 -- BEFORE BOD
AND B.BATCH_CODE IN(SELECT BATCH_CODE FROM ETLM_BATCH_BRANCH WHERE BRANCH_CODE=@BRANCH_CODE)
--** Remove below condition to be able to run batch multi time per day
--AND BATCH_CODE NOT IN(SELECT P.BATCH_CODE 
--						FROM ETLB_BATCH_PROC_DETAIL P 
--						INNER JOIN ETLM_BATCH B1 ON P.BATCH_CODE=B1.BATCH_CODE
--						WHERE P.BRANCH_CODE=@BRANCH_CODE 
--						AND P.BRANCH_DATE=@BRANCH_DATE 
--						AND P.PROC_TYPE='C'
--						AND P.PARENT_BATCH=1
--						AND B1.BATCH_TYPE='B'
--		)
ORDER BY BATCH_NUM;

SELECT @MAX=@@IDENTITY;
WHILE @COUNT<=@MAX BEGIN
	SET @IS_ERROR=0
	
	SELECT @BATCH_CODE=BATCH_CODE,@BATCH_NAME=BATCH_NAME,
			@BATCH_SCRIPT=BATCH_SCRIPT,@DBNAME=DBNAME,@SERVER_NAME=SERVER_NAME 
	FROM @TAB T WHERE ID=@COUNT

	IF ISNULL(@BATCH_SCRIPT,'')<>'' 
	BEGIN
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@BRANCH_CODE',@BRANCH_CODE)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@BRANCH_DATE',@BRANCH_DATE)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@BATCH_CODE',@BATCH_CODE)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@BATCH_DESC',@BATCH_NAME)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@DB_NAME',@DBNAME)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@SERVER_NAME',@SERVER_NAME)

			BEGIN TRAN;
					BEGIN TRY
						PRINT('#Processing batch:  '+@BATCH_CODE+'-'+@BATCH_NAME );
						-- CALL SP BY BATCH PROCESS
						EXEC sp_executesql @BATCH_SCRIPT;
					END TRY
					BEGIN CATCH
						SET @IS_ERROR=1;
						RETURN
					END CATCH;
			COMMIT TRAN;
	END 
	SET @COUNT=@COUNT+1;
END;
			 
END
