CREATE PROC [dbo].[SP_ETL_FACT_LOAN_PAYMENT] @BRANCH_DATE DATE,@IS_RE_PROC BIT
AS
BEGIN
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCDW..FACT_LOAN_PAYMENT WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END

IF OBJECT_ID('tempdb..#PAY') IS NOT NULL
  DROP TABLE #PAY
IF OBJECT_ID('tempdb..#PAY1') IS NOT NULL
  DROP TABLE #PAY1
IF OBJECT_ID('tempdb..#PAR') IS NOT NULL
  DROP TABLE #PAR
IF OBJECT_ID('tempdb..#OUT') IS NOT NULL
  DROP TABLE #OUT

select BRANCH_CODE,ACCOUNT_NUMBER,DUE_DATE,PAID_DATE,SUM(AMOUNT_PAID) AMOUNT_PAID INTO #PAY from SGTB_LOAN_PAYMENT 
where  COMPONENT_NAME in ('MAIN_INT','PRINCIPAL') AND PAID_DATE=@BRANCH_DATE
GROUP BY BRANCH_CODE,ACCOUNT_NUMBER,PAID_DATE,DUE_DATE

SELECT P.BRANCH_CODE,P.ACCOUNT_NUMBER,DUE_DATE,SUM(AMOUNT_DUE) EMI_AMOUNT,(SELECT MIN(NEX.SCHEDULE_DUE_DATE) FROM SGTB_ACCOUNT_SCHEDULE NEX WHERE NEX.COMPONENT_NAME in ('MAIN_INT','PRINCIPAL') AND NEX.ACCOUNT_NUMBER=P.ACCOUNT_NUMBER AND NEX.SCHEDULE_DUE_DATE>P.DUE_DATE) NEXT_PAYMENT_DATE,PAID_DATE,AMOUNT_PAID INTO #PAY1  FROM #PAY P 
INNER JOIN SGTB_ACCOUNT_SCHEDULE SCH ON P.BRANCH_CODE=SCH.BRANCH_CODE AND P.ACCOUNT_NUMBER=SCH.ACCOUNT_NUMBER AND p.DUE_DATE=SCH.SCHEDULE_DUE_DATE	
WHERE COMPONENT_NAME in ('MAIN_INT','PRINCIPAL')
GROUP BY P.BRANCH_CODE,P.ACCOUNT_NUMBER,DUE_DATE,PAID_DATE,AMOUNT_PAID

select BRANCH_CODE,ACCOUNT_NUMBER,DATEDIFF(DAY,DUE_DATE,PAID_DATE) DATELATE,SUM(AMOUNT_PAID) PD_AMOUNT INTO #PAR from SGTB_LOAN_PAYMENT 
where  COMPONENT_NAME in ('ODIN_PNLTY','ODPR_PNLTY')
GROUP BY BRANCH_CODE,ACCOUNT_NUMBER,PAID_DATE,DUE_DATE,PAID_DATE

select LOAN_AC_NO,AMOUNT_DISBURSED-ISNULL(SUM(AMOUNT_PAID),0) OUTSTANDING INTO #OUT from  BBCDW..DIM_LOAN_ACCOUNT CL LEFT JOIN SGTB_LOAN_PAYMENT PAY ON CL.LOAN_AC_NO=PAY.ACCOUNT_NUMBER AND COMPONENT_NAME='PRINCIPAL' AND PAID_DATE<=@BRANCH_DATE
where  ACCOUNT_STATUS<>'V' AND IS_CURRENT=1
GROUP BY LOAN_AC_NO,AMOUNT_DISBURSED

INSERT INTO BBCDW..FACT_LOAN_PAYMENT

SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,P.BRANCH_CODE,PRO.PRODUCT_KEY,LOAN_AC_KEY,CUSTOMER_KEY,ACCOUNT_KEY,P.DUE_DATE,P.EMI_AMOUNT,P.NEXT_PAYMENT_DATE,P.PAID_DATE,AMOUNT_PAID,DATELATE,PD_AMOUNT,O.OUTSTANDING 
FROM #PAY1 P INNER JOIN #OUT O ON P.ACCOUNT_NUMBER=O.LOAN_AC_NO
INNER JOIN BBCDW..DIM_LOAN_ACCOUNT CL ON CL.LOAN_AC_NO=P.ACCOUNT_NUMBER AND CL.IS_CURRENT=1
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=CL.CUSTOMER_ID AND CUS.IS_CURRENT=1
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON AC.CUST_AC_NO=CL.DR_AC_NO AND AC.IS_CURRENT=1
INNER JOIN BBCDW..DIM_CL_PRODUCT PRO ON PRO.PRODUCT_CODE=CL.PRODUCT_CODE AND PRO.IS_CURRENT=1
LEFT JOIN #PAR R ON P.BRANCH_CODE=R.BRANCH_CODE AND P.ACCOUNT_NUMBER=R.ACCOUNT_NUMBER

END
