

CREATE PROC [dbo].[SP_ETL_FACT_PERSISTENCY] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

	--DECLARE @BRANCH_DATE	DATE = '2023-06-30'
	--	,@IS_RE_PROC		BIT = 1

	IF @IS_RE_PROC = 1 DELETE FROM  DLKHFACT..FACT_PERSISTENCY WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

	DROP TABLE IF EXISTS	#POL
	DROP TABLE IF EXISTS	#CVG

	SELECT * INTO #POL FROM (
		SELECT POL_KEY,POL_ID,POL_BILL_MODE_CD, POL_CSTAT_CD,POL_MPREM_AMT,POL_ISS_EFF_DT,POL_INFC_DT, POL_PD_TO_DT_NUM, SERV_AGT_ID , ROW_NUMBER() OVER(PARTITION BY POL_ID ORDER BY START_DT DESC) AS ROW_NUM  FROM DLKHDIM..DIM_POLICY WHERE START_DT <= @BRANCH_DATE 
	) POL WHERE POL.ROW_NUM = 1
	
	-- CALCULATE PREMIUM FROM CVG LVL WHEN POLICY IN LAPSED STATUS
	SELECT SUM(C.CVG_MPREM_AMT) AS CVG_MPREM_AMT, MAX(C.CVG_MAT_XPRY_DUR) AS CVG_MAT_XPRY_DUR, POL.POL_ID INTO #CVG FROM (
		SELECT POL_ID, CVG_MAT_XPRY_DUR,CVG_MPREM_AMT, CVG_CSTAT_CD , ROW_NUMBER() OVER(PARTITION BY POL_ID,CVG_NUM ORDER BY START_DT DESC) AS ROW_NUM FROM DLKHDIM..DIM_COVERAGE WHERE START_DT <= @BRANCH_DATE
	) C
	LEFT JOIN #POL POL ON POL.POL_ID = C.POL_ID 
	WHERE  C.ROW_NUM = 1 AND C.CVG_CSTAT_CD NOT IN ('P','R','G','S','V','I','Y','A','D','E','F','H','T','W','X') 
	GROUP BY POL.POL_ID
	 

	INSERT INTO  DLKHFACT..FACT_PERSISTENCY
	SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY
	,P.POL_KEY
	,CLI.CLI_KEY PO_CLI_KEY
	,AG.AGTC_KEY
	,P.POL_ID
	,PO_ID = PO.CLI_ID 
	,PO_NAME = CONCAT(RTRIM(CLI.ENTR_SUR_NM),' ', RTRIM(CLI.ENTR_GIV_NM))
	,PO_PHONE = RTRIM(CLI.CLI_CNTCT_ID_TXT)
	,P.POL_BILL_MODE_CD
	,POL_TERM = CPREM.CVG_MAT_XPRY_DUR
	,FYP = CASE WHEN P.POL_MPREM_AMT = 0 THEN CPREM.CVG_MPREM_AMT ELSE P.POL_MPREM_AMT END 
	,AFYP =  CASE WHEN P.POL_MPREM_AMT = 0 THEN (12 / CAST(P.POL_BILL_MODE_CD AS INT)) * CPREM.CVG_MPREM_AMT  ELSE (12 / CAST(P.POL_BILL_MODE_CD AS INT)) * P.POL_MPREM_AMT  END 
	,P.POL_CSTAT_CD
	,POL_CSTAT = PS.DM_AV_DESC_TXT
	,SUBMISSION_DT = P.POL_ISS_EFF_DT
	,ISSUANCE_DT = P.POL_INFC_DT
	,P.POL_ISS_EFF_DT
	,POL_PD_TO_DT = DBO.ConvertDate(P.POL_PD_TO_DT_NUM)
	,P.SERV_AGT_ID AGT_ID
	,AD.LeaderId AGT_LEAD_ID
	,AD.LeaderName AGT_LEAD_NAME
	,AD.Branch AGT_BRANCH
	FROM #POL P
	LEFT JOIN DLKHDIM..DIM_POLICY_CLIENT PO ON PO.POL_ID = P.POL_ID AND PO.POL_CLI_REL_TYP_CD = 'O' AND PO.IS_CURRENT = 1
	LEFT JOIN DLKHSTAGE..SGTM_PARA_1 PS ON PS.DM_AV_CD=P.POL_CSTAT_CD AND PS.CO_ID='CP' AND PS.DM_AV_TBL_CD='POL-CSTAT-CD' and PS.DM_AV_DESC_LANG_CD='E'
	LEFT JOIN #CVG CPREM ON CPREM.POL_ID = P.POL_ID
	LEFT JOIN (SELECT *, ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY CLI_ID)  AS ROW_NUM FROM DLKHSTAGE..V_CLI_INFO ) CLI ON CLI.CLI_ID = PO.CLI_ID AND CLI.ROW_NUM = 1
	LEFT JOIN (SELECT *, ROW_NUMBER() OVER(PARTITION BY AGT_ID ORDER BY AGT_ID)  AS ROW_NUM FROM DLKHSTAGE..V_AGENT) AG ON AG.AGT_ID = P.SERV_AGT_ID AND AG.ROW_NUM = 1
	LEFT JOIN DLKHSTAGE..SGTM_AGENT_DETAIL AD ON AD.AgentId = P.SERV_AGT_ID
	WHERE P.POL_CSTAT_CD IN ('1', 'B','E') 
	--AND P.POL_ID = '044404430 '

end
