CREATE PROC [dbo].[SP_ETL_FACT_PRE_COLL] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

 IF OBJECT_ID('tempdb..#POL') IS NOT NULL
  DROP TABLE #POL

  select * into #POL from DLKHDIM..DIM_POLICY
  update #POL set POL_PD_TO_DT_NUM='2019-12-01' where POL_PD_TO_DT_NUM='2019-11-31'
  update #POL set POL_PD_TO_DT_NUM='2020-03-01' where POL_PD_TO_DT_NUM='2020-02-31'

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_COLLECTION WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

INSERT INTO DLKHFACT..FACT_COLLECTION
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,POL_KEY,P.POL_ID,POL_APP_FORM_ID,PARA.DM_AV_DESC_TXT POL_STAT,P.PLAN_ID,POL_BILL_MODE_CD,  RTRIM(LTRIM(CI.ENTR_SUR_NM))+' '+RTRIM(LTRIM(CI.ENTR_GIV_NM)) 
CLI_NAME,CC.CLI_CNTCT_ID_TXT CLI_PHONE2,CC1.CLI_CNTCT_ID_TXT CLI_PHONE1,EM.CLI_CNTCT_ID_TXT EMAIL,AD.CLI_CITY_NM_TXT,POL_PD_TO_DT_NUM,
 DATENAME(DAY,POL_PD_TO_DT_NUM)  _DAY,
 DATEPART(M,POL_PD_TO_DT_NUM)  _MONTH,
 DATENAME(YEAR,POL_PD_TO_DT_NUM)  _YEAR, 
POL_ISS_EFF_DT POL_CREAT_DT,SUM(CV.CVG_MPREM_AMT) PRE_AMT,POL_PREM_SUSP_AMT,POL_OS_DISB_AMT,'' BANK_CASH,V.AGT_ID,V.ENTR_SUR_NM,V.ENTR_GIV_NM,V.AGT_PHON_NUM,D.ETBL_DESC_TXT  
FROM #POL P  INNER JOIN DLKHDIM..DIM_POLICY_CLIENT PC ON PC.POL_ID=P.POL_ID AND P.IS_CURRENT=1 AND PC.IS_CURRENT=1  
INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID  
INNER JOIN DLKHDIM..DIM_CLIENT C ON C.CLI_ID=PC.CLI_ID AND C.IS_CURRENT=1  
INNER JOIN DLKHDIM..DIM_CLIENT_IND CI ON CI.CLI_ID=C.CLI_ID AND CI.IS_CURRENT=1  
INNER JOIN DLKHDIM..DIM_COVERAGE CV ON CV.POL_ID=P.POL_ID AND CV.IS_CURRENT=1 
INNER JOIN DLKHDIM..DIM_CLIENT_ADD AD ON AD.CLI_ID=C.CLI_ID AND AD.IS_CURRENT=1 
INNER JOIN V_AGENT V ON V.AGT_ID=W.AGT_ID and V.AGT_CLI_REL_TYP_CD='M'
LEFT JOIN DLKHDIM..DIM_CLIENT_CONTACT CC ON CC.CLI_ID=C.CLI_ID AND CC.IS_CURRENT=1 AND CC.CLI_CNTCT_ID_CD='HO'  
LEFT JOIN DLKHDIM..DIM_CLIENT_CONTACT CC1 ON CC1.CLI_ID=C.CLI_ID AND CC1.IS_CURRENT=1 AND CC1.CLI_CNTCT_ID_CD='CP'  
LEFT JOIN DLKHDIM..DIM_CLIENT_CONTACT EM ON EM.CLI_ID=C.CLI_ID AND EM.IS_CURRENT=1 AND EM.CLI_CNTCT_ID_CD='EM'  
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND PARA.DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E'  and PARA.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE D ON V.AGT_DISB_CHNL=D.ETBL_VALU_ID AND D.ETBL_TYP_ID='DCHNL' AND D.ETBL_LANG_CD='E' AND D.CO_ID='CP'
  WHERE  P.POL_CSTAT_CD IN ('D','B','3','1') and POL_PD_TO_DT_NUM<>'0000-00-00'  
GROUP BY POL_KEY,P.POL_ID,POL_APP_FORM_ID,PARA.DM_AV_DESC_TXT,P.PLAN_ID,POL_BILL_MODE_CD,  
CC.CLI_CNTCT_ID_TXT,CC1.CLI_CNTCT_ID_TXT,EM.CLI_CNTCT_ID_TXT,AD.CLI_CITY_NM_TXT,POL_PD_TO_DT_NUM, 
 CI.ENTR_SUR_NM,CI.ENTR_GIV_NM,POL_ISS_EFF_DT,POL_PREM_SUSP_AMT,POL_OS_DISB_AMT,V.AGT_PHON_NUM,  
 V.AGT_ID,V.ENTR_SUR_NM,V.ENTR_GIV_NM,D.ETBL_DESC_TXT
END
