CREATE PROC [dbo].[SP_ETL_FACT_OVERDRAFT] @BRANCH_DATE DATE,@IS_RE_PROC BIT
AS
BEGIN
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCDW..FACT_OVERDRAFT WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END
INSERT INTO BBCDW..FACT_OVERDRAFT
select CONVERT(VARCHAR,@BRANCH_DATE,112) ,RM.RM_NAME,AC.BRANCH_CODE,CUS.CUSTOMER_NO,AC.CUST_AC_NO,AC.AC_DESC,P_SEX,case when CUS.COUNTRY='KHM' THEN 'R' ELSE 'N' END RESIDENT_STATUS,AC.CCY
,AC.ACC_STATUS,BAL.ACY_CUR_BAL AS FCY_BAL, BAL.LCY_CUR_BAL AS LCY_BAL,FA.APPROVE_AMOUNT LIMIT_AMOUNT,LINK.LINE_START_DATE TOD_LIMIT_START_DATE,LINK.LINE_EXPIRY_DATE TOD_LIMIT_END_DATE,CASE WHEN ACC_STATUS='NORM' THEN 'N' ELSE 'Y' END Dormant,
NATIONALITY,LINK.LIAB_NO,DSP_EFF_LINE_AMOUNT,RATE1.UDE_VALUE,SUM(COL.COLLATERAL_VALUE) COLLATERAL_VALUE
 ,CASE WHEN FA.APPROVE_AMOUNT+BAL.LCY_CUR_BAL>=0 THEN 0 ELSE (FA.APPROVE_AMOUNT+BAL.LCY_CUR_BAL)*-1 END EXCESS,0 OVERDUE,ACCOUNT_CLASS,
 CODE.LOV CODE_NUM,CODE.LOV_DESC CODE,OWN.LOV_DESC OWN,CRR.LOV CRR,SI.LOV SI from BBCDW..FACT_DAILY_AC_BAL BAL INNER JOIN BBCDW..DIM_CUSTOMER CUS ON BAL.CUSTOMER_KEY=CUS.CUSTOMER_KEY
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY and ACCOUNT_CLASS not IN ('NOSTRO', 'INTERN')
LEFT JOIN BBCDW..DIM_ICTM ICM ON ICM.ACC=AC.CUST_AC_NO AND ICM.IS_CURRENT=1
LEFT JOIN BBCDW..FACT_CUST_ACCOUNT_LINKAGES LINK ON AC.ACCOUNT_KEY=LINK.ACCOUNT_KEY AND LINK.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
LEFT JOIN BBCDW..FACT_DAILY_FACILITY FA ON CONCAT(LINK.LINE_CODE,LINK.LINE_SERIAL)=CONCAT(FA.LINE_CODE,FA.LINE_SERIAL) AND FA.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
LEFT JOIN BBCDW..DIM_RELATION_MANAGER RM ON RM.RM_ID=CUS.RM_ID AND RM.BRANCH_CODE=1
LEFT JOIN (select * from BBCDW..DIM_ICTM_UDE RATE inner join (select MAX(UDE_EFF_DT) UDE_EFF_DT1,ACC ACC1 from BBCDW..DIM_ICTM_UDE where IS_CURRENT=1 AND UDE_ID='DR_RATE_CADI1' group by ACC) Y
 on RATE.ACC=Y.ACC1 and RATE.UDE_EFF_DT=Y.UDE_EFF_DT1
 where RATE.IS_CURRENT=1 AND RATE.UDE_ID='DR_RATE_CADI1') RATE1 on AC.CUST_AC_NO=RATE1.ACC
LEFT JOIN BBCDW..DIM_COLL COL ON FA.LIAB_ID=COL.LIAB_ID AND COL.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_UDF_VAL V ON CUS.CUSTOMER_NO=V.REC_KEY AND V.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_UDF_LOV CODE ON V.FIELD_VAL_15=CODE.LOV AND CODE.FIELD_NAME='INDUSTRY_CODE'
LEFT JOIN BBCDW..DIM_UDF_LOV OWN ON V.FIELD_VAL_16=OWN.LOV AND OWN.FIELD_NAME='OWNERSHIP_CIF'
LEFT JOIN BBCDW..DIM_UDF_LOV CRR ON V.FIELD_VAL_17=CRR.LOV AND CRR.FIELD_NAME='CCR_CIF'
LEFT JOIN BBCDW..DIM_UDF_LOV SI ON V.FIELD_VAL_18=SI.LOV AND SI.FIELD_NAME='SI_CIF'
WHERE BAL.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) AND (LCY_CUR_BAL<0 OR AC.ACCOUNT_KEY=LINK.ACCOUNT_KEY) and ACCOUNT_TYPE<>'S'
GROUP BY RM.RM_NAME,AC.BRANCH_CODE,CUS.CUSTOMER_NO,AC.CUST_AC_NO,AC.AC_DESC,P_SEX,CUS.COUNTRY,AC.CCY
,AC.ACC_STATUS,BAL.ACY_CUR_BAL, BAL.LCY_CUR_BAL,FA.APPROVE_AMOUNT,LINK.LINE_START_DATE,LINK.LINE_EXPIRY_DATE,
NATIONALITY,LINK.LIAB_NO,DSP_EFF_LINE_AMOUNT,RATE1.UDE_VALUE,ACCOUNT_CLASS,CODE.LOV_DESC,OWN.LOV_DESC,CRR.LOV,SI.LOV,CODE.LOV
END
