-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 14-SEP-2016
-- Description:	Execute IACR Loan Batch's Scripts
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_PROC_IACR_LOAN_FACT]
			@BRANCH_DATE DATE,
			@BATCH_CODE VARCHAR(20),
			@DB_NAME VARCHAR(20),
			@DBDW_NAME VARCHAR(20),
			@DBMART_NAME VARCHAR(20),
			@SERVER_NAME VARCHAR(20)
	
AS
BEGIN

		SELECT TOP 1 
				@DB_NAME=CASE WHEN ISNULL([DB_NAME],'')='' THEN @DB_NAME ELSE [DB_NAME] END,
				@DBDW_NAME=CASE WHEN ISNULL(DBDW_NAME,'')='' THEN @DBDW_NAME ELSE DBDW_NAME END,
				@DBMART_NAME=CASE WHEN ISNULL(MART_NAME,'')='' THEN @DBMART_NAME ELSE MART_NAME END,
				@SERVER_NAME=CASE WHEN ISNULL(SERVER_NAME,'')='' THEN @SERVER_NAME ELSE SERVER_NAME END 
		FROM ETLM_BATCH B WHERE B.BATCH_CODE=@BATCH_CODE

		DECLARE @TAB TABLE(ID INT IDENTITY,SQL_CODE VARCHAR(10),SQL_STR VARCHAR(MAX),SQL_DESC VARCHAR(250))
		DECLARE @COUNT INT,@MAX INT
		
		SET NOCOUNT ON;

		BEGIN TRAN;
		
		BEGIN TRY
		
			SET @COUNT=1

			INSERT INTO @TAB
			SELECT S.SQL_CODE,S.SQL_SCRIPT,S.SCRIPT_DESC FROM ETLM_SQLSCRIPTS S WHERE S.BATCH_CODE=@BATCH_CODE
			ORDER BY S.BATCH_PROC_NUM,S.SEQ_IN_BATCH_CODE;
		
			DECLARE @ERROR_CODE VARCHAR(50),@ERROR_MSG NVARCHAR(MAX),@SQL_STR NVARCHAR(MAX),@SQL_DESC VARCHAR(250),
					@START_TIME AS DATETIME,@END_TIME AS DATETIME,@SQL_CODE AS VARCHAR(10),@PROC_DESC AS VARCHAR(250),@ROWCOUNT INT=0

			SET @ERROR_CODE=''
			SET @ERROR_MSG=''
			SET @SQL_STR=''

			SELECT @MAX=@@IDENTITY;
			WHILE @COUNT<=@MAX 
			BEGIN
					SELECT @SQL_CODE=T.SQL_CODE,@SQL_STR=T.SQL_STR,@SQL_DESC=T.SQL_DESC FROM @TAB T WHERE T.ID=@COUNT
					
					SET @START_TIME=GETDATE();
					IF ISNULL(RTRIM(LTRIM(@SQL_STR)),'')<>''
					BEGIN
						SET @SQL_STR=REPLACE(@SQL_STR,'@BRANCH_DATE',@BRANCH_DATE)
						SET @SQL_STR=REPLACE(@SQL_STR,'@SERVER_NAME',@SERVER_NAME)
						SET @SQL_STR=REPLACE(@SQL_STR,'@DB_NAME',@DB_NAME)
						SET @SQL_STR=REPLACE(@SQL_STR,'@DBDW_NAME',@DBDW_NAME)
						SET @SQL_STR=REPLACE(@SQL_STR,'@DBMART_NAME',@DBMART_NAME)
						
						EXEC sp_executesql @SQL_STR;
				
						SET @ROWCOUNT = @@RowCount
	
						SET @PROC_DESC= N'BATCH CODE: '+ @BATCH_CODE +', SQL CODE: '+@SQL_CODE +', SQL DESC: '+ @SQL_DESC +', RowCount: '+ CAST(@ROWCOUNT  AS VARCHAR(100))
						SET @END_TIME=GETDATE()
						EXEC SP_ETL_PROC_WRITE_LOG 'ALL',@BRANCH_DATE,@BATCH_CODE,'C',@PROC_DESC,@START_TIME,@END_TIME,'','',@SQL_STR
					END
					SET @COUNT=@COUNT+1;
			END -- LOOP

			

		END TRY

		BEGIN CATCH

			SELECT @ERROR_CODE=ERROR_NUMBER(),@ERROR_MSG=ERROR_MESSAGE(), @END_TIME=GETDATE()
			
			IF @@TRANCOUNT>0 
				ROLLBACK TRAN
			PRINT ('ETL Processing fail on batch '+ @BATCH_CODE +'. Transaction Rollbacked!')

			SET @PROC_DESC='Error batch '+ @BATCH_CODE +' with SQLCODE: '+ @SQL_CODE;

			EXEC SP_ETL_PROC_WRITE_LOG 'ALL',@BRANCH_DATE,@BATCH_CODE,'E',@PROC_DESC,@START_TIME,@END_TIME,@ERROR_CODE,@ERROR_MSG,@SQL_STR

		END CATCH

		IF @@TRANCOUNT>0
			COMMIT TRAN;
END
