
-- ===================================================
-- Author		:	BUNCHHOEUN CHHIM 
-- Create date	:	22-NOV-2017
-- Description	:	FACT CL INSTALLMENT 
--					RETAIL CUST (EXCLUDE STAFF & CORP)
-- ===================================================
CREATE PROCEDURE [dbo].[SP_ETL_FACT_CL_INST_RETAIL]
--CREATE PROCEDURE [dbo].[SP_ETL_FACT_CL_INST_RETAIL]
	@BRANCH_DATE DATE, @IS_RE_PRC BIT
AS
BEGIN

DELETE FROM BBCDW..FACT_LOAN_INST_RETAIL

IF OBJECT_ID('tempdb..#INSTALLMENT') IS NOT NULL
	DROP TABLE #INSTALLMENT
IF OBJECT_ID('tempdb..#LOANRETAIL') IS NOT NULL
	DROP TABLE #LOANRETAIL
IF OBJECT_ID('tempdb..#RETAILCUST') IS NOT NULL
	DROP TABLE #RETAILCUST
IF OBJECT_ID('tempdb..#LOANACC') IS NOT NULL
	DROP TABLE #LOANACC

IF OBJECT_ID('tempdb..#SCHEDULE') IS NOT NULL
	DROP TABLE #SCHEDULE

SELECT CUSTOMER_NO
INTO #RETAILCUST
FROM BBCDW..DIM_CUSTOMER 
WHERE CUSTOMER_TYPE = 'I'
	and RECORD_STAT = 'O'
	and AUTH_STAT = 'A'
	and STAFF = 'N'
	AND IS_CURRENT = '1'

SELECT LOAN_AC_KEY, LOAN_AC_NO, CUSTOMER_ID
INTO #LOANACC	
FROM BBCDW..DIM_LOAN_ACCOUNT
WHERE IS_CURRENT = 1

SELECT A.CUSTOMER_NO, B.LOAN_AC_KEY, B.LOAN_AC_NO 
INTO #LOANRETAIL
FROM #RETAILCUST A
LEFT JOIN #LOANACC B ON A.CUSTOMER_NO = B.CUSTOMER_ID

SELECT BRANCH_CODE, ACCOUNT_NUMBER, SCHEDULE_ST_DATE, SCHEDULE_DUE_DATE, SETTLEMENT_CCY, sum(AMOUNT_DUE) AMT_DUE, SCHEDULE_NO
INTO #SCHEDULE
FROM BBCSTAGE..SGTB_ACCOUNT_SCHEDULE
WHERE COMPONENT_NAME IN ('MAIN_INT','PRINCIPAL')
GROUP BY BRANCH_CODE, ACCOUNT_NUMBER, SCHEDULE_ST_DATE, SCHEDULE_DUE_DATE, SETTLEMENT_CCY, SCHEDULE_NO
order by ACCOUNT_NUMBER, SCHEDULE_ST_DATE;

INSERT INTO BBCDW..FACT_LOAN_INST_RETAIL(DATEKEY, BRANCH_CODE, CUSTOMER_NO, LOAN_AC_KEY, SCHEDULE_ST_DATE, SCHEDULE_DUE_DATE, AMOUNT_DUE, COMPONENT_CCY, ETL_DT)
SELECT CONVERT(VARCHAR, @BRANCH_DATE, 112), B.BRANCH_CODE, A.CUSTOMER_NO, A.LOAN_AC_KEY, B.SCHEDULE_ST_DATE, B.SCHEDULE_DUE_DATE, B.AMT_DUE, B.SETTLEMENT_CCY, GETDATE()
FROM #LOANRETAIL A
LEFT JOIN #SCHEDULE B 
	ON A.LOAN_AC_NO = B.ACCOUNT_NUMBER
WHERE A.LOAN_AC_NO IS NOT NULL

END
