-- =============================================
-- Author:		BUNCHHOEUN CHHIM
-- Create date: 13-Mar-18
-- Description:	Loan Payment History.
--				The data based on 
--				branch date param
-- =============================================
--CREATE PROCEDURE [dbo].[SP_ETL_FACT_CL_PAID_HIS]
CREATE PROCEDURE [dbo].[SP_ETL_FACT_CL_PAID_HIS]
	@BRANCH_DATE DATE, @IS_RE_PRC BIT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	IF @IS_RE_PRC = 1
	BEGIN
		DELETE FROM  BBCDW..FACT_CL_PAID_HIS WHERE DATE_KEY = CONVERT(VARCHAR,@BRANCH_DATE,112);
	END

	--INT AMT
	IF OBJECT_ID('tempdb..#CL_INT_AMT') IS NOT NULL
	DROP TABLE #CL_INT_AMT

	SELECT a.ACCOUNT_NUMBER, PAID_DATE, SUM(A.AMOUNT_PAID) PAID_AMT
	INTO #CL_INT_AMT
	FROM BBCSTAGE..SGTB_LOAN_PAYMENT a
	WHERE a.COMPONENT_NAME like 'MAIN_INT'
		AND a.PAID_DATE = @BRANCH_DATE
	GROUP BY A.ACCOUNT_NUMBER, A.PAID_DATE

	--PRINCIPAL AMT
	IF OBJECT_ID('tempdb..#CL_PRIN_AMT') IS NOT NULL
	DROP TABLE #CL_PRIN_AMT

	SELECT a.ACCOUNT_NUMBER, PAID_DATE, sum(a.AMOUNT_PAID) PAID_AMT
	INTO #CL_PRIN_AMT
	FROM BBCSTAGE..SGTB_LOAN_PAYMENT a
	WHERE a.COMPONENT_NAME like 'PRINCIPAL'
		AND a.PAID_DATE = @BRANCH_DATE
	GROUP BY A.ACCOUNT_NUMBER, A.PAID_DATE

	--PENALTY AMT
	IF OBJECT_ID('tempdb..#CL_PENALTY_AMT') IS NOT NULL
	DROP TABLE #CL_PENALTY_AMT

	SELECT a.ACCOUNT_NUMBER, PAID_DATE, sum(AMOUNT_PAID) PENALTY_AMT
	INTO #CL_PENALTY_AMT
	FROM BBCSTAGE..SGTB_LOAN_PAYMENT a
	WHERE a.COMPONENT_NAME in ('ODIN_PNLTY','ODPR_PNLTY')
		AND a.PAID_DATE = @BRANCH_DATE
	GROUP BY a.account_number, paid_date

	--INSERT FACT LOAN PAID HIS
	INSERT INTO BBCDW..FACT_CL_PAID_HIS(DATE_KEY, LOAN_NUM, CUST_KEY, BRN_KEY, EVENT_DATE, EVENT_DESC, OS_BAL, PRINCIPLE_PAID, INTEREST_PAID, PENALTY, OVERDUE_PRINCIPLE, OVERDUE_INTEREST, OVERDUE_PENALTY, CAPITAL_OS, ETL_DATE)
	SELECT CONVERT(VARCHAR, @BRANCH_DATE, 112), A.LOAN_AC_NO, (SELECT CU.CUSTOMER_KEY FROM BBCDW..DIM_CUSTOMER CU WHERE CU.CUSTOMER_NO = A.CUSTOMER_ID AND CU.IS_CURRENT = 1) CUST_KEY,
		(SELECT BR.BRANCH_KEY FROM BBCDW..DIM_BBC_BRANCH BR WHERE BR.BRANCH_CODE = A.BRANCH_CODE AND BR.IS_CURRENT = 1) BRN_KEY, @BRANCH_DATE EVENT_DATE, 'LOAN PAYMENT' EVENT_DESC, 
		B.PRINCIPAL_OS OS_BAL, D.PAID_AMT PRINCIPAL_PAID, C.PAID_AMT INTEREST_PAID, E.PENALTY_AMT PENALTY, B.PRIN_OVERDUE OVERDUE_PRINCIPLE, B.INT_OVERDUE OVERDUE_INTEREST, 
		E.PENALTY_AMT OVERDUE_PENALTY, B.LAST_PRINCIPAL_BAL CAPITAL_OS, @BRANCH_DATE
	FROM #CL_PRIN_AMT D
		LEFT JOIN BBCDW..DIM_LOAN_ACCOUNT A ON D.ACCOUNT_NUMBER = A.LOAN_AC_NO
		LEFT JOIN BBCSTAGE..SGTB_LOAN_IACR_LOAN B ON D.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER
		LEFT JOIN #CL_INT_AMT C ON D.ACCOUNT_NUMBER = C.ACCOUNT_NUMBER
		LEFT JOIN #CL_PENALTY_AMT E ON D.ACCOUNT_NUMBER = E.ACCOUNT_NUMBER
	WHERE A.IS_CURRENT = 1
END
