-- =============================================
-- Author:		HING TIPI
-- Create date: 21-DEC-2018
-- Description:	ETL BATCH PROCESS FOR DIMENSION TABLES
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_PROC_BATCH_DIMS]
	@BRANCH_DATE DATE,@DB_NAME VARCHAR(20),@DBDW_NAME VARCHAR(20),@SERVER_NAME VARCHAR(20),@IS_ERROR BIT OUTPUT
AS
BEGIN
	
	SET NOCOUNT ON;
	  IF OBJECT_ID('tempdb..#ETL') IS NOT NULL
	 DROP TABLE #ETL
	CREATE TABLE #ETL (ID INT IDENTITY,BATCH_CODE VARCHAR(15),BATCH_NAME VARCHAR(100),DB_NAME VARCHAR(15),DBDW_NAME VARCHAR(15),SERVER_NAME VARCHAR(15))
	DECLARE @COUNT INT,@MAX INT,@BATCH_CODE VARCHAR(15),@BATCH_NAME VARCHAR(100),@BATCH_SCRIPT NVARCHAR(MAX)
	DECLARE @ERROR_CODE AS VARCHAR(50),@ERROR_MSG AS NVARCHAR(MAX)

	SET @COUNT=1
	INSERT INTO #ETL
	SELECT 
			BATCH_CODE,BATCH_NAME,DB_NAME,DBDW_NAME,SERVER_NAME
	FROM ETLM_BATCH B 
	WHERE B.BATCH_TYPE='D' AND B.IS_ENABLED=1 
	AND B.EFFECTIVE_DATE<=@BRANCH_DATE
	AND PARENT_BATCH=2 -- DIMENSIONS MAIN BATCH
	ORDER BY B.BATCH_NUM
	SELECT @MAX=@@IDENTITY;
	WHILE @COUNT<=@MAX BEGIN
		
		SET @IS_ERROR=0
		SELECT @BATCH_CODE=BATCH_CODE,@BATCH_NAME=BATCH_NAME,
			@DB_NAME=CASE WHEN ISNULL([DB_NAME],'')='' THEN @DB_NAME ELSE [DB_NAME] END,
			@DBDW_NAME=CASE WHEN ISNULL(DBDW_NAME,'')='' THEN @DB_NAME ELSE [DBDW_NAME] END,
			@SERVER_NAME=CASE WHEN ISNULL(SERVER_NAME,'')='' THEN @SERVER_NAME ELSE [SERVER_NAME] END
		FROM #ETL T WHERE ID=@COUNT
		
		SET @BATCH_SCRIPT=N'EXEC SP_ETL_PROC_BATCH_SCRIPT ''@BRANCH_DATE'',''@BATCH_CODE'',''@DB_NAME'',''@DBDW_NAME'','''',''@SERVER_NAME'''
		IF ISNULL(@BATCH_SCRIPT,'')<>'' 
		BEGIN
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@BRANCH_DATE',@BRANCH_DATE)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@BATCH_CODE',@BATCH_CODE)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@DB_NAME',@DB_NAME)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@DBDW_NAME',@DBDW_NAME)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@SERVER_NAME',@SERVER_NAME)
			--SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@DBMART_NAME','')
			BEGIN TRAN;
			BEGIN TRY

				
				-- CALL SP BY BATCH PROCESS
				EXEC sp_executesql @BATCH_SCRIPT;
				--print @BATCH_SCRIPT;
			END TRY
			BEGIN CATCH
				SET @IS_ERROR=1;
				PRINT (ERROR_MESSAGE())
				RETURN
			END CATCH;
			COMMIT TRAN;
		END 
	
	SET @COUNT=@COUNT+1;
	
	END;
			 

END
