
CREATE PROC [dbo].[SP_ETL_FACT_POL_DETAIL] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

IF @IS_RE_PROC = 1 DELETE FROM  DLKHFACT..FACT_POL_DETAIL WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)

INSERT INTO DLKHFACT..FACT_POL_DETAIL ([DATE_KEY],[POL_KEY],[POL_ID],[AG_KEY],[AGT_ID],[CLI_KEY],[CLI_ID])
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY, P.POL_KEY, P.POL_ID 
	   ,AGT.AG_KEY,PW.AGT_ID ,CLI.CLI_KEY CLI_KEY, PC.CLI_ID
FROM DLKHDIM..DIM_POLICY P 
LEFT JOIN DLKHSTAGE..SGTB_POLICY_WRITING PW ON PW.POL_ID = P.POL_ID 
LEFT JOIN DLKHDIM..DIM_POLICY_CLIENT PC ON PC.POL_ID = P.POL_ID 
	AND PC.POL_CLI_REL_TYP_CD ='O' AND PC.IS_CURRENT=1 AND PC.POL_CLI_REL_SUB_CD = 'P'
LEFT JOIN DLKHDIM..DIM_CLIENT CLI ON CLI.CLI_ID = PC.CLI_ID AND CLI.IS_CURRENT =1
LEFT JOIN DLKHDIM..DIM_AG AGT ON AGT.AGT_ID = PW.AGT_ID AND AGT.IS_CURRENT = 1
WHERE  P.IS_CURRENT = 1 

END
