
	CREATE PROC [dbo].[SP_ETL_FACT_AXP_AGENT_COMM] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
	AS
	BEGIN

		--DECLARE @BRANCH_DATE	DATE = '2024-05-25'
		--	,@IS_RE_PROC BIT = 1

		IF @IS_RE_PROC = 1 DELETE FROM  DLKHFACT..FACT_AXP_AGENT_COMM WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

		DROP TABLE IF EXISTS #TMP

		SELECT DISTINCT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY
			,POL_KEY
			,AG_KEY
			,COV_KEY
			,P.POL_ID
			,P.POL_APP_FORM_ID,W.AGT_ID AGT_ID
			,RTRIM(LTRIM(V.ENTR_SUR_NM))+' '+RTRIM(LTRIM(V.ENTR_GIV_NM)) AGENT_NAME
			,COM.COMM_HIST_AMT
			,COMM_DUR_CALC_DT
			,COM.COMM_HIST_PRCES_DT
			,C.PLAN_ID,PA.ETBL_DESC_TXT PLAN_DESC
			,CVG_MAT_XPRY_DUR  POL_TERM
			,POL_CSTAT_CD
			,PARA.DM_AV_DESC_TXT POL_STAT_DESC
			,POL_APP_RECV_DT POL_CREAT_DT
			,P.POL_APP_CMPLT_DT
			,C.CVG_MPREM_AMT COM_PRE
			,CASE WHEN V.CHANNEL = 'BA' THEN 'BANCA' WHEN V.CHANNEL = 'AG' THEN 'AGENCY' ELSE '' END CHANNEL
			,CASE  WHEN P.POL_BILL_MODE_CD=3 THEN 'QUARTERLY' 
				WHEN P.POL_BILL_MODE_CD=6 THEN 'SEMI ANNUAL' 
				WHEN P.POL_BILL_MODE_CD=1 THEN 'MONTHLY' 
				WHEN P.POL_BILL_MODE_CD=12 THEN 'ANNUAL'
				ELSE P.POL_BILL_MODE_CD END PRE_MODE
			,PC.POL_ACTV_TYP_ID
			,COM_TYPE = CASE COM.PREV_PRCES_ANNV_YR 	
				WHEN 0 THEN (
					CASE WHEN PC.POL_ACTV_TYP_ID='1082' AND DATEDIFF(M,PPC.PCHST_EFF_DT, COM.COMM_DUR_CALC_DT) > 0 THEN 'RFYC' ELSE 'IFYC' END)  
				WHEN 1 THEN '2YC'
				WHEN 2 THEN '3YC'
				ELSE 'N/A'
			END
			,PPC.PCHST_EFF_DT INITIAL_DATE
			,C.CVG_MPREM_AMT MODAL_PRE
			,CVG_ME_FCT
			,C.CVG_MPREM_AMT  - C.CVG_MPREM_AMT PRE_BEFORE
			,C.CVG_MPREM_AMT PRE_AFTER
			,C.CVG_MPREM_AMT * (CASE WHEN CAST(P.POL_BILL_MODE_CD AS INT)>0 THEN 12/CAST(P.POL_BILL_MODE_CD AS INT) ELSE 1 END) AS AFYP
			,COM.COMM_HIST_GEN_ID 
			--,COM.PREV_PRCES_ANNV_YR
		INTO #TMP 
		FROM DLKHDIM..DIM_POLICY P 
		INNER JOIN SGTB_COMMISSION_HIS COM ON COM.POL_ID = P.POL_ID AND P.IS_CURRENT = 1
		INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID = P.POL_ID AND C.IS_CURRENT = 1 
			AND C.PLAN_ID = COM.CVG_PLAN_ID AND C.CVG_NUM = COM.CVG_NUM AND C.CVG_CSTAT_CD <> 'B'
		LEFT JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
		LEFT JOIN V_AGENT V ON V.AGT_ID=W.AGT_ID 
		LEFT JOIN 
			(
				SELECT POL_ID,MIN(PCHST_EFF_DT) PCHST_EFF_DT 
				FROM SGTB_POLICY_CHANGE PPC 
				WHERE PPC.PCHST_STAT_CD='A' AND PPC.POL_ACTV_TYP_ID='1082' GROUP BY POL_ID
			) PPC ON COM.POL_ID = PPC.POL_ID
		LEFT JOIN SGTB_POLICY_CHANGE PC ON COM.POL_ID  =PC.POL_ID AND COM.COMM_DUR_CALC_DT=PC.PCHST_EFF_DT 
			AND PCHST_STAT_CD='A' AND POL_ACTV_TYP_ID IN ('1082','1084')
		LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
		LEFT JOIN SGTB_EDITTABLE PA ON C.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
		LEFT JOIN SGTB_EDITTABLE PS ON C.CVG_STBL_1_CD = PS.ETBL_VALU_ID AND PS.ETBL_TYP_ID='STB1' AND PS.ETBL_LANG_CD='E' AND PS.CO_ID='CP'	
		WHERE P.POL_ID NOT IN ('001000744') 
			AND P.POL_CSTAT_CD NOT IN ('B') 
			AND BUS_FCN_ID NOT IN ('M297','1453')
			AND COMM_HIST_REASN_CD NOT IN ('K')
			OR COMM_DUR_CALC_DT IS NOT NULL

	
		INSERT INTO DLKHFACT..FACT_AXP_AGENT_COMM
		SELECT DISTINCT T.*,CASE WHEN COM_TYPE  IN ('IFYC','RFYC') THEN (CASE WHEN POL_TERM='6' THEN MODAL_PRE/2 ELSE MODAL_PRE END) ELSE 0 END WFYP
		FROM #TMP T 

		END
