
-- =============================================
-- Author:		TIPI
-- Create date: 10-JAN-2017
-- Description:	FACT DAILY GL BALANCE
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_FACT_DD_GL_BAL]
	@BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCDW..FACT_DAILY_GL_BAL WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
	END
IF OBJECT_ID('tempdb..#GL') IS NOT NULL
  DROP TABLE #GL
IF OBJECT_ID('tempdb..#GL1') IS NOT NULL
  DROP TABLE #GL1
IF OBJECT_ID('tempdb..#BR') IS NOT NULL
  DROP TABLE #BR
IF OBJECT_ID('tempdb..#CUR') IS NOT NULL
  DROP TABLE #CUR
IF OBJECT_ID('tempdb..#CUR2') IS NOT NULL
  DROP TABLE #CUR2
IF OBJECT_ID('tempdb..#CUR1') IS NOT NULL
  DROP TABLE #CUR1
IF OBJECT_ID('tempdb..#CUR3') IS NOT NULL
  DROP TABLE #CUR3
DECLARE @PARA_DATE DATE;
DECLARE @CHECK BIT=1;
select @PARA_DATE=MAX(BGK_DATE)
from BBCDW..FACT_DAILY_GL_HISTORY where  BGK_DATE<@BRANCH_DATE 

select BRANCH_CODE,GL_CODE,CCY_CODE,F.FIN_YEAR,PERIOD_CODE,PARENT_GL,LEAF,CATEGORY,
ISNULL(DR_MOV,0) DR_MOV,ISNULL(CR_MOV,0)CR_MOV,ISNULL(DR_BAL,0)DR_BAL,ISNULL(CR_BAL,0)CR_BAL,
ISNULL(DR_MOV_LCY,0)DR_MOV_LCY,ISNULL(CR_MOV_LCY,0)CR_MOV_LCY,ISNULL(DR_BAL_LCY,0)DR_BAL_LCY,ISNULL(CR_BAL_LCY,0) CR_BAL_LCY   INTO #GL
from BBCDW..FACT_DAILY_GL_HISTORY H INNER JOIN  BBCDW..DIM_FIN_PERIOD F ON H.FIN_YEAR=F.FIN_YEAR AND H.PERIOD_CODE=F.FIN_MONTH  where  BGK_DATE=@PARA_DATE order by BGK_DATE

select BRANCH_CODE,GL_CODE,CCY_CODE,F.FIN_YEAR,PERIOD_CODE,CUST_AC_NO,
ISNULL(DR_MOV,0) DR_MOV,ISNULL(CR_MOV,0)CR_MOV,ISNULL(DR_BAL,0)DR_BAL,ISNULL(CR_BAL,0)CR_BAL,
ISNULL(DR_MOV_LCY,0)DR_MOV_LCY,ISNULL(CR_MOV_LCY,0)CR_MOV_LCY,ISNULL(DR_BAL_LCY,0)DR_BAL_LCY,ISNULL(CR_BAL_LCY,0) CR_BAL_LCY   INTO #BR
from BBCDW..FACT_GL_ACC_BREAKUP H INNER JOIN  BBCDW..DIM_FIN_PERIOD F ON H.FIN_YEAR=F.FIN_YEAR AND H.PERIOD_CODE=F.FIN_MONTH  where  BGK_DATE=@PARA_DATE order by BGK_DATE

select 
H.BGK_DATE,H.BRANCH_CODE,H.GL_CODE,H.CCY_CODE,H.FIN_YEAR,H.PERIOD_CODE,H.PARENT_GL,H.LEAF,H.CATEGORY,
T.DR_BAL OPN_DR,
T.CR_BAL OPN_CR,
T.DR_BAL_LCY OPN_DR_LCY,
T.CR_BAL_LCY OPN_CR_LCY,
CASE WHEN T.PERIOD_CODE=H.PERIOD_CODE AND (H.DR_MOV>=T.DR_MOV AND H.CR_MOV>=T.CR_MOV) THEN  H.DR_MOV - isnull(T.DR_MOV,0)
     WHEN T.PERIOD_CODE=H.PERIOD_CODE AND (H.DR_MOV<T.DR_MOV OR H.CR_MOV<T.CR_MOV) THEN  H.DR_MOV  ELSE H.DR_MOV END  DR_MOV,
CASE WHEN T.PERIOD_CODE=H.PERIOD_CODE AND (H.CR_MOV>=T.CR_MOV AND H.DR_MOV>=T.DR_MOV) THEN  H.CR_MOV - isnull(T.CR_MOV,0)
     WHEN T.PERIOD_CODE=H.PERIOD_CODE AND (H.CR_MOV<T.CR_MOV OR H.DR_MOV<T.DR_MOV) THEN  H.CR_MOV ELSE H.CR_MOV END  CR_MOV,
H.DR_BAL CLO_DR,
H.CR_BAL CLO_CR,
CASE WHEN T.PERIOD_CODE=H.PERIOD_CODE AND (H.DR_MOV_LCY>=T.DR_MOV_LCY AND H.CR_MOV_LCY>=T.CR_MOV_LCY) THEN H.DR_MOV_LCY - isnull(T.DR_MOV_LCY,0)
     WHEN T.PERIOD_CODE=H.PERIOD_CODE AND (H.DR_MOV_LCY<T.DR_MOV_LCY OR H.CR_MOV_LCY<T.CR_MOV_LCY) THEN  H.DR_MOV_LCY ELSE H.DR_MOV_LCY END DR_MOV_LCY,
CASE WHEN T.PERIOD_CODE=H.PERIOD_CODE AND (H.CR_MOV_LCY>=T.CR_MOV_LCY AND H.DR_MOV_LCY>=T.DR_MOV_LCY) THEN  H.CR_MOV_LCY - isnull(T.CR_MOV_LCY,0)
     WHEN T.PERIOD_CODE=H.PERIOD_CODE AND (H.CR_MOV_LCY<T.CR_MOV_LCY OR H.DR_MOV_LCY<T.DR_MOV_LCY) THEN  H.CR_MOV_LCY ELSE H.CR_MOV_LCY END CR_MOV_LCY,
H.DR_BAL_LCY CLO_DR_LCY,
H.CR_BAL_LCY CLO_CR_LCY INTO #GL1
from BBCDW..FACT_DAILY_GL_HISTORY H LEFT JOIN #GL T ON H.GL_CODE=T.GL_CODE  AND H.CCY_CODE=T.CCY_CODE AND H.BRANCH_CODE=T.BRANCH_CODE  where H.BGK_DATE=@BRANCH_DATE
and H.GL_CODE not in ('32121000','32122000','32112000','32111000','32100000','13211000','13351000')
insert into #GL1
select 
H.BGK_DATE,H.BRANCH_CODE,H.GL_CODE,H.CCY_CODE,H.FIN_YEAR,H.PERIOD_CODE,H.PARENT_GL,H.LEAF,H.CATEGORY,
T.DR_BAL OPN_DR,
T.CR_BAL OPN_CR,
T.DR_BAL_LCY OPN_DR_LCY,
T.CR_BAL_LCY OPN_CR_LCY,
CASE WHEN T.PERIOD_CODE=H.PERIOD_CODE THEN  H.DR_MOV - isnull(T.DR_MOV,0)
     ELSE H.DR_MOV END  DR_MOV,
CASE WHEN T.PERIOD_CODE=H.PERIOD_CODE  THEN  H.CR_MOV - isnull(T.CR_MOV,0)
     ELSE H.CR_MOV END  CR_MOV,
H.DR_BAL CLO_DR,
H.CR_BAL CLO_CR,
CASE WHEN T.PERIOD_CODE=H.PERIOD_CODE  THEN H.DR_MOV_LCY - isnull(T.DR_MOV_LCY,0)
      ELSE H.DR_MOV_LCY END DR_MOV_LCY,
CASE WHEN T.PERIOD_CODE=H.PERIOD_CODE  THEN  H.CR_MOV_LCY - isnull(T.CR_MOV_LCY,0)
      ELSE H.CR_MOV_LCY END CR_MOV_LCY,
H.DR_BAL_LCY CLO_DR_LCY,
H.CR_BAL_LCY CLO_CR_LCY 
from BBCDW..FACT_DAILY_GL_HISTORY H LEFT JOIN #GL T ON H.GL_CODE=T.GL_CODE  AND H.CCY_CODE=T.CCY_CODE AND H.BRANCH_CODE=T.BRANCH_CODE  where H.BGK_DATE=@BRANCH_DATE
and H.GL_CODE in ('32121000','32122000','32112000','32111000','32100000','13211000','13351000')

--***************Resident Private Sector******************
IF (SELECT COUNT(*) FROM #BR where GL_CODE='32121000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32121000'))>0
BEGIN
	IF (SELECT TOP 1 PERIOD_CODE FROM #BR)<>(SELECT TOP 1 PERIOD_CODE FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE)
	BEGIN
			SELECT SUM(CR_BAL) CR_BAL,SUM(CR_BAL_LCY) CR_BAL_LCY,CCY_CODE INTO #CUR1 FROM #BR where GL_CODE='32121000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32121000') group by CCY_CODE

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32121000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32120000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

print 1

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13211000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13210000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13200000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR1 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

	END
	ELSE
	BEGIN
	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0
print 2
	SELECT CCY_CODE,SUM(CR_MOV_LCY)-SUM(DR_MOV_LCY)-SUM(CR_BAL_LCY) DR_BAL_LCY,SUM(CR_MOV)-SUM(DR_MOV)-SUM(CR_BAL) DR_BAL INTO #CUR3 FROM #BR where GL_CODE='32121000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32121000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32121000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32120000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13211000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13210000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13200000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR3 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

	END
END
IF (SELECT COUNT(*) FROM #BR where GL_CODE='13211000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13211000'))>0
BEGIN
	IF (SELECT TOP 1 PERIOD_CODE FROM #BR)<>(SELECT TOP 1 PERIOD_CODE FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE)
	BEGIN
			SELECT CCY_CODE,SUM(DR_BAL)DR_BAL,SUM(DR_BAL_LCY) DR_BAL_LCY INTO #CUR FROM #BR where GL_CODE='13211000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13211000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13211000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13210000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13200000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32121000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32120000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'
print 3

	END
	ELSE
	BEGIN
	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0
print 4
	SELECT CCY_CODE,SUM(CR_MOV_LCY)-SUM(DR_MOV_LCY)+SUM(DR_BAL_LCY) DR_BAL_LCY,SUM(CR_MOV)-SUM(DR_MOV)+SUM(DR_BAL) DR_BAL INTO #CUR2 FROM #BR where GL_CODE='13211000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13211000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13211000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13210000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13200000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32121000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32120000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

	END

END
--*************** Non Resident Private Sector******************
IF OBJECT_ID('tempdb..#CURRR') IS NOT NULL
  DROP TABLE #CURRR
IF OBJECT_ID('tempdb..#CUR222') IS NOT NULL
  DROP TABLE #CUR222
IF OBJECT_ID('tempdb..#CUR111') IS NOT NULL
  DROP TABLE #CUR111
IF OBJECT_ID('tempdb..#CUR333') IS NOT NULL
  DROP TABLE #CUR333
IF (SELECT COUNT(*) FROM #BR where GL_CODE='32122000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32122000'))>0
BEGIN
	IF (SELECT TOP 1 PERIOD_CODE FROM #BR)<>(SELECT TOP 1 PERIOD_CODE FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE)
	BEGIN
			SELECT SUM(CR_BAL) CR_BAL,SUM(CR_BAL_LCY) CR_BAL_LCY,CCY_CODE INTO #CUR111 FROM #BR where GL_CODE='32122000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32122000') group by CCY_CODE

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32122000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32120000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'
print 5

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13212000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13210000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13200000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

	END
	ELSE
	BEGIN
	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0
print 6
	SELECT CCY_CODE,SUM(CR_MOV_LCY)-SUM(DR_MOV_LCY)-SUM(CR_BAL_LCY) DR_BAL_LCY,SUM(CR_MOV)-SUM(DR_MOV)-SUM(CR_BAL) DR_BAL INTO #CUR333 FROM #BR where GL_CODE='32122000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32122000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32122000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32120000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13212000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13210000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13200000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

	END
END
IF (SELECT COUNT(*) FROM #BR where GL_CODE='13212000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13212000'))>0
BEGIN
	IF (SELECT TOP 1 PERIOD_CODE FROM #BR)<>(SELECT TOP 1 PERIOD_CODE FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE)
	BEGIN
			SELECT CCY_CODE,SUM(DR_BAL)DR_BAL,SUM(DR_BAL_LCY) DR_BAL_LCY INTO #CURRR FROM #BR where GL_CODE='13212000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13212000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13212000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13210000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13200000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'
print 7
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32122000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32120000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

	END
	ELSE
	BEGIN
	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0
	print 8
	SELECT CCY_CODE,SUM(CR_MOV_LCY)-SUM(DR_MOV_LCY)+SUM(DR_BAL_LCY) DR_BAL_LCY,SUM(CR_MOV)-SUM(DR_MOV)+SUM(DR_BAL) DR_BAL INTO #CUR222 FROM #BR where GL_CODE='13212000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13212000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13212000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13210000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13200000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32122000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32120000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

	END

END

--*************** Non Resident Individual******************
IF OBJECT_ID('tempdb..#CURRRR') IS NOT NULL
  DROP TABLE #CURRRR
IF OBJECT_ID('tempdb..#CUR2222') IS NOT NULL
  DROP TABLE #CUR2222
IF OBJECT_ID('tempdb..#CUR1111') IS NOT NULL
  DROP TABLE #CUR1111
IF OBJECT_ID('tempdb..#CUR3333') IS NOT NULL
  DROP TABLE #CUR3333
IF (SELECT COUNT(*) FROM #BR where GL_CODE='32112000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32112000'))>0
BEGIN
	IF (SELECT TOP 1 PERIOD_CODE FROM #BR)<>(SELECT TOP 1 PERIOD_CODE FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE)
	BEGIN
			SELECT SUM(CR_BAL) CR_BAL,SUM(CR_BAL_LCY) CR_BAL_LCY,CCY_CODE INTO #CUR1111 FROM #BR where GL_CODE='32112000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32112000') group by CCY_CODE

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32112000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32110000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'
print 5

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13352000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13350000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13300000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR1111 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

	END
	ELSE
	BEGIN
	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0
print 6
	SELECT CCY_CODE,SUM(CR_MOV_LCY)-SUM(DR_MOV_LCY)-SUM(CR_BAL_LCY) DR_BAL_LCY,SUM(CR_MOV)-SUM(DR_MOV)-SUM(CR_BAL) DR_BAL INTO #CUR3333 FROM #BR where GL_CODE='32112000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32112000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32112000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32110000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13352000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13350000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13300000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR3333 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

	END
END
IF (SELECT COUNT(*) FROM #BR where GL_CODE='13352000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13352000'))>0
BEGIN
	IF (SELECT TOP 1 PERIOD_CODE FROM #BR)<>(SELECT TOP 1 PERIOD_CODE FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE)
	BEGIN
			SELECT CCY_CODE,SUM(DR_BAL)DR_BAL,SUM(DR_BAL_LCY) DR_BAL_LCY INTO #CURRRR FROM #BR where GL_CODE='13352000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13352000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13352000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13350000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13300000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'
print 7
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32112000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32110000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURRRR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

	END
	ELSE
	BEGIN
	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0
	print 8
	SELECT CCY_CODE,SUM(CR_MOV_LCY)-SUM(DR_MOV_LCY)+SUM(DR_BAL_LCY) DR_BAL_LCY,SUM(CR_MOV)-SUM(DR_MOV)+SUM(DR_BAL) DR_BAL INTO #CUR2222 FROM #BR where GL_CODE='13352000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13352000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13352000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13350000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13300000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32112000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32110000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR2222 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

	END

END
--***************Resident Individuals******************
IF OBJECT_ID('tempdb..#CURR') IS NOT NULL
  DROP TABLE #CURR
IF OBJECT_ID('tempdb..#CUR22') IS NOT NULL
  DROP TABLE #CUR22
IF OBJECT_ID('tempdb..#CUR11') IS NOT NULL
  DROP TABLE #CUR11
IF OBJECT_ID('tempdb..#CUR33') IS NOT NULL
  DROP TABLE #CUR33

IF (SELECT COUNT(*) FROM #BR where GL_CODE='32111000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32111000'))>0
BEGIN
	IF (SELECT TOP 1 PERIOD_CODE FROM #BR)<>(SELECT TOP 1 PERIOD_CODE FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE)
	BEGIN
			SELECT SUM(CR_BAL) CR_BAL,SUM(CR_BAL_LCY) CR_BAL_LCY,CCY_CODE INTO #CUR11 FROM #BR where GL_CODE='32111000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32111000') group by CCY_CODE

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32111000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32110000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.CR_BAL_LCY,DR_MOV=DR_MOV+C.CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

print 9

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13351000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13350000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13300000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.CR_BAL_LCY,CR_MOV=CR_MOV+CR_BAL FROM #GL1 G INNER JOIN #CUR11 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

	END
	ELSE
	BEGIN
	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0
print 10
	SELECT CCY_CODE,SUM(CR_MOV_LCY)-SUM(DR_MOV_LCY)-SUM(CR_BAL_LCY) DR_BAL_LCY,SUM(CR_MOV)-SUM(DR_MOV)-SUM(CR_BAL) DR_BAL INTO #CUR33 FROM #BR where GL_CODE='32111000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='32111000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32111000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32110000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+DR_BAL_LCY,CR_MOV=CR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13351000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13350000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13300000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+C.DR_BAL_LCY,DR_MOV=DR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR33 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

	END
END
IF (SELECT COUNT(*) FROM #BR where GL_CODE='13351000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13351000'))>0
BEGIN
	IF (SELECT TOP 1 PERIOD_CODE FROM #BR)<>(SELECT TOP 1 PERIOD_CODE FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE)
	BEGIN
			SELECT CCY_CODE,SUM(DR_BAL)DR_BAL,SUM(DR_BAL_LCY) DR_BAL_LCY INTO #CURR FROM #BR where GL_CODE='13351000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13351000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13351000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13350000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13300000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'
print 11
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32111000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32110000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CURR C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

	END
	ELSE
	BEGIN
	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0
print 12
	SELECT CCY_CODE,SUM(CR_MOV_LCY)-SUM(DR_MOV_LCY)+SUM(DR_BAL_LCY) DR_BAL_LCY,SUM(CR_MOV)-SUM(DR_MOV)+SUM(DR_BAL) DR_BAL INTO #CUR22 FROM #BR where GL_CODE='13351000' and CUST_AC_NO not in  (
SELECT CUST_AC_NO FROM BBCDW..FACT_GL_ACC_BREAKUP where BGK_DATE=@BRANCH_DATE and GL_CODE='13351000') GROUP BY CCY_CODE

UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13351000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13350000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13300000'
UPDATE G SET CR_MOV_LCY=CR_MOV_LCY+C.DR_BAL_LCY,CR_MOV=CR_MOV+C.DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='13000000'

UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32111000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32110000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32100000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='32000000'
UPDATE G SET DR_MOV_LCY=DR_MOV_LCY+DR_BAL_LCY,DR_MOV=DR_MOV+DR_BAL FROM #GL1 G INNER JOIN #CUR22 C ON G.CCY_CODE=C.CCY_CODE WHERE GL_CODE='30000000'

	END

END

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1),CR_MOV_LCY=DR_MOV_LCY*(-1)  WHERE DR_MOV_LCY<0 AND CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1),CR_MOV=DR_MOV*(-1)  WHERE DR_MOV<0 AND CR_MOV<0

	UPDATE #GL1 SET DR_MOV_LCY=CR_MOV_LCY*(-1)+ DR_MOV_LCY,CR_MOV_LCY=0 WHERE CR_MOV_LCY<0
	UPDATE #GL1 SET DR_MOV=CR_MOV*(-1)+ DR_MOV,CR_MOV=0 WHERE CR_MOV<0

	UPDATE #GL1 SET CR_MOV_LCY=DR_MOV_LCY*(-1)+ CR_MOV_LCY,DR_MOV_LCY=0 WHERE DR_MOV_LCY<0
	UPDATE #GL1 SET CR_MOV=DR_MOV*(-1)+ CR_MOV,DR_MOV=0 WHERE DR_MOV<0

	INSERT INTO BBCDW..FACT_DAILY_GL_BAL(DATE_KEY,FIN_PERIOD_KEY,BRANCH_KEY,GL_KEY,PARENT_GL,
			CCY_KEY,CATEGORY_KEY,NBC_GL_CODE,LEAF,GL_DRCR,
			OPN_CR_FCY,OPN_DR_FCY,
			OPN_CR_LCY,OPN_DR_LCY,
			OPN_FCY_BAL,OPN_LCY_BAL,
			CR_MOV_FCY,DR_MOV_FCY,
			CR_MOV_LCY,DR_MOV_LCY,	  
			CLO_CR_FCY,CLO_DR_FCY,
			CLO_CR_LCY,CLO_DR_LCY,
			CLO_FCY_BAL,CLO_LCY_BAL,ETL_DT)
SELECT 
CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,FIN_PERIOD_KEY,BRANCH_KEY,GL_KEY,B.PARENT_GL,
			CCY_KEY,CATEGORY_KEY,GM.CBANK_LINE_CR,B.LEAF,GC.DRCR,
			ISNULL(OPN_CR,0),ISNULL(OPN_DR,0),
			ISNULL(OPN_CR_LCY,0),ISNULL(OPN_DR_LCY,0),
			ISNULL(OPN_CR,0)-ISNULL(OPN_DR,0),
			ISNULL(OPN_CR_LCY,0)-ISNULL(OPN_DR_LCY,0),
			CR_MOV,DR_MOV,
			CR_MOV_LCY,DR_MOV_LCY,	  
			CLO_CR,CLO_DR,
			CLO_CR_LCY,CLO_DR_LCY,
			(CLO_CR-CLO_DR)*VAL,(CLO_CR_LCY-CLO_DR_LCY)*VAL,ETL_DT FROM #GL1 B
INNER JOIN BBCDW..DIM_FIN_PERIOD FP ON B.FIN_YEAR=FP.FIN_YEAR AND FP.FIN_MONTH=B.PERIOD_CODE
		INNER JOIN BBCDW..DIM_BBC_BRANCH BR ON BR.BRANCH_CODE=B.BRANCH_CODE
		INNER JOIN BBCDW..DIM_GLMASTER GM ON B.GL_CODE=GM.GL_CODE and GM.IS_CURRENT=1
		INNER JOIN BBCDW..DIM_CURRENCY CY ON CY.CCY_CODE=B.CCY_CODE
		INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=B.CATEGORY

END
