CREATE PROC [dbo].[SP_ETL_FACT_AGENT_SUM] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

--DECLARE @BRANCH_DATE	DATE = '2024-05-25'
--			,@IS_RE_PROC BIT = 1

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_AGT_SUM WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

 IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
IF OBJECT_ID('tempdb..#TREQT') IS NOT NULL
DROP TABLE #TREQT
IF OBJECT_ID('tempdb..#NON') IS NOT NULL
DROP TABLE #NON
IF OBJECT_ID('tempdb..#DISPATCH') IS NOT NULL
DROP TABLE #DISPATCH
IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
DROP TABLE #TMP
IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
DROP TABLE #TMP1
IF OBJECT_ID('tempdb..#A') IS NOT NULL
DROP TABLE #A
IF OBJECT_ID('tempdb..#W') IS NOT NULL
DROP TABLE #W
IF OBJECT_ID('tempdb..#T') IS NOT NULL
DROP TABLE #T
IF OBJECT_ID('tempdb..#TT') IS NOT NULL
DROP TABLE #TT

SELECT * INTO #TREQT FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TREQT')

SELECT DISTINCT POL_CLI_ID
		,CASE 
		WHEN REQIR_ID IN ('U0193','U0194','U0195','U0196','U0197','U0198','U0199','U0200','U0201','U0202','0085','0086','0084','0097','U0207','U0208',
				'0084','0085','0086','0087','0088','0089','0090','0091','0092','0093','0094','0095','0095') 
			THEN (
					CASE WHEN CPREQ_STAT_CD IN ('CAN','WVD') THEN 'NON-ME' ELSE 'ME' END
				)  
		WHEN REQIR_ID  IN ('0098','U0209') 
			THEN (
					CASE WHEN CPREQ_STAT_CD IN ('CAN') THEN 'NON-COL' ELSE 'COL' END
				)  
		ELSE 'NON-ME' END NONJET_STATUS 
	INTO #NON FROM #TREQT

SELECT 
    CONVERT(VARCHAR, @BRANCH_DATE, 112) DATE_KEY,
    P.POL_KEY,
    C.COV_KEY,
    VA.AG_KEY,
    P.POL_ID,
    SUM(CVG_SUM_INS_AMT) CVG_FACE_AMT,
    P.POL_MPREM_AMT,
    P.POL_GRS_APREM_AMT,
    PA.ETBL_DESC_TXT PLAN_DESC,
    CASE 
        WHEN POL_BILL_MODE_CD = 3 THEN 'Quarterly' 
        WHEN POL_BILL_MODE_CD = 6 THEN 'Semi Annual' 
        WHEN POL_BILL_MODE_CD = 1 THEN 'Month' 
        WHEN POL_BILL_MODE_CD = 12 THEN 'Annual'
        ELSE POL_BILL_MODE_CD 
    END PRE_MODE,
    RTRIM(LTRIM(VVC.ENTR_SUR_NM)) + ' ' + RTRIM(LTRIM(VVC.ENTR_GIV_NM)) CLIENT_NAME,
    POL_APP_RECV_DT POL_CREAT_DT,
    W.AGT_ID,
    VA.ENTR_SUR_NM + ' ' + VA.ENTR_GIV_NM AGENT_NAME,
    VA.AGT_DISB_CHNL,
    CASE WHEN VA.CHANNEL = 'BA' THEN 'BANCA' ELSE 'AGENCY' END CSC_NAME,
    CASE 
        WHEN POL_BILL_MODE_CD = 3 THEN P.POL_MPREM_AMT * 4 
        WHEN POL_BILL_MODE_CD = 6 THEN P.POL_MPREM_AMT * 2 
        WHEN POL_BILL_MODE_CD = 1 THEN P.POL_MPREM_AMT * 12 
        WHEN POL_BILL_MODE_CD = 12 THEN P.POL_MPREM_AMT
        ELSE P.POL_MPREM_AMT 
    END APE,
    DATEDIFF(DAY, POL_APP_RECV_DT, GETDATE()) PENDING_DAYS,
    DATEADD(DAY, 21, POL_APP_RECV_DT) NTU,
    RR.REASON,
    CASE 
        WHEN NN.NONJET_STATUS IS NOT NULL THEN NN.NONJET_STATUS
        WHEN NN2.NONJET_STATUS IS NOT NULL THEN NN2.NONJET_STATUS
        WHEN NN3.NONJET_STATUS IS NOT NULL THEN NN3.NONJET_STATUS
        ELSE NN1.NONJET_STATUS 
    END NONJET_STATUS 
INTO #TMP 
FROM DLKHDIM..DIM_POLICY P 
INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID = P.POL_ID AND C.IS_CURRENT = 1 AND P.IS_CURRENT = 1 AND LEFT(C.PLAN_ID, 2) IN ('KB','CB','BE')
INNER JOIN DLKHDIM..DIM_POLICY_CLIENT PC ON PC.POL_ID = P.POL_ID AND PC.IS_CURRENT = 1
INNER JOIN DLKHSTAGE..SGTB_POLICY_WRITING W ON W.POL_ID = P.POL_ID
INNER JOIN V_AGENT VA ON VA.AGT_ID = W.AGT_ID --AND VA.AGT_CLI_REL_TYP_CD = 'M'
INNER JOIN DLKHDIM..DIM_CLIENT_IND VVC ON VVC.CLI_ID = PC.CLI_ID AND VVC.IS_CURRENT = 1
LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE PA ON P.PLAN_ID = PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID = 'PLAN' AND ETBL_LANG_CD = 'E' AND PA.CO_ID = 'CP'
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD = PARA.DM_AV_CD AND DM_AV_TBL_CD = 'POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD = 'E' AND PARA.CO_ID = 'CP'
LEFT JOIN #NON NN ON P.POL_ID = NN.POL_CLI_ID AND NN.NONJET_STATUS = 'ME'
LEFT JOIN #NON NN1 ON P.POL_ID = NN1.POL_CLI_ID AND NN1.NONJET_STATUS = 'Non-ME'
LEFT JOIN #NON NN2 ON P.POL_ID = NN2.POL_CLI_ID AND NN2.NONJET_STATUS = 'COL'
LEFT JOIN #NON NN3 ON P.POL_ID = NN3.POL_CLI_ID AND NN3.NONJET_STATUS = 'Non-COL'
LEFT JOIN (
    SELECT 
        POL_CLI_ID,
        STUFF((SELECT DISTINCT ', ' + LTRIM(RTRIM(RMRKS))
               FROM #TREQT t2
               WHERE t2.POL_CLI_ID = t1.POL_CLI_ID
               FOR XML PATH('')
        ), 1, 1, '') REASON
    FROM #TREQT t1
    GROUP BY POL_CLI_ID
) RR ON P.POL_ID = RR.POL_CLI_ID
WHERE P.POL_CSTAT_CD LIKE 'P%'
GROUP BY 
    P.POL_KEY, C.COV_KEY, VA.AG_KEY, P.POL_ID, P.POL_MPREM_AMT, PA.ETBL_DESC_TXT, P.POL_BILL_MODE_CD, VVC.ENTR_GIV_NM, VVC.ENTR_SUR_NM, 
    P.POL_APP_RECV_DT, W.AGT_ID, VA.ENTR_SUR_NM, VA.ENTR_GIV_NM, VA.AGT_DISB_CHNL, RR.REASON, NN.NONJET_STATUS, NN2.NONJET_STATUS, 
    NN3.NONJET_STATUS, NN1.NONJET_STATUS, P.POL_GRS_APREM_AMT, VA.CHANNEL, va.AGT_DISB_CHNL;

UPDATE #TMP 
SET NONJET_STATUS = 'COL+ME'  
WHERE POL_ID IN (
    SELECT N.POL_CLI_ID 
    FROM #NON N 
    INNER JOIN #NON N1 ON N.POL_CLI_ID = N1.POL_CLI_ID AND N.NONJET_STATUS = 'COL' AND N1.NONJET_STATUS = 'ME'
);

INSERT INTO DLKHFACT..FACT_AGT_SUM
SELECT * FROM #TMP;

end
