-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 29-SEP-2016
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_FACT_DD_FX_CASH_SETTL] 
	@BRANCH_DATE AS DATE,@DB_NAME VARCHAR(15),@SERVER_NAME VARCHAR(15),@IS_RE_PROC BIT=0
AS
BEGIN
	
	 IF OBJECT_ID('tempdb..#ENTRIES') IS NOT NULL
  DROP TABLE #ENTRIES
	IF @IS_RE_PROC=1 
	BEGIN
			DELETE FROM BBCNBCMART..FACT_DAILY_FX_CASH_SETTLEMENT WHERE DATE_KEY= CONVERT(VARCHAR,@BRANCH_DATE,112)
			DELETE FROM BBCNBCMART..FACT_WEEKLY_FX_CASH_SETTLEMENT WHERE DATE_KEY= CONVERT(VARCHAR,@BRANCH_DATE,112)
	END

	DECLARE @EX_RATE_KHR AS FLOAT=0.0,@EX_RATE_THB AS FLOAT=0.0,@EX_RATE_EUR AS FLOAT=0.0,@TODAY_DATE AS DATE;
	DECLARE @EX_RATE_KHR_L AS FLOAT,@EX_RATE_THB_L AS FLOAT,@EX_RATE_EUR_L AS FLOAT;

	DECLARE
			@OPENING_CASH_BAL_KHR		MONEY=0.0, 

			@ADJUSTMENT_Open numeric(10,2),@ADJUSTMENT_Close numeric(10,2),
			-- FROM DEPOSIT
			@TODAY_CASH_CR_BAL_KHR		MONEY=0.0,
			@FROM_DEPOSIT_KHR			MONEY=0.0,
			@FROM_DEPOSIT_SAVING_KHR	MONEY=0.0,
			@FROM_DEPOSIT_CURRENT_KHR	MONEY=0.0,
			@FROM_DEPOSIT_FIXED_KHR		MONEY=0.0,
			@FROM_NBC_KHR				MONEY=0.0,
			@SALE_CURRENCY_KHR			MONEY=0.0,
			@OTHER_CASH_RECEIPT_KHR		MONEY=0.0,

			-- WITHDRAWAL
			@TODAY_CASH_DR_BAL_KHR		MONEY=0.0,
			@WITHDRAWAL_DEPOSIT_KHR		MONEY=0.0,
			@WITHDRAWAL_DEPOSIT_SAVING_KHR MONEY=0.0,
			@WITHDRAWAL_DEPOSIT_CURRENT_KHR MONEY=0.0,
			@WITHDRAWAL_DEPOSIT_FIXED_KHR MONEY=0.0,
			@TO_NBC_KHR				MONEY=0.0,
			@PURCHASE_CURRENCY_KHR		MONEY=0.0,
			@OTHER_PAYMENTS_KHR			MONEY=0.0 ,

			@OPENING_CASH_BAL		MONEY=0.0, 
			@OPENING_CASH_BAL_AD       Money,
			-- FROM DEPOSIT
			@TODAY_CASH_CR_BAL		MONEY=0.0,
			@FROM_DEPOSIT			MONEY=0.0,
			@FROM_DEPOSIT_SAVING	MONEY=0.0,
			@FROM_DEPOSIT_CURRENT	MONEY=0.0,
			@FROM_DEPOSIT_FIXED		MONEY=0.0,
			@FROM_NBC				MONEY=0.0,
	@SALE_CURRENCY			MONEY=0.0,
			@OTHER_CASH_RECEIPT		MONEY=0.0,

			-- WITHDRAWAL
			@TODAY_CASH_DR_BAL		MONEY=0.0,
			@WITHDRAWAL_DEPOSIT		MONEY=0.0,
			@WITHDRAWAL_DEPOSIT_SAVING MONEY=0.0,
			@WITHDRAWAL_DEPOSIT_CURRENT MONEY=0.0,
			@WITHDRAWAL_DEPOSIT_FIXED MONEY=0.0,
			@TO_NBC				MONEY=0.0,
			@PURCHASE_CURRENCY		MONEY=0.0,
			@OTHER_PAYMENTS			MONEY=0.0,
			@PETTY_CASH MONEY,
			@PETTY_CASH_KHR MONEY

			
			select @EX_RATE_KHR=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='KHR' and RATE_DATE=@BRANCH_DATE and BRANCH_CODE='001'
			select @EX_RATE_THB=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='THB' and RATE_DATE=@BRANCH_DATE and BRANCH_CODE='001'
			select @EX_RATE_EUR=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='EUR' and RATE_DATE=@BRANCH_DATE and BRANCH_CODE='001'

			select @EX_RATE_KHR_L=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='KHR' and RATE_DATE=(select MAX(RATE_DATE) from BBCDW..DIM_RATE where RATE_DATE<@BRANCH_DATE) and BRANCH_CODE='001'
			select @EX_RATE_THB_L=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='THB' and RATE_DATE=(select MAX(RATE_DATE) from BBCDW..DIM_RATE where RATE_DATE<@BRANCH_DATE) and BRANCH_CODE='001'
			select @EX_RATE_EUR_L=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='EUR' and RATE_DATE=(select MAX(RATE_DATE) from BBCDW..DIM_RATE where RATE_DATE<@BRANCH_DATE) and BRANCH_CODE='001'

			IF ISNULL(@EX_RATE_KHR,0)<=0  
			BEGIN
			
			select MAX(RATE_DATE) from BBCDW..DIM_RATE where RATE_DATE<@BRANCH_DATE
			select @EX_RATE_KHR=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='KHR' and RATE_DATE=(select MAX(RATE_DATE) from BBCDW..DIM_RATE where RATE_DATE<@BRANCH_DATE) and BRANCH_CODE='001'
			select @EX_RATE_THB=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='THB' and RATE_DATE=(select MAX(RATE_DATE) from BBCDW..DIM_RATE where RATE_DATE<@BRANCH_DATE) and BRANCH_CODE='001'
			select @EX_RATE_EUR=MID_RATE from BBCDW..DIM_RATE where RATE_TYPE='NBC' and CCY1='USD' and CCY2='EUR' and RATE_DATE=(select MAX(RATE_DATE) from BBCDW..DIM_RATE where RATE_DATE<@BRANCH_DATE) and BRANCH_CODE='001'
			
			END
			Print @EX_RATE_KHR 
			Print @EX_RATE_EUR
			Print @EX_RATE_THB
			-- GET OPENING CASH BALANCE
			SELECT 
					@OPENING_CASH_BAL= isnull(SUM((G.OPN_FCY_BAL*GC.VAL)/@EX_RATE_THB),0),
					@OPENING_CASH_BAL_AD=isnull(SUM((G.OPN_FCY_BAL*GC.VAL)/@EX_RATE_THB_L),0)
			FROM BBCDW..FACT_DAILY_GL_BAL G 
			INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=G.CATEGORY_KEY
			INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=G.CCY_KEY
			WHERE 
			 CU.CCY_CODE='THB' -- Exclude KHR Currency
				AND   G.GL_KEY IN(SELECT GL_KEY FROM BBCDW..DIM_GLMASTER M WHERE M.GL_CODE IN('11110000') and m.IS_CURRENT=1)
				  AND G.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
			
			SELECT 
					@OPENING_CASH_BAL=isnull(@OPENING_CASH_BAL,0)+ isnull(SUM((G.OPN_FCY_BAL*GC.VAL)*@EX_RATE_EUR),0),
					@OPENING_CASH_BAL_AD=isnull(@OPENING_CASH_BAL_AD,0)+ isnull(SUM((G.OPN_FCY_BAL*GC.VAL)*@EX_RATE_EUR_L),0)
			FROM BBCDW..FACT_DAILY_GL_BAL G 
			INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=G.CATEGORY_KEY
			INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=G.CCY_KEY
			WHERE 
			 CU.CCY_CODE='EUR' -- Exclude KHR Currency
				AND   G.GL_KEY IN(SELECT GL_KEY FROM BBCDW..DIM_GLMASTER M WHERE M.GL_CODE IN('11110000') and m.IS_CURRENT=1)
				  AND G.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
			SELECT 
					@OPENING_CASH_BAL=isnull(@OPENING_CASH_BAL,0)+ isnull(SUM(G.OPN_LCY_BAL*GC.VAL),0),
					@OPENING_CASH_BAL_AD=isnull(@OPENING_CASH_BAL_AD,0)+ isnull(SUM(G.OPN_LCY_BAL*GC.VAL),0)
			FROM BBCDW..FACT_DAILY_GL_BAL G 
			INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=G.CATEGORY_KEY
			INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=G.CCY_KEY
			WHERE 
			 CU.CCY_CODE='USD' -- Exclude KHR Currency
				AND   G.GL_KEY IN(SELECT GL_KEY FROM BBCDW..DIM_GLMASTER M WHERE M.GL_CODE IN('11110000') and m.IS_CURRENT=1)
				  AND G.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)

			SELECT 
					@OPENING_CASH_BAL_KHR= isnull(SUM(G.OPN_FCY_BAL*GC.VAL),0)
			FROM BBCDW..FACT_DAILY_GL_BAL G 
			INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=G.CATEGORY_KEY
			WHERE 
			 G.CCY_KEY=96 -- Include KHR Currency
				AND   G.GL_KEY IN(SELECT GL_KEY FROM BBCDW..DIM_GLMASTER M WHERE M.GL_CODE IN('11110000') and m.IS_CURRENT=1)
				  AND G.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
	

			-- GET TODAY DR AND CR CASH MOVEMENT
			SELECT 
					@TODAY_CASH_DR_BAL= ISNULL(SUM(G.DR_MOV_LCY),0),
					@TODAY_CASH_CR_BAL=ISNULL(SUM(G.CR_MOV_LCY),0)
			FROM BBCDW..FACT_DAILY_GL_BAL G 
			INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=G.CATEGORY_KEY
			INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=G.CCY_KEY
			WHERE  
			CU.CCY_CODE='USD' -- Exclude KHR Currency
				AND  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
				 AND G.GL_KEY IN(SELECT GL_KEY FROM BBCDW..DIM_GLMASTER M WHERE M.GL_CODE IN('11110000') and IS_CURRENT=1)
			SELECT 
					@TODAY_CASH_DR_BAL= @TODAY_CASH_DR_BAL+ISNULL(SUM(G.DR_MOV_FCY),0)*@EX_RATE_EUR,
					@TODAY_CASH_CR_BAL=@TODAY_CASH_CR_BAL+ISNULL(SUM(G.CR_MOV_FCY),0)*@EX_RATE_EUR
			FROM BBCDW..FACT_DAILY_GL_BAL G 
			INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=G.CATEGORY_KEY
			INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=G.CCY_KEY
			WHERE  
			CU.CCY_CODE='EUR' -- Exclude KHR Currency
				AND  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
				 AND G.GL_KEY IN(SELECT GL_KEY FROM BBCDW..DIM_GLMASTER M WHERE M.GL_CODE IN('11110000') and IS_CURRENT=1)
			SELECT 
					@TODAY_CASH_DR_BAL= @TODAY_CASH_DR_BAL+ISNULL(SUM(G.DR_MOV_FCY),0)/@EX_RATE_THB,
					@TODAY_CASH_CR_BAL=@TODAY_CASH_CR_BAL+ISNULL(SUM(G.CR_MOV_FCY),0)/@EX_RATE_THB
			FROM BBCDW..FACT_DAILY_GL_BAL G 
			INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=G.CATEGORY_KEY
			INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=G.CCY_KEY
			WHERE  
			CU.CCY_CODE='THB' -- Exclude KHR Currency
				AND  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
				 AND G.GL_KEY IN(SELECT GL_KEY FROM BBCDW..DIM_GLMASTER M WHERE M.GL_CODE IN('11110000') and IS_CURRENT=1)
			SELECT 
					@TODAY_CASH_DR_BAL_KHR= ISNULL(SUM(G.DR_MOV_FCY),0),
					@TODAY_CASH_CR_BAL_KHR=ISNULL(SUM(G.CR_MOV_FCY),0)
			FROM BBCDW..FACT_DAILY_GL_BAL G 
			INNER JOIN BBCDW..DIM_GLCATEGORY GC ON GC.CATEGORY_KEY=G.CATEGORY_KEY
			INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=G.CCY_KEY
			WHERE  
			CU.CCY_CODE='KHR' -- Exclude KHR Currency
				AND  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
				 AND G.GL_KEY IN(SELECT GL_KEY FROM BBCDW..DIM_GLMASTER M WHERE M.GL_CODE IN('11110000') and IS_CURRENT=1)
			--*********************
			--	FROM DEPOSIT
			--*********************
select E.TRN_REF_NO,AC_NO,AC_CCY,E.TRN_CODE,LCY_AMOUNT,FCY_AMOUNT,DRCR_IND into #ENTRIES from SGTB_AC_ENTRIES E where E.TRN_DT=@BRANCH_DATE and E.TRN_CODE IN (205,206,207)
UPDATE R SET AC_CCY=E1.AC_CCY,FCY_AMOUNT=E1.FCY_AMOUNT from  #ENTRIES R inner join #ENTRIES E1 on E1.TRN_REF_NO=R.TRN_REF_NO WHERE E1.AC_NO in ('11110001','11110002')
select @PETTY_CASH=isnull(SUM(LCY_AMOUNT),0) from #ENTRIES  WHERE AC_NO in ('001000002300075',
'001000002300064',
'001000002300100',
'001000002300086',
'001000002300053',
'001000002300097') and AC_CCY='USD' and TRN_CODE<>'205'
select @PETTY_CASH=@PETTY_CASH+isnull(SUM(FCY_AMOUNT),0)*@EX_RATE_EUR from #ENTRIES  WHERE AC_NO in ('001000002300075',
'001000002300064',
'001000002300100',
'001000002300086',
'001000002300053',
'001000002300097') and AC_CCY='EUR' and TRN_CODE<>'205'
select @PETTY_CASH=@PETTY_CASH+isnull(SUM(FCY_AMOUNT),0)/@EX_RATE_THB from #ENTRIES  WHERE AC_NO in ('001000002300075',
'001000002300064',
'001000002300100',
'001000002300086',
'001000002300053',
'001000002300097') and AC_CCY='THB' and TRN_CODE<>'205'
select @PETTY_CASH_KHR=isnull(SUM(FCY_AMOUNT),0) from #ENTRIES  WHERE AC_NO in ('001000002300075',
'001000002300064',
'001000002300100',
'001000002300086',
'001000002300053',
'001000002300097') and AC_CCY='KHR' and TRN_CODE<>'205'
UPDATE R SET FCY_AMOUNT=0,LCY_AMOUNT=0 from  #ENTRIES R inner join #ENTRIES E1 on E1.TRN_REF_NO=R.TRN_REF_NO WHERE E1.AC_NO in ('001000002300075',
'001000002300064',
'001000002300100',
'001000002300086',
'001000002300053',
'001000002300097')

			-- GET FROM DEPOSIT (SAVING, CURRENT AND FIXED)
			SELECT 
					@FROM_DEPOSIT=ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN ISNULL(E.FCY_AMOUNT,0)/@EX_RATE_THB ELSE 0 END),0) ,
					@FROM_DEPOSIT_SAVING =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='S' THEN ISNULL(E.FCY_AMOUNT,0)/@EX_RATE_THB ELSE 0 END),0),
					@FROM_DEPOSIT_CURRENT =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='U' THEN ISNULL(E.FCY_AMOUNT,0)/@EX_RATE_THB ELSE 0 END),0),
					@FROM_DEPOSIT_FIXED =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='Y' THEN ISNULL(E.FCY_AMOUNT,0)/@EX_RATE_THB ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			WHERE 
				AC.ACCOUNT_TYPE IN('S','U','Y')
			AND E.AC_CCY='THB'
			SELECT 
					@FROM_DEPOSIT=@FROM_DEPOSIT+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN ISNULL(E.FCY_AMOUNT,0)*@EX_RATE_EUR ELSE 0 END),0) ,
					@FROM_DEPOSIT_SAVING =@FROM_DEPOSIT_SAVING+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='S' THEN ISNULL(E.FCY_AMOUNT,0)*@EX_RATE_EUR ELSE 0 END),0),
					@FROM_DEPOSIT_CURRENT =@FROM_DEPOSIT_CURRENT+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='U' THEN ISNULL(E.FCY_AMOUNT,0)*@EX_RATE_EUR ELSE 0 END),0),
					@FROM_DEPOSIT_FIXED =@FROM_DEPOSIT_FIXED+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='Y' THEN ISNULL(E.FCY_AMOUNT,0)*@EX_RATE_EUR ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			WHERE 
				AC.ACCOUNT_TYPE IN('S','U','Y')
			AND E.AC_CCY='EUR'
			SELECT 
					@FROM_DEPOSIT=@FROM_DEPOSIT+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN ISNULL(E.LCY_AMOUNT,0) ELSE 0 END),0) ,
					@FROM_DEPOSIT_SAVING =@FROM_DEPOSIT_SAVING+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='S' THEN ISNULL(E.LCY_AMOUNT,0) ELSE 0 END),0),
					@FROM_DEPOSIT_CURRENT =@FROM_DEPOSIT_CURRENT+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='U' THEN ISNULL(E.LCY_AMOUNT,0) ELSE 0 END),0),
					@FROM_DEPOSIT_FIXED =@FROM_DEPOSIT_FIXED+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='Y' THEN ISNULL(E.LCY_AMOUNT,0) ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			WHERE 
				AC.ACCOUNT_TYPE IN('S','U','Y')
			AND E.AC_CCY='USD'
			SELECT 
					@FROM_DEPOSIT_KHR=ISNULL(SUM(CASE WHEN E.DRCR_IND='C'  THEN E.FCY_AMOUNT ELSE 0 END),0) ,
					@FROM_DEPOSIT_SAVING_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='S' THEN E.FCY_AMOUNT ELSE 0 END),0),
					@FROM_DEPOSIT_CURRENT_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='U' THEN E.FCY_AMOUNT ELSE 0 END),0),
					@FROM_DEPOSIT_FIXED_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='Y' THEN E.FCY_AMOUNT ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			WHERE 
				AC.ACCOUNT_TYPE IN('S','U','Y') 
			AND E.AC_CCY='KHR'
			
			---FIXED---
			--SELECT 
					
			--		@FROM_DEPOSIT_FIXED =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='Y' THEN E.LCY_AMOUNT ELSE 0 END),0)

			--FROM SGTB_AC_ENTRIES E
			--INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			--WHERE 
			--	E.TRN_DT=@BRANCH_DATE AND
			--	AC.ACCOUNT_TYPE='Y'
			--AND E.AC_CCY<>'KHR'
			--SELECT 
					
			--		@FROM_DEPOSIT_FIXED_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' AND AC.ACCOUNT_TYPE='Y' THEN E.FCY_AMOUNT ELSE 0 END),0)

			--FROM SGTB_AC_ENTRIES E
			--INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			--WHERE 
			--	E.TRN_DT=@BRANCH_DATE AND
			--	AC.ACCOUNT_TYPE='Y'
			--AND E.AC_CCY='KHR'

			---FROM NBC---
			SELECT 
					@FROM_NBC =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN E.FCY_AMOUNT/@EX_RATE_THB ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
			WHERE 
				CUS.CUSTOMER_CATEGORY='NBC'
			AND E.AC_CCY='THB'
			SELECT 
					@FROM_NBC =@FROM_NBC+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN E.FCY_AMOUNT*@EX_RATE_EUR ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
			WHERE 
				CUS.CUSTOMER_CATEGORY='NBC'
			AND E.AC_CCY='EUR'
			SELECT 
					@FROM_NBC =@FROM_NBC+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN E.LCY_AMOUNT ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
			WHERE 
				CUS.CUSTOMER_CATEGORY='NBC'
			AND E.AC_CCY='USD'

			SELECT 
					
					@FROM_NBC_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN E.FCY_AMOUNT ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
			WHERE 
				CUS.CUSTOMER_CATEGORY='NBC'
			AND E.AC_CCY='KHR'

			-- GET SALE OF FOREIGN CURRENCIES
			SELECT
					@SALE_CURRENCY=ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT/@EX_RATE_THB ELSE 0 END),0)
			FROM SGTB_AC_ENTRIES E
			WHERE E.AC_NO in ('11110001','11110002')
					AND E.TRN_CODE in (212,213) 
					and e.AC_CCY='THB'
					AND E.TRN_DT=@BRANCH_DATE
			SELECT
					@SALE_CURRENCY=@SALE_CURRENCY+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT*@EX_RATE_EUR ELSE 0 END),0)
			FROM SGTB_AC_ENTRIES E
			WHERE E.AC_NO in ('11110001','11110002')
					AND E.TRN_CODE in (212,213) 
					and e.AC_CCY='EUR'
					AND E.TRN_DT=@BRANCH_DATE

			SELECT
					@SALE_CURRENCY=@SALE_CURRENCY+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.LCY_AMOUNT ELSE 0 END),0)
			FROM SGTB_AC_ENTRIES E
			WHERE E.AC_NO in ('11110001','11110002')
					AND E.TRN_CODE in (212,213) 
					and e.AC_CCY='USD'
					AND E.TRN_DT=@BRANCH_DATE
			SELECT
					@SALE_CURRENCY_KHR=ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT ELSE 0 END),0)
			FROM SGTB_AC_ENTRIES E
			WHERE E.AC_NO in ('11110001','11110002')
					AND E.TRN_CODE in (212,213) 
					and e.AC_CCY='KHR'
					AND E.TRN_DT=@BRANCH_DATE

					if @OPENING_CASH_BAL>@OPENING_CASH_BAL_AD

				Begin
					
					set @ADJUSTMENT_Open = @OPENING_CASH_BAL-@OPENING_CASH_BAL_AD
					set @ADJUSTMENT_Close = 0

				End
			Else if @OPENING_CASH_BAL=@OPENING_CASH_BAL_AD
				
				Begin
				
					set @ADJUSTMENT_Close=0
					set @ADJUSTMENT_Open=0

				End 
			Else
				Begin
				
					set @ADJUSTMENT_Close= @OPENING_CASH_BAL_AD-@OPENING_CASH_BAL
					set @ADJUSTMENT_Open=0

				End
			Print 'Open'
			Print @ADJUSTMENT_Open
			Print 'Close'
			Print @ADJUSTMENT_Close
			DECLARE @TRANSFER_DEPO MONEY,@TRANSFER_WITH MONEY,@TRANSFER_DEPO_KHR MONEY,@TRANSFER_WITH_KHR MONEY
			SELECT @TRANSFER_DEPO=isnull(SUM(LCY_AMOUNT),0) FROM SGTB_AC_ENTRIES WHERE TRN_DT=@BRANCH_DATE AND TRN_CODE IN (215,214,273,994,993) AND DRCR_IND='D' AND AC_CCY='USD'
			SELECT @TRANSFER_DEPO=@TRANSFER_DEPO+(isnull(SUM(FCY_AMOUNT),0)*@EX_RATE_EUR) FROM SGTB_AC_ENTRIES WHERE TRN_DT=@BRANCH_DATE AND TRN_CODE IN (215,214,273,994,993) AND DRCR_IND='D' AND AC_CCY='EUR'
			SELECT @TRANSFER_DEPO=@TRANSFER_DEPO+(isnull(SUM(FCY_AMOUNT),0)/@EX_RATE_THB) FROM SGTB_AC_ENTRIES WHERE TRN_DT=@BRANCH_DATE AND TRN_CODE IN (215,214,273,994,993) AND DRCR_IND='D' AND AC_CCY='THB'
			SELECT @TRANSFER_DEPO_KHR=isnull(SUM(FCY_AMOUNT),0) FROM SGTB_AC_ENTRIES WHERE TRN_DT=@BRANCH_DATE AND TRN_CODE IN (215,214,273,994,993) AND DRCR_IND='D' AND AC_CCY='KHR'

			SELECT @TRANSFER_WITH=isnull(SUM(LCY_AMOUNT),0) FROM SGTB_AC_ENTRIES WHERE TRN_DT=@BRANCH_DATE AND TRN_CODE IN (215,214,273,994,993) AND DRCR_IND='C' AND AC_CCY='USD'
			SELECT @TRANSFER_WITH=@TRANSFER_WITH+(isnull(SUM(FCY_AMOUNT),0)*@EX_RATE_EUR) FROM SGTB_AC_ENTRIES WHERE TRN_DT=@BRANCH_DATE AND TRN_CODE IN (215,214,273,994,993) AND DRCR_IND='C' AND AC_CCY='EUR'
			SELECT @TRANSFER_WITH=@TRANSFER_WITH+(isnull(SUM(FCY_AMOUNT),0)/@EX_RATE_THB) FROM SGTB_AC_ENTRIES WHERE TRN_DT=@BRANCH_DATE AND TRN_CODE IN (215,214,273,994,993) AND DRCR_IND='C' AND AC_CCY='THB'
			SELECT @TRANSFER_WITH_KHR=SUM(FCY_AMOUNT) FROM SGTB_AC_ENTRIES WHERE TRN_DT=@BRANCH_DATE AND TRN_CODE IN (215,214,273,994,993) AND DRCR_IND='C' AND AC_CCY='KHR'
			-- OTHERS CASH DEPOSIT
			SET @OTHER_CASH_RECEIPT= ISNULL(@TODAY_CASH_DR_BAL,0)	- ISNULL(@SALE_CURRENCY,0) - ISNULL(@FROM_DEPOSIT,0)- ISNULL(@FROM_NBC,0) + @ADJUSTMENT_Open - @TRANSFER_DEPO - @PETTY_CASH
			SET @OTHER_CASH_RECEIPT_KHR=  ISNULL(@TODAY_CASH_DR_BAL_KHR,0)	- ISNULL(@SALE_CURRENCY_KHR,0) - ISNULL(@FROM_DEPOSIT_KHR,0)- ISNULL(@FROM_NBC_KHR,0) - @TRANSFER_DEPO_KHR - @PETTY_CASH_KHR

			--*********************
			--	WITHDRAWAL DEPOSIT
			--*********************

			SELECT 
					@WITHDRAWAL_DEPOSIT=ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT/@EX_RATE_THB ELSE 0 END),0) ,
					@WITHDRAWAL_DEPOSIT_SAVING =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='S' THEN E.FCY_AMOUNT/@EX_RATE_THB ELSE 0 END),0),
					@WITHDRAWAL_DEPOSIT_CURRENT =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='U' THEN E.FCY_AMOUNT/@EX_RATE_THB ELSE 0 END),0),
					@WITHDRAWAL_DEPOSIT_FIXED =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='Y' THEN E.FCY_AMOUNT/@EX_RATE_THB ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			WHERE 
				AC.ACCOUNT_TYPE IN('S','U','Y')
				AND E.AC_CCY='THB'
			 SELECT 
					@WITHDRAWAL_DEPOSIT=@WITHDRAWAL_DEPOSIT+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT*@EX_RATE_EUR ELSE 0 END),0) ,
					@WITHDRAWAL_DEPOSIT_SAVING =@WITHDRAWAL_DEPOSIT_SAVING+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='S' THEN E.FCY_AMOUNT*@EX_RATE_EUR ELSE 0 END),0),
					@WITHDRAWAL_DEPOSIT_CURRENT =@WITHDRAWAL_DEPOSIT_CURRENT+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='U' THEN E.FCY_AMOUNT*@EX_RATE_EUR ELSE 0 END),0),
					@WITHDRAWAL_DEPOSIT_FIXED =@WITHDRAWAL_DEPOSIT_FIXED+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='Y' THEN E.FCY_AMOUNT*@EX_RATE_EUR ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			WHERE 
				AC.ACCOUNT_TYPE IN('S','U','Y') 
				AND E.AC_CCY='EUR'
			 SELECT 
					@WITHDRAWAL_DEPOSIT=@WITHDRAWAL_DEPOSIT+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.LCY_AMOUNT ELSE 0 END),0) ,
					@WITHDRAWAL_DEPOSIT_SAVING =@WITHDRAWAL_DEPOSIT_SAVING+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='S' THEN E.LCY_AMOUNT ELSE 0 END),0),
					@WITHDRAWAL_DEPOSIT_CURRENT =@WITHDRAWAL_DEPOSIT_CURRENT+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='U' THEN E.LCY_AMOUNT ELSE 0 END),0),
					@WITHDRAWAL_DEPOSIT_FIXED =@WITHDRAWAL_DEPOSIT_FIXED+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='Y' THEN E.LCY_AMOUNT ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			WHERE 
				AC.ACCOUNT_TYPE IN('S','U','Y')
				AND E.AC_CCY='USD'
			 SELECT 
					@WITHDRAWAL_DEPOSIT_KHR=ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT ELSE 0 END),0) ,
					@WITHDRAWAL_DEPOSIT_SAVING_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='S' THEN E.FCY_AMOUNT ELSE 0 END),0),
					@WITHDRAWAL_DEPOSIT_CURRENT_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='U' THEN E.FCY_AMOUNT ELSE 0 END),0),
					@WITHDRAWAL_DEPOSIT_FIXED_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='Y' THEN E.FCY_AMOUNT ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			WHERE 
				AC.ACCOUNT_TYPE IN('S','U','Y')
				AND E.AC_CCY='KHR'
			 ----FIXED---
			-- SELECT 
			--		@WITHDRAWAL_DEPOSIT_FIXED =ISNULL(SUM(CASE WHEN E.DRCR_IND='D'  AND AC.ACCOUNT_TYPE='Y' THEN E.LCY_AMOUNT ELSE 0 END),0)
				

			--FROM SGTB_AC_ENTRIES E
			--INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			--WHERE 
			--	E.TRN_DT=@BRANCH_DATE AND
			--	AC.ACCOUNT_TYPE='Y'
			--	AND E.AC_CCY<>'KHR'
			--SELECT 
			--		@WITHDRAWAL_DEPOSIT_FIXED_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' AND AC.ACCOUNT_TYPE='Y' THEN E.FCY_AMOUNT ELSE 0 END),0)

			--FROM SGTB_AC_ENTRIES E
			--INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			--WHERE 
			--	E.TRN_DT=@BRANCH_DATE AND
			--	AC.ACCOUNT_TYPE='Y'
			--	AND E.AC_CCY='KHR'

			---TO NBC---
			SELECT 
					
					@TO_NBC =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT/@EX_RATE_THB ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
			WHERE 
				CUS.CUSTOMER_CATEGORY='NBC'
			AND E.AC_CCY='THB'
			SELECT 
					
					@TO_NBC =@TO_NBC+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT*@EX_RATE_EUR ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
			WHERE 
				CUS.CUSTOMER_CATEGORY='NBC'
			AND E.AC_CCY='EUR'
			SELECT 
					
					@TO_NBC =@TO_NBC+ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.LCY_AMOUNT ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
			WHERE 
				CUS.CUSTOMER_CATEGORY='NBC'
			AND E.AC_CCY='USD'
			SELECT 
					
					@TO_NBC_KHR =ISNULL(SUM(CASE WHEN E.DRCR_IND='D' THEN E.FCY_AMOUNT ELSE 0 END),0)

			FROM #ENTRIES E
			INNER JOIN  BBCDW..DIM_CUST_ACCOUNT AC ON E.AC_NO=AC.CUST_AC_NO AND AC.IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
			WHERE 
				CUS.CUSTOMER_CATEGORY='NBC'
			AND E.AC_CCY='KHR'

			SELECT
					@PURCHASE_CURRENCY=ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN E.FCY_AMOUNT/@EX_RATE_THB ELSE 0 END),0)
			FROM SGTB_AC_ENTRIES E
			WHERE E.AC_NO in ('11110001','11110002')
					AND E.TRN_CODE in (212,213) 
					and e.AC_CCY='THB'
					AND E.TRN_DT=@BRANCH_DATE
			SELECT
					@PURCHASE_CURRENCY=@PURCHASE_CURRENCY+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN E.FCY_AMOUNT*@EX_RATE_EUR ELSE 0 END),0)
			FROM SGTB_AC_ENTRIES E
			WHERE E.AC_NO in ('11110001','11110002')
					AND E.TRN_CODE in (212,213) 
					and e.AC_CCY='EUR'
					AND E.TRN_DT=@BRANCH_DATE
			SELECT
					@PURCHASE_CURRENCY=@PURCHASE_CURRENCY+ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN E.LCY_AMOUNT ELSE 0 END),0)
			FROM SGTB_AC_ENTRIES E
			WHERE E.AC_NO in ('11110001','11110002')
					AND E.TRN_CODE in (212,213) 
					and e.AC_CCY='USD'
					AND E.TRN_DT=@BRANCH_DATE
			SELECT
					@PURCHASE_CURRENCY_KHR=ISNULL(SUM(CASE WHEN E.DRCR_IND='C' THEN E.FCY_AMOUNT ELSE 0 END),0)
			FROM SGTB_AC_ENTRIES E
			WHERE E.AC_NO in ('11110001','11110002')
					AND E.TRN_CODE in (212,213)
					and e.AC_CCY='KHR'
					AND E.TRN_DT=@BRANCH_DATE

						-- OTHERS PAYMENT
			SET @OTHER_PAYMENTS=ISNULL(@TODAY_CASH_CR_BAL,0)-ISNULL(@WITHDRAWAL_DEPOSIT,0)-ISNULL(@PURCHASE_CURRENCY,0)-ISNULL(@TO_NBC,0)+@ADJUSTMENT_Close - @TRANSFER_WITH - @PETTY_CASH
			SET @OTHER_PAYMENTS_KHR=ISNULL(@TODAY_CASH_CR_BAL_KHR,0)-ISNULL(@WITHDRAWAL_DEPOSIT_KHR,0)-ISNULL(@PURCHASE_CURRENCY_KHR,0)-ISNULL(@TO_NBC_KHR,0)- isnull(@TRANSFER_WITH_KHR ,0) -@PETTY_CASH_KHR
			DECLARE @TAB AS TABLE(DATE_KEY INT,ITEM_KEY INT,EX_RATE MONEY,AMT_IN_USD MONEY,AMT_IN_RIEL MONEY,ETL_DT DATETIME)

			DECLARE @II_TOTAL_Total_Receipts_in_FX MONEY,@III_SUB_TOAL MONEY,@IV_TOTAL_Deduct_Payments_in_FX MONEY,@V_BAL_END_OF_PERIOD MONEY

			SET @II_TOTAL_Total_Receipts_in_FX=ISNULL(@FROM_DEPOSIT,0)+ISNULL(@SALE_CURRENCY,0)+ISNULL(@OTHER_CASH_RECEIPT,0)+ISNULL(@FROM_NBC,0)
			SET @III_SUB_TOAL=ISNULL(@OPENING_CASH_BAL_AD,0)+ISNULL(@II_TOTAL_Total_Receipts_in_FX,0)
			SET @IV_TOTAL_Deduct_Payments_in_FX=ISNULL(@WITHDRAWAL_DEPOSIT,0)+ISNULL(@PURCHASE_CURRENCY,0)+ISNULL(@OTHER_PAYMENTS,0)+ISNULL(@TO_NBC,0)
			SET @V_BAL_END_OF_PERIOD=@III_SUB_TOAL-@IV_TOTAL_Deduct_Payments_in_FX

			-- FROM DEPOSIT ITEMS
			INSERT INTO @TAB 
			VALUES(CONVERT(VARCHAR,@BRANCH_DATE,112),1,@EX_RATE_KHR,@OPENING_CASH_BAL_AD,@OPENING_CASH_BAL_AD*@EX_RATE_KHR,GETDATE()),	-- OPENING CASH BALANCE
					(CONVERT(VARCHAR,@BRANCH_DATE,112),2,@EX_RATE_KHR,@FROM_DEPOSIT,@FROM_DEPOSIT*@EX_RATE_KHR,GETDATE()),			-- FROM DEPOSIT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),3,@EX_RATE_KHR,@FROM_DEPOSIT_SAVING,@FROM_DEPOSIT_SAVING*@EX_RATE_KHR,GETDATE()), -- FROM DEPOSIT SAVING
					(CONVERT(VARCHAR,@BRANCH_DATE,112),4,@EX_RATE_KHR,@FROM_DEPOSIT_CURRENT,@FROM_DEPOSIT_CURRENT*@EX_RATE_KHR,GETDATE()), -- FROM DEPOSIT CURRENT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),5,@EX_RATE_KHR,@FROM_DEPOSIT_FIXED,@FROM_DEPOSIT_FIXED*@EX_RATE_KHR,GETDATE()), -- FROM DEPOSIT FIXED
					(CONVERT(VARCHAR,@BRANCH_DATE,112),6,@EX_RATE_KHR,0,0,GETDATE()), -- LOAN REPAYMENTS, No Bussiness Required so amount zero
					(CONVERT(VARCHAR,@BRANCH_DATE,112),7,@EX_RATE_KHR,@SALE_CURRENCY,@SALE_CURRENCY*@EX_RATE_KHR,GETDATE()), -- SALE OF CURRENCIES
					(CONVERT(VARCHAR,@BRANCH_DATE,112),8,@EX_RATE_KHR,@FROM_NBC,@FROM_NBC*@EX_RATE_KHR,GETDATE()), -- Fund from NBC, zero for now
					(CONVERT(VARCHAR,@BRANCH_DATE,112),9,@EX_RATE_KHR,0,0,GETDATE()), -- Fund from Banks, zero for now
					(CONVERT(VARCHAR,@BRANCH_DATE,112),10,@EX_RATE_KHR,@OTHER_CASH_RECEIPT,@OTHER_CASH_RECEIPT*@EX_RATE_KHR,GETDATE()), -- OTHERS RECEIPT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),11,@EX_RATE_KHR,@II_TOTAL_Total_Receipts_in_FX,@II_TOTAL_Total_Receipts_in_FX*@EX_RATE_KHR,GETDATE()),  --Total Receipts in Foreign Currency (1+2+3+4+5+6)
					(CONVERT(VARCHAR,@BRANCH_DATE,112),12,@EX_RATE_KHR,@III_SUB_TOAL,@III_SUB_TOAL*@EX_RATE_KHR,GETDATE()) --Sub-Total=    (I+II)

			-- WITHDRAWAL DEPOSIT ITEMS
			INSERT INTO @TAB 
					VALUES (CONVERT(VARCHAR,@BRANCH_DATE,112),13,@EX_RATE_KHR,@WITHDRAWAL_DEPOSIT,@WITHDRAWAL_DEPOSIT*@EX_RATE_KHR,GETDATE()),			-- WITHDRAWAL DEPOSIT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),14,@EX_RATE_KHR,@WITHDRAWAL_DEPOSIT_SAVING,@WITHDRAWAL_DEPOSIT_SAVING*@EX_RATE_KHR,GETDATE()), -- FROM DEPOSIT SAVING
					(CONVERT(VARCHAR,@BRANCH_DATE,112),15,@EX_RATE_KHR,@WITHDRAWAL_DEPOSIT_CURRENT,@WITHDRAWAL_DEPOSIT_CURRENT*@EX_RATE_KHR,GETDATE()), -- FROM DEPOSIT CURRENT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),16,@EX_RATE_KHR,@WITHDRAWAL_DEPOSIT_FIXED,@WITHDRAWAL_DEPOSIT_FIXED*@EX_RATE_KHR,GETDATE()), -- FROM DEPOSIT FIXED
					(CONVERT(VARCHAR,@BRANCH_DATE,112),17,@EX_RATE_KHR,0,0,GETDATE()), -- Loan paid out, No Bussiness Required so amount zero
					(CONVERT(VARCHAR,@BRANCH_DATE,112),18,@EX_RATE_KHR,@PURCHASE_CURRENCY,@PURCHASE_CURRENCY*@EX_RATE_KHR,GETDATE()), -- PURCHASE OF CURRENCIES
					(CONVERT(VARCHAR,@BRANCH_DATE,112),19,@EX_RATE_KHR,@TO_NBC,@TO_NBC*@EX_RATE_KHR,GETDATE()), -- Fund to NBC, zero for now
					(CONVERT(VARCHAR,@BRANCH_DATE,112),20,@EX_RATE_KHR,0,0,GETDATE()), -- Fund to Banks, zero for now
					(CONVERT(VARCHAR,@BRANCH_DATE,112),21,@EX_RATE_KHR,@OTHER_PAYMENTS,@OTHER_PAYMENTS*@EX_RATE_KHR,GETDATE()), -- Others payments
					(CONVERT(VARCHAR,@BRANCH_DATE,112),22,@EX_RATE_KHR,@IV_TOTAL_Deduct_Payments_in_FX,@IV_TOTAL_Deduct_Payments_in_FX*@EX_RATE_KHR,GETDATE()),  --Deduct payments in Forieng Currency				
					(CONVERT(VARCHAR,@BRANCH_DATE,112),23,@EX_RATE_KHR,@V_BAL_END_OF_PERIOD,@V_BAL_END_OF_PERIOD*@EX_RATE_KHR,GETDATE()) --Sub-Total=    (I+II)
					

			INSERT BBCNBCMART..FACT_DAILY_FX_CASH_SETTLEMENT 
			SELECT * FROM @TAB

			DECLARE @TAB1 AS TABLE(DATE_KEY INT,ITEM_KEY INT,EX_RATE MONEY,AMT_IN_USD MONEY,AMT_IN_RIEL MONEY,ETL_DT DATETIME)

			
			SET @II_TOTAL_Total_Receipts_in_FX=ISNULL(@FROM_DEPOSIT_KHR,0)+ISNULL(@SALE_CURRENCY_KHR,0)+ISNULL(@OTHER_CASH_RECEIPT_KHR,0)+ISNULL(@FROM_NBC_KHR,0)
			SET @III_SUB_TOAL=ISNULL(@OPENING_CASH_BAL_KHR,0)+ISNULL(@II_TOTAL_Total_Receipts_in_FX,0)
			SET @IV_TOTAL_Deduct_Payments_in_FX=ISNULL(@WITHDRAWAL_DEPOSIT_KHR,0)+ISNULL(@PURCHASE_CURRENCY_KHR,0)+ISNULL(@OTHER_PAYMENTS_KHR,0)+ISNULL(@TO_NBC_KHR,0)
			SET @V_BAL_END_OF_PERIOD=@III_SUB_TOAL-@IV_TOTAL_Deduct_Payments_in_FX

			-- FROM DEPOSIT ITEMS
			INSERT INTO @TAB1 
			VALUES(CONVERT(VARCHAR,@BRANCH_DATE,112),1,@EX_RATE_KHR,@OPENING_CASH_BAL_KHR,0,GETDATE()),	-- OPENING CASH BALANCE
					(CONVERT(VARCHAR,@BRANCH_DATE,112),2,@EX_RATE_KHR,@FROM_DEPOSIT_KHR,0,GETDATE()),			-- FROM DEPOSIT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),3,@EX_RATE_KHR,@FROM_DEPOSIT_SAVING_KHR,0,GETDATE()), -- FROM DEPOSIT SAVING
					(CONVERT(VARCHAR,@BRANCH_DATE,112),4,@EX_RATE_KHR,@FROM_DEPOSIT_CURRENT_KHR,0,GETDATE()), -- FROM DEPOSIT CURRENT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),5,@EX_RATE_KHR,@FROM_DEPOSIT_FIXED_KHR,0,GETDATE()), -- FROM DEPOSIT FIXED
					(CONVERT(VARCHAR,@BRANCH_DATE,112),6,@EX_RATE_KHR,0,0,GETDATE()), -- LOAN REPAYMENTS, No Bussiness Required so amount zero
					(CONVERT(VARCHAR,@BRANCH_DATE,112),7,@EX_RATE_KHR,@SALE_CURRENCY_KHR,0,GETDATE()), -- SALE OF CURRENCIES
					(CONVERT(VARCHAR,@BRANCH_DATE,112),8,@EX_RATE_KHR,@FROM_NBC_KHR,0,GETDATE()), -- Fund from NBC, zero for now
					(CONVERT(VARCHAR,@BRANCH_DATE,112),9,@EX_RATE_KHR,0,0,GETDATE()), -- Fund from Banks, zero for now
					(CONVERT(VARCHAR,@BRANCH_DATE,112),10,@EX_RATE_KHR,@OTHER_CASH_RECEIPT_KHR,0,GETDATE()), -- OTHERS RECEIPT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),11,@EX_RATE_KHR,@II_TOTAL_Total_Receipts_in_FX,0,GETDATE()),  --Total Receipts in Foreign Currency (1+2+3+4+5+6)
					(CONVERT(VARCHAR,@BRANCH_DATE,112),12,@EX_RATE_KHR,@III_SUB_TOAL,0,GETDATE()) --Sub-Total=    (I+II)

			-- WITHDRAWAL DEPOSIT ITEMS
			INSERT INTO @TAB1 
					VALUES (CONVERT(VARCHAR,@BRANCH_DATE,112),13,@EX_RATE_KHR,@WITHDRAWAL_DEPOSIT_KHR,0,GETDATE()),			-- WITHDRAWAL DEPOSIT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),14,@EX_RATE_KHR,@WITHDRAWAL_DEPOSIT_SAVING_KHR,0,GETDATE()), -- FROM DEPOSIT SAVING
					(CONVERT(VARCHAR,@BRANCH_DATE,112),15,@EX_RATE_KHR,@WITHDRAWAL_DEPOSIT_CURRENT_KHR,0,GETDATE()), -- FROM DEPOSIT CURRENT
					(CONVERT(VARCHAR,@BRANCH_DATE,112),16,@EX_RATE_KHR,@WITHDRAWAL_DEPOSIT_FIXED_KHR,0,GETDATE()), -- FROM DEPOSIT FIXED
					(CONVERT(VARCHAR,@BRANCH_DATE,112),17,@EX_RATE_KHR,0,0,GETDATE()), -- Loan paid out, No Bussiness Required so amount zero
					(CONVERT(VARCHAR,@BRANCH_DATE,112),18,@EX_RATE_KHR,@PURCHASE_CURRENCY_KHR,0,GETDATE()), -- PURCHASE OF CURRENCIES
					(CONVERT(VARCHAR,@BRANCH_DATE,112),19,@EX_RATE_KHR,@TO_NBC_KHR,0,GETDATE()), -- Fund to NBC, zero for now
					(CONVERT(VARCHAR,@BRANCH_DATE,112),20,@EX_RATE_KHR,0,0,GETDATE()), -- Fund to Banks, zero for now
					(CONVERT(VARCHAR,@BRANCH_DATE,112),21,@EX_RATE_KHR,@OTHER_PAYMENTS_KHR,0,GETDATE()), -- Others payments
					(CONVERT(VARCHAR,@BRANCH_DATE,112),22,@EX_RATE_KHR,@IV_TOTAL_Deduct_Payments_in_FX,0,GETDATE()),  --Deduct payments in Forieng Currency				
					(CONVERT(VARCHAR,@BRANCH_DATE,112),23,@EX_RATE_KHR,@V_BAL_END_OF_PERIOD,0,GETDATE()) --Sub-Total=    (I+II)
					

INSERT BBCNBCMART..FACT_WEEKLY_FX_CASH_SETTLEMENT 
			SELECT * FROM @TAB1

END
