-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 04-OCT-2016
-- Description:	ETL FACT TABLES MAIN BATCH
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_FACTS_MAIN] @BRANCH_DATE DATE,@EXEC_TYPE CHAR(2)='DD'
AS
BEGIN
	
	SET NOCOUNT ON;

	DECLARE @DB_NAME VARCHAR(20),@DBDW_NAME VARCHAR(20),@SERVER_NAME VARCHAR(20),@BATCH_NAME VARCHAR(100),@PROC_DESC VARCHAR(250)=''
	DECLARE @START_BATCH VARCHAR(10)='MAINFACTS'
	DECLARE @PROC_TIME AS DATETIME,@IS_ERROR BIT=0
	DECLARE @EFFECTIVE_DATE DATE, @IS_ENABLED BIT

	SELECT    @DB_NAME=B.DB_NAME
			, @DBDW_NAME=B.DBDW_NAME
			, @SERVER_NAME=B.SERVER_NAME 
			, @BATCH_NAME=B.BATCH_NAME
			, @IS_ENABLED=B.IS_ENABLED
			, @EFFECTIVE_DATE=B.EFFECTIVE_DATE
	FROM ETLM_BATCH B WHERE B.BATCH_CODE=@START_BATCH

	IF @EFFECTIVE_DATE>@BRANCH_DATE OR @IS_ENABLED=0 RETURN;

	
	-- Start ETL Process before BOD Batch
	SET @PROC_TIME=GETDATE()
	SET @PROC_DESC='Start running '+ @BATCH_NAME +'...'
	EXEC SP_ETL_PROC_WRITE_LOG 'ALL',@BRANCH_DATE,@START_BATCH,'S', @PROC_DESC,@PROC_TIME,NULL,'','',''

	---------------------------
	-- Execute Batch Process --
	---------------------------
	EXEC SP_ETL_PROC_BATCH_FACTS @BRANCH_DATE,@DB_NAME,@DBDW_NAME,@SERVER_NAME,@IS_ERROR OUT,@EXEC_TYPE 

	-- End ETL Process before BOD Batch
	IF @IS_ERROR=0 
	BEGIN
			SET @PROC_TIME=GETDATE()
			SET @PROC_DESC='End running '+ @BATCH_NAME +'.'
			EXEC SP_ETL_PROC_WRITE_LOG 'ALL',@BRANCH_DATE,@START_BATCH,'X',@PROC_DESC,NULL,@PROC_TIME,'','',''
	END;

END
