CREATE PROC [dbo].[SP_ETL_FACT_AXP_AGENT] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_AXP_AGENT WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

INSERT INTO DLKHFACT..FACT_AXP_AGENT
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,AGENT_KEY,PARTY_ID AGENT_CODE,SURNAME,NAME2,AGENT_TYPE,CREAT_DT,LAS_MOV,LAS_MOV_DT,CSC_NAME,TEAM_TYPE,TEAM_CODE_1,TEAM_NAME_1,
TEAM_CODE_2,TEAM_NAME_2,TEAM_CODE_3,TEAM_NAME_3,TEAM_CODE_4,TEAM_NAME_4,TEAM_CODE_5,TEAM_NAME_5,TEAM_CODE_6,TEAM_NAME_6,
DOB,MOBILE_NUM,BIS_PHONE,PIN,EMAIL,AddressLine1,AddressLine2,AddressLine3,AddressLine4,REPORT_TO FROM V_AGENT_INFO
END
