CREATE PROC [dbo].[SP_ETL_FACT_ACTURAIL] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_ACTURAIL WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
IF OBJECT_ID('tempdb..#C') IS NOT NULL
  DROP TABLE #C
  
  SELECT * INTO #C FROM DLKHDIM..DIM_COVERAGE

  

SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,CVG.COV_KEY,POL_KEY,CLI_KEY,CVG.POL_ID,CVG.CVG_NUM,CVG.PLAN_ID,CASE WHEN LEFT(CVG.PLAN_ID,1)='K' THEN '1' 
WHEN LEFT(CVG.PLAN_ID,2)='DW' THEN '2' ELSE '3' END BEN_NO,CVG_APP_CMPLT_DT,CVG_ISS_EFF_DT,CVG.CVG_STAT_PRCES_DT,CVG.CVG_CSTAT_CD,CVG.CVG_PREV_CSTAT_CD,
CASE WHEN LEFT(CVG.PLAN_ID,1)='K' THEN 'AE' WHEN LEFT(CVG.PLAN_ID,2)='DW' THEN 'PWOP' ELSE 'TRIDER' END CLASS,CVG_FACE_AMT,
CASE WHEN POL_BILL_MODE_CD=3 THEN 'Q' WHEN POL_BILL_MODE_CD=6 THEN 'H' WHEN POL_BILL_MODE_CD=1 THEN 'M' WHEN POL_BILL_MODE_CD=12 THEN 'Y'
ELSE POL_BILL_MODE_CD END PRE_MODE,CVGC.INSRD_CLI_ID,C.CLI_SEX_CD,C.CLI_BTH_DT,ISNULL(PO.CLI_SEX_CD,POO.CLI_SEX_CD) POSEX,ISNULL(PO.CLI_BTH_DT,POO.CLI_BTH_DT) POBOD,CVG.CVG_MAT_XPRY_DT,
case when P.POL_BILL_MODE_CD=1 then CVG.CVG_MPREM_AMT*12 when P.POL_BILL_MODE_CD=3 then CVG.CVG_MPREM_AMT*4 when P.POL_BILL_MODE_CD=6 then CVG.CVG_MPREM_AMT*2 else CVG.CVG_MPREM_AMT end TARGET_PREM,CVG.CVG_MPREM_AMT
,POL_PD_TO_DT_NUM,CVG.CVG_RT_AGE AGE,W.AGT_ID,CVG_ME_FCT,(CVG_ME_FCT-1)* 100 AS MEDICAL_LOADING_PERCENT,
CVG_BASIC_PREM_AMT,CASE WHEN CVG_CSTAT_CD='1' AND LEFT(CVG_PREV_CSTAT_CD,1)='P' THEN 'ISSUED'
WHEN LEFT(CVG_CSTAT_CD,1)='P' THEN 'PENDING'
WHEN CVG_CSTAT_CD='D' THEN 'DEAD'
WHEN CVG_CSTAT_CD='E' THEN 'SURRENDERED'
WHEN CVG_CSTAT_CD='R'  THEN 'REJECTED'
WHEN CVG_CSTAT_CD='B'  THEN 'LAPSED'
WHEN CVG_CSTAT_CD='A' THEN 'CFI'
WHEN CVG_CSTAT_CD='1' AND LEFT(CVG_PREV_CSTAT_CD,1)<>'P' THEN 'PREMIUM PAYING'
WHEN CVG_CSTAT_CD='2' THEN 'WAIVER' ELSE '' END MOVE_TYPE,CVG.CVG_MAT_XPRY_DUR POL_PREM_PAY_DUR,CASE WHEN LEFT(CVG.PLAN_ID,1)='K' THEN CVG_FACE_AMT/2 
WHEN CVG.PLAN_ID='DRD001' THEN 0 ELSE CVG_FACE_AMT END TPD_BENEFIT,  CVG_EMR_UW_RT,
CVG_EMR_UW1_RT,
CVG_EMR_UW2_RT,
CVG_EMR_UW3_RT,
CVG_EMR_PER_MIL_LD,
CVG_ADB_MIL_LD,
CVG_TPD_MIL_LD,
CVG_ATPD_MIL_LD,
P.POL_BILL_MODE_CD,P.POL_CSTAT_CD
INTO #TMP
FROM #C CVG INNER JOIN DLKHDIM..DIM_POLICY P ON CVG.POL_ID=P.POL_ID AND CVG.IS_CURRENT=1 AND P.IS_CURRENT=1
INNER JOIN SGTB_COVERAGE_CLI CVGC ON CVGC.POL_ID=CVG.POL_ID AND CVG.CVG_NUM=CVGC.CVG_NUM
INNER JOIN DLKHDIM..DIM_CLIENT C ON C.CLI_ID=CVGC.INSRD_CLI_ID AND C.IS_CURRENT=1
INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
LEFT JOIN (SELECT CVG.POL_ID,CLI_SEX_CD,CLI_BTH_DT FROM SGTM_COVERAGE CVG
INNER JOIN SGTB_COVERAGE_CLI CVGC ON CVGC.POL_ID=CVG.POL_ID AND CVG.CVG_NUM=CVGC.CVG_NUM
INNER JOIN DLKHDIM..DIM_CLIENT C ON C.CLI_ID=CVGC.INSRD_CLI_ID AND C.IS_CURRENT=1  WHERE LEFT(PLAN_ID,2)='DW') PO ON P.POL_ID=PO.POL_ID
LEFT JOIN (SELECT PC.POL_ID,CLI_SEX_CD,CLI_BTH_DT FROM DLKHDIM..DIM_POLICY_CLIENT PC INNER JOIN DLKHDIM..DIM_CLIENT C ON PC.CLI_ID=C.CLI_ID  AND C.IS_CURRENT=1 AND PC.IS_CURRENT=1) POO ON P.POL_ID=POO.POL_ID
WHERE P.POL_PD_TO_DT_NUM<>'0000-00-00'
 

UPDATE T SET MOVE_TYPE='REISSUED' FROM #TMP T INNER JOIN 
(SELECT DISTINCT C.POL_ID FROM DLKHDIM..DIM_POLICY C
INNER JOIN (SELECT POL_ID FROM DLKHDIM..DIM_POLICY WHERE  POL_CSTAT_CD='1' GROUP BY POL_ID HAVING COUNT(POL_ID)>1) N ON C.POL_ID=N.POL_ID 
WHERE  POL_CSTAT_CD='1' GROUP BY C.POL_ID,POL_CSTAT_CD,POL_STAT_CHNG_DT HAVING COUNT(POL_STAT_CHNG_DT)=1) N  ON T.POL_ID=N.POL_ID
 WHERE MOVE_TYPE='ISSUED'

 insert INTO DLKHFACT..FACT_ACTURAIL
 SELECT * FROM #TMP

 end
