-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 22-SEP-2016
-- Description:	FACT FA DEPRECIATIONS DETAILS
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_FACT_DD_FA_DEPRECIATION]
	@BRANCH_DATE AS DATE,@IS_RE_PROC BIT=0
 
AS
BEGIN
		-- FIXED ASSET DEP. DETAIL
		INSERT INTO BBCDW..FACT_FA_DEP_DETAIL 
		SELECT 
				*,@BRANCH_DATE ETL
		FROM BBCFCC..FCCBBCPRD.FATB_DEPRECIATION_DETAIL S 
		WHERE NOT EXISTS(
							SELECT ASSET_REF_NO 
							FROM  BBCDW..FACT_FA_DEP_DETAIL S1 
							WHERE S.ASSET_REF_NO=S1.ASSET_REF_NO AND S.DEPRECIATION_DATE=S1.DEPRECIATION_DATE
						)

		-- FIXED ASSET REGISTERED REPORT FACT
		INSERT INTO BBCDW..FACT_FA_DEPRECIATION 
		SELECT 
			CONVERT(VARCHAR,X.DEPRECIATION_DATE,112) DATE_KEY,
			C.FA_CONTRACT_KEY,
			BR.BRANCH_KEY,
			FL.LOCATION_KEY,
			FC.FA_CATEGORY_KEY,
			PR.PRODUCT_KEY,
			FS.FA_STATUS_KEY,
			YEAR(X.DEPRECIATION_DATE),
			MONTH(X.DEPRECIATION_DATE),
			C.USEFUL_LIFE,
			C.ASSET_CCY,
			C.ASSET_COST,
			X.PREV_YEAR_ACCM,
			X.PREV_MONTH_DEP,
			X.CURR_MONTH_DEP,
			X.CURR_YEAR_ACCM,
			X.TOTAL_ACCM,
			C.ASSET_COST-X.TOTAL_ACCM AS NBV,
			@BRANCH_DATE ETL_DT
		FROM BBCDW..DIM_FA_CONTRACT C 
		INNER JOIN BBCDW..DIM_BBC_BRANCH BR ON BR.BRANCH_CODE=C.BRANCH
		INNER JOIN BBCDW..DIM_FA_LOCATION FL ON C.LOCATION=FL.LOCATION
		INNER JOIN BBCDW..DIM_FA_CATEGORY FC ON C.CATEGORY=FC.CATEGORY AND FC.IS_CURRENT=1
		INNER JOIN BBCDW..DIM_CS_PRODUCT PR ON C.PRODUCT_CODE=PR.PRODUCT_CODE AND PR.IS_CURRENT=1
		INNER JOIN BBCDW..DIM_FA_STATUS FS ON C.CONTRACT_STATUS=FS.CONTRACT_STATUS
		LEFT JOIN 
		(
			SELECT
				V.ASSET_REF_NO,V.DEPRECIATION_DATE,
				SUM(CASE WHEN M.DEP_YEAR<YEAR(V.DEPRECIATION_DATE) THEN ISNULL(M.DEP_AMOUNT,0) ELSE 0 END) PREV_YEAR_ACCM,
				SUM(CASE WHEN M.DEP_YEAR=YEAR(V.DEPRECIATION_DATE) AND M.DEP_MONTH<MONTH(V.DEPRECIATION_DATE) THEN ISNULL(M.DEP_AMOUNT,0) ELSE 0 END) PREV_MONTH_DEP,
				SUM(CASE WHEN M.DEP_YEAR=YEAR(V.DEPRECIATION_DATE) AND M.DEP_MONTH=MONTH(V.DEPRECIATION_DATE) THEN ISNULL(M.DEP_AMOUNT,0) ELSE 0 END) CURR_MONTH_DEP,
				SUM(CASE WHEN M.DEP_YEAR=YEAR(V.DEPRECIATION_DATE) THEN ISNULL(M.DEP_AMOUNT,0) ELSE 0 END) CURR_YEAR_ACCM,
				SUM(ISNULL(M.DEP_AMOUNT,0)) TOTAL_ACCM 
			FROM BBCDW..FACT_FA_DEP_DETAIL V 
			INNER JOIN V_FA_DEP_MONTHLY M ON V.ASSET_REF_NO=M.ASSET_REF_NO
			GROUP BY V.ASSET_REF_NO,V.DEPRECIATION_DATE
		) X ON X.ASSET_REF_NO=C.ASSET_REF_NO
		WHERE C.IS_CURRENT=1 AND X.CURR_MONTH_DEP>0
		AND NOT EXISTS (
				SELECT FA_CONTRACT_KEY FROM BBCDW..FACT_FA_DEPRECIATION DEP 
				WHERE DEP.CONTRACT_KEY=C.FA_CONTRACT_KEY 
				AND DEP.DATE_KEY=CONVERT(VARCHAR,X.DEPRECIATION_DATE,112)
		)
		ORDER BY X.DEPRECIATION_DATE,X.ASSET_REF_NO
END
