CREATE PROC [dbo].[SP_ETL_FACT_POL_ISSUSED] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN

--DECLARE @BRANCH_DATE	DATE = '2024-05-25'
--			,@IS_RE_PROC BIT = 1

IF @IS_RE_PROC=1
DELETE FROM  DLKHFACT..FACT_POL_ISSUSED WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);

IF OBJECT_ID('tempdb..#APE') IS NOT NULL
DROP TABLE #APE

SELECT POL_ID,SUM(CASE WHEN CVG_CSTAT_CD IN ('1','2') THEN CVG_BASIC_PREM_AMT+CVG_FE_PREM_AMT+CVG_ME_PREM_AMT ELSE 0 END) ANN_PREMIUM12,
SUM(CASE WHEN CVG_CSTAT_CD NOT IN ('1','2') THEN CVG_BASIC_PREM_AMT+CVG_FE_PREM_AMT+CVG_ME_PREM_AMT ELSE 0 END) ANN_PREMIUM_OTHER INTO #APE FROM DLKHDIM..DIM_COVERAGE
WHERE IS_CURRENT=1
GROUP BY POL_ID

INSERT INTO DLKHFACT..FACT_POL_ISSUSED
SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY,AG_KEY,P.POL_KEY,COV_KEY,P.POL_ID,CL.CLI_ID,P.POL_APP_FORM_ID,CL.ENTR_SUR_NM,CL.ENTR_GIV_NM,CL.CLI_CNTCT_ID_TXT CLI_PHONE,PA.ETBL_DESC_TXT PLAN_DESC,CVG_SUM_INS_AMT SUM_ASS,
CASE WHEN POL_CSTAT_CD IN ('1','2') THEN APE.ANN_PREMIUM12 ELSE APE.ANN_PREMIUM_OTHER END APE,C.CVG_MPREM_AMT,
CASE WHEN POL_BILL_MODE_CD=3 THEN
'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Month' WHEN POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE POL_BILL_MODE_CD END PRE_MODE,P.POL_APP_RECV_DT POL_ISS_DT,P.POL_CSTAT_CD,PARA.DM_AV_DESC_TXT POL_STAT_DESC,
CL.CLI_ADDR_LN_1_TXT,CL.CLI_ADDR_LN_2_TXT,CL.CLI_ADDR_LN_3_TXT,CL.CLI_CITY_NM_TXT,
W.AGT_ID AGENT_CODE,V.ENTR_SUR_NM AGENT_SURNAME,V.ENTR_GIV_NM AGENT_NAME,POL_ISS_EFF_DT POL_COM_DT,POL_INFC_DT POL_INF_DT
,CASE WHEN V.CHANNEL = 'BA' THEN 'BANCA' ELSE 'AGENCY' END CHANNEL
,CVG_ME_FCT,C.CVG_MPREM_AMT-CVG_ME_PREM_AMT PRE_BEFORE,C.CVG_MPREM_AMT PRE_AFTER
 FROM DLKHDIM..DIM_POLICY P
INNER JOIN DLKHDIM..DIM_COVERAGE C ON C.POL_ID=P.POL_ID AND C.IS_CURRENT=1 AND P.IS_CURRENT=1
INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID=P.POL_ID
INNER JOIN DLKHDIM..DIM_POLICY_CLIENT PC ON PC.POL_ID=P.POL_ID AND PC.IS_CURRENT=1
INNER JOIN V_CLI_INFO CL ON CL.CLI_ID=PC.CLI_ID
INNER JOIN #APE APE ON APE.POL_ID=P.POL_ID
INNER JOIN V_AGENT V ON V.AGT_ID=W.AGT_ID --and V.AGT_CLI_REL_TYP_CD='M'
LEFT JOIN SGTB_EDITTABLE PA ON C.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E'AND PARA.CO_ID='CP'
WHERE P.POL_CSTAT_CD='1'
END
