CREATE PROC [dbo].[SP_ETL_FACT_DEP_OUTSIDE_CAM] @DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN 
	IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCNBCMART..FACT_TWICE_WEEK_DEP_OUTSIDE_CAM WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112);
	END
 IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
   IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
  DROP TABLE #TMP1
     IF OBJECT_ID('tempdb..#TMP2') IS NOT NULL
  DROP TABLE #TMP2
     IF OBJECT_ID('tempdb..#TMP3') IS NOT NULL
  DROP TABLE #TMP3
SELECT DATE_KEY,BRN.BRANCH_CODE,AC.ACCOUNT_KEY,BAL.CUSTOMER_KEY,
  BAL.LCY_CUR_BAL*(-1) LCY_CUR_BAL  INTO #TMP
FROM BBCDW..FACT_DAILY_AC_BAL BAL 
 INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY AND AC.IS_CURRENT=1
 INNER JOIN BBCDW..DIM_CUSTOMER CUS ON AC.CUST_NO=CUS.CUSTOMER_NO AND CUS.IS_CURRENT=1
 INNER JOIN BBCDW..DIM_COUNTRY CT ON CUS.COUNTRY=CT.COUNTRY_CODE
 INNER JOIN BBCDW..DIM_BBC_BRANCH BRN ON BRN.BRANCH_KEY=BAL.BRANCH_KEY
WHERE CUSTOMER_CATEGORY = 'NBK' AND ACCOUNT_CLASS='NOSTRO' AND Convert(DATE, LEFT(DATE_KEY, 8))=@DATE 
ORDER BY 1

SELECT CUS.CUSTOMER_KEY,CUS.CUSTOMER_NO,CUSTOMER_CATEGORY,TMP.DATE_KEY,BRANCH_CODE,ACCOUNT_KEY,COUNTRY,LCY_CUR_BAL INTO #TMP1 FROM BBCDW..DIM_CUSTOMER CUS LEFT JOIN #TMP TMP ON CUS.CUSTOMER_KEY=TMP.CUSTOMER_KEY AND CUS.CUSTOMER_CATEGORY='NBK' AND IS_CURRENT=1

SELECT CUSTOMER_KEY,CUSTOMER_NO,DATE_KEY,ISNULL(BRANCH_CODE,MM.BRANCH) BRANCH_CODE,ACCOUNT_KEY,COUNTRY,
  CASE WHEN DATEDIFF(DAY,@DATE,MM.MATURITY_DATE)<=30 THEN 101
  WHEN DATEDIFF(DAY,@DATE,MM.MATURITY_DATE)<=90 THEN 102 
  WHEN DATEDIFF(DAY,@DATE,MM.MATURITY_DATE)<=180 THEN 103
  WHEN DATEDIFF(DAY,@DATE,MM.MATURITY_DATE)<=360 THEN 104
  WHEN DATEDIFF(DAY,@DATE,MM.MATURITY_DATE)>360 THEN 105 END LOOKUP_KEY,
  LCY_CUR_BAL,LCY_AMOUNT INTO #TMP2
FROM #TMP1 LEFT JOIN BBCDW..DIM_MM_CONTRACT MM ON #TMP1.CUSTOMER_NO=MM.COUNTERPARTY AND MM.IS_CURRENT=1 AND MM.PRODUCT_TYPE='L' AND MM.CONTRACT_STATUS='A' AND DATEDIFF(DAY,@DATE,MM.MATURITY_DATE)>1
WHERE CUSTOMER_CATEGORY='NBK'

UPDATE #TMP2 SET DATE_KEY=(SELECT TOP 1 DATE_KEY FROM #TMP2 WHERE DATE_KEY IS NOT NULL) WHERE DATE_KEY IS NULL
SELECT * INTO #TMP3 FROM #TMP2 WHERE (LCY_CUR_BAL IS NOT NULL OR LCY_AMOUNT IS NOT NULL) AND (LCY_CUR_BAL <>0 OR LCY_AMOUNT IS NOT NULL)
INSERT INTO BBCNBCMART..FACT_TWICE_WEEK_DEP_OUTSIDE_CAM
select DATE_KEY,BRANCH_CODE,Convert(DATE, LEFT(DATE_KEY, 8)),ACCOUNT_KEY,CUSTOMER_KEY,COUNTRY,ISNULL(LOOKUP_KEY,0),ISNULL(LCY_CUR_BAL,0),ISNULL(LCY_AMOUNT,0),GETDATE() from #TMP3

END
