 
 
CREATE PROC [dbo].[SP_ETL_FACT_ATR] @BRANCH_DATE DATE,@IS_RE_PROC BIT=0

AS

BEGIN
 
	--DECLARE @BRANCH_DATE	DATE = '2021-11-29'

	--	,@IS_RE_PROC		BIT	= 1
 
	IF @IS_RE_PROC = 1 DELETE FROM  DLKHFACT..FACT_ATR WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112);
 
	DROP TABLE IF EXISTS #TMP
 
	SELECT DISTINCT 

		CVG.COV_KEY

		,POL_KEY

		,C.CLI_KEY

		,CVG.POL_ID

		,CVG.CVG_NUM

		,CVG.PLAN_ID

		,CVG.CVG_APP_CMPLT_DT

		,CVG.CVG_ISS_EFF_DT

		,CVG.CVG_STAT_PRCES_DT

		,CVG.CVG_CSTAT_CD

		,CVG.CVG_PREV_CSTAT_CD

		,CASE WHEN LEFT(CVG.PLAN_ID,1)='K' THEN 'AE' 

			WHEN LEFT(CVG.PLAN_ID,1)='C' THEN 'LS' 

			WHEN LEFT(CVG.PLAN_ID,2)='DW' THEN 'PWOP' 

			ELSE 'TRIDER' 

		END CLASS

		,CVG.CVG_FACE_AMT

		,CASE WHEN POL_BILL_MODE_CD=3 THEN 'Q' 

			WHEN POL_BILL_MODE_CD=6 THEN 'H' 

			WHEN POL_BILL_MODE_CD=1 THEN 'M' 

			WHEN POL_BILL_MODE_CD=12 THEN 'Y'

			ELSE POL_BILL_MODE_CD 

		END PRE_MODE

		,CVGC.INSRD_CLI_ID

		,C.CLI_SEX_CD

		,C.CLI_BTH_DT,CVG.CVG_MAT_XPRY_DT

		,CASE WHEN P.POL_BILL_MODE_CD='01' THEN CVG.CVG_MPREM_AMT*12 

			WHEN P.POL_BILL_MODE_CD='03' THEN CVG.CVG_MPREM_AMT*4 

			WHEN P.POL_BILL_MODE_CD='06' THEN CVG.CVG_MPREM_AMT*2 ELSE CVG.CVG_MPREM_AMT 

			END TARGET_PREM,CVG.CVG_MPREM_AMT

		,POL_PD_TO_DT_NUM

		,CVG.CVG_RT_AGE AGE

		,W.AGT_ID,CVG.CVG_ME_FCT

		,(CVG.CVG_ME_FCT-1)* 100 AS MEDICAL_LOADING_PERCENT

		,CVG.CVG_BASIC_PREM_AMT

		,CVG.CVG_MAT_XPRY_DUR POL_PREM_PAY_DUR

		,CASE WHEN LEFT(CVG.PLAN_ID,1)='K' THEN CVG.CVG_FACE_AMT/2 

			WHEN CVG.PLAN_ID='DRD001' THEN 0 ELSE CVG.CVG_FACE_AMT 

		END TPD_BENEFIT

		,CVG.CVG_EMR_UW_RT

		,CVG.CVG_EMR_UW1_RT

		,CVG.CVG_EMR_UW2_RT

		,CVG.CVG_EMR_UW3_RT

		,CVG.CVG_EMR_PER_MIL_LD

		,CVG.CVG_ADB_MIL_LD

		,CVG.CVG_TPD_MIL_LD

		,CVG.CVG_ATPD_MIL_LD

		,P.POL_BILL_MODE_CD

		,P.POL_CSTAT_CD

		,C.CLI_OCCP_CLAS_CD

		,PC.CLI_ID PO

		,CPO.CLI_SEX_CD POSEX

		,CPO.CLI_BTH_DT PODOB

		,P.POL_GRS_APREM_AMT

		,CVG.CVG_EMR_UW4_RT

		,CVG.CVG_HLTH_MIL_LD

		,CVG.CVG_EMR_UW5_RT

		,CVG.CVG_FAMI_MIL_LD

		,PREV_CVG_FACE_AMT = PREFACE.PREV_CVG_FACE_AMT

		,PREV_POL_BILL_MODE_CD = PREBL.PREV_POL_BILL_MODE_CD

		,PREV_PO = PREPO.PREV_PO

		,PRECLI.PREV_CLI_OCCP_CLAS_CD	

		,C.OCCP_ID

		,PPREM.PREV_CVG_MPREM_AMT

		,P.POL_PREV_CSTAT_CD

		,P.POL_STAT_CHNG_DT

		,P.POL_INFC_DT

	INTO #TMP

	FROM DLKHDIM..DIM_COVERAGE CVG 

	INNER JOIN DLKHDIM..DIM_POLICY P ON CVG.POL_ID = P.POL_ID AND CVG.IS_CURRENT = 1 AND P.IS_CURRENT = 1

	INNER JOIN SGTB_COVERAGE_CLI CVGC ON CVGC.POL_ID = CVG.POL_ID AND CVG.CVG_NUM = CVGC.CVG_NUM

	INNER JOIN DLKHDIM..DIM_CLIENT C ON C.CLI_ID = CVGC.INSRD_CLI_ID AND C.IS_CURRENT = 1

	INNER JOIN SGTB_POLICY_WRITING W ON W.POL_ID = P.POL_ID

	LEFT JOIN SGTB_POLICY_CLIENT PC ON PC.POL_ID = P.POL_ID AND PC.POL_CLI_REL_TYP_CD = 'O'

	LEFT JOIN DLKHDIM..DIM_CLIENT CPO ON PC.CLI_ID=CPO.CLI_ID AND CPO.IS_CURRENT = 1

	-- PREVIOUS CVG_FACE_AMOUNT

	LEFT JOIN 

		(

			SELECT PREV_UPDT_TS,POL_ID,CVG_NUM,PREV_CVG_FACE_AMT = CVG_FACE_AMT, LAST_UPDATE = ROW_NUMBER() OVER(PARTITION BY POL_ID ORDER BY PREV_UPDT_TS DESC ) 

			FROM DLKHDIM..DIM_COVERAGE WHERE IS_CURRENT != 1

		) PREFACE

		ON CVG.POL_ID = PREFACE.POL_ID AND CVG.CVG_NUM = PREFACE.CVG_NUM AND CVG.CVG_FACE_AMT != PREFACE.PREV_CVG_FACE_AMT AND PREFACE.LAST_UPDATE = 1

	-- PREVIOUS BILLING MODE 

	LEFT JOIN (

			SELECT PREV_UPDT_TS,POL_ID,PREV_POL_BILL_MODE_CD = POL_BILL_MODE_CD, LAST_UPDATE = ROW_NUMBER() OVER(PARTITION BY POL_ID ORDER BY PREV_UPDT_TS DESC ) 

			FROM DLKHDIM..DIM_POLICY WHERE IS_CURRENT != 1

		) PREBL ON P.POL_ID = PREBL.POL_ID AND P.POL_BILL_MODE_CD != PREBL.PREV_POL_BILL_MODE_CD AND PREBL.LAST_UPDATE = 1

	-- PREVIOUS PO

	LEFT JOIN 

		(

			SELECT PREV_UPDT_TS,POL_ID,PREV_PO = CLI_ID, LAST_UPDATE = ROW_NUMBER() OVER(PARTITION BY POL_ID ORDER BY PREV_UPDT_TS DESC ) 

			FROM DLKHDIM..DIM_POLICY_CLIENT WHERE IS_CURRENT != 1

		) PREPO

	ON PC.POL_ID = PREPO.POL_ID AND PC.CLI_ID != PREPO.PREV_PO AND PREPO.LAST_UPDATE = 1

	-- PREVIOUS OCCUPATION CLASS

	LEFT JOIN 

		(

			SELECT PREV_UPDT_TS,CLI_ID,PREV_CLI_OCCP_CLAS_CD = CLI_OCCP_CLAS_CD, LAST_UPDATE = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC ) 

			FROM DLKHDIM..DIM_CLIENT WHERE IS_CURRENT != 1

		) PRECLI

		ON C.CLI_ID = PRECLI.CLI_ID AND C.CLI_OCCP_CLAS_CD != PRECLI.PREV_CLI_OCCP_CLAS_CD AND PRECLI.LAST_UPDATE = 1

	--	PREVIOUS COVERAGE PREMIUM AMOUNT

	LEFT JOIN 

		(

			SELECT PREV_UPDT_TS,POL_ID,CVG_NUM,PREV_CVG_MPREM_AMT = CVG_MPREM_AMT, LAST_UPDATE = ROW_NUMBER() OVER(PARTITION BY POL_ID ORDER BY PREV_UPDT_TS DESC ) 

			FROM DLKHDIM..DIM_COVERAGE WHERE IS_CURRENT != 1 

		) PPREM

		ON CVG.POL_ID = PPREM.POL_ID AND CVG.CVG_NUM = PPREM.CVG_NUM AND CVG.CVG_MPREM_AMT != PPREM.PREV_CVG_MPREM_AMT AND PPREM.LAST_UPDATE = 1

	WHERE P.POL_PD_TO_DT_NUM <> '0000-00-00' 

		AND LEFT(P.POL_CSTAT_CD,1) <> 'P' 

		AND LEFT(CVG.CVG_CSTAT_CD,1) <> 'P'

	 INSERT INTO DLKHFACT..FACT_ATR

		([DATE_KEY]

        ,[COV_KEY]

        ,[POL_KEY]

        ,[CLI_KEY]

        ,[POL_ID]

        ,[CVG_NUM]

        ,[PLAN_ID]

        ,[CVG_APP_CMPLT_DT]

        ,[CVG_ISS_EFF_DT]

        ,[CVG_STAT_PRCES_DT]

        ,[CVG_CSTAT_CD]

        ,[CVG_PREV_CSTAT_CD]

        ,[CLASS]

        ,[CVG_FACE_AMT]

        ,[PRE_MODE]

        ,[INSRD_CLI_ID]

        ,[CLI_SEX_CD]

        ,[CLI_BTH_DT]

        ,[CVG_MAT_XPRY_DT]

        ,[TARGET_PREM]

        ,[CVG_MPREM_AMT]

        ,[POL_PD_TO_DT_NUM]

        ,[AGE]

        ,[AGT_ID]

        ,[CVG_ME_FCT]

        ,[MEDICAL_LOADING_PERCENT]

        ,[CVG_BASIC_PREM_AMT]

        ,[POL_PREM_PAY_DUR]

        ,[TPD_BENEFIT]

        ,[CVG_EMR_UW_RT]

        ,[CVG_EMR_UW1_RT]

        ,[CVG_EMR_UW2_RT]

        ,[CVG_EMR_UW3_RT]

        ,[CVG_EMR_PER_MIL_LD]

        ,[CVG_ADB_MIL_LD]

        ,[CVG_TPD_MIL_LD]

        ,[CVG_ATPD_MIL_LD]

        ,[POL_BILL_MODE_CD]

        ,[POL_CSTAT_CD]

        ,[CLI_OCCP_CLAS_CD]

        ,[POL_GRS_APREM_AMT]

        ,[PO]

        ,[POSEX]

        ,[PODOB]

		,[CVG_EMR_UW4_RT]

		,[CVG_HLTH_MIL_LD]

		,[CVG_EMR_UW5_RT]

		,[CVG_FAMI_MIL_LD]

		,[PREV_CVG_FACE_AMT]

		,[PREV_POL_BILL_MODE_CD]

		,[PREV_PO]

		,[PREV_CLI_OCCP_CLAS_CD]

		,[INSRD_OCCP_ID]

		,[PREV_CVG_MPREM_AMT]

		,[POL_PREV_CSTAT_CD]

		,[POL_STAT_CHNG_DT]

		,[POL_INFC_DT]

		)

	 SELECT CONVERT(VARCHAR,@BRANCH_DATE,112) DATE_KEY

		,T.COV_KEY

		,T.POL_KEY

		,T.CLI_KEY

		,T.POL_ID

		,T.CVG_NUM

		,T.PLAN_ID

		,T.CVG_APP_CMPLT_DT

		,T.CVG_ISS_EFF_DT

		,T.CVG_STAT_PRCES_DT

		,T.CVG_CSTAT_CD

		,T.CVG_PREV_CSTAT_CD

		,T.CLASS

		,T.CVG_FACE_AMT

		,T.PRE_MODE

		,T.INSRD_CLI_ID

		,T.CLI_SEX_CD

		,T.CLI_BTH_DT

		,T.CVG_MAT_XPRY_DT

		,T.TARGET_PREM

		,T.CVG_MPREM_AMT

		,T.POL_PD_TO_DT_NUM

		,T.AGE

		,T.AGT_ID

		,T.CVG_ME_FCT

		,T.MEDICAL_LOADING_PERCENT

		,T.CVG_BASIC_PREM_AMT

		,T.POL_PREM_PAY_DUR

		,T.TPD_BENEFIT

		,T.CVG_EMR_UW_RT

		,T.CVG_EMR_UW1_RT

		,T.CVG_EMR_UW2_RT

		,T.CVG_EMR_UW3_RT

		,T.CVG_EMR_PER_MIL_LD

		,T.CVG_ADB_MIL_LD

		,T.CVG_TPD_MIL_LD

		,T.CVG_ATPD_MIL_LD

		,T.POL_BILL_MODE_CD

		,T.POL_CSTAT_CD

		,T.CLI_OCCP_CLAS_CD

		,POL_GRS_APREM_AMT

		,T.PO,T.POSEX

		,T.PODOB 

		,T.CVG_EMR_UW4_RT

		,T.CVG_HLTH_MIL_LD

		,T.CVG_EMR_UW5_RT

		,T.CVG_FAMI_MIL_LD

		,T.PREV_CVG_FACE_AMT

		,T.PREV_POL_BILL_MODE_CD

		,T.PREV_PO

		,T.PREV_CLI_OCCP_CLAS_CD

		,T.OCCP_ID

		,T.PREV_CVG_MPREM_AMT

		,T.POL_PREV_CSTAT_CD

		,T.POL_STAT_CHNG_DT

		,T.POL_INFC_DT

	  FROM #TMP T
 
END
