-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 04-OCT-2016
-- Description:	ETL BATCH PROCESS FOR FACT TABLES
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_PROC_BATCH_FACTS]
	@BRANCH_DATE	DATE
	,@DB_NAME		VARCHAR(20)
	,@DBDW_NAME		VARCHAR(20)
	,@SERVER_NAME	VARCHAR(20)
	,@IS_ERROR		BIT OUTPUT
	,@EXEC_TYPE		CHAR(2)
	,@IS_RE_PROC	BIT = 0
AS
BEGIN
	
	SET NOCOUNT ON;

	DECLARE @TAB TABLE(ID INT IDENTITY,BATCH_CODE VARCHAR(15),BATCH_NAME VARCHAR(100),BATCH_SCRIPT NVARCHAR(MAX))
	DECLARE @COUNT INT,@MAX INT,@BATCH_CODE VARCHAR(15),@BATCH_NAME VARCHAR(100),@BATCH_SCRIPT NVARCHAR(MAX),
		@START_TIME DATETIME,@END_TIME DATETIME
	DECLARE @ERROR_CODE AS VARCHAR(50),@ERROR_MSG AS NVARCHAR(MAX)

	SET @COUNT=1

	INSERT INTO @TAB
	SELECT 
			BATCH_CODE,BATCH_NAME,BATCH_SCRIPT
	FROM ETLM_BATCH B 
	WHERE B.BATCH_TYPE='F' -- BATCH FOR FACT TABLES
	AND B.IS_ENABLED=1 
	AND B.EFFECTIVE_DATE<=@BRANCH_DATE
	AND PARENT_BATCH=3 -- FACTS MAIN BATCH
	AND B.EXEC_TYPE=@EXEC_TYPE -- DAILY BATCH RUNNING
	ORDER BY B.BATCH_NUM

	--CHECK FOR MONTHLY BATCH
	IF @BRANCH_DATE = EOMONTH(@BRANCH_DATE,0)
	INSERT INTO @TAB
	SELECT 
			BATCH_CODE,BATCH_NAME,BATCH_SCRIPT
	FROM ETLM_BATCH B 
	WHERE B.BATCH_TYPE='F' -- BATCH FOR FACT TABLES
	AND B.IS_ENABLED=1 
	AND B.EFFECTIVE_DATE<=@BRANCH_DATE
	AND PARENT_BATCH=3 -- FACTS MAIN BATCH
	AND B.EXEC_TYPE='MM' -- MONTHLY BATCH RUNNING
	ORDER BY B.BATCH_NUM

	SELECT @MAX=@@IDENTITY;
	WHILE @COUNT<=@MAX BEGIN
		
		SET @IS_ERROR=0
		SELECT @BATCH_CODE=BATCH_CODE,@BATCH_NAME=BATCH_NAME,
				@BATCH_SCRIPT=BATCH_SCRIPT
		FROM @TAB T WHERE ID=@COUNT

		IF ISNULL(@BATCH_SCRIPT,'')<>'' 
		BEGIN
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@BRANCH_DATE',@BRANCH_DATE)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@BATCH_CODE',@BATCH_CODE)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@DB_NAME',@DB_NAME)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@DBDW_NAME',@DBDW_NAME)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@SERVER_NAME',@SERVER_NAME)
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@DBMART_NAME','')
			SET @BATCH_SCRIPT=REPLACE(@BATCH_SCRIPT,'@IS_RE_PROC',@IS_RE_PROC)

			BEGIN TRAN;
			BEGIN TRY
				SET @START_TIME=GETDATE();
				-- PRINT(@BATCH_SCRIPT);
				-- CALL SP BY BATCH PROCESS
				EXEC sp_executesql @BATCH_SCRIPT;

				SET @END_TIME=GETDATE()
				EXEC SP_ETL_PROC_WRITE_LOG '',@BRANCH_DATE,@BATCH_CODE,'C','',@START_TIME,@END_TIME,'','',@BATCH_SCRIPT

			END TRY
			BEGIN CATCH
				SET @IS_ERROR=1;
				PRINT (ERROR_MESSAGE())
				RETURN
			END CATCH;
			COMMIT TRAN;
		END 
	
	SET @COUNT=@COUNT+1;
	
	END;
			 

END
