-- =============================================
-- Author:		HING TIPI
-- Create date: 21-DEC-2018
-- Description:	ETL Process write log
-- =============================================
CREATE PROCEDURE [dbo].[SP_ETL_PROC_WRITE_LOG]
	@BRANCH_CODE AS VARCHAR(3),
	@BRANCH_DATE AS DATE,
	@BATCH_CODE AS VARCHAR(15),
	@PROC_TYPE AS CHAR(1),
	@PROC_DESC AS NVARCHAR(MAX),
	@START_TIME AS DATETIME,
	@END_TIME AS DATETIME,
	@ERROR_CODE AS VARCHAR(50),
	@ERROR_MSG AS NVARCHAR(MAX),
	@STR_SQL AS NVARCHAR(MAX)
	 
AS
BEGIN
	DECLARE @TRAN_LOG varchar(20)

	BEGIN TRAN @TRAN_LOG
	BEGIN TRY
		INSERT INTO ETLB_BATCH_PROC_DETAIL
				(BRANCH_CODE,BRANCH_DATE,PARENT_BATCH,BATCH_NUM,BATCH_CODE,PROC_SEQ,PROC_TYPE,PROC_DESC,START_TIME,END_TIME,ERROR_CODE,ERROR_MSG,STR_SCRIPTS)
	
		SELECT 
				@BRANCH_CODE,@BRANCH_DATE,
				(SELECT PARENT_BATCH FROM ETLM_BATCH D WHERE D.BATCH_CODE=@BATCH_CODE) AS PARENT_CODE,
			
				(SELECT BATCH_NUM FROM ETLM_BATCH D WHERE D.BATCH_CODE=@BATCH_CODE) AS BATCH_NUM,
				@BATCH_CODE,
				ISNULL((SELECT MAX(PROC_SEQ) FROM ETLB_BATCH_PROC_DETAIL D 
					WHERE D.BRANCH_CODE=@BRANCH_CODE AND D.BRANCH_DATE=@BRANCH_DATE AND D.BATCH_CODE=@BATCH_CODE),0)+1 AS PROC_SEQ,
				@PROC_TYPE,@PROC_DESC, @START_TIME,@END_TIME,@ERROR_CODE,@ERROR_MSG,@STR_SQL;
		COMMIT TRAN @TRAN_LOG;
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN @TRAN_LOG
		PRINT('Fail to write log... '+ ERROR_MESSAGE());
	END CATCH;
END
