create PROC [dbo].[SP_ETL_FACT_ASSET] @DATE DATE,@IS_RE_PROC BIT=0
AS
BEGIN
IF @IS_RE_PROC=1
	BEGIN
		DELETE FROM  BBCNBCMART..[FACT_BS_ASSET] WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112);
END
 IF OBJECT_ID('tempdb..#ASSET') IS NOT NULL
  DROP TABLE #ASSET
 IF OBJECT_ID('tempdb..#MINUS_ASSET') IS NOT NULL
  DROP TABLE #MINUS_ASSET
 IF OBJECT_ID('tempdb..#PRO_ASSET') IS NOT NULL
  DROP TABLE #PRO_ASSET
 IF OBJECT_ID('tempdb..#PRO') IS NOT NULL
  DROP TABLE #PRO
 IF OBJECT_ID('tempdb..#MINUS') IS NOT NULL
  DROP TABLE #MINUS
   IF OBJECT_ID('tempdb..#ASSET1') IS NOT NULL
  DROP TABLE #ASSET1
 IF OBJECT_ID('tempdb..#MINUS1') IS NOT NULL
  DROP TABLE #MINUS1
   IF OBJECT_ID('tempdb..#PRO1') IS NOT NULL
  DROP TABLE #PRO1
 IF OBJECT_ID('tempdb..#RESULT') IS NOT NULL
  DROP TABLE #RESULT
 IF OBJECT_ID('tempdb..#RESULT_O') IS NOT NULL
  DROP TABLE #RESULT_O
 IF OBJECT_ID('tempdb..#RESULT_K') IS NOT NULL
  DROP TABLE #RESULT_K
 IF OBJECT_ID('tempdb..#PRO_O') IS NOT NULL
  DROP TABLE #PRO_O
 IF OBJECT_ID('tempdb..#PRO_K') IS NOT NULL
  DROP TABLE #PRO_K
----PROVISION/DEPRE---------
SELECT ROW_NUMBER() OVER(ORDER BY ITEM_KEY ASC) AS ID,ITEM_KEY,Description,Provison GL,PARENT,LEV,ODER INTO #PRO_ASSET FROM BBCNBCMART..DIM_BS_ASSET WHERE Provison<>''
-----MINUS------
SELECT ROW_NUMBER() OVER(ORDER BY ITEM_KEY ASC) AS ID,ITEM_KEY,Description,Minus GL,PARENT,LEV,ODER INTO #MINUS_ASSET  FROM BBCNBCMART..DIM_BS_ASSET WHERE Minus<>''

Declare @ID int, @GL varchar(100),@Des nvarchar(100),@max int,@min int=1
CREATE TABLE #ASSET (ID INT,GL VARCHAR(100),ITEM_KEY INT,DESCRIPTION VARCHAR(100))
CREATE TABLE #PRO (ID INT,GL VARCHAR(100),ITEM_KEY INT,DESCRIPTION VARCHAR(100))
CREATE TABLE #MINUS (ID INT,GL VARCHAR(100),ITEM_KEY INT,DESCRIPTION VARCHAR(100))
select @max=MAX(ITEM_KEY) from BBCNBCMART..DIM_BS_ASSET 
while @min<=@max

	BEGIN
		select @ID=ITEM_KEY,@GL=GL,@Des=Description from BBCNBCMART..DIM_BS_ASSET where ITEM_KEY=@min
		INSERT INTO #ASSET
		select * from BBCDW..FnSplit_With_Desc(@GL,',',@ID,@Des)
		SET @min=@min+1
	END
SET @ID=0
SET @GL=''
SET @Des=''
SET @max=0
SET @min=1
select @max=MAX(ID) from #MINUS_ASSET
while @min<=@max

	BEGIN
		select @ID=ITEM_KEY,@GL=GL,@Des=Description from #MINUS_ASSET where ID=@min
		INSERT INTO #MINUS
		select * from BBCDW..FnSplit_With_Desc(@GL,',',@ID,@Des)
		SET @min=@min+1
	END
SET @ID=0
SET @GL=''
SET @Des=''
SET @max=0
SET @min=1
select @max=MAX(ID) from #PRO_ASSET
while @min<=@max

	BEGIN
		select @ID=ITEM_KEY,@GL=GL,@Des=Description from #PRO_ASSET where ID=@min
		INSERT INTO #PRO
		select * from BBCDW..FnSplit_With_Desc(@GL,',',@ID,@Des)
		SET @min=@min+1
	END
	SELECT DATE_KEY,ITEM_KEY,DESCRIPTION,SUM(CLO_LCY_BAL) CLO_LCY_BAL,CU.CCY_CODE INTO #ASSET1 FROM BBCDW..FACT_DAILY_GL_BAL BAL INNER JOIN BBCDW..DIM_GLMASTER GL ON BAL.GL_KEY=GL.GL_KEY AND IS_CURRENT=1
	INNER JOIN #ASSET COM ON COM.GL=GL.GL_CODE INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=BAL.CCY_KEY WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112) GROUP BY DATE_KEY,ITEM_KEY,DESCRIPTION,CCY_CODE
	SELECT DATE_KEY,ITEM_KEY,DESCRIPTION,SUM(CLO_LCY_BAL) CLO_LCY_BAL,CU.CCY_CODE INTO #PRO1 FROM BBCDW..FACT_DAILY_GL_BAL BAL INNER JOIN BBCDW..DIM_GLMASTER GL ON BAL.GL_KEY=GL.GL_KEY AND IS_CURRENT=1
	INNER JOIN #PRO COM ON COM.GL=GL.GL_CODE INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=BAL.CCY_KEY WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112) GROUP BY DATE_KEY,ITEM_KEY,DESCRIPTION,CCY_CODE

	SELECT DATE_KEY,ITEM_KEY,DESCRIPTION,SUM(CLO_LCY_BAL) CLO_LCY_BAL,CU.CCY_CODE INTO #MINUS1 FROM BBCDW..FACT_DAILY_GL_BAL BAL INNER JOIN BBCDW..DIM_GLMASTER GL ON BAL.GL_KEY=GL.GL_KEY AND IS_CURRENT=1
	INNER JOIN #MINUS COM ON COM.GL=GL.GL_CODE INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=BAL.CCY_KEY WHERE DATE_KEY=CONVERT(VARCHAR,@DATE,112) GROUP BY DATE_KEY,ITEM_KEY,DESCRIPTION,CCY_CODE

	SELECT COM.DATE_KEY,COM.ITEM_KEY,COM.DESCRIPTION,(COM.CLO_LCY_BAL - ISNULL(MIN.CLO_LCY_BAL,0)) CLO_LCY_BAL,COM.CCY_CODE INTO #RESULT FROM #ASSET1 COM LEFT JOIN #MINUS1 MIN ON COM.ITEM_KEY=MIN.ITEM_KEY and COM.CCY_CODE=MIN.CCY_CODE
	select * INTO #RESULT_O from #RESULT  WHERE CCY_CODE<>'KHR'
	select * INTO #RESULT_K from #RESULT WHERE CCY_CODE='KHR'
	select * INTO #PRO_O from #PRO1 WHERE CCY_CODE<>'KHR'
	select * INTO #PRO_K from #PRO1 WHERE CCY_CODE='KHR'
	
	INSERT INTO BBCNBCMART..[FACT_BS_ASSET]

	SELECT CONVERT(VARCHAR,@DATE,112),COM.ITEM_KEY,COM.Description,GL,PARENT,LEV,ISNULL(REK.CLO_LCY_BAL,0) CLO_LCY_BAL,ISNULL(RE.CLO_LCY_BAL,0) CLO_FCY_BAL,
	ISNULL(PROK.CLO_LCY_BAL,0) PRO_L,ISNULL(PRO.CLO_LCY_BAL,0) PRO_F,COM.oder FROM BBCNBCMART..DIM_BS_ASSET COM LEFT JOIN #RESULT_O RE ON COM.ITEM_KEY=RE.ITEM_KEY
	LEFT JOIN #RESULT_K REK ON COM.ITEM_KEY=REK.ITEM_KEY
	LEFT JOIN #PRO_K PROK ON COM.ITEM_KEY=PROK.ITEM_KEY
	LEFT JOIN #PRO_O PRO ON COM.ITEM_KEY=PRO.ITEM_KEY

	

	END
