-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 05-OCT-2016
-- Description:	GET CURRENCY EXCHANGE RATE BY DATE
-- =============================================
CREATE PROC [dbo].[SP_GET_EX_RATE_BY_PERIOD1]

AS
BEGIN
	DECLARE @SQL VARCHAR(4000)='',@OPENQUERY nvarchar(4000)='',@EX_RATE MONEY=0.0
	
	SET @EX_RATE=(SELECT MID_RATE FROM OPENQUERY(BBCFCC,'SELECT MID_RATE  FROM FCCBBCPRD.CYTM_RATES R WHERE R.CCY1=''USD'' AND R.CCY2=''THB'' AND R.BRANCH_CODE=000 AND R.RATE_TYPE=''NBC'' AND R.RATE_DATE=''2016-03-02'''))

	SELECT @EX_RATE
END
