-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 05-OCT-2016
-- Description:	GET CURRENCY EXCHANGE RATE BY DATE
-- =============================================
CREATE PROC [dbo].[SP_GET_EX_RATE_BY_PERIOD]
(
	@SERVER_NAME VARCHAR(20),@DB_NAME VARCHAR(20), @BRANCH_CODE VARCHAR(3),@PERIOD VARCHAR(15),@PERIOD_TYPE VARCHAR(1), --P: PERIOD (YYYYMM), D=DATE 
	@CCY1 VARCHAR(3),@CCY2 VARCHAR(3),@RATE_TYPE VARCHAR(15),@RATE_TYPE_VAL VARCHAR(1) -- M: MID RATE, S:SALE RATE, B: BUY RATE
)
AS
BEGIN
	DECLARE @SQL VARCHAR(4000)='',@OPENQUERY nvarchar(4000)='',@EX_RATE MONEY=0.0
	
	SELECT 
			TOP 1 @SQL=S.SQL_SCRIPT
	FROM ETLM_SQLSCRIPTS S WHERE S.SQL_CODE='001';

	IF @PERIOD_TYPE='P' -- BY PERIOD(YYYYMM)
	BEGIN
			  SET @SQL=REPLACE(@SQL,'@RATE_DATE_STR','TO_CHAR(R1.RATE_DATE,''''YYYYMM'''')')
	END
	ELSE
	BEGIN
			SET @SQL=REPLACE(@SQL,'@RATE_DATE_STR','R1.RATE_DATE')
	END

	IF @RATE_TYPE_VAL='M'
	BEGIN
			SET @OPENQUERY='SELECT @EX_RATE=MID_RATE FROM OPENQUERY([@SERVER_NAME],''';
	END
	ELSE IF @RATE_TYPE_VAL='S'
	BEGIN
		SET @OPENQUERY='SELECT @EX_RATE=SALE_RATE FROM OPENQUERY([@SERVER_NAME],''';
	END
	ELSE SET @OPENQUERY='SELECT @EX_RATE=BUY_RATE FROM OPENQUERY([@SERVER_NAME],''';

	SET @OPENQUERY=@OPENQUERY+@SQL +''')';
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@SERVER_NAME',@SERVER_NAME);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@DB_NAME',@DB_NAME);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@PERIOD',@PERIOD);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@CCY1',@CCY1);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@CCY2',@CCY2);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@BRANCH_CODE',@BRANCH_CODE);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@RATE_TYPE',@RATE_TYPE);

	--PRINT(@OPENQUERY)

	exec sp_executesql @OPENQUERY,N'@EX_RATE NUMERIC(12,8) OUT',@EX_RATE OUT;

	RETURN @EX_RATE

END
