

create FUNCTION [dbo].[CALCULATE_PO_AGE]
(
	@DOB DATETIME, @POL_EFF_DATE DATETIME 
)
RETURNS INT AS 
BEGIN
	DECLARE @tmpdate datetime, @years INT
	SELECT @tmpdate = @DOB
	SELECT @years = DATEDIFF(yy, @tmpdate, @POL_EFF_DATE) - CASE WHEN (MONTH(@DOB) > MONTH(@POL_EFF_DATE)) OR (MONTH(@DOB) = MONTH(@POL_EFF_DATE) AND DAY(@DOB) > DAY(@POL_EFF_DATE)) THEN 1 ELSE 0 END
	RETURN @years
END
