

CREATE FUNCTION [dbo].[CALCULATE_APE_POID] (@POID VARCHAR(20), @APPRECDT DATE)
RETURNS DECIMAL(10,2)
AS 
BEGIN
	DECLARE @APE DECIMAL (10,2);
	
	SELECT @APE = SUM(ISNULL(CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE 
		   POL.POL_MPREM_AMT END * 
		   (CASE WHEN CAST(POL.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(POL.POL_BILL_MODE_CD AS INT) END),0) )	-- APE/AFYP
	FROM [UAT7].[DB77IUA1].[KCAPXUT1].[TPOL] POL
	INNER JOIN 	[UAT7].[DB77IUA1].[KCAPXUT1].[TPOLC] POLC 
				ON POL.POL_ID = POLC.POL_ID AND POLC.POL_CLI_REL_TYP_CD = 'O'
	LEFT JOIN DLKHSTAGE.dbo.V_GET_PREMIUM_AMT_POL_LAPSE_LIVE POL0 ON POL.POL_ID = POL0.POL_ID
	WHERE POLC.CLI_ID = @POID AND POL.POL_APP_RECV_DT <= @APPRECDT 
GROUP BY POLC.CLI_ID;

	RETURN @APE;
END;
