
CREATE FUNCTION [dbo].[CONVERT_KH_MONTH]
(
	@MONNUM INT
) 
RETURNS NVARCHAR(25) AS
BEGIN
	DECLARE @RESULT NVARCHAR(25)
	SET @RESULT = 
	CASE 
		WHEN @MONNUM = 1 THEN N'មករា'
		WHEN @MONNUM = 2 THEN N'កុម្ភៈ'
		WHEN @MONNUM = 3 THEN N'មីនា'
		WHEN @MONNUM = 4 THEN N'មេសា'
		WHEN @MONNUM = 5 THEN N'ឧសភា'
		WHEN @MONNUM = 6 THEN N'មិថុនា'
		WHEN @MONNUM = 7 THEN N'កក្កដា'
		WHEN @MONNUM = 8 THEN N'សីហា'
		WHEN @MONNUM = 9 THEN N'កញ្ញា'
		WHEN @MONNUM = 10 THEN N'តុលា'
		WHEN @MONNUM = 11 THEN N'វិច្ឆិកា'
		WHEN @MONNUM = 12 THEN N'ធ្នូ'
		ELSE NULL
	END
	RETURN @RESULT
END
