CREATE Function [dbo].[FCOLLECTION](@ETL_DATE date) returns table
as 
return(
SELECT D.COLCT_EFF_DT,CL.PREV_UPDT_TS LPREV_UPDT_TS,CL.COLCT_DOC_DT,CL.COLCT_TOT_AMT,COLCT_ACCT_NUM,CL.COLCT_PAYR_NM,CL.COLCT_CLR_REJ_DT,CL.COLCT_STAT_CD,CL.COLCT_RCPT_NUM,PA.ETBL_DESC_TXT COLLEC_SRCE,CL.COLCT_REMARK,COLCT_REF_NUM,
D.PREV_UPDT_TS DPREV_UPDT_TS,D.POL_ID,D.COLCT_POL_AMT,D.COLCT_PREM_AMT,D.COLCT_DPOS_AMT,D.COLCT_LOAN_AMT,D.COLCT_APL_AMT,D.COLCT_PDF_AMT,D.COLCT_SIDFND_AMT,D.POL_PREM_SUSP_AMT,D.POL_MISC_SUSP_AMT,D.POL_OS_DISB_AMT,D.COLCT_TOPUP_AMT,
CL.COLCT_MICR_NUM FROM SGTB_COLLECT CL 
INNER JOIN SGTB_COLLECT_DETAIL D ON CL.COLCT_MICR_NUM=D.COLCT_MICR_NUM AND CL.COLCT_ID_NUM=D.COLCT_ID_NUM
LEFT JOIN SGTB_EDITTABLE PA ON PA.ETBL_VALU_ID=CL.COLCT_PREM_SRCE AND PA.ETBL_TYP_ID='PSRC' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
)
