CREATE FUNCTION [dbo].[FN_GET_POL_DUR] (
    @POL_ID VARCHAR(100)
    ,@PCHST_EFF_DT DATE
    ,@CURRENT_VALUE VARCHAR(40)
)
RETURNS VARCHAR(40) AS
BEGIN
    DECLARE @RES VARCHAR(40), @POL_DURATION_DAY INT;

    SET @POL_DURATION_DAY = 
        DATEDIFF(
            DAY
            ,(
            SELECT 
                MIN(PCHST_EFF_DT) PCHST_EFF_DT 
            FROM 
                SGTB_POLICY_CHANGE PC 
            WHERE PC.POL_ID = @POL_ID
                AND PC.PCHST_STAT_CD='A' 
                AND PC.POL_ACTV_TYP_ID IN ('1082','1084')
            GROUP BY POL_ID)
            ,@PCHST_EFF_DT
        )

    SET @RES = CASE 
            WHEN @POL_DURATION_DAY >= 1 AND @POL_DURATION_DAY < 365 THEN 'RFYP'
            WHEN @POL_DURATION_DAY >= 365 AND @POL_DURATION_DAY < 730 THEN '2YP'
            WHEN @POL_DURATION_DAY >= 730 AND @POL_DURATION_DAY < 1095 THEN '3YP'
            WHEN @POL_DURATION_DAY >= 1095 AND @POL_DURATION_DAY < 1460 THEN '4YP'
            WHEN @POL_DURATION_DAY >= 1460 AND @POL_DURATION_DAY < 1825 THEN '5YP'
            ELSE @CURRENT_VALUE -- CAST(@POL_DURATION_DAY AS VARCHAR)
        END
    RETURN @RES
END
