--- CREATED BY OUDOM 23-APR-2024

CREATE FUNCTION [dbo].[FN_GET_WFYP]
(
	@POL_ID		VARCHAR(10)
	,@POL_TERM	SMALLINT = 0
	,@PREMIUM	DECIMAL(12,2) = 0
)
RETURNS		DECIMAL(12,2)
AS
BEGIN
	DECLARE @WFYP	DECIMAL(12,2),
			@PLAN	VARCHAR(6)

	IF @POL_TERM <= 0	
		SELECT @POL_TERM = CVG_MAT_XPRY_DUR FROM SGTM_COVERAGE WHERE POL_ID = @POL_ID AND CVG_NUM = 1

	IF @PREMIUM <= 0	
		SELECT @PREMIUM = CASE WHEN POL.POL_MPREM_AMT = 0 THEN POL0.POL_MPREM_AMT ELSE POL.POL_MPREM_AMT END, @PLAN = PLAN_ID
		FROM SGTB_POLICY POL
		LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE POL0 ON POL.POL_ID = POL0.POL_ID 
		WHERE POL.POL_ID = @POL_ID

	SELECT @WFYP = CASE WHEN @POL_TERM = 6 AND LEFT(@PLAN,2) = 'KB' THEN @PREMIUM / 2 --EDUPRO AND PREMIUM 6 50%
				   WHEN @PLAN = 'CBS001' THEN @PREMIUM / 10 --- LOANSHIELD SINGLE 10% ALL TERM
				   ELSE @PREMIUM END

	RETURN @WFYP
END
