

CREATE FUNCTION [dbo].[FN_GET_MODAL_PREMIUM_0_HIS]
(
	@POL_ID			VARCHAR(10) 	
	,@START_DATE	DATE
)
RETURNS MONEY
AS
BEGIN
    DECLARE @POL_MPREMIUM_HIS	MONEY

	SELECT   @POL_MPREMIUM_HIS = SUM(CASE WHEN CVG.PLAN_ID = 'BES001' THEN CVG.CVG_UNDSCNT_PREM ELSE CVG.CVG_MPREM_AMT END)

	FROM DIM_COVERAGE CVG
	LEFT JOIN DIM_POLICY POL ON CVG.POL_ID = POL.POL_ID AND POL.START_DT = @START_DATE
	WHERE 1 = 1
	AND CVG.POL_ID = @POL_ID AND CVG.START_DT <= @START_DATE AND  ISNULL(CVG.END_DT,GETDATE()) > @START_DATE
		AND POL.POL_CSTAT_CD IN ('A','B','D','E','R','3')
		AND CVG.CVG_CSTAT_CD NOT IN ('S')
	GROUP BY CVG.POL_ID

	RETURN @POL_MPREMIUM_HIS

END
