CREATE FUNCTION FN_GET_CVG_RIDER (
    @POL_ID VARCHAR(100)
)
RETURNS TABLE
AS
RETURN
    SELECT 
        CVG.CVG_NUM
        ,CVG.CO_ID
        ,CVG.PLAN_ID 
        ,PLAN_NM = RTRIM(PA.ETBL_DESC_TXT) 
    FROM SGTM_COVERAGE CVG
        LEFT JOIN SGTB_POLICY POL ON POL.POL_ID = CVG.POL_ID
        -- PLAN NAME
        LEFT JOIN SGTB_EDITTABLE PA ON CVG.PLAN_ID=PA.ETBL_VALU_ID 
            AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' 
            AND PA.CO_ID='CP' 
    WHERE POL.POL_ID = @POL_ID
        AND CVG.PLAN_ID NOT IN (
            'KBE001'    --EdUPRO
            ,'DWP001'   --WOP1
            ,'DWP002'   --WOP2
        )
