CREATE PROC [dbo].[RPT_PRE_COLL] @START DATE, @END DATE, @ASOF DATE
AS
BEGIN

IF OBJECT_ID('tempdb..#PAY1') IS NOT NULL
  DROP TABLE #PAY1
  IF OBJECT_ID('tempdb..#PAY2') IS NOT NULL
  DROP TABLE #PAY2
IF OBJECT_ID('tempdb..#COL') IS NOT NULL
  DROP TABLE #COL
IF OBJECT_ID('tempdb..#HIS') IS NOT NULL
  DROP TABLE #HIS
IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
IF OBJECT_ID('tempdb..#SMS') IS NOT NULL
  DROP TABLE #SMS
IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
  DROP TABLE #TMP1
IF OBJECT_ID('tempdb..#TMP2') IS NOT NULL
  DROP TABLE #TMP2

 SELECT *, ROW_NUMBER() OVER ( PARTITION BY POL_ID ORDER BY PCHST_EFF_DT) ROW_NUM into #PAY2 FROM DLKHSTAGE..SGTB_POLICY_CHANGE WHERE  POL_ACTV_TYP_ID IN (1082) AND PCHST_STAT_CD='A' and PCHST_NEW_VALU_TXT like '%001%'
SELECT *,0 ROW_NUM into #PAY1 FROM DLKHSTAGE..SGTB_POLICY_CHANGE  WHERE  POL_ACTV_TYP_ID IN (1084)

INSERT INTO #PAY1
SELECT * FROM #PAY2 WHERE ROW_NUM>1 and PCHST_EFF_DT BETWEEN @START AND @END

SELECT ACCT_HIST_PRCES_DT,ACCT_HIST_AMT,H.POL_ID INTO #HIS FROM DLKHSTAGE..SGTB_ACCOUNTING_TRANHIS H INNER JOIN (SELECT POL_ID,MAX(ACCT_HIST_GEN_ID) MAX_ID FROM DLKHSTAGE..SGTB_ACCOUNTING_TRANHIS WHERE ACCT_HIST_PRCES_DT BETWEEN @START AND @END  AND ACCT_BASE_ID='249800'
AND ETL_DATE=@ASOF
GROUP BY POL_ID) HH ON H.ACCT_HIST_GEN_ID=HH.MAX_ID AND H.POL_ID=HH.POL_ID WHERE ETL_DATE=@ASOF

SELECT * INTO #COL FROM FACT_COLLECTION WHERE DATE_KEY=CONVERT(VARCHAR,@ASOF,112) AND POL_PD_TO_DT_NUM>'2018-01-01' and POL_STAT in ('PREMIUM PAYING','LAPSED')

SELECT C.*,cast(P.PCHST_EFF_DT as date) PCHST_EFF_DT,CASE WHEN P.PCHST_EFF_DT IS NOT NULL THEN cast(P.PCHST_EFF_DT as date) ELSE C.POL_PD_TO_DT_NUM END PAIDTODATE,CAST(PREV_UPDT_TS AS DATE) PREV_UPDT_TS INTO #TMP FROM #COL C FULL JOIN #PAY1 P ON C.POL_ID=P.POL_ID 

DELETE FROM #TMP WHERE DATE_KEY IS NULL

  

SELECT T.*,ACCT_HIST_PRCES_DT,ACCT_HIST_AMT,
CASE WHEN DATEDIFF(DAY,@ASOF,POL_PD_TO_DT_NUM)<=7 AND DATEDIFF(DAY,@ASOF,POL_PD_TO_DT_NUM)>=0 THEN  DATEDIFF(DAY,@ASOF,POL_PD_TO_DT_NUM)+1 ELSE 0 END REMIND,
CASE WHEN POL_BILL_MODE_CD=3 THEN
'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Monthly' WHEN POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE POL_BILL_MODE_CD END PRE_MODE INTO #TMP1
 FROM #TMP T LEFT JOIN #HIS H ON T.POL_ID=H.POL_ID AND T.PCHST_EFF_DT IS NOT NULL AND T.PREV_UPDT_TS>=H.ACCT_HIST_PRCES_DT
  WHERE PAIDTODATE BETWEEN @START AND @END OR POL_PD_TO_DT_NUM BETWEEN @START AND @END 
  

  SELECT * INTO #TMP2 FROM #TMP1 WHERE POL_PD_TO_DT_NUM>PAIDTODATE  and POL_PD_TO_DT_NUM<=@END
 UPDATE #TMP2 SET PCHST_EFF_DT=NULL,PAIDTODATE=POL_PD_TO_DT_NUM,ACCT_HIST_AMT=NULL,ACCT_HIST_PRCES_DT=NULL
 SELECT DISTINCT T.DATE_KEY,POL_KEY,T.POL_ID,POL_APP_FORM_ID,POL_STAT,PLAN_ID,POL_BILL_MODE_CD,CLI_NAME,CLI_PHONE2,CLI_PHONE1,EMAIL,CLI_CITY_NM_TXT,POL_PD_TO_DT_NUM,_DAY,_MONTH,_YEAR,POL_CREAT_DT,PRE_AMT,
 POL_PREM_SUSP_AMT,POL_OS_DISB_AMT,BANK_CASH,AGENT_NO,AGENT_LASTNAME,AGENT_FIRSTNAME,AGENT_MOBILE,CSC_NAME,PCHST_EFF_DT,T.PAIDTODATE,ACCT_HIST_PRCES_DT,ACCT_HIST_AMT,REMIND,PRE_MODE,
CASE WHEN POL_BILL_MODE_CD=1 AND ACCT_HIST_PRCES_DT IS NULL  AND DATEDIFF(DAY,POL_PD_TO_DT_NUM,@ASOF)>0  THEN  dbo.FullMonthsSeparation(POL_PD_TO_DT_NUM,@ASOF)/1 
WHEN POL_BILL_MODE_CD=3 AND ACCT_HIST_PRCES_DT IS NULL  AND DATEDIFF(DAY,POL_PD_TO_DT_NUM,@ASOF)>0 THEN  dbo.FullMonthsSeparation(POL_PD_TO_DT_NUM,@ASOF)/3
WHEN POL_BILL_MODE_CD=6 AND ACCT_HIST_PRCES_DT IS NULL  AND DATEDIFF(DAY,POL_PD_TO_DT_NUM,@ASOF)>0 THEN  dbo.FullMonthsSeparation(POL_PD_TO_DT_NUM,@ASOF)/6
WHEN POL_BILL_MODE_CD=12 AND ACCT_HIST_PRCES_DT IS NULL  AND DATEDIFF(DAY,POL_PD_TO_DT_NUM,@ASOF)>0 THEN  dbo.FullMonthsSeparation(POL_PD_TO_DT_NUM,@ASOF)/12 ELSE 0 END  MISSED_INSTALL,CASE WHEN PCHST_EFF_DT IS NULL AND DATEDIFF(DAY,POL_PD_TO_DT_NUM,@ASOF)>0 THEN DATEDIFF(DAY,POL_PD_TO_DT_NUM,@ASOF) ELSE 0 END MISSDAY,DATENAME(DAY,T.PAIDTODATE) _DAY1,DATENAME(MONTH,T.PAIDTODATE) _MONTH1,DATENAME(YEAR,T.PAIDTODATE) _YEAR1
,C.CLI_SEX_CD CLI_SEX,A.ABM_ID,CONCAT(A.ABM_SURNAME,' ',A.ABM_GIVNAME) ABM_NAME
 FROM (
 SELECT * FROM #TMP1
 UNION ALL
 SELECT * FROM #TMP2
 ) T 
INNER JOIN DLKHSTAGE..SGTB_POLICY_CLIENT PC ON PC.POL_ID=T.POL_ID
INNER JOIN DLKHSTAGE..SGTM_CLIENT C ON C.CLI_ID=PC.CLI_ID
INNER JOIN FACT_AGENT A ON T.AGENT_NO=A.AGT_ID AND A.AGT_CLI_REL_TYP_CD='M'
 WHERE T.PAIDTODATE>=@START AND A.DATE_KEY=CONVERT(VARCHAR,@ASOF,112)

 END
