
/***************************************************************************************************

	REPORT:.......... REPLAVEMENT OF POLICY (SALE DIST. DEPT.)

	PURPOSE:.........  

    Changelog

    ***********

	VERSION    DATE CHNG   UPD_BY     DESC

	VERS0.1		                      Initial Version

	VERS0.1	   28-05-2024  DOM        GET UNDISCOUNT PREMIUM AMOUNT AS MODAL PREM FOR EASYCARE

***************************************************************************************************/
 
CREATE PROC [dbo].[RPT_REPLACEMENT_OF_POLICY] 

	@ASOF_DATE DATE,

	@START_DATE		DATE = NULL,

	@END_DATE		DATE = NULL

AS

	--DECLARE @ASOF_DATE	DATE = '2024-05-29'

	--DECLARE @START_DATE	DATE = '2024-05-01'

	--DECLARE @END_DATE	DATE = '2024-05-27'
 
	IF ISNULL(@START_DATE,'') = ''	SET @START_DATE = '2000-01-01'

	IF ISNULL(@END_DATE,'') = ''	SET @END_DATE = @ASOF_DATE
 
	DROP TABLE IF EXISTS #AGT

	DROP TABLE IF EXISTS #EDIT
 
 
	SELECT * INTO #AGT FROM DLKHSTAGE..V_GET_AGENT_BASIC

	SELECT ETBL_VALU_ID,ETBL_TYP_ID,ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) INTO #EDIT FROM DLKHSTAGE..SGTB_EDITTABLE WHERE CO_ID = 'CP' AND ETBL_LANG_CD = 'E'

		AND ETBL_TYP_ID IN ('AGTLE','DV-AGT-STAT-CD','CSRC','BILL-MODE')
 
	SELECT DISTINCT A.DATE_KEY

		,A.POL_KEY

		,A.CLIIND_KEY

		,A.POL_ID		

		,POL_APP_FORM_ID = RTRIM(P.POL_APP_FORM_ID)

		,A.CS_REV_DT

		,DM_AV_DESC_TXT = UPPER(RTRIM(A.DM_AV_DESC_TXT))

		,PO_ID = PO.CLI_ID

		,PO_NAME = CONCAT(RTRIM(A.ENTR_SUR_NM),' ',RTRIM(A.ENTR_GIV_NM))

		--,PO_TEL = RTRIM(POC.CLI_CNTCT_ID_TXT)

		,PO_TEL1 = CASE WHEN MO.CLI_CNTCT_ID_TXT != '' OR MO.CLI_CNTCT_ID_TXT IS NOT NULL THEN RTRIM(MO.CLI_CNTCT_ID_TXT)

						WHEN HO.CLI_CNTCT_ID_TXT != '' OR HO.CLI_CNTCT_ID_TXT IS NOT NULL THEN RTRIM(HO.CLI_CNTCT_ID_TXT) 

						WHEN BU.CLI_CNTCT_ID_TXT != '' OR BU.CLI_CNTCT_ID_TXT IS NOT NULL THEN RTRIM(BU.CLI_CNTCT_ID_TXT)

						END
 
		,PO_TEL2 = CASE WHEN (HO.CLI_CNTCT_ID_TXT != '' OR HO.CLI_CNTCT_ID_TXT IS NOT NULL) AND (MO.CLI_CNTCT_ID_TXT != '' OR MO.CLI_CNTCT_ID_TXT IS NOT NULL) THEN RTRIM(HO.CLI_CNTCT_ID_TXT) 

						WHEN (BU.CLI_CNTCT_ID_TXT != '' OR BU.CLI_CNTCT_ID_TXT IS NOT NULL) AND (HO.CLI_CNTCT_ID_TXT != '' OR HO.CLI_CNTCT_ID_TXT IS NOT NULL) THEN RTRIM(BU.CLI_CNTCT_ID_TXT)

						END

		,BLI_CLI_ID = BLI.INSRD_CLI_ID

		,BLI_NAME = CONCAT(RTRIM(BINFO.ENTR_SUR_NM),' ',RTRIM(BINFO.ENTR_GIV_NM))

		--,BLI_TEL = RTRIM(BINFO.CLI_CNTCT_ID_TXT)

		,BLI_TEL1 = CASE WHEN BMO.CLI_CNTCT_ID_TXT != '' OR BMO.CLI_CNTCT_ID_TXT IS NOT NULL THEN RTRIM(BMO.CLI_CNTCT_ID_TXT)

						 WHEN BHO.CLI_CNTCT_ID_TXT != '' OR BHO.CLI_CNTCT_ID_TXT IS NOT NULL THEN RTRIM(BHO.CLI_CNTCT_ID_TXT) 

						 WHEN BBU.CLI_CNTCT_ID_TXT != '' OR BBU.CLI_CNTCT_ID_TXT IS NOT NULL THEN RTRIM(BBU.CLI_CNTCT_ID_TXT) 

						 END
 
		,BLI_TEL2 = CASE WHEN (BHO.CLI_CNTCT_ID_TXT != '' OR BHO.CLI_CNTCT_ID_TXT IS NOT NULL) AND (BMO.CLI_CNTCT_ID_TXT != '' OR BMO.CLI_CNTCT_ID_TXT IS NOT NULL) THEN RTRIM(BHO.CLI_CNTCT_ID_TXT) 

						 WHEN (BBU.CLI_CNTCT_ID_TXT != '' OR BBU.CLI_CNTCT_ID_TXT IS NOT NULL) AND (BHO.CLI_CNTCT_ID_TXT != '' OR BHO.CLI_CNTCT_ID_TXT IS NOT NULL) THEN RTRIM(BBU.CLI_CNTCT_ID_TXT) 

						 END

		,A.PLAN_ID

		,PLAN_NAME = RTRIM(A.PLAN_NAME)

		,A.POL_AGT_SHR_PCT

		,A.POL_BILL_MODE_CD

		,BMODE.ETBL_DESC_TXT AS BILL_MODE

		,A.POL_CSTAT_CD

		,POL_CSTAT_DESC = RTRIM(PSTAT.DM_AV_DESC_TXT)

		,CASE WHEN A.POL_CSTAT_CD IN('A','B','E') THEN P.POL_STAT_CHNG_DT END POL_STAT_CHNG_DT

		,A.POL_ISS_DT

		,A.POL_PREM_PAY_DUR

		,A.CVG_ME_FCT

		,CASE WHEN A.PLAN_ID = 'BES001' THEN C.CVG_UNDSCNT_PREM ELSE A.CVG_MPREM_AMT END CVG_MPREM_AMT

		,A.CVG_SUM_INS_AMT

		,AFYP = 

		 CASE WHEN A.PLAN_ID = 'CBS001' THEN A.AFYP * 0.1 ELSE

		 CASE WHEN A.PLAN_ID = 'BES001' THEN C.CVG_UNDSCNT_PREM * (CASE WHEN CAST(A.POL_BILL_MODE_CD AS INT)>0 THEN 12/CAST(A.POL_BILL_MODE_CD AS INT) ELSE 1 END) ELSE A.AFYP END END

		,CASE WHEN A.PLAN_ID = 'BES001' THEN C.CVG_UNDSCNT_PREM ELSE A.CVG_MPREM_AMT END POL_MPREM_AMT

		--,WFYP = DLKHSTAGE.dbo.FN_GET_WFYP (A.POL_ID, A.POL_PREM_PAY_DUR, A.CVG_MPREM_AMT)

		--,WFYP = A.AFYP / (CASE WHEN CAST(A.POL_BILL_MODE_CD AS INT) = 0 THEN 1 ELSE 12/CAST(A.POL_BILL_MODE_CD AS INT) END) 

		,A.PRE_AFTER

		,A.PRE_BEFORE

		,A.PRO_LOAD_DT

		,CSC_NAME = RTRIM(A.CSC_NAME)

		,A.AGENT_CODE

		,A.AGENT_KEY

		,ABM_ID = AGM.AGT_ID

		,ABM_NAME = CONCAT(RTRIM(AGM.ENTR_SUR_NM),' ',RTRIM(AGM.ENTR_GIV_NM))

		,OVRID_BASE_AGT_ID = AGL.AGT_ID

		,LNAME = RTRIM(AGL.ENTR_SUR_NM) + ' ' + RTRIM(AGL.ENTR_GIV_NM)

		,AGT_NAME = RTRIM(AGT.ENTR_SUR_NM) + ' ' + RTRIM(AGT.ENTR_GIV_NM)

		,AGT.AGT_STAT_CD

		,AGT_STAT_DESC = AGST.ETBL_DESC_TXT

		,AGT_TITL_DESC = AGTLE.ETBL_DESC_TXT

		,AGT.AGT_CNTRCT_STRT_DT

		,BANK_AREA =  RTRIM(BKA.ENTR_SUR_NM)

		,POLW.POL_SOLD_BR_ID

		,POL_SOLD_BR_NAME = RTRIM(SLDBR.ETBL_DESC_TXT)

		,P.CUST_SRC_CD

		,CUST_SRC_DESC = CSRC.ETBL_DESC_TXT

	FROM DLKHFACT..FACT_AXP_AA A 

	LEFT JOIN DLKHSTAGE..SGTM_COVERAGE C ON C.POL_ID = A.POL_ID AND C.CVG_NUM = '01'

	LEFT JOIN DLKHSTAGE..SGTB_POLICY P ON A.POL_ID = P.POL_ID

	LEFT JOIN DLKHSTAGE..SGTB_POLICY_CLIENT PO ON PO.POL_ID = A.POL_ID AND PO.POL_CLI_REL_TYP_CD = 'O'

	--LEFT JOIN DLKHSTAGE..V_CLI_INFO POC ON POC.CLI_ID = PO.CLI_ID 

	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_CONTACT MO ON MO.CLI_ID = PO.CLI_ID  AND MO.CLI_CNTCT_ID_CD='MO' --CELLPHONE

	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_CONTACT HO ON HO.CLI_ID = PO.CLI_ID  AND HO.CLI_CNTCT_ID_CD='HO' --HOME

	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_CONTACT BU ON BU.CLI_ID = PO.CLI_ID  AND BU.CLI_CNTCT_ID_CD='BU' --OFFICE

	LEFT JOIN DLKHSTAGE..SGTB_POLICY_WRITING POLW ON A.POL_ID = POLW.POL_ID

	LEFT JOIN DLKHSTAGE..SGTB_COVERAGE_CLI BLI ON BLI.POL_ID = A.POL_ID AND BLI.CVG_NUM = '01'

	LEFT JOIN DLKHSTAGE..V_CLI_INFO BINFO ON BINFO.CLI_ID = BLI.INSRD_CLI_ID

	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_CONTACT BMO ON BMO.CLI_ID = BLI.INSRD_CLI_ID  AND BMO.CLI_CNTCT_ID_CD='MO' --CELLPHONE

	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_CONTACT BHO ON BHO.CLI_ID = BLI.INSRD_CLI_ID  AND BHO.CLI_CNTCT_ID_CD='HO' --HOME

	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_CONTACT BBU ON BBU.CLI_ID = BLI.INSRD_CLI_ID  AND BBU.CLI_CNTCT_ID_CD='BU' --OFFICE

	LEFT JOIN #AGT AGT ON A.AGENT_CODE = AGT.AGT_ID

	LEFT JOIN #AGT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID

	LEFT JOIN #AGT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID

	LEFT JOIN #AGT BKA ON AGM.OVRID_BASE_AGT_ID = BKA.AGT_ID

	LEFT JOIN #EDIT AGTLE ON AGT.AGT_TITL = AGTLE.ETBL_VALU_ID AND AGTLE.ETBL_TYP_ID = 'AGTLE'

	LEFT JOIN #EDIT AGST ON AGT.AGT_STAT_CD = AGST.ETBL_VALU_ID AND AGST.ETBL_TYP_ID = 'DV-AGT-STAT-CD'

	LEFT JOIN #EDIT CSRC ON P.CUST_SRC_CD = CSRC.ETBL_VALU_ID AND CSRC.ETBL_TYP_ID = 'CSRC'

	LEFT JOIN #EDIT BMODE ON A.POL_BILL_MODE_CD = BMODE.ETBL_VALU_ID AND BMODE.ETBL_TYP_ID = 'BILL-MODE'

	LEFT JOIN DLKHSTAGE..SGTM_PARA SLDBR ON POLW.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_LANG_CD = 'E' AND SLDBR.ETBL_TYP_ID = 'SOLDBR'

	LEFT JOIN DLKHSTAGE..SGTM_PARA_1 PSTAT ON PSTAT.DM_AV_CD = A.POL_CSTAT_CD AND PSTAT.DM_AV_DESC_LANG_CD = 'E' AND PSTAT.CO_ID = 'CP' AND PSTAT.DM_AV_TBL_CD = 'POL-CSTAT-CD'

	WHERE  A.DATE_KEY = CONVERT(VARCHAR,@ASOF_DATE,112) AND A.POL_ISS_DT BETWEEN @START_DATE AND @END_DATE 

	ORDER BY A.POL_ID ASC
