
CREATE PROC [dbo].[RPT_UNUSE_POL] @BRANCH_DATE DATE
AS
BEGIN
	SELECT *,
		CASE WHEN FAMILY_NAME IS NULL OR FAMILY_NAME='' 
			OR GIVEN_NAME IS NULL OR GIVEN_NAME='' 
			OR DOB IS NULL OR DOB='' 
			OR CLI_IDEN_NO IS NULL OR CLI_IDEN_NO=''
			OR SEX IS NULL OR SEX='' 
			OR SMOKER IS NULL OR SMOKER='' 
			OR MS IS NULL OR MS='' 
			OR RT IS NULL OR RT='' 
			OR ADDRESS IS NULL OR ADDRESS='' 
			OR CITY IS NULL OR CITY='' 
			OR DISTRICT IS NULL OR DISTRICT='' 
			OR  WARD IS NULL OR WARD=''
		THEN 'INVALID CLIENT' 
		ELSE 'VALID CLIENT' END STATUS_CLIENT 
	FROM FACT_UNUSE_POL 
	WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
END
