CREATE PROC [dbo].[RPT_PAYMENT_REVERSE] @BRANCH_DATE DATE,@START DATE, @END DATE
AS
BEGIN
SELECT distinct * FROM FACT_PAYMENT_REVERSE WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) AND CAST(TRAN_DATE AS DATE) BETWEEN @START	AND @END
END
