

CREATE PROC [dbo].[RPT_AGENT_SUM_ABM] @ASOF DATE
AS
	--DECLARE	@ASOF DATE	= '2024-06-26'
	DROP TABLE IF EXISTS #AGT

	SELECT * INTO #AGT FROM DLKHSTAGE..V_GET_AGENT_BASIC

		SELECT  ABM_ID = AGM.AGT_ID
			,ABMNAME = RTRIM(AGM.ENTR_SUR_NM) + ' ' + RTRIM(AGM.ENTR_GIV_NM)
			,COUNT(POL_ID) #PENDING
			,SUM(POL_MPREM_AMT) POL_MPREM_AMT
			,SUM(APE) AFYP
			,MAX(PENDING_DAYS) PENDING_DAYS
		FROM FACT_AGT_SUM C
		LEFT JOIN #AGT AGT ON C.AGT_ID = AGT.AGT_ID
		LEFT JOIN #AGT AGL ON  AGT.OVRID_BASE_AGT_ID  = AGL.AGT_ID
		LEFT JOIN #AGT AGM ON  AGL.OVRID_BASE_AGT_ID  = AGM.AGT_ID

		WHERE C.CSC_CODE = 'AG'	--	AGENCY
			AND C.DATE_KEY = CONVERT(VARCHAR,@ASOF,112)
		GROUP BY AGM.AGT_ID, AGM.ENTR_SUR_NM, AGM.ENTR_GIV_NM

		ORDER BY AGM.AGT_ID
