

CREATE PROC [dbo].[RPT_AGENT_SUM_BANK]
(
	@ASOF DATE
)
AS

	--DECLARE	@ASOF DATE	= '2024-06-27'
	DROP TABLE IF EXISTS #AGT

	SELECT * INTO #AGT FROM DLKHSTAGE..V_GET_AGENT_BASIC

	SELECT FA.*
		,LCODE = AGL.AGT_ID
		,LNAME = RTRIM(AGL.ENTR_SUR_NM) + ' ' + RTRIM(AGL.ENTR_GIV_NM)
		,ABM_ID = AGM.AGT_ID
		,ABMNAME = CASE WHEN FA.CSC_CODE = 'BA' THEN RTRIM(AGL.ENTR_SUR_NM) ELSE RTRIM(AGM.ENTR_SUR_NM)END + ' ' + CASE WHEN FA.CSC_CODE = 'BA' THEN RTRIM(AGL.ENTR_SUR_NM) ELSE RTRIM(AGM.ENTR_GIV_NM)END
		,P.POL_APP_FORM_ID
	FROM FACT_AGT_SUM FA
	LEFT JOIN DLKHSTAGE..SGTB_POLICY P ON FA.POL_ID = P.POL_ID
	LEFT JOIN #AGT AGT ON FA.AGT_ID = AGT.AGT_ID
	LEFT JOIN #AGT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
	WHERE FA.CSC_CODE = 'AG'
		AND FA.DATE_KEY = CONVERT(VARCHAR,@ASOF,112) 
	ORDER BY POL_ID
