CREATE PROC [dbo].[RPT_ATR_OUT_OF_FORCE] @BRANCH_DATE DATE
AS
--	DECLARE	@BRANCH_DATE	DATE = '2025-12-08'
	SELECT DISTINCT DATE_KEY
		,F.COV_KEY 
		,F.POL_KEY
		,CLI_KEY
		,F.POL_ID
		,F.CVG_NUM
		,F.PLAN_ID
		,F.CVG_APP_CMPLT_DT
		,F.CVG_ISS_EFF_DT
		,F.CVG_STAT_PRCES_DT
		,F.CVG_CSTAT_CD
		,CVG_CSTAT_DESC = CASE WHEN F.CVG_CSTAT_CD = 'A' THEN 'CFI' ELSE RTRIM(CVGSTAT.DM_AV_DESC_TXT) END
		,F.CVG_PREV_CSTAT_CD
		,CLASS
		,F.CVG_FACE_AMT
		,PRE_MODE 
		,INSRD_CLI_ID
		,CLI_SEX_CD
		,CLI_BTH_DT
		,F.CVG_MAT_XPRY_DT
		,TARGET_PREM
		,F.CVG_MPREM_AMT
		,F.POL_PD_TO_DT_NUM
		,AGE = AGE + 0
		,AGT_ID
		,F.CVG_ME_FCT
		,MEDICAL_LOADING_PERCENT
		,F.CVG_BASIC_PREM_AMT
		,POL_PREM_PAY_DUR
		,TPD_BENEFIT
		,F.CVG_EMR_UW_RT
		,F.CVG_EMR_UW1_RT
		,F.CVG_EMR_UW2_RT
		,F.CVG_EMR_UW3_RT
		,F.CVG_EMR_PER_MIL_LD
		,F.CVG_ADB_MIL_LD
		,F.CVG_TPD_MIL_LD
		,F.CVG_ATPD_MIL_LD
		,F.POL_BILL_MODE_CD
		,F.POL_CSTAT_CD
		,CLI_OCCP_CLAS_CD
		,F.POL_GRS_APREM_AMT
		,PO
		,POSEX
		,PODOB
		,CVG_EMR_UW4_RT = ISNULL(F.CVG_EMR_UW4_RT,0)
		,CVG_HLTH_MIL_LD = ISNULL(F.CVG_HLTH_MIL_LD,0)
		,CVG_EMR_UW5_RT = ISNULL(F.CVG_EMR_UW5_RT,0)
		,CI_EMR = CASE WHEN F.PLAN_ID = 'DRD004' THEN F.CVG_EMR_UW5_RT ELSE 0 END
		,CI_WOP_EMR = CASE WHEN F.PLAN_ID = 'DRD004' THEN 0 ELSE F.CVG_EMR_UW5_RT END
		,CVG_FAMI_MIL_LD = ISNULL(F.CVG_FAMI_MIL_LD,0)
		,CI_PER_MILLE = CASE WHEN F.PLAN_ID = 'DRD004' THEN F.CVG_FAMI_MIL_LD ELSE 0 END
		,CI_PER_WOP_MILLE = CASE WHEN F.PLAN_ID = 'DRD004' THEN 0 ELSE F.CVG_FAMI_MIL_LD END
		,PREV_CVG_FACE_AMT = ISNULL(PREV_CVG_FACE_AMT, F.CVG_FACE_AMT)
		,PREV_POL_BILL_MODE_CD = CASE 
		    WHEN ISNULL(PREV_POL_BILL_MODE_CD,'') = '03' THEN 'Q'
		    WHEN ISNULL(PREV_POL_BILL_MODE_CD,'') = '06' THEN 'H'
		    WHEN ISNULL(PREV_POL_BILL_MODE_CD,'') = '01' THEN 'M'
		    WHEN ISNULL(PREV_POL_BILL_MODE_CD,'') = '12' AND POL.POL_BILL_TYP_CD = 'P' THEN 'F'
		    WHEN ISNULL(PREV_POL_BILL_MODE_CD,'') = '12' THEN 'Y'
		    ELSE PRE_MODE
		END
		,PREV_PO = ISNULL(PREV_PO,PO)
		,PREV_CLI_OCCP_CLAS_CD = ISNULL(PREV_CLI_OCCP_CLAS_CD,CLI_OCCP_CLAS_CD)
		,INSRD_OCCP_ID
		,CLI_OCCUP = RTRIM(EDIT.ETBL_DESC_TXT) 
		,STATUS_PREMIUM = CASE WHEN F.CVG_CSTAT_CD = 'D' THEN 'DP' ELSE 'OF' END

		--DL-956
		,CASE 
			WHEN F.PLAN_ID = 'BSS001' THEN RTRIM(STB1.ETBL_DESC_TXT) 
			WHEN ( F.PLAN_ID = 'KBE003' AND CVG.CVG_STBL_1_CD IN ('P1', 'P2') ) THEN RTRIM(PLN.ETBL_DESC_TXT) + ' ' + STB1.ETBL_DESC_TXT
			ELSE RTRIM(PLN.ETBL_DESC_TXT)
		END PRODUCT_NAME
		,PREMIUM_TYPE = CASE
                            WHEN F.PLAN_ID = 'KBE003' AND POL.POL_BILL_TYP_CD = 'P' THEN 'Single Pay'
                            WHEN F.PLAN_ID = 'KBE002' THEN 'Limited Pay' 
							WHEN F.PLAN_ID = 'DRD005' THEN 'Limited Pay' 
							WHEN F.PLAN_ID = 'CBS001' THEN 'Single Pay'
							WHEN F.PLAN_ID = 'BSS001' THEN CASE WHEN CVG.CVG_MAT_XPRY_DUR != CVG.PREM_PMT_DUR THEN 'Limited Pay' ELSE 'Full Pay' END
							WHEN F.PLAN_ID = 'BES001' THEN CASE WHEN CVG.CVG_STBL_1_CD = 'AP' THEN 'Advanced Pay' ELSE 'Regular Pay' END
							ELSE 'Regular Pay' END
		,UNDISCOUNT_PREMIUM = CASE WHEN F.PLAN_ID = 'BES001' THEN CVG.CVG_UNDSCNT_PREM ELSE NULL END
		,LAP.LAST_LAPSED_DATE LAST_LAPSED_DATE
		,CVG_ROP = CASE 
			WHEN CVG.CVG_STBL_2_CD = 'CRP' THEN '100ROP'
			WHEN CVG.CVG_STBL_2_CD = 'SRP' THEN '70ROP'
			ELSE NULL
		END 
	FROM [DLKHFACT].[DBO].[FACT_ATR] F
	INNER JOIN DLKHDIM..DIM_POLICY POL ON F.POL_KEY = POL.POL_KEY
    LEFT JOIN DLKHDIM..DIM_COVERAGE CVG ON CVG.COV_KEY = F.COV_KEY
	LEFT JOIN [DLKHSTAGE]..[SGTB_EDITTABLE] EDIT ON F.INSRD_OCCP_ID = EDIT.ETBL_VALU_ID AND EDIT.ETBL_TYP_ID='OCCCD' AND EDIT.CO_ID = 'CP' AND EDIT.ETBL_LANG_CD = 'E'
	LEFT JOIN DLKHSTAGE..SGTM_PARA_1 CVGSTAT ON F.CVG_CSTAT_CD = CVGSTAT.DM_AV_CD AND CVGSTAT.DM_AV_TBL_CD ='CVG-CSTAT-CD' AND CVGSTAT.CO_ID = 'CP' AND CVGSTAT.DM_AV_DESC_LANG_CD = 'E'
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE PLN ON  PLN.ETBL_TYP_ID = 'PLAN' AND F.PLAN_ID = PLN.ETBL_VALU_ID  
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE STB1 ON STB1.ETBL_TYP_ID = 'STB1' AND CVG.CVG_STBL_1_CD = STB1.ETBL_VALU_ID 
	-- GET LAST LAPSE DATE
	LEFT JOIN (SELECT POL_ID,CVG_NUM, MAX(MVT_TRXN_PRCES_DT) LAST_LAPSED_DATE FROM DLKHSTAGE..SGTB_MVTX WHERE MVT_TRXN_LN_NUM = '190' AND MVT_TRXN_PRCES_DT < @BRANCH_DATE GROUP BY POL_ID,CVG_NUM) LAP ON LAP.POL_ID = F.POL_ID AND LAP.CVG_NUM = F.CVG_NUM
	WHERE F.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) 
		AND (F.POL_CSTAT_CD IN ('A','B','D','E','F') OR F.CVG_CSTAT_CD IN ('A','B','D','E','F'))
		-- EXCLUDE ANY POLICIES ISSUE AND CFI WITHIN THE SAME MONTH
		AND NOT (F.POL_CSTAT_CD = 'A' AND F.POL_PREV_CSTAT_CD = '1' AND LEFT(F.POL_STAT_CHNG_DT,7) = LEFT(F.POL_INFC_DT,7))
	ORDER BY F.POL_ID
