CREATE PROC [dbo].[RPT_PRE_COLL_SALE] @START DATE, @END DATE, @ASOF DATE
AS
BEGIN

IF OBJECT_ID('tempdb..#PAY1') IS NOT NULL
  DROP TABLE #PAY1
IF OBJECT_ID('tempdb..#COL') IS NOT NULL
  DROP TABLE #COL
IF OBJECT_ID('tempdb..#HIS') IS NOT NULL
  DROP TABLE #HIS
IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
IF OBJECT_ID('tempdb..#SMS') IS NOT NULL
  DROP TABLE #SMS

 SELECT * INTO #SMS FROM OPENQUERY(DLIPNHHPDB02,'SELECT * FROM TBES')
SELECT * into #PAY1 FROM DLKHSTAGE..SGTB_POLICY_CHANGE  WHERE PCHST_EFF_DT BETWEEN @START AND @END AND POL_ACTV_TYP_ID=1084
SELECT ACCT_HIST_PRCES_DT,ACCT_HIST_AMT,RECPT_ID,H.POL_ID INTO #HIS FROM DLKHSTAGE..SGTB_ACCOUNTING_TRANHIS H INNER JOIN (SELECT POL_ID,MAX(ACCT_HIST_GEN_ID) MAX_ID FROM DLKHSTAGE..SGTB_ACCOUNTING_TRANHIS WHERE ACCT_HIST_PRCES_DT BETWEEN @START AND @END AND BPF_ID='BF0460Payment' AND ACCT_BASE_ID=102300
AND ETL_DATE=@ASOF AND LEFT(RECPT_ID,1)<>'R'
GROUP BY POL_ID) HH ON H.ACCT_HIST_GEN_ID=HH.MAX_ID AND H.POL_ID=HH.POL_ID WHERE ETL_DATE=@ASOF

--SELECT * FROM DLKHSTAGE..SGTB_ACCOUNTING_TRANHIS
SELECT * INTO #COL FROM FACT_COLLECTION WHERE DATE_KEY=CONVERT(VARCHAR,@ASOF,112) 
SELECT C.*,cast(P.PREV_UPDT_TS as date) PCHST_EFF_DT,CASE WHEN P.PCHST_EFF_DT IS NOT NULL THEN cast(P.PREV_UPDT_TS as date) ELSE C.POL_PD_TO_DT_NUM END PAIDTODATE INTO #TMP FROM #COL C FULL JOIN #PAY1 P ON C.POL_ID=P.POL_ID 

DELETE FROM #TMP WHERE DATE_KEY IS NULL

SELECT T.*,ACCT_HIST_PRCES_DT,ACCT_HIST_AMT,RECPT_ID,CASE WHEN RECPT_ID IS NULL AND DATEDIFF(DAY,PAIDTODATE,@ASOF)>0 THEN DATEDIFF(DAY,PAIDTODATE,@ASOF) ELSE 0 END MISSDAY,
CASE WHEN POL_BILL_MODE_CD=1 AND RECPT_ID IS NULL  AND DATEDIFF(DAY,PAIDTODATE,@ASOF)>0  THEN  DATEDIFF(MONTH,PAIDTODATE,@ASOF)/1 
WHEN POL_BILL_MODE_CD=3 AND RECPT_ID IS NULL  AND DATEDIFF(DAY,PAIDTODATE,@ASOF)>0 THEN  DATEDIFF(MONTH,PAIDTODATE,@ASOF)/3
WHEN POL_BILL_MODE_CD=6 AND RECPT_ID IS NULL  AND DATEDIFF(DAY,PAIDTODATE,@ASOF)>0 THEN  DATEDIFF(MONTH,PAIDTODATE,@ASOF)/6
WHEN POL_BILL_MODE_CD=12 AND RECPT_ID IS NULL  AND DATEDIFF(DAY,PAIDTODATE,@ASOF)>0 THEN  DATEDIFF(MONTH,PAIDTODATE,@ASOF)/12 ELSE 0 END  MISSED_INSTALL,
CASE WHEN DATEDIFF(DAY,@ASOF,PAIDTODATE)<=7 AND DATEDIFF(DAY,@ASOF,PAIDTODATE)>0 THEN  DATEDIFF(DAY,@ASOF,PAIDTODATE) ELSE 0 END REMIND,
CASE WHEN S.SEND_DT IS NOT NULL then 'Sent' ELSE 'FutureDate' END BE7,CASE WHEN S.SEND_DT IS NOT NULL then S.SEND_DT ELSE NULL END BE7_DT,
CASE WHEN S2.SEND_DT IS NOT NULL then 'Sent' ELSE 'FutureDate' END AF3,CASE WHEN S2.SEND_DT IS NOT NULL then S2.SEND_DT ELSE NULL END AF3_DT,
CASE WHEN S1.SEND_DT IS NOT NULL then 'Sent' ELSE 'FutureDate' END LAP,CASE WHEN  S1.SEND_DT IS NOT NULL then S1.SEND_DT ELSE NULL END LAP_DT,
DATENAME(DAY,PAIDTODATE) _DAY1,DATENAME(MONTH,PAIDTODATE) _MONTH1,DATENAME(YEAR,PAIDTODATE) _YEAR1,CASE WHEN POL_BILL_MODE_CD=3 THEN
'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Month' WHEN POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE POL_BILL_MODE_CD END PRE_MODE
 FROM #TMP T LEFT JOIN #HIS H ON T.POL_ID=H.POL_ID AND T.PCHST_EFF_DT IS NOT NULL
 LEFT JOIN #SMS S ON T.POL_ID=S.POL_ID AND S.LETTER_ID=61 AND S.APP_TYPE='SMS' and S.POL_STATUS=1
  LEFT JOIN #SMS S2 ON T.POL_ID=S2.POL_ID AND S2.LETTER_ID=62 AND S2.APP_TYPE='SMS' and S2.POL_STATUS=1
 LEFT JOIN #SMS S1 ON T.POL_ID=S1.POL_ID AND S1.LETTER_ID=3 AND S1.APP_TYPE='SMS' and S1.POL_STATUS=1 WHERE PAIDTODATE BETWEEN @START AND @END
 END
