
CREATE PROC [dbo].[RPT_AGENT_COMM] @ASOF_DATE DATE,@BRANCH_DATE DATE,@END_DATE DATE
AS
--	 DECLARE @ASOF_DATE	DATE = '2026-01-23'
--	 	,@BRANCH_DATE	DATE = '2026-01-01'
--	 	,@END_DATE		DATE = '2026-01-26'

	DROP TABLE IF EXISTS #AGENT
	SELECT * INTO #AGENT FROM DLKHFACT..FACT_AGENT WHERE DATE_KEY = CONVERT(VARCHAR(10),@END_DATE,112)

	SELECT  C.DATE_KEY
		, C.POL_KEY
		, C.AGENT_KEY
		, C.COV_KEY
		, C.POL_ID
		, POL_APP_FORM_ID = RTRIM(C.POL_APP_FORM_ID)
		, C.AGT_ID
		, C.AGENT_NAME
		, C.COMM_HIST_AMT
		, CASE WHEN RTRIM(CVG.INTRO_ID) != '' AND C.COM_TYPE IN ('IFYC','RFYC') THEN C.COMM_HIST_AMT/2  ELSE C.COMM_HIST_AMT END AGT_COMM_AMT
		, CASE WHEN RTRIM(CVG.INTRO_ID) != '' AND C.COM_TYPE IN ('IFYC','RFYC') THEN C.COMM_HIST_AMT/2  ELSE 0 END INTODUCER_REWARD
		, C.COMM_EFF_DT
		, C.COMM_HIST_PRCES_DT
		, C.PLAN_ID
		, PLAN_DESC = RTRIM(C.PLAN_DESC)
		,CASE 
			WHEN PMTYP.PLAN_ID = 'BES001' THEN PMTYP.ETBL_DESC_TXT 
			WHEN PMTYP.PLAN_ID IN  ('CBS001') THEN 'Single-Premium' 
             WHEN P.PLAN_ID IN ('KBE003') AND P.POL_BILL_TYP_CD = 'P' THEN 'Single Premium' 
			ELSE CASE WHEN P.PLAN_ID = 'KBE003' THEN 'Regular Premium' ELSE 'Regular Premium' END
		END AS PYM_MODE
		---------------------------------------------------------------
		, C.POL_TERM
		, C.POL_CSTAT_CD
		, POL_STAT_DESC = RTRIM(C.POL_STAT_DESC)
		, C.POL_CREAT_DT
		, C.POL_APP_CMPLT_DT
		, C.COM_PRE
		, CSC_CODE = RTRIM(C.CSC_CODE)
		, C.PRE_MODE 
		, C.POL_ACTV_TYP_ID
		, C.COM_TYPE
		, C.INITIAL_DATE
		, CASE WHEN C.PLAN_ID = 'BES001' THEN CVG.CVG_UNDSCNT_PREM ELSE C.MODAL_PRE END MODAL_PRE
		, C.CVG_ME_FCT
		, C.PRE_BEFORE
		, C.PRE_AFTER
		, AFYP = CASE WHEN P.PLAN_ID = 'KBE003' AND P.POL_BILL_TYP_CD = 'P' THEN C.AFYP * 0.1 ELSE  CASE WHEN C.PLAN_ID = 'CBS001' THEN C.AFYP * 0.1 ELSE CASE WHEN C.PLAN_ID = 'BES001' THEN CVG.CVG_UNDSCNT_PREM * (CASE WHEN CAST(P.POL_BILL_MODE_CD AS INT)>0 THEN 12/CAST(P.POL_BILL_MODE_CD AS INT) ELSE 1 END) ELSE C.AFYP END END END
		, C.GEN_ID
		, WFYP =  CASE WHEN C.PLAN_ID = 'BES001' THEN  CVG.CVG_UNDSCNT_PREM ELSE  C.WFYP END
		, ABM_ID = AGT.ABM_ID
		, ABMNAME = AGM.Name
		, AGT.OVRID_BASE_AGT_ID LCODE
		, LNAME = AGL.Name
		, PLCODE = AGT.PREV_LEAD_CODE
		, PLNAME = RTRIM(PRE_AGL.ENTR_SUR_NM) + ' ' + RTRIM(PRE_AGL.ENTR_GIV_NM)
		, PABM = AGT.PREV_ABM_CODE
		, PABMNAME = RTRIM(PRE_AGM.ENTR_SUR_NM) + ' ' + RTRIM(PRE_AGM.ENTR_GIV_NM)
		, CASE WHEN AGT.CHANNEL = 'BA' THEN ORG.ORG_CODE ELSE NULL END BANK_BRANCH_CODE 
		, CASE WHEN AGT.CHANNEL = 'BA' THEN ORG.NAME ELSE NULL END BANK_BRANCH_NAME
		, CASE WHEN AGT.CHANNEL = 'BA' THEN PN.NAME WHEN AGT.CHANNEL = 'AG' THEN AGD.SALES_OFFICE_NAME
			ELSE NULL END ORGANIZATION 
		, CVG.INTRO_ID
		, COMMISSION_SLIT = CASE WHEN RTRIM(CVG.INTRO_ID) != '' THEN '50%' ELSE '100%' END
	FROM DLKHFACT..FACT_AXP_AGENT_COMM C 
	LEFT JOIN DLKHDIM..DIM_POLICY P ON P.POL_ID = C.POL_ID AND P.POL_KEY = C.POL_KEY
	LEFT JOIN DLKHDIM..DIM_COVERAGE CVG ON CVG.POL_ID = CVG.POL_ID AND CVG.COV_KEY = C.COV_KEY
	LEFT JOIN #AGENT AGT ON C.AGT_ID = AGT.AGT_ID 
	LEFT JOIN DLKHSTAGE..SGTM_AGENT_DETAIL AGL ON AGL.AgentId = AGT.OVRID_BASE_AGT_ID
	LEFT JOIN DLKHSTAGE..SGTM_AGENT_DETAIL AGM ON AGM.AgentId = AGT.ABM_ID
	LEFT JOIN DLKHSTAGE..DMS_AGENT_DETAIL AGD ON AGD.AGENT_CODE = AGT.AGT_ID
	LEFT JOIN DLKHSTAGE..DMS_ORGANIZATION ORG ON ORG.SALE_SUPPORT LIKE CONCAT('%',C.AGT_ID,'%')
	LEFT JOIN DLKHSTAGE..DMS_PARTNER PN ON PN.CODE = ORG.PARTNER_CODE AND PN.HIERARCHICAL_MODEL = 3

	LEFT JOIN #AGENT PRE_AGL ON AGT.PREV_LEAD_CODE = PRE_AGL.AGT_ID AND PRE_AGL.AGT_CLI_REL_TYP_CD = 'M'
	LEFT JOIN #AGENT PRE_AGM ON AGT.PREV_ABM_CODE = PRE_AGM.AGT_ID AND PRE_AGM.AGT_CLI_REL_TYP_CD = 'M'

	-----RETRIEVE INFORMAITON FOR EASY CARE PREMIUM TYPE------
	LEFT JOIN 
	(	SELECT CVG.POL_ID,CVG.PLAN_ID,CVG.CVG_STBL_1_CD, ETBL_DESC_TXT = RTRIM(PS.ETBL_DESC_TXT)
		FROM DLKHSTAGE..SGTM_COVERAGE CVG
		INNER JOIN DLKHSTAGE..SGTB_EDITTABLE PS 
		ON PS.ETBL_VALU_ID = CVG.CVG_STBL_1_CD AND PS.ETBL_TYP_ID = 'STB1'
		WHERE CVG_NUM = '01'
	)PMTYP ON PMTYP.POL_ID = C.POL_ID
	--EC NO RIDER & COVER ONLY 2 YEARS PRM MODE NO CHANGE THE ENTIRE YEAR, BASE COM HIS SO ROWS DONT CHANGE CAN JOIN THE CVG TABLE AS ONE TO MANY AND NO CHANGE------

	WHERE C.DATE_KEY=CONVERT(VARCHAR,@ASOF_DATE,112)
		AND C.COMM_HIST_PRCES_DT BETWEEN CONVERT(VARCHAR,@BRANCH_DATE,112) AND CONVERT(VARCHAR,@END_DATE,112)
