
CREATE PROC [dbo].[RPT_AGENT_SUM_FA_LIVE]
AS

DROP TABLE IF EXISTS #AGT
DROP TABLE IF EXISTS #POL

SELECT * INTO #AGT FROM	DLKHSTAGE..V_GET_AGENT_BASIC_LIVE	

SELECT POL.POL_ID, POL.AGT_ID,POL.POL_MPREM_AMT 
			,CASE 
			WHEN POL.POL_BILL_MODE_CD=3 THEN POL.POL_MPREM_AMT * 4 
			WHEN POL.POL_BILL_MODE_CD=6 THEN POL.POL_MPREM_AMT * 2 
			WHEN POL.POL_BILL_MODE_CD=1 THEN POL.POL_MPREM_AMT * 12 
			WHEN POL.POL_BILL_MODE_CD=12 THEN POL.POL_MPREM_AMT
			ELSE POL.POL_MPREM_AMT END APE
		,DATEDIFF(DAY,POL.POL_APP_RECV_DT,GETDATE()) PENDING_DAYS 
INTO #POL	   
FROM OPENQUERY(UAT7,'
SELECT POL.POL_ID,CVGA.AGT_ID,POL.POL_APP_RECV_DT,POL.POL_BILL_MODE_CD,POL.POL_MPREM_AMT
FROM KCAPXUT1.TPOL POL
LEFT JOIN KCAPXUT1.TCVGA CVGA ON POL.POL_ID = CVGA.POL_ID AND CVGA.CVG_NUM=01 
WHERE POL.POL_CSTAT_CD LIKE ''P%'' 
')POL;

SELECT FA.AGT_ID
		,AGENT_NAME = RTRIM(AGT.ENTR_SUR_NM) + ' ' + RTRIM(AGT.ENTR_GIV_NM)
		,LCODE = AGL.AGT_ID
		,LNAME = RTRIM(AGL.ENTR_SUR_NM) + ' ' + RTRIM(AGL.ENTR_GIV_NM)
		,ABM_ID = AGM.AGT_ID
		,ABMNAME = RTRIM(AGM.ENTR_SUR_NM) + ' ' + RTRIM(AGM.ENTR_GIV_NM)
		,FA.PENDING
		,FA.POL_MPREM_AMT
		,FA.AFYP
		,FA.PENDING_DAYS
		,BANKNAME = RTRIM(AGB.ENTR_SUR_NM) + ' ' + RTRIM(AGB.ENTR_GIV_NM)
	FROM
	(
SELECT AGT.AGT_ID
	   ,COUNT(POL_ID) PENDING
       ,SUM(POL_MPREM_AMT) POL_MPREM_AMT
	   ,SUM(APE) AFYP
	   ,MAX(PENDING_DAYS) PENDING_DAYS
FROM #POL POL
INNER JOIN #AGT AGT ON AGT.AGT_ID = POL.AGT_ID AND AGT.AGT_DISB_CHNL = '2'
GROUP BY AGT.AGT_ID
) AS FA
	LEFT JOIN #AGT AGT ON FA.AGT_ID = AGT.AGT_ID
	LEFT JOIN #AGT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
	LEFT JOIN #AGT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
	LEFT JOIN #AGT AGB ON AGB.AGT_ID = AGM.OVRID_BASE_AGT_ID
	--ORDER BY FA.AGT_ID
