

CREATE PROC [dbo].[RPT_AGENT_SUM]
(
	@ASOF DATE
)
AS

	--DECLARE	@ASOF DATE	= '2024-06-26'
	DROP TABLE IF EXISTS #AGT

	SELECT * INTO #AGT FROM DLKHSTAGE..V_GET_AGENT_BASIC

	SELECT FA.*
		,LCODE = AGL.AGT_ID
		,LNAME = RTRIM(AGL.ENTR_SUR_NM) + ' ' + RTRIM(AGL.ENTR_GIV_NM)
		,ABM_ID = AGM.AGT_ID
		,ABMNAME = RTRIM(AGM.ENTR_SUR_NM) + ' ' + RTRIM(AGM.ENTR_GIV_NM)
		,P.POL_APP_FORM_ID
	FROM FACT_AGT_SUM FA
	LEFT JOIN DLKHSTAGE..SGTB_POLICY P ON FA.POL_ID = P.POL_ID
	LEFT JOIN #AGT AGT ON FA.AGT_ID = AGT.AGT_ID
	LEFT JOIN #AGT AGL ON AGT.OVRID_BASE_AGT_ID  = AGL.AGT_ID
	LEFT JOIN #AGT AGM ON AGL.OVRID_BASE_AGT_ID  = AGM.AGT_ID
	WHERE FA.CSC_CODE = 'AG'		-- AGENCY
		AND FA.DATE_KEY = CONVERT(VARCHAR,@ASOF,112) 
	ORDER BY POL_ID
