CREATE PROC [dbo].[RPT_ATR_MOV] @START DATE,@END DATE
AS
--	DECLARE	@START	DATE = '2025-11-01'
--			,@END	DATE = '2025-12-08'

	DROP TABLE IF EXISTS #ATR
	DROP TABLE IF EXISTS #LST
	DROP TABLE IF EXISTS #EDIT

	SELECT 
		ETBL_TYP_ID, ETBL_VALU_ID, ETBL_DESC_TXT = RTRIM(ETBL_DESC_TXT) 
	INTO #EDIT 
	FROM DLKHSTAGE..SGTB_EDITTABLE 
	WHERE CO_ID = 'CP' 
	AND ETBL_LANG_CD = 'E'
	AND ETBL_TYP_ID IN ('PLAN','OCCCD')

	SELECT ATR.*
		, CASE WHEN COALESCE(ATR.PREV_POL_BILL_MODE_CD, ATR.PRE_MODE) = '12' AND POL.POL_BILL_TYP_CD = 'P' THEN 'F'
			ELSE COALESCE(ATR.PREV_POL_BILL_MODE_CD, ATR.PRE_MODE)
		END ATR_PREV_POL_BILL_MODE_CD
		,ATR_MOV_STAT = CAST(
			CASE WHEN ATR.CVG_CSTAT_CD IN ('1','3') AND ATR.CVG_PREV_CSTAT_CD NOT IN ('B','E') AND ATR.POL_CSTAT_CD IN ('1','3') THEN 'ISSUED' 
				WHEN ATR.POL_CSTAT_CD IN ('B','E') AND ATR.POL_PREV_CSTAT_CD = '1' THEN 'LAPSED' 
				WHEN ATR.POL_CSTAT_CD = 'R' OR ATR.POL_CSTAT_CD = 'A' THEN 'CFI'  
				WHEN ATR.POL_CSTAT_CD = '2' THEN 'WAIVER'
				WHEN ATR.POL_CSTAT_CD = 'D' AND ATR.CVG_CSTAT_CD = 'D' THEN 'DTHCLM' 
				ELSE '' 
			END AS VARCHAR(255))

		--DL-955
		,CASE 
			WHEN ATR.PLAN_ID = 'BSS001' THEN RTRIM(STB1.ETBL_DESC_TXT)
			WHEN ( ATR.PLAN_ID = 'KBE003' AND CVG.CVG_STBL_1_CD IN ('P1', 'P2') ) THEN RTRIM(PLN.ETBL_DESC_TXT) + ' ' + STB1.ETBL_DESC_TXT
			ELSE RTRIM(PLN.ETBL_DESC_TXT)END PRODUCT_NAME
		,PREMIUM_TYPE = CASE
							WHEN ATR.PLAN_ID = 'KBE003' AND POL.POL_BILL_TYP_CD = 'P' THEN 'Single Pay' 
							WHEN ATR.PLAN_ID = 'KBE002' THEN 'Limited Pay' 
							WHEN ATR.PLAN_ID = 'DRD005' THEN 'Limited Pay' 
							WHEN ATR.PLAN_ID = 'CBS001' THEN 'Single Pay'
							WHEN ATR.PLAN_ID = 'BSS001' THEN CASE WHEN CVG.CVG_MAT_XPRY_DUR != CVG.PREM_PMT_DUR THEN 'Limited Pay' ELSE 'Full Pay' END
							WHEN ATR.PLAN_ID = 'BES001' THEN CASE WHEN CVG.CVG_STBL_1_CD = 'AP' THEN 'Advanced Pay' ELSE 'Regular Pay' END
							ELSE 'Regular Pay' END
		,UNDISCOUNT_PREMIUM = CASE WHEN ATR.PLAN_ID = 'BES001' THEN CVG.CVG_UNDSCNT_PREM ELSE NULL END
		,LAP.LAST_LAPSED_DATE LAST_LAPSED_DATE
		,CVG_ROP = CASE 
			WHEN CVG.CVG_STBL_2_CD = 'CRP' THEN '100ROP'
			WHEN CVG.CVG_STBL_2_CD = 'SRP' THEN '70ROP'
			ELSE NULL
		END 
	INTO #ATR
	FROM dbo.FACT_ATR ATR
	INNER JOIN DLKHDIM..DIM_POLICY POL ON ATR.POL_KEY = POL.POL_KEY
	LEFT JOIN DLKHDIM..DIM_COVERAGE CVG ON CVG.COV_KEY = ATR.COV_KEY
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE PLN ON  PLN.ETBL_TYP_ID = 'PLAN' AND ATR.PLAN_ID = PLN.ETBL_VALU_ID  
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE STB1 ON STB1.ETBL_TYP_ID = 'STB1' AND CVG.CVG_STBL_1_CD = STB1.ETBL_VALU_ID 
	-- GET LAST LAPSE DATE
	LEFT JOIN (SELECT POL_ID,CVG_NUM, MAX(MVT_TRXN_PRCES_DT) LAST_LAPSED_DATE FROM DLKHSTAGE..SGTB_MVTX WHERE MVT_TRXN_LN_NUM = '190' AND MVT_TRXN_PRCES_DT < @END GROUP BY POL_ID,CVG_NUM) LAP ON LAP.POL_ID = ATR.POL_ID AND LAP.CVG_NUM = ATR.CVG_NUM
	
	WHERE ATR.DATE_KEY BETWEEN CONVERT(VARCHAR,@START,112) AND CONVERT(VARCHAR,@END,112) 
		AND (LEFT(ATR.POL_CSTAT_CD,1) <> 'P' AND LEFT(ATR.CVG_CSTAT_CD,1) <> 'P')
		AND (LEFT(ATR.POL_CSTAT_CD,1) <> 'R' AND LEFT(ATR.POL_PREV_CSTAT_CD,1) <> 'P')
		AND NOT (ATR.POL_CSTAT_CD='1' AND ATR.CVG_CSTAT_CD IN ('R','B'))

	-- GET RECORDS MATCH TO CONDITION END DATE
	SELECT  * INTO #LST FROM #ATR F WHERE DATE_KEY = CONVERT(VARCHAR,@END,112) 

	-- DEFINE MOVEMENT STATUS

	-- TAKE OUT IF POLICY WAS ISSUED/INFORCED THAN WAS REJECTED/NOT TAKEN IN SAME MONTH 
	DELETE FROM #LST WHERE POL_CSTAT_CD IN ('A', 'R') AND DATEDIFF(MONTH, POL_INFC_DT,POL_STAT_CHNG_DT) = 0

	-- MOVEMENT: PREMIUM PAYING 
	UPDATE #LST SET ATR_MOV_STAT = 'PREMIUM PAYING'  WHERE ATR_MOV_STAT = '' AND POL_CSTAT_CD = '1' AND POL_PREV_CSTAT_CD IN ('B','E')

	-- MOVEMENT: LAPSED & PREMIUM PAYINNG IF POLICY WAS LAPSED AND REINSTATED IN SAME MONTH
	UPDATE LST SET ATR_MOV_STAT = 'LAPSED & PREMIUM PAYING' FROM #LST LST WHERE ATR_MOV_STAT = 'PREMIUM PAYING' 
		AND (
			SELECT COUNT(*) FROM #ATR ATR WHERE ATR.POL_CSTAT_CD IN ('B','E') AND ATR.POL_ID = LST.POL_ID 
			AND DATEDIFF(MONTH,ATR.POL_STAT_CHNG_DT,LST.POL_STAT_CHNG_DT) = 0
		) > 0

	UPDATE LST SET ATR_MOV_STAT = 'POLALT' 
	FROM #LST LST 
	WHERE (
		PREV_CVG_FACE_AMT IS NOT NULL  
		OR PREV_POL_BILL_MODE_CD IS NOT NULL 
		OR PREV_CLI_OCCP_CLAS_CD IS NOT NULL 
		OR PREV_PO IS NOT NULL OR PREV_CVG_MPREM_AMT IS NOT NULL
		)
		AND 
		(LST.ATR_MOV_STAT IN ('ISSUED') AND  (SELECT COUNT(1) FROM #ATR ATR WHERE DATEDIFF(MONTH,ATR.POL_STAT_CHNG_DT,LST.POL_STAT_CHNG_DT) > 0) = 0)

	-- RETURN RESULT
	SELECT MVD.DATE_KEY
		,MVD.COV_KEY
		,MVD.POL_KEY
		,MVD.CLI_KEY
		,MVD.POL_ID
		,MVD.CVG_NUM
		,MVD.PLAN_ID
		,PLAN_DESC = PLN.ETBL_DESC_TXT
		,MVD.CVG_APP_CMPLT_DT
		,MVD.CVG_ISS_EFF_DT
		,MVD.CVG_STAT_PRCES_DT
		,MVD.CVG_CSTAT_CD
		,MVD.CVG_PREV_CSTAT_CD
		,MVD.CLASS
		,MVD.CVG_FACE_AMT
		,MVD.PRE_MODE
		,MVD.INSRD_CLI_ID
		,MVD.CLI_SEX_CD
		,MVD.CLI_BTH_DT
		,MVD.CVG_MAT_XPRY_DT
		,MVD.TARGET_PREM
		,MVD.CVG_MPREM_AMT
		,MVD.POL_PD_TO_DT_NUM
		,AGE = MVD.AGE + 0
		,MVD.AGT_ID
		,MVD.CVG_ME_FCT
		,MVD.MEDICAL_LOADING_PERCENT
		,MVD.CVG_BASIC_PREM_AMT
		,MVD.POL_PREM_PAY_DUR
		,MVD.TPD_BENEFIT
		,MVD.CVG_EMR_UW_RT
		,MVD.CVG_EMR_UW1_RT
		,MVD.CVG_EMR_UW2_RT
		,MVD.CVG_EMR_UW3_RT
		,MVD.CVG_EMR_PER_MIL_LD
		,MVD.CVG_ADB_MIL_LD
		,MVD.CVG_TPD_MIL_LD
		,MVD.CVG_ATPD_MIL_LD
		,MVD.POL_BILL_MODE_CD
		,MVD.POL_CSTAT_CD
		,MVD.CLI_OCCP_CLAS_CD
		,MVD.POL_GRS_APREM_AMT
		,MVD.PO
		,MVD.POSEX
		,MVD.PODOB
		,MVD.CVG_EMR_UW4_RT
		,MVD.CVG_HLTH_MIL_LD
		,MVD.CVG_EMR_UW5_RT
		,CI_EMR = CASE WHEN MVD.PLAN_ID = 'DRD004' THEN MVD.CVG_EMR_UW5_RT ELSE 0 END
		,CI_WOP_EMR = CASE WHEN PLAN_ID = 'DRD004' THEN 0 ELSE MVD.CVG_EMR_UW5_RT END
		,CVG_FAMI_MIL_LD = ISNULL(MVD.CVG_FAMI_MIL_LD,0)
		,CI_PER_MILLE = CASE WHEN MVD.PLAN_ID = 'DRD004' THEN MVD.CVG_FAMI_MIL_LD ELSE 0 END
		,CI_PER_WOP_MILLE = CASE WHEN MVD.PLAN_ID = 'DRD004' THEN 0 ELSE MVD.CVG_FAMI_MIL_LD END
		,PREV_CVG_FACE_AMT = ISNULL(MVD.PREV_CVG_FACE_AMT,MVD.CVG_FACE_AMT)

		,PREV_POL_BILL_MODE_CD = ATR_PREV_POL_BILL_MODE_CD
		,PREV_PO = ISNULL(MVD.PREV_PO, MVD.PO)
		,PREV_CLI_OCCP_CLAS_CD = ISNULL(MVD.PREV_CLI_OCCP_CLAS_CD, MVD.CLI_OCCP_CLAS_CD)
		,MVD.INSRD_OCCP_ID
		,INSRD_OCCP_DESC = OCC.ETBL_DESC_TXT
		,MVD.PREV_CVG_MPREM_AMT
		,MVD.POL_PREV_CSTAT_CD
		,MVD.POL_STAT_CHNG_DT
		,MVD.POL_INFC_DT 
		,MVD.ATR_MOV_STAT
		--DL-955
		,MVD.PRODUCT_NAME
		,MVD.PREMIUM_TYPE
		,MVD.LAST_LAPSED_DATE
		,MVD.UNDISCOUNT_PREMIUM
		,MVD.CVG_ROP
	FROM #LST MVD
	LEFT JOIN #EDIT PLN ON MVD.PLAN_ID = PLN.ETBL_VALU_ID AND ETBL_TYP_ID = 'PLAN'
	LEFT JOIN #EDIT OCC ON MVD.INSRD_OCCP_ID = OCC.ETBL_VALU_ID AND OCC.ETBL_TYP_ID = 'OCCCD'
	WHERE MVD.CVG_STAT_PRCES_DT BETWEEN CONVERT(VARCHAR,@START,112) AND CONVERT(VARCHAR,@END,112)
