
CREATE OR ALTER PROC [dbo].[RPT_PRE_COLL] @START DATE, @END DATE, @ASOF DATE
AS

-- DECLARE @START DATE = 2026-01-01, 
-- DECLARE @END DATE = 2026-07-27, 
-- DECLARE @ASOF DATE = 2026-07-27;

	DROP TABLE IF EXISTS  #PAY1
	DROP TABLE IF EXISTS  #PAY2
	DROP TABLE IF EXISTS  #COL
	DROP TABLE IF EXISTS  #HIS
	DROP TABLE IF EXISTS  #TMP
	DROP TABLE IF EXISTS  #SMS
	DROP TABLE IF EXISTS  #TMP1
	DROP TABLE IF EXISTS  #TMP2
	DROP TABLE IF EXISTS  #AGENT

	-- GET SOME INFO OF AGENT ONLY 
	SELECT * INTO #AGENT FROM DLKHSTAGE..V_DMS_AGENT_REPORTING_LINE_LIVE


	SELECT *, ROW_NUMBER() OVER (PARTITION BY POL_ID ORDER BY PCHST_EFF_DT) ROW_NUM 
	INTO #PAY2 
	FROM DLKHSTAGE..SGTB_POLICY_CHANGE WHERE POL_ACTV_TYP_ID IN (1082) AND PCHST_STAT_CD = 'A' AND PCHST_NEW_VALU_TXT LIKE '%001%'

	SELECT *,0 ROW_NUM INTO #PAY1 FROM DLKHSTAGE..SGTB_POLICY_CHANGE  WHERE  POL_ACTV_TYP_ID IN (1084)

	INSERT INTO #PAY1
	SELECT * FROM #PAY2 WHERE ROW_NUM>1 AND PCHST_EFF_DT BETWEEN @START AND @END

	SELECT ACCT_HIST_PRCES_DT,ACCT_HIST_AMT,H.POL_ID 
	INTO #HIS 
	FROM DLKHSTAGE..SGTB_ACCOUNTING_TRANHIS H 
	INNER JOIN (
		SELECT POL_ID,MAX(ACCT_HIST_GEN_ID) MAX_ID FROM DLKHSTAGE..SGTB_ACCOUNTING_TRANHIS 
		WHERE ACCT_HIST_PRCES_DT BETWEEN @START AND @END  AND ACCT_BASE_ID='249800' AND ETL_DATE=@ASOF
		GROUP BY POL_ID
	) HH ON H.ACCT_HIST_GEN_ID=HH.MAX_ID AND H.POL_ID=HH.POL_ID WHERE ETL_DATE = @ASOF

	SELECT * INTO #COL FROM FACT_COLLECTION WHERE DATE_KEY=CONVERT(VARCHAR,@ASOF,112) AND POL_PD_TO_DT_NUM > '2018-01-01' AND POL_STAT IN ('PREMIUM PAYING','LAPSED')

	SELECT C.*
		,CAST(P.PCHST_EFF_DT AS DATE) PCHST_EFF_DT
		,CASE WHEN P.PCHST_EFF_DT IS NOT NULL THEN CAST(P.PCHST_EFF_DT AS DATE) ELSE C.POL_PD_TO_DT_NUM END PAIDTODATE
		,CAST(PREV_UPDT_TS AS DATE) PREV_UPDT_TS 
	INTO #TMP 
	FROM #COL C FULL JOIN #PAY1 P ON C.POL_ID=P.POL_ID 

	DELETE FROM #TMP WHERE DATE_KEY IS NULL
  
	SELECT T.*,ACCT_HIST_PRCES_DT,ACCT_HIST_AMT
		,CASE WHEN DATEDIFF(DAY,@ASOF,POL_PD_TO_DT_NUM)<=7 AND DATEDIFF(DAY,@ASOF,POL_PD_TO_DT_NUM)>=0 THEN  DATEDIFF(DAY,@ASOF,POL_PD_TO_DT_NUM)+1 ELSE 0 END REMIND
		,CASE WHEN POL_BILL_MODE_CD=3 THEN 'QUARTERLY' 
			WHEN POL_BILL_MODE_CD=6 THEN 'SEMI ANNUAL' 
			WHEN POL_BILL_MODE_CD=1 THEN 'MONTHLY' 
			WHEN POL_BILL_MODE_CD=12 THEN 'ANNUAL'
			ELSE POL_BILL_MODE_CD END PRE_MODE 
	INTO #TMP1
	FROM #TMP T LEFT JOIN #HIS H ON T.POL_ID=H.POL_ID AND T.PCHST_EFF_DT IS NOT NULL AND T.PREV_UPDT_TS>=H.ACCT_HIST_PRCES_DT
	WHERE PAIDTODATE BETWEEN @START AND @END OR POL_PD_TO_DT_NUM BETWEEN @START AND @END 
  

	SELECT * INTO #TMP2 
	FROM #TMP1 WHERE POL_PD_TO_DT_NUM>PAIDTODATE  AND POL_PD_TO_DT_NUM < =@END

	UPDATE #TMP2 SET PCHST_EFF_DT=NULL,PAIDTODATE=POL_PD_TO_DT_NUM,ACCT_HIST_AMT=NULL,ACCT_HIST_PRCES_DT=NULL

	SELECT DISTINCT 
		T.DATE_KEY
		,T.POL_KEY
		,T.POL_ID
		,T.POL_APP_FORM_ID
		,T.POL_STAT
		,T.PLAN_ID
		,PLAN_NAME = P_STAT.ETBL_DESC_TXT
		,T.POL_BILL_MODE_CD
		,T.CLI_NAME
		,T.CLI_PHONE2
		,T.CLI_PHONE1,EMAIL,CLI_CITY_NM_TXT
		,T.POL_PD_TO_DT_NUM,_DAY,_MONTH,_YEAR
		,T.POL_CREAT_DT,PRE_AMT
		,T.POL_PREM_SUSP_AMT
		,T.POL_OS_DISB_AMT,BANK_CASH,AGENT_NO,AGENT_LASTNAME,AGENT_FIRSTNAME,AGENT_MOBILE
		--,CSC_NAME = RTRIM(T.CSC_NAME)
		,CSC_NAME = RTRIM(A.AGENT_CHANNEL)
		,PCHST_EFF_DT,T.PAIDTODATE,ACCT_HIST_PRCES_DT,ACCT_HIST_AMT,REMIND,PRE_MODE
		,CASE WHEN T.POL_BILL_MODE_CD=1 AND ACCT_HIST_PRCES_DT IS NULL  AND DATEDIFF(DAY,T.POL_PD_TO_DT_NUM,@ASOF)>0  THEN  DBO.FULLMONTHSSEPARATION(T.POL_PD_TO_DT_NUM,@ASOF)/1 
			WHEN T.POL_BILL_MODE_CD=3 AND ACCT_HIST_PRCES_DT IS NULL  AND DATEDIFF(DAY,T.POL_PD_TO_DT_NUM,@ASOF)>0 THEN  DBO.FULLMONTHSSEPARATION(T.POL_PD_TO_DT_NUM,@ASOF)/3
			WHEN T.POL_BILL_MODE_CD=6 AND ACCT_HIST_PRCES_DT IS NULL  AND DATEDIFF(DAY,T.POL_PD_TO_DT_NUM,@ASOF)>0 THEN  DBO.FULLMONTHSSEPARATION(T.POL_PD_TO_DT_NUM,@ASOF)/6
			WHEN T.POL_BILL_MODE_CD=12 AND ACCT_HIST_PRCES_DT IS NULL  AND DATEDIFF(DAY,T.POL_PD_TO_DT_NUM,@ASOF)>0 THEN  DBO.FULLMONTHSSEPARATION(T.POL_PD_TO_DT_NUM,@ASOF)/12 
			ELSE 0 
		 END  MISSED_INSTALL
		,CASE WHEN PCHST_EFF_DT IS NULL AND DATEDIFF(DAY,T.POL_PD_TO_DT_NUM,@ASOF)>0 THEN DATEDIFF(DAY,T.POL_PD_TO_DT_NUM,@ASOF) ELSE 0 END MISSDAY
		,DATENAME(DAY,T.PAIDTODATE) _DAY1
		,DATENAME(MONTH,T.PAIDTODATE) _MONTH1
		,DATENAME(YEAR,T.PAIDTODATE) _YEAR1
		,C.CLI_SEX_CD CLI_SEX
		,A.ABM_ID
		,CONCAT(A.ABM_SURNAME,' ',A.ABM_GIVNAME) ABM_NAME
		-- DL-1771
		,AGT.LeaderId AGT_LEAD_ID
		,AGT.LeaderName AGT_LEAD_NAME
		,CASE 
		    WHEN AGT.SMALL_OFFICE IS NOT NULL AND LTRIM(RTRIM(AGT.SMALL_OFFICE)) <> ''
		    THEN AGT.SMALL_OFFICE
		    ELSE 
		        CASE 
		            WHEN AGT.CHANNEL = 'BA' THEN AGT.PARTNER_NAME 
		            WHEN AGT.CHANNEL = 'AG' THEN CONCAT(AGT.BRANCH_CODE,' - ',AGT.BRANCH_NAME) 
		        END
		END AS SMALL_OFFICE
		,SLDBR.ETBL_DESC_TXT POL_SOLD_BR_NAME
		-- from pns_pol_iss_input
		,CASE WHEN AGT.CHANNEL = 'BA' THEN AGT.BRANCH_CODE ELSE NULL END BANK_BRANCH_CODE
		,CASE WHEN AGT.CHANNEL = 'BA' THEN AGT.BRANCH_NAME  WHEN AGT.CHANNEL = 'AG' THEN 'AGENCY' ELSE NULL END BANK_BRANCH_NAME
		,CASE WHEN AGT.CHANNEL = 'BA' THEN AGT.PARTNER_NAME WHEN AGT.CHANNEL = 'AG' THEN CONCAT(AGT.BRANCH_CODE,' - ',AGT.BRANCH_NAME) ELSE NULL END ORGANIZATION
    
    -- DL-2287
    ,T.AGENT_TYPE
		-- DL-2284
		,CASE WHEN DIM_POL.POL_PREV_ANNV_DUR <> '000'
			THEN 'IFYP'
			ELSE 'RFYP'
		END AS RENEWAL_YEAR
		-- DL-2284
	 FROM 
	 (
		 SELECT * FROM #TMP1
		 UNION ALL
		 SELECT * FROM #TMP2
	 ) T 
	INNER JOIN DLKHSTAGE..SGTB_POLICY_CLIENT PC ON PC.POL_ID=T.POL_ID
	INNER JOIN DLKHSTAGE..SGTM_CLIENT C ON C.CLI_ID=PC.CLI_ID
	INNER JOIN FACT_AGENT A ON T.AGENT_NO=A.AGT_ID AND A.AGT_CLI_REL_TYP_CD='M'

	LEFT JOIN #AGENT AGT ON CAST(AGT.AGENT_CODE AS VARCHAR) = A.AGT_ID
	LEFT JOIN DLKHSTAGE..SGTB_POLICY_WRITING POLW ON T.POL_ID = POLW.POL_ID
	LEFT JOIN DLKHSTAGE..SGTM_PARA SLDBR 
		ON POLW.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID 
		AND SLDBR.ETBL_TYP_ID = 'SOLDBR' AND SLDBR.ETBL_LANG_CD = 'E'
	-- DL-1771
	-- DL-2284
	LEFT JOIN DLKHDIM..DIM_POLICY DIM_POL ON DIM_POL.POL_KEY=T.POL_KEY
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE P_STAT 
		ON T.PLAN_ID=P_STAT.ETBL_VALU_ID 
		AND P_STAT.ETBL_TYP_ID='PLAN' 
		AND P_STAT.ETBL_LANG_CD='E' 
		AND P_STAT.CO_ID='CP'
	WHERE T.PAIDTODATE >= @START AND A.DATE_KEY = CONVERT(VARCHAR,@ASOF,112)
go

