CREATE PROC [dbo].[RPT_AGENT_DETAIL] @BRANCH_DATE DATE
AS
BEGIN
IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP

SELECT * INTO #TMP FROM DLKHFACT..FACT_AGENT WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) 

SELECT DISTINCT A.AGT_ID,case when A.AGT_STAT_CD='A' then 'Active' else 'Inactive' end AGT_STAT_CD,LTRIM(RTRIM(A.ENTR_SUR_NM))+' '+LTRIM(RTRIM(A.ENTR_GIV_NM)) AGENT_NAME,A.AGENT_TITLE,A.AGT_CNTRCT_STRT_DT,A.AGT_CNTRCT_TRMN_DT,A.CLI_BTH_DT,ISNULL(A.AGT_CNTRCT_TRMN_DT,A.AGT_TITL_EFF_DT) MOVE_DATE,A.AGENT_CHANNEL,A.AGT_REF_ID,CP.CLI_CNTCT_ID_TXT AGT_PHON_NUM,A.ID_CARD,EM.CLI_CNTCT_ID_TXT EMAIL,A.ADDRESS_LN_1,A.ADDRESS_LN_2,A.ADDRESS_LN_3,
A.COMMUNE,A.DISTRICT,A.CITY,A.PREV_LEAD_CODE,LTRIM(RTRIM(PC.ENTR_SUR_NM))+' '+LTRIM(RTRIM(PC.ENTR_GIV_NM)) PREV_LEADER,A.PREV_ABM_CODE,LTRIM(RTRIM(PA.ENTR_SUR_NM))+' '+LTRIM(RTRIM(PA.ENTR_GIV_NM)) PREV_ABM,
A.OVRID_BASE_AGT_ID LEADER_CODE,LTRIM(RTRIM(L.ENTR_SUR_NM))+' '+LTRIM(RTRIM(L.ENTR_GIV_NM)) LEADER,A.ABM_ID,LTRIM(RTRIM(A.ABM_SURNAME))+' '+LTRIM(RTRIM(A.ABM_GIVNAME)) ABM_NAME
FROM #TMP A left JOIN #TMP PC ON  A.PREV_LEAD_CODE=PC.AGT_ID
LEFT JOIN #TMP PA ON  A.PREV_ABM_CODE=PA.AGT_ID
LEFT JOIN #TMP L ON  A.OVRID_BASE_AGT_ID=L.AGT_ID
Left join DLKHSTAGE..SGTM_CLIENT_CONTACT EM ON A.AGT_ID=EM.CLI_ID AND EM.CLI_CNTCT_ID_CD='EM' AND EM.CO_ID='CP' AND EM.CLI_CNTRY_ID_CD='CD'
Left join DLKHSTAGE..SGTM_CLIENT_CONTACT CP ON A.AGT_ID=CP.CLI_ID AND CP.CLI_CNTCT_ID_CD='MO' AND CP.CO_ID='CP' AND CP.CLI_CNTRY_ID_CD='CD'
END
