CREATE PROC [dbo].[RPT_AGENT_COM] @BRANCH_DATE DATE,@END_DATE DATE
AS
BEGIN
SELECT  * FROM DLKHFACT..FACT_AXP_AGENT_COM WHERE DATE_KEY BETWEEN CONVERT(VARCHAR,@BRANCH_DATE,112) AND CONVERT(VARCHAR,@END_DATE,112)
END
