CREATE proc [dbo].[RPT_ACT_MOV] @START DATE,@END DATE
as

select DISTINCT ACT.POL_ID,
ACT.CVG_NUM,
ACT.PLAN_ID,
ACT.BEN_NO,
ACT.CVG_APP_CMPLT_DT,
ACT.CVG_ISS_EFF_DT,
ACT.CVG_STAT_PRCES_DT,
ACT.CVG_CSTAT_CD,
ACT.CVG_PREV_CSTAT_CD,
ACT.CLASS,CVG_FACE_AMT,
ACT.PRE_MODE,
ACT.INSRD_CLI_ID,
ACT.CLI_SEX_CD,
ACT.CLI_BTH_DT,
(
SELECT TOP 1 TEDIT.ETBL_DESC_TXT
FROM DLKHDIM..DIM_CLIENT CLI
LEFT JOIN [DLKHSTAGE].[dbo].[SGTB_EDITTABLE] TEDIT ON CLI.OCCP_ID=TEDIT.ETBL_VALU_ID AND TEDIT.ETBL_TYP_ID='OCCCD'
WHERE CLI.CLI_ID=ACT.INSRD_CLI_ID
AND DATEDIFF(DAY,CLI.ETL_DATE,ACT.CVG_STAT_PRCES_DT)>=0
ORDER BY CLI.ETL_DATE DESC
) AS CLI_OCCUP,
ACT.POSEX,POBOD,
ACT.CVG_MAT_XPRY_DT,
ACT.TARGET_PREM,POL_GRS_APREM_AMT,
ACT.POL_PD_TO_DT_NUM,
ACT.AGE,
W.AGT_ID,CVG_ME_FCT,
ACT.MEDICAL_LOADING_PERCENT,
ACT.CVG_BASIC_PREM_AMT,
ACT.MOVE_TYPE,
ACT.TERM,
ACT.TPD_BENEFIT,LOADING_LIFE_PERCENT,LOADING_TPD_PERCENT ,LOADING_ADB_PERCENT ,
 LOADING_ATPD_PERCENT ,LOADING_LIFE_PERMILLE ,LOADING_TPD_PERMILLE ,LOADING_ADB_PERMILLE ,LOADING_ATPD_PERMILLE,CASE WHEN CVG_CSTAT_CD='B' THEN 'LP' WHEN CVG_CSTAT_CD='1' THEN 'PP' WHEN CVG_CSTAT_CD='2' THEN 'WB' ELSE '' END PAYMENT_STATUS,
CASE WHEN CVG_CSTAT_CD='B' THEN DATEADD(MONTH,CAST(BILL_MODE AS INT),CAST(POL_PD_TO_DT_NUM AS DATE)) ELSE NULL END NEXT_PREMUM_DATE
 FROM FACT_ACTURAIL ACT  INNER JOIN DLKHSTAGE..SGTB_POLICY_WRITING  W ON ACT.POL_ID=W.POL_ID
 WHERE ACT.CVG_STAT_PRCES_DT BETWEEN @START AND @END
 ORDER BY ACT.CVG_STAT_PRCES_DT
