

CREATE PROC [dbo].[RPT_AGENT_SUM_AGENT] @ASOF DATE
AS
	--DECLARE	@ASOF DATE	= '2024-06-26'
	DROP TABLE IF EXISTS #AGT

	SELECT * INTO #AGT FROM DLKHSTAGE..V_GET_AGENT_BASIC

	SELECT FA.AGT_ID
		,AGENT_NAME = RTRIM(AGT.ENTR_SUR_NM) + ' ' + RTRIM(AGT.ENTR_GIV_NM)
		,LCODE = AGL.AGT_ID
		,LNAME = RTRIM(AGL.ENTR_SUR_NM) + ' ' + RTRIM(AGL.ENTR_GIV_NM)
		,ABM_ID = AGM.AGT_ID
		,ABMNAME = RTRIM(AGM.ENTR_SUR_NM) + ' ' + RTRIM(AGM.ENTR_GIV_NM)
		,FA.#PENDING
		,FA.POL_MPREM_AMT
		,FA.AFYP
		,FA.PENDING_DAYS
	FROM
	(
		SELECT 	C.AGT_ID
			,COUNT(POL_ID) #PENDING
			,SUM(POL_MPREM_AMT) POL_MPREM_AMT
			,SUM(APE) AFYP
			,MAX(PENDING_DAYS) PENDING_DAYS
		FROM FACT_AGT_SUM C
		WHERE C.CSC_CODE = 'AG'	--	AGENCY
			AND C.DATE_KEY = CONVERT(VARCHAR,@ASOF,112)
		GROUP BY C.AGT_ID
	) AS FA
	LEFT JOIN #AGT AGT ON FA.AGT_ID = AGT.AGT_ID
	LEFT JOIN #AGT AGL ON  AGT.OVRID_BASE_AGT_ID  = AGL.AGT_ID
	LEFT JOIN #AGT AGM ON  AGL.OVRID_BASE_AGT_ID  = AGM.AGT_ID
