CREATE proc [dbo].[RPT_ACT_INFORCE] @ASOF DATE
as
select DISTINCT POL_ID,CVG_NUM,PLAN_ID,BEN_NO,CVG_APP_CMPLT_DT,CVG_ISS_EFF_DT,CVG_STAT_PRCES_DT,CVG_CSTAT_CD,CVG_PREV_CSTAT_CD,CLASS,CVG_FACE_AMT,PRE_MODE,INSRD_CLI_ID,
 CLI_SEX_CD,CLI_BTH_DT,POSEX,POBOD,CVG_MAT_XPRY_DT,TARGET_PREM,POL_GRS_APREM_AMT,POL_PD_TO_DT_NUM,AGE,AGT_ID,CVG_ME_FCT,MEDICAL_LOADING_PERCENT,CVG_BASIC_PREM_AMT,MOVE_TYPE,TERM,TPD_BENEFIT,LOADING_LIFE_PERCENT,LOADING_TPD_PERCENT ,LOADING_ADB_PERCENT ,
 LOADING_ATPD_PERCENT ,LOADING_LIFE_PERMILLE ,LOADING_TPD_PERMILLE ,LOADING_ADB_PERMILLE ,LOADING_ATPD_PERMILLE 
 ,(
SELECT TOP 1 TEDIT.ETBL_DESC_TXT
FROM DLKHDIM..DIM_CLIENT CLI
LEFT JOIN [DLKHSTAGE].[dbo].[SGTB_EDITTABLE] TEDIT ON CLI.OCCP_ID=TEDIT.ETBL_VALU_ID AND TEDIT.ETBL_TYP_ID='OCCCD'
WHERE CLI.CLI_ID=ACT.INSRD_CLI_ID
AND DATEDIFF(DAY,CLI.ETL_DATE,ACT.CVG_STAT_PRCES_DT)>=0
ORDER BY CLI.ETL_DATE DESC
) AS CLI_OCCUP,CASE WHEN POL_STATUS='B' THEN 'LP' WHEN POL_STATUS='1' THEN 'PP' WHEN POL_STATUS='2' THEN 'WB' ELSE '' END PAYMENT_STATUS,
CASE WHEN CVG_CSTAT_CD='B' THEN DATEADD(MONTH,CAST(BILL_MODE AS INT),CAST(POL_PD_TO_DT_NUM AS DATE)) ELSE NULL END NEXT_PREMUM_DATE from FACT_ACTURAIL ACT where CVG_CSTAT_CD  IN ('1','B') AND DATE_KEY=CONVERT(VARCHAR,@ASOF,112)
  ORDER BY CVG_STAT_PRCES_DT
