
CREATE PROC [dbo].[RPT_AGENT_SUM_BANK_LIVE]
AS

DROP TABLE IF EXISTS #POL
DROP TABLE IF EXISTS #TREQT
DROP TABLE IF EXISTS #AGT
DROP TABLE IF EXISTS #NON
DROP TABLE IF EXISTS #TMPX

SELECT * INTO #TREQT FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUT1.TREQT')

SELECT DISTINCT POL_CLI_ID
		,CASE 
		WHEN REQIR_ID IN ('U0193','U0194','U0195','U0196','U0197','U0198','U0199','U0200','U0201','U0202','0085','0086','0084','0097','U0207','U0208',
				'0084','0085','0086','0087','0088','0089','0090','0091','0092','0093','0094','0095','0095') 
			THEN (
					CASE WHEN CPREQ_STAT_CD IN ('CAN','WVD') THEN 'NON-ME' ELSE 'ME' END
				)  
		WHEN REQIR_ID  IN ('0098','U0209') 
			THEN (
					CASE WHEN CPREQ_STAT_CD IN ('CAN') THEN 'NON-COL' ELSE 'COL' END
				)  
		ELSE 'NON-ME' END NONJET_STATUS 
INTO #NON FROM #TREQT

SELECT * INTO #AGT FROM	DLKHSTAGE..V_GET_AGENT_BASIC_LIVE	

SELECT POL.POL_ID, POL.CVG_FACE_AMT, POL.POL_MPREM_AMT,POL.POL_GRS_APREM_AMT
	   ,POL.PLAN_ID 
	   ,CASE WHEN POL_BILL_MODE_CD = 3 THEN 'QUARTERLY' 
			WHEN POL_BILL_MODE_CD = 6 THEN 'SEMI ANNUAL' 
			WHEN POL_BILL_MODE_CD=1 THEN 'MONTH' 
			WHEN POL_BILL_MODE_CD=12 THEN 'ANNUAL'
			ELSE POL_BILL_MODE_CD END PRE_MODE
		,RTRIM(LTRIM(POL.ENTR_SUR_NM))+' '+RTRIM(LTRIM(POL.ENTR_GIV_NM)) CLIENT_NAME
		, POL.POL_APP_RECV_DT POL_CREAT_DT , POL.AGT_ID
		,CASE 
			WHEN POL.POL_BILL_MODE_CD=3 THEN POL.POL_MPREM_AMT * 4 
			WHEN POL.POL_BILL_MODE_CD=6 THEN POL.POL_MPREM_AMT * 2 
			WHEN POL.POL_BILL_MODE_CD=1 THEN POL.POL_MPREM_AMT * 12 
			WHEN POL.POL_BILL_MODE_CD=12 THEN POL.POL_MPREM_AMT
			ELSE POL.POL_MPREM_AMT END APE
		,DATEDIFF(DAY,POL.POL_APP_RECV_DT,GETDATE()) PENDING_DAYS
		,DATEADD(DAY,21,POL.POL_APP_RECV_DT) NTU
		,POL.POL_APP_FORM_ID
		,POL.POL_UW_RMRKS REMARK
		,POL.USER_ID
		
INTO #POL  
FROM OPENQUERY(UAT7,'
SELECT POL.POL_ID,CVGA.AGT_ID,POL.POL_APP_RECV_DT,POL.POL_BILL_MODE_CD,POL.POL_MPREM_AMT
	   ,POL.POL_APP_FORM_ID , SUM(CVG.CVG_SUM_INS_AMT) CVG_FACE_AMT 
	   ,POL.PLAN_ID ,POLC.POL_UW_RMRKS
	   ,POL.POL_GRS_APREM_AMT ,POLC.CLI_ID ,CLNM.ENTR_SUR_NM, CLNM.ENTR_GIV_NM
	   ,POL.POL_STAT_CHNG_DT
	   ,UWWK.USER_ID

FROM KCAPXUT1.TPOL POL
LEFT JOIN KCAPXUT1.TCVGA CVGA ON POL.POL_ID = CVGA.POL_ID AND CVGA.CVG_NUM=01 
LEFT JOIN KCAPXUT1.TCVG CVG ON POL.POL_ID = CVG.POL_ID  AND LEFT(CVG.PLAN_ID,1) IN (''K'',''C'')
LEFT JOIN KCAPXUT1.TPOLC POLC ON POLC.POL_ID = POL.POL_ID
LEFT JOIN KCAPXUT1.TCLNM CLNM ON CLNM.CLI_ID=POLC.CLI_ID
LEFT JOIN KCAPXUT1.TUWWK UWWK ON UWWK.CLI_ID = POLC.CLI_ID 

WHERE POL.POL_CSTAT_CD LIKE ''P%'' 
GROUP BY POL.POL_ID,CVGA.AGT_ID,POL.POL_APP_RECV_DT,POL.POL_BILL_MODE_CD,POL.POL_MPREM_AMT
	   ,POL.POL_APP_FORM_ID,POL.POL_GRS_APREM_AMT ,POLC.CLI_ID ,CLNM.ENTR_SUR_NM, CLNM.ENTR_GIV_NM
	   ,POL.PLAN_ID,POL_APP_RECV_DT,POL.POL_STAT_CHNG_DT,POLC.POL_UW_RMRKS,UWWK.USER_ID
')POL
--WHERE POL.POL_STAT_CHNG_DT <= '2024-03-29';

SELECT POL.POL_ID,POL.CVG_FACE_AMT,POL.POL_MPREM_AMT,POL.POL_GRS_APREM_AMT,PA.ETBL_DESC_TXT PLAN_DESC
	   ,POL.PRE_MODE,POL.CLIENT_NAME,POL.POL_CREAT_DT,POL.AGT_ID ,AGT.ENTR_SUR_NM+' '+AGT.ENTR_GIV_NM AGENT_NAME 
	   ,AGT.AGT_DISB_CHNL CSC_CODE,AGT.AGT_DISB_CHNL_DESC CSC_NAME,POL.APE,POL.PENDING_DAYS,POL.NTU, RR.REASON
	   ,CASE 
			WHEN NN.NONJET_STATUS IS NOT NULL THEN NN.NONJET_STATUS
			WHEN NN2.NONJET_STATUS IS NOT NULL THEN NN2.NONJET_STATUS
			WHEN NN3.NONJET_STATUS IS NOT NULL THEN NN3.NONJET_STATUS
			ELSE NN1.NONJET_STATUS END NONJET_STATUS
	   ,LCODE = AGL.AGT_ID
	    ,LNAME = RTRIM(AGL.ENTR_SUR_NM) + ' ' + RTRIM(AGL.ENTR_GIV_NM)
		,ABM_ID = AGM.AGT_ID
		,ABMNAME = RTRIM(AGM.ENTR_SUR_NM) + ' ' + RTRIM(AGM.ENTR_GIV_NM) 
		,POL.POL_APP_FORM_ID
		,POL.REMARK
		,POL.USER_ID
INTO #TMP
FROM #POL POL 
LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE PA ON POL.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND ETBL_LANG_CD='E' AND PA.CO_ID='CP' 
INNER JOIN #AGT AGT ON AGT.AGT_ID = POL.AGT_ID AND AGT.AGT_CLI_REL_TYP_CD ='M'  AND AGT.AGT_DISB_CHNL = '2'
LEFT JOIN #AGT AGL ON CASE WHEN AGT.AGT_DISB_CHNL IN ('3','4') AND AGT.OVRID_BASE_AGT_ID IN ('100010','100009') THEN '100000' ELSE AGT.OVRID_BASE_AGT_ID END = AGL.AGT_ID
LEFT JOIN #AGT AGM ON CASE WHEN AGL.OVRID_BASE_AGT_ID IN ('100010','100009') THEN AGL.AGT_ID ELSE AGL.OVRID_BASE_AGT_ID END = AGM.AGT_ID
LEFT JOIN #NON NN ON POL.POL_ID=NN.POL_CLI_ID AND NN.NONJET_STATUS='ME'
LEFT JOIN #NON NN1 ON POL.POL_ID=NN1.POL_CLI_ID AND NN1.NONJET_STATUS='NON-ME'
LEFT JOIN #NON NN2 ON POL.POL_ID=NN2.POL_CLI_ID AND NN2.NONJET_STATUS='COL'
LEFT JOIN #NON NN3 ON POL.POL_ID=NN3.POL_CLI_ID AND NN3.NONJET_STATUS='NON-COL'
LEFT JOIN (SELECT POL_CLI_ID,
	  STUFF((SELECT DISTINCT ', ' + LTRIM(RTRIM(RMRKS))
			   FROM #TREQT T2
			   WHERE T2.POL_CLI_ID = T1.POL_CLI_ID
			   FOR XML PATH('')),1,1,'') REASON
	FROM #TREQT T1
	GROUP BY POL_CLI_ID) RR ON POL.POL_ID=RR.POL_CLI_ID

UPDATE #TMP SET NONJET_STATUS='COL+ME'  WHERE POL_ID IN (SELECT N.POL_CLI_ID FROM #NON N INNER JOIN #NON N1 ON N.POL_CLI_ID=N1.POL_CLI_ID AND N.NONJET_STATUS='COL' AND N1.NONJET_STATUS='ME')

SELECT * FROM #TMP TMP
