
-- =============================================
CREATE FUNCTION [dbo].[FN_GET_NOSTRO_ACCOUNT]
(	
@REPORT_DATE AS DATE
)
RETURNS TABLE 
AS
RETURN 
(
SELECT AC.BRANCH_CODE,CUS.CUSTOMER_NO,CUST_AC_NO,CUS.FULL_NAME,AC_DESC,ACCOUNT_CLASS,CCY,CASE WHEN ACY_CUR_BAL<0 THEN 'D' ELSE 'C' END AC_STMT_TYPE,ACC_STATUS,ACY_CUR_BAL,LCY_CUR_BAL 
FROM FACT_DAILY_AC_BAL BAL INNER JOIN DIM_CUST_ACCOUNT AC ON AC.ACCOUNT_KEY=BAL.ACCOUNT_KEY
INNER JOIN DIM_CUSTOMER CUS ON BAL.CUSTOMER_KEY=CUS.CUSTOMER_KEY
 WHERE DATE_KEY=CONVERT(VARCHAR,@REPORT_DATE,112) AND ACCOUNT_CLASS='NOSTRO'
)
