-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [dbo].[FN_GET_NBC_COA_BAL]
(
	@FIN_PERIOD AS INT
)
RETURNS 
@TB_RESULT TABLE 
(
	NBC_CODE VARCHAR(10),
	CURRENCY VARCHAR(5),
	CBANK_LINE_CR VARCHAR(10),
	CCY VARCHAR(5),
	AC_NO VARCHAR(10),
	LCY_BAL NUMERIC(22,8),LEAF VARCHAR(1)
)
AS
BEGIN
	INSERT INTO @TB_RESULT
	SELECT 
				X.*
	FROM 
	(
			
SELECT
				LEFT(CBANK_LINE_CR,4)NBC_CODE,BBCSTAGE.DBO.FN_GET_NBC_CCY_NO(cu.CCY_CODE,RIGHT(M.CBANK_LINE_CR,2))CURRENCY,
				CBANK_LINE_CR,CU.CCY_CODE,GL_CODE,
				SUM(CLO_LCY_BAL) CLO_LCY_BAL,B.LEAF 
			FROM BBCDW..FACT_DAILY_GL_BAL B 
			INNER JOIN BBCDW..DIM_GLMASTER M ON B.GL_KEY=M.GL_KEY and IS_CURRENT=1
			INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=B.CCY_KEY
			WHERE DATE_KEY=@FIN_PERIOD
			GROUP BY CBANK_LINE_CR,CCY_CODE,GL_CODE,B.LEAF
			 
	) X
	
	RETURN 
END
