CREATE PROC [dbo].[RPT_CUST_PORTFOLIO_COUNT] @BRANCH_DATE DATE
AS
BEGIN
 IF OBJECT_ID('tempdb..#tmp') IS NOT NULL
  DROP TABLE #tmp
SELECT distinct 'aActive CIF' CIF,RELATIONSHIP_MANAGER,CIF COUNT into #tmp FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) 
select CIF,RELATIONSHIP_MANAGER,COUNT(CIF) Count from #tmp group by RELATIONSHIP_MANAGER,CIF
UNION ALL
SELECT 'bACCOUNT OPEN' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='O' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'cACCOUNT USD' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='O' AND CCY='USD' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'dACCOUNT KHR' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='O' AND CCY='KHR' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'eACCOUNT EUR' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='O' AND CCY='EUR' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'fACCOUNT THB' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='O' AND CCY='THB' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'gACCOUNT CLOSE' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='C' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'hACCOUNT USD' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='C' AND CCY='USD' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'iACCOUNT KHR' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='C' AND CCY='KHR' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'jACCOUNT EUR' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='C' AND CCY='EUR' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER
UNION ALL
SELECT 'kACCOUNT THB' ACCOUNT,RELATIONSHIP_MANAGER,COUNT(ACCOUNT_NUMBER) FROM FACT_CUSTOMER_PORTFOLIO WHERE ACCOUNT_CLASS NOT IN ('NOSTRO','INTERN') AND RECORD_STAT='C' AND CCY='THB' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)  GROUP BY RELATIONSHIP_MANAGER

END
