create PROC [dbo].[RPT_DAILY_GL_DETAIL_OLD] @START_DATE DATE,@END_DATE DATE
AS

		 IF OBJECT_ID('tempdb..#TZGLE') IS NOT NULL
  DROP TABLE #TZGLE
  	 IF OBJECT_ID('tempdb..#TZGLE1') IS NOT NULL
  DROP TABLE #TZGLE1
  	 IF OBJECT_ID('tempdb..#VE') IS NOT NULL
  DROP TABLE #VE

Select  
'02' as RPT_CD
,TACTH.ACCT_CRCY_CD
,TACTH.ACCT_HIST_PRCES_DT as ACCT_HIST_PRCES_DT
,TACTH.ACCT_BASE_ID
,TACTH.ACCT_YR as ACCT_YR
,TACTH.ACCT_SBSDRY_CO_ID
,TACTH.ACCT_PLAN_ID
,TACTH.BR_OR_DEPT_ID
,TACTH.ACCT_ISS_LOC_CD
,TACTH.ACCT_CRNT_LOC_CD
,TACTH.ACCT_ISS_LOC_CD as ACCT_ISS_LOC_CD1
,(case when ISNULL(TACTH.ACCT_DESC_TXT,'')<>'' then ISNULL(TACTH.ACCT_DESC_TXT,'')
 else
	case when ISNULL(TACTD.ACCT_DESC_TXT,'')<>'' then ISNULL(TACTD.ACCT_DESC_TXT,'') 
	else
		case when ISNULL(TACTD1.ACCT_DESC_TXT,'')<>'' then ISNULL(TACTD1.ACCT_DESC_TXT,'') 		
		else 
			case when ISNULL(TACTD2.ACCT_DESC_TXT,'') <>'' then ISNULL(TACTD2.ACCT_DESC_TXT,'') 
			else
				ISNULL(TACTD3.ACCT_DESC_TXT,'') 
			end 
		end 
	End
end
	) as ACCT_DESC_TXT 
,TACTH.CHQ_VCHR_ID
,TACTH.USER_ID,
pp.POL_MPREM_AMT*(CASE WHEN CAST(PP.POL_BILL_MODE_CD AS INT)>0 THEN 12/CAST(PP.POL_BILL_MODE_CD AS INT)
ELSE 1 END) ANUAL_PREM
,TACTH.ACCT_HIST_GR_TS as ACCT_HIST_GR_DT
,ACCT_HIST_GR_TS
,TACTH.POL_ID as POL_ID
,RTRIM(LTRIM(I.ENTR_SUR_NM))+' '+RTRIM(LTRIM(I.ENTR_GIV_NM)) POL_NAME
,TACTH.POL_PLAN_ID as POL_PLAN_ID
,CASE WHEN PP.POL_CSTAT_CD='1' THEN 'ACTIVE' ELSE 'CANCEL' END POL_PLAN_NAME,
PP.POL_APP_FORM_ID
,0 SUM_ASSURE
,w.AGT_ID as ENTRY_AGT_ID
,A.ENTR_SUR_NM+' '+A.ENTR_GIV_NM  ENTRY_AGT_NAME
,A.CHANNEL CSC_NAME
,POL_APP_CMPLT_DT
,CASE WHEN POL_BILL_MODE_CD=3 THEN
'Quarterly' WHEN POL_BILL_MODE_CD=6 THEN 'Semi Annual' WHEN POL_BILL_MODE_CD=1 THEN 'Month' WHEN POL_BILL_MODE_CD=12 THEN 'Annual'
ELSE POL_BILL_MODE_CD END PRE_MODE
,dbo.[ConvertDate](POL_PD_TO_DT_NUM) POL_PD_TO_DT_NUM
,TACTH.CHQ_ID
,TACTH.ACCT_HIST_SRC_CD 
,(Case when TACTH.ACCT_HIST_AMT>0 then TACTH.ACCT_HIST_AMT else 0 end) as ACCT_HIST_AMT
,(Case when TACTH.ACCT_HIST_AMT<0 then TACTH.ACCT_HIST_AMT else 0 end) as ACCT_HIST_AMT_A
,TACTH.ACCT_SUB_TYP_CD as ACCT_SUB_TYP_CD
,TACTH.ACCT_HIST_BTCH_NUM
,TACTH.BUS_FCN_ID as BUS_FCN_ID
,TACTH.BPF_ID as BPF_ID
, TACTH.ACCT_DESC_TXT ACCT_DESC_TXT_1
, 0 COMM_HIST_AMT
, 0 AGT_CPREM_AMT
, TTBL_VALU_TXT ACCT_SUN_ID
,PP.POL_MPREM_AMT
,pp.POL_ISS_EFF_DT
, '' ACCT_PRD_CD
, ''  FUND_CD
, ''  AGT_ID
,PA.ETBL_DESC_TXT PLANNAME,ACCT_HIST_GEN_ID,MET.ETBL_DESC_TXT METHOD,P.CVG_MAT_XPRY_DUR TERM,PP.POL_ISS_EFF_DT POL_APP_RECV_DT,PARA.DM_AV_DESC_TXT POL_STAT INTO #TZGLE
From 
SGTB_ACCOUNTING_TRANHIS TACTH
Left join SGTM_TTTAB TZGLM On TACTH.ACCT_BASE_ID=TZGLM.ETBL_VALU_ID 
Left join SGTM_ACCOUNTDESC TACTD On TACTH.CO_ID = TACTD.CO_ID AND (TACTH.ACCT_BASE_ID = TACTD.ACCT_DESC_ID) And TACTH.ACCT_DESC_REASN_CD = TACTD.ACCT_DESC_REASN_CD AND TACTD.ACCT_DESC_LANG_CD='E'
Left join SGTM_ACCOUNTDESC TACTD1 On TACTH.CO_ID = TACTD1.CO_ID AND(TACTH.ACCT_BASE_ID = TACTD1.ACCT_DESC_ID) And ISNULL(TACTD1.ACCT_DESC_REASN_CD,'')='' And TACTD.ACCT_DESC_REASN_CD is null AND TACTD1.ACCT_DESC_LANG_CD='E'
Left join SGTM_ACCOUNTDESC TACTD2 On TACTH.CO_ID = TACTD2.CO_ID AND TACTD2.ACCT_DESC_ID=CONCAT(left(TACTH.ACCT_BASE_ID,1),'00000') And TACTH.ACCT_DESC_REASN_CD = TACTD2.ACCT_DESC_REASN_CD And TACTD.ACCT_DESC_REASN_CD is null And TACTD1.ACCT_DESC_REASN_CD is null AND TACTD2.ACCT_DESC_LANG_CD='E'
Left join SGTM_ACCOUNTDESC TACTD3 On TACTH.CO_ID = TACTD3.CO_ID AND TACTD3.ACCT_DESC_ID=CONCAT(left(TACTH.ACCT_BASE_ID,1),'00000') And ISNULL(TACTD3.ACCT_DESC_REASN_CD,'')='' And TACTD.ACCT_DESC_REASN_CD is null And TACTD1.ACCT_DESC_REASN_CD is null And TACTD2.ACCT_DESC_REASN_CD is null AND TACTD3.ACCT_DESC_LANG_CD='E'
left join SGTB_POLICY_WRITING W on TACTH.POL_ID=W.POL_ID
inner join SGTB_POLICY_CLIENT C on C.POL_ID=TACTH.POL_ID 
inner join DLKHDIM..DIM_CLIENT_IND I on I.CLI_ID=C.CLI_ID AND I.IS_CURRENT=1
INNER JOIN (SELECT POL_ID,CVG_MAT_XPRY_DUR FROM SGTM_COVERAGE GROUP BY POL_ID,CVG_MAT_XPRY_DUR) P ON P.POL_ID=TACTH.POL_ID
INNER JOIN SGTB_POLICY PP ON PP.POL_ID=P.POL_ID
LEFT JOIN SGTB_EDITTABLE PA ON TACTH.POL_PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
LEFT JOIN SGTM_PARA_1 PARA ON PP.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
LEFT JOIN SGTB_EDITTABLE MET ON MET.ETBL_LANG_CD='E' AND MET.ETBL_TYP_ID='COMTH' AND  PP.COLCT_MTHD_CD=MET.ETBL_VALU_ID AND MET.CO_ID='CP'
LEFT JOIN V_AGENT A ON W.AGT_ID=A.AGT_ID
Where TACTH.CO_ID = 'CP' 
  AND TACTH.ACCT_HIST_PST_DT BETWEEN @START_DATE AND @END_DATE and TACTH.ETL_DATE=@END_DATE
 order by TACTH.ACCT_BASE_ID

  Select 
RPT_CD
,ACCT_CRCY_CD
,ACCT_HIST_PRCES_DT
,ACCT_BASE_ID
,ACCT_YR
,ACCT_SBSDRY_CO_ID
,ACCT_PLAN_ID
,BR_OR_DEPT_ID
,ACCT_ISS_LOC_CD
,ACCT_CRNT_LOC_CD
,ACCT_DESC_TXT
,CHQ_VCHR_ID
,USER_ID
,ANUAL_PREM
,ACCT_HIST_GR_DT
,POL_ID
,POL_PD_TO_DT_NUM
,POL_NAME
,POL_PLAN_ID
,POL_PLAN_NAME
,POL_APP_FORM_ID
,SUM_ASSURE
,PRE_MODE
,ENTRY_AGT_ID
,ENTRY_AGT_NAME
,CSC_NAME,POL_APP_CMPLT_DT
,CHQ_ID
,ACCT_HIST_SRC_CD
,ACCT_HIST_AMT
,ACCT_HIST_AMT_A
,ACCT_SUB_TYP_CD
,ACCT_HIST_BTCH_NUM
,BUS_FCN_ID
,ACCT_DESC_TXT_1
,COMM_HIST_AMT
,AGT_CPREM_AMT
,ACCT_SUN_ID
,POL_MPREM_AMT
,POL_ISS_EFF_DT
,ACCT_PRD_CD
,FUND_CD
,AGT_ID
,PLANNAME,ACCT_HIST_GEN_ID,METHOD,TERM,POL_APP_RECV_DT,POL_STAT INTO #TZGLE1
FROM #TZGLE
WHERE NOT (ACCT_BASE_ID LIKE '3S10_0'
       AND ACCT_DESC_TXT = 'SFG ACCT - ADD PR')

Select 
CO_ID, POL_ID INTO #VE
FROM DLKHDIM..DIM_POLICY 
WHERE CO_ID = 'CP' 
AND POL_BUS_CLAS_CD = 'L' 
AND POL_PREM_TYP_CD = 'B' and IS_CURRENT=1

SELECT  distinct
@END_DATE AS TRXN_PRCES_DT
,'POL' AS TYPE
,A.ACCT_HIST_PRCES_DT
,A.ACCT_BASE_ID
,A.ACCT_DESC_TXT
,A.USER_ID
,A.ACCT_HIST_GR_DT
,A.POL_ID
,ANUAL_PREM
,POL_PD_TO_DT_NUM
,POL_NAME
,POL_PLAN_ID
,POL_APP_CMPLT_DT
,POL_PLAN_NAME
,POL_APP_FORM_ID
,SUM_ASSURE
,PRE_MODE
,ENTRY_AGT_ID
,ENTRY_AGT_NAME
,A.CSC_NAME
--,CASE WHEN (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) >= 0 Then (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) 
,CASE WHEN (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) >= 0 Then (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) 
 else 0 
 End as ACCT_HIST_AMT
--,CASE WHEN (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) <  0 Then (ACCT_HIST_AMT + BIGINT(ACCT_HIST_AMT_A)) 
,CASE WHEN (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) <  0 Then (ACCT_HIST_AMT + CAST(ACCT_HIST_AMT_A AS DECIMAL(15,2))) 
 else 0 
 End as ACCT_HIST_AMT_A
,A.ACCT_SUN_ID
,A.POL_MPREM_AMT
,POL_ISS_EFF_DT
,A.ACCT_PRD_CD
,A.FUND_CD
,D.ETBL_DESC_TXT CSC_CODE
,ISNULL(FC.COLCT_RCPT_NUM,FCC.COLCT_RCPT_NUM) RECPT_ID,A.PLANNAME,ISNULL(FC.COLCT_REMARK,FCC.COLCT_REMARK) PAYMENT_TYPE, ISNULL(FC.COLLEC_SRCE,FCC.COLLEC_SRCE)  BNK_BR_NM,ISNULL(FC.COLCT_ACCT_NUM,FCC.COLCT_ACCT_NUM) PAYE_BNK_ACCT_ID,
PPC.PCHST_EFF_DT INITIAL_DATE,PPCC.PCHST_EFF_DT LAST_PAY_DT,CASE WHEN DATEDIFF(DAY,A.POL_ISS_EFF_DT,PPCC.PCHST_EFF_DT)>=365 THEN 'RYP' ELSE 'FYP' END STATUS1,CASE WHEN POL_APP_CMPLT_DT<@START_DATE AND POL_STAT='PREMIUM PAYING' THEN 'INFORCE' WHEN POL_STAT='PREMIUM PAYING' THEN 'NEW BUS' ELSE '' END MODE
,METHOD,TERM,ACCT_HIST_GEN_ID,POL_APP_RECV_DT
FROM #TZGLE1 A 
LEFT JOIN #VE VE ON VE.CO_ID = 'CP' AND VE.POL_ID = A.POL_ID
LEFT JOIN V_AGENT B ON A.ENTRY_AGT_ID = B.AGT_ID
--LEFT JOIN #CASH CS ON A.POL_ID=CS.POL_ID
--LEFT JOIN SGTM_PARA_1 PARA ON CS.PMT_TYP_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='ZCTX-PMT-TYP-CD'
--LEFT JOIN SGTM_PARA_1 PARA1 ON A.POL_COLCT_MTHD_CD=PARA1.DM_AV_CD AND PARA1.DM_AV_TBL_CD='POL-COLCT-MTHD-CD'   
LEFT JOIN (SELECT POL_ID,MIN(PCHST_EFF_DT) PCHST_EFF_DT FROM SGTB_POLICY_CHANGE PPC WHERE PPC.PCHST_STAT_CD='A' AND PPC.POL_ACTV_TYP_ID='1082' AND CAST(PCHST_EFF_DT AS DATE)<=@END_DATE GROUP BY POL_ID) PPC ON A.POL_ID=PPC.POL_ID 
LEFT JOIN (SELECT POL_ID,MAX(PCHST_EFF_DT) PCHST_EFF_DT FROM SGTB_POLICY_CHANGE PPC WHERE PPC.PCHST_STAT_CD='A' AND PPC.POL_ACTV_TYP_ID IN ('1082','1084') AND CAST(PCHST_EFF_DT AS DATE)<=@END_DATE GROUP BY POL_ID) PPCC ON A.POL_ID=PPCC.POL_ID 
--LEFT JOIN [FCOLLECTION](@END_DATE) FC ON A.ACCT_HIST_PRCES_DT=FC.COLCT_EFF_DT AND A.POL_ID=FC.POL_ID
LEFT JOIN [FCOLLECTION](@END_DATE) FC ON A.ACCT_HIST_PRCES_DT=FC.COLCT_EFF_DT AND A.POL_ID=FC.POL_ID AND A.ACCT_HIST_AMT=COLCT_TOT_AMT 
LEFT JOIN [FCOLLECTION](@END_DATE) FCC ON A.ACCT_HIST_PRCES_DT=FCC.COLCT_EFF_DT AND A.POL_ID=FCC.POL_ID AND A.ACCT_HIST_AMT_A=(FCC.COLCT_TOT_AMT*-1)
LEFT JOIN SGTB_EDITTABLE D ON B.AGT_DISB_CHNL=D.ETBL_VALU_ID AND D.ETBL_TYP_ID='DCHNL' AND D.ETBL_LANG_CD='E' AND D.CO_ID='CP'
WHERE (A.ACCT_SUN_ID NOT IN ('2261010', '5511100', '5512100') Or A.ACCT_BASE_ID in ('361010','361020','3B1020','3B1120'))   
	AND (LEFT(A.ACCT_BASE_ID,2) <> 'FX' OR VE.POL_ID IS NULL)
;
