CREATE PROC [dbo].[RPT_OD_OVERVIEW] @FROM_DATE1 DATE,@TO_DATE1 DATE,@CUST_NO1 VARCHAR(400) AS
BEGIN
declare @cust_no int=@CUST_NO1
declare @FROM_DATE date=@FROM_DATE1
declare @TO_DATE date=@TO_DATE1
declare @END DATE=@TO_DATE
IF OBJECT_ID('tempdb..#Overview') IS NOT NULL
  DROP TABLE #Overview
IF OBJECT_ID('tempdb..#Overview1') IS NOT NULL
  DROP TABLE #Overview1
IF OBJECT_ID('tempdb..#turnC') IS NOT NULL
  DROP TABLE #turnC
IF OBJECT_ID('tempdb..#turnD') IS NOT NULL
  DROP TABLE #turnD
create table #Overview(Year int,NUM_MONTH INT,Month varchar(max),Average_Balance money,Authorized_Overdraft money,DayOD int,DayOVER int,MIN_BAL MONEY,MAX_BAL MONEY)
create table #turnC(Year int, Month VARCHAR(500),Num_Trn int, Balance money, DRCR varchar(100),Account varchar(500))
create table #turnD(Year int, Month VARCHAR(500),Num_Trn int, Balance money, DRCR varchar(100),Account varchar(500))
while YEAR(@FROM_DATE)<=YEAR(@END)
begin
	while @FROM_DATE<=@END
	begin
set @FROM_DATE =(select dateadd(d,-1,dateadd(mm,datediff(m,0,@FROM_DATE),1 )))
set @TO_DATE = (select dateadd(d,-1,dateadd(mm,datediff(m,0,@FROM_DATE)+1,0)))
IF OBJECT_ID('tempdb..#AVG') IS NOT NULL
  DROP TABLE #AVG
IF OBJECT_ID('tempdb..#AVGG') IS NOT NULL
  DROP TABLE #AVGG
IF OBJECT_ID('tempdb..#AVG1') IS NOT NULL
  DROP TABLE #AVG1
IF OBJECT_ID('tempdb..#AVG11') IS NOT NULL
  DROP TABLE #AVG11
IF OBJECT_ID('tempdb..#AVG2') IS NOT NULL
  DROP TABLE #AVG2
IF OBJECT_ID('tempdb..#CR') IS NOT NULL
  DROP TABLE #CR
IF OBJECT_ID('tempdb..#DR') IS NOT NULL
  DROP TABLE #DR
IF OBJECT_ID('tempdb..#C') IS NOT NULL
  DROP TABLE #C
IF OBJECT_ID('tempdb..#D') IS NOT NULL
  DROP TABLE #D
IF OBJECT_ID('tempdb..#tmp') IS NOT NULL
  DROP TABLE #tmp
IF OBJECT_ID('tempdb..#tmp1') IS NOT NULL
  DROP TABLE #tmp1
create table #tmp1 (month int,startdate date)
select * into #tmp from BBCDW..DIM_HOLIDAY where BRANCH_CODE='001' and YEAR = (YEAR(@FROM_DATE)) and MONTH=DATEPART(m, @FROM_DATE)

declare @min_month int=1

while @min_month<=12
begin
declare @max int = (select LEN(holiday_list) from #tmp where branch_code='001' and month=@min_month)
declare @min int=1
while @min<=@max
begin
insert into #tmp1
select @min_month,(select 
case when SUBSTRING(holiday_list,@min,1)='W' then null else
CONVERT(date,cast(CONCAT(Year,RIGHT('00'+ cast(MONTH as varchar),2),right('00'+cast(@min as varchar),2)) as varchar),112) end from #tmp where MONTH=@min_month and branch_code='001')

set @min=@min+1
end
set @min_month=@min_month+1
end

delete from #tmp1 where startdate is null
alter table #tmp1
add ID int identity(1,1)

SELECT bal.DATE_KEY,CUSTOMER_NO,
 LCY_CUR_BAL  LCY_BALANCE,
 ACY_CUR_BAL  FCY_BALANCE,max(fac.COLLATERAL_CONTRIBUTION) APPROVE_AMOUNT
 into #AVG FROM BBCDW..FACT_DAILY_AC_BAL BAL 
INNER JOIN BBCDW..DIM_CUSTOMER AC ON BAL.CUSTOMER_KEY=AC.CUSTOMER_KEY and DATE_KEY between CONVERT(VARCHAR,@FROM_DATE,112) and CONVERT(VARCHAR,@TO_DATE,112)
left JOIN BBCDW..FACT_CUST_ACCOUNT_LINKAGES LINK ON LINK.ACCOUNT_KEY=BAL.ACCOUNT_KEY AND  LINK.DATE_KEY between CONVERT(VARCHAR,@FROM_DATE,112) and CONVERT(VARCHAR,@TO_DATE,112)
left JOIN BBCDW..FACT_DAILY_FACILITY FAC ON CONCAT(FAC.LINE_CODE,FAC.LINE_SERIAL)=CONCAT(LINK.LINE_CODE,LINK.LINE_SERIAL) AND FAC.DATE_KEY between CONVERT(VARCHAR,@FROM_DATE,112) and CONVERT(VARCHAR,@TO_DATE,112)
where CUSTOMER_NO=@cust_no
GROUP BY CUSTOMER_NO,LCY_CUR_BAL,ACY_CUR_BAL,bal.DATE_KEY 

declare @countmin int=1
while @countmin<=(select count(*) from #tmp1)
begin

INSERT INTO #AVG
SELECT DATE_KEY+1,CUSTOMER_NO,LCY_BALANCE,FCY_BALANCE,APPROVE_AMOUNT FROM #AVG WHERE DATEADD(day,1,CAST(CONVERT(VARCHAR,(DATE_KEY),112) AS DATE)) IN (select startdate from #tmp1 where ID=@countmin and startdate not in ('2017-12-30'))		

set @countmin=@countmin+1
end

--INSERT INTO #AVG
--SELECT DATE_KEY+1,CUSTOMER_NO,LCY_BALANCE,FCY_BALANCE,APPROVE_AMOUNT FROM #AVG WHERE DATEADD(day,1,CAST(CONVERT(VARCHAR,(DATE_KEY),112) AS DATE)) IN (select startdate from #tmp1)
--INSERT INTO #AVG
--SELECT DATE_KEY+1,CUSTOMER_NO,LCY_BALANCE,FCY_BALANCE,APPROVE_AMOUNT FROM #AVG WHERE DATEADD(day,1,CAST(CONVERT(VARCHAR,(DATE_KEY),112) AS DATE)) IN (select startdate from #tmp1)
--AND CAST(CONVERT(VARCHAR,(DATE_KEY),112) AS DATE)  IN (select startdate from #tmp1)
--INSERT INTO #AVG
--SELECT DATE_KEY+1,CUSTOMER_NO,LCY_BALANCE,FCY_BALANCE,APPROVE_AMOUNT FROM #AVG WHERE DATEADD(day,1,CAST(CONVERT(VARCHAR,(DATE_KEY),112) AS DATE)) IN (select startdate from #tmp1)
--AND DATEADD(day,-1,CAST(CONVERT(VARCHAR,(DATE_KEY),112) AS DATE))  IN (select startdate from #tmp1)

if datediff(day,@FROM_DATE,(select CAST(CONVERT(VARCHAR,min(DATE_KEY),112) AS DATE) from #AVG))>0
begin
DECLARE @SUB_DATE INT=(SELECT MAX(DATE_KEY) FROM BBCDW..FACT_DAILY_AC_BAL WHERE DATEPART(M,CAST(CONVERT(VARCHAR,DATE_KEY,112) AS DATE))=DATEPART(M,DATEADD(MONTH,-1,@TO_DATE)))
DECLARE @COUNT INT=1
DECLARE @BAL INT=datediff(day,@FROM_DATE,(select CAST(CONVERT(VARCHAR,min(DATE_KEY),112) AS DATE) from #AVG))
DECLARE @MIND INT=(SELECT MIN(DATE_KEY) FROM #AVG)

WHILE @COUNT<=@BAL
BEGIN
insert into #AVG
SELECT @MIND-@COUNT,CUSTOMER_NO,
 LCY_CUR_BAL  LCY_BALANCE,
 ACY_CUR_BAL  FCY_BALANCE,(SELECT MAX(APPROVE_AMOUNT) FROM #AVG) APPROVE_AMOUNT
  FROM BBCDW..FACT_DAILY_AC_BAL BAL 
INNER JOIN BBCDW..DIM_CUSTOMER AC ON BAL.CUSTOMER_KEY=AC.CUSTOMER_KEY and DATE_KEY=@SUB_DATE
left JOIN BBCDW..FACT_CUST_ACCOUNT_LINKAGES LINK ON LINK.ACCOUNT_KEY=BAL.ACCOUNT_KEY AND  LINK.DATE_KEY=@SUB_DATE
left JOIN BBCDW..FACT_DAILY_FACILITY FAC ON CONCAT(FAC.LINE_CODE,FAC.LINE_SERIAL)=CONCAT(LINK.LINE_CODE,LINK.LINE_SERIAL) AND FAC.DATE_KEY=@SUB_DATE
where CUSTOMER_NO=@cust_no
GROUP BY CUSTOMER_NO,LCY_CUR_BAL,ACY_CUR_BAL
SET @COUNT = @COUNT+1
END
end

UPDATE #AVG SET APPROVE_AMOUNT=(SELECT MAX(APPROVE_AMOUNT) FROM #AVG)

select CAST(CONVERT(VARCHAR,(DATE_KEY),112) AS DATE) DATE_KEY,CUSTOMER_NO,SUM(LCY_BALANCE)LCY_BALANCE,SUM(FCY_BALANCE)FCY_BALANCE,APPROVE_AMOUNT INTO #AVGG from #AVG
GROUP BY DATE_KEY,CUSTOMER_NO,APPROVE_AMOUNT order by DATE_KEY

SELECT DATE_KEY,APPROVE_AMOUNT,(select AVG(LCY_BALANCE) FROM #AVGG) LCY_AVG,(select AVG(FCY_BALANCE) FROM #AVGG) FCY_AVG,
(SELECT COUNT(*) FROM #AVGG WHERE LCY_BALANCE<0) OD,(SELECT COUNT(*) FROM #AVGG WHERE (LCY_BALANCE*-1)>APPROVE_AMOUNT) ODOVER,(SELECT MIN(LCY_BALANCE) FROM #AVGG) MIN_BAL,(SELECT MAX(LCY_BALANCE) FROM #AVGG) MAX_BAL INTO #AVG2 FROM #AVGG

--update #AVGG set DATE_KEY=DATEADD(day,1,DATE_KEY) where DATEADD(day,1,DATE_KEY) in (select startdate from #tmp1 where DATENAME(WEEKDAY,startdate) not in ('Saturday','Sunday'))
--update #AVGG set DATE_KEY=DATEADD(day,1,DATE_KEY) where DATEADD(day,1,DATE_KEY) in (select startdate from #tmp1 where DATENAME(WEEKDAY,startdate) not in ('Saturday','Sunday'))
--update #AVGG set DATE_KEY=DATEADD(day,1,DATE_KEY) where DATEADD(day,1,DATE_KEY) in (select startdate from #tmp1 where DATENAME(WEEKDAY,startdate) not in ('Saturday','Sunday'))
--update #AVGG set DATE_KEY=DATEADD(day,1,DATE_KEY) where DATEADD(day,1,DATE_KEY) in (select startdate from #tmp1 where DATENAME(WEEKDAY,startdate) not in ('Saturday','Sunday'))
--update #AVGG set DATE_KEY=DATEADD(day,1,DATE_KEY) where DATEADD(day,1,DATE_KEY) in (select startdate from #tmp1 where DATENAME(WEEKDAY,startdate) not in ('Saturday','Sunday'))

--update #AVGG set DATE_KEY=DATEADD(day,1,DATE_KEY) where DATEADD(day,1,DATE_KEY)=@TO_DATE and DATENAME(WEEKDAY,DATEADD(day,1,DATE_KEY)) in ('Saturday','Sunday')

--DATEADD(MONTH,-1,@TO_DATE)

--SELECT MAX(min_day) DAYS,CUSTOMER_NO INTO #C FROM #AVG WHERE LCY_DR_BALANCE=0 GROUP BY CUSTOMER_NO
--SELECT MAX(min_day) DAYS,CUSTOMER_NO INTO #D FROM #AVG WHERE LCY_CR_BALANCE=0 GROUP BY CUSTOMER_NO

--UPDATE A SET A.LCY_DR_BALANCE=0,A.FCY_DR_BALANCE=0 FROM #AVG A INNER JOIN (SELECT CASE WHEN #C.DAYS>#D.DAYS THEN #D.DAYS ELSE #C.DAYS END DAYS,
--CASE WHEN #C.DAYS>#D.DAYS THEN #D.CUSTOMER_NO ELSE #C.CUSTOMER_NO END CUST_AC_NO FROM #C FULL JOIN #D ON #C.CUSTOMER_NO=#D.CUSTOMER_NO)
--D ON A.CUSTOMER_NO=D.CUST_AC_NO WHERE A.LCY_CR_BALANCE=0 AND A.min_day<=D.DAYS

--UPDATE A SET A.LCY_CR_BALANCE=0,A.FCY_CR_BALANCE=0 FROM #AVG A INNER JOIN (SELECT MAX(min_day) DAYS,CUSTOMER_NO FROM #AVG WHERE LCY_CR_BALANCE=0 GROUP BY CUSTOMER_NO)
--D ON A.CUSTOMER_NO=D.CUSTOMER_NO WHERE A.LCY_CR_BALANCE>0  AND A.min_day<=D.DAYS

--select *,DATEDIFF(DAY,min_day,max_day)+1 daysC,case when LCY_BALANCE<0 then DATEDIFF(DAY,min_day,max_day)+1  else 0 end daysD,
--LCY_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) LCY_AVG,
--FCY_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) FCY_AVG
--INTO #AVG1 from #AVG  where (LCY_BALANCE<>0)
--order by CUSTOMER_NO,min_day,max_day

--SELECT CUSTOMER_NO,
--SUM(LCY_AVG)/NULLIF(d.c,0) LCY_AVG,
--SUM(FCY_AVG)/NULLIF(d.c,0) FCY_AVG,
--APPROVE_AMOUNT
--INTO #AVG2 FROM #AVG1 inner join (select (SUM(daysD)) d,(SUM(daysC)) c,CUSTOMER_NO ac from #AVG1   
--group by CUSTOMER_NO) d on #AVG1.CUSTOMER_NO=d.ac group by CUSTOMER_NO,d.d,d.c,APPROVE_AMOUNT

insert into #Overview
SELECT YEAR(@FROM_DATE),DATEPART(M,@FROM_DATE),DATENAME(MONTH,@FROM_DATE),LCY_AVG,APPROVE_AMOUNT*-1,
OD,ODOVER,MIN_BAL,MAX_BAL FROM #AVG2 GROUP BY LCY_AVG,APPROVE_AMOUNT,OD,MIN_BAL,MAX_BAL,ODOVER

insert into #turnC
select YEAR(@FROM_DATE),DATENAME(m, @FROM_DATE),COUNT(TRN_REF_NO),SUM(LCY_AMOUNT),DRCR_IND,AC_NO from BBCSTAGE..SGTB_AC_ENTRIES where TRN_DT between @FROM_DATE and @TO_DATE and RELATED_CUSTOMER=@cust_no and EVENT='INIT' and CUST_GL='A' and DRCR_IND='C'
group by DRCR_IND,AC_NO
insert into #turnD
select YEAR(@FROM_DATE),DATENAME(m, @FROM_DATE),COUNT(TRN_REF_NO),SUM(LCY_AMOUNT),DRCR_IND,AC_NO from BBCSTAGE..SGTB_AC_ENTRIES where TRN_DT between @FROM_DATE and @TO_DATE and RELATED_CUSTOMER=@cust_no and EVENT='INIT' and CUST_GL='A' and DRCR_IND='D'
group by DRCR_IND,AC_NO

SET @FROM_DATE=DATEADD(MONTH,1,@FROM_DATE)
	END
SET @FROM_DATE=DATEADD(YEAR,1,@FROM_DATE)
END

SELECT O.*,SUM(C.Num_Trn) Num_TrnC,
SUM(C.Balance) BalanceC into #Overview1  FROM #Overview O 
LEFT JOIN #turnC C ON O.Year=C.YEAR and o.Month=c.Month
group by o.Year,o.Month,Average_Balance,Authorized_Overdraft,DayOD,NUM_MONTH,MIN_BAL,MAX_BAL,DayOVER

SELECT O.*,SUM(C.Num_Trn) Num_TrnD,
SUM(C.Balance) BalanceD,R.Order_Char,MAX_BAL-MIN_BAL VARI   FROM #Overview1 O
INNER JOIN DIM_ORDER R ON R.ID=O.NUM_MONTH 
LEFT JOIN #turnD C ON O.Year=C.YEAR and o.Month=c.Month
group by o.Year,o.Month,Average_Balance,Authorized_Overdraft,DayOD,o.Num_TrnC,o.BalanceC,NUM_MONTH,Order_Char,MIN_BAL,MAX_BAL,DayOVER
ORDER BY Order_Char
END
