CREATE PROC [dbo].[RPT_NBC_TWICE_WEEK_DEP_OUTSIDE_CAM] @DATE DATE,@RATE MONEY
AS
BEGIN
  IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP

SELECT * INTO #TMP FROM BBCNBCMART.DBO.FACT_TWICE_WEEK_DEP_OUTSIDE_CAM RPT WHERE TO_DATE=@DATE
SELECT isnull(CUS.CUSTOMER_NAME1,'') AS BANK_NAME,COUN.DESCRIPTION COUNTRY,LOOK.DESCRIPTION AS DEPOSIT_TYPE,
(CURRENT_BALANCE * @RATE) CURRENT_BALANCE,(PLACEMENT*@RATE) PLACEMENT,@RATE EX_RATE,LOOK.ORD_VAL
FROM #TMP RPT
INNER JOIN DIM_COUNTRY COUN ON COUN.COUNTRY_CODE=RPT.COUNTRY
INNER JOIN DIM_CUSTOMER CUS ON CUS.CUSTOMER_KEY=RPT.CUSTOMER_KEY
FULL JOIN BBCNBCMART.DBO.DIM_REPORT_LOOKUP LOOK ON LOOK.LOOKUP_KEY=RPT.DEPOSIT_TYPE_KEY ORDER BY LOOK.ORD_VAL
END
