CREATE PROC [dbo].[RPT_TERM_DEOP_NO_STAFF] @BRANCH_DATE DATE
AS
BEGIN
select RELATIONSHIP_MANAGER,CUS.CUSTOMER_CATEGORY,AC_DESC,AC.BRANCH_CODE,CIF,ACCOUNT_NUMBER,F.FCY_BAL,F.CCY,F.LCY_BAL,RT.UDE_VALUE RATE,TD_START_DATE,TD_MATURITY_DATE,DATEDIFF(MONTH,TD_START_DATE,TD_MATURITY_DATE) TENOR,IACR from FACT_CUSTOMER_PORTFOLIO F INNER JOIN DIM_CUSTOMER CUS ON F.CIF=CUS.CUSTOMER_NO AND CUS.IS_CURRENT=1
INNER JOIN DIM_CUST_ACCOUNT AC ON AC.CUST_AC_NO=ACCOUNT_NUMBER AND AC.IS_CURRENT=1
LEFT JOIN DIM_ICTM_UDE RT ON ACCOUNT_NUMBER=RT.ACC AND RT.UDE_ID NOT IN('PENAL_RATE','PENAL_RATE','TAX_RATE','RD_OD_PNL_RATE','SPL_RATE') AND RT.IS_CURRENT=1
INNER JOIN FACT_DAILY_IACR_ACCOUNT I ON I.ACCOUNT=ACCOUNT_NUMBER AND I.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
 WHERE F.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) AND TD_MATURITY_DATE IS NOT NULL AND CIF NOT IN (SELECT CUST_NO FROM DIM_CUST_ACCOUNT WHERE ACCOUNT_CLASS IN ('CAEMPL','SAEMPL') AND IS_CURRENT=1)
END
