CREATE PROC [dbo].[RPT_CUST_PORTFOLIO] @BRANCH_DATE DATE
AS
BEGIN
 IF OBJECT_ID('tempdb..#CR') IS NOT NULL
  DROP TABLE #CR
 IF OBJECT_ID('tempdb..#DR') IS NOT NULL
  DROP TABLE #DR
DECLARE @KHR float=(SELECT MID_RATE FROM DIM_RATE WHERE RATE_TYPE='NBC' and CCY1='USD' and CCY2='KHR' AND BRANCH_CODE='001' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112))
DECLARE @EUR float=(SELECT MID_RATE FROM DIM_RATE WHERE RATE_TYPE='NBC' and CCY1='USD' and CCY2='EUR' AND BRANCH_CODE='001' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112))
DECLARE @THB float=(SELECT MID_RATE FROM DIM_RATE WHERE RATE_TYPE='NBC' and CCY1='USD' and CCY2='THB' AND BRANCH_CODE='001' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112))

select CASE WHEN AC_CCY='EUR' THEN  (FCY_AMOUNT)*@EUR
WHEN AC_CCY='KHR' THEN (FCY_AMOUNT)/@KHR
WHEN AC_CCY='THB' THEN (FCY_AMOUNT)/@THB
WHEN AC_CCY='USD' THEN (LCY_AMOUNT) END LCY_AMOUNT,RELATED_ACCOUNT INTO #DR from BBCSTAGE..SGTB_AC_ENTRIES where TRN_DT=@BRANCH_DATE and EVENT='IACR' and DRCR_IND='C' and PRODUCT like '%D%' 

select CASE WHEN AC_CCY='EUR' THEN  (FCY_AMOUNT)*@EUR
WHEN AC_CCY='KHR' THEN (FCY_AMOUNT)/@KHR
WHEN AC_CCY='THB' THEN (FCY_AMOUNT)/@THB
WHEN AC_CCY='USD' THEN (LCY_AMOUNT) END LCY_AMOUNT,RELATED_ACCOUNT INTO #CR from BBCSTAGE..SGTB_AC_ENTRIES where TRN_DT=@BRANCH_DATE and EVENT='IACR' and DRCR_IND='C' AND PRODUCT NOT like '%D%' 

SELECT F.*,V.FIELD_VAL_5 FATCA,isnull(ICB.IACR,0) LCY_CR_ACCR_AMOUNT,case when isnull(ICD.IACR,0)<0 then isnull(ICD.IACR,0)*(-1) else isnull(ICD.IACR,0) end LCY_DR_ACCR_AMOUNT,ISNULL(C.LCY_AMOUNT,0) CR_LIQUIDATION,ISNULL(D.LCY_AMOUNT,0) DR_LIQUIDATION,ISNULL(DC.LCY_AMOUNT,0) DAILY_CR_ACC,ISNULL(DD.LCY_AMOUNT,0) DAILY_DR_ACC,CL.DESCRIPTION ACCOUNT_CLASS_DESC FROM FACT_CUSTOMER_PORTFOLIO  F
INNER JOIN DIM_ACCOUNT_CLASS CL ON F.ACCOUNT_CLASS=CL.ACCOUNT_CLASS 
 LEFT JOIN DIM_UDF_VAL V ON F.CIF=V.REC_KEY 
LEFT JOIN (SELECT isnull(IACR,0) IACR,ACCOUNT FROM BBCDW..FACT_DAILY_IACR_ACCOUNT WHERE  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) and IACR>=0 ) ICB ON F.ACCOUNT_NUMBER=ICB.ACCOUNT
LEFT JOIN (SELECT isnull(IACR,0) IACR,ACCOUNT FROM BBCDW..FACT_DAILY_IACR_ACCOUNT WHERE  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) and IACR<0) ICD ON F.ACCOUNT_NUMBER=ICD.ACCOUNT 
LEFT JOIN (select AC_NO,SUM(LCY_AMOUNT) LCY_AMOUNT from BBCSTAGE..SGTB_AC_ENTRIES where TRN_DT=@BRANCH_DATE and EVENT='ILIQ' and CUST_GL='A' and AMOUNT_TAG in ('ILIQ') and PRODUCT<>'PCKG' and DRCR_IND='D' GROUP BY AC_NO) D ON F.ACCOUNT_NUMBER=D.AC_NO
LEFT JOIN (select AC_NO,SUM(LCY_AMOUNT) LCY_AMOUNT from BBCSTAGE..SGTB_AC_ENTRIES where TRN_DT=@BRANCH_DATE and EVENT='ILIQ' and CUST_GL='A' and AMOUNT_TAG in ('ILIQ') and PRODUCT<>'PCKG' and DRCR_IND='C' GROUP BY AC_NO) C ON F.ACCOUNT_NUMBER=C.AC_NO
LEFT JOIN (select sum(LCY_AMOUNT) LCY_AMOUNT,RELATED_ACCOUNT from #DR GROUP BY RELATED_ACCOUNT) DD ON F.ACCOUNT_NUMBER=DD.RELATED_ACCOUNT
LEFT JOIN (select sum(LCY_AMOUNT) LCY_AMOUNT,RELATED_ACCOUNT from #CR GROUP BY RELATED_ACCOUNT) DC ON F.ACCOUNT_NUMBER=DC.RELATED_ACCOUNT
WHERE RECORD_STAT='O' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
AND V.IS_CURRENT=1 and FUNCTION_ID='STDCIF'
END
