CREATE PROC [dbo].[RPT_OD] @BRANCH_DATE DATE
AS
BEGIN
SELECT *,CASE WHEN DATEDIFF(DAY,@BRANCH_DATE,TOD_LIMIT_END_DATE)<=90 THEN '***' ELSE '' END REMARK FROM FACT_OVERDRAFT WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
END
