CREATE PROC [dbo].[RPT_MONTHLY_CUST_PORTFOLIO] @FROM_DATE DATE,@TO_DATE DATE
AS
BEGIN
IF OBJECT_ID('tempdb..#AVG') IS NOT NULL
  DROP TABLE #AVG
IF OBJECT_ID('tempdb..#AVG1') IS NOT NULL
  DROP TABLE #AVG1
IF OBJECT_ID('tempdb..#AVG2') IS NOT NULL
  DROP TABLE #AVG2
IF OBJECT_ID('tempdb..#CR') IS NOT NULL
  DROP TABLE #CR
IF OBJECT_ID('tempdb..#DR') IS NOT NULL
  DROP TABLE #DR
SELECT BAL.ACCOUNT_KEY,cast(CONVERT(varchar,MIN(DATE_KEY)) as date) min_day,cast(CONVERT(varchar,max(DATE_KEY)) as date) max_day,CUST_AC_NO,
CASE WHEN LCY_CUR_BAL<0 THEN LCY_CUR_BAL*(-1) ELSE 0 END LCY_DR_BALANCE,
CASE WHEN LCY_CUR_BAL>0 THEN LCY_CUR_BAL ELSE 0 END LCY_CR_BALANCE,
CASE WHEN ACY_CUR_BAL<0 THEN ACY_CUR_BAL*(-1) ELSE 0 END FCY_DR_BALANCE,
CASE WHEN ACY_CUR_BAL>0 THEN ACY_CUR_BAL ELSE 0 END FCY_CR_BALANCE into #AVG FROM BBCDW..FACT_DAILY_AC_BAL BAL 
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY and ACCOUNT_CLASS not in ('INTERN')
WHERE DATE_KEY BETWEEN CONVERT(VARCHAR,@FROM_DATE,112) AND CONVERT(VARCHAR,@TO_DATE,112)
GROUP BY CUST_AC_NO,LCY_CUR_BAL,ACY_CUR_BAL,BAL.ACCOUNT_KEY  order by CUST_AC_NO,min_day,max_day

select *,DATEDIFF(DAY,min_day,max_day)+1 days,
LCY_DR_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) LCY_DR_AVG,
FCY_DR_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) FCY_DR_AVG,
LCY_CR_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) LCY_CR_AVG,
FCY_CR_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) FCY_CR_AVG INTO #AVG1 from #AVG 
order by CUST_AC_NO,min_day,max_day

SELECT CUST_AC_NO,
(SUM(LCY_DR_AVG)/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)) LCY_DR_AVG,(SUM(FCY_DR_AVG)/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)) FCY_DR_AVG,
(SUM(LCY_CR_AVG)/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)) LCY_CR_AVG,(SUM(FCY_CR_AVG)/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)) FCY_CR_AVG 
INTO #AVG2 FROM #AVG1 group by CUST_AC_NO

SELECT AC_NO,SUM(LCY_AMOUNT) DR INTO #DR FROM BBCSTAGE..SGTB_AC_ENTRIES WHERE TRN_DT BETWEEN @FROM_DATE AND @TO_DATE AND MODULE ='IC' AND EVENT='ILIQ'
AND LEN(AC_NO)>10 AND DRCR_IND='D' AND PRODUCT IN (select PRODUCT_CODE from BBCDW..DIM_ICPRMNT WHERE [RULE] IN ('TD01','TD02','TD03','CADI','CACI','SACI','SACM')) GROUP BY AC_NO

SELECT AC_NO,SUM(LCY_AMOUNT) CR INTO #CR FROM BBCSTAGE..SGTB_AC_ENTRIES WHERE TRN_DT BETWEEN @FROM_DATE AND @TO_DATE AND MODULE ='IC' AND EVENT='ILIQ'
AND LEN(AC_NO)>10 AND DRCR_IND='C' AND PRODUCT IN (select PRODUCT_CODE from BBCDW..DIM_ICPRMNT WHERE [RULE] IN ('TD01','TD02','TD03','CADI','CACI','SACI','SACM')) GROUP BY AC_NO

SELECT BRANCH_CODE,CUST_NO CIF,AC.CUST_AC_NO ACCOUNT_NUMBER,FULL_NAME,P_SEX SEX,ACCOUNT_CLASS,CASE WHEN ACCOUNT_TYPE='U' THEN 'CURRENT'
WHEN ACCOUNT_TYPE='S' THEN 'SAVING'
WHEN ACCOUNT_TYPE='Y' THEN 'FIXED'
WHEN ACCOUNT_TYPE='N' THEN 'NOSTRO' END ACCOUNT_TYPE,CCY,CIF_CREATION_DATE CIF_OPEN_DATE,
AC.AC_OPEN_DATE ACCOUNT_OPEN_DATE,ICM.INT_START_DATE,MATURITY_DATE,ROLLOVER_TYPE,CASE WHEN AC.ACY_CURR_BALANCE <= 0 THEN 'D' ELSE 'C' END DRCR_AC,
ACC_STATUS,DESIGNATION,LCY_DR_AVG,ISNULL(DR,0)DR_INTEREST,
ISNULL((ISNULL(DR*365/NULLIF(LCY_DR_AVG,0),0)/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)),0) LCY_AVERAGE_RATE_DR,LCY_CR_AVG,ISNULL(CR,0)CR_INTEREST,ISNULL((ISNULL(CR*365/NULLIF(LCY_CR_AVG,0),0)/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)),0) LCY_AVERAGE_RATE_CR,FCY_DR_AVG,
ISNULL((ISNULL(DR*365/NULLIF(FCY_DR_AVG,0),0)/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)),0) FCY_AVERAGE_RATE_DR,FCY_CR_AVG,ISNULL((ISNULL(CR*365/NULLIF(FCY_CR_AVG,0),0)/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)),0) FCY_AVERAGE_RATE_CR,
LOV_DESC FROM #AVG2 A
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON AC.CUST_AC_NO=A.CUST_AC_NO AND IS_CURRENT=1
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
LEFT JOIN (select D.REC_KEY CIF_NO,LOV_DESC from BBCDW..DIM_UDF_VAL D
INNER JOIN BBCDW..DIM_UDF_LOV L ON D.FIELD_VAL_10=L.LOV AND L.FIELD_NAME='PACKAGE' WHERE FUNCTION_ID ='STDCIF' AND D.IS_CURRENT=1 AND L.IS_CURRENT=1) UDF ON AC.CUST_NO=UDF.CIF_NO AND AC.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_ICTM ICM ON ICM.ACC=AC.CUST_AC_NO AND ICM.IS_CURRENT=1 AND AC.IS_CURRENT=1
LEFT JOIN #CR ON A.CUST_AC_NO=#CR.AC_NO
LEFT JOIN #DR ON A.CUST_AC_NO=#DR.AC_NO

END
