CREATE PROC [dbo].[RPT_CUST_PORTFOLIO_Paul] @BRANCH_DATE DATE
AS
BEGIN
SELECT F.*,V.FIELD_VAL_5 FATCA,isnull(ICB.IACR,0) LCY_CR_ACCR_AMOUNT,isnull(ICD.IACR,0) LCY_DR_ACCR_AMOUNT FROM FACT_CUSTOMER_PORTFOLIO  F LEFT JOIN DIM_UDF_VAL V ON F.CIF=V.REC_KEY
LEFT JOIN (SELECT isnull(IACR,0) IACR,ACCOUNT FROM BBCDW..FACT_DAILY_IACR_ACCOUNT WHERE  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) and IACR>=0 ) ICB ON ICB.ACCOUNT=F.ACCOUNT_NUMBER 
LEFT JOIN (SELECT isnull(IACR,0) IACR,ACCOUNT FROM BBCDW..FACT_DAILY_IACR_ACCOUNT WHERE  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) and IACR<0) ICD ON ICD.ACCOUNT=F.ACCOUNT_NUMBER 
 WHERE RECORD_STAT='O' AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
AND V.IS_CURRENT=1 and FUNCTION_ID='STDCIF' and RELATIONSHIP_MANAGER='Paul BALMETTE'
END
