CREATE PROC [dbo].[RPT_MONTHLY_CUST_PORTFOLIO_NEW] @FROM_DATE DATE,@TO_DATE DATE
AS
BEGIN

IF OBJECT_ID('tempdb..#AVG') IS NOT NULL
  DROP TABLE #AVG
IF OBJECT_ID('tempdb..#AVG1') IS NOT NULL
  DROP TABLE #AVG1
IF OBJECT_ID('tempdb..#AVG11') IS NOT NULL
  DROP TABLE #AVG11
IF OBJECT_ID('tempdb..#AVG2') IS NOT NULL
  DROP TABLE #AVG2
IF OBJECT_ID('tempdb..#CR') IS NOT NULL
  DROP TABLE #CR
IF OBJECT_ID('tempdb..#DR') IS NOT NULL
  DROP TABLE #DR
create table #tmp1 (month int,startdate date)
select * into #tmp from BBCDW..DIM_HOLIDAY where BRANCH_CODE='001' and YEAR = (YEAR(@FROM_DATE)) and MONTH=DATEPART(m, @FROM_DATE)

declare @min_month int=1

while @min_month<=12
begin
declare @max int = (select LEN(holiday_list) from #tmp where branch_code='001' and month=@min_month)
declare @min int=1
while @min<=@max
begin
insert into #tmp1
select @min_month,(select 
case when SUBSTRING(holiday_list,@min,1)='W' then null else
CONVERT(date,cast(CONCAT(Year,RIGHT('00'+ cast(MONTH as varchar),2),right('00'+cast(@min as varchar),2)) as varchar),112) end from #tmp where MONTH=@min_month and branch_code='001')

set @min=@min+1
end
set @min_month=@min_month+1
end

delete from #tmp1 where startdate is null
alter table #tmp1
add ID int identity(1,1)

SELECT bal.DATE_KEY,CUST_AC_NO,
CASE WHEN LCY_CUR_BAL<0 THEN LCY_CUR_BAL*(-1) ELSE 0 END LCY_DR_BALANCE,
CASE WHEN LCY_CUR_BAL>0 THEN LCY_CUR_BAL ELSE 0 END LCY_CR_BALANCE,
CASE WHEN ACY_CUR_BAL<0 THEN ACY_CUR_BAL*(-1) ELSE 0 END FCY_DR_BALANCE,
CASE WHEN ACY_CUR_BAL>0 THEN ACY_CUR_BAL ELSE 0 END FCY_CR_BALANCE into #AVG FROM BBCDW..FACT_DAILY_AC_BAL BAL 
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY and ACCOUNT_CLASS not in ('INTERN') and DATE_KEY between CONVERT(VARCHAR,@FROM_DATE,112) and CONVERT(VARCHAR,@TO_DATE,112)
WHERE cast(AC_OPEN_DATE as date) BETWEEN @FROM_DATE AND @TO_DATE 

declare @countmin int=1
while @countmin<=(select count(*) from #tmp1)
begin

INSERT INTO #AVG
SELECT DATE_KEY+1,CUST_AC_NO,LCY_DR_BALANCE,LCY_CR_BALANCE,FCY_DR_BALANCE,FCY_CR_BALANCE FROM #AVG WHERE DATEADD(day,1,CAST(CONVERT(VARCHAR,(DATE_KEY),112) AS DATE)) IN (select startdate from #tmp1 where ID=@countmin and startdate not in ('2017-12-30'))		

set @countmin=@countmin+1
end

select CUST_AC_NO,COUNT(DATE_KEY) days,AVG(LCY_DR_BALANCE) LCY_DR_AVG,AVG(LCY_CR_BALANCE) LCY_CR_AVG,AVG(FCY_DR_BALANCE) FCY_DR_AVG,
AVG(FCY_CR_BALANCE) FCY_CR_AVG into #AVG1 from #AVG where (LCY_DR_BALANCE<>0 or LCY_CR_BALANCE<>0)
group by CUST_AC_NO

--select *,DATEDIFF(DAY,min_day,max_day)+1 days,
--LCY_DR_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) LCY_DR_AVG,
--FCY_DR_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) FCY_DR_AVG,
--LCY_CR_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) LCY_CR_AVG,
--FCY_CR_BALANCE*((DATEDIFF(DAY,min_day,max_day)+1)) FCY_CR_AVG INTO #AVG1 from #AVG  where (LCY_DR_BALANCE<>0 or LCY_CR_BALANCE<>0)
--order by CUST_AC_NO,min_day,max_day

--SELECT CUST_AC_NO,
--(SUM(LCY_DR_AVG)/d.d) LCY_DR_AVG,(SUM(FCY_DR_AVG)/d.d) FCY_DR_AVG,
--(SUM(LCY_CR_AVG)/d.d) LCY_CR_AVG,(SUM(FCY_CR_AVG)/d.d) FCY_CR_AVG 
--INTO #AVG2 FROM #AVG1 inner join (select (SUM(days)) d,CUST_AC_NO ac from #AVG1   
--group by CUST_AC_NO) d on #AVG1.CUST_AC_NO=d.ac group by CUST_AC_NO,d.d

SELECT AC_NO,SUM(LCY_AMOUNT) DR INTO #DR FROM BBCSTAGE..SGTB_AC_ENTRIES WHERE TRN_DT BETWEEN @FROM_DATE AND @TO_DATE AND MODULE ='IC' AND EVENT='ILIQ'
AND LEN(AC_NO)>10 AND DRCR_IND='D' AND PRODUCT IN (select PRODUCT_CODE from BBCDW..DIM_ICPRMNT WHERE [RULE] IN ('CADI','CACI','SACI','SACM') and AMOUNT_TAG='ILIQ') GROUP BY AC_NO

SELECT AC_NO,SUM(LCY_AMOUNT) CR INTO #CR FROM BBCSTAGE..SGTB_AC_ENTRIES WHERE TRN_DT BETWEEN @FROM_DATE AND @TO_DATE AND MODULE ='IC' AND EVENT='ILIQ'
AND LEN(AC_NO)>10 AND DRCR_IND='C' AND PRODUCT IN (select PRODUCT_CODE from BBCDW..DIM_ICPRMNT WHERE [RULE] IN ('CADI','CACI','SACI','SACM')and AMOUNT_TAG='ILIQ') GROUP BY AC_NO
union all
SELECT RELATED_ACCOUNT,SUM(LCY_AMOUNT) CR FROM BBCSTAGE..SGTB_AC_ENTRIES WHERE TRN_DT BETWEEN @FROM_DATE AND @TO_DATE AND MODULE ='IC' AND EVENT='IACR'
AND DRCR_IND='C' AND PRODUCT IN (select PRODUCT_CODE from BBCDW..DIM_ICPRMNT WHERE [RULE] IN ('TD01','TD02','TD03')and AMOUNT_TAG='IACR') GROUP BY RELATED_ACCOUNT

SELECT BRANCH_CODE,CUST_NO CIF,AC.CUST_AC_NO ACCOUNT_NUMBER,FULL_NAME,P_SEX SEX,ACCOUNT_CLASS,CASE WHEN ACCOUNT_TYPE='U' THEN 'CURRENT'
WHEN ACCOUNT_TYPE='S' THEN 'SAVING'
WHEN ACCOUNT_TYPE='Y' THEN 'FIXED'
WHEN ACCOUNT_TYPE='N' THEN 'NOSTRO' END ACCOUNT_TYPE,CCY,CIF_CREATION_DATE CIF_OPEN_DATE,
AC.AC_OPEN_DATE ACCOUNT_OPEN_DATE,ICM.INT_START_DATE,MATURITY_DATE,ROLLOVER_TYPE,CASE WHEN AC.ACY_CURR_BALANCE <= 0 THEN 'D' ELSE 'C' END DRCR_AC,
ACC_STATUS,DESIGNATION,LCY_DR_AVG,ISNULL(DR,0)DR_INTEREST,
ISNULL((ISNULL(DR*360/NULLIF(LCY_DR_AVG,0),0)/d.d),0) LCY_AVERAGE_RATE_DR,LCY_CR_AVG,ISNULL(CR,0)CR_INTEREST,ISNULL((ISNULL(CR*360/NULLIF(LCY_CR_AVG,0),0)/d.d),0) LCY_AVERAGE_RATE_CR,FCY_DR_AVG,
ISNULL((ISNULL(DR*360/NULLIF(FCY_DR_AVG,0),0)/d.d),0) FCY_AVERAGE_RATE_DR,FCY_CR_AVG,ISNULL((ISNULL(CR*360/NULLIF(FCY_CR_AVG,0),0)/d.d),0) FCY_AVERAGE_RATE_CR,
LOV_DESC FROM #AVG1 A
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC ON AC.CUST_AC_NO=A.CUST_AC_NO AND IS_CURRENT=1
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_NO=AC.CUST_NO AND CUS.IS_CURRENT=1
left join (select (SUM(days)) d,CUST_AC_NO ac from #AVG1 group by CUST_AC_NO) d on A.CUST_AC_NO=d.ac
LEFT JOIN (select D.REC_KEY CIF_NO,LOV_DESC from BBCDW..DIM_UDF_VAL D
INNER JOIN BBCDW..DIM_UDF_LOV L ON D.FIELD_VAL_10=L.LOV AND L.FIELD_NAME='PACKAGE' WHERE FUNCTION_ID ='STDCIF' AND D.IS_CURRENT=1 AND L.IS_CURRENT=1) UDF ON AC.CUST_NO=UDF.CIF_NO AND AC.IS_CURRENT=1
LEFT JOIN BBCDW..DIM_ICTM ICM ON ICM.ACC=AC.CUST_AC_NO AND ICM.IS_CURRENT=1 AND AC.IS_CURRENT=1
LEFT JOIN #CR ON A.CUST_AC_NO=#CR.AC_NO
LEFT JOIN #DR ON A.CUST_AC_NO=#DR.AC_NO

drop table #tmp
drop table #tmp1

end
