CREATE PROC [dbo].[RPT_CUST_PORTFOLIO_RM] @BRANCH_DATE DATE
AS
BEGIN
SELECT *,isnull(ICB.IACR,0) LCY_CR_ACCR_AMOUNT,isnull(ICD.IACR,0) LCY_DR_ACCR_AMOUNT FROM FACT_CUSTOMER_PORTFOLIO
LEFT JOIN (SELECT isnull(IACR,0) IACR,ACCOUNT FROM BBCDW..FACT_DAILY_IACR_ACCOUNT WHERE  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) and IACR>=0 ) ICB ON ICB.ACCOUNT=ACCOUNT_NUMBER 
LEFT JOIN (SELECT isnull(IACR,0) IACR,ACCOUNT FROM BBCDW..FACT_DAILY_IACR_ACCOUNT WHERE  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) and IACR<0) ICD ON ICD.ACCOUNT=ACCOUNT_NUMBER 
 WHERE  DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) 
AND RELATIONSHIP_MANAGER IN ('Kimleng LEY','Nicola FERRONATO','Geoffroy DUPUIS','Tepkosol CHAN','Veang LY','Sokheng UN','Chandawin LUY')
END
