-- =============================================
-- Author:		BUNCHHOEUN CHHIM
-- Create date: 15-JAN-18
-- Description:	POS FILE BODY FOR OPERATION CODE
--				IN (N04,N05) AND STATUS = 'S'
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_MERC_STATEMENT]
	@START_DATE DATE, @END_DATE DATE, 
	@MERC_ID NCHAR(20)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT A.OPERATION_CODE, ABS(D.ACTUAL_NET) NET_AMT, ABS(D.ACTUAL_TOT) AMT, A.MERCHANT_FEE_AMT FEE_AMT, D.DEP_NBR NO_TRN_BATCH, A.MERCHANT_ID, A.MERCHANT_NAME, A.MERCHANT_ACC_NUMBER,
	B.CCY, C.TRN_DT SETTLE_DATE, D.MERCH_SEQ BATCH_NO, 
	(SELECT LTRIM(RTRIM(C.TERM_ID)) FROM BBCDW..DIM_ATM_POS C WHERE C.MERCH_ID = CONCAT('000000',A.MERCHANT_ID) AND C.IS_CURRENT = 1) TERM_ID

	FROM BBCSTAGE..SGTB_FILE_BODY A 
		LEFT JOIN BBCDW..DIM_CUST_ACCOUNT B ON A.MERCHANT_ACC_NUMBER = B.CUST_AC_NO
		INNER JOIN BBCSTAGE..SGTB_AC_ENTRIES C ON A.FCC_REFERENCE_NO = C.TRN_REF_NO
		INNER JOIN BBCCARD..CARD_MERC_TRN D ON A.MERCHANT_ID = D.MERCHANT
			AND A.MICROFILM_REF = CONCAT('0000', D.MICRO_REF)
	WHERE A.MERCHANT_ID = @MERC_ID
		AND D.BANKLINK IS NOT NULL
		AND C.TRN_DT BETWEEN @START_DATE AND @END_DATE
		AND C.AMOUNT_TAG = 'TXN_AMT'
		AND C.TRN_CODE IN ('700','704')
		AND A.DESTINATION_TYPE = 'V'
		AND A.OPERATION_CODE IN ('N04','N05')
		AND A.STATUS = 'S'
		AND B.IS_CURRENT = 1	

END
