-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 22-SEP-2016
-- Description:	ETL MONEY MARKET PLACEMENT REPORTS
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_MM_PLACEMENT]
	@REPORT_DATE DATE,@STATUS VARCHAR(20)
AS
BEGIN

	SET NOCOUNT ON;

    SELECT 
		(CASE WHEN C.COUNTERPARTY_TYPE='NBC' AND C.PRODUCT_TYPE='L' THEN 1
			 WHEN C.COUNTERPARTY_TYPE<>'NBC' AND C.PRODUCT_TYPE='L' THEN 2 ELSE 3 END) ORDER_VAL,
		 (CASE WHEN C.COUNTERPARTY_TYPE='NBC' AND C.PRODUCT_TYPE='L' THEN 'Placement with NBC' 
			  WHEN C.COUNTERPARTY_TYPE!='NBC' AND C.PRODUCT_TYPE='L' THEN 'Placement with Others Bank'
			  ELSE 	'Placement from Others/Banks' END) AS C_TYPE,
			  C.CURRENCY,C.PRODUCT,C.PRODUCT_DESC,C.COUNTERPARTY_NAME,C.COUNTERPARTY,C.CONTRACT_REF_NO,
			CASE WHEN C.CURRENCY='USD' THEN 0 ELSE C.AMOUNT END AMOUNT,C.LCY_AMOUNT,C.BOOKING_DATE,C.VALUE_DATE,C.MATURITY_DATE,C.MAIN_COMP_RATE,C.TENOR,C.CONTRACT_STATUS,
			(SELECT SUM(ISNULL(FCY_AMOUNT,0))  FROM FACT_MM_ACCRUED_INT M WHERE C.CONTRACT_KEY=M.CONTRACT_KEY AND M.TRN_DT<=@REPORT_DATE)  FCY_ACR_AMT,
			(SELECT SUM(ISNULL(LCY_AMOUNT,0))  FROM FACT_MM_ACCRUED_INT M WHERE C.CONTRACT_KEY=M.CONTRACT_KEY AND M.TRN_DT<=@REPORT_DATE)  LCY_ACR_AMT,
			(CASE WHEN C.CONTRACT_STATUS='A' THEN DATEDIFF(D,@REPORT_DATE,C.MATURITY_DATE)+1 ELSE 0 END) AS REMAIN_DAYS
			  
	FROM DIM_MM_CONTRACT C 
	WHERE  C.VALUE_DATE<=@REPORT_DATE 
	AND C.IS_CURRENT=1
	AND C.CONTRACT_STATUS collate database_default IN(SELECT Value FROM dbo.FnSplit(@STATUS,','))
	ORDER BY 1,C.VALUE_DATE ASC

END
