CREATE PROC [dbo].[SP_RPT_INCOME_STAT] @REPORT_DATE DATE,@EX_RATE MONEY
AS
BEGIN

IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
select DATE_KEY,ITEM_KEY,GL,Description,Level,[Order],Parent,CLO_LCY_BAL,CLO_FCY_BAL INTO #TMP from BBCNBCMART..FACT_INCOME_STATE WHERE DATE_KEY=CONVERT(VARCHAR,@REPORT_DATE,112) order by ITEM_KEY

DECLARE @LV INT
DECLARE @ID INT
SELECT @LV=MAX(Level) FROM #TMP WHERE GL='' AND [Order]=4
WHILE @LV>0
BEGIN

UPDATE #TMP SET CLO_LCY_BAL=(SELECT ISNULL(SUM(CLO_LCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY),
CLO_FCY_BAL=(SELECT ISNULL(SUM(CLO_FCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY)
WHERE Level=@LV AND  GL='' AND [Order]=4
SET @LV=@LV-1
END

SELECT @LV=MAX(Level) FROM #TMP WHERE GL='' AND [Order]=6
WHILE @LV>0
BEGIN

UPDATE #TMP SET CLO_LCY_BAL=(SELECT ISNULL(SUM(CLO_LCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY),
CLO_FCY_BAL=(SELECT ISNULL(SUM(CLO_FCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY)  
WHERE Level=@LV AND  GL='' AND [Order]=6
SET @LV=@LV-1
END
SELECT @LV=1
UPDATE #TMP SET CLO_LCY_BAL=CLO_LCY_BAL*(-1),CLO_FCY_BAL=CLO_FCY_BAL*(-1) WHERE ITEM_KEY IN (68,70)
WHILE @LV>0
BEGIN

UPDATE #TMP SET CLO_LCY_BAL=(SELECT ISNULL(SUM(CLO_LCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY and T.[Order]=8),
CLO_FCY_BAL=(SELECT ISNULL(SUM(CLO_FCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY and T.[Order]=8)  
WHERE  GL='' AND [Order]=8
SET @LV=@LV-1
END

SELECT @LV=1
WHILE @LV>0
BEGIN

UPDATE #TMP SET CLO_LCY_BAL=(SELECT ISNULL(SUM(CLO_LCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY and T.[Order]=12),
CLO_FCY_BAL=(SELECT ISNULL(SUM(CLO_FCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY and T.[Order]=12)  
WHERE  GL='' AND [Order]=12
SET @LV=@LV-1
END
SELECT @LV=MAX(Level) FROM #TMP WHERE GL='' AND [Order]=13
WHILE @LV>0
BEGIN

UPDATE #TMP SET CLO_LCY_BAL=(SELECT ISNULL(SUM(CLO_LCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY),
CLO_FCY_BAL=(SELECT ISNULL(SUM(CLO_FCY_BAL),0) FROM #TMP T WHERE T.Parent=#TMP.ITEM_KEY)  
WHERE Level=@LV AND  GL='' AND [Order]=13
SET @LV=@LV-1
END

UPDATE #TMP SET CLO_LCY_BAL=(SELECT SUM(CLO_LCY_BAL) FROM #TMP T WHERE T.[Order]=4 AND T.Level=1),
CLO_FCY_BAL=(SELECT SUM(CLO_FCY_BAL) FROM #TMP T WHERE T.[Order]=4 AND T.Level=1) WHERE #TMP.[Order]=4 AND Level=0

UPDATE #TMP SET CLO_LCY_BAL=(SELECT SUM(CLO_LCY_BAL) FROM #TMP T WHERE T.[Order]=6 AND T.Level=1),
CLO_FCY_BAL=(SELECT SUM(CLO_FCY_BAL) FROM #TMP T WHERE T.[Order]=6 AND T.Level=1) WHERE #TMP.[Order]=6 AND Level=0

UPDATE #TMP SET CLO_LCY_BAL=(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=1)-(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=2),
CLO_FCY_BAL=(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=1)-(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=2)
WHERE Level=0 AND [Order]=3

UPDATE #TMP SET CLO_LCY_BAL=(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=3)+(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=4),
CLO_FCY_BAL=(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=3)+(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=4)
WHERE Level=0 AND [Order]=5

UPDATE #TMP SET CLO_LCY_BAL=(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=5)-(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=6),
CLO_FCY_BAL=(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=5)-(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=6)
WHERE Level=0 AND [Order]=7

UPDATE #TMP SET CLO_LCY_BAL=(SELECT SUM(CLO_LCY_BAL) FROM #TMP WHERE Level=0 AND [Order] IN (7,8,9,10)),
CLO_FCY_BAL=(SELECT SUM(CLO_FCY_BAL) FROM #TMP WHERE Level=0 AND [Order] IN (7,8,9,10))
WHERE Level=0 AND [Order]=11

UPDATE #TMP SET CLO_LCY_BAL=(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=11)+(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=12),
CLO_FCY_BAL=(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=11)+(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=12)
WHERE Level=0 AND [Order]=13

UPDATE #TMP SET CLO_LCY_BAL=CLO_LCY_BAL+(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=13)-(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=1 AND [Order]=13),
CLO_FCY_BAL=CLO_FCY_BAL+(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=13)-(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=1 AND [Order]=13)
WHERE Level=0 AND [Order]=14

UPDATE #TMP SET CLO_LCY_BAL=
CLO_LCY_BAL+
(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=14)+
(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=15)+
(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=16)+
(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=17)+
(SELECT CLO_LCY_BAL FROM #TMP WHERE Level=0 AND [Order]=18),

CLO_FCY_BAL=CLO_FCY_BAL+
(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=14)+
(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=15)+
(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=16)+
(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=17)+
(SELECT CLO_FCY_BAL FROM #TMP WHERE Level=0 AND [Order]=18)
WHERE Level=0 AND [Order]=19

SELECT DATE_KEY,ITEM_KEY,Description,Level,CLO_LCY_BAL CLO_LCY_BAL_USD,CLO_LCY_BAL*@EX_RATE CLO_LCY_BAL_KHR,CLO_FCY_BAL CLO_FCY_BAL_USD,
CLO_FCY_BAL*@EX_RATE CLO_FCY_BAL_KHR,(CLO_FCY_BAL*@EX_RATE)+(CLO_LCY_BAL*@EX_RATE) BalanceTotal FROM #TMP ORDER BY ITEM_KEY

END
