CREATE PROC [dbo].[SP_RPT_NBC_DEPO_CLASS] @BRANCH_DATE DATE
AS
BEGIN

	IF OBJECT_ID('tempdb..#depo') IS NOT NULL
  DROP TABLE #depo
SELECT DATE_KEY,TYPE,ACCOUNT_TYPE,F.CCY,sum(FCY) FCY,sum(LCY) LCY into #depo FROM BBCNBCMART..FACT_DEPO_CLASS F 
WHERE DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
group by DATE_KEY,TYPE,ACCOUNT_TYPE,F.CCY

select DATE_KEY,TYPE,d.CCY,CCY_DESC,DEPO_TYPE_DESC,isnull(FCY,0) FCY,isnull(LCY,0) LCY from BBCNBCMART..DIM_DEP_CLASS c full join #depo d on c.CCY=d.CCY and c.DEPO_TYPE=d.ACCOUNT_TYPE 

END
