-- =============================================
-- Author:		HENG SOPHAT
-- Create date: <Create Date,,>
-- Description:	DAILY CASH SETTLEMENT REPORT
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_WEEKLY_CASH_SETTLEMENT]
	@REPORT_DATE DATE,@TODATE DATE,@RATE MONEY
AS
BEGIN
	
	SET NOCOUNT ON;
	  IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
	SELECT DATE_KEY,ITEM_KEY,EX_RATE,AMT_IN_USD,AMT_IN_RIEL INTO #TMP FROM BBCNBCMART..FACT_WEEKLY_FX_CASH_SETTLEMENT WHERE DATE_KEY BETWEEN CONVERT(VARCHAR,@REPORT_DATE,112)  AND CONVERT(VARCHAR,@TODATE,112)
	AND ITEM_KEY not in (1,12,23)
	INSERT INTO #TMP
		SELECT DATE_KEY,ITEM_KEY,EX_RATE,AMT_IN_USD,AMT_IN_RIEL FROM BBCNBCMART..FACT_WEEKLY_FX_CASH_SETTLEMENT WHERE DATE_KEY=CONVERT(VARCHAR,@REPORT_DATE,112) AND ITEM_KEY in (1,12,23)
		update #TMP set AMT_IN_USD=(select sum(AMT_IN_USD) from #TMP where ITEM_KEY=11)+(select sum(AMT_IN_USD) from #TMP where ITEM_KEY=1) where item_key=12
		update #TMP set AMT_IN_USD=(select sum(AMT_IN_USD) from #TMP where ITEM_KEY=12)-(select sum(AMT_IN_USD) from #TMP where ITEM_KEY=22) where item_key=23
    SELECT 
		R.ITEM_LEVEL,
		(CASE WHEN R.ITEM_LEVEL=2 THEN '							'
						  WHEN R.ITEM_LEVEL=1 THEN '			'
						  ELSE '' END
	     )+R.ITEM_CODE AS ITEM_CODE,

		(CASE WHEN R.ITEM_LEVEL=2 THEN '							'
						  WHEN R.ITEM_LEVEL=1 THEN '			'
						  ELSE '' END
			)+R.ITEM_DESC AS REPORT_ITEM,
		SUM(F.AMT_IN_USD) AMT_IN_USD,
		(SUM(F.AMT_IN_USD)*@RATE)/1000000  AMT_IN_MILLION_RIEL
	FROM #TMP F
	INNER JOIN BBCNBCMART..DIM_NBC_REPORT_ITEMS R ON F.ITEM_KEY=R.ITEM_KEY
	WHERE R.REPORT_ID=1
	GROUP BY R.ITEM_LEVEL,R.ITEM_CODE,R.ITEM_DESC,ORD_VAL
	ORDER BY ORD_VAL

END
