-- ===================================================
-- Author		:	BUNCHHOEUN CHHIM 
-- Create date	:	28-NOV-2017
-- Description	:	REPORT CL LOAN SCHEDULE
--					RETAIL CUST (EXCLUDE STAFF & CORP)
-- ===================================================
--CREATE PROC [dbo].[SP_RPT_LOAN_SCHEDULE_RETAIL] @FROMDATE DATE,@TODATE DATE
CREATE PROC [dbo].[SP_RPT_LOAN_SCHEDULE_RETAIL] @FROMDATE DATE,@TODATE DATE

AS
BEGIN

SELECT P.BRANCH_CODE,LOAN_AC_NO,CUS.CUSTOMER_NO, CL.DR_AC_NO, AC_DESC,DUE_DATE, NEXT_PAYMENT_DATE, EMI_AMOUNT, cl.CURRENCY FROM BBCDW..FACT_LOAN_PAYMENT P INNER JOIN DIM_CUST_ACCOUNT AC ON P.ACCOUNT_KEY=AC.ACCOUNT_KEY
INNER JOIN DIM_CUSTOMER CUS ON CUS.CUSTOMER_KEY=CIF_KEY
INNER JOIN DIM_LOAN_ACCOUNT CL ON CL.LOAN_AC_KEY=LOAN_KEY
INNER JOIN DIM_CL_PRODUCT PRO ON PRO.PRODUCT_KEY=P.PRODUCT_KEY
WHERE DATE_KEY BETWEEN CONVERT(VARCHAR,@FROMDATE,112) AND CONVERT(VARCHAR,@TODATE,112) AND ACCOUNT_CLASS not in ('CAEMPL','SAEMPL') AND  LEFT(PRODUCT_DESC,6) like '%IN%'

END
