-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_EOC_BATCH_DETAIL]
	@SERVER_NAME VARCHAR(15),@DB_NAME VARCHAR(15),@BRANCH_DATE AS DATE
AS
BEGIN
	DECLARE @SQL NVARCHAR(4000),@OPENQUERY nvarchar(4000)

	SET @SQL='
	SELECT BRANCH_CODE,
      BRANCH_DATE,
      EOC_REF_NO,
      EOC_STAGE,
	  EOC_STAGE_SEQ,
      EOC_BATCH,
	  EOC_BATCH_SEQ,
      EOC_BATCH_STATUS,
      ERROR_CODE,
      ERROR_PARAM,
      ERROR,
      EOD_DATE,
      START_TIME,
      END_TIME
 FROM @DB_NAME.AETBS_EOC_PROGRAMS Q WHERE Q.BRANCH_DATE=''''@BRANCH_DATE''''
UNION ALL
SELECT T.BRANCH_CODE,
      T.BRANCH_DATE,
      T.EOC_REF_NO,
      T.EOC_STAGE,
	  T.EOC_STAGE_SEQ,
      T.EOC_BATCH,
	  T.EOC_BATCH_SEQ,
      T.EOC_BATCH_STATUS,
      T.ERROR_CODE,
      T.ERROR_PARAM,
      T.ERROR,
      T.EOD_DATE,
      T.START_TIME,
      T.END_TIME
 FROM @DB_NAME.AETB_EOC_PROGRAMS_history T
 WHERE  NVL(T.EOC_BATCH_STATUS,''''**'''') NOT in  (''''N'''',''''A'''') AND T.BRANCH_DATE=''''@BRANCH_DATE''''
 UNION ALL
 SELECT
      R.BRANCH_CODE,
      R.BRANCH_DATE,
      R.EOC_REF_NO,
      R.EOC_STAGE,
	  R.EOC_STAGE_SEQ,
      Q.EOC_BATCH,
	  Q.EOC_BATCH_SEQ,
      R.EOC_STAGE_STATUS,
      R.ERROR_CODE,
      R.ERROR_PARAM,
      R.ERROR,
      R.EOD_DATE,
      R.START_TIME,
      R.END_TIME
     from @DB_NAME.AETBS_EOC_RUNCHART_HISTORY R
	 LEFT JOIN @DB_NAME.AETB_EOC_PROGRAMS_history Q ON  Q.EOC_REF_NO=R.EOC_REF_NO AND Q.EOD_DATE=R.EOD_DATE AND  Q.EOC_BATCH_STATUS=''''A''''
     WHERE R.EOC_STAGE_STATUS =''''A'''' AND R.EOD_DATE=''''@BRANCH_DATE''''
	'') X ORDER BY BRANCH_CODE,START_TIME
	';

	SET @OPENQUERY='SELECT 
							 BRANCH_CODE, BRANCH_DATE, EOC_REF_NO, EOC_STAGE, EOC_STAGE_SEQ, EOC_BATCH, EOC_BATCH_SEQ, EOC_BATCH_STATUS, ERROR_CODE, ERROR_PARAM, ERROR, EOD_DATE, START_TIME, END_TIME
					FROM OPENQUERY([@SERVER_NAME],''';

	SET @OPENQUERY=@OPENQUERY+@SQL;
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@SERVER_NAME',@SERVER_NAME);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@DB_NAME',@DB_NAME);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@BRANCH_DATE',@BRANCH_DATE);

	PRINT @OPENQUERY;
	EXEC sp_executesql @OPENQUERY;

END
