CREATE PROC [dbo].[SP_RPT_CREDIT_PRO] @BRANCH_DATE DATE
AS
BEGIN
DECLARE @30 DATE= DATEADD(DAY,-29,@BRANCH_DATE)
DECLARE @60 DATE= DATEADD(DAY,-59,@BRANCH_DATE)
DECLARE @90 DATE= DATEADD(DAY,-89,@BRANCH_DATE)
DECLARE @COUNT INT
IF OBJECT_ID('tempdb..#30') IS NOT NULL
DROP TABLE #30
IF OBJECT_ID('tempdb..#60') IS NOT NULL
DROP TABLE #60
IF OBJECT_ID('tempdb..#90') IS NOT NULL
DROP TABLE #90
IF OBJECT_ID('tempdb..#EX') IS NOT NULL
DROP TABLE #EX
IF OBJECT_ID('tempdb..#VD') IS NOT NULL
DROP TABLE #VD
IF OBJECT_ID('tempdb..#EXCESS') IS NOT NULL
DROP TABLE #EXCESS
IF OBJECT_ID('tempdb..#IN') IS NOT NULL
DROP TABLE #IN
IF OBJECT_ID('tempdb..#INAC') IS NOT NULL
DROP TABLE #INAC
IF OBJECT_ID('tempdb..#DR') IS NOT NULL
DROP TABLE #DR
IF OBJECT_ID('tempdb..#CR') IS NOT NULL
DROP TABLE #CR
IF OBJECT_ID('tempdb..#INLESS') IS NOT NULL
DROP TABLE #INLESS
IF OBJECT_ID('tempdb..#IN60') IS NOT NULL
DROP TABLE #IN60
IF OBJECT_ID('tempdb..#30_') IS NOT NULL
DROP TABLE #30_
IF OBJECT_ID('tempdb..#60_') IS NOT NULL
DROP TABLE #60_
IF OBJECT_ID('tempdb..#90_') IS NOT NULL
DROP TABLE #90_
----------------CREDIT DEBIT DEBIT INTEREST-----------------
--select distinct EVENT,EVENT_DESCR from SGTB_AC_ENTRIES WHERE VALUE_DT BETWEEN @30 AND @BRANCH_DATE AND CUST_GL='A'

select CASE WHEN DRCR_IND='C' THEN SUM(LCY_AMOUNT) END C30,
CASE WHEN DRCR_IND='D' THEN SUM(LCY_AMOUNT) END D30,
CASE WHEN PRODUCT_DESCRIPTION LIKE '%Debit Interest%' THEN SUM(LCY_AMOUNT) END DI30,AC_NO INTO #30 from BBCSTAGE..SGTB_AC_ENTRIES WHERE VALUE_DT BETWEEN @30 AND @BRANCH_DATE AND CUST_GL='A' AND EVENT NOT IN ('REVL','REVR')
GROUP BY DRCR_IND,AC_NO,PRODUCT_DESCRIPTION

select CASE WHEN DRCR_IND='C' THEN SUM(LCY_AMOUNT) END C60,
CASE WHEN DRCR_IND='D' THEN SUM(LCY_AMOUNT) END D60,
CASE WHEN PRODUCT_DESCRIPTION LIKE '%Debit Interest%' THEN SUM(LCY_AMOUNT) END DI60,AC_NO INTO #60 from BBCSTAGE..SGTB_AC_ENTRIES WHERE VALUE_DT BETWEEN @60 AND @BRANCH_DATE AND CUST_GL='A' AND EVENT NOT IN ('REVL','REVR')
GROUP BY DRCR_IND,AC_NO,PRODUCT_DESCRIPTION

select CASE WHEN DRCR_IND='C' THEN SUM(LCY_AMOUNT) END C90,
CASE WHEN DRCR_IND='D' THEN SUM(LCY_AMOUNT) END D90,
CASE WHEN PRODUCT_DESCRIPTION LIKE '%Debit Interest%' THEN SUM(LCY_AMOUNT) END DI90,AC_NO INTO #90 from BBCSTAGE..SGTB_AC_ENTRIES WHERE VALUE_DT BETWEEN @90 AND @BRANCH_DATE AND CUST_GL='A' AND EVENT NOT IN ('REVL','REVR')
GROUP BY DRCR_IND,AC_NO,PRODUCT_DESCRIPTION

SELECT SUM(C30)C30,SUM(D30)D30,SUM(DI30)DI30,AC_NO INTO #30_ FROM #30 GROUP BY AC_NO
SELECT SUM(C60)C60,SUM(D60)D60,SUM(DI60)DI60,AC_NO INTO #60_ FROM #60 GROUP BY AC_NO
SELECT SUM(C90)C90,SUM(D90)D90,SUM(DI90)DI90,AC_NO INTO #90_ FROM #90 GROUP BY AC_NO

---------------EXCESS--------------
select AC.ACCOUNT_KEY,CUST_AC_NO,DSP_EFF_LINE_AMOUNT,LINK.LINE_START_DATE,LINK.LINE_EXPIRY_DATE,MAX(VAL_DT) VAL_DT INTO #EX from BBCDW..DIM_CUST_ACCOUNT AC 
INNER JOIN BBCDW..FACT_CUST_ACCOUNT_LINKAGES LINK ON AC.ACCOUNT_KEY=LINK.ACCOUNT_KEY
INNER JOIN BBCSTAGE..SGTB_VD_BAL BAL ON BAL.ACC=CUST_AC_NO
LEFT JOIN BBCDW..FACT_DAILY_FACILITY FA ON CONCAT(LINK.LINE_CODE,LINK.LINE_SERIAL)=CONCAT(FA.LINE_CODE,FA.LINE_SERIAL) AND FA.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
WHERE LINK.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) AND LCY_BAL<(DSP_EFF_LINE_AMOUNT*(-1)) AND LINK.LINE_EXPIRY_DATE>=@BRANCH_DATE
GROUP BY AC.ACCOUNT_KEY,CUST_AC_NO,DSP_EFF_LINE_AMOUNT,LINK.LINE_START_DATE,LINK.LINE_EXPIRY_DATE ORDER BY CUST_AC_NO
SELECT @COUNT=COUNT(*) FROM #EX

SELECT TOP (@COUNT)  BAL.VAL_DT,ACC,LCY_BAL INTO #VD FROM BBCSTAGE..SGTB_VD_BAL BAL INNER JOIN #EX E ON BAL.ACC=E.CUST_AC_NO WHERE BAL.VAL_DT<=@BRANCH_DATE ORDER BY BAL.VAL_DT DESC

SELECT ACCOUNT_KEY,CUST_AC_NO,DSP_EFF_LINE_AMOUNT,LINE_START_DATE,LINE_EXPIRY_DATE,DATEDIFF(DAY,E.VAL_DT,V.VAL_DT)+1 EXCESS INTO #EXCESS FROM #EX E INNER JOIN #VD V ON E.CUST_AC_NO=V.ACC
WHERE DSP_EFF_LINE_AMOUNT<(V.LCY_BAL*(-1))

-------------INACTIVE---------------
SELECT DATEDIFF(DAY,MAX(VALUE_DT),@BRANCH_DATE) VALUE_DT,DRCR_IND,AC_NO INTO #IN FROM BBCSTAGE..SGTB_AC_ENTRIES WHERE CUST_GL='A' AND EVENT IN ('DSBR','INIT','DEBK','LIQD')
GROUP BY DRCR_IND,AC_NO
UNION ALL
SELECT DATEDIFF(DAY,MAX(AC.AC_OPEN_DATE),@BRANCH_DATE),'C',CUST_AC_NO FROM BBCDW..DIM_CUST_ACCOUNT AC LEFT OUTER JOIN BBCSTAGE..SGTB_AC_ENTRIES S ON AC.CUST_AC_NO=S.AC_NO WHERE IS_CURRENT=1 AND  ACCOUNT_CLASS NOT IN ('INTERN','NOSTRO') AND S.AC_NO IS NULL
GROUP BY CUST_AC_NO
SELECT MAX(VALUE_DT) VALUE_DT,AC_NO INTO #INAC FROM #IN GROUP BY AC_NO HAVING MAX(VALUE_DT)>=30

-----------INFLOW SMALLER THAN DR-----------
SELECT SUM(LCY_AMOUNT) DRINT,AC_NO INTO #DR FROM BBCSTAGE..SGTB_AC_ENTRIES WHERE CUST_GL='A' AND PRODUCT_DESCRIPTION LIKE '%Debit Interest%'
GROUP BY AC_NO
SELECT SUM(LCY_AMOUNT) CR,S.AC_NO INTO #CR FROM BBCSTAGE..SGTB_AC_ENTRIES S WHERE CUST_GL='A' AND EVENT IN ('DSBR','INIT','LIQD') AND DRCR_IND='C'
GROUP BY S.AC_NO

SELECT ISNULL(CR,0)CR,ISNULL(#CR.AC_NO,#DR.AC_NO) AC_NO,ISNULL(DRINT,0) DRINT INTO #INLESS FROM #CR FULL JOIN #DR ON #CR.AC_NO=#DR.AC_NO
WHERE ISNULL(CR,0)<ISNULL(DRINT,0)

---------------NO INFLOW 60DAYS-----------
SELECT MAX(VALUE_DT) VALUE_DT,AC_NO INTO #IN60  FROM #IN GROUP BY AC_NO,DRCR_IND HAVING MAX(VALUE_DT)>60 AND DRCR_IND='C' 

SELECT AC_DESC,AC.CUST_AC_NO,C30,C60,C90,
D30,D60,D90,
DI30,DI60,DI90,isnull(C30,0)-isnull(D30,0)DE30,isnull(C60,0)-isnull(D60,0)DE60,isnull(C90,0)-isnull(D90,0)DE90,#EX.DSP_EFF_LINE_AMOUNT LIMIT_AMOUNT,#EX.LINE_START_DATE START_DATE,#EX.LINE_EXPIRY_DATE END_DATE,EXCESS,
#INAC.VALUE_DT INACTIVE,CASE WHEN L.AC_NO IS NOT NULL THEN 'YES' ELSE 'NO' END INFLOW_DEBIT,#IN60.VALUE_DT NOINFLOW60,
CASE WHEN EXCESS IS NULL AND #INAC.VALUE_DT IS NULL AND L.AC_NO IS NULL AND #IN60.VALUE_DT IS NULL 
 THEN 'OK' END STATUS FROM BBCDW..DIM_CUST_ACCOUNT AC 
LEFT JOIN #30_ ON AC.CUST_AC_NO=#30_.AC_NO
LEFT JOIN #60_ ON AC.CUST_AC_NO=#60_.AC_NO
LEFT JOIN #90_ ON AC.CUST_AC_NO=#90_.AC_NO
LEFT JOIN #EXCESS EX ON AC.ACCOUNT_KEY=EX.ACCOUNT_KEY
LEFT JOIN #EX ON AC.ACCOUNT_KEY=#EX.ACCOUNT_KEY
LEFT JOIN #INAC ON AC.CUST_AC_NO=#INAC.AC_NO
LEFT JOIN #INLESS L ON AC.CUST_AC_NO=L.AC_NO
LEFT JOIN #IN60 ON AC.CUST_AC_NO=#IN60.AC_NO
WHERE AC.IS_CURRENT=1 AND ACCOUNT_CLASS NOT IN ('INTERN','NOSTRO') 
END
