CREATE PROC [dbo].[SP_RPT_LOAN_PERIOD_MONTH] @BRANCH_DATE DATE
AS
BEGIN
IF OBJECT_ID('tempdb..#SIZE') IS NOT NULL
  DROP TABLE #SIZE
IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
CREATE TABLE #SIZE (ID SMALLINT,SIZE VARCHAR(100))
INSERT INTO #SIZE
SELECT 1,'aUP TO 1M'
INSERT INTO #SIZE
SELECT 2,'b>1 TO 3M'
INSERT INTO #SIZE
SELECT 3,'c>3 TO 6M'
INSERT INTO #SIZE
SELECT 4,'d>6 TO 12M'
INSERT INTO #SIZE
SELECT 5,'e>1Y TO 2Y'
INSERT INTO #SIZE
SELECT 6,'f>2Y TO 3Y'
INSERT INTO #SIZE
SELECT 7,'g>3Y TO 4Y'
INSERT INTO #SIZE
SELECT 8,'h>4Y TO 5Y'
INSERT INTO #SIZE
SELECT 9,'i>5Y TO 10Y'
INSERT INTO #SIZE
SELECT 10,'j>10Y'
select AC_DESC FULL_NAME,CUST_AC_NO,CASE WHEN LEFT(CL.PRODUCT_DESC,6) LIKE '%CO%' THEN 'CORPORATE'
when CL.PRODUCT_DESC LIKE '%House%' THEN 'HOUSING LOAN' ELSE 'INDIVIDUAL' END CUSTOMER_CATEGORY,
CASE WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE)<=30 THEN 1
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) <=90 THEN 2
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) <=180 THEN 3
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) <=360 THEN 4
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) <=720 THEN 5
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) <=1080 THEN 6
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) <=1440 THEN 7
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) <=1800 THEN 8
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) <=3600 THEN 9
WHEN DATEDIFF(DAY,@BRANCH_DATE,MATURITY_DATE) >3600 THEN 10 END SIZE,IM.PRINCIPAL_OS PRINCIPAL_OS,MATURITY_DATE INTO #TMP from DIM_LOAN_ACCOUNT CN
INNER JOIN BBCDW..FACT_DAILY_IACR_LOAN IM ON CN.LOAN_AC_KEY=IM.LOAN_AC_KEY
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC  ON AC.CUST_AC_NO=CN.DR_AC_NO AND AC.IS_CURRENT=1
INNER JOIN BBCDW..DIM_CL_PRODUCT CL ON CL.PRODUCT_CODE=CN.PRODUCT_CODE AND CL.IS_CURRENT=1
where IM.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)

UNION ALL

select AC_DESC FULL_NAME,CUST_AC_NO,CASE WHEN LEFT(CL.PRODUCT_DESC,6) LIKE '%CO%' THEN 'CORPORATE'
when CL.PRODUCT_DESC LIKE '%House%' THEN 'HOUSING LOAN' ELSE 'INDIVIDUAL' END CUSTOMER_CATEGORY,
1 SIZE,IM.INTEREST_ACCRUED_BAL PRINCIPAL_OS,MATURITY_DATE  from DIM_LOAN_ACCOUNT CN
INNER JOIN BBCDW..FACT_DAILY_IACR_LOAN IM ON CN.LOAN_AC_KEY=IM.LOAN_AC_KEY
INNER JOIN BBCDW..DIM_CUST_ACCOUNT AC  ON AC.CUST_AC_NO=CN.DR_AC_NO AND AC.IS_CURRENT=1
INNER JOIN BBCDW..DIM_CL_PRODUCT CL ON CL.PRODUCT_CODE=CN.PRODUCT_CODE AND CL.IS_CURRENT=1
where IM.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)

SELECT FULL_NAME,CUST_AC_NO,CUSTOMER_CATEGORY,SUM(ISNULL(PRINCIPAL_OS,0)) LCY_CUR_BAL,S.SIZE,T.MATURITY_DATE EXP_DATE FROM #SIZE S LEFT JOIN #TMP T ON S.ID=T.SIZE
GROUP BY FULL_NAME,CUST_AC_NO,CUSTOMER_CATEGORY,S.SIZE,T.MATURITY_DATE

END
