create proc [dbo].[SP_RPT_NBC_BALANCE_SHEET] @REPORT_DATE DATE,@EX_RATE MONEY
AS
BEGIN
 IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
 IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
  DROP TABLE #TMP1
SELECT * INTO #TMP FROM BBCNBCMART..FACT_BS_ASSET WHERE DATE_KEY=CONVERT(VARCHAR,@REPORT_DATE,112)
;with C as
(
  select T.ITEM_KEY,T.CLO_LCY_BAL,T.CLO_FCY_BAL,T.PRO_LCY_BAL,T.PRO_FCY_BAL,T.ITEM_KEY as RootID from #TMP T
  union all
  select T.ITEM_KEY,T.CLO_LCY_BAL,T.CLO_FCY_BAL,T.PRO_LCY_BAL,T.PRO_FCY_BAL,C.RootID from #TMP T
  inner join C on T.Parent = C.ITEM_KEY
)
select T.DATE_KEY, T.ITEM_KEY,T.Parent,T.Description,T.CLO_LCY_BAL,S.CLO_LCY_BAL_TOTAL,
T.CLO_FCY_BAL,S.CLO_FCY_BAL_TOTAL,PRO_LCY_BAL,PRO_LCY_BAL_TOTAL,PRO_FCY_BAL,PRO_FCY_BAL_TOTAL INTO #TMP1 from #TMP T
  inner join (
             select RootID,sum(CLO_LCY_BAL) as CLO_LCY_BAL_TOTAL,sum(CLO_FCY_BAL) as CLO_FCY_BAL_TOTAL,
			 sum(PRO_LCY_BAL) as PRO_LCY_BAL_TOTAL,sum(PRO_FCY_BAL) as PRO_FCY_BAL_TOTAL from C group by RootID
             ) as S
    on T.ITEM_KEY = S.RootID
order by T.ITEM_KEY
option (maxrecursion 0)

UPDATE #TMP1

    SET CLO_LCY_BAL_TOTAL = h.CLO_LCY_BAL_TOTAL,
	CLO_FCY_BAL_TOTAL=h.CLO_FCY_BAL_TOTAL,
	PRO_LCY_BAL_TOTAL=h.PRO_LCY_BAL_TOTAL,
	PRO_FCY_BAL_TOTAL=h.PRO_FCY_BAL_TOTAL

    FROM #TMP1 ut CROSS JOIN
         (select SUM(CLO_LCY_BAL_TOTAL) as CLO_LCY_BAL_TOTAL,SUM(CLO_FCY_BAL_TOTAL) as CLO_FCY_BAL_TOTAL,
		 SUM(PRO_LCY_BAL_TOTAL) PRO_LCY_BAL_TOTAL,SUM(PRO_FCY_BAL_TOTAL) PRO_FCY_BAL_TOTAL from #TMP1 where Parent=0) h
    WHERE ut.Parent IS NULL;

SELECT DATE_KEY,ITEM_KEY,Parent,Description,
CLO_LCY_BAL_TOTAL*@EX_RATE CLO_LCY_BAL_TOTAL,
CLO_FCY_BAL_TOTAL*@EX_RATE CLO_FCY_BAL_TOTAL,
PRO_LCY_BAL_TOTAL*@EX_RATE PRO_LCY_BAL_TOTAL,
PRO_FCY_BAL_TOTAL*@EX_RATE PRO_FCY_BAL_TOTAL FROM #TMP1 order by ITEM_KEY
END
