CREATE PROC [dbo].[SP_RPT_LOAN_LISTING_RETAIL] @FROM_DATE AS DATE,
	@BRANCH_CODE AS VARCHAR(500),@PRODUCT_CODE AS VARCHAR(500),
	@PRODUCT_CAT AS VARCHAR(1000),@RM_ID AS VARCHAR(1000), 
	@CCY AS VARCHAR(100), @LOAN_AC_NO AS VARCHAR(35)
AS
BEGIN
IF OBJECT_ID('tempdb..#GUA') IS NOT NULL
  DROP TABLE #GUA	
Select distinct ST2.LOAN_AC_KEY,ST2.RESPONSIBILITY,
    substring(
        (
            Select ','+C.FULL_NAME  AS [text()]
            From (SELECT * FROM  FACT_LOAN_GUARANTOR G 
WHERE G.RESPONSIBILITY='GUA' and DATE_KEY=CONVERT(VARCHAR,@FROM_DATE,112)) ST1 INNER JOIN DIM_CUSTOMER C ON  ST1.CUSTOMER_KEY=C.CUSTOMER_KEY
            Where ST1.LOAN_AC_KEY = ST2.LOAN_AC_KEY
            ORDER BY ST1.LOAN_AC_KEY
            For XML PATH ('')
        ), 2, 1000) GUARANTOR INTO #GUA
From (SELECT * FROM  FACT_LOAN_GUARANTOR G WHERE G.RESPONSIBILITY='GUA' and DATE_KEY=CONVERT(VARCHAR,@FROM_DATE,112)) ST2 INNER JOIN DIM_CUSTOMER C1 ON  ST2.CUSTOMER_KEY=C1.CUSTOMER_KEY

	SELECT 
	L.OVERALL_LIMIT,LINK.OVERALL_AMOUNT FACILITY_LIMIT,F.FINANCED_AMT-F.DISBURSED_AMT OVERDRAWN,EMI_AMOUNT,ODIN,ODPR,
CAST(DATEDIFF(M, VALUE_DATE, MATURITY_DATE) AS varchar)+ ' M' TENOR
,AC.FIELD_CHAR_7 LOAN_TYPE,AC.USER_DEFINED_STATUS CLASSIFICATION,
	C.RESIDENT_STATUS BORROWER_TYPE,RE.LOV_DESC REAL_ESTATE,G.GUARANTOR GUARANTOR_NAME,SE.LOV_DESC SECURED,OWN.LOV_DESC OWNERSHIP,CODE.LOV INDUSTRY_CODE,
	CODE.LOV_DESC INDUSTRY_DESC,FIELD_CHAR_9 PURPOSE,PUR.LOV_DESC PURPOSE_DESC,

		F.DATE_KEY,
		CONVERT(DATE, CAST(F.DATE_KEY AS VARCHAR(8)), 112) BRANCH_DATE,
		BR.BRANCH_CODE,
		RM.RM_ID,AC.LOAN_AC_NO,C.CUSTOMER_NO,C.P_SEX GENDER,C.FULL_NAME,
		PR.PRODUCT_CODE,PR.PRODUCT_DESC,PC.PRODUCT_CATEGORY PRODUCT_CAT,
		AC.VALUE_DATE,AC.MATURITY_DATE,CY.CCY_CODE CURRENCY,F.FINANCED_AMT,F.DISBURSED_AMT,
		F.TOTAL_PRINCIPAL,F.TOTAL_INTEREST,F.INTEREST_RATE,F.PRINCIPAL_PAID,F.PRINCIPAL_OS,
			F.INTEREST_PAID,F.INTEREST_OS,F.INTEREST_ACCRUED,F.LAST_PRINCIPAL_BAL,F.LAST_INTEREST_BAL,
			F.INTEREST_ACCRUED_BAL,F.TOTAL_ACCRUED,F.START_UNPAID_DATE,F.OVERDUE_DAY,F.PRINCIPAL_OVERDUE,F.INTEREST_OVERDUE,sum(COL.COLLATERAL_VALUE) COLLATERAL_VALUE
	FROM FACT_DAILY_IACR_LOAN F
	INNER JOIN DIM_BBC_BRANCH BR ON F.BRANCH_KEY=BR.BRANCH_KEY
	INNER JOIN DIM_LOAN_ACCOUNT AC ON F.LOAN_AC_KEY=AC.LOAN_AC_KEY
	INNER JOIN DIM_CUSTOMER C ON F.CUSTOMER_KEY=C.CUSTOMER_KEY
	INNER JOIN DIM_CL_PRODUCT PR ON F.PRODUCT_KEY=PR.PRODUCT_KEY
	INNER JOIN DIM_CL_PRODUCT_CATE PC ON F.PRODUCT_CATE_KEY=PC.PRODUCT_CATE_KEY
	INNER JOIN DIM_RELATION_MANAGER RM ON F.RM_KEY=RM.RM_KEY
	INNER JOIN DIM_CURRENCY CY ON F.CURRENCY_KEY=CY.CCY_KEY
	INNER JOIN DIM_LIAB L ON L.LIAB_NO=C.CUSTOMER_NO AND L.IS_CURRENT=1
	LEFT JOIN (select ACCOUNT_NUMBER,DSP_EFF_LINE_AMOUNT OVERALL_AMOUNT from BBCSTAGE..SGTB_CL_LINKAGE l INNER JOIN FACT_DAILY_FACILITY FACI ON L.LINKED_REFERENCE_NO=CONCAT(FACI.LINE_CODE,LINE_SERIAL) AND DATE_KEY=CONVERT(VARCHAR,@FROM_DATE,112)) LINK ON AC.LOAN_AC_NO=LINK.ACCOUNT_NUMBER
	left JOIN DIM_COLL COL ON COL.LIAB_ID=L.ID AND COL.IS_CURRENT=1
	LEFT JOIN #GUA G ON G.LOAN_AC_KEY=AC.LOAN_AC_KEY
	LEFT JOIN BBCDW..DIM_UDF_VAL V ON C.CUSTOMER_NO=V.REC_KEY AND V.IS_CURRENT=1
	LEFT JOIN (SELECT FIELD_NAME,LOV,LOV_DESC FROM DIM_UDF_LOV WHERE FIELD_NAME='REAL_ESTATE' AND IS_CURRENT=1 ) RE ON AC.FIELD_CHAR_8=RE.LOV
	LEFT JOIN (SELECT FIELD_NAME,LOV,LOV_DESC FROM DIM_UDF_LOV WHERE FIELD_NAME='SECURITY INDICATOR' AND IS_CURRENT=1) SE ON AC.FIELD_CHAR_6=SE.LOV
	LEFT JOIN BBCDW..DIM_UDF_LOV OWN ON V.FIELD_VAL_16=OWN.LOV AND OWN.FIELD_NAME='OWNERSHIP_CIF'
	LEFT JOIN BBCDW..DIM_UDF_LOV CODE ON V.FIELD_VAL_15=CODE.LOV AND CODE.FIELD_NAME='INDUSTRY_CODE'
	LEFT JOIN (SELECT FIELD_NAME,LOV,LOV_DESC FROM DIM_UDF_LOV WHERE FIELD_NAME='LOAN_PURPOSE' AND IS_CURRENT=1) PUR ON AC.FIELD_CHAR_9=PUR.LOV
	INNER JOIN BBCDW..DIM_CUST_ACCOUNT ACC ON AC.CR_AC_NO=ACC.CUST_AC_NO AND ACC.IS_CURRENT=1 AND AC.IS_CURRENT=1
	WHERE F.DATE_KEY=CONVERT(VARCHAR,@FROM_DATE,112) AND LEFT(PRODUCT_DESC,6) like '%IN%'
	GROUP BY BR.BRANCH_CODE,
RM.RM_ID,AC.LOAN_AC_NO,C.CUSTOMER_NO,C.P_SEX,C.FULL_NAME,
PR.PRODUCT_CODE,PR.PRODUCT_DESC,PC.PRODUCT_CATEGORY,
AC.VALUE_DATE,AC.MATURITY_DATE,CY.CCY_CODE,F.FINANCED_AMT,F.DISBURSED_AMT,
F.TOTAL_PRINCIPAL,F.TOTAL_INTEREST,F.INTEREST_RATE,F.PRINCIPAL_PAID,F.PRINCIPAL_OS,
F.INTEREST_PAID,F.INTEREST_OS,F.INTEREST_ACCRUED,F.LAST_PRINCIPAL_BAL,F.LAST_INTEREST_BAL,
F.INTEREST_ACCRUED_BAL,F.TOTAL_ACCRUED,F.START_UNPAID_DATE,F.OVERDUE_DAY,F.PRINCIPAL_OVERDUE,F.INTEREST_OVERDUE,L.OVERALL_LIMIT,LINK.OVERALL_AMOUNT,
EMI_AMOUNT,ODIN,ODPR,FIELD_CHAR_7,USER_DEFINED_STATUS,RESIDENT_STATUS,RE.LOV_DESC,GUARANTOR,SE.LOV_DESC,OWN.LOV_DESC,CODE.LOV,
CUSTOMER_TYPE,FIELD_CHAR_9,PUR.LOV_DESC,F.DATE_KEY

END
