-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 21-SEP-2016
-- Description:	Daily GL Balance Movement
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_GLBAL_MOVMENT]
	@FROM_DATE AS DATE ,@TO_DATE AS DATE,@BRANCH AS NVARCHAR(200),@CCY AS NVARCHAR(100),@AC_NO AS VARCHAR(20)
AS
BEGIN
	

	SELECT 
		GM.GL_CODE,GM.GL_DESC,CY.CCY_CODE CCY,
		SUM(B.DR_MOV_FCY) DR_MOV_FCY,
		 SUM(B.CR_MOV_FCY) CR_MOV_FCY,
		 SUM(B.DR_MOV_LCY) DR_MOV_LCY,
		 SUM(B.CR_MOV_LCY) CR_MOV_LCY
	FROM FACT_DAILY_GL_BAL B 
	INNER JOIN DIM_GLMASTER GM ON B.GL_KEY=GM.GL_KEY
	INNER JOIN DIM_GLCATEGORY GC ON B.CATEGORY_KEY=GC.CATEGORY_KEY
	INNER JOIN DIM_CURRENCY CY ON B.CCY_KEY=CY.CCY_KEY
	INNER JOIN DIM_BBC_BRANCH BR ON B.BRANCH_KEY=BR.BRANCH_KEY
	WHERE B.LEAF='Y'
	AND B.DATE_KEY BETWEEN CONVERT(VARCHAR,@FROM_DATE,112) AND CONVERT(VARCHAR,@TO_DATE,112)
	AND BR.BRANCH_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@BRANCH,',')) 
	AND CY.CCY_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@CCY,',')) 
	AND GM.GL_CODE LIKE @AC_NO+'%'
	GROUP BY GM.GL_CODE,GM.GL_DESC,CY.CCY_CODE
	ORDER BY GM.GL_CODE,CY.CCY_CODE

END
