create proc [dbo].[SP_RPT_NBC_BALANCE_SHEET_LI] @REPORT_DATE DATE,@EX_RATE MONEY
AS
BEGIN
 IF OBJECT_ID('tempdb..#TMP2') IS NOT NULL
  DROP TABLE #TMP2
 IF OBJECT_ID('tempdb..#TMP3') IS NOT NULL
  DROP TABLE #TMP3
  SELECT * INTO #TMP2 FROM BBCNBCMART..FACT_BS_LIABILITY WHERE DATE_KEY=CONVERT(VARCHAR,@REPORT_DATE,112)
 
;with D as
(
  select T.ITEM_KEY,T.CLO_LCY_BAL,T.CLO_FCY_BAL,T.ITEM_KEY as RootID from #TMP2 T
  union all
  select T.ITEM_KEY,T.CLO_LCY_BAL,T.CLO_FCY_BAL,D.RootID from #TMP2 T
  inner join D on T.Parent = D.ITEM_KEY
)
select T.DATE_KEY, T.ITEM_KEY,T.Parent,T.Description,T.CLO_LCY_BAL,S.CLO_LCY_BAL_TOTAL,
T.CLO_FCY_BAL,S.CLO_FCY_BAL_TOTAL INTO #TMP3 from #TMP2 T
  inner join (
             select RootID,sum(CLO_LCY_BAL) as CLO_LCY_BAL_TOTAL,sum(CLO_FCY_BAL) as CLO_FCY_BAL_TOTAL from D group by RootID
             ) as S
    on T.ITEM_KEY = S.RootID
order by T.ITEM_KEY
option (maxrecursion 0)

UPDATE #TMP3

    SET CLO_LCY_BAL_TOTAL = h.CLO_LCY_BAL_TOTAL,
	CLO_FCY_BAL_TOTAL=h.CLO_FCY_BAL_TOTAL

    FROM #TMP3 ut CROSS JOIN
         (select SUM(CLO_LCY_BAL_TOTAL) as CLO_LCY_BAL_TOTAL,SUM(CLO_FCY_BAL_TOTAL) as CLO_FCY_BAL_TOTAL from #TMP3 where Parent=0) h
    WHERE ut.Parent IS NULL;

SELECT DATE_KEY,ITEM_KEY,Parent,Description,
CLO_LCY_BAL_TOTAL*@EX_RATE CLO_LCY_BAL_TOTAL,
CLO_FCY_BAL_TOTAL*@EX_RATE CLO_FCY_BAL_TOTAL
FROM #TMP3 order by ITEM_KEY
END
