CREATE proc [dbo].[SP_RPT_MONTHLY_CL_IACR_LOAN] @FROM_DATE AS DATE, @TO_DATE AS DATE, 
	@BRANCH_CODE AS VARCHAR(500),@PRODUCT_CODE AS VARCHAR(500),
	@PRODUCT_CAT AS VARCHAR(1000),@RM_ID AS VARCHAR(1000), 
	@CCY AS VARCHAR(100), @LOAN_AC_NO AS VARCHAR(35)
AS
BEGIN
IF OBJECT_ID('tempdb..#AVG') IS NOT NULL
  DROP TABLE #AVG
IF OBJECT_ID('tempdb..#AVG1') IS NOT NULL
  DROP TABLE #AVG1
IF OBJECT_ID('tempdb..#AVG2') IS NOT NULL
  DROP TABLE #AVG2

SELECT LOAN_AC_KEY,cast(CONVERT(varchar,MIN(DATE_KEY)) as date) min_day,cast(CONVERT(varchar,max(DATE_KEY)) as date) max_day,
PRINCIPAL_OS INTO #AVG FROM BBCDW..FACT_DAILY_IACR_LOAN
where DATE_KEY BETWEEN CONVERT(VARCHAR,@FROM_DATE,112) AND CONVERT(VARCHAR,@TO_DATE,112)
GROUP BY LOAN_AC_KEY,PRINCIPAL_OS

select *,DATEDIFF(DAY,min_day,max_day)+1 days,
PRINCIPAL_OS*(DATEDIFF(DAY,min_day,max_day)+1) BALANCE INTO #AVG1 from #AVG 
order by LOAN_AC_KEY,min_day,max_day

SELECT LOAN_AC_KEY,
(SUM(BALANCE)/(DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1) AVG_BALANCE
INTO #AVG2 FROM #AVG1 group by LOAN_AC_KEY

select BR.BRANCH_CODE,RM.RM_ID,AC.LOAN_AC_NO,CA.AC_DESC,CUS.CUSTOMER_NO,P_SEX,CL.PRODUCT_CODE,CL.PRODUCT_DESC,
V.AVG_BALANCE,ISNULL((L.INTEREST_PAID*365/AVG_BALANCE/((DATEDIFF(DAY,@FROM_DATE,@TO_DATE))+1)),0) AVERAGE_RATE,
VALUE_DATE,MATURITY_DATE,CU.CCY_CODE,FINANCED_AMT,TOTAL_INTEREST,PRINCIPAL_PAID,PRINCIPAL_OS,INTEREST_RATE,INTEREST_PAID,INTEREST_OS,
INTEREST_ACCRUED,INTEREST_ACCRUED_BAL,LAST_PRINCIPAL_BAL,LAST_INTEREST_BAL,START_UNPAID_DATE,OVERDUE_DAY,PRINCIPAL_OVERDUE,INTEREST_OVERDUE from BBCDW..FACT_DAILY_IACR_LOAN L
INNER JOIN BBCDW..DIM_LOAN_ACCOUNT AC ON AC.LOAN_AC_KEY=L.LOAN_AC_KEY 
INNER JOIN BBCDW..DIM_CUST_ACCOUNT CA ON CA.ACCOUNT_KEY=L.ACCOUNT_KEY
INNER JOIN BBCDW..DIM_CL_PRODUCT CL ON CL.PRODUCT_KEY=L.PRODUCT_KEY
INNER JOIN BBCDW..DIM_CL_PRODUCT_CATE CATE ON CATE.PRODUCT_CATE_KEY=L.PRODUCT_CATE_KEY
INNER JOIN BBCDW..DIM_CURRENCY CU ON CU.CCY_KEY=L.CURRENCY_KEY
INNER JOIN BBCDW..DIM_BBC_BRANCH BR ON BR.BRANCH_KEY=L.BRANCH_KEY
INNER JOIN BBCDW..DIM_RELATION_MANAGER RM ON RM.RM_KEY=L.RM_KEY AND RM.BRANCH_CODE=1
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_KEY=L.CUSTOMER_KEY
INNER JOIN #AVG2 V ON V.LOAN_AC_KEY=L.LOAN_AC_KEY
where DATE_KEY=CONVERT(VARCHAR,@TO_DATE,112)
AND AC.BRANCH_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@BRANCH_CODE,',')) 
			  AND AC.PRODUCT_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@PRODUCT_CODE,',')) 
			  AND CATE.PRODUCT_CATEGORY collate database_default IN(SELECT Value FROM dbo.FnSplit(@PRODUCT_CAT,',')) 
			  AND RM.RM_ID collate database_default IN(SELECT Value FROM dbo.FnSplit(@RM_ID,',')) 
			  AND AC.CURRENCY collate database_default IN(SELECT Value FROM dbo.FnSplit(@CCY,',')) 
			  AND AC.LOAN_AC_NO LIKE '%'+ UPPER(@LOAN_AC_NO) + '%'
END
