
CREATE PROCEDURE [dbo].[SP_RPT_NBC_MNT_COA_UNF]
	@DATE AS date,@RATE money
AS
BEGIN

declare @para int =cast(CONVERT(VARCHAR,@DATE,112) as int)
	IF OBJECT_ID('tempdb..#tmp') IS NOT NULL
  DROP TABLE #tmp
  	IF OBJECT_ID('tempdb..#TMPP') IS NOT NULL
  DROP TABLE #TMPP
  	IF OBJECT_ID('tempdb..#tmp0') IS NOT NULL
  DROP TABLE #tmp0
  	IF OBJECT_ID('tempdb..#TMP4') IS NOT NULL
  DROP TABLE #TMP4
  	IF OBJECT_ID('tempdb..#TMP3') IS NOT NULL
  DROP TABLE #TMP3
  	IF OBJECT_ID('tempdb..#TMP1') IS NOT NULL
  DROP TABLE #TMP1
  	IF OBJECT_ID('tempdb..#TMP2') IS NOT NULL
  DROP TABLE #TMP2

	select * into #tmp from FN_GET_NBC_COA_BAL(@para)

	update #tmp set nbc_code=LEFT(nbc_code,3)+'1'  where nbc_code='3865'
	update #tmp set CURRENCY=CONCAT('1',RIGHT(CURRENCY,1)) where NBC_CODE='3196'
	update #tmp set currency=LEFT(currency,1)+'9' where CONCAT(NBC_CODE,CURRENCY) not in (SELECT CONCAT(NBC_CODE,CURRENCY) FROM #tmp A inner JOIN DIM_NBC_COA AC ON CONCAT(AC.L1,AC.L2,AC.L3,AC.L4)=CONCAT(NBC_CODE,CURRENCY) where leaf='Y') and leaf='Y'
	update #tmp set currency=LEFT(currency,1)+'0' where leaf='N'

	SELECT CA.AC_LEVEL,CA.L1,CA.L2,CA.L3,CA.L4,CA.AC_DESC,isnull(SUM(T.LCY_BAL),0) USD_BAL INTO #TMPP FROM DIM_NBC_COA CA left JOIN #TMP T ON CONCAT(CA.L1,CA.L2,CA.L3,CA.L4)=CONCAT(NBC_CODE,CURRENCY)
	 GROUP BY CA.AC_LEVEL,CA.L1,CA.L2,CA.L3,CA.L4,CA.AC_DESC
	 ORDER BY CA.L1,CA.L2,CA.L3,CA.L4,CA.AC_LEVEL

SELECT CONCAT(L1,L2,L3,LEFT(L4,1)) ID,SUM(USD_BAL) BAL INTO #TMP4 FROM #TMPP WHERE AC_LEVEL=5 GROUP BY L1,L2,L3,L4
SELECT LEFT(L1,1)ID,SUM(USD_BAL) BAL into #tmp0 FROM #TMPP WHERE AC_LEVEL=5 GROUP BY L1 order by L1
SELECT CONCAT(L1,L2,L3) ID,SUM(USD_BAL) BAL into #TMP3 FROM #TMPP WHERE AC_LEVEL=5 GROUP BY L1,L2,L3
SELECT CONCAT(L1,L2) ID,SUM(USD_BAL) BAL into #TMP2 FROM #TMPP WHERE AC_LEVEL=5 GROUP BY L1,L2
SELECT L1 ID,SUM(USD_BAL) BAL into #TMP1 FROM #TMPP WHERE AC_LEVEL=5 GROUP BY L1

	 UPDATE T SET USD_BAL=BAL FROM #TMPP T INNER JOIN (select ID,SUM(BAL) BAL from #TMP4 group by ID) C ON CONCAT(T.L1,T.L2,T.L3,LEFT(T.L4,1))=C.ID WHERE AC_LEVEL=4
	 UPDATE T SET USD_BAL=BAL FROM #TMPP T INNER JOIN (select ID,SUM(BAL) BAL from #TMP3 group by ID) C ON CONCAT(T.L1,T.L2,T.L3)=C.ID WHERE AC_LEVEL=3
	 UPDATE T SET USD_BAL=BAL FROM #TMPP T INNER JOIN (select ID,SUM(BAL) BAL from #TMP2 group by ID) C ON CONCAT(T.L1,T.L2)=C.ID WHERE AC_LEVEL=2
	 UPDATE T SET USD_BAL=BAL FROM #TMPP T INNER JOIN (select ID,SUM(BAL) BAL from #TMP1 group by ID) C ON T.L1=C.ID WHERE AC_LEVEL=1
	 UPDATE T SET USD_BAL=BAL FROM #TMPP T INNER JOIN (select ID,SUM(BAL) BAL from #tmp0 group by ID) C ON LEFT(T.L1,1)=C.ID WHERE AC_LEVEL=0
	 SELECT AC_LEVEL,L1,L2,L3,L4,AC_DESC,isnull(USD_BAL,0) USD_BAL,isnull(USD_BAL,0)*@RATE KHR_BAL,@RATE EX_RATE FROM #TMPP ORDER BY L1,L2,L3,L4,AC_LEVEL
	 
END
