--=========================================
--==============DEVELOPMENT HISTORY========
--CREATED BY	:	BUNCHHOEUN CHHIM
--CREATED DATE	:	13-FEB-18
--DESCR			:	FILTER ACCOUNT CLOSED 
--				:	CASA ONLY (EXCLUDED TD)
--==========================================
--ALTER PROC [dbo].[RPT_CUST_PORTFOLIO_CLOSE] @BRANCH_DATE DATE
CREATE PROC [dbo].[SP_RPT_CASA_ACC_CLOSE] 
	@START_DT DATE, @END_DT DATE
AS
BEGIN
	SELECT * 
	FROM FACT_CUSTOMER_PORTFOLIO 
	WHERE RECORD_STAT = 'C' 
		AND ACCOUNT_TYPE IN ('U','S')
		AND DATE_KEY <= CONVERT(VARCHAR, @END_DT, 112) AND DATE_KEY >= CONVERT(VARCHAR, @START_DT, 112)
END
