CREATE PROC [dbo].[SP_RPT_NBC_TOP_20_DEP] @BRANCH_DATE DATE
AS
BEGIN
	IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
select * into #TMP from BBCNBCMART..FACT_DEPO_TOP_20 where DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
SELECT ROW_NUMBER() OVER(ORDER BY LCY_BALANCE DESC) AS ID,T.CCY_DESC,DEPO_TYPE_DESC,DEPO_TYPE,ISNULL(AC_DESC,'')AC_DESC,ISNULL(RES_STATUS,'') RES_STATUS,ISNULL(CUS_CLASS,'')CUS_CLASS,ISNULL(LCY_BALANCE,0)LCY_BALANCE  FROM BBCNBCMART..DIM_DEP_TOP20 T LEFT JOIN #TMP F ON T.CCY=F.CCY AND T.DEPO_TYPE=F.ACCOUNT_TYPE
ORDER BY LCY_BALANCE DESC
END
