CREATE PROC [dbo].[SP_RPT_OD_PERIOD_MONTH] @BRANCH_DATE DATE
AS
BEGIN
IF OBJECT_ID('tempdb..#SIZE') IS NOT NULL
  DROP TABLE #SIZE
IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
CREATE TABLE #SIZE (ID SMALLINT,SIZE VARCHAR(100))
INSERT INTO #SIZE
SELECT 1,'aUP TO 1M'
INSERT INTO #SIZE
SELECT 2,'b>1 TO 3M'
INSERT INTO #SIZE
SELECT 3,'c>3 TO 6M'
INSERT INTO #SIZE
SELECT 4,'d>6 TO 12M'
INSERT INTO #SIZE
SELECT 5,'e>1Y TO 2Y'
INSERT INTO #SIZE
SELECT 6,'f>2Y TO 3Y'
INSERT INTO #SIZE
SELECT 7,'g>3Y TO 4Y'
INSERT INTO #SIZE
SELECT 8,'h>4Y TO 5Y'
INSERT INTO #SIZE
SELECT 9,'i>5Y TO 10Y'
INSERT INTO #SIZE
SELECT 10,'j>10Y'
select AC_DESC FULL_NAME,CUST_AC_NO,CASE WHEN CUSTOMER_CATEGORY='IND' THEN 'INDIVIDUAL' ELSE 'CORPORATE' END CUSTOMER_CATEGORY,
CASE WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE)<=30 THEN 1
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) <=90 THEN 2
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) <=180 THEN 3
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) <=360 THEN 4
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) <=720 THEN 5
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) <=1080 THEN 6
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) <=1440 THEN 7
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) <=1800 THEN 8
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) <=3600 THEN 9
WHEN DATEDIFF(DAY,@BRANCH_DATE,LINE_EXPIRY_DATE) >3600 THEN 10 END SIZE,LCY_CUR_BAL*(-1) LCY_CUR_BAL,LINE_EXPIRY_DATE INTO #TMP from BBCDW..DIM_CUST_ACCOUNT AC 
INNER JOIN BBCDW..FACT_DAILY_AC_BAL BAL ON BAL.ACCOUNT_KEY=AC.ACCOUNT_KEY
INNER JOIN BBCDW..DIM_CUSTOMER CUS ON CUS.CUSTOMER_KEY=BAL.CUSTOMER_KEY 
INNER JOIN BBCDW..FACT_CUST_ACCOUNT_LINKAGES IM ON BAL.ACCOUNT_KEY=IM.ACCOUNT_KEY where IM.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
AND BAL.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
AND LCY_CUR_BAL<0

SELECT FULL_NAME,CUST_AC_NO,CUSTOMER_CATEGORY,LCY_CUR_BAL,S.SIZE,T.LINE_EXPIRY_DATE EXP_DATE FROM #SIZE S LEFT JOIN #TMP T ON S.ID=T.SIZE

END
