-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 20-SEP-2016
-- Description:	Trial Balance Consolidated Report
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_DD_TB_CONSOL_BY_CUR]
	@REPORT_DATE DATE,@CURRENCY varchar(50),@BRANCH VARCHAR(100)
AS
BEGIN
	
	SET NOCOUNT ON;
	declare	@BRANCH_DATE DATE=@REPORT_DATE
	SELECT 
			GM.GL_CODE,GM.GL_DESC,cu.CCY_CODE,
			SUM(B.OPN_DR_LCY) OPN_DR_BAL,SUM(B.OPN_CR_LCY) OPN_CR_BAL,
			SUM(B.DR_MOV_LCY) MOV_DR_BAL,SUM(B.CR_MOV_LCY) MOV_CR_BAL,
			SUM(B.CLO_DR_LCY) CLO_DR_BAL,SUM(B.CLO_CR_LCY) CLO_CR_BAL
	FROM FACT_DAILY_GL_BAL B
	INNER JOIN DIM_GLMASTER GM ON B.GL_KEY=GM.GL_KEY 
	INNER JOIN DIM_BBC_BRANCH BR ON BR.BRANCH_KEY=B.BRANCH_KEY
	INNER JOIN DIM_CURRENCY CU ON CU.CCY_KEY=B.CCY_KEY
	WHERE B.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) 
			AND B.LEAF='Y' AND CCY_CODE='USD'
			AND BR.BRANCH_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@BRANCH,','))
			AND CU.CCY_CODE collate database_default IN (SELECT Value FROM dbo.FnSplit(@CURRENCY,',')) 
			 and GL_CODE NOT IN ('57441000','66211000')
	GROUP BY GM.GL_CODE,GM.GL_DESC,cu.CCY_CODE
	UNION ALL
	SELECT 
			GM.GL_CODE,GM.GL_DESC,cu.CCY_CODE,
			SUM(B.OPN_DR_FCY) OPN_DR_BAL,SUM(B.OPN_CR_FCY) OPN_CR_BAL,
			SUM(B.DR_MOV_FCY) MOV_DR_BAL,SUM(B.CR_MOV_FCY) MOV_CR_BAL,
			SUM(B.CLO_DR_FCY) CLO_DR_BAL,SUM(B.CLO_CR_FCY) CLO_CR_BAL
	FROM FACT_DAILY_GL_BAL B
	INNER JOIN DIM_GLMASTER GM ON B.GL_KEY=GM.GL_KEY 
	INNER JOIN DIM_BBC_BRANCH BR ON BR.BRANCH_KEY=B.BRANCH_KEY
	INNER JOIN DIM_CURRENCY CU ON CU.CCY_KEY=B.CCY_KEY
	WHERE B.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) 
			AND B.LEAF='Y' AND CCY_CODE<>'USD'
			AND BR.BRANCH_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@BRANCH,','))
			AND CU.CCY_CODE collate database_default IN (SELECT Value FROM dbo.FnSplit(@CURRENCY,',')) 
			 and GL_CODE NOT IN ('57441000','66211000')
	GROUP BY GM.GL_CODE,GM.GL_DESC,cu.CCY_CODE
	UNION ALL
	SELECT 
			GM.GL_CODE,GM.GL_DESC,cu.CCY_CODE,
			SUM(B.OPN_DR_LCY) OPN_DR_BAL,SUM(B.OPN_CR_LCY) OPN_CR_BAL,
			SUM(B.DR_MOV_LCY) MOV_DR_BAL,SUM(B.CR_MOV_LCY) MOV_CR_BAL,
			SUM(B.CLO_DR_LCY) CLO_DR_BAL,SUM(B.CLO_CR_LCY) CLO_CR_BAL
	FROM FACT_DAILY_GL_BAL B
	INNER JOIN DIM_GLMASTER GM ON B.GL_KEY=GM.GL_KEY 
	INNER JOIN DIM_BBC_BRANCH BR ON BR.BRANCH_KEY=B.BRANCH_KEY
	INNER JOIN DIM_CURRENCY CU ON CU.CCY_KEY=B.CCY_KEY
	WHERE B.DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112) 
			AND B.LEAF='Y'
			AND BR.BRANCH_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@BRANCH,','))
			AND CU.CCY_CODE collate database_default IN (SELECT Value FROM dbo.FnSplit(@CURRENCY,',')) 
			 and GL_CODE IN ('57441000','66211000')
	GROUP BY GM.GL_CODE,GM.GL_DESC,cu.CCY_CODE 
	ORDER BY GM.GL_CODE

END
