-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_EOC_ERROR_ABORTED]
	@SERVER_NAME VARCHAR(15),@DB_NAME VARCHAR(15),@BRANCH_DATE AS DATE
AS
BEGIN
	DECLARE @SQL NVARCHAR(1000),@OPENQUERY nvarchar(4000)

	SET @SQL='
				SELECT 
				  BRANCH_CODE,
				  EOC_STAGE,
				  EOC_BATCH,
				  ERROR_CODE,
				  ERROR_PARAM,
				  ERROR
				FROM @DB_NAME.AETBS_EOC_PROGRAMS R WHERE R.EOC_BATCH_STATUS =''''A'''' AND R.BRANCH_DATE=''''@BRANCH_DATE''''
				UNION
				SELECT
						R.BRANCH_CODE,
						R.EOC_STAGE,
						Q.EOC_BATCH,
						R.ERROR_CODE,
						R.ERROR_PARAM,
						R.ERROR
				 from @DB_NAME.AETBS_EOC_RUNCHART_HISTORY R
				 LEFT JOIN @DB_NAME.AETB_EOC_PROGRAMS_history Q ON  Q.EOC_REF_NO=R.EOC_REF_NO AND Q.EOD_DATE=R.EOD_DATE AND  Q.EOC_BATCH_STATUS=''''A''''
				 WHERE R.EOC_STAGE_STATUS =''''A'''' AND R.BRANCH_DATE=''''@BRANCH_DATE''''
	'')';

	SET @OPENQUERY='SELECT * FROM OPENQUERY([@SERVER_NAME],''';
	SET @OPENQUERY=@OPENQUERY+@SQL;
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@SERVER_NAME',@SERVER_NAME);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@DB_NAME',@DB_NAME);
	SET @OPENQUERY=REPLACE(@OPENQUERY,'@BRANCH_DATE',@BRANCH_DATE);

	PRINT @OPENQUERY;
	EXEC sp_executesql @OPENQUERY;

END
