CREATE PROC [dbo].[SP_RPT_NBC_DEPO_AMOUNT] @BRANCH_DATE DATE
AS
BEGIN

  IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP

SELECT 'BDeposit Amount' Type,DEPO_TYPE_DESC,SIZE,BALANCE,DEPO_AMOUNT_TYPE INTO #TMP FROM BBCNBCMART..DIM_DEP_AMOUNT A LEFT JOIN BBCNBCMART..FACT_DEPO_AMOUNT M ON A.DEPO_TYPE=M.TYPE AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)
union all
SELECT 'ANumber of Deposit Accounts',DEPO_TYPE_DESC,SIZE,ACCOUNT,DEPO_AMOUNT_TYPE FROM BBCNBCMART..DIM_DEP_AMOUNT A LEFT JOIN BBCNBCMART..FACT_DEPO_AMOUNT M ON A.DEPO_TYPE=M.TYPE AND DATE_KEY=CONVERT(VARCHAR,@BRANCH_DATE,112)

SELECT Type,DEPO_TYPE_DESC,SIZE,BALANCE,DEPO_AMOUNT_TYPE_EN,DEPO_AMOUNT_TYPE_ID FROM #TMP T LEFT JOIN BBCNBCMART..DIM_DEPO_AMOUNT_TYPE P ON T.DEPO_AMOUNT_TYPE=P.DEPO_AMOUNT_TYPE_ID 

END
