-- =============================================
-- Author:		HENG SOPHAT
-- Create date: <Create Date,,>
-- Description:	DAILY CASH SETTLEMENT REPORT
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_DAILY_CASH_SETTLEMENT]
	@REPORT_DATE DATE,@RATE MONEY
AS
BEGIN
	
	SET NOCOUNT ON;

    SELECT 
		R.ITEM_LEVEL,
		(CASE WHEN R.ITEM_LEVEL=2 THEN '							'
						  WHEN R.ITEM_LEVEL=1 THEN '			'
						  ELSE '' END
	     )+R.ITEM_CODE AS ITEM_CODE,

		(CASE WHEN R.ITEM_LEVEL=2 THEN '							'
						  WHEN R.ITEM_LEVEL=1 THEN '			'
						  ELSE '' END
			)+R.ITEM_DESC AS REPORT_ITEM,
		F.AMT_IN_USD,
		F.EX_RATE,
		(F.AMT_IN_USD*@RATE)/1000000  AMT_IN_MILLION_RIEL
	FROM BBCNBCMART..FACT_DAILY_FX_CASH_SETTLEMENT F
	INNER JOIN BBCNBCMART..DIM_NBC_REPORT_ITEMS R ON F.ITEM_KEY=R.ITEM_KEY
	WHERE R.REPORT_ID=1 AND F.DATE_KEY=CONVERT(VARCHAR,@REPORT_DATE,112) 
	ORDER BY ORD_VAL

END
