 CREATE PROC [dbo].[SP_RPT_NBC_INTERNET_BANKING_LOCAL] @FROMDATE DATE, @TODATE DATE
 AS
 BEGIN
IF OBJECT_ID('tempdb..#SIZE_USD') IS NOT NULL
  DROP TABLE #SIZE_USD
 IF OBJECT_ID('tempdb..#SIZE_KHR') IS NOT NULL
  DROP TABLE #SIZE_KHR
 IF OBJECT_ID('tempdb..#INTER') IS NOT NULL
  DROP TABLE #INTER
 IF OBJECT_ID('tempdb..#INTER1') IS NOT NULL
  DROP TABLE #INTER1
 IF OBJECT_ID('tempdb..#CUST') IS NOT NULL
  DROP TABLE #CUST
   IF OBJECT_ID('tempdb..#CUST1') IS NOT NULL
  DROP TABLE #CUST1
create table #SIZE_USD (ID INT,SIZE VARCHAR(MAX),CCY VARCHAR(100))
INSERT INTO #SIZE_USD
SELECT 1,'0 TO $100','USD'
INSERT INTO #SIZE_USD
SELECT 2,'OVER $100 TO $500','USD'
INSERT INTO #SIZE_USD
SELECT 3,'OVER $500 TO $1000','USD'
INSERT INTO #SIZE_USD
SELECT 4,'OVER $1000 TO $2000','USD'
INSERT INTO #SIZE_USD
SELECT 5,'OVER $2000','USD'

create table #SIZE_KHR (ID INT,SIZE VARCHAR(MAX),CCY VARCHAR(100))
INSERT INTO #SIZE_KHR
SELECT 1,'0 TO KHR 400,000','KHR'
INSERT INTO #SIZE_KHR
SELECT 2,'OVER KHR 400,000 TO KHR 2,000,000','KHR'
INSERT INTO #SIZE_KHR
SELECT 3,'OVER 2,000,000 TO KHR 4,000,000','KHR'
INSERT INTO #SIZE_KHR
SELECT 4,'OVER KHR 4,000,000 TO KHR 8,000,000','KHR'
INSERT INTO #SIZE_KHR
SELECT 5,'OVER KHR 8,000,000','KHR'

-----INTER TRANSFER-------
select LCY_AMOUNT,CASE WHEN LCY_AMOUNT<=100 THEN 1
WHEN LCY_AMOUNT>100 AND LCY_AMOUNT<=500 THEN 2
WHEN LCY_AMOUNT>500 AND LCY_AMOUNT<=1000 THEN 3
WHEN LCY_AMOUNT>1000 AND LCY_AMOUNT<=2000 THEN 4
WHEN LCY_AMOUNT>2000 THEN 5 END SIZE,AC_CCY CCY,RELATED_CUSTOMER INTO #INTER from BBCSTAGE..SGTB_AC_ENTRIES where TRN_DT between @FROMDATE and  @TODATE
and  PRODUCT in ('EBSI','INFT','EBS2','LTSE') and DRCR_IND='C'
and AC_CCY in ('USD') and EVENT not in ('CYPO')
UNION ALL
select FCY_AMOUNT,CASE WHEN FCY_AMOUNT<=400000 THEN 1
WHEN FCY_AMOUNT>400000 AND FCY_AMOUNT<=2000000 THEN 2
WHEN FCY_AMOUNT>2000000 AND FCY_AMOUNT<=4000000 THEN 3
WHEN FCY_AMOUNT>4000000 AND FCY_AMOUNT<=8000000 THEN 4
WHEN FCY_AMOUNT>8000000 THEN 5 END SIZE,AC_CCY,RELATED_CUSTOMER from BBCSTAGE..SGTB_AC_ENTRIES where TRN_DT between @FROMDATE and  @TODATE
and  PRODUCT in ('EBSI','INFT','EBS2','LTSE') and DRCR_IND='C'
and AC_CCY in ('KHR') and EVENT not in ('CYPO')

SELECT SIZE,CCY,RELATED_CUSTOMER INTO #CUST FROM #INTER  GROUP BY SIZE,CCY,RELATED_CUSTOMER
SELECT SIZE,CCY,COUNT(RELATED_CUSTOMER) RELATED_CUSTOMER INTO #CUST1 FROM #CUST GROUP BY SIZE,CCY

SELECT SUM(LCY_AMOUNT) LCY_AMOUNT,COUNT(LCY_AMOUNT) NUM,SIZE,CCY INTO #INTER1 FROM #INTER GROUP BY SIZE,CCY

SELECT NUM,LCY_AMOUNT,RELATED_CUSTOMER NUMCUST,#SIZE_USD.CCY,#SIZE_USD.SIZE FROM #SIZE_USD LEFT JOIN 
#INTER1 ON #SIZE_USD.ID=#INTER1.SIZE AND #SIZE_USD.CCY=#INTER1.CCY LEFT JOIN #CUST1 ON ID=#CUST1.SIZE AND #SIZE_USD.CCY=#CUST1.CCY
UNION ALL
SELECT NUM,LCY_AMOUNT,RELATED_CUSTOMER NUMCUST,#SIZE_KHR.CCY,#SIZE_KHR.SIZE FROM #SIZE_KHR LEFT JOIN 
#INTER1 ON #SIZE_KHR.ID=#INTER1.SIZE AND #SIZE_KHR.CCY=#INTER1.CCY LEFT JOIN #CUST1 ON ID=#CUST1.SIZE AND #SIZE_KHR.CCY=#CUST1.CCY

END
