	CREATE PROCEDURE [dbo].[SP_RPT_BALANCE_SHEET_HO]
	@REPORT_DATE DATE,@BRANCH AS VARCHAR(100)
AS
BEGIN
	DECLARE @LAST_BAL_DT AS INT

	SELECT @LAST_BAL_DT=MAX(DATE_KEY) FROM FACT_DAILY_GL_BAL B WHERE B.DATE_KEY<=CONVERT(VARCHAR,@REPORT_DATE,112)

	SELECT 
			BR.BRANCH_CODE,
			CAST(GC.CATEGORY_KEY AS VARCHAR)+'-'+GC.DESCRIPTION AS CATEGORY,
			GM.GL_CODE,L.LINE_CODE,L.[LINE_DESC],GM.GL_DESC,CY.CCY_CODE AS CCY,
			CASE WHEN CY.CCY_CODE='USD' THEN B.CLO_LCY_BAL*VAL ELSE B.CLO_FCY_BAL*VAL END AS FCY_BAL,B.CLO_LCY_BAL*VAL AS LCY_BAL
	FROM FACT_DAILY_GL_BAL B
	INNER JOIN DIM_GLMASTER GM ON B.GL_KEY=GM.GL_KEY
	INNER JOIN DIM_GLCATEGORY GC ON B.CATEGORY_KEY=GC.CATEGORY_KEY
	INNER JOIN DIM_CURRENCY CY ON B.CCY_KEY=CY.CCY_KEY
	INNER JOIN DIM_BBC_BRANCH BR ON B.BRANCH_KEY=BR.BRANCH_KEY
	LEFT JOIN DIM_GLLINE L ON GM.HO_LINE_CR=L.LINE_CODE and L.IS_CURRENT=1
	WHERE B.LEAF='Y'
			AND B.DATE_KEY=@LAST_BAL_DT
			AND BR.BRANCH_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@BRANCH,',')) 
	ORDER BY 3,1,5;
END
