-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 22-09-2016
-- Description:	FA Registration Report
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_FA_REGISTERED]
	-- Add the parameters for the stored procedure here
	@BRANCH VARCHAR(100),@REPORT_DATE DATE, @CATEGORY AS VARCHAR(200),@LOCATION AS VARCHAR(100)
AS
BEGIN
	SELECT 
			BR.BRANCH_CODE BRANCH,
			FC.CATEGORY,
			FC.DESCRIPTION CATEGORY_DESC,
			FL.LOCATION,
			FL.DESCRIPTION LOCATION_DESC,
			PR.PRODUCT_CODE,
			PR.PRODUCT_DESCRIPTION PRODUCT_DESC,
			C.SERIAL_NO,
			C.ASSET_REF_NO,
			C.DESCRIPTION FA_NAME,
			C.CAPITALIZATION_DATE,
			C.USEFUL_LIFE_IN_YEAR,
			C.ASSET_CCY,
			F.ASSET_COST,
			C.CONTRACT_STATUS
			,F.PREV_YEAR_ACCM
			,F.PREV_MONTH_DEP
			,F.CURR_MONTH_DEP
			,F.CURR_YEAR_ACCM
			,F.TOTAL_ACCM
			,F.NBV
		FROM FACT_FA_DEPRECIATION F
		INNER JOIN DIM_BBC_BRANCH BR ON F.BRANCH_KEY=BR.BRANCH_KEY
		INNER JOIN DIM_FA_CATEGORY FC ON F.CATEGORY_KEY=FC.FA_CATEGORY_KEY
		INNER JOIN DIM_FA_LOCATION FL ON F.LOCATION_KEY=FL.LOCATION_KEY
		INNER JOIN DIM_FA_CONTRACT C ON F.CONTRACT_KEY=C.FA_CONTRACT_KEY
		INNER JOIN DIM_CS_PRODUCT PR ON F.PRODUCT_KEY=PR.PRODUCT_KEY 
		WHERE C.CAPITALIZATION_DATE<=@REPORT_DATE
			  AND F.DEP_YEAR=YEAR(@REPORT_DATE) AND F.DEP_MONTH=MONTH(@REPORT_DATE)
			  AND F.DATE_KEY=(SELECT MAX(DATE_KEY) FROM FACT_FA_DEPRECIATION F1 WHERE LEFT(F1.DATE_KEY,6)<=LEFT(CONVERT(VARCHAR,@REPORT_DATE,112),6) AND F1.CONTRACT_KEY=F.CONTRACT_KEY)
			  AND C.CATEGORY collate database_default IN(SELECT Value FROM dbo.FnSplit(@CATEGORY,',')) 
			  AND C.LOCATION collate database_default IN(SELECT Value FROM dbo.FnSplit(@LOCATION,','))
			  AND BR.BRANCH_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@BRANCH,','))
			  and CONTRACT_STATUS<>'S'
END
