-- =============================================
-- Author:		HENG SOPHAT
-- Create date: 28-SEP-2016
-- Description:	IACR LOAN REPORT
-- =============================================
CREATE PROCEDURE [dbo].[SP_RPT_CL_IACR_LOAN_]
	@FROM_DATE AS DATE, 
	@BRANCH_CODE AS VARCHAR(500),@PRODUCT_CODE AS VARCHAR(500),
	@PRODUCT_CAT AS VARCHAR(1000),@RM_ID AS VARCHAR(1000), 
	@CCY AS VARCHAR(100), @LOAN_AC_NO AS VARCHAR(35)
AS
BEGIN
	
	SET NOCOUNT ON;
	SELECT 
		F.DATE_KEY,
		CONVERT(DATE, CAST(F.DATE_KEY AS VARCHAR(8)), 112) BRANCH_DATE,
		BR.BRANCH_CODE,
		RM.RM_ID,AC.LOAN_AC_NO,C.CUSTOMER_NO,C.P_SEX GENDER,C.FULL_NAME,
		PR.PRODUCT_CODE,PR.PRODUCT_DESC,PC.PRODUCT_CATEGORY PRODUCT_CAT,
		AC.VALUE_DATE,AC.MATURITY_DATE,CY.CCY_CODE CURRENCY,F.FINANCED_AMT,F.DISBURSED_AMT,
		F.TOTAL_PRINCIPAL,F.TOTAL_INTEREST,F.INTEREST_RATE,F.PRINCIPAL_PAID,F.PRINCIPAL_OS,
		F.INTEREST_PAID,F.INTEREST_OS,F.INTEREST_ACCRUED,F.LAST_PRINCIPAL_BAL,F.LAST_INTEREST_BAL,
		F.INTEREST_ACCRUED_BAL,F.TOTAL_ACCRUED,F.START_UNPAID_DATE,F.OVERDUE_DAY,F.PRINCIPAL_OVERDUE,F.INTEREST_OVERDUE,ODIN,ODPR,
		USER_DEFINED_STATUS, CL.LINKED_AMOUNT, CL.LINKAGE_CURRENCY, CL.LINKED_REFERENCE_NO, CL.DESCRIPTION,PARENT_RM_ID

	FROM FACT_DAILY_IACR_LOAN F
	INNER JOIN DIM_BBC_BRANCH BR ON F.BRANCH_KEY=BR.BRANCH_KEY
	INNER JOIN DIM_LOAN_ACCOUNT AC ON F.LOAN_AC_KEY=AC.LOAN_AC_KEY
	INNER JOIN DIM_CUSTOMER C ON F.CUSTOMER_KEY=C.CUSTOMER_KEY
	INNER JOIN DIM_CL_PRODUCT PR ON F.PRODUCT_KEY=PR.PRODUCT_KEY
	INNER JOIN DIM_CL_PRODUCT_CATE PC ON F.PRODUCT_CATE_KEY=PC.PRODUCT_CATE_KEY
	INNER JOIN DIM_RELATION_MANAGER RM ON F.RM_KEY=RM.RM_KEY
	INNER JOIN DIM_CURRENCY CY ON F.CURRENCY_KEY=CY.CCY_KEY
	INNER JOIN BBCSTAGE..SGTB_CL_LINKAGE CL ON AC.LOAN_AC_NO = CL.ACCOUNT_NUMBER
	INNER JOIN BBCSTAGE..SGTM_STTMS_RM_HIERARCHY HI ON HI.RM_ID=RM.RM_ID
	WHERE F.DATE_KEY = CONVERT(VARCHAR,@FROM_DATE,112) 
			  AND AC.BRANCH_CODE collate database_default IN(SELECT Value FROM dbo.FnSplit(@BRANCH_CODE,',')) 
			  AND PC.PRODUCT_CATEGORY collate database_default IN(SELECT Value FROM dbo.FnSplit(@PRODUCT_CAT,',')) 
			  AND AC.CURRENCY collate database_default IN(SELECT Value FROM dbo.FnSplit(@CCY,',')) 
			  AND AC.LOAN_AC_NO LIKE '%'+ UPPER(@LOAN_AC_NO) + '%'
END
