CREATE proc [dbo].[SP_RPT_NBC_TWICE_WEEK_DEP_PERFORM_CAM] @DATE DATE,@TODATE date,@RATE money
AS
BEGIN

IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
  DROP TABLE #TMP
select DATE_KEY,DEPOSIT_TYPE_KEY,CUST_TYPE,sum(OPEN_BAL)OPEN_BAL,sum(DEPOSIT_BAL)DEPOSIT_BAL,sum(WITHDRAW_BAL)WITHDRAW_BAL INTO #TMP  from BBCNBCMART..FACT_TWICE_WEEK_DEP_PERFORM 
where DATE_KEY=CONVERT(VARCHAR,CAST(@DATE AS DATE),112) group by DATE_KEY,DEPOSIT_TYPE_KEY,CUST_TYPE
UNION ALL
select DATE_KEY,DEPOSIT_TYPE_KEY,CUST_TYPE,0,sum(DEPOSIT_BAL)DEPOSIT_BAL,sum(WITHDRAW_BAL)WITHDRAW_BAL  from BBCNBCMART..FACT_TWICE_WEEK_DEP_PERFORM 
where DATE_KEY> CONVERT(VARCHAR,CAST(@DATE AS DATE),112) AND DATE_KEY<=CONVERT(VARCHAR,CAST(@TODATE AS DATE),112)
group by DATE_KEY,DEPOSIT_TYPE_KEY,CUST_TYPE

SELECT ORDER_BY,DEPO_DES,ISNULL(TP.CUST_TYPE,'') CUST_TYPE,ISNULL(@RATE,0) EX_RATE,
(ISNULL(sum(OPEN_BAL),0)) OPEN_BAL,(ISNULL(sum(DEPOSIT_BAL),0)) DEPOSIT_BAL,(ISNULL(sum(WITHDRAW_BAL),0)) WITHDRAW_BAL
 FROM BBCNBCMART..DIM_DEPO_TYPE TP LEFT JOIN #TMP BAL ON TP.DEPO_KEY=BAL.DEPOSIT_TYPE_KEY
 group by ORDER_BY,DEPO_DES,TP.CUST_TYPE
END
