 
 

CREATE VIEW [dbo].[DMS_POLICY_MASTER_DATA] AS

SELECT DISTINCT  

P.POL_ID POLICY_NO

,P.POL_APP_FORM_ID APPLICATION_NO

,P.PLAN_ID

,RTRIM(PLN.ETBL_DESC_TXT) PLAN_NAME

,PC.CLI_ID

,CONCAT(RTRIM(PONM.ENTR_SUR_NM),' ', RTRIM(PONM.ENTR_GIV_NM)) PO_NAME

,PC.CLI_ID PO_ID

,RTRIM(POCN.CLI_CNTCT_ID_TXT) PO_PHONE_NO

,CONCAT(RTRIM(BLNM.ENTR_SUR_NM),' ', RTRIM(BLNM.ENTR_GIV_NM)) BLI_NAME

,BLI.INSRD_CLI_ID BLI_ID

,RTRIM(BLCN.CLI_CNTCT_ID_TXT) BLI_PHONE_NO

,RTRIM(POAD.CLI_ADDR_LN_1_TXT) PO_ADDR_1

,RTRIM(POAD.CLI_ADDR_LN_2_TXT) PO_ADDR_2

,RTRIM(POAD.CLI_ADDR_MUN_CD) PO_DISTRICT

,RTRIM(POAD.CLI_ADDR_CNTY_CD) PO_CITY

,P.POL_APP_SIGN_DT SUBMISSION_DATE

,LOADING_DATE = ''

,P.POL_INFC_DT ISSUED_DATE

,DBO.ConvertDate(P.POL_PD_TO_DT_NUM) PAID_TO_DATE

,P.POL_BILL_MODE_CD PREMIUM_MODE

,AFYP = IIF(P.POL_CSTAT_CD IN ('A','B','D','E','R','3'),

           (12 / IIF(CAST(P.POL_BILL_MODE_CD AS INT) = 0, 1, CAST(P.POL_BILL_MODE_CD AS INT))) * IIF(P.PLAN_ID = 'BES001',P0.POL_UNDSCNT_MPREM_AMT , P0.POL_MPREM_AMT),

           (12 / IIF(CAST(P.POL_BILL_MODE_CD AS INT) = 0, 1, CAST(P.POL_BILL_MODE_CD AS INT))) * IIF(P.PLAN_ID = 'BES001',CVG.CVG_UNDSCNT_PREM , P.POL_MPREM_AMT)

        )

,WFYP = IIF(CVG.CVG_MAT_XPRY_DUR = 6 OR CVG.CVG_MAT_XPRY_DUR = 9,

            (IIF(P.POL_CSTAT_CD IN ('A','B','D','E','R','3'), P0.POL_MPREM_AMT , P.POL_MPREM_AMT)) /2 ,

            IIF(P.POL_CSTAT_CD IN ('A','B','D','E','R','3'), P0.POL_MPREM_AMT , P.POL_MPREM_AMT)

        )

,P.POL_CSTAT_CD POL_STATUS

,RTRIM(STAT.DM_AV_DESC_TXT) POL_STATUS_DESC

,CASE WHEN P.POL_CSTAT_CD IN ('E','B','A') THEN P.POL_STAT_CHNG_DT END TERMINATION_DATE

,CASE WHEN P.POL_CSTAT_CD = '1' AND P.POL_PREV_CSTAT_CD = 'B' THEN P.POL_STAT_CHNG_DT END REINSTATE_DATE

,P0.POL_FACE_AMT SUM_INSURED

,CVG.CVG_MAT_XPRY_DUR POL_TERM

,CVG.PREM_PMT_DUR PREMIUM_TERM

,CVG.CVG_STBL_1_CD PREMIUM_TYPE

,P.PREV_SERV_AGT_ID ORIG_SERVING_AG_CODE

,PAG.Name ORIG_SERVING_AG_NAME

,AG.AgentId SERVICING_CODE

,AG.NAME SERVICING_NAME

,AG.Status SERVICING_STATUS

,AG.TitleRole SERVICING_POSITION

,AG.EffectiveDate JOINED_DATE

,AG.RefferedById RECRUITER_CODE

,AGR.Name RECRUITER_NAME

,COMMISSION_SPLIT = 100

,CASE WHEN AG.DistributionChannelCode = '1' THEN 'AG' WHEN AG.DistributionChannelCode = '2' THEN 'BA' ELSE AG.DistributionChannelCode END DISTRIBUTION_CAHHNEL

,PREMIUM_BEF_LOADING = IIF(P.POL_CSTAT_CD IN ('E', 'B','A'),

                          IIF(P.PLAN_ID = 'BES001',P0.POL_UNDSCNT_MPREM_AMT , P0.POL_MPREM_AMT),  

                          IIF(P.PLAN_ID = 'BES001',CVG.CVG_UNDSCNT_PREM , P.POL_MPREM_AMT)

                       ) - PCVG.CVG_ME_PREM_AMT

,MODAL_PREMIUM = IIF(P.POL_CSTAT_CD IN ('E', 'B','A'),

                    IIF(P.PLAN_ID = 'BES001',P0.POL_UNDSCNT_MPREM_AMT , P0.POL_MPREM_AMT),  

                    IIF(P.PLAN_ID = 'BES001',CVG.CVG_UNDSCNT_PREM , P.POL_MPREM_AMT)

                 )

-- BELOW CHANGE FOR MAPPING SOURCE 0F CUSTOMER FOR DL-881

,SOURCE_OF_CUSTOMER_CODE =
                    CASE WHEN P.POL_ISS_EFF_DT >= '2025-07-01' THEN
                        CASE P.CUST_SRC_CD
                            WHEN '01' THEN '1'
                            WHEN '02' THEN '3'
                            WHEN '03' THEN '3'
                            WHEN '04' THEN '1'
                            WHEN '05' THEN '3'
                            WHEN '06' THEN '3'
                            ELSE P.CUST_SRC_CD
                            END  
                    ELSE  
                            CASE P.CUST_SRC_CD
                            WHEN '01' THEN '1'
                            WHEN '02' THEN '4'
                            WHEN '03' THEN '3'
                            WHEN '04' THEN '1'
                            WHEN '05' THEN '4'
                            WHEN '06' THEN '3'
                            ELSE P.CUST_SRC_CD
                            END
                    END

,SOURCE_OF_CUSTOMER_DESC =  CASE WHEN P.POL_ISS_EFF_DT >= '2025-07-01' THEN
                        CASE P.CUST_SRC_CD
                        WHEN '01' THEN 'Bank Staff'
                        WHEN '02' THEN 'Refer Customer'
                        WHEN '03' THEN 'Refer Customer'
                        WHEN '04' THEN 'Bank Staff'
                        WHEN '05' THEN 'Refer Customer'
                        WHEN '06' THEN 'Refer Customer'
                        ELSE '' END
                    ELSE    
                        CASE P.CUST_SRC_CD
                            WHEN '01' THEN 'Bank Staff'
                            WHEN '02' THEN 'ISS`S own network'
                            WHEN '03' THEN 'Refer Customer'
                            WHEN '04' THEN 'Bank Staff'
                            WHEN '05' THEN 'ISS`S own network'
                            WHEN '06' THEN 'Other'
                        ELSE '' END
                    END

,BANK_NAME = ''

,LOCATION = ''

,ETL_DATE = GETDATE()

FROM SGTB_POLICY P

LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE P0 ON P0.POL_ID = P.POL_ID

LEFT JOIN SGTB_POLICY_CLIENT PC ON PC.POL_ID = P.POL_ID AND POL_CLI_REL_TYP_CD = 'O' --PO

LEFT JOIN SGTB_COVERAGE_CLI BLI ON BLI.POL_ID = P.POL_ID AND CVG_NUM = '01'

LEFT JOIN SGTM_COVERAGE CVG ON CVG.POL_ID = P.POL_ID AND CVG.CVG_NUM = '01'

LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_ADD WHERE LEN(CLI_ID) >= 10 AND CLI_ADDR_TYP_CD = 'PR') POAD ON PC.CLI_ID = POAD.CLI_ID AND POAD.#NO = 1

LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) PONM ON PC.CLI_ID= PONM.CLI_ID AND PONM.#NO = 1

LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) BLNM ON BLI.INSRD_CLI_ID= BLNM.CLI_ID AND BLNM.#NO = 1

LEFT JOIN SGTM_CLIENT_CONTACT POCN ON POCN.CLI_ID = PC.CLI_ID AND POCN.CLI_CNTCT_ID_CD = 'MO'

LEFT JOIN SGTM_CLIENT_CONTACT BLCN ON BLCN.CLI_ID = PC.CLI_ID AND BLCN.CLI_CNTCT_ID_CD = 'MO'

LEFT JOIN SGTM_PARA_1 STAT ON STAT.DM_AV_CD = P.POL_CSTAT_CD AND STAT.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND STAT.DM_AV_DESC_LANG_CD = 'E'

LEFT JOIN (

            SELECT SUM(CVG_FACE_AMT) POL_FACE_AMT, SUM(CVG_ME_PREM_AMT) CVG_ME_PREM_AMT, SUM(CVG_MPREM_AMT) CVG_MPREM_AMT,SUM(CVG_UNDSCNT_PREM) CVG_UNDSCNT_PREM, POL_ID, MAX(CVG_MAT_XPRY_DUR) POL_TERM

            FROM SGTM_COVERAGE WHERE CVG_CSTAT_CD NOT IN ('S') GROUP BY POL_ID

          ) PCVG ON PCVG.POL_ID = P.POL_ID

LEFT JOIN SGTB_POLICY_WRITING AGT ON AGT.POL_ID = P.POL_ID

LEFT JOIN SGTM_AGENT_DETAIL AG ON AG.AgentId = ISNULL(P.SERV_AGT_ID, AGT.AGT_ID)

LEFT JOIN SGTM_AGENT_DETAIL PAG ON PAG.AgentId = P.PREV_SERV_AGT_ID

--LEFT JOIN SGTM_AGENT_DETAIL AGI ON AGI.AgentId = AGT.AGT_ID

LEFT JOIN SGTM_AGENT_DETAIL AGR ON AGR.AgentId = AG.RefferedById -- AG RECUITER

LEFT JOIN SGTM_PARA SLDBR ON AGT.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_TYP_ID = 'SOLDBR'

LEFT JOIN SGTB_EDITTABLE PLN ON PLN.ETBL_VALU_ID = P.PLAN_ID AND PLN.ETBL_TYP_ID = 'PLAN'
