

CREATE VIEW [dbo].[DMS_POLICY_MASTER_DATA] AS
SELECT DISTINCT  P.POL_ID POLICY_NO
,P.POL_APP_FORM_ID APPLICATION_NO
,P.PLAN_ID
,RTRIM(PLN.ETBL_DESC_TXT) PLAN_NAME
,PC.CLI_ID
,CONCAT(RTRIM(PONM.ENTR_SUR_NM),' ', RTRIM(PONM.ENTR_GIV_NM)) PO_NAME
,PC.CLI_ID PO_ID
,RTRIM(POCN.CLI_CNTCT_ID_TXT) PO_PHONE_NO
,CONCAT(RTRIM(BLNM.ENTR_SUR_NM),' ', RTRIM(BLNM.ENTR_GIV_NM)) BLI_NAME
,BLI.INSRD_CLI_ID BLI_ID
,RTRIM(BLCN.CLI_CNTCT_ID_TXT) BLI_PHONE_NO
,RTRIM(POAD.CLI_ADDR_LN_1_TXT) PO_ADDR_1
,RTRIM(POAD.CLI_ADDR_LN_2_TXT) PO_ADDR_2
,RTRIM(POAD.CLI_ADDR_MUN_CD) PO_DISTRICT
,RTRIM(POAD.CLI_ADDR_CNTY_CD) PO_CITY
,P.POL_APP_SIGN_DT SUBMISSION_DATE
,LOADING_DATE = ''
,P.POL_ISS_EFF_DT ISSUED_DATE
,P.POL_PD_TO_DT_NUM PAID_TO_DATE
,P.POL_BILL_MODE_CD PREMIUM_MODE
--,AFYP = CASE WHEN P.POL_CSTAT_CD IN ('E', 'B') THEN (12 / CAST(P.POL_BILL_MODE_CD AS INT)) * P0.POL_MPREM_AMT ELSE (12 / CAST(P.POL_BILL_MODE_CD AS INT)) * P.POL_MPREM_AMT END
--,WFYP = CASE WHEN CVG.CVG_MAT_XPRY_DUR = 6 OR CVG.CVG_MAT_XPRY_DUR = 9 THEN (CASE WHEN P.POL_CSTAT_CD IN ('E', 'B') THEN P0.POL_MPREM_AMT ELSE P.POL_MPREM_AMT END )/2 ELSE (CASE WHEN P.POL_CSTAT_CD IN ('E', 'B') THEN P0.POL_MPREM_AMT ELSE P.POL_MPREM_AMT END ) END
,P.POL_CSTAT_CD POL_STATUS
,RTRIM(STAT.DM_AV_DESC_TXT) POL_STATUS_DESC
,CASE WHEN P.POL_CSTAT_CD IN ('E','B','A') THEN P.POL_STAT_CHNG_DT END TERMINATION_DATE
,CASE WHEN P.POL_CSTAT_CD = '1' AND P.POL_PREV_CSTAT_CD = 'B' THEN P.POL_STAT_CHNG_DT END REINSTATE_DATE
,PCVG.POL_FACE_AMT SUM_INSURED
,PCVG.POL_TERM 
,CVG.CVG_STBL_1_CD PREMIUM_TYPE
,P.PREV_SERV_AGT_ID ORIG_SERVING_AG_CODE
,AG.Name ORIG_SERVING_AG_NAME
,AGT.AGT_ID SERVICING_CODE
,AGI.NAME SERVICING_NAME
,AGI.Status SERVICING_STATUS
,AGI.TitleRole SERVICING_POSITION
,AGI.EffectiveDate JOINED_DATE
,AGI.RefferedById RECRUITER_CODE 
,AGR.Name RECRUITER_NAME
,COMMISSION_SPLIT = 100
,CASE WHEN AGI.DistributionChannelCode = '1' THEN 'AG' WHEN AGI.DistributionChannelCode = '2' THEN 'BA' ELSE AGI.DistributionChannelCode END DISTRIBUTION_CAHHNEL
,PCVG.CVG_MPREM_AMT - PCVG.CVG_ME_PREM_AMT PREMIUM_BEF_LOADING
,P.POL_MPREM_AMT MODAL_PREMIUM
,BANK_NAME = ''
,LOCATION = ''
,ETL_DATE = GETDATE()
FROM SGTB_POLICY P
LEFT JOIN V_GET_PREMIUM_AMT_POL_LAPSE P0 ON P0.POL_ID = P.POL_ID
LEFT JOIN SGTB_POLICY_CLIENT PC ON PC.POL_ID = P.POL_ID AND POL_CLI_REL_TYP_CD = 'O' --PO
LEFT JOIN SGTB_COVERAGE_CLI BLI ON BLI.POL_ID = P.POL_ID AND CVG_NUM = '01'
LEFT JOIN SGTM_COVERAGE CVG ON CVG.POL_ID = P.POL_ID AND CVG.CVG_NUM = '01'
LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_ADD WHERE LEN(CLI_ID) >= 10 AND CLI_ADDR_TYP_CD = 'PR') POAD ON PC.CLI_ID = POAD.CLI_ID AND POAD.#NO = 1

LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) PONM ON PC.CLI_ID= PONM.CLI_ID AND PONM.#NO = 1
LEFT JOIN (SELECT #NO = ROW_NUMBER() OVER(PARTITION BY CLI_ID ORDER BY PREV_UPDT_TS DESC), * FROM SGTM_CLIENT_IND WHERE LEN(CLI_ID) >= 10) BLNM ON BLI.INSRD_CLI_ID= BLNM.CLI_ID AND BLNM.#NO = 1

LEFT JOIN SGTM_CLIENT_CONTACT POCN ON POCN.CLI_ID = PC.CLI_ID AND POCN.CLI_CNTCT_ID_CD = 'MO'
LEFT JOIN SGTM_CLIENT_CONTACT BLCN ON BLCN.CLI_ID = PC.CLI_ID AND BLCN.CLI_CNTCT_ID_CD = 'MO'
LEFT JOIN SGTM_PARA_1 STAT ON STAT.DM_AV_CD = P.POL_CSTAT_CD AND STAT.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND STAT.DM_AV_DESC_LANG_CD = 'E'
LEFT JOIN (SELECT SUM(CVG_FACE_AMT) POL_FACE_AMT, SUM(CVG_ME_PREM_AMT) CVG_ME_PREM_AMT, SUM(CVG_MPREM_AMT) CVG_MPREM_AMT, POL_ID, MAX(CVG_MAT_XPRY_DUR) POL_TERM FROM SGTM_COVERAGE GROUP BY POL_ID) PCVG ON PCVG.POL_ID = P.POL_ID
LEFT JOIN SGTM_AGENT_DETAIL AG ON AG.AgentId = P.PREV_SERV_AGT_ID
LEFT JOIN SGTB_POLICY_WRITING AGT ON AGT.POL_ID = P.POL_ID
LEFT JOIN SGTM_AGENT_DETAIL AGI ON AGI.AgentId = AGT.AGT_ID
LEFT JOIN SGTM_AGENT_DETAIL AGR ON AGR.AgentId = AGI.RefferedById -- AG RECUITER
LEFT JOIN SGTM_PARA SLDBR ON AGT.POL_SOLD_BR_ID = SLDBR.ETBL_VALU_ID AND SLDBR.ETBL_TYP_ID = 'SOLDBR'

LEFT JOIN SGTB_EDITTABLE PLN ON PLN.ETBL_VALU_ID = P.PLAN_ID AND PLN.ETBL_TYP_ID = 'PLAN'
