

CREATE VIEW [dbo].[V_AGENT_INFO] AS
SELECT Agent_Key AGENT_KEY,T.PartyId PARTY_ID,T.PIN,NameFormat NAME_FORMAT,Title TITLE,Forename1 NAME1,Forename2 NAME2,Forename3 NAME3,Surname SURNAME,Sex SEX,DateOfBirth DOB,MartialType MT,MobileNumber MOBILE_NUM,BusinessPhone BIS_PHONE,EmailAddress EMAIL
,PaymentMethod PAYMENT_MODE,AgentType AGENT_TYPE,T.ReportsTo REPORT_TO,T.RecruitedBy RECRUIT_BY,DateOfHire CREAT_DT,LastMovement LAS_MOV,DateOfLastMovement LAS_MOV_DT,T.ModifiedDate,PayFlag PAY_FLAG,IDIssuedDate ID_ISS_DT,IDIssuedPlace ID_ISS_PLACE,
EducationID EDU_ID,CareerID CAREER_ID,OtherCareer OTHER_CAREER,AD.AddressLine1,AddressLine2,AddressLine3,AddressLine4,sZipCode,OfficeCode CSC_CODE,OName CSC_NAME,TEAM_TYPE, TEAM_CODE_1, TEAM_NAME_1,
 TEAM_CODE_2, TEAM_NAME_2, TEAM_CODE_3, TEAM_NAME_3
,TEAM_CODE_4, TEAM_NAME_4
,TEAM_CODE_5, TEAM_NAME_5
,TEAM_CODE_6, TEAM_NAME_6 FROM DLKHDIM..DIM_AGENT T
INNER JOIN DLKHSTAGE..SGTB_OFFICEMAP O ON O.PartyID=T.PartyId AND T.IS_CURRENT=1
INNER JOIN DLKHDIM..DIM_OFFICE F ON F.OCode=O.OfficeCode AND F.IS_CURRENT=1
LEFT JOIN V_TEAM T1 ON T.PartyId=T1.PARTY_ID
LEFT JOIN DLKHDIM..DIM_AGENT_ADD AD ON T.PartyId=AD.PartyId AND AD.IS_CURRENT=1
