

CREATE VIEW [dbo].[V_AGENT] AS
SELECT AG_KEY = AG.ID
	,AGTC_KEY = ''
	,CLI_KEY = C.ID
	,AGT_ID = CAST(AG.AGENT_CODE AS varchar(10))
	,BR_ID 
	,AGT_PHON_NUM = C.MOBILE_PHONE
	,AGT_STAT_CD = AG.AGENT_STATUS_CODE
	,AGT_CNTRCT_STRT_DT = AG.APPOINTED_DATE
	,AGT_CNTRCT_TRMN_DT = AG.TERMINATED_DATE
	,AGT_VEST_INT_AMT
	,AGT_TYP_CD
	,AGT_PMT_MTHD_CD = AG.PAYMENT_METHOD
	,AGT_CMPNST_SCHD_CD = T.CONTRACT_TYPE
	,QLTY_BON_PGM_IND
	,MKT_BON_PGM_IND
	,NHS_CMPNST_PGM_IND
	,AGT_OTHR_CMPNST_CD
	,AGT_FIN_ARANG_IND
	,AGT_BROK_OVRID_IND
	,AGT_SERV_FEE_IND
	,FYR_COMM_CALC_CD
	,RENW_COMM_CALC_CD
	,AUTO_COMM_PMT_CD
	,AGT_COMM_WTHLD_PCT
	,DEV_PGM_INCM_AMT
	,NMED_UWG_PRVLG_IND
	,AGT_FRNG_BNFT_IND
	,PARTL_ADV_COMM_CD
	,PARTL_ADV_COMM_AMT
	,AGT_CLAS_LIC_CD
	,AGT_SPNSR_LIC_IND
	,AGT_PRIM_LIC_ID
	,AGT_LOC_LIC_CD
	,PREV_AGT_ID
	,PREV_BR_ID
	,AGT_CMPNST_CRCY_CD
	,OVRID_BASE_AGT_ID = AGT.LeaderId
	,A.OVRID_ID 
	,AGT_CCAS_QUALF_IND
	,AGT_TRAIL_COMM_IND
	,AGT_TITL = AG.AGENT_TYPE
	,AGT_REF_ID = CAST(AG.REFER_AGENT_CODE AS varchar(10))
	,AGT_TITL_EFF_DT
	,AGT_DISB_CHNL = AG.CHANNEL
	,AGT_CLI_REL_TYP_CD = 'M'
	,CLI_ID = C.CLIENT_CODE
	,ADDR_TYP_CD = ad.ADDRESS_TYPE
	,BNK_ACCT_NUM = AG.BANK_CODE
	,RTRIM(LTRIM(C.FORENAME2)) ENTR_SUR_NM
	,RTRIM(LTRIM(C.SURNAME)) ENTR_GIV_NM
	,CLI_SEX_CD = C.GENDER
	,CLI_BTH_DT = C.DOB
	,CLI_CIN_NUM = ID_NUMBER
	,CLI_ADDR_LN_1_TXT = AD.FULL_ADDRESS
	,CLI_ADDR_LN_2_TXT = ''
	,CLI_ADDR_LN_3_TXT = ''
	,COMMUNE = AD.WARD_NAME
	,DISTRICT = AD.DISTRICT_NAME
	,CITY = AD.PROVINCE_NAME
	,AG.CHANNEL CHANNEL
FROM DMS_AGENT_DETAIL AG 
LEFT JOIN SGTM_AGENT_DETAIL AGT ON AGT.AgentId = CAST(AG.AGENT_CODE AS varchar)
LEFT JOIN DLKHDIM..DIM_AG A  ON CAST(AG.AGENT_CODE AS varchar) = A.AGT_ID AND A.IS_CURRENT = 1
LEFT JOIN DMS_CLIENT_DETAIL C ON C.CLIENT_CODE = AG.CLIENT_CODE AND C.CHANNEL = AG.CHANNEL
LEFT JOIN DMS_AGENT_TYPE T ON T.AGENT_TYPE = AG.AGENT_TYPE
LEFT JOIN DMS_CLIENT_ADDRESS AD ON AD.CLIENT_CODE = C.CLIENT_CODE AND AD.ADDRESS_TYPE = 'Res'
