CREATE VIEW dbo.V_BENE_PIVOT
AS
SELECT        BEN1.POL_ID, BEN1_PCT = BEN1.BENE1, BEN2_PCT = BEN1.BENE2, BEN3_PCT = BEN1.BENE3, BEN4_PCT = BEN1.BENE4, BEN1_CLI_ID = BEN2.BENE1, BEN2_CLI_ID = BEN2.BENE2, BEN3_CLI_ID = BEN2.BENE3, 
                         BEN4_CLI_ID = BEN2.BENE4, BEN1_CLI_NM = BEN3.BENE1, BEN2_CLI_NM = BEN3.BENE2, BEN3_CLI_NM = BEN3.BENE3, BEN4_CLI_NM = BEN3.BENE4
FROM            (SELECT        POL_ID, BNFY_SEQ_NUM = 'BENE' + CONVERT(VARCHAR(2), BNFY_SEQ_NUM), BNFY_PRCDS_PCT
                          FROM            SGTM_BENE) PV1 PIVOT (MIN(BNFY_PRCDS_PCT) FOR BNFY_SEQ_NUM IN ([BENE1], [BENE2], [BENE3], [BENE4])) BEN1 INNER JOIN
                             (SELECT        POL_ID, BNFY_SEQ_NUM = 'BENE' + CONVERT(VARCHAR(2), BNFY_SEQ_NUM), CLI_ID
                               FROM            SGTM_BENE) PV2 PIVOT (MIN(CLI_ID) FOR BNFY_SEQ_NUM IN ([BENE1], [BENE2], [BENE3], [BENE4])) BEN2 ON BEN1.POL_ID = BEN2.POL_ID INNER JOIN
                             (SELECT        POL_ID, BNFY_SEQ_NUM = 'BENE' + CONVERT(VARCHAR(2), BNFY_SEQ_NUM), BNFY_NM = RTRIM(CLIN.ENTR_SUR_NM) + ' ' + RTRIM(CLIN.ENTR_GIV_NM)
                               FROM            SGTM_BENE BENE LEFT JOIN
                                                         SGTM_CLIENT_IND CLIN ON BENE.CLI_ID = CLIN.CLI_ID) PV3 PIVOT (MIN(BNFY_NM) FOR BNFY_SEQ_NUM IN ([BENE1], [BENE2], [BENE3], [BENE4])) BEN3 ON BEN1.POL_ID = BEN3.POL_ID
