

CREATE VIEW [dbo].[V_CLI_POL_INFC]
AS 
	SELECT DISTINCT  CLI.CLI_ID
		,CNM.CLI_INDV_SUR_NM AS FAMILY_NAME
		,CNM.CLI_INDV_GIV_NM AS GIVEN_NAME
		,CLI.CLI_SEX_CD
		,CLI.CLI_BTH_DT
		,OCCU.ETBL_DESC_TXT AS OCCUPATION
		,CASE WHEN ISNULL(CLI.CLI_SUPPRT_DOC_ID,'') = '' THEN 'NR' ELSE CLI.CLI_SUPPRT_DOC_ID END AS CLI_SUPPRT_DOC_ID
		,ISNULL(CINSD.ETBL_DESC_TXT,'ID Card') AS CLI_SUPPORT_DOC_TYPE
		,'Resident' AS RESIDENT
		,CLI.CLI_CIN_NUM
		,ISNULL(CAD.CLI_PSTL_CD,'') AS CLI_PSTL_CD
		,CTRS.ETBL_DESC_TXT AS COUNTRY
		,CAD.CLI_CRNT_LOC_CD AS PROVINCE_CODE_ING
		,PROVINCE_CODE =  CLOC.ETBL_VALU_ID
		,PROVINCE =  CLOC.ETBL_DESC_TXT  
		,CAD.CLI_ADDR_MUN_CD AS DISTRICT_CODE_ING
		,DISTRICT_CODE = (SELECT TOP 1 DISTRICT_CODE FROM DLKHSTAGE..LOC_KH WHERE DISTRICT_CODE_ING = CAD.CLI_ADDR_MUN_CD)
		,DIST.ETBL_DESC_TXT AS DISTRICT
		,CAD.CLI_ADDR_CNTY_CD AS WARD_CODE_ING
		,WARD_CODE = (SELECT TOP 1 WARD_CODE FROM DLKHSTAGE..LOC_KH WHERE WARD_CODE_ING = CAD.CLI_ADDR_CNTY_CD)
		,WARD.ETBL_DESC_TXT AS WARD
		,CAD.CLI_ADDR_LN_1_TXT
		,POL.POL_ID
		,CVG.PLAN_ID
		,PLN.ETBL_DESC_TXT AS PLAN_TYPE
		,POL_INFC_DT
		,ISNULL(POL.POL_INFC_DT,'01-01-1990') AS POLICY_INFORCE_DATE
		,ISNULL(POL.POL_ISS_EFF_DT,'01-01-1990') AS POLICY_ISSUED_DATE
		,IS_LIFE_INS_RIEL = '0'
		,IS_LIFE_INS_US = '1'
		,CVG.CVG_FACE_AMT
		--,IS_HEALTH_INS_RIEL = '0'
		--,IS_HEALTH_INS_US = '0'
		--,IS_LOAN_INS_RIEL = '0'	
		--,IS_LOAN_INS_US = '0'
		--,IS_EDU_SAVING_INS_RIEL = '0'
		--,IS_EDU_SAVING_INS_US = '0'
		,AG.AGT_DISB_CHNL
		,AG.AGT_DISB_CHNL_DESC
		,POLW.AGT_ID
		,AGT_ENTR_SUR_NM = AG.ENTR_SUR_NM
		,AGT_ENTR_GIV_NM = AG.ENTR_GIV_NM
		,AGT_PHON_NUM = RTRIM(AG.AGT_PHON_NUM)
		,AG.AGT_ADDR_LN_1_TXT
		,AGT_LDR_ID = AGL.AGT_ID
		,AGT_LDR_SUR_NM = AGL.ENTR_SUR_NM
		,AGT_LDR_GIV_NM = AGL.ENTR_GIV_NM
		,AGT_MGR_ID = AGM.AGT_ID
		,AGT_MGR_SUR_NM = AGM.ENTR_SUR_NM
		,AGT_MGR_GIV_NM = AGM.ENTR_GIV_NM
		,ORG.PARTNER_NAME BANK_NAME
	FROM DLKHSTAGE..SGTM_CLIENT CLI
	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_IND CNM ON CLI.CLI_ID = CNM.CLI_ID
	LEFT JOIN DLKHSTAGE..SGTM_CLIENT_ADD CAD ON CLI.CLI_ID = CAD.CLI_ID
	LEFT JOIN DLKHSTAGE..SGTM_PARA CTRS ON CAD.CLI_CTRY_CD=CTRS.ETBL_VALU_ID AND CTRS.ETBL_TYP_ID='CNTRY'
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE DIST ON CAD.CLI_ADDR_MUN_CD=DIST.ETBL_VALU_ID AND DIST.ETBL_TYP_ID='MCPCD'
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE WARD ON CAD.CLI_ADDR_CNTY_CD=WARD.ETBL_VALU_ID AND WARD.ETBL_TYP_ID='CTYPC'
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE OCCU ON CLI.OCCP_ID=OCCU.ETBL_VALU_ID AND OCCU.ETBL_TYP_ID='OCCCD'
	LEFT JOIN DLKHSTAGE..SGTB_POLICY_CLIENT PLC ON CLI.CLI_ID = PLC.CLI_ID
	RIGHT JOIN DLKHSTAGE..SGTB_POLICY POL ON PLC.POL_ID = POL.POL_ID
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE CINSD ON CLI.CLI_SUPPRT_DOC_ID = CINSD.ETBL_VALU_ID AND CINSD.ETBL_TYP_ID = 'CINSD'
	LEFT JOIN DLKHSTAGE..SGTM_COVERAGE CVG ON POL.POL_ID = CVG.POL_ID AND CVG.CVG_NUM IN ('01')--('01','02','03')
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE PLN ON CVG.PLAN_ID = PLN.ETBL_VALU_ID AND PLN.ETBL_TYP_ID = 'PLAN'
	LEFT JOIN DLKHSTAGE..SGTB_POLICY_WRITING POLW ON POL.POL_ID = POLW.POL_ID
	LEFT JOIN DLKHSTAGE..DMS_ORGANIZATION ORG ON ORG.SALE_SUPPORT LIKE CONCAT('%',POLW.AGT_ID,'%')
	LEFT JOIN V_GET_AGENT_BASIC AG ON POLW.AGT_ID = AG.AGT_ID --AND AG.AGT_CLI_REL_TYP_CD = 'R' 
	LEFT JOIN V_GET_AGENT_BASIC AGL ON AG.OVRID_BASE_AGT_ID = AGL.AGT_ID --AND AGL.AGT_CLI_REL_TYP_CD = 'M' 
	LEFT JOIN V_GET_AGENT_BASIC AGM ON AGL.OVRID_BASE_AGT_ID = AGM.AGT_ID --AND AGM.AGT_CLI_REL_TYP_CD = 'M'
	LEFT JOIN DLKHSTAGE..SGTB_EDITTABLE CLOC ON CAD.CLI_CRNT_LOC_CD = CLOC.ETBL_VALU_ID AND CLOC.ETBL_TYP_ID= 'CLOC' AND CLOC.ETBL_LANG_CD = 'E' AND CLOC.PREV_UPDT_USER_ID = 'AMS104'
	WHERE 1 = 1
	AND POL.POL_INFC_DT IS NOT NULL
	--AND ISNULL(POL.POL_INFC_DT,'1990-01-01') BETWEEN '2020-04-01' AND '2020-06-30'
	--AND CLI.CLI_ID = '0000000333'
	--AND WARD.WARD_NAME_EN IS NULL
	--AND AGT.AGT_DISB_CHNL = 2
	--ORDER BY CNM.CLI_ID --,POL.POL_INFC_DT
