

CREATE VIEW [dbo].[V_CLI_INFO]
AS

SELECT C.CLI_KEY,I.CLIIND_KEY,C.CLI_ID,CLI_AGE_PROOF_IND,CLI_BTH_DT,CLI_SEX_CD,CLI_SMKR_CD,CLI_LANG_CD,CLI_TAX_ID,CLI_TXEMP_CD,CLI_MARIT_STAT_CD,CLI_HT,CLI_WGT,CLI_BTH_LOC_CD,OCCP_ID,
CLI_INCM_EARN_CD,CLI_UWGDECN_CD,CLI_UWGDECN_DT,UW_USER_1_ID,UW_USER_2_ID,CLI_CMPLT_CCAS_IND,PREV_UWG_ACTV_DT,CLI_CIN_NUM CLI_ID_NUM,CLI_INDV_GR_CD,
GIV_NM_PHNT_TXT,SUR_NM_PHNT_TXT,ENTR_GIV_NM,ENTR_SUR_NM,CLI_INDV_GIV_NM,CLI_INDV_SUR_NM,CLI_ADDR_LN_1_TXT,CLI_ADDR_LN_2_TXT,CLI_ADDR_LN_3_TXT,CA.CLI_CITY_NM_TXT,CLI_ADDR_CNTCT_TXT,CLI_PSTL_CD,
CT.CLI_CNTCT_ID_TXT FROM DLKHDIM..DIM_CLIENT C INNER JOIN DLKHDIM..DIM_CLIENT_IND I ON C.CLI_ID=I.CLI_ID AND C.IS_CURRENT=1 AND I.IS_CURRENT=1
left JOIN DLKHDIM..DIM_CLIENT_ADD CA ON CA.CLI_ID=C.CLI_ID AND CA.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_CLIENT_CONTACT CT ON CT.CLI_ID=C.CLI_ID AND CT.IS_CURRENT=1 AND CT.CLI_CNTCT_ID_CD='MO'
where c.CO_ID='CP'
