

CREATE VIEW V_CS_SURVEY
AS
	SELECT CSV.CS_NAME
		, CSV.CS_COMMENTS
		, CSV.CS_RATING
		, RATING_DETAIL = CASE CSV.CS_RATING 
			WHEN '1' THEN 'Very Dissatisfied' 
			WHEN '2' THEN 'Dissatisfied' 
			WHEN '3' THEN 'Satisfied'
			WHEN '4' THEN 'Very Satisfied'
			WHEN '5' THEN 'Excellent'
			ELSE ''
			END
		, CSV.CS_USER_NAME
		, CSV.POL_ID
		, POL.POL_INFC_DT
		, POL.POL_CSTAT_CD
		, STS.DM_AV_DESC_TXT
	FROM DLKHSTAGE..CS_SURVEY CSV
	LEFT JOIN DLKHSTAGE..SGTB_POLICY POL ON CSV.POL_ID = POL.POL_ID
	LEFT JOIN DLKHSTAGE..SGTM_PARA_1 STS ON STS.DM_AV_CD = POL.POL_CSTAT_CD AND (STS.DM_AV_TBL_CD = 'POL-CSTAT-CD' AND STS.CO_ID = 'CP' AND STS.DM_AV_DESC_LANG_CD = 'E')
;
