
-- Save to temp table due to future use of Hierachy Tier[1-7]
CREATE VIEW [dbo].[V_DMS_AGENT_HIERARCHY] AS 

SELECT CAST(A.AGENT_CODE AS VARCHAR) AgentId, A.CLIENT_CODE ClientId, A.AGENT_NAME Name, C.GENDER Gender, C.DOB BirthDate, C.PRIVATE_PHONE CellPhone, C.BUSINESS_PHONE OfficePhone
, C.MOBILE_PHONE PhoneNumber, C.EMAIL_ADDRESS1 Email, A.APPOINTED_DATE EffectiveDate, A.TERMINATED_DATE TerminationDate, A.AGENT_STATUS Status, '' ContractTypeCode, '' ContractType
, A.RECRUIT_AGENT_CODE RefferedById, AT.GROUP_TYPE AgentType
, CASE WHEN A.CHANNEL = 'BA' THEN ORG.NAME ELSE A.SALES_OFFICE_NAME END Branch 
, A.CHANNEL DistributionChannelCode
, CASE WHEN A.CHANNEL = 'BA' THEN 'BANCA' ELSE 'AGENCY' END DistributionChannel
, A.AGENT_TYPE TitleRole

, CASE WHEN A.CHANNEL = 'BA' THEN AL.AGENT_CODE ELSE A.REPORTING_TO_CODE END LeaderId
, CASE WHEN A.CHANNEL = 'BA' THEN AL.AGENT_NAME ELSE A.REPORTING_TO_NAME END LeaderName
, CASE WHEN A.CHANNEL = 'BA' THEN AL.AGENT_TYPE ELSE A.REPORTING_TO_NAME END LeaderTitleRole

, CASE WHEN A.CHANNEL = 'BA' THEN CAST(AM.AGENT_CODE AS varchar) ELSE
		CASE WHEN T1.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN CAST(T1.AGENT_CODE AS varchar)
		WHEN T2.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN CAST(T2.AGENT_CODE AS varchar)
		WHEN T3.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN CAST(T3.AGENT_CODE AS varchar)
		WHEN T4.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN CAST(T4.AGENT_CODE AS varchar)
		ELSE NULL
		END
	END ManagerId
, CASE WHEN A.CHANNEL = 'BA' THEN CAST(AM.AGENT_NAME AS varchar) ELSE
		CASE WHEN T1.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4  ) THEN T1.AGENT_NAME 
		WHEN T2.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4  ) THEN T2.AGENT_NAME 
		WHEN T3.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4  ) THEN T3.AGENT_NAME 
		WHEN T4.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4  ) THEN T4.AGENT_NAME 
		ELSE NULL
		END
	END ManagerName
, CASE WHEN A.CHANNEL = 'BA' THEN CAST(AM.AGENT_TYPE AS varchar) ELSE
		CASE WHEN T1.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4  ) THEN T1.AGENT_TYPE 
		WHEN T2.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4  ) THEN T2.AGENT_TYPE 
		WHEN T3.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4  ) THEN T3.AGENT_TYPE 
		WHEN T4.AGENT_TYPE IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4  ) THEN T4.AGENT_TYPE 
		ELSE NULL
		END
	END ManagerTitleRole

, CASE WHEN A.CHANNEL = 'BA' THEN AL.AGENT_CODE ELSE T1.AGENT_CODE END Tier1Id
, CASE WHEN A.CHANNEL = 'BA' THEN AL.AGENT_NAME ELSE T1.AGENT_NAME END Tier1Name 
, CASE WHEN A.CHANNEL = 'BA' THEN AL.AGENT_TYPE ELSE R1.AGENT_TYPE END Tier1TitleRole

,T2.AGENT_CODE Tier2Id, T2.AGENT_NAME Tier2Name , R2.AGENT_TYPE Tier2TitleRole
,T3.AGENT_CODE Tier3Id, T3.AGENT_NAME Tier3Name , R3.AGENT_TYPE Tier3TitleRole
,T4.AGENT_CODE Tier4Id, T4.AGENT_NAME Tier4Name , R4.AGENT_TYPE Tier4TitleRole
,T5.AGENT_CODE Tier5Id, T5.AGENT_NAME Tier5Name , R5.AGENT_TYPE Tier5TitleRole
,T6.AGENT_CODE Tier6Id, T6.AGENT_NAME Tier6Name , R6.AGENT_TYPE Tier6TitleRole
,T7.AGENT_CODE Tier7Id, T7.AGENT_NAME Tier7Name , R7.AGENT_TYPE Tier7TitleRole

FROM DMS_AGENT_DETAIL A
LEFT JOIN DMS_AGENT_TYPE AT ON AT.AGENT_TYPE = A.AGENT_TYPE 
LEFT JOIN DMS_ORGANIZATION ORG ON ORG.SALE_SUPPORT LIKE CONCAT('%',A.AGENT_CODE,'%')
LEFT JOIN DMS_AGENT_DETAIL AL ON AL.AGENT_CODE = ORG.BD_MANAGER_CODE
LEFT JOIn DMS_AGENT_DETAIL AM ON AM.AGENT_CODE = AL.REPORTING_TO_CODE

LEFT JOIN DMS_CLIENT_DETAIL C  ON C.CLIENT_CODE = A.CLIENT_CODE AND A.CHANNEL = C.CHANNEL

LEFT JOIN DMS_AGENT_DETAIL T1 ON T1.AGENT_CODE = A.REPORTING_TO_CODE 
LEFT JOIN DMS_AGENT_TYPE R1 ON R1.AGENT_TYPE = T1.AGENT_TYPE

LEFT JOIN DMS_AGENT_DETAIL T2 ON T2.AGENT_CODE = T1.REPORTING_TO_CODE
LEFT JOIN DMS_AGENT_TYPE R2 ON R2.AGENT_TYPE = T2.AGENT_TYPE

LEFT JOIN DMS_AGENT_DETAIL T3 ON T3.AGENT_CODE = T2.REPORTING_TO_CODE
LEFT JOIN DMS_AGENT_TYPE R3 ON R3.AGENT_TYPE = T3.AGENT_TYPE

LEFT JOIN DMS_AGENT_DETAIL T4 ON T4.AGENT_CODE = T3.REPORTING_TO_CODE
LEFT JOIN DMS_AGENT_TYPE R4 ON R4.AGENT_TYPE = T4.AGENT_TYPE

LEFT JOIN DMS_AGENT_DETAIL T5 ON T5.AGENT_CODE = T4.REPORTING_TO_CODE
LEFT JOIN DMS_AGENT_TYPE R5 ON R5.AGENT_TYPE = T5.AGENT_TYPE

LEFT JOIN DMS_AGENT_DETAIL T6 ON T6.AGENT_CODE = T5.REPORTING_TO_CODE
LEFT JOIN DMS_AGENT_TYPE R6 ON R6.AGENT_TYPE = T6.AGENT_TYPE

LEFT JOIN DMS_AGENT_DETAIL T7 ON T6.AGENT_CODE = T6.REPORTING_TO_CODE
LEFT JOIN DMS_AGENT_TYPE R7 ON R7.AGENT_TYPE = T7.AGENT_TYPE
