

CREATE VIEW [dbo].[V_DMS_AGENT_REPORTING_LINE_LIVE] AS
SELECT AGENT_CODE,CLIENT_CODE, AGENT_NAME, AGENT_TYPE,AGENT_STATUS,APPOINTED_DATE
,CHANNEL, CASE WHEN CHANNEL = 'BA' THEN 'BANCA' WHEN CHANNEL = 'AG' THEN 'AGENCY' ELSE '' END CHANNEL_DESC
,MOBILE_PHONE
,SMALL_OFFICE
,BRANCH_CODE = CASE WHEN CHANNEL = 'BA' THEN ORG_CODE ELSE SALES_OFFICE_CODE END
,BRANCH_NAME = CASE WHEN CHANNEL = 'BA' THEN ORG_NAME ELSE SALES_OFFICE_NAME END
,BD_MANAGER_CODE,BD_MANAGER_NAME,ORG_PARENT_CODE, ORG_PARENT_NAME

, CASE WHEN CHANNEL = 'BA' THEN BD_MANAGER_CODE ELSE Tier1Id END LeaderId
, CASE WHEN CHANNEL = 'BA' THEN BD_MANAGER_NAME ELSE Tier1Name END LeaderName
, CASE WHEN CHANNEL = 'BA' THEN AGENT_TYPE ELSE Tier1TitleRole END LeaderRole

, CASE WHEN CHANNEL = 'BA' THEN MANAGER_CODE ELSE
		CASE 
		WHEN Tier1TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier1Id
		WHEN Tier2TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier2Id
		WHEN Tier3TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier3Id
		WHEN Tier4TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier4Id
		ELSE NULL
		END
	END ManagerId
, CASE WHEN CHANNEL = 'BA' THEN MANAGER_NAME ELSE
		CASE 
		WHEN Tier1TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier1Name
		WHEN Tier2TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier2Name
		WHEN Tier3TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier3Name
		WHEN Tier4TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier4Name
		ELSE NULL
		END
	END ManagerName
, CASE WHEN CHANNEL = 'BA' THEN MANAGER_TYPE  ELSE
		CASE 
		WHEN Tier1TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier1TitleRole
		WHEN Tier2TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier2TitleRole
		WHEN Tier3TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier3TitleRole
		WHEN Tier4TitleRole IN (SELECT AGENT_TYPE FROM DMS_AGENT_TYPE WHERE TYPE_LEVEL = 4 ) THEN Tier4TitleRole
		ELSE NULL
		END
	END ManagerRole
, PARTNER_CODE, PARTNER_NAME

FROM OPENQUERY([10.116.17.220], ' SELECT A.AGENT_CODE,A.CLIENT_CODE
, CONCAT(C.FORENAME2, '' '', C.SURNAME) AGENT_NAME
, A.AGENT_TYPE,A.AGENT_STATUS,A.APPOINTED_DATE
,A.SALES_OFFICE_CODE,A.SALES_OFFICE_NAME, A.CHANNEL, A.SMALL_OFFICE
,O.BD_MANAGER_CODE,O.BD_MANAGER_NAME
,AL.AGENT_TYPE BD_MANAGER_TYPE
,AM.AGENT_CODE MANAGER_CODE
,CONCAT(AMC.FORENAME2, '' '', AMC.SURNAME) MANAGER_NAME
,AM.AGENT_TYPE MANAGER_TYPE
,O.ORG_PARENT_CODE, O.ORG_PARENT_NAME, C.PRIVATE_PHONE MOBILE_PHONE,O.ORG_CODE, O.NAME ORG_NAME
,PN.CODE PARTNER_CODE, PN.NAME PARTNER_NAME

, CASE WHEN A.CHANNEL = ''BA'' THEN O.BD_MANAGER_CODE ELSE T1.AGENT_CODE END Tier1Id
, CASE WHEN A.CHANNEL = ''BA'' THEN CONCAT(ALC.FORENAME2, '' '', ALC.SURNAME) ELSE T1.AGENT_NAME END Tier1Name 
, CASE WHEN A.CHANNEL = ''BA'' THEN OM.AGENT_TYPE ELSE R1.AGENT_TYPE END Tier1TitleRole

,T2.AGENT_CODE Tier2Id, CONCAT(C2.FORENAME2, '' '', C2.SURNAME) Tier2Name , R2.AGENT_TYPE Tier2TitleRole
,T3.AGENT_CODE Tier3Id, CONCAT(C3.FORENAME2, '' '', C3.SURNAME) Tier3Name , R3.AGENT_TYPE Tier3TitleRole
,T4.AGENT_CODE Tier4Id, CONCAT(C4.FORENAME2, '' '', C4.SURNAME) Tier4Name , R4.AGENT_TYPE Tier4TitleRole
FROM DMS_UAT..DMS_AGENT_DETAIL A
LEFT JOIN DMS_UAT..DMS_AGENT_TYPE AT ON AT.AGENT_TYPE = A.AGENT_TYPE 
LEFT JOIN DMS_UAT..DMS_ORGANIZATION O ON O.SALE_SUPPORT LIKE CONCAT(''%'',A.AGENT_CODE,''%'')
LEFT JOIN DMS_UAT..DMS_AGENT_DETAIL AL ON AL.AGENT_CODE = O.BD_MANAGER_CODE
LEFT JOIN DMS_UAT..DMS_CLIENT_DETAIL ALC ON ALC.CLIENT_CODE = AL.CLIENT_CODE
LEFT JOIN DMS_UAT..DMS_AGENT_DETAIL AM ON AM.AGENT_CODE = AL.REPORTING_TO_CODE
LEFT JOIN DMS_UAT..DMS_CLIENT_DETAIL AMC ON AMC.CLIENT_CODE = AM.CLIENT_CODE
LEFT JOIN DMS_UAT..DMS_PARTNER PN ON PN.CODE = O.PARTNER_CODE AND PN.CHANNEL = O.CHANNEL AND PN.HIERARCHICAL_MODEL = 3
LEFT JOIN DMS_UAT..DMS_AGENT_TYPE OM ON OM.AGENT_TYPE = AM.AGENT_TYPE
LEFT JOIN DMS_UAT..DMS_CLIENT_DETAIL C  ON C.CLIENT_CODE = A.CLIENT_CODE 

LEFT JOIN DMS_UAT..DMS_AGENT_DETAIL T1 ON T1.AGENT_CODE = A.REPORTING_TO_CODE 
LEFT JOIN DMS_UAT..DMS_AGENT_TYPE R1 ON R1.AGENT_TYPE = T1.AGENT_TYPE
LEFT JOIN DMS_UAT..DMS_CLIENT_DETAIL C1 ON C1.CLIENT_CODE = T1.CLIENT_CODE

LEFT JOIN DMS_UAT..DMS_AGENT_DETAIL T2 ON T2.AGENT_CODE = T1.REPORTING_TO_CODE
LEFT JOIN DMS_UAT..DMS_AGENT_TYPE R2 ON R2.AGENT_TYPE = T2.AGENT_TYPE
LEFT JOIN DMS_UAT..DMS_CLIENT_DETAIL C2 ON C2.CLIENT_CODE = T2.CLIENT_CODE

LEFT JOIN DMS_UAT..DMS_AGENT_DETAIL T3 ON T3.AGENT_CODE = T2.REPORTING_TO_CODE
LEFT JOIN DMS_UAT..DMS_AGENT_TYPE R3 ON R3.AGENT_TYPE = T3.AGENT_TYPE
LEFT JOIN DMS_UAT..DMS_CLIENT_DETAIL C3 ON C3.CLIENT_CODE = T3.CLIENT_CODE

LEFT JOIN DMS_UAT..DMS_AGENT_DETAIL T4 ON T4.AGENT_CODE = T3.REPORTING_TO_CODE
LEFT JOIN DMS_UAT..DMS_AGENT_TYPE R4 ON R4.AGENT_TYPE = T4.AGENT_TYPE
LEFT JOIN DMS_UAT..DMS_CLIENT_DETAIL C4 ON C4.CLIENT_CODE = T4.CLIENT_CODE
')
