

CREATE VIEW [dbo].[V_DMS_PREMIUM_COLLECTION_POLICY] AS

WITH CDSA (POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD,PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM, CDA_TOT_MPREM_AMT) AS (

	SELECT POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD,PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM, CDA_TOT_MPREM_AMT
	FROM OPENQUERY(UAT7, 'SELECT POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD, PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM, CDA_TOT_MPREM_AMT FROM KCAPXUAT.TCDSA WHERE  CDA_TYP_CD = ''PP'' AND CDA_STAT_CD IN (''A'',''R'') ')
	WHERE CAST(PREV_UPDT_TS AS DATE) != GETDATE()
)
,CDSA_A (POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD,PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM, CDA_TOT_MPREM_AMT ) AS 
(
	SELECT POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD,PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM , CDA_TOT_MPREM_AMT 
	--FROM OPENQUERY(UAT7, 'SELECT POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD, PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT FROM KCAPXPR1.TCDSA') 
	FROM CDSA
	WHERE  CDA_STAT_CD = 'A' 
), 
CDSA_R (POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD,PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM, CDA_TOT_MPREM_AMT ) AS 
(
	SELECT * 
	FROM (
	SELECT POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD,PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM , CDA_TOT_MPREM_AMT   
	--FROM OPENQUERY(UAT7, 'SELECT POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD, PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT FROM KCAPXPR1.TCDSA') 
	FROM CDSA
	WHERE  CDA_STAT_CD = 'R' 
	UNION ALL
	SELECT POL_ID, CDA_EFF_DT,CDA_STAT_CD = 'A',CDA_TOT_TRXN_AMT*-1,CDA_TYP_CD,PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM , CDA_TOT_MPREM_AMT  
	--FROM OPENQUERY(UAT7, 'SELECT POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD, PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT FROM KCAPXPR1.TCDSA') 
	FROM CDSA
	WHERE  CDA_STAT_CD = 'R' ) AS CDSA_R
),
CDSA_F (POL_ID, CDA_EFF_DT,CDA_STAT_CD,CDA_TOT_TRXN_AMT,CDA_TYP_CD,PREV_UPDT_TS,CDA_FWD_PRCES_DT,CDA_REVRS_PRCES_DT,CDA_SEQ_NUM, CDA_TOT_MPREM_AMT ) AS 
(
	SELECT * 
	FROM (
	SELECT * FROM CDSA_A
	UNION ALL
	SELECT * FROM CDSA_R ) AS FINAL
)

SELECT DISTINCT  PC.POL_ID POLICY_ID
		,PC.CDA_SEQ_NUM IDENTIFY_NUM
		,P1.PLAN_ID
		,PLN.ETBL_DESC_TXT PLAN_NAME
		,PC.CDA_EFF_DT COLLECTION_EFFECTIVE_DATE
		,CASE WHEN PC.CDA_TOT_TRXN_AMT < 0 THEN PC.CDA_REVRS_PRCES_DT ELSE PC.CDA_FWD_PRCES_DT END COLLECTION_DATE
		,PC.CDA_TOT_TRXN_AMT POLICY_COLLECTION_AMOUNT
		, CONCAT(
			CASE WHEN DATEDIFF(MONTH, P1.POL_ISS_EFF_DT,PC.CDA_EFF_DT) = 0 THEN 'IF' 
			WHEN DATEDIFF(MONTH, P1.POL_ISS_EFF_DT,PC.CDA_EFF_DT) < 12 THEN 'RF' 
			ELSE CAST((DATEDIFF(MONTH, P1.POL_ISS_EFF_DT,PC.CDA_EFF_DT)/12) + 1 AS varchar) END
			, ''
			, 'YC' ) COMMISION_TYPE
		, CONCAT(
			CASE WHEN DATEDIFF(MONTH, P1.POL_ISS_EFF_DT,PC.CDA_EFF_DT) = 0 THEN 'IF' 
			WHEN DATEDIFF(MONTH, P1.POL_ISS_EFF_DT,PC.CDA_EFF_DT) < 12 THEN 'RF' 
			ELSE CAST((DATEDIFF(MONTH, P1.POL_ISS_EFF_DT,PC.CDA_EFF_DT)/12) + 1 AS varchar) END
			, ''
			, 'YP' ) RENEWAL_YEAR
		,ISNULL(P.SERV_AGT_ID, P1.SERV_AGT_ID) AGT_ID
		,CDA_TOT_MPREM_AMT
		,ETL_DATE = GETDATE()
	FROM CDSA_F PC
	LEFT JOIN DLKHDIM..DIM_POLICY P ON P.POL_ID = PC.POL_ID AND  P.START_DT <= (CASE WHEN PC.CDA_TOT_TRXN_AMT < 0 THEN PC.CDA_REVRS_PRCES_DT ELSE PC.CDA_FWD_PRCES_DT END) AND  ISNULL(P.END_DT,GETDATE()) > (CASE WHEN PC.CDA_TOT_TRXN_AMT < 0 THEN PC.CDA_REVRS_PRCES_DT ELSE PC.CDA_FWD_PRCES_DT END)
	LEFT JOIN SGTB_POLICY P1 ON P1.POL_ID = PC.POL_ID 
	LEFT JOIN SGTB_EDITTABLE PLN ON PLN.ETBL_VALU_ID = P1.PLAN_ID AND PLN.ETBL_TYP_ID = 'PLAN'
	WHERE 1 = 1
	AND YEAR(PC.CDA_EFF_DT) >= 2022
	--AND PC.POL_ID = '700020726'
