CREATE VIEW V_FA_DEP_MONTHLY
AS
SELECT 
		V.ASSET_REF_NO,YEAR(V.DEPRECIATION_DATE) DEP_YEAR,
		MONTH(V.DEPRECIATION_DATE) DEP_MONTH,
		SUM(CURRENT_DEPRECIATION) DEP_AMOUNT
FROM BBCDW..FACT_FA_DEP_DETAIL V
GROUP BY  V.ASSET_REF_NO,YEAR(V.DEPRECIATION_DATE),MONTH(V.DEPRECIATION_DATE)
