

CREATE VIEW [dbo].[V_GET_PREMIUM_AMT_POL_LAPSE] 
AS
	SELECT POL.POL_ID
	, POL.POL_BILL_MODE_CD
	, POL_FACE_AMT = SUM(CVG.CVG_FACE_AMT)
	, POL_MPREM_AMT = SUM(CVG.CVG_MPREM_AMT)
	, POL_UNDSCNT_MPREM_AMT = SUM(CVG.CVG_UNDSCNT_PREM)
	, TOTAL_CVG_NUM = COUNT(CVG.CVG_NUM)
	, POL_TERM = MAX(CVG.CVG_MAT_XPRY_DUR)
	, POL_ME_PREM_AMT = SUM(CVG_ME_PREM_AMT) 
	FROM SGTM_COVERAGE CVG
	LEFT JOIN SGTB_POLICY POL ON CVG.POL_ID = POL.POL_ID
	WHERE 1 = 1
		AND POL.POL_CSTAT_CD IN ('A','B','D','E','R','3')
		AND POL.POL_STAT_CHNG_DT = CVG.CVG_STAT_PRCES_DT	-- IF BOTH VALUES ARE SAME => COVERAGE WAS LAPSED, ELSE COVERAGE WAS DROPPED
	GROUP BY POL.POL_ID, POL.POL_BILL_MODE_CD
	--ORDER BY POL.POL_ID DESC
