

CREATE VIEW [dbo].[V_GET_AGENT_BASIC] AS
	SELECT 
		CO_ID = 'CP'
		,CAST(AG.AGENT_CODE AS varchar) AGT_ID
		,A.PREV_AGT_ID
		,AG.AGENT_STATUS AGT_STAT_CD
		,AGT_PHON_NUM = RTRIM(C.MOBILE_PHONE)
		,AGT_EMAIL = RTRIM(C.EMAIL_ADDRESS1)
		,AGT_PHON_NUM_BUS = RTRIM(C.BUSINESS_PHONE)
		,AGT_PHON_NUM_HOME = RTRIM(C.BEEPER_PHONE)
		,AG.AGENT_TYPE AGT_TITL
		,AG.REFER_AGENT_CODE AGT_REF_ID
		,A.AGT_TYP_CD
		,A.BR_ID
		,AGT_BR_DESC = RTRIM(AKEY.ETBL_DESC_TXT)
		,A.PREV_BR_ID
		,AGT.LeaderId OVRID_BASE_AGT_ID
		,A.OVRID_ID
		,RTRIM(LTRIM(C.SURNAME)) ENTR_SUR_NM
		,RTRIM(LTRIM(C.FORENAME2)) ENTR_GIV_NM
		,AGT_SEX_CODE = C.GENDER
		,AGT_BTH_DT = C.DOB
		,AGT_CIN_NUM = C.ID_NUMBER
		,AGT_ADDR_LN_1_TXT = RTRIM(AD.FULL_ADDRESS)
		,AGT_ADDR_LN_2_TXT = ''
		,AGT_ADDR_LN_3_TXT = ''
		,COMMUNE = RTRIM(AD.WARD_NAME)
		,DISTRICT = RTRIM(AD.DISTRICT_NAME)
		,CITY = RTRIM(AD.PROVINCE_NAME)
		,AG.CHANNEL AGT_DISB_CHNL
		,AGT_DISB_CHNL_DESC = CASE WHEN AG.CHANNEL = 'BA' THEN 'BANCA' ELSE 'AGENCY' END
		,AGT_CLI_REL_TYP_CD = 'M'
		,AG.APPOINTED_DATE AGT_CNTRCT_STRT_DT
	FROM DMS_AGENT_DETAIL AG
	LEFT JOIN SGTM_AGENT_DETAIL AGT ON AGT.AgentId = AG.AGENT_CODE
	LEFT JOIN SGTM_AG A ON A.AGT_ID = CAST(AG.AGENT_CODE AS varchar)
	LEFT JOIN DMS_CLIENT_DETAIL C ON C.CLIENT_CODE = AG.CLIENT_CODE AND C.CHANNEL = AG.CHANNEL
	LEFT JOIN DMS_CLIENT_ADDRESS AD ON AD.CLIENT_CODE = C.CLIENT_CODE AND AD.ADDRESS_TYPE = 'Res'
	LEFT JOIN SGTB_EDITTABLE AKEY ON A.BR_ID = AKEY.ETBL_VALU_ID AND AKEY.ETBL_TYP_ID = 'AKEY' AND AKEY.ETBL_LANG_CD = 'E' AND AKEY.CO_ID = 'CP'
