

CREATE VIEW [dbo].[V_GET_POL_CLI_ROLE_LIVE]
AS
	SELECT 
	DISTINCT
		INSRD.POL_ID
		,INSRD.INSRD_CLI_ID
		,INSRD.INSRD_ROLE
	FROM
	(
		SELECT DISTINCT CLI.POL_ID,  CLI.INSRD_CLI_ID
			, INSRD_ROLE =  CASE WHEN CLI.INSRD_CLI_ID = PO.CLI_ID THEN PO.INSRD_ROLE
								 WHEN BLI.BLI_ID = CLI.INSRD_CLI_ID THEN BLI.INSRD_ROLE
								 ELSE 'ALI' END
		FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TCVGC') CLI 

		LEFT JOIN 
		(
		SELECT POL_ID,CLI_ID, INSRD_ROLE = 'PO'
		FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TPOLC') WHERE POL_CLI_REL_TYP_CD = 'O' 
		) PO ON PO.CLI_ID = CLI.INSRD_CLI_ID AND PO.POL_ID = CLI.POL_ID

		LEFT JOIN 
		(
			SELECT POL_ID,BLI_ID = INSRD_CLI_ID, INSRD_ROLE = 'BLI'
			FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TCVGC') WHERE CVG_NUM = '01'
		)AS BLI ON CLI.INSRD_CLI_ID = BLI.BLI_ID AND CLI.POL_ID = BLI.POL_ID

		UNION ALL
		
		SELECT POL_ID,BLI_ID = INSRD_CLI_ID, INSRD_ROLE = 'BLI'
		FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TCVGC') WHERE CVG_NUM = '01'
		
		UNION ALL
	
		SELECT POL_ID,CLI_ID, INSRD_ROLE = 'PO'
		FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TPOLC') POLC WHERE POLC.POL_CLI_REL_TYP_CD = 'O'

	)INSRD
