CREATE VIEW dbo.V_GET_CVG_INSRD_ROLE
AS
SELECT        CLI.POL_ID, CLI.INSRD_CLI_ID, CLI.CVG_NUM, CASE WHEN CLI.INSRD_CLI_ID = BLI.BLI_ID THEN 'BLI' ELSE 'ALI' END AS INSRD_ROLE
FROM            dbo.SGTB_COVERAGE_CLI AS CLI LEFT OUTER JOIN
                             (SELECT        POL_ID, INSRD_CLI_ID AS BLI_ID, 'BLI' AS INSRD_ROLE
                               FROM            dbo.SGTB_COVERAGE_CLI
                               WHERE        (CVG_NUM = '01')) AS BLI ON CLI.INSRD_CLI_ID = BLI.BLI_ID AND CLI.POL_ID = BLI.POL_ID
