

CREATE VIEW [dbo].[V_GET_NON_JET_AND_INCOMPLETE_CODE]
AS
	SELECT GRP_CD = 'COL', NON_JET_STAT_CD = 'COL',REQIR_ID = '0027'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0028'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0029'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0030'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0031'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0032'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0033'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0034'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0035'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0036'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0037'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0038'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0039'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0040'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = '0042'		UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0193'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0194'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0195'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0196'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0197'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0198'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0199'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0200'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0201'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0202'	UNION
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0207'	UNION	
	SELECT GRP_CD = 'ME', NON_JET_STAT_CD = 'ME', REQIR_ID = 'U0208'	UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0001'		UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0002'		UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0003'		UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0004'		UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0005'		UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0006'		UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0021'		UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0022'		UNION
	SELECT GRP_CD = 'IA', NON_JET_STAT_CD = 'IA', REQIR_ID = '0041'		UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0101'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0008'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0009'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0010'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0011'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0012'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0013'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0014'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0015'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0016'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0017'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0018'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0019'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0020'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0023'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0024'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0025'	UNION
	SELECT GRP_CD = 'OTR', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0026'	
	--SELECT GRP_CD = '', NON_JET_STAT_CD = 'OTR', REQIR_ID = '0042'
