

CREATE VIEW [dbo].[V_GET_AGENT_BASIC_LIVE]
AS
	SELECT 
		AG.CO_ID
		,AG.AGT_ID
		,AG.PREV_AGT_ID
		,AG.AGT_STAT_CD
		,AGT_PHON_NUM = RTRIM(AG.AGT_PHON_NUM)
		,AG.AGT_TITL
		,AG.AGT_REF_ID
		,AG.AGT_TYP_CD
		,AG.BR_ID
		,AGT_BR_DESC = RTRIM(AKEY.ETBL_DESC_TXT)
		,AG.PREV_BR_ID
		,AG.OVRID_BASE_AGT_ID
		,AG.OVRID_ID
		,RTRIM(LTRIM(CIND.ENTR_SUR_NM)) ENTR_SUR_NM
		,RTRIM(LTRIM(CIND.ENTR_GIV_NM)) ENTR_GIV_NM
		,AGT_SEX_CODE = CLI.CLI_SEX_CD
		,AGT_BTH_DT = CLI.CLI_BTH_DT
		,AGT_CIN_NUM = CLI.CLI_CIN_NUM
		,AGT_ADDR_LN_1_TXT = RTRIM(CLIA.CLI_ADDR_LN_1_TXT)
		,AGT_ADDR_LN_2_TXT = RTRIM(CLIA.CLI_ADDR_LN_2_TXT)
		,AGT_ADDR_LN_3_TXT = RTRIM(CLIA.CLI_ADDR_LN_3_TXT)
		,COMMUNE = RTRIM(CMU.ETBL_DESC_TXT)
		,DISTRICT = RTRIM(DIS.ETBL_DESC_TXT)
		,CITY = RTRIM(CIT.ETBL_DESC_TXT)
		,AG.AGT_DISB_CHNL
		,AGT_DISB_CHNL_DESC = RTRIM(CH.ETBL_DESC_TXT)
		,AGC.AGT_CLI_REL_TYP_CD
	FROM OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TAG') AG
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TAGTC') AGC ON AG.AGT_ID = AGC.AGT_ID
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TCLI') CLI ON CLI.CLI_ID = AGC.CLI_ID
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TCLNM') CIND ON AGC.CLI_ID = CIND.CLI_ID AND CIND.PREV_UPDT_TS = (SELECT MAX(PREV_UPDT_TS) FROM SGTM_CLIENT_IND WHERE CLI_ID = AGC.CLI_ID GROUP BY CLI_ID)
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TCLIA') CLIA ON AGC.CLI_ID = CLIA.CLI_ID AND CLIA.PREV_UPDT_TS = (SELECT MAX(PREV_UPDT_TS) FROM SGTM_CLIENT_ADD WHERE CLI_ID = AGC.CLI_ID GROUP BY CLI_ID)
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TEDIT') CMU ON CMU.ETBL_LANG_CD='E' AND CMU.ETBL_TYP_ID='CTYPC' AND  CLIA.CLI_ADDR_CNTY_CD=CMU.ETBL_VALU_ID AND CMU.CO_ID='CP'
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TEDIT') DIS ON DIS.ETBL_LANG_CD='E' AND DIS.ETBL_TYP_ID='MCPCD' AND  CLIA.CLI_ADDR_MUN_CD=DIS.ETBL_VALU_ID AND DIS.CO_ID='CP'
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TEDIT') CIT ON CIT.ETBL_LANG_CD='E' AND CIT.ETBL_TYP_ID='CLOC' AND  CLIA.CLI_CRNT_LOC_CD=CIT.ETBL_VALU_ID AND CIT.CO_ID='CP'
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TEDIT') CH ON AG.AGT_DISB_CHNL = CH.ETBL_VALU_ID AND CH.ETBL_TYP_ID='DCHNL' AND CH.ETBL_LANG_CD = 'E' AND CH.CO_ID = 'CP'
	LEFT JOIN OPENQUERY(UAT7,'SELECT * FROM KCAPXUAT.TEDIT') AKEY ON AG.BR_ID = AKEY.ETBL_VALU_ID AND AKEY.ETBL_TYP_ID = 'AKEY' AND AKEY.ETBL_LANG_CD = 'E' AND AKEY.CO_ID = 'CP'
	WHERE AGC.AGT_CLI_REL_TYP_CD = 'M'
