

CREATE VIEW [dbo].[V_KIZUNA_INTRODUCER_REWARD] AS
SELECT  
P.POL_ID POLICY_ID
,C.CVG_NUM COVERAGE_NUM
,C.PLAN_ID
,PA.ETBL_DESC_TXT PLAN_DESC
,POL_CSTAT_CD POLICY_STATUS
,PARA.DM_AV_DESC_TXT POLICY_STATUS_DESC
,COMM_DUR_CALC_DT COMMISSION_EFFECTIVE_DATE
,COM.COMM_PRCES_DT COMMISSION_DATE
,C.CVG_MPREM_AMT PREMIUM_AMOUNT
,COM.COMM_AMT COMMISSION_AMOUNT
,CASE WHEN  INTRO_ID != '' THEN CAST( COM.COMM_AMT / 2 AS float) ELSE 0 END REWARD_AMOUNT
,C.INTRO_ID INTRODUCER_CODE
,C.MIT_PHEAK_ID MITPHEARK_CODE
,COM.AGT_ID AGENT_CODE
,ETL_DT = GETDATE()
	FROM (
	SELECT POL_ID,CVG_NUM, COMM_TRXN_AMT COMM_AMT,COMM_DUR_CALC_DT, BUS_FCN_ID, COMM_TRXN_REASN_CD COMM_REASN_CD, COMM_TRXN_PRCES_DT COMM_PRCES_DT,AGT_ID FROM SGTB_COMMISSION
	UNION ALL 
	SELECT POL_ID,CVG_NUM, COMM_HIST_AMT COMM_AMT, COMM_DUR_CALC_DT,BUS_FCN_ID, COMM_HIST_REASN_CD COMM_REASN_CD, COMM_HIST_PRCES_DT COMM_PRCES_DT,AGT_ID FROM SGTB_COMMISSION_HIS) COM
	LEFT JOIN SGTB_POLICY P ON COM.POL_ID = P.POL_ID 
	LEFT JOIN SGTM_COVERAGE C ON C.POL_ID = COM.POL_ID AND C.CVG_NUM = COM.CVG_NUM 
	LEFT JOIN 
		(
			SELECT POL_ID,MIN(PCHST_EFF_DT) PCHST_EFF_DT 
			FROM SGTB_POLICY_CHANGE PPC 
			WHERE PPC.PCHST_STAT_CD='A' AND PPC.POL_ACTV_TYP_ID='1082' GROUP BY POL_ID
		) PPC ON COM.POL_ID = PPC.POL_ID
	LEFT JOIN SGTB_POLICY_CHANGE PC ON COM.POL_ID  =PC.POL_ID AND COM.COMM_DUR_CALC_DT=PC.PCHST_EFF_DT 
		AND PCHST_STAT_CD='A' AND POL_ACTV_TYP_ID IN ('1082','1084')
	LEFT JOIN SGTM_PARA_1 PARA ON P.POL_CSTAT_CD=PARA.DM_AV_CD AND DM_AV_TBL_CD='POL-CSTAT-CD' AND PARA.DM_AV_DESC_LANG_CD='E' AND PARA.CO_ID='CP'
	LEFT JOIN SGTB_EDITTABLE PA ON C.PLAN_ID=PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID='PLAN' AND PA.ETBL_LANG_CD='E' AND PA.CO_ID='CP'
	WHERE P.POL_ID NOT IN ('001000744') 
		AND BUS_FCN_ID NOT IN ('M297','1453')
		AND COMM_REASN_CD NOT IN ('K')
		--OR COMM_DUR_CALC_DT IS NOT NULL	)
		AND C.INTRO_ID != ''
		AND (LEFT(P.POL_CSTAT_CD,1) = 'P' OR P.POL_CSTAT_CD IN ('1', 'R','A'))
