CREATE VIEW dbo.V_PIVOT_CLIENT_CONTACT
AS
SELECT        T .*
FROM            (SELECT        CLI_ID, CLI_CNTCT_ID_CD, CLI_CNTCT_ID_TXT = RTRIM(CLI_CNTCT_ID_TXT)
                          FROM            SGTM_CLIENT_CONTACT) CLI PIVOT (MIN(CLI_CNTCT_ID_TXT) FOR CLI_CNTCT_ID_CD IN ([EM], [HO], [BU], [MO])) T
