

CREATE VIEW [dbo].[V_PIVOT_POL_CLI_ROLE_LIVE]
AS
	SELECT PIV.*
	FROM
	(
		SELECT CLIR.POL_ID
			,CLIR.INSRD_CLI_ID
			,INSRD_ROLE = CLIR.INSRD_ROLE +  CASE WHEN CLIR.INSRD_ROLE = 'ALI' THEN  CONVERT(VARCHAR(1),ROW_NUMBER() OVER (PARTITION BY CLIR.POL_ID, CLIR.INSRD_ROLE ORDER BY CLIR.INSRD_CLI_ID)) ELSE '' END
		FROM V_GET_POL_CLI_ROLE_LIVE CLIR
		WHERE 1 = 1
	) CLI
	PIVOT(MIN(INSRD_CLI_ID) FOR INSRD_ROLE IN ([PO],[BLI],[ALI1],[ALI2])) PIV
