

CREATE VIEW [dbo].[V_PNS_INFO_DETAILS]
AS
SELECT        

RTRIM(C.CLI_ID) AS CLI_ID, 
RTRIM(P.POL_ID) AS POL_ID, 
RTRIM(P.POL_APP_FORM_ID) AS POL_APP_FORM_ID, 
RTRIM(I.ENTR_SUR_NM) AS LAST_NAME, 
RTRIM(I.ENTR_GIV_NM) AS FIRST_NAME, 
CONCAT(RTRIM(I.ENTR_SUR_NM),' ',RTRIM(I.ENTR_GIV_NM)) AS PO_NAME, 
RTRIM(C.CLI_BTH_DT) AS CLI_BTH_DT,
RTRIM(C.CLI_SEX_CD) AS CLI_SEX_CD,
'855' + RIGHT(RTRIM(CT.CLI_CNTCT_ID_TXT), LEN(RTRIM(CT.CLI_CNTCT_ID_TXT)) - 1) AS PHONE_NUM, 
RTRIM(EM.CLI_CNTCT_ID_TXT) AS EMAIL, 
RTRIM(PA.ETBL_DESC_TXT) AS PLAN_NAME, 
RTRIM(PARA.DM_AV_DESC_TXT) AS POL_STATUS, 
RTRIM(P.POL_APP_CMPLT_DT) AS ISSUE_DATE, 
RTRIM(P.POL_BILL_MODE_CD) AS FREQ, 
RTRIM(P.POL_APP_RECV_DT) AS POL_COMM_DATE, 
RTRIM(P.POL_PD_TO_DT_NUM) AS PRE_DUE_DATE, 
RTRIM(P.POL_STAT_CHNG_DT) AS POL_STAT_CHNG_DT, 
RTRIM(P.POL_MPREM_AMT) AS POL_MPREM_AMT
FROM            DLKHDIM.dbo.DIM_CLIENT AS C INNER JOIN
                         DLKHDIM.dbo.DIM_CLIENT_IND AS I ON C.CLI_ID = I.CLI_ID AND C.IS_CURRENT = 1 AND I.IS_CURRENT = 1 INNER JOIN
                         DLKHDIM.dbo.DIM_POLICY_CLIENT AS PC ON PC.CLI_ID = C.CLI_ID AND PC.IS_CURRENT = 1 AND PC.POL_CLI_REL_SUB_CD = 'P' INNER JOIN
                         DLKHDIM.dbo.DIM_POLICY AS P ON P.POL_ID = PC.POL_ID AND P.IS_CURRENT = 1 LEFT OUTER JOIN
                         dbo.SGTB_EDITTABLE AS PA ON P.PLAN_ID = PA.ETBL_VALU_ID AND PA.ETBL_TYP_ID = 'PLAN' LEFT OUTER JOIN
                         dbo.SGTM_PARA_1 AS PARA ON P.POL_CSTAT_CD = PARA.DM_AV_CD AND PARA.DM_AV_TBL_CD = 'POL-CSTAT-CD' LEFT OUTER JOIN
                         (select CLI_CNTCT_ID_CD,CLI_ID,CLI_CNTCT_ID_TXT,IS_CURRENT,MAX(PREV_UPDT_TS) PREV_UPDT_TS from DLKHDIM.dbo.DIM_CLIENT_CONTACT group by CLI_CNTCT_ID_CD,CLI_ID,CLI_CNTCT_ID_TXT,IS_CURRENT) 
						 AS EM ON C.CLI_ID = EM.CLI_ID AND EM.IS_CURRENT = 1 AND EM.CLI_CNTCT_ID_CD = 'EM' left outer join
						 (select CLI_CNTCT_ID_CD,CLI_ID,CLI_CNTCT_ID_TXT,IS_CURRENT,MAX(PREV_UPDT_TS) PREV_UPDT_TS from DLKHDIM.dbo.DIM_CLIENT_CONTACT group by CLI_CNTCT_ID_CD,CLI_ID,CLI_CNTCT_ID_TXT,IS_CURRENT) 
						AS CT ON C.CLI_ID = CT.CLI_ID AND CT.IS_CURRENT = 1 AND CT.CLI_CNTCT_ID_CD = 'CP' 

WHERE        (P.POL_CSTAT_CD IN ('1'))
