

CREATE VIEW [dbo].[V_TEAM]
AS
SELECT T.PartyId PARTY_ID,T1.TeamType TEAM_TYPE,T1.TeamNo TEAM_CODE_1,T1.Name TEAM_NAME_1,
T2.TeamNo TEAM_CODE_2,T2.Name TEAM_NAME_2,T3.TeamNo TEAM_CODE_3,T3.Name TEAM_NAME_3
,T4.TeamNo TEAM_CODE_4,T4.Name TEAM_NAME_4
,T5.TeamNo TEAM_CODE_5,T5.Name TEAM_NAME_5
,T6.TeamNo TEAM_CODE_6,T6.Name TEAM_NAME_6 FROM DLKHDIM..DIM_AGENT T INNER JOIN  DLKHDIM..DIM_TEAM T1 ON T1.PartyId=T.ReportsTo AND T1.IS_CURRENT=1 AND T.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_TEAM T2 ON T1.ReportsTo=T2.PartyId AND T2.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_TEAM T3 ON T2.ReportsTo=T3.PartyId AND T3.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_TEAM T4 ON T3.ReportsTo=T4.PartyId AND T4.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_TEAM T5 ON T4.ReportsTo=T5.PartyId AND T5.IS_CURRENT=1
LEFT JOIN DLKHDIM..DIM_TEAM T6 ON T5.ReportsTo=T6.PartyId AND T6.IS_CURRENT=1
